### ISSUE TITLE
Vagrant との連携

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1]
Vagrant を利用して、簡単に開発環境を構築できるようにする

### See Also.

<https://github.com/nanasess/vagrant-lamp>

**Comment by shinichi-takahashi** [comment]
本件、submoduleとしてVagrantfileを同梱するのとを検討するため、再度開きました

**Comment by nanasess** [comment]
cookbook も submodule にしたいです

**Comment by Yangsin** [comment]
CookbookまでSubmodule化すると、Cookbook側の変更でVagrantが動かなくなりChef等でになれない方は戸惑うとおもうので、まずは、Cookbookは取り込んでいる状態の以下のリポジトリをSubmoduleとして追加する方向です進めます。

https://github.com/poego/vagrant-centos6-eccube

**Comment by nanasess** [comment]
> CookbookまでSubmodule化すると、Cookbook側の変更でVagrantが動かなくなりChef等でになれない方は戸惑うとおもうので、

submodule で参照しているディレクトリもコミットしておけば、予期せぬ変更を勝手に取り込んで、動かなくなることは無いです
<http://qiita.com/sotarok/items/0d525e568a6088f6f6bb>

**Comment by nanasess** [comment]
config.omnibus.chef_version = :latest

これはバージョン指定しておいた方が無難かなと思います

**Comment by nanasess** [comment]
あと、 個人のリポジトリではなく、 github.com/EC-CUBE 以下にリポジトリを作りませんか？
その方がチームで作業しやすいかなと。

**Comment by shinichi-takahashi** [comment]
PR!!PR!!!!

**Comment by shinichi-takahashi** [comment]
あ、リポジトリかorz
失礼いたしました。

**Comment by Yangsin** [comment]
@nanasess さん
https://github.com/EC-CUBE/eccube-vagrant
として用意してみましたので、思われているところをPRいただいてもよろしいでしょうか。

Vagrant側のリポジトリのイメージが固まったら改めて本体にPRしたいとおもうので、先のPRは一度クローズしました。

    config.omnibus.chef_version = :latest
は、確かにバージョン決めたほうがよさそうですね。
今のところ最新の12.2.1で動作確認されてます。

**Comment by nanasess** [comment]
:+1:

**Comment by nanasess** [comment]
[EC-CUBE/eccube-vagrant](https://github.com/EC-CUBE/eccube-vagrant) で改善を進めているためクローズします
