### ISSUE TITLE
ER図

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#10]
まずは 2.13.x ベースのものを追加

**Comment by shinichi-takahashi** [comment]
@nanasess 
ありがとうございます！

こちら（document labelがついているもの）はリリースまでは継続して変更していくものとなりますので、
このissue自体は残しておきます。

**Comment by Yangsin** [comment]
#48 でテーブル定義書の議論がありますので、こちらのメンテナンスについてもそちらに移させていただき、一度Issueクローズしますね。
