### ISSUE TITLE
#670 商品一覧の表示件数とページングの不具合に対する調査結果とヘルプ依頼

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1015]
■前置き
「Paginator」には問題がありませんでした。

■原因
①Doctrineのクエリビルダーで「Offset」「Limit」をかけ結果取得をすると
「ProductClass」に対して「Offset」「Limit」を取得し、「DISTINCT」を
行うため、重複値分、取得結果が減る。
------------------------以下参考(プロファイラーの結果)-----------------------
[price02 ASC]
SELECT 
  DISTINCT d0_.product_id AS product_id0, 
  d1_.price02 AS price021 
FROM 
  dtb_product d0_ 
  INNER JOIN dtb_product_class d1_ ON d0_.product_id = d1_.product_id 
  AND (d1_.del_flg = 0) 
WHERE 
  (d0_.status = 1) 
  AND (d0_.del_flg = 0) 
ORDER BY 
  d1_.price02 ASC 
LIMIT 
  15 OFFSET 0

SELECT 
  DISTINCT d0_.product_id AS product_id0, 
  d0_.name AS name1, 
  d0_.note AS note2, 
  d0_.description_list AS description_list3, 
  d0_.description_detail AS description_detail4, 
  d0_.search_word AS search_word5, 
  d0_.free_area AS free_area6, 
  d0_.del_flg AS del_flg7, 
  d0_.create_date AS create_date8, 
  d0_.update_date AS update_date9, 
  d0_.creator_id AS creator_id10, 
  d0_.status AS status11 
FROM 
  dtb_product d0_ 
  INNER JOIN dtb_product_class d1_ ON d0_.product_id = d1_.product_id 
  AND (d1_.del_flg = 0) 
WHERE 
  (
    d0_.status = 1 
    AND d0_.product_id IN (?)
  ) 
  AND (d0_.del_flg = 0) 
ORDER BY 
  d1_.price02 ASC

Parameters: [["3","4","5","6","7","8","9","2","10","11","12","13","14","15","16"]] 

[price02 DESC]
SELECT 
  DISTINCT d0_.product_id AS product_id0, 
  d0_.name AS name1, 
  d0_.note AS note2, 
  d0_.description_list AS description_list3, 
  d0_.description_detail AS description_detail4, 
  d0_.search_word AS search_word5, 
  d0_.free_area AS free_area6, 
  d0_.del_flg AS del_flg7, 
  d0_.create_date AS create_date8, 
  d0_.update_date AS update_date9, 
  d0_.creator_id AS creator_id10, 
  d0_.status AS status11 
FROM 
  dtb_product d0_ 
  INNER JOIN dtb_product_class d1_ ON d0_.product_id = d1_.product_id 
  AND (d1_.del_flg = 0) 
WHERE 
  (
    d0_.status = 1 
    AND d0_.product_id IN (?)
  ) 
  AND (d0_.del_flg = 0) 
ORDER BY 
  d1_.price02 ASC

Parameters: [["3","4","5","6","7","8","9","2","10","11","12","13","14","15","16"]] 
------------------------(プロファイラーの結果)-----------------------

■問題点
①Dctrineベースで、「GROUP BY」「DISTINCT」なし、チェーンメソッドの
順番を変えても、結果は同じとなる。
②サブクエリを用い、「DISTINCT」後に「LIMIT」「OFFSET」を設定を行う事として、
クエリビルダーでSQL生成を試みたが「FROM (SELECT ～」を行うと、FROMの後が
「Entity」でないため、エラーとなる。

■仮対応と問題点
①問題点を踏まえ、直接SQLハードコーディングし発行している。
②また①の結果取得が配列のため、なんらかの形でオブジェクトを
取得しなおす(もしくはマッピング)する必要がある。
③①②からメンテナンス性にかける上、ロジックが無駄に複雑になる。

■結論
みなさん知恵をお借りしたいです。

■備考
現状は仮対応で実装を進めていきます。
みなさんの意見をいただき、リファクタリングしたいと思います。

**Comment by chihiro-adachi** [comment]
#670

**Comment by nanasess** [comment]
配列をオブジェクトにマッピングするのは AbstractEntity::setPropertiesFromArray() でできます。
Doctrine のオジェクトにはならないのが難点ですが。

根本的には Paginator の拡張を独自に作る or 別の実装を探さないといけない気がします。

**Comment by nobuhiko** [comment]
価格順で並び替える場合って、商品のどの価格で並び替えるのかも考えないとおかしな結果になるような

**Comment by ttsuru** [comment]
これ、ただ、countQueryを別でsetするだけでいけますよ。
countQueryの場合だけ、orderbyを削除してあげるだけです。

**Comment by ttsuru** [comment]
https://github.com/KnpLabs/KnpPaginatorBundle/blob/master/Resources/doc/manual_counting.md
こちらに Manual counting のドキュメントがあります。
僕の方でも見てみます。

**Comment by geany-y** [comment]
@nanasess
@nobuhiko
@ttsuru

みなさんコメント有難うございます。
仮実装に夢中になり気づきませんでした。
一応身の毛もよだつ様な、残念な実装を終えました。
有難う御座いました。

@ttsuru
有難うございます。
ドキュメントの方も確認してみます。
もう少し、本スレッドをあたためて、その後リファクタリングかけます。

**Comment by chihiro-adachi** [comment]
@geany-y 
`array('wrap-queries' => true)`でいけるか見ていただけませんか。いちおう手元の環境ではちゃんと動いているように見えるのですが。

https://github.com/EC-CUBE/ec-cube/commit/25593c3fe1389120045645c5af6329680e8c36ee

**Comment by geany-y** [comment]
@chihiro-adachi
有難うございます。
ご提案の方法でこちらの環境でも、バグでません。
あれこれ時間をかけたわりには、あっさりで、ある意味残念ですが、
これでCloseできそうですね。
助かりました。

他のページネートで問題がある箇所も進めて参ります。

**Comment by chihiro-adachi** [comment]
#1034 #1035
