### ISSUE TITLE
EC-CUBE3.0.4 カスタマイズしたadminテンプレートが読み込めない

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#1016]
開発フォーラムで投稿がありました。
フォーラムにも書かれている通り、設定ファイル読込に変更した結果
設定されている定数値に誤りがあるようです。
記述ミスなのか、意図的に変更したものかどうか他の修正等を確認する必要がありそうです。

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&order=ASC&topic_id=16504&forum=12

**Comment by chihiro-adachi** [comment]
#1017 にて修正
