### ISSUE TITLE
eccube_install.sh の HTTP(S)_URL のデフォルト値

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#102]
- test.local ではなく [eccube-vagrant](https://github.com/EC-CUBE/eccube-vagrant) に合わせる、もしくは localhost のように汎用的なホスト名とする、もしくは必須入力とする。
  - #62 のようなトラブルに苦しむ人がいるので。。。
- ```HTTP_URL``` の最後に **/** が無い

**Comment by Yangsin** [comment]
- ```HTTP_URL``` の最後に **/** が無い  
については修正がはいっていますので、一度クローズさせていただきます。
URLの修正に関しては引き続きのため、別途インストールシェルの調整として、 #179 課題を送ります。
