### ISSUE TITLE
【改善要望】受注登録の会員検索時、検索結果が多い場合表示件数を絞って欲しい。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#1024]
■対象画面・機能
受注登録画面の会員検索機能
■現状の動作
会員検索のポップアップウィンドウで「検索」ボタン押下時、
（検索結果数が大量の場合も）全件表示されてしまう。
→ 数万件などの場合、ブラウザがクラッシュしてしまう危険性あり。
■想定の動作
会員検索のポップアップウィンドウで「検索」ボタン押下時、
100件くらいのみ表示し、条件を絞ってもらう旨のメッセージを表示してほしい。

以下、画面・機能にも同様の対応が必要であると考えられます。
■受注登録画面
　・会員検索
　・商品の追加
■商品登録画面
　・規格登録

**Comment by Yangsin** [comment]
#1917 で重複しており、そちらで改善が進んでいるためクローズします。
