### ISSUE TITLE
受注キャンセル時に会員データの最終購入時間・購入回数・購入金額等が更新されない。

### ISSUE THREAD

**Issue by yuh2** [EC-CUBE/ec-cube#1025]
受注キャンセル時に会員データの最終購入時間・購入回数・購入金額等が更新されない。

src/Eccube/Service/OrderService.php：：setCustomerUpdate

        $user->setBuyTimes($user->getBuyTimes() + 1);
        $user->setBuyTotal($user->getBuyTotal() + $Order->getTotal());
となっているので、取得するデータの信頼性が無い気がします。

**Comment by chihiro-adachi** [comment]
#1190 で対応.
