### ISSUE TITLE
dtb_order.pre_order_id のインデックス

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1036]
`dtb_order.pre_order_id` にインデックスを付与するべき。
また、ユニーク制約も必要と思われる。

**Comment by flickertone** [comment]
完全に異なる、新規のorderであるはずが、注文確定時に既存のorderを上書きしてしまうという事象を確認しました。

新規の注文時、購入処理中はorder_id=2であった注文（idは仮です）が、注文確定と同時に、既存の注文であるorder_id=1の情報を上書きするかたちで、登録されてしまう事象がありました。

上記２つのorder_idは、pre_order_idが、完全に重複しておりました。
pre_order_idはuniqでないと問題が発生するのではないかと認識しているのですが、いかがでしょうか。
