### ISSUE TITLE
【ヘルプ依頼】管理画面:受注管理 > 受注登録画面 エラーについて

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1040]
■以下エラーが表示され表示されません。
どなたか詳しい方ヘルプください。
管理画面: 受注管理 > 受注登録画面 / admin/order/new
ClassNotFoundException in SerializerServiceProvider.php line 41:

**Comment by k-yamamura** [comment]
composerを更新していますのでmasterから最新とってきた際は、
 ``` php composer.phar install --dev --no-interaction ```
で更新をお願いします。

**Comment by geany-y** [comment]
有難う御座います。
助かりました。
