### ISSUE TITLE
【仕様検討】商品登録時にカテゴリ選択がされていない際に確認が必要か

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1042]
■以下イシューへの書き込みの件です

https://github.com/EC-CUBE/ec-cube/issues/797
----------------------------------------------------------------------------------
@seasoftjapan
私も、カテゴリーを割り当てたくないこと時折ありますね。
反面、選択忘れをアラートされて救われるケースも。。
----------------------------------------------------------------------------------
@nobuhiko 
商品マスターの一覧画面で、赤色でカテゴリー選択されてないことをお知らせするとか
----------------------------------------------------------------------------------

以上について、カテゴリ未選択に対しての何かしらのアクションが必要でしょうか。

**Comment by Yangsin** [comment]
議論が分散してしまいますので、元のIssueにそのままコメントいただければ十分ですのでこちらはクローズします。
