### ISSUE TITLE
商品CSVアップロードができない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1044]
htmlタグ(tableタグなど)がCSVファイルの本文中に含まれていた場合、
CSVアップロードできない。

原因と対処方法は以下を参照。
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16511&forum=10&post_id=73042#forumpost73042

**Comment by chihiro-adachi** [comment]
#1047 にて対応.
