### ISSUE TITLE
IE11 で商品詳細画面の規格2表示不具合

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1088]
IE11 では、1回クリックしたのみでは、規格2のプルダウンが展開されない(「選択してください」という表示のまま)
2回目のクリックで、正常に展開される

**Comment by Yangsin** [comment]
JavaScriptの読み込みが影響しているかも？手元のIE11でも初回表示時だけ発生することが確認できました。

**Comment by trebla-on** [comment]
ie11場合はこんな問題よくありますみたい、一部対応しましたのでこちらのご確認お願いします
http://ec-cube-trebla2.herokuapp.com/products/detail/1
対応されてない環境はこちらです
http://ec-cube-trebla1.herokuapp.com/products/detail/1
※ちなみに自分のPC（windows10&ie11）場合は一回でもこの問題発生してなかったです。

**Comment by trebla-on** [comment]
以下のパターンを確認しましたがいつもオプション出ました、
■Windows7 IE11
■Windows8 IE11
■Windows10 IE11

**Comment by t-nagahashi** [comment]
再現方法が不明確のため、一旦マイルストーンを変更します。

**Comment by nanasess** [comment]
以下で修正されている可能性があります。
https://github.com/EC-CUBE/ec-cube/pull/1756

**Comment by nanasess** [comment]
#1756 で修正済み
