### ISSUE TITLE
受注管理での商品追加で、在庫数が減らない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1095]
商品を追加しても在庫が減らない。
2系では、商品を追加した場合在庫が減少する

**Comment by t-nagahashi** [comment]
本件、#1094 とあわせて、対応方針考えたいと思います。

まずは、修正前に以下仕様のドラフトを作成します。
・各ケース（操作）における、2系・3系での現状の挙動を整理
・仕様の検討

**Comment by kiy0taka** [comment]
#2084 で仕様をまとめましたのでこちらはクローズします。
