### ISSUE TITLE
【管理画面】コンテンツ管理 > ページ管理 > 新規入力画面テーブル「URL・ファイル名」レイアウト崩れ

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1097]
主題画面で、以下項目が長い文字の場合、画面の外に(右方向)文字がはみ出しスクロールバーを横に操作すると全体のレイアウトが崩れて表示される。
※word-breakなどの指定が必要??

**Comment by chihiro-adachi** [comment]
#1187 で対応.
