### ISSUE TITLE
【ユーザー画面/商品購入】カートに商品が追加されない事がある

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1099]
ユーザー画面から以下フローで商品購入を行った場合、最後の商品がカートに追加されない。
※他2端末で検証をしたが未再現

1. カートに規格なし商品を2件投入(別商品を投入)
2. カートに購入販売制限「1」・在庫「2」の規格あり商品を投入
→2の商品が追加されない(エラー表示なし)

**Comment by chihiro-adachi** [comment]
再現性なし、ということでクローズさせていただきます。
