### ISSUE TITLE
mod_rewriteを標準では使わないようにした方がいいんじゃないでしょうか？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1103]
フォーラムを見ているとmod_rewriteで詰まるひとが多いようなので、標準はindex.phpでアクセスするようにしておき、wordpressのように管理画面から動作を変更できるようにした方が親切なのではないでしょうか

**Comment by ttsuru** [comment]
index.php/なんたら
でもアクセスできるので、Symfonyのように少しテンプレートの書き方を変えたら動くような気がします。

**Comment by nanasess** [comment]
管理画面から設定できるようすれば、 #558 の互換性の問題とかもうまくできそうですね。

**Comment by k-yamamura** [comment]
こちらの対応方針ですが、

ドキュメントルートをEC-CUBEルート直下に設定するものとして、
レンタルサーバによってはindex.phpをつけないと動作しないという環境もありますので、
* EC-CUBEデフォルトURLは ``` http://xxxxx/html/index.php ```

管理画面の設定で、
* index.phpを付けたり無くしたりの設定が可能
* URLを自由に付けれるように(htmlを無くしたり、storeのように別のurlにしたり)管理画面から設定できるようにする

対応方法としては下記のどちらかで対応可能かどうかを検討
* .htaccessのみで対応
* ディレクトリを移動させる

として考えています。

レンタルサーバによっては当然動作しない環境も出てくると思いますが、
修正方針としてこうした方が良いなどのご意見を聞かせて頂ければ幸いです。

**Comment by ttsuru** [comment]
@k-yamamura 

> index.phpを付けたり無くしたりの設定が可能

これは、設定をしなくてもSymfonyのように挙動できるのではないでしょうか。

**Comment by ttsuru** [comment]
ほとんどの場合は、index.php と vendor/ のディレクトリの位置関係だけで、環境変数でどうにかできるはずです。

**Comment by ttsuru** [comment]
.htaccess なしかつ ROOT直に index.php だと環境として危険じゃないですかね・・・

**Comment by k-yamamura** [comment]
@ttsuru 
ご指摘ありがとうございます。

apacheが前提となりますがレンタルサーバによっては
```
DirectoryIndex
```
が使えないところがあり ``` index.php ``` をつけないと動かないため、
デフォルトでは ``` index.php ``` を有効にしようと考えていました。
本来であれば ``` DirectoryIndex ``` が使えればこのような事を考えなくても良いのですが。

ご指摘いただいた内容も含めて回避方法がないかもう一度調べてみます。

**Comment by nobuhiko** [comment]
レンタルサーバーが .htaccess なしかつ ROOT直に index.php じゃないと動かない以上そこにあわせていかないと、バッドノウハウで危険なものが巷にあふれるだけな気がします

> EC-CUBEデフォルトURLは http://xxxxx/html/index.php

html が標準で付く状態はsrcやappにアクセスも出来てしまう状況なのでおかしな状況な気がします

**Comment by ttsuru** [comment]
@nobuhiko 
僕も同意見です。
ECサイトとして不適切なインフラだけでも排除したほうがいいと思います。

**Comment by nanasess** [comment]
Magento や Drupal など競合製品は ROOT 直下に index.php があるので、同様に、適切に .htaccess が設定されていれば良いと思いますけどね。
mod_rewrite が使えない(FollowSymlinks が無効)なレンサバは多そうですが、 Deny も無効になっているような環境がどれだけあるかは、調べないとわからないですね。

https://github.com/drupal/drupal
https://github.com/magento/magento2

**Comment by Yangsin** [comment]
html がつかないURLで安全に運用できるようにしたいですね。

1) http://hogehoge.net/
 html がドキュメントルートとして設定されているイメージ）
や
2) http://hogehoge.net/store/
 store/html、store/src みたいな配置になっているものを .htaccess とmod_rewriteでゴニョゴニョするイメージ。

でしたが、もろもろご意見みてますと 2のほうの対応が不十分な状況であることと、mod_rewriteが使えない環境でどう動かすかという課題で
前提条件のレンタルサーバーの要件が未設定だと思いますので、

まずは、以下のように定めさせてください

* .htaccess のDenyが利用できないような環境はNG 
* .htaccess の中で mod_rewrite が使えない環境は動作環境として認める
* .htaccess のみならず、 IISのweb.configも同様の条件とする

なお、今のところ3系の動作検証をロックオンでおこなったサーバーでこの条件に合致しないようなサーバーはありませんでした。

この環境下で

* html がつかないURLで安全に運用できる
* 現在利用しているEC-CUBE3のサイトがアップデート対応できる

ような改善が行えれればと思います。

ちなみに、当初のディレクトリ構成でも近しい議論があったので、参考までに。
https://github.com/EC-CUBE/ec-cube/issues/201

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
