### ISSUE TITLE
EC-CUBEバージョンアップ方法の見直し

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1110]
3.0.5で不要となったファイルやライブラリがsrcやvendorディレクトリを上書きしただけでは残りっぱなしになる。
migration時に適切に対象となるファイルを削除するのが正しい?

**Comment by Yangsin** [comment]
ファイルを勝手に削除してしまうというのも問題になりえるので、バックアップをどこかに作るとかでしょうか・・・
Discussionとしてご意見募集します。

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
