### ISSUE TITLE
本番運用時のtwigファイル変更時の反映について見直し

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1113]
本番環境だとtwigファイルを変更して反映する場合、
cacheディレクトリにあるtwigディレクトリを削除するか、
app/console cache:clear
とコマンドを叩いて反映させるしか方法はありません。

お手軽にtwigファイルを反映させる方法を検討。

**Comment by nanasess** [comment]
Merged from #1306
