### ISSUE TITLE
プラグイン用管理画面のデザインについて

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1114]
プラグイン用の管理画面を作成時に別ウィンドウが開くが、
現行のdefault_frame.twigをそのまま流用すると左メニューやヘッダーが表示されます。

JavaScriptで左メニューやヘッダーを制御して隠すことは可能ですが、
そもそも不要だと思われますのでプラグイン用の管理画面default_frame.twigを作成する必要があります。

**Comment by shhirose** [comment]
そもそも別ウィンドウにする必要ってあるんでしょうか。
左メニューとプラグインの設定リンクのURLを同じにしても良い気がするので同一ウィンドウで良いのではないでしょうか。

**Comment by ttsuru** [comment]
:+1: 
個人的にはWordPressっぽい感じでいいような・・・

**Comment by okazy** [comment]
プラグイン設定画面は同一ウインドウで開くようになりましたのでこちらはクローズします。
