### ISSUE TITLE
配送方法・支払い方法を一度全部消すと登録できない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1117]
開発コミュニティもある通り、
配送方法・支払い方法を全て消した後、新規登録しようとするとエラーになる。
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16557&forum=9&post_id=73150

他の機能も問題がないのか要確認。

**Comment by chihiro-adachi** [comment]
#1130 で対応.
