### ISSUE TITLE
商品一覧ページの商品が価格昇順にソートされない

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1118]
本件、以下で解決していたはずでしたが、主題の通り、価格順のソートの際は、
正しく昇順で表示されません。
※proice02に対して「order」していますが、集約関数を使用していなため、
正しくソートされていないと思われます。

https://github.com/EC-CUBE/ec-cube/issues/670
商品マスターで商品一覧した時の表示件数が違う #726
会員マスター管理画面で2ページ目以降の検索結果が0になってしまう #737
Dev y master / yoshinaga #954
#670 商品一覧の表示件数とページングの不具合に対する調査結果とヘルプ依頼 #1015
#670 商品一覧の表示件数とページングの不具合 #1034
#726 商品マスターで商品一覧した時の表示件数が違う #1035

私がこのまま対応にあたります。

**Comment by geany-y** [comment]
以下にPULLしています
https://github.com/EC-CUBE/ec-cube/pull/1129

**Comment by chihiro-adachi** [comment]
#1129 にて対応.

**Comment by k-yamamura** [comment]
MySQLの場合、
ONLY_FULL_GROUP_BY
が設定されているとこの対応ではエラーが発生します。
確認方法は、
select @@sql_mode;
を実行し、
ONLY_FULL_GROUP_BY
が含まれているを確認してください。

**Comment by chihiro-adachi** [comment]
#1197 にて対応.
