### ISSUE TITLE
[管理画面テーマ] テキストエリアが小さく入力しずらい。

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1122]
・商品情報入力エリア
・フリーエリア
・メールテンプレート、ヘッダ・フッタ
など

テキストエリアが小さいので、少し高くした方がよいのでは。

高さを維持する必要が無い箇所もあるかもしれないため、数パターンのクラスを用意した方がよいかもしれません。

**Comment by k-yamamura** [comment]
mergeされましたのでcloseとさせて頂きます。
