### ISSUE TITLE
[管理画面] 右上のログインユーザのプルダウン項目改善

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1126]
- 最終ログイン時刻をドロップダウンで見せる必要性が見当たらない。
  最終ログイン時刻を確認する場合は、管理者が編集者のログイン時刻を見たり、不正ログインがあるかどうかを見るためではないか？
  /admin/setting/system/member
  最終ログインを表示させる必要がある場合、メンバー管理の項目に追加しては？

また、ドロップダウンで表示させる項目は、
・ログインIDの表示（不要かな？）
・パスワード変更（メンバー編集ページヘの直リンク）
・ログアウト
かなと思いました。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
