### ISSUE TITLE
【テスト環境】fixture作成用メソッドを提供するクラスをつくる

### ISSUE THREAD

**Issue by casek** [EC-CUBE/ec-cube#1127]
現在、Unitテスト用にあるEccubeTestCaseクラスの以下のfixture作成用メソッドを、受け入れテストなど他のテスト（他のテストフレームワーク）でも利用できるように、Eccube\Utilのクラスとして独立させる。

* EccubeTestCase::createCustormer()
* EccubeTestCase::createProduct()
* EccubeTestCase::createOrder()

**Comment by nanasess** [comment]
Merged from #1662 

eccube-codeception にも Pull Request しています
https://github.com/EC-CUBE/eccube-codeception/pull/6
