### ISSUE TITLE
【受入テスト】管理画面でiframe要素にname属性をつける

### ISSUE THREAD

**Issue by casek** [EC-CUBE/ec-cube#1128]
codeceptionでの受入テスト記述上、iframe内のコンテンツにアクセスするには、iframe要素にname属性がないといけない。
管理画面の「ホーム - お知らせ」で使われているiframeにname属性をつける。
その他、別箇所でもiframeを使っているところがあれば、同等の対応が必要。

**Comment by Yangsin** [comment]
他にphpinfo()を出力している箇所でiframeを利用しています。
