### ISSUE TITLE
【受入テスト】form要素にid属性をつける！

### ISSUE THREAD

**Issue by casek** [EC-CUBE/ec-cube#1139]
例えば、/entry/confirmのform要素にはid属性がついてない。
codeceptionのwebdriverモジュールでid属性なしのform要素にアクセスしようとするとパニック！（codeceptionもしくはwebdriverのbugと思われるが...）
なので、確実にcodeceptionで受入テスト実施するために、id属性のないform要素を洗い出し、すべてにid属性をつける。

**Comment by Yangsin** [comment]
:+1:

**Comment by nanasess** [comment]
3.0.10 で対応済みですのでクローズします
