### ISSUE TITLE
【ユーザー画面 / 新規会員登録】テキストボックスにスマホの絵文字を入れてもバリデートがかからない

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1144]
まだ保存時にどうなるか調査未ですが、スマホでテキストボックスに絵文字が入力できます

**Comment by geany-y** [comment]
実際にユーザー新規登録で確認
→DBカラムに空文字が保存される
→その後編集を行うと、該当テキストボックスは空で表示

**Comment by nanasess** [comment]
おそらく、絵文字に限らず UTF-8 で 4byte 文字や、 合成文字は、すべて同様の結果ではないでしょうか。
PostgreSQL や、 MySQL でもキャラクタセットを utf8mb4 にすれば保存できるのではないでしょうか。

**Comment by geany-y** [comment]
そうですね。。。。
どうしましょうか
①仕様として絵文字を認める
→nanasessさんのと提案通り、DBのデータ形式を変更
②絵文字は認めないが、DBに空文字が入るのは困るので、
バリデートのみ行う
③放置

**Comment by nanasess** [comment]
> ①仕様として絵文字を認める
> →nanasessさんのと提案通り、DBのデータ形式を変更

utf8mb4 が使用できるのは MySQL 5.3.3 以降なので、 MySQL 5.1.x は対応できなくなってしまいます。
Doctrine でうまいことできるのでしょうかね。

> ②絵文字は認めないが、DBに空文字が入るのは困るので、バリデートのみ行う

絵文字に限らず、 4byte の UTF-8 をすべて排除することになるので、 以下の文字も排除されることになってしまいます。

https://www.softel.co.jp/blogs/tech/archives/596

> ③放置

インストール時に MySQL 5.3.3 以降の場合は utf8mb4、 それ以外は utf-8 にできるのであれば、対応した方が良いと思います。

**Comment by xuelian311** [comment]
[nanasess](https://github.com/nanasess)さんから回答があり、そこからしばらく議論が進んでないため、クローズいたします。
