### ISSUE TITLE
【改善要望】受注登録時に「会員」「商品」が検索入力可能だがその度リロードがかかり使いにくい

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1145]
管理画面の「受注登録」で「会員・商品」を検索→入力できるが、その際に画面がリロードし、商品を入力していたのに画面の上までスクロールを強制され、使い勝手が悪く感じる

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
