### ISSUE TITLE
【受入テスト】ブラウザのalertをやめる

### ISSUE THREAD

**Issue by casek** [EC-CUBE/ec-cube#1146]
削除などのアクション時にブラウザのalertで確認を求める部分が多い。
受入テストで採用しているphantomJSはalertをサポートしていないのでテストできない。
Selenium2はサポートしているが、、、
- Selenium2は遅すぎて受入テストに向かない
- alertをbootstrapのwindowに置き換えてphantomJSでテストできるようにしたい
- そもそもalertポップアップ、UI的にどうなの？というのもあるようなないような。。

という理由で「置き換え」実施したい。

現時点では、alert利用部分の受入テストコードは省略しとく。
「置き換え」実施されたらテストコード追加するのがいい。
該当箇所には「/\* ToDo: popup */」とコメント入れておく。

**Comment by Yangsin** [comment]
ユーザーに確認の求めるに、アラート以外のいい方法があって、既存のプラグインとかに影響がないなら置き換え実施もできますが、今のところアラート以外には、いちいち画面遷移するとかになってしまいそう・・・

**Comment by casek** [comment]
あ、bootstrapはwindowじゃなくてmodalって呼ぶんだったw
これ、現在loadしてるbootstrap.customにも含まれてますよね？
これでいいのでは？と思っとります。

**Comment by casek** [comment]
ちなみに
http://getbootstrap.com/javascript/#modals
です

**Comment by Yangsin** [comment]
管理画面UIの見直しなどで一部対応可能なものについては検討します。

**Comment by okazy** [comment]
管理画面は4.0対応でアラートをモーダルへ変更しています。

phantomJSを使っていないのでクローズします。
