### ISSUE TITLE
3.0.3から3.0.5へアップデートした際に既存会員でご注文内容のご確認に遷移するとエラーになる

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#1154]
[PHP]   5.4.45
[データベース]    MySQL 5.6.21 
[WEBサーバ]  使用しているWEBサーバ名、バージョン
[ブラウザ]  Apache 
[現象]  
1.　EC-CUBE3.0.3を入れ会員登録を行います。
2.　EC-CUBEを3.0.5にアップデートします
　　下記の方法で行いました。
　　http://ec-cube.github.io/update.html
3. カートに商品を入れ、「ご注文内容のご確認」画面に遷移するとエラーになる

原因：$CustomerAddressが取得できないため

EC-CUBE3.0.5では会員登録と同時にお届け先に登録された会員が追加されますが、
EC-CUBE3.0.3では追加されていないためエラーが発生します。

**Comment by chihiro-adachi** [comment]
注文確認画面の表示、注文完了できることを確認しました。
#1158 で修正できているようなのでクローズします。
