### ISSUE TITLE
運用中の支払方法などの変更に関する注意喚起を記載すべき

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1156]
カートに商品がある状態で、配送先の支払方法を変更すると、購入確認画面へ遷移するとシステムエラーが発生する。
また、購入確認画面で配送先の支払方法を変更すると、本来は選択できないはずの支払方法が選択できるようになってしまう。

ロジック内で制御せず、運用でのカバー（メンテナンス状態にしてから変更させる）で問題はないと思うが、そのような注意喚起の記載が必要と思われる。

**Comment by nanasess** [comment]
#1158 で修正いただきましたのでクローズします。
