### ISSUE TITLE
ShoppingService の問題点

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1160]
- CartService, OrderService に依存している。 Cart エンティティのインスタンスを渡すのはありだと思うが、 サービスに依存すべきではない
- サービスクラスは、ステートレスが基本なので、セッションに依存すべきではない。
- Order に関連するエンティティを生成したり、集計するメソッドがいくつか存在するが、多くはエンティティ内に処理を移譲可能
- 上記の問題のため、フロント側と、管理画面側での処理の抽象化が困難になっている。集計や、 Order エンティティを抽象的に扱うサービスクラスを別途作成するべき。
- `copyTo*` は、 `Entity::copyProperties()` で代替可能

**Comment by chihiro-adachi** [comment]
PusrchaseFlow等に抽象化されたため、クローズします。
