### ISSUE TITLE
仮会員登録時のリンクの有効期限を設定したほうがよい

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1168]
パスワード再発行と同じように、仮会員の secret_key も有効期限を設けたほうがよい。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
