### ISSUE TITLE
【仕様の確認】管理画面－メール管理の仕様についての確認

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/ec-cube#1169]
管理画面－メール管理の仕様について確認をしたいのですが、

画面上の「テンプレート」項目が「件名」の同じ内容が表示されるように「3.0.4」か「3.0.5」のバージョンで変わったようですが、今後この仕様で進むのでしょうか？

確認した限りだとissueに「テンプレート」項目が「件名」の内容を表示するような仕様変更に関する内容が無かったので教えてください。

ご確認の程、よろしくお願い致します。

**Comment by Yangsin** [comment]
開発終了となった3系の質問で議論も進んでいないため、クローズさせていただきます。
