### ISSUE TITLE
インストーラ使ったインストールを行うと管理画面ログインできない

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#117]
ざっと作ったため、管理画面にログインできない状態です。
近々直しますので、開発されている方はそれまでeccube_install.shでインストールしてください。

**Comment by nobuhiko** [comment]
インストーラーからeccube_install.sh叩けばいいんじゃ・・

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
それも考えたんですが、Doctrineのschema-toolつかおうかな、とかとか考えてまして・・・。

**Comment by Yangsin** [comment]
かなり状況がかわっていると思いますので、ひとまずクローズします。
