### ISSUE TITLE
site.logのローテーションについて

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1170]
現状、site.logは日付ごとにsite_2015-10-28.logのようなファイルが作成されるようになっているように思いますが、site.log自体はどんどん大きなファイルになっていっていませんか？

**Comment by nanasess** [comment]
なってますね :worried: 
ちょうどログまわりの改修をしているので見てみます。

**Comment by nanasess** [comment]
Merged from #1179
