### ISSUE TITLE
会員登録時にメールの受信に失敗するとそのメールアドレスが使用できなくなる

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1178]
会員登録時、変更時に仮会員のメールアドレスに対しても重複チェックをしているため、たとえば仮会員登録完了メールの受信に失敗すると、2度とそのメールが使用できなくなる。

仮会員のメールアドレスは重複チェックの対象から外し、本会員登録時、会員情報変更時にアクティブな重複メールアドレスがないかチェックするように修正する必要がある。

仮会員登録： 同じメールアドレスで複数回の登録可。ただし、本会員のメールアドレスとの重複は不可
本会員登録： 本会員のメールアドレスと重複していないかどうかのチェックを行う。
会員情報変更： 本会員のメールアドレスと重複していないかどうかのチェックを行う。

**Comment by Yangsin** [comment]
ぱっと見ですが以下の懸念を感じました。

* 顧客管理の画面で、仮会員の状態でメールアドレスが重複した会員データが残り続けてしまうと、邪魔じゃないか。特にメールアドレスで会員検索を行ったさいに複数類似したデータがでてくると、かなり邪魔なデータになりそう
* 仮会員→本会員の認証時に同じアドレスで仮会員のままになっている他のアドレスをどう扱うべきか？

**Comment by shhirose** [comment]
> * 顧客管理の画面で、仮会員の状態でメールアドレスが重複した会員データが残り続けてしまうと、邪魔じゃないか。特にメールアドレスで会員検索を行ったさいに複数類似したデータがでてくると、かなり邪魔なデータになりそう

#1168 で Issue を上げていますが、仮会員にも有効期限を設けるべきだと思います。
その有効期限で制限をかければよいと思います。

> * 仮会員→本会員の認証時に同じアドレスで仮会員のままになっている他のアドレスをどう扱うべきか？

有効期限を設けるなら放置で良いと思います。
設けないのであれば本会員登録された段階で、同一メールアドレスは削除扱いにする必要がありますね。

**Comment by shhirose** [comment]
> #1168 で Issue を上げていますが、仮会員にも有効期限を設けるべきだと思います。
> その有効期限で制限をかければよいと思います。

修正範囲が大きくなるので、削除扱いにしたほうが無難ですね。


キャリアメールを使用している方に多いですが、指定受信をしていないためにメールを受け取れないということは頻繁に起こるので、対応しないというわけには行かないかと思います。

**Comment by ttsuru** [comment]
もう一度仮会員登録したらメールが送信される形でいかがでしょうか。
Eccube\Entity\Customerに唯一存在するValidatorをForm側に移動できれば一番簡単かと思います。

**Comment by shhirose** [comment]
@ttsuru 
> もう一度仮会員登録したらメールが送信される形でいかがでしょうか。
それでもいいかもしれませんね。

ちなみにメールアドレスの重複チェックは`Eccube\Entity\Customer`でやっているのでしょうか？
理由はわかりますか？

**Comment by ttsuru** [comment]
@shhirose 
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Entity/Customer.php#L285
こちらですね。
理由はおそらくFormでのValidationの実装がわからなかったんじゃないかなと思います。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
