### ISSUE TITLE
管理画面に http:// でログインしていると、顧客に送信するメールの URL が http:// になってしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1201]
例えば、仮会員登録メールなど、 https:// を強制したい場合に意図しない結果となってしまう。

不具合ではないが、何らかの注意喚起をしておきたい。
(ロードバランサーを使用した場合など、 https:// の判定が難しくなるケースもある)

関連 #703

**Comment by xuelian311** [comment]
#703 でコメントされている通り、http:// と https:// で異なるサブドメインへのインストールはサポートされなくなったということで、こちらのissueも解決済みとしてクローズします。
