### ISSUE TITLE
デフォルトのお届け先の編集

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1202]
Myページから、デフォルトのお届け先を編集すると、購入フローで再編集できなくなってしまう。
デフォルトのお届け先は、会員情報と同一としておいた方が良いのではないか。

また、管理画面から会員情報を編集しても、お届け先に反映することができない。

**Comment by ttsuru** [comment]
チケットありがとうございます。
マイページで住所を変えたのに配送先が違うままというミスが非常に多く出てきそうな気がします。

なので、こちら早めに対応した方がよさそうですね。
また、マイグレーションも必要になりますね・・・

**Comment by k-yamamura** [comment]
住所が編集されるパターンですがこのような感じでしょうか。

1. 会員住所を変更 → お届け先住所に ``` 反映する ```

2. お届け先住所を変更 → 会員住所には ``` 反映しない ```

3. 商品購入後(配送前)に会員住所を変更 → お届け先住所に ``` 反映する ```、受注情報(dtb_order)とお届け先情報(dtb_shipping)は ``` 反映する? 反映しない? ```

4. 商品購入後(配送前)にお届け先住所を変更 → お届け先住所には ``` 反映しない ```、お届け先情報(dtb_shipping)は ``` 反映する? 反映しない? ```

5. 商品購入後(配送後)に会員住所を変更 → お届け先住所に ``` 反映する ```、受注情報(dtb_order)とお届け先情報(dtb_shipping)は ``` 反映しない ```

6. 商品購入後(配送後)にお届け先住所を変更 → お届け先住所には ``` 反映しない ```、お届け先情報(dtb_shipping)は ``` 反映しない ```

**Comment by seasoftjapan** [comment]
受注情報(dtb_order)とお届け先情報(dtb_shipping)は、(少なくとも暗黙的には) 変わっちゃいけない気がします。

配送前の受注を検知して、「変わりませんよ」ってアラートすると親切だと思いますが。ま、無くても不自然には思いません。

**Comment by k-yamamura** [comment]
@seasoftjapan 
ありがとうございます。

会員情報とお届け先情報を連動させるとなるとテーブルを分けている理由が腑に落ち無くて、
整理の意味も込めて確認させてもらいました。

**Comment by okazy** [comment]
以下の方針で対応したのでクローズします。

- 注文時に、「会員住所」＆「お届け先リストの住所」からお届け先を選択できる
- お届け先のデフォルトは「会員住所」となる。
- 会員登録時にお届け先リストには追加しない

https://github.com/EC-CUBE/ec-cube/pull/3174
