### ISSUE TITLE
Session problem on PostgreSQL 9 and later. (Postgres9以降でsessionが保存されない)

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1216]
Postgresの環境によってdtb_sessionに値が正常に保存されない時があり、
管理画面ログインやカートに商品追加ができない現象が発生する。

原因は以下の通り。
https://github.com/symfony/symfony/issues/14569

回避方法として以下のSQLを実行するとsessionが正常に保存されるようになり正常に動作する。
``` ALTER DATABASE データベース名 SET bytea_output = 'escape'; ```

**Comment by nanasess** [comment]
DBセッションハンドラは、フロントエンドを冗長化しない限りは不要なので、無くても良いと思います。
また、フロントエンドを冗長化する際には、 Redis など、他の性能の優れたキャッシュ用DBを使用した方が良いと思います。

**Comment by nanasess** [comment]
#1392 にて PdoSessionHandler を使用しないようになりましたのでクローズします
