### ISSUE TITLE
twigが変更されても、キャッシュが更新されない

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1222]
通常のテンプレートシステムは、テンプレートファイルを修正すると自動的にキャッシュが更新されますが、
EC-CUBE3の場合は、twigが更新されても、自動的にキャッシュが更新されません。

こちらにデバッグモードに変更する方法がありますが、そもそもこれはバグという認識でよろしいでしょうか？
http://qiita.com/Yammy/items/868ef8325dc1a92ef06a

**Comment by nanasess** [comment]
キャッシュが更新されないのは、 Symfony2 の仕様ですね。

http://docs.symfony.gr.jp/symfony2/book/templating.html#twig

**Comment by hainey** [comment]
ありがとうございます。Symfony2 の仕様でしたら、やっぱりEC-CUBEの設定ファイルでdevかprodかの環境設定が必要ですね。

**Comment by nanasess** [comment]
開発中は、 /index_dev.php にアクセスすると、 dev の環境設定になったりしますので、ご利用いただければー
http://ec-cube.github.io/tips.html

**Comment by nanasess** [comment]
#1306 にて、管理画面よりキャッシュを削除できるようになりましたのでクローズします。
