### ISSUE TITLE
マスターデータ管理の実装

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1226]
mtb_hoge の編集を管理画面上から行うマスターデータ管理の実装

## スコープ
 
* mtb_hoge の編集のみをあつかう
* mtb_hoge のキャッシュ化については含まない

**Comment by nobuhiko** [comment]
すでに使われているkey 例えば Eccube\Repository\Master\Authority の id を編集しようとすると外部キー制約でアプリが落ちる。

**Comment by nobuhiko** [comment]
実際には使われていないテーブルが複数残っている
- mtb_country
- mtb_db
- mtb_device_type
- mtb_zip

**Comment by nanasess** [comment]
- id の編集は不可
- 同一 id 項目の編集は update 

で、良いと思います。

**Comment by ttsuru** [comment]
@nobuhiko 
get_magic_quotes_gpc の対応をautoload.phpでやるのはautoloadのファイルの意味から離れていると思います。
また、PHP 5.4で廃止になる、5.3で非推奨だと思いますが、コードで対策をする必要があるのでしょうか。

**Comment by nobuhiko** [comment]
@ttsuru どこで実装するのがいいんでしょう？

**Comment by nobuhiko** [comment]
@nanasess １回作ると削除できなくなる仕様でいいってことでしょうか？

**Comment by nanasess** [comment]
@nobuhiko 外部キー制約がかかっている場合は、削除できない。でいいと思いますが、外部キー制約をチェックできるんですかね...

**Comment by nobuhiko** [comment]
@nanasess try catchは試しましたが無理でしたね…

**Comment by k-yamamura** [comment]
@nobuhiko 
MySQLで確認を行いましたが、
```
try {
    $app['orm.em']->flush();
} catch(\Exception $e) {
}
```
で例外(ForeignKeyConstraintViolationException)のcatchが出来ていますが、
お手数ですが試されたDBとバージョンを教えてもらえないでしょうか。

**Comment by nobuhiko** [comment]
@k-yamamura 今試してみたら出来ました。なにか書き方がおかしかったみたいです
