### ISSUE TITLE
Symfony 2.8 への対応

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1228]
Symfony 2.8が間もなくリリースされますが、2.7 -> 2.8 への対応を行いますか？

メンテナンススケジュール
http://symfony.com/roadmap

・2.7
May 2015
Release

May 2018
End of support for bug fixes

May 2019
End of support for security fixes

・2.8
Nov 2015
Release

Nov 2018
End of support for bug fixes

Nov 2019
End of support for security fixes

silex本体は "~2.3|3.0.*" となっています。

**Comment by Yangsin** [comment]
いろいろと変わってますんで、影響次第ですねぇ。
http://qiita.com/issei-m/items/c108e133c42c3932b03c

2.7も2018年までBugFixがされるLTS対象なので無理に2.8にあげる必要性は感じてませんがいかがでしょうか。
2.7内での追従のほうもしないといけないですね。
http://symfony.com/blog/symfony-2-7-7-released

**Comment by ttsuru** [comment]
タイミング的には EC-CUBE 3.1 にあげる際でしょうか。
あげた際の見えるメリットは WebProfiler ぐらいですかね・・・

**Comment by chihiro-adachi** [comment]
現状では2.7.xを利用していくということで、クローズさせていただきます。
