### ISSUE TITLE
管理画面：設定＞システム情報設定＞メンバー管理

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1232]
現行のメンバー管理では権限機能が実装されておらず、権限機能を追加する。 #767

## 権限管理の変更
* メニューの非表示制御(2系ではCSSでの表示制御しかしておらず、直接URLを入力すると表示されてしまう)
* URLによるアクセス制限
* 権限ごとによるロールでの制御

### 権限管理の方法
* voterを使って実装
* dtb_authority_roleのテーブルを新規作成し、mtb_authorityで管理されている権限に対して拒否するURLを設定する(ブラックリスト方式)
* 権限とURLを制御する画面(権限管理)を追加

### 権限管理の設定方法
* mtb_authorityに対して権限を追加後、権限管理画面でURL制限を実行する

## アクセス制御が必要な機能
* システム情報設定
* オーナーズストア
* コンテンツ管理/ファイル管理

## ER・テーブル定義の変更点
dtb_authority_roleテーブルを新規作成

## 関連機能・仕様
メンバー管理 #217

**Comment by nobuhiko** [comment]
mtb_* は id, name, rank のみのテーブルとしておかないとマスターデータ管理が成り立たなくなります

**Comment by nanasess** [comment]
Merged from #1262
