### ISSUE TITLE
管理画面cssの不具合

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1240]
Pluginの開発で、管理画面で　{{ form_errors(form) }}でフォームの上にエラーメッセージを表示する際に出力されるHTMLは下記のようになっています。
<pre>
&lt;div class="alert alert-danger">
    &lt;ul class="list-unstyled">&lt;p class="errormsg text-danger">エラーメッセージ&lt;/p>&lt;/ul>
    &lt;/div>
</pre>
/template/admin/assets/css/dashboard.cssに下記のように定義していたので

<pre>
.alert-danger {
    color:#fff;
    background-color:#DE5D50;
    border-color: transparent;
}

.text-danger {
    color: #DE5D50;
}
</pre>
背景と文字が同じ色で表示してしまいました。alert-dangerをbootstrapのデフォルトに戻したほうが良いではないでしょうか？

あとalertに, margin-top: -16px;が一般的ではないので、削除したほうが良いと思います。
<pre>
.alert {
    border-radius: 0;
	margin-top: -16px;
	position: relative;
}
</pre>

**Comment by k-yamamura** [comment]
ご指摘ありがとうございます。

「背景と文字が同じ色で表示してしまいました。」
ということですがどのようなタグを記述されているのか記載してもらえないでしょうか。

また、alertに関するご指摘ですが、
今回管理画面で使用するalert componentsは、
主にalert.twigで使用しておりましたのでこのようなcss定義にしています。

Boostrap3のalertタグがこのままだと使い勝手が悪いということでしたら、
こうして欲しいというご要望を送って頂くか、
修正案をPull requestで送ってもらえないでしょうか。

ご足労お掛けしますがよろしくお願い致します。

**Comment by hainey** [comment]
HTMLコードは下記となります。

<pre>
&lt;div class="alert alert-danger">
    &lt;ul class="list-unstyled">&lt;p class="errormsg text-danger">エラーメッセージ&lt;/p>&lt;/ul>
    &lt;/div>
</pre>

alertの修正案としてbootstrapの .alert の　margin-top: -16px;を削除し、
alert.twigにinlineにstyle="margin-top: -16px;"を追加するか、top-alert というclassを追加して、
dashboard.cssに定義を追加したほうが良いかと思います。
.top-alert {
margin-top: -16px;
}

**Comment by k-yamamura** [comment]
回答ありがとうございます。

言葉足らずで申し訳ございません。
twigでどのように記述をされているか記載してもらえないでしょうか。

修正案については他の画面の影響範囲を調査した上で対応するか判断させて頂きます。

**Comment by hainey** [comment]
twigには下記のようになります。
....
{% form_theme form 'Form/bootstrap_3_horizontal_layout.html.twig' %}
....
{% block main %}
....
{{ form_errors(form) }}
....

**Comment by k-yamamura** [comment]
回答ありがとうございます。

```
<form class="form-horizontal" method="post">
    {{ form_widget(form) }}
</form>
```
と記述したとき、FormTypeにhiddenタイプが含まれていた場合、
同様の現象が再現される事を確認しました。

今回のようなケースが発生する事は稀だと思われますが、
```
<div class="alert">
    <p class="errormsg text-danger">メッセージ</p>
</div>
```
と出力されるように変更します。

ご報告ありがとうございます。
