### ISSUE TITLE
管理画面の検索条件を引き継ぐべき箇所で正しく引き継げていない

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1247]
■以下でセッションにObjectが直接書き込まれている。
管理画面の検索条件を格納している箇所では、正しい復元が出来ておらず、
検索結果がおかしい。

■該当箇所
/Admin/AdminController.php:150
/Admin/Customer/CustomerController.php:68
/Admin/Order/OrderController.php:71
/Admin/Product/ProductController.php:74:
/Admin/Product/ProductController.php:91:
/Install/InstallController.php:76:
/Service/CartService.php:113:

**Comment by ttsuru** [comment]
@geany-y 
Objectをsessionに書き込んでも問題はないはずです。
問題があるのは、Entity以外のオブジェクトをSession に保存しているか、__sleep __wakeup が正しく実装されていないオブジェクトだと思います。

**Comment by geany-y** [comment]
@ttsuru
Entity以外のオブジェクトをSession に保存→そのとおりです。
__sleep __wakeup が正しく実装されていないオブジェクト→未確認です。

入れ子オブジェクトがやられている感じです。
シリアライズ/アンシリアライズで対応考えていますが、
@ttsuru どうでしょうか??

**Comment by ttsuru** [comment]
@geany-y 
http://stackoverflow.com/questions/11857510/store-serialized-object-in-session
こちらにも記載がありますが、serialize自体はSymfony側で自動的に行うようになっています。
ですので、動作が正しくない部分があれば __sleep __wakeup が正しく実装されていれば問題ないかと思います。

**Comment by ttsuru** [comment]
あとは、こちらも関連documentですね。
http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/cookbook/entities-in-session.html

**Comment by geany-y** [comment]
@ttsuru
わざわざご丁寧に有りがとう御座います！！
恥ずかしながら知りませんでした。。
> __sleep __wakeup が正しく実装されていれば問題ないかと思います。
了解です。

リンク先参考にしながら対応にあたります！

**Comment by ttsuru** [comment]
@geany-y 
私もはまった覚えが何度もあります。

objectでも refresh(再取得) を正しく行わないと、問題になる場合がありますね。

**Comment by geany-y** [comment]
@ttsuru 
有難うございます！！
>objectでも refresh(再取得) を正しく行わないと、問題になる場合がありますね。

こちらも覚えておきます。

**Comment by geany-y** [comment]
/Admin/Customer/CustomerController.php:68
/Admin/Order/OrderController.php:71
/Admin/Product/ProductController.php:74:
/Admin/Product/ProductController.php:91:
上記については以下で解決
#1429

**Comment by nanasess** [comment]
serialize/unserialize した場合は、 EntityManager::merge($Entity); をしなければならないようです。
が、 ArrayCollection の場合は merge は解決できず、 #1429 でやっているように、 find などで再取得する必要があるようです。

**Comment by geany-y** [comment]
@nanasess 
>serialize/unserialize した場合は、 EntityManager::merge($Entity); をしなければならないようです。
>が、 ArrayCollection の場合は merge は解決できず、 #1429 でやっているように、 find などで再取得する必要があるようです。

→ありがとうございます。

以下の様な対応を考えていたのですが、却下となりました。。w
ある段階で#1429を参考に対応したいと思います。
https://github.com/EC-CUBE/ec-cube/compare/master...geany-y:1248?expand=1

**Comment by Yangsin** [comment]
#1084 と重複
