### ISSUE TITLE
画像登録時、拡張子でしかチェックをしていない為、拡張子偽装したファイルをアップできる。

### ISSUE THREAD

**Issue by SF-kitagawa** [EC-CUBE/ec-cube#1258]
[EC-CUBE] 3.0.6
[PHP] 5.6.15
[データベース] Mysql 5.6.27
[WEBサーバ] Apache/2.4.6
[ブラウザ]  google chrome 47.0.2526.73 m
[現象]
管理画面側なので問題は少ないとは思いますが、
拡張子偽装したファイルをアップできるため対応する方が良いかと思います。

**Comment by nanasess** [comment]
#1548 で修正されていますのでクローズします
