### ISSUE TITLE
Plugin開発のデザインについて

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1263]
ECCUBE3のデフォルトテンプレートはBootstrap3ですので
Plugin開発時、Bootstrapのclass名を直接使っていますが、デザインテンプレートがBootstrapベースではないことも可能ですので、Plugin開発のBootstrap classの利用はやめた方がよいでしょうか？

参考：https://github.com/EC-CUBE/ec-cube/issues/260

また、標準テンプレートのbootstrap.custom.min.cssですが、すべてのbootstrap3のComponentが含まれていないようで、どこまで使えるかの資料はあるでしょうか？

**Comment by Yangsin** [comment]
フロント側、/template/default/css/bootstrap.custom.min.css の話だとおもいますが

こちらでは、
・グリッドレイアウト
・ボタン関連のclass名一般化
の2点について、
ルールを共通化するために必要最小限のCSSの構成をBootstrapカスタマイザーからダウンロードして利用してます。

その後、bootstrap.jsで、
・ドロップダウンメニュー
・モーダルウインドウ
を再現するにあたり必要なCSSを、bootstrap.cssから手動でピックアップして該当CSSファイルに追記しております。

おおむね、
・グリッドレイアウト
・ボタン関連のclass名
・ドロップダウンメニュー
・モーダルウインドウ

がbootstrap3のCSSとして使えるかと。
ただ、カスタマイザーからダウンロードした内容があくまでも最小限のCSSですので、
場合によってはbootstrap3と同様の状態にならない可能性があります。
また、後程追記したもの(JSに関連するCSS)に関しては、EC-CUBE3のデフォルトフロントデザインを再現するための調整が入っているため、
bootstrapのCSSそのままではない点ご注意ください。

今後提供されるデザインテンプレートもそうですが、フロント側はサイトによって大きくデザインが変わるので、必要なCSSやJSは本体のデフォルトを利用するよりも、プラグイン独自で用意できるものなら、用意されるのがよいかと思っています。

**Comment by Yangsin** [comment]
開発終了となった3系の質問で議論も進んでいないため、クローズさせていただきます。
