### ISSUE TITLE
XmlHttpRequest でエラーが発生した場合のステータス

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1266]
ShoppingController で HTTP Status 500 (Internal Server Error) を返しているが、これはプログラム上の不具合が発生した場合のステータスなので、 HTTP Status 400 (Bad Request) を返すのが正しい

Exception をスローした場合は 500 で問題ない

**Comment by nanasess** [comment]
@chihiro-adachi Exception をスローした場合は Internal Server Error なので、ログ出力は Error レベルになるかなと思いますが、いかがでしょう？

**Comment by nobuhiko** [comment]
Exception をスローした場合は実装側は意識せず、全部ログに吐かれるとか出来ないもんですかね〜

**Comment by ttsuru** [comment]
@nobuhiko Error拡張すればできそうですねー

**Comment by chihiro-adachi** [comment]
@nanasess ありがとうございます。ログ出力はerrorが適切ですね。修正しました。

@nobuhiko @ttsuru 
通常の画面であれば、例外スローした場合はログ出してくれてますね。なので普段はあまり意識する必要はないかなと思います。

今回の箇所は、処理復旧させてjsonのレスポンスを返す必要があるので、個別に制御してます。

ajaxリクエスト時の例外を補足して制御する場合は、Silex::errorだと、例外のオブジェクトとエラーコードしかアクセス出来ないので、Symfony2のKernelEvents::Excepitonに置き換えればできそうな気がします。

**Comment by nobuhiko** [comment]
@chihiro-adachi 
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Service/PluginService.php#L115
そうなんですか？例えばこことかログに吐き出してくれなくて困ったんですけど・・

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ごめんなさい、ここでないですね、
この例外は呼び出し元で適切にハンドリング＋ログ出力するべきかな、と思いますので見直しますてみます。

**Comment by chihiro-adachi** [comment]
#1430 で修正されました。
ログ出力等については、#1432　#1446　で対応しています。
