### ISSUE TITLE
非会員購入時、確認画面でフリガナの変更ができない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1267]
お届け先変更の UI に合わせた方が良いと思われます。

**Comment by nanasess** [comment]
関連 #1266

**Comment by geany-y** [comment]
@nanasess
以前指摘いただいた、フリガナでひらがなで入力された際に、mb_convert_kanaでカタカナ変換する件ですが、フロント画面の新規会員登録を確認したところ、指摘の機構で変換がされていました。
よって一度、該当箇所を洗いだし、別Issuesとして切り分けます。

**Comment by Yangsin** [comment]
お届け先変更のUIに合わせるのはテンプレートへの影響が大きく、マイナーバージョンとしては、現状のAjaxの箇所にフリガナ追加程度にとどめます。

**Comment by ryo-endo** [comment]
対応内容をまとめます。

ゲスト購入時、
お客様情報の「変更」ボタンを押した時に表示される以下のフォームに、「フリガナ」を追加します。
追加する場所は、名前と郵便番号のあいだ。

![image](https://cloud.githubusercontent.com/assets/16891862/22240079/bf4588dc-e25c-11e6-80df-0099a8ab913f.png)

※レイアウトが崩れているのは別のIssueで対応する。https://github.com/EC-CUBE/ec-cube/issues/1696

**Comment by chihiro-adachi** [comment]
#2155 で対応
