### ISSUE TITLE
カート内数量減算を連続クリックでカートから商品が削除できてしまう

### ISSUE THREAD

**Issue by SF-kitagawa** [EC-CUBE/ec-cube#1268]
[EC-CUBE] 3.0.6
[PHP] 5.6.15
[データベース] Mysql 5.6.27
[WEBサーバ] Apache/2.4.6
[ブラウザ] google chrome 47.0.2526.73 m
数量が1の時は「-」が押せないが、一旦数量を増やしたのち「-」を連続でクリックすると1で止まらずに商品が削除される。

**Comment by Yangsin** [comment]
連続クリック自体は許容しつつも、のこり1個になったときには、そこでとどまるように修正するのが望ましいですね。

**Comment by ryo-endo** [comment]
初期実装から、商品数が0になるとカートから商品を削除する実装になっていました。
https://github.com/EC-CUBE/ec-cube/blame/65a3a4804805a8ad95338f4a4295ba40868d8fad/src/Eccube/Service/CartService.php#L136

連続クリック時に意図せずカートから商品が消えてしまうなど、利便性が悪いため、商品マイナス時には残り１個で止まるよう仕様変更します。
