### ISSUE TITLE
インストール時、データベースの初期化をスキップすると、STEP3 の管理者情報が反映されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1276]
2系では、データベースの初期化をスキップした場合でも、インストーラで設定した管理者情報(パスワード等)は、更新されるようになっていました。

管理者パスワードを忘れた際の救済措置としても、管理者情報の更新はできるようにしておいた方が良いと思います。

**Comment by chihiro-adachi** [comment]
#1334 で修正されました。
