### ISSUE TITLE
郵便番号検索ボタンの仕様変更

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1277]
間違った郵便番号を入力してしまった場合、自動入力時のエラーメッセージが表示されない
レスポンスが悪いのか、間違っているか、わからないのでユーザービリティに欠ける。
また、郵便番号検索ボタンではなく、 onchange などのイベントで検索しても良いのではないでしょうか。

**Comment by Yangsin** [comment]
https://github.com/EC-CUBE/ec-cube/pull/2337
