### ISSUE TITLE
【ユーザー画面/商品一覧】商品説明の長い商品を表示した際にボックスが崩れる

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1283]
商品説明に長文が登録されたもの、短文での説明が混在すると、
商品一覧レイアウトが崩れる
→JSでDIV内の最も高い要素に行DIVの高さを揃えるプラグインがあったはず
![broken_block](https://cloud.githubusercontent.com/assets/14922838/11624623/69f48aac-9d18-11e5-881c-86621eff2c30.jpg)

**Comment by konotakanobu** [comment]
http://www.tinybeans.net/blog/download/jquery-plugin/jquery-auto-height.html

これですかね。

**Comment by geany-y** [comment]
@konotakanobu 
レス有難うございます！
あっそれですw

**Comment by shhirose** [comment]
functions.js にすでに同じようなツールの matchHeight があるので、それを使用したほうが良いかと。
http://brm.io/jquery-match-height/

**Comment by geany-y** [comment]
@shhirose 

あっレス有難う御座います。
>functions.js にすでに同じようなツールの matchHeight があるので、それを使用したほうが良いかと。
>http://brm.io/jquery-match-height/
→こちらを優先的に導入します。

**Comment by chihiro-adachi** [comment]
fixed #1369
