### ISSUE TITLE
複数配送時、お届け先が商品ごとに分かれてしまい、送料もそれぞれ加算される

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1289]
複数配送を指定した際、お届け先が商品ごとに分かれてしまう。
この場合、それぞれに送料が加算されてしまう。

お届け先ごとに商品をまとめる必要がある。

2系では、上記のような仕様となっておりました。
#### 配送先の指定

![default](https://cloud.githubusercontent.com/assets/815715/11649368/bd215670-9dc1-11e5-9490-6eee8ebb92d6.PNG)
#### 確認画面

![2](https://cloud.githubusercontent.com/assets/815715/11649379/cb5e3e06-9dc1-11e5-9c0c-18b5290f80bb.PNG)

**Comment by nanasess** [comment]
送料が加算されてしまうため、バグとしておきました。

**Comment by lqdung-lockon** [comment]
This is commit to fix and included unit test. Please check here #1895.

**Comment by chihiro-adachi** [comment]
#2055 で修正
