### ISSUE TITLE
フックポイントeccube.event.app.afterについて

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1292]
フックポイントeccube.event.app.afterについて
FilterResponseEventがパラメーターとして渡されていなかったので、
全体のresponseに対して何かを変更したい際には、不便だと思います

Eccube/Application.phpに
下記のような変更はご検討していただけないでしょうか？

<pre>
/*
        $this->after(function(Request $request, Response $response, \Silex\Application $app) {
            $app['eccube.event.dispatcher']->dispatch('eccube.event.app.after');
        }, self::LATE_EVENT);
*/
        $app = $this;
        $this->on(\Symfony\Component\HttpKernel\KernelEvents::RESPONSE, function (\Symfony\Component\HttpKernel\Event\FilterResponseEvent $event) use ($app) {
            if (\Symfony\Component\HttpKernel\HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
                return;
            }
            $app['eccube.event.dispatcher']->dispatch('eccube.event.app.after', $event);
        }, self::LATE_EVENT);
</pre>

**Comment by Yangsin** [comment]
Qiitaにあがってた以下とも関係しそうですね。  http://qiita.com/Geany/items/a1bea004f170d69af6c6

**Comment by Yangsin** [comment]
サイト共通・フロント共通・管理画面共通の3パターンくらいが考えられそうですが、サイト共通はあまり利用用途が思いつかないのです。
全ページにタグを埋め込むとかなら、フロント画面だけならブロックを利用するでもいけそうですが、具体的なユースケースってどんなものがありますでしょうか。

**Comment by hainey** [comment]
既に生成したタグを変更したりする場合はいまのフックポイントで対応できないですね

**Comment by chihiro-adachi** [comment]
3.0.9でフックポイントが新設されました。#1410
各フックポイントでは、イベント関連の引数が渡り、リクエスト情報やレスポンス情報にアクセスすることができます。
