### ISSUE TITLE
Eccube/Application missing Finish Middleware

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1293]
http://silex.sensiolabs.org/doc/middlewares.html#finish-middleware
フックポイントにFinishの実装が足りなかったようで、実装したほうが良いと思います。

**Comment by k-yamamura** [comment]
```
eccube.event.controller.ルート名.finish
```
というイベントがご指摘にあります```finish(kernel.terminate)```イベントに該当するのですが
こちらでは事足りないということでしょうか。

**Comment by hainey** [comment]
ルート単位ではなくて、アプリケーション単位のfinishのイベントがないようです。

**Comment by chihiro-adachi** [comment]
3.0.9でフックポイントが新設されました。#1410
