### ISSUE TITLE
EC-CUBEをインストール時にレンタルサーバによってはDBエラーが発生し正常にインストールできない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1297]
バージョンアップをするに従いマイグレーションファイルが増えたため、
特定のレンタルサーバで共有のMySQLを使ってEC-CUBEのインストールを行うと、
以下の現象が発生し正常にインストールできない。
```
PDOException: SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query 
```
my.cnfを修正できる環境であれば対応可能だが、修正できない環境の場合、アプリケーション側で対処する必要が有る。

**Comment by nanasess** [comment]
Merged from #1301
