### ISSUE TITLE
管理画面のデザイン変更・メニュー構成変更

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#13]
下記イメージで管理画面を実装する
* システムに関する項目はすべて「設定」タブにいれる
* レスポンシブ対応

![default](https://cloud.githubusercontent.com/assets/9044511/5524940/611583a6-8a21-11e4-9d7d-c857107f44d6.png)

**Comment by Yangsin** [comment]
管理画面のメニューを構成も合わせて置き換えるイメージです。
* ホーム  
* 商品管理  
* 受注管理  
* 売上管理  
* 会員管理  
  -  メルマガ管理もここに統合  
* コンテンツ管理  
  -  新着情報管理  
  -  おすすめ商品管理  
  -  ファイル管理
  -  レイアウト管理
  - ページ管理
  - ブロック管理
* 設定  
  - 基本情報設定
  - デザイン設定
  - システム設定
  - 機能拡張（オーナーズストア）

**Comment by chihiro-adachi** [comment]
管理画面のメニュー整理行いました。

運用系と設定系の機能に分類し、以下のように定義してます。

* 運用系機能
    + ホーム
    + 商品管理
    + 会員管理
    + 受注管理
    + 売上集計
    + コンテンツ管理
* 設定系機能
    + ショップ設定 =  旧基本情報管理
    + システム設定
    + 拡張機能 = 旧オーナーズストア

詳細を以下にあげました。
https://docs.google.com/a/lockon.co.jp/spreadsheets/d/1Jsf19-drYC98FLsNAsaNR8gmYuK4TQAolfRkBYTTuxc/edit#gid=1426792749

ご意見いただければ嬉しいです。

**Comment by shinichi-takahashi** [comment]
@chihiro-adachi 
画面と合致していないように見えるため、 `/operation/` の層をなくし、その層に属するものは一階層上に置こうと思います。

**Comment by shinichi-takahashi** [comment]
@chihiro-adachi 
また、URLの末尾の `/` はすべて削除します。
