### ISSUE TITLE
会員購入時、お届け先の選択で Request::get() を使用している

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1303]
`$form->handleRequest($request);` を使用するべき。

**Comment by Yangsin** [comment]
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Controller/ShoppingController.php#L563 の箇所かと

**Comment by Yangsin** [comment]
具体的な事象として #1801 が発生する。 #1801 に集約とします。
