### ISSUE TITLE
cli-config.php を ROOT ディレクトリから移動する

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1304]
取り急ぎ、cliを動かすためにおきましたが、移動できるようでしたら移動したいです。。。

**Comment by nanasess** [comment]
ROOT 直下または ROOT/config にしか置けないようですね
https://github.com/doctrine/doctrine2/blob/cd11723e6310b5973f50e7d9819c58916721d290/bin/doctrine.php#L33

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
