### ISSUE TITLE
【改善要望】非公開商品の確認時のURLについて

### ISSUE THREAD

**Issue by systemfriend-tsuji** [EC-CUBE/ec-cube#1309]
EC-CUBE3.0.7で確認しています。
管理画面の商品管理の確認ボタンを押下して商品ページを表示する際にURLに「?admin=1」を付けている
のは何か意図はありますでしょうか？

プログラムを確認しますと同じセッションで管理画面にログインしている場合は表示できるように記述されて
いましたので、管理画面の商品の確認ボタンで「?admin=1」を付けて表示しなくてもよいのではと思っています。

**Comment by Yangsin** [comment]
3系でのレビュー実装上の使用です。
開発終了となった3系の質問で議論も進んでいないため、クローズさせていただきます。
