### ISSUE TITLE
Filter を設定した後、戻さないとその後の処理全てに影響が出る

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1311]
CartService：：getCart() で、ProductClass のみ soft_delete を除外しているが、検索終了後に除外したままになってしまっているため、その後の処理や、ブロックで ProductClass を検索すると soft_delete が適応されていない状況になる。

ここ以外でも特定のページでのみ有効にしている Filter も処理が終了した際に無効化しなければ、ブロックやプラグインで影響が出る可能性がある。

**Comment by Yangsin** [comment]
論理削除の見直し #2314
にのっとり本Issueはクローズします。
