### ISSUE TITLE
「受注マスタ」となっているが、受注はマスタではなくトランザクションではないか

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1312]
受注はトランザクションなので、「マスタ」ではないと思います。
![image](https://cloud.githubusercontent.com/assets/578548/11741316/847670fe-a03b-11e5-8909-ef6bf973cc65.png)

**Comment by Yangsin** [comment]
EC-CUBEリリース以来の歴史的経緯ですね。
希望が多いようであれば名称変更もよいかと思いますので、ひとまずこのまま置いておきます。
賛同される方は :+1:  お願いします。 他に名称案などもあればコメントをどうぞ。

**Comment by okazy** [comment]
4.0では「〇〇マスター」から「〇〇一覧」に変更しています。
