### ISSUE TITLE
PHP5.6.x でオーナーズストアが動かない？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1318]
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16708&forum=13&post_id=73889#forumpost73889

**Comment by nanasess** [comment]
これが原因でしょうか?
http://d2b6.seesaa.net/article/426112731.html
http://php.net/manual/ja/migration56.openssl.php

**Comment by nanasess** [comment]
ca-bundle.crt を指定するしかないかも

http://www.textbox.jp/note/sakura-php56-ssl-error.html
http://qiita.com/dora_kou/items/c9c2f7d8d53303ee1aab

WordPress は自前で持っている様子
https://github.com/WordPress/WordPress/blob/master/wp-includes/certificates/ca-bundle.crt

**Comment by chihiro-adachi** [comment]
#1461
