### ISSUE TITLE
Pluginに使われるjsファイルやcssファイルについて

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1319]
https://github.com/EC-CUBE/ec-cube/issues/201

こちらによると、html/pluginのフォルダが用意されていますが、
Pluginインストール時は自動ではなく、Pluginのコードでファイルをコピーする必要があるので、Pluginの開発者にとっては面倒だと思います。

EC-CUBE本体でインストール時自動的にやって頂くのはいかがでしょうか？

Pluginのフォルダ構造にhtmlというフォルダを作成し、html以下のファイルは自動的に html/plugin/PluginName/の下にコピーするのはいかがでしょうか？

また,デザインに関わるcss/jsはテンプレートで上書きすることも可能として、Pluginのtwigファイルからcss/jsを参照した際は、Filterを作って頂いて、テンプレートに同名ファイルが存在すれば、テンプレートのファイルを優先して参照するというロジックを入れて頂いていががでしょうか？

**Comment by xuelian311** [comment]
#2644 で本件解決済みであるため、クローズいたします。
