### ISSUE TITLE
twigでのphp関数の呼び出し機構を廃止

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1320]
twigテンプレートにはＰＨＰ関数を使うことができないので、
Smartyなどになれている開発者には不便です、こちらのPHP関数をtwigに実行できるExtensionを公式的に導入するのはいかがでしょうか？
http://pastebin.com/VZzgSGLq

**Comment by ttsuru** [comment]
TwigはViewですし、Viewでロジックで実装すべき内容を書くこと自体、推奨されないのではないでしょうか。

**Comment by hainey** [comment]
TwigPHPExtensionはphpをロジックとしてtwigに書くことではなくて、
{{php_ini_get}} など phpの関数の前にphp_をつけることだけで、phpの標準関数をtwigで直接使えるExtensionとなります。

もちろんControllerに事前に関数を読んで変数をセットすることもできるんですが、もともとロジックではなくて、変数にする必要ない場合でもわざわざViewから分離してControllerに書くのも、かえてプログラムが読みにくくなってしまいます。

またTwigPHPExtensionを導入する以外の方法で、下記のtwigの公式ドキュメントにも方法があるようです。
http://twig.sensiolabs.org/doc/recipes.html
Defining undefined Functions and Filters on the Flyのところをご参照ください。

**Comment by ttsuru** [comment]
@hainey 
僕がいったExtentionは TwigPHPExtension のことではなく、必要になった場合に適時Extentionを書けばいいのではないかという点です。

Viewでロジックを書かないという内容は現在のベストプラクティスに近くなっており、現状のEC-CUBEでもPHPをわざわざTwig内に書く必要性がわかりません。
おそらく、ユースケースを幾つか挙げていただいた方が他の方にもわかりやすいのではないかと思います。

**Comment by seasoftjapan** [comment]
ビューでも PHP をカジュアルに使えるようになるのは歓迎です。PHP の関数群は便利ですから。

**Comment by nanasess** [comment]
React のように View にロジックを記述するフレームワークも出てきていますし、PHP関数も適材適所で使えたら良いのではないかなと思います。

**Comment by okazy** [comment]
2021/6/17 セキュリティ対策検討会メモ

Twig 内で PHP 関数が実行できるのは、セキュリティの観点から望ましくないので、非推奨としてゆくゆくは廃止していくことも検討しなければいけない。

**Comment by chihiro-adachi** [comment]
4.1で非推奨化されましたので、4.2で機能を削除します

**Comment by chihiro-adachi** [comment]
以下で修正されました。4.2ブランチへ反映されています。
https://github.com/EC-CUBE/ec-cube/commit/7cd9c2ee7a68ee58d90c17ab4f83696ec56065ea
