### ISSUE TITLE
RFC違反のメールアドレス の許容

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/ec-cube#1325]
フロント側の「お客様情報の入力」画面で、メールアドレスを入力する項目について、相談させてください。
運用中のサイトから出てきた問題なのですが、過去のISSUESを確認するとこの箇所のチェックについてRFC2822の規格を元にチェック処理を行っていると思います。

最終対応、EC-CUBE3.0.5
#692
#829

それで、 問題点についてですがキャリアメールについて問題があるのを見つけました。
・NTTドコモ　メールアドレス
https://www.nttdocomo.co.jp/info/spam_mail/measure/change_add/
このサイトを見ると、

＊また、2009年4月1日以降、「.」は「..」などのように連続で使用することや@マークの直前で使用することはできなくなりました。  注意アドレス内に「..」や「.@」が存在する場合、一部のメールサービスからのメールが正しく届かない可能性がございます。

とあり、2009年4月より前は@より前に「..」が使えていました。

今回運用中のサイトで該当のメールアドレスが入ってきたので、今後どうして行くか検討の余地があるかなと思います。

**Comment by Yangsin** [comment]
RFC違反のアドレス自体は徐々に使えなくなっていっていると思っていますが、今回のケースの場合にお客様は代替の手段がないものでしょうか。
代替手段のないお客様がまだまだいるのであれば、２系同様に許容することも検討する価値はありそうです。それが日本製であるEC-CUBEの良さでもあるので。
ちょっと皆様の状況をお伺いしてみたいポイントですね。

**Comment by ttsuru** [comment]
結構跳ねられるシステム増えましたよね・・・
ガラケー対応してないので、validationの厳密さを優先するか、ガラケー対応を優先するかという問題になりますね。

**Comment by nanasess** [comment]
顧客の某サイトでは、まだ2000件以上ありました。
docomo の SP モードでスマートフォンをお使いのお客様が多いです。

**Comment by shhirose** [comment]
これローカル部をダブルクォーテーションで括って送信すれば送信されると思います。
RFCのチェック有無を判定して、#829 で追加された validator の  strict の値を false にし、送信処理でダブルクォーテーションをつければよいかと思います。
前の案件でやっていましたので大丈夫だと思うのですが、検証できる環境があれば検証していただきたいと思います。

例）hoge.@example.com → "hoge."@example.com

対応しようと思っていたのですが、時間と検証環境がないためなかなかできませんでした・・・。

**Comment by ttsuru** [comment]
@shhirose 
RFC違反の動作を行うのでしたら、MTAごとに検証をしないといけないと思います。

**Comment by seasoftjapan** [comment]
@ttsuru 
ガラケーのみなんでしたっけ? だったら、スルーしても良い気はします。
スマホでも存在するなら深刻ですね。

**Comment by seasoftjapan** [comment]
「..」とか「.@」を検出して、「"」クォートでフォーム入力するように誘導できないですか?

けど、インターフェイス的に、スマートじゃないか・・・

**Comment by nanasess** [comment]
スマホでも存在するんです。 docomo の SP モードや ezweb で過去に作成したメールアドレスを使い続けることが可能なので。某顧客のところでは2000件以上ありました。

**Comment by ttsuru** [comment]
@seasoftjapan 
スマホ時代になってからアドレス変更をした方はRFC違反にはなっていません。
かなり前から変更していない方ですね。

**Comment by ttsuru** [comment]
@nanasess 
2000件という数字よりも、その中で実際のアクティブユーザーが何％とか、全体の何％という方が議論になると思います。

**Comment by ttsuru** [comment]
本件は切り替えられるようになっているようが良さそうな気がします。。。

**Comment by ttsuru** [comment]
いつからRFC違反のアドレスに変更できなくなったかをまとめました。

2003年 vodafone移行時
2009年4月 docomo
2009年9月 au

**Comment by ttsuru** [comment]
SwiftMailer でも話題に上がっています。
https://github.com/swiftmailer/swiftmailer/issues/71

**Comment by seasoftjapan** [comment]
> 本件は切り替えられるようになっているようが良さそうな気がします。。。

賛成です。

**Comment by ttsuru** [comment]
6年前にもEC-CUBEで話題になっていますね。
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=5456&forum=9

**Comment by shhirose** [comment]
2系の標準ではどうなんでしょうか？

**Comment by nanasess** [comment]
2系(2.11以降)は切り替えられるようになっていて、デフォルトは RFC違反も許容してます。

**Comment by shhirose** [comment]
その時はどのような対応だったんでしょうか？
基本的にその対応をするって方針でいいんではないでしょうか。

**Comment by nobuhiko** [comment]
3系は swiftmailer がエラーで落ちるということなのでこういう対応になっているんですが、そこは大丈夫なのでしょうか？

**Comment by shhirose** [comment]
そこも含めて検証する必要はありますね

**Comment by ttsuru** [comment]
@nobuhiko @shhirose 
https://github.com/swiftmailer/swiftmailer/issues/71
こちらにあるようにロジックの差し替えが必要ですね。

**Comment by Yangsin** [comment]
ざっとご意見拝見したかぎり。

ガラケーのサポートとRFC違反のメールアドレスの許容は別問題で、RFC違反のアドレスは未だ利用されており切替可能な事が望ましいですね。

**Comment by nanasess** [comment]
修正箇所が多く、切り替えできるまでは至ってないのですが、こんな感じの対応で送信できるようになると思います。
https://github.com/nanasess/ec-cube/commit/5a646b14e0ba01b2067546e2f37e519f31b6b6c6

**Comment by Yangsin** [comment]
切替まで実装することが困難なことから、カスタマイズTipsとしての扱いでドキュメントとしてまとめていくこととします。

**Comment by ttsuru** [comment]
こちら、他のSymfonyの案件で対応しました。
swiftmailer 6ではValidationの実装が分離されており、カスタマイズ可能となっています。

**Comment by ttsuru** [comment]
```
            "require": {
                "egulias/email-validator": "~2.0",
                "php": ">=7.0.0"
            },
```
なので採用は少しむずかしいかもしれません。

**Comment by chihiro-adachi** [comment]
#3667

**Comment by Yangsin** [comment]
#3667 が採用され、4系で実装済み
