### ISSUE TITLE
プラグインでのDBALベストプラクティスについて

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1328]
現状、プラグインのマイグレーション時に、 ``executeUpdate()`` を利用していますが、変数をそのままSQL文に入れるなど、あまりよいとは言えない例が多くあります。

・冪等性を考慮したアップデートについて
http://qiita.com/iakio/items/adf1f923d1cfccbba765
こちらにあるような形が良いかと思います。

・INSERT または UPDATE について
現状、なぜか executeUpdate を利用していますが、こちらは insert もしくは update のほうが安全にSQLを実行できます。

http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html

**Comment by ttsuru** [comment]
他にもありますが、ぜひ、migration自体のベストプラクティスを定義していった方が良いかと思います。

**Comment by nanasess** [comment]
本当は、やっちゃいけないのかもしれませんが、こんなことを試みたことがあります。
https://github.com/nanasess/ec-cube/commit/e42ee29c8c3ddf0ac7a5e89af19612cc16e80f95

migration のベストプラクティスを定義しない理由は無いと思いますが、リソースがそこまで追いついていないのが実情かと...

**Comment by ttsuru** [comment]
@nanasess 
気づいたタイミングでは何らかのアクションを起こしていますが、現状、危険な表記が多い点が非常に気になります。

**Comment by Yangsin** [comment]
何がベストプラティクスとして定義できるかも、用意でききれていないのですが、2系でプラグイン開発時のセキュリティガイド作ったように、そうしていきたいのは山々です。
https://github.com/EC-CUBE/ec-cube.github.io
へも、お気づきの点などご協力いただけると助かります

**Comment by ttsuru** [comment]
@Yangsin 
どこかのタイミングで整理します。

**Comment by chihiro-adachi** [comment]
ec-cube.github.ioにマイグレーションの作成についてissue起案しました
https://github.com/EC-CUBE/ec-cube.github.io/issues/71

**Comment by ryo-endo** [comment]
上記のとおり、github.io側にIssue作成させていただきましたので、こちらはCLOSEさせていただきます。
EC-CUBE/ec-cube.github.io#71
