### ISSUE TITLE
今後のドキュメント化に向けた情報や実装の参考にしたい情報

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1330]
http://ec-cube.github.io に追加していきたい内容や、
今後の実装の参考にしたいネタを書き留めておくためのIssue
随時、コメントなどで貯めていきます。好きにコメントいただいてもいいです。
見づらくなってきたりしたら、調整します。

**Comment by Yangsin** [comment]
Twigの参考ドキュメント
http://twig.sensiolabs.org/pdf/Twig.pdf

**Comment by Yangsin** [comment]
案件内で閉じたプラグインなどでの利用を主に想定して、イベントとは別に継承的な概念も必要かも。
参考） バンドルの継承を使って既存のバンドルのパーツを上書きする方法
http://docs.symfony.gr.jp/symfony2/cookbook/bundles/inheritance.html

**Comment by Yangsin** [comment]
SilexのREST APIのSkeleton
https://github.com/vesparny/silex-simple-rest

**Comment by k-yamamura** [comment]
Symfony2用として公開されているBundleをSilexで使えるようにする参考記事です。
http://tech.quartetcom.co.jp/2014/12/03/knppaginatobundle-adapted-to-silex/

**Comment by nanasess** [comment]
Doctrine のベストプラクティスです。
http://ocramius.github.io/doctrine-best-practices/#/

**Comment by nanasess** [comment]
PHP の oauth2 の実装です。 Drupal は、これを拡張しているようです。
https://github.com/bshaffer/oauth2-server-php

**Comment by nanasess** [comment]
OpenID Certification
http://openid.net/certification/
EC-CUBE もここに載せられたら知名度が上がると思います。

**Comment by Yangsin** [comment]
ドキュメント周りのリポジトリが別途存在するためこちらはクローズさせていただきます。
