### ISSUE TITLE
__PHP_Incomplete_Class エラー

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1332]
ECCUBE 3.0.5

どんなケースで発生しているかがはっきりしないですが、ログイン後しばらく放置してからマイページに行くと下記のようなエラーがありました。

PHP Catchable fatal error:  Argument 1 passed to Eccube\\Repository\\OrderRepository::getQueryBuilderByCustomer() must be an instance of Eccube\\Entity\\Customer, instance of __PHP_Incomplete_Class given, called in /var/www/eccube3/src/Eccube/Controller/Mypage/MypageController.php on line 74 and defined in /var/www/eccube3/src/Eccube/Repository/OrderRepository.php on line 453, referer: http://eccube3.localhost.com/

**Comment by nanasess** [comment]
タイムアウトで、 Customer のインスタンスが取得できなくなってしまった感じですかね。

**Comment by hainey** [comment]
こちらのエラーの原因がわかりました

Application.phpのinitPluginEventDispatcher関数に
<pre>
        // hook point
        $this->before(function(Request $request, \Silex\Application $app) {
            $app['eccube.event.dispatcher']->dispatch('eccube.event.app.before');
        }, self::EARLY_EVENT);
</pre>
EARLY_EVENTが原因で、eccube.event.app.beforeの関数にセッションの操作を行うと、
上記のエラーになってしまいました。
また、EARLY_EVENTだと、eccube.event.app.beforeのイベント関数にもログインしているユーザー情報も取得できません。
EARLY_EVENTをLATE_EVENTに直していただくとセッション操作もログインしているユーザー情報も問題なく取得できました。
一般的には、Pluginの開発者はセッションなどの取得が必要と思いますので、ECCUBE本体の修正をお勧めします。

**Comment by chihiro-adachi** [comment]
3.0.9でフックポイントが新設されました. #1410
ログインユーザ情報については、eccube.event.xxx.controllerで取得することが可能です。
