### ISSUE TITLE
submodule となっている docs を完全に分離する

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1341]
submodule とする意味もないので、別リポジトリだけでいいのではないでしょうか。
submodule ですと、docs が更新されてもsubmodule update するまで更新されませんし、あまり意味がないように感じます。

**Comment by chihiro-adachi** [comment]
ドキュメント自体、http://ec-cube.github.io/ へ集約していく方針ですので、submoduleの定義については削除で進めたいと思います。※のちほどpr投げます。

**Comment by ryo-endo** [comment]
#1668 で対応。
