### ISSUE TITLE
COPYRIGHT 表記を変更する

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1342]
現状、 LICENSE と COPYING がそれぞれありますが、 LICENSE に統一すべきではないでしょうか。
また、現状、ソースコードごとに以下のコメントがありますが、非常に長く、ソースコードのメンテナンス性を下げていると思います。
また、本来のEC-CUBEのライセンスのデュアルライセンスではなく、GPLのみがコメントとして表記されており、変更するべきかと思います。

また、年が変わるごとにすべてのソースコードの2015部分が2016になるのもメンテナンス性を下げてしまう原因になるとおもいます。
こちら、時間がかかるかもしれませんが非常に強く変更をお願いしたい部分です。

Symfony FWのように以下の表記をそれぞれのソースで行い、参照先はLICENSEが良いと思います。

```
/*
 * This file is part of the EC-CUBE package.
 *
 * (c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

**Comment by Yangsin** [comment]
LICENSEの下にCOPYINGのテキストもってくるようにしましょう。

ソースごとのコメントについては、EC-CUBE開発当初のロックオン法務の見解でした。
慣習化されているため、そのままにしておりますが
ご提案の方法でも問題ないと法務確認もできていますので、どこかのタイミングなおしたいなぁと思っていたところです。

年明けたら2016に直す作業の代わりにやっちゃいましょう。

**Comment by ttsuru** [comment]
@Yangsin 
確認ありがとうございます。
一応、プラグイン部分でライセンスが異なると思いますので、例外付きGPLと明記した方が良いかと思います。

**Comment by okazy** [comment]
年表記をやめ、cs-fixerで自動でつけられるようにしました。
