### ISSUE TITLE
【改善要望】商品種別が異なる商品を同時購入できない（カートイン時にチェックエラーになる）

### ISSUE THREAD

**Issue by fuidou** [EC-CUBE/ec-cube#1348]
商品種別が異なる商品を同時購入しようとしたら、カートイン時に「この商品は同時に購入することはできません。」のエラーなっています。
恐らく、配送方法と支払方法が商品種別によって制御されるため、同時購入できないような仕様になっていると思いますが、カートに入れるまでは許可すべきではないでようか？
カートの中は、商品種別でグルピング表示し、別々レジに進めるようにするとか・・・

ご検討ほどよろしくお願いいたします。

**Comment by nanasess** [comment]
2系は、カートに入って分かれるようになってますね。

**Comment by xuelian311** [comment]
#2630 で実装済みであるため、クローズします。
