### ISSUE TITLE
規格有の商品で、規格を選択した場合の挙動

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1349]
規格を選択した場合
- 2系では、商品コード、通常価格、販売価格が動的に選択した規格のものが表示される
- 3系では、XXXX～XXXX という表示であり、選択した規格が何に該当するのかカートに入れるまで分からない

品切れ商品を選択した場合
- 2系では、「カートに入れる」ボタンが「品切れ中」のテキストに変わる
- 3系では、カートに入れるボタンをクリックできてしまい、カート画面に遷移してからエラーメッセージが表示される

2系のような UI の方がユーザーにとってストレスが無いと思われます

**Comment by chihiro-adachi** [comment]
#1756 で修正
