### ISSUE TITLE
購入中に品切れになった場合のエラーメッセージに商品名が正しく表示されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1350]
1. 購入中に品切れになる
2. エラー画面に遷移する
3. 「カートに戻る」ボタンをクリック
4. カート画面でエラーメッセージが表示されるが、商品名が正常に表示されない

![default](https://cloud.githubusercontent.com/assets/815715/11947531/8a600778-a8ab-11e5-8384-2fc4c01e4759.PNG)

この場合は、カートに戻っても何も無い状態なので、「カートに戻る」ボタンは不要ではないでしょうか。

**Comment by Yangsin** [comment]
#1273 と重複のためクローズします。

**Comment by ryo-endo** [comment]
重複していた #1273 はすでにCLOSEされていたので、こちらを再OPEN。

**Comment by t-nagahashi** [comment]
同じissueがあるいためクローズいたします。
#2142
