### ISSUE TITLE
商品登録>商品規格 画面で、「登録」チェックボックスの ON/OFF を繰替えして登録すると product_class_id が新規追加される

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1353]
規格管理画面にて、以下のような挙動となっている
- 「登録」チェックボックスを OFF にする -> del_flg = 1 となる
- 「登録」チェックボックスを ON にする -> dtb_product_class に新たな行が追加される

論理削除していても再利用できていない。
また、受注履歴からの再購入ができなくなってしまう。

**Comment by nanasess** [comment]
一旦 OFF で登録すると、 #1351 と同様に、システムエラーとなってしまう

**Comment by trebla-on** [comment]
PRを作りました、こちらのISSUE結構難しのでPRはWIPとして作りました、対応の考え方はご確認お願いします。

**Comment by nanasess** [comment]
#2196 で修正済み
