### ISSUE TITLE
Myページ・購入履歴詳細のメール件名に、管理画面から送信した場合、店舗名が付与されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1354]
- 受注完了時に送信したメールの件名には **[店舗名]** が付与されている
- 管理画面より再送したメールの件名には **[店舗名]** が付与されていない

![default](https://cloud.githubusercontent.com/assets/815715/11989893/180be210-aa49-11e5-9789-fb857034da41.PNG)

なお、実際に送信したメールの件名には、店舗名が付与されている

**Comment by ryo-endo** [comment]
期待値は、店舗名が付与されていること。
