### ISSUE TITLE
管理画面でログイン時フロント画面のＴＯＰに遷移してしまう

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1361]
3.0.7 管理画面ログインＵＲＬ(/admin/login)を直接叩いてログインする際、またはパスワード入力間違いの際に
正しいパスワードでログイン後、フロント画面に遷移してしまう現象があります。
admin/login.twigに下記を追加すると修正されるようです。

&lt;input type="hidden" name="_target_path" value="admin_homepage" /&gt;

参考：http://stackoverflow.com/questions/12329855/symfony-2-keep-target-path-even-on-wrong-password

**Comment by ttsuru** [comment]
login 時に ``/admin/login`` を叩かず、 ``/admin/`` を叩けば良いと思います。

ただ、Firewallの設定項目をしっかりやったほうがよさそうですね。

**Comment by nanasess** [comment]
#536 こちらも類似

**Comment by hainey** [comment]
/admin/で一回パスワード間違いましたら　/admin/loginに遷移されるので、
その場合はフロントに遷移します。
環境依存ではないようです。

**Comment by nobuhiko** [comment]
なんかたまにフロントに飛ぶなとは思ってましたけどそんな罠があったんですね・・

**Comment by nanasess** [comment]
言葉足らずでした。 #536 も別の環境でも発生していましたので、こちらの修正案で解決できる可能性があります。

**Comment by ttsuru** [comment]
Symfony では default_target_path で設定できそうです。

http://symfony.com/doc/2.7/cookbook/security/form_login.html#changing-the-default-page

**Comment by shhirose** [comment]
`default_target_path`も必要ですが、失敗した時なので、`default_target_path`ではなく`failure_path`で設定したほうが良いのではないでしょうか。

**Comment by ttsuru** [comment]
@shhirose 
``failure_path`` って失敗した時にリダイレクトしちゃうんじゃないでしょうか。

**Comment by shhirose** [comment]
@ttsuru 
そうですね。
なので`failure_path: /admin/`とすればよいかと。

**Comment by ttsuru** [comment]
@shhirose 
failure_path って設定する必要ないと思います。
リダイレクトしてしまうと本来のログイン先の挙動が変わってしまうと思います。

**Comment by k-yamamura** [comment]
@hainey 
こちらの現象ですが3.0.0の頃から発生しておりまして、
再現したりしなかったりという状況であり原因の特定には中々至っておりませんでした。

(/admin/login)を直接叩いてログインする際、またはパスワード入力間違いの際に発生するという事ですが、このオペレーションを行うとお使いの環境では必ずこの問題は発生しますでしょうか。

**Comment by hainey** [comment]
最近ローカルのソースコードSVN updateしたら、ローカル環境では発生しなくなりました。
その他環境(3.0.7)はまだ発生しています。みなさんは再現されるでしょうか？

再現手順(100%)
Chrome/Firefox/IE 
1. キャッシュクリア
2.　ブラウザを閉じる→ブラウザを起動
3. URL欄に、..../admin/login　を入力
4. 正しいID/PASSでログイン
5. トップに遷移される
6. URL欄に ..../admin/を入力　ログインされている

また、時々管理画面ログインできないときがありますが、ブラウザを閉じて再度起動したらログインできるようになるケースがあるようです。

**Comment by erizou1492** [comment]
上記手順とは少し違うのですが、3.0.8で操作しているときに下記の手順でよく発生します。

1.操作時間がタイムアウト
2.ログイン画面表示
3.正しいID/PASSでログイン
4.フロントトップに遷移される
5.URLに .../admin/を入力し管理画面が表示される

**Comment by chihiro-adachi** [comment]
以下の手順でも100%発生します(3.0.11)。

- 基本情報＞ショップマスタに遷移(登録画面であればなんでも良い)
- セッションのファイル(`app/cache/eccube/session`)を削除
- 登録ボタンを押下
- ログイン画面が表示される
- ログイン実行

フロント画面が表示されるが、ログイン自体は成功している(/adminにアクセスすると閲覧できる)

**Comment by ryo-endo** [comment]
こちら #2177 で対応してmasterにマージしましたので、Issueを閉じさせていただきます。
ご報告ありがとうございました。
