### ISSUE TITLE
MultiViews 有効環境下でページ管理で作成したURLにアクセスできない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1362]
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16821&forum=2

ページ管理で作成した新規ページを作成する際に、

URL : hoge
ファイル名 : hoge

というようにファイル名とURLが同一だとMultiViewsが有効の場合、
http://xxxx/html/user_data/hoge
だとアクセスできなくなり、
http://xxxx/html/index.php/user_data/hoge
とindex.phpをつけないとアクセスできない。

**Comment by Yangsin** [comment]
根本的な解決をアプリケーション側で測るのはむずかしそうです。
回避策をドキュメントとしてまとめて行く方針で・・・

**Comment by xuelian311** [comment]
長期間に渡り議論が進んでないため、クローズいたします。必要ありましたら別途issueを立てて頂き、本issueを関連付けいただけると幸いです。
