### ISSUE TITLE
appディレクトリが存在しない場合、テンプレートがアップロードできない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1363]
テンプレートをアップロードする際に、テンプレートの中にappディレクトリが存在しなければエラーとなる。
htmlディレクトリだけでもアップロードできるようにする。
#1052 とは逆パターンです。

**Comment by ttsuru** [comment]
app ディレクトリは必要なんではないでしょうか。

**Comment by t-nagahashi** [comment]
以下、仕様で良いのではないでしょうか？
・ EC-CUBE本体としては、appディレクトリはファイルがなくても空ディレクトリとして用意しておく仕様とする。
　（本来、appディレクトリは存在しなくても挙動としては、問題ないですが）


ただ、app配下にファイルもしくはディレクトリが存在しないと、以下メッセージが表示されます。
「appディレクトリが見つかりません。ファイルの形式を確認してください。」

ソースを確認すると、
appディレクトリの存在チェックのみしかしていないように見えるのですが、
その配下までチェックしているような挙動です。

ファイルパス：\src\Eccube\Controller\Admin\Store\TemplateController.php

`// htmlディレクトリの存在チェック.
if (!file_exists($htmlDir)) {
    $form['file']->addError(new FormError('htmlディレクトリが見つかりません。ファイルの形式を確認してください。'));

    if (file_exists($tmpDir)) {
        $fs = new Filesystem();
        $fs->remove($tmpDir);
    }

    return $app->render('Store/template_add.twig', array(
        'form' => $form->createView(),
    ));
}`

**Comment by ryo-endo** [comment]
@ttsuru 
いまのデザプレの仕様ですと、app以下にtwigファイルを含むことになるので、appディレクトリ必要なんです。
とはいえ、appディレクトリ有り/無しどちらも考慮はしておかないと、といった感じです。

**Comment by t-nagahashi** [comment]
要件が変化したため、issueを別でたてましたので、Closeします。
#2115
