### ISSUE TITLE
プラグインでのDOM要素の挿入/編集について

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1364]
プラグイン作成にあたり、例えば特定のDOMに要素を追加したい場合など、
filterで取得し、str_replaceで、テキスト置き換えるという方法とられていますが、
なにかよい手段がないものかと考えています。

置換元として、例えばfilter("div#hoge")の中身を書き換えようとして、
文字列が半角スペース1つだけだった場合、
`<div id="hoge"> </hoge>`

予期せぬ半角スペースの箇所と置換されてしまうケースがあり得ます。
スペースが1つでも2つでも3つでも同様です。

jQueryのように、次のように挿入できれば柔軟かなとおもい、
`$("#hoge").append("<p>挿入</p>");`

DOM Crawlerコンポーネントですとか、PHPマニュアルのDOMの頁をみたり、
https://github.com/symfony/dom-crawler/
http://php.net/manual/ja/book.dom.php
試行錯誤していたのですが、私の力では上手く実現できず、、、

最終的に、symfonyのissueでも似たようなDOM編集についてのトピックを見つけまして、
そこで紹介されていたDOM Crawlerの拡張ライブラリを使うとすんなり思ったことができました。
https://github.com/wasinger/htmlpagedom

ちなみに、DOM Crawlerコンポーネントは、DOM編集するためのものではない。と公式に本トピックがcloseされているので、見当違いな解決案なのかもしれません。
https://github.com/symfony/symfony/issues/8036

一応、1案として(Wa72\HtmlPageDom)。

**Comment by xuelian311** [comment]
開発終了となった3系の質問で議論も進んでいないため、クローズさせていただきます。
