### ISSUE TITLE
AOP の導入

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1365]
現在の Middleware/FilterResponseEvent ベースの拡張ではプラグインの自由度に欠けるため、 [AOP](https://ja.wikipedia.org/wiki/アスペクト指向プログラミング) 導入の提案です。

[Go! AOP PHP](https://github.com/goaop/framework) を組込むことによって実現できそうです。
これにより JoinPoint, PointCut 等のパターンを利用して、 ネイティブ関数を含む、すべての関数の振舞いを変更可能です。

まだ多くの問題はあるものの、 `ProductRepository::getQueryBuilderBySearchData()` の結果を変更することに成功しています。[(検証コード)](https://github.com/nanasess/ec-cube/commit/d2182b14a141f06edeae0e1362cf22d087c1247c)

現在の主な問題点は以下の通り
- [ ] PHP5.4+ になってしまう
- [ ] 時折 `zend_mm_heap corrupted` というエラーに遭遇する
- [ ] `index_dev.php` で動作しない
- [ ] 重い
- [ ] Pimple の DI コンテナに載せた場合の動作を未検証(Go! AOP PHPは独自の DI コンテナを使用している)
- [ ] PHPUnit が通らない...

**Comment by nanasess** [comment]
Go! AOP Framework 2.0 がリリースされたようです。PHP5.6+ になっていますね。。。
https://github.com/goaop/framework/releases/tag/2.0.0

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
