### ISSUE TITLE
3.0.8、index_dev.phpを開くとdebugのプロファイラでエラー？

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1366]
3.0.7から、3.0.8にアップデートし、
念の為、composer updateしました
index.phpでは正常に動作していますが、index_dev.phpにアクセスしますと、次のようなエラーがでます。

![image](https://cloud.githubusercontent.com/assets/1335922/12058374/c4db6f7a-af8e-11e5-8163-0b09efbc82da.png)

/index_dev.php Line 90 をコメントアウトしますと、動作しました。
`
// $app->register(new \Saxulum\SaxulumWebProfiler\Provider\SaxulumWebProfilerProvider());
`

3.0.8で導入されたdumpまわりのエラーなのか、私のアプデみすなのかわかりません。

**Comment by geany-y** [comment]
ご報告ありがとうございます。
解決策ではなく、申訳ありませんが、参考情報だけとなります。
何か助力となれば幸いです。
[ 環境 ]
Kagoya VPS

[インストール作業]
①v3.0.8DL( wget )
http://downloads.ec-cube.net/src/eccube-3.0.8.zip
②cube3 ルートディレクトリで 「composer install」
③webインストーラーでインストール
④index_dev.phpに自ドメインを追記
⑤問題なくなく稼働

[気になった点]
①エラーの「2.3.」ファイル内リーディングいたしましたが、該当行にはコードが見つからず

上記参考にしかならないとは思いますが、報告です。

**Comment by k-yamamura** [comment]
3.0.8からdebug用としてdumpライブラリを導入しており、
index_dev.phpを実行している時しか必要がないライブラリなのですが、
それがインストールされていないためエラーが発生しております。

解決方法はEC-CUBEディレクトリ直下で、以下のコマンドを入力してください。
```
php composer.phar update symfony/var-dumper symfony/debug-bundle
```

``` Could not open input file: composer.phar ``` というエラーが発生すれば、
```
curl -sS https://getcomposer.org/installer | php
```
と実行後、再度同じコマンドを入力してください。

**Comment by tomothumb** [comment]
早速の解凍ありがとうございます。
symfony/var-dumper
symfony/debug-bundle
この２つのパッケージは正常にはいってました。
MacのMAMP環境ですが、自分の環境が悪いだけのような気もしてきました。
新規インストールや別環境にてインストールしてみるなど、いろいろ試して改めて報告いたします。

**Comment by tomothumb** [comment]
新規インストールし
`
curl -sS https://getcomposer.org/installer | php
sudo php composer.phar update symfony/var-dumper symfony/debug-bundle
`
とすると正常にインストール完了しました。
composerのキャッシュディレクトリに書き込み権限がないようなエラーがでましたのでsudoしたら行けたという感じです。

3.0.7からのアップデートでも同じようにやったつもりだったんですけどね。

お騒がせしました。
