### ISSUE TITLE
存在しないbind名をurlやpathで指定するとエラーとなるが運用中はエラーを握りつぶしたい

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1370]
存在しない bind 名を twig で指定すると`RouteNotFoundException`が発生し、画面が正常に表示されない。
開発時はエラーが表示されても良いが、運用中は画面が表示されなくなる問題が発生する。

`{{ url('hoge') }}`と`{{ path('hoge')}}`が対象。

プラグインの無効化や、ページの削除で発生が想定される。

**Comment by nanasess** [comment]
完全に黙殺するのは問題だと思いますので、 `E_USER_WARNING` をスローするとかでしょうか。

**Comment by shhirose** [comment]
@nanasess 
画面が真っ白になったり、中断しなければ問題ないので、`E_USER_WARNING`の対応で問題ありません。

**Comment by ttsuru** [comment]
これって、 ``RouteNotFoundException `` じゃやぱり問題なんですかねぇ・・・・

**Comment by shhirose** [comment]
@ttsuru 
購入側としたら、見ようとしたページが真っ白になったりしたらちょっと嫌ですし、運営側としてもダメと判断される方が大多数かなと思います・・・。
個人経営ならまだ妥協してもらえる可能性もありますが、そうでない場合は構築者が責められるかなと思います。

**Comment by ttsuru** [comment]
@shhirose 
``RouteNotFoundException`` なので、真っ白にはならないと思います。
正常にリンクがはれていないのも問題なのではないでしょうか。

僕も ``E_USER_WARNING `` には賛成ですが、もう少ししっかりと対応理由を定義しといたほうが良いと思います。

**Comment by shhirose** [comment]
@ttsuru 
> `RouteNotFoundException` なので、真っ白にはならないと思います。

そうですね。システムエラー画面が表示されますね。

> 正常にリンクがはれていないのも問題なのではないでしょうか。

本件はリンク切れが発生した場合の対応なので、「リンクを正しくしてください」というわけにはいきません。
リンク切れを検知するまでに、どのようにして購入者に負担がないように対応するかという事になります。

**Comment by shinichi-takahashi** [comment]
これではなく？
http://silex-users-jp.phper.jp/doc/html/usage.html#error-handlers

**Comment by shhirose** [comment]
@shinichi-takahashi 
現在その対応が Application でされているので、システムエラー画面が表示されているのだと思います。

やりたいのは、twig 上で `{{ url('hoge') }}`と記載されていて、`hoge`は過去にルーティングとして存在していたけど、現在はなくなってしまった場合（例えばページを削除）に、システムエラー画面を表示したくないんです。
（ページを削除した人が、被リンク先を全て把握しているとは限らないため。）

システムエラー画面を表示してしまうと、例えばトップページでこの現象が発生した場合に、サイトとして機能しなくなってしまうので、`url`関数内部で例外が発生した際に`try-catch`などで、握りつぶし（ログ出力などは行う）、URLは表示されないが、ページとしては機能するようにしておきたいのです。

**Comment by shinichi-takahashi** [comment]
@shhirose んにゃ、これをプラグインでもなんでも外部から拡張したったらいいんちゃいますか？
`$e instance of RouteNotFoundException` みたいな感じで。
僕が作ったプラグイン機構からどう変わったかは追ってませんが、プラグイン側のRoutingが優先されるように設計してたはずなので外部からどうとでもできると思いますよ

**Comment by nanasess** [comment]
本体で対応して悪影響が出るようなものでもないので、本体で対応してもいいと思いますけど。

**Comment by shhirose** [comment]
PR してみました。
`E_USER_WARNING`を発生させ、システムエラー画面が表示されないようにしました。

取り込むかどうかはLOCKON様にお任せしようと思いますが、対応方法が適切か確認いただければ幸いです。

**Comment by ttsuru** [comment]
いい感じですね！
好みかもしれませんが debug の際はそのまま exception でもいいような気がしました。

**Comment by shhirose** [comment]
私もコーディングしながら再スローでいいかもとは思いましたが、ひとまず @nanasess さん提案の`E_USER_WARNING`にしてみました。

**Comment by shhirose** [comment]
マージされているのでクローズします。
