### ISSUE TITLE
index_dev.phpが使えない

### ISSUE THREAD

**Issue by mkobayashi** [EC-CUBE/ec-cube#1371]
・windows7
・xampp
環境で
index.php ==> index.php.bk
index_dev.php ==> index.php

としてページを見ようとするとエラーになる
エラーメッセージは

ClassNotFoundException in DumpDataCollector.php line 28:

**Comment by nanasess** [comment]
こちらと同様の事象でしょうか？
https://github.com/EC-CUBE/ec-cube/issues/1366#issuecomment-168112770

**Comment by k-yamamura** [comment]
恐らく同様の現象だと思われますので解決方法は、
下記URLの「デバッグモードの有効化」にあるEC-CUBE3.0.8から・・・の内容をご確認ください。
http://ec-cube.github.io/tips.html

今後も似たような問題が発生すると思いますので別途対応を行います。

**Comment by mkobayashi** [comment]
ご返信有り難うございます。

xampp

で行う場合はどうすればよいのでしょうか？
curlやphpコマンドをwindowsで扱えるのでしょうか？

**Comment by nanasess** [comment]
xampp の中に php.exe があると思いますので、これにパスを通せばできます。
curl を使わなくても、以下のコマンドで composer をインストールすることが可能です。
`php -r "readfile('https://getcomposer.org/installer');" | php`

**Comment by imgnation** [comment]
cygwinを使用し、上記の通り実行しました

 /cygdrive/c/xampp/php/php.exe -r "readfile('https://getcomposer.org/installer');" | /cygdrive/c/xampp/php/php.exe 

/html/index_dev.php

にアクセスした所

Whoops, looks like something went wrong.

1/1
ClassNotFoundException in DumpDataCollector.php line 28:
Attempted to load interface "DataDumperInterface" from namespace "Symfony\Component\VarDumper\Dumper".
Did you forget a "use" statement for another namespace?

と表示されます。
xampp環境でindex_dev.phpを使用するにはまだなにか足りないのでしょうか？

**Comment by nanasess** [comment]
```
/cygdrive/c/xampp/php/php.exe -r "readfile('https://getcomposer.org/installer');" | /cygdrive/c/xampp/php/php.exe 
```
上記のコマンドで composer.phar がダウンロードされると思いますので、続いて以下のコマンドを実行してみてください

```
/cygdrive/c/xampp/php/php.exe composer.phar update symfony/var-dumper symfony/debug-bundle
```

**Comment by imgnation** [comment]
composer.phar
はダウンロードされました

/cygdrive/c/xampp/php/php.exe composer.phar update symfony/var-dumper symfony/debug-bundle

を実行しようと思うのですが、symphonyのパスはどちらになるのでしょうか？
/vendor/symphony
で良いのでしょうか？

**Comment by nanasess** [comment]
`symfony/var-dumper symfony/debug-bundle` は、内部のパス指定ですので、このまま実行してみていただければ大丈夫です。

**Comment by mkobayashi** [comment]
ありがとうございます。
EC-CUBEのルートディレクトリから実行した所
index_dev.phpが動作するようになりました
