### ISSUE TITLE
SSL強制で無限ループ

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#1372]
config.ymlでforce_ssl: 1にしてSSLでアクセスするとリダイレクトの無限ループになります。
これ僕だけ？

**Comment by nanasess** [comment]
無限ループになるのは、 cloud9 でしたっけ？

**Comment by tao-s** [comment]
いや、CentOS+ApacheなVPSでもなりました。
確かちゃんとSSLかどうかを取れてないのが原因だった気が...

**Comment by giwa** [comment]
HTTPS -> AWS certificate manager- HTTP -> nginx - HTTP -> EC CUBE

上記のような構成で構築しました。
nginx で http でアクセスした場合 https にリダイレクトするように設定しました。
この場合、EC CUBEがhttpでアクセスしたものと判断し、EC CUBEによるhttpsリダイレクトが発生し、無限ループになりました。
EC CUBEのversionは3.0.9です。

**Comment by nanasess** [comment]
#1357 こちらも参考に

**Comment by trebla-on** [comment]
インストールの時にサイトへのアクセスを、SSL（https）経由に制限する選んだ場合はｈｔｔｐｓ判断できるバーリデトいります。
一部こちらに https://github.com/EC-CUBE/ec-cube/pull/1357 対応されてますみたい

**Comment by ryo-endo** [comment]
@trebla-on 
#1357 の対応(設定項目の追加)で回避はできそうでしょうか？
また、https判断できるバリデートは実装できそうですか？

**Comment by trebla-on** [comment]
@ryo-endo 
コメントを確認しましたが対応方法についてもっと詳しく聞きたいです。

> #1357 の対応(設定項目の追加)で回避はできそうでしょうか？ 

こちら了解です

>     https判断

これはインストールの時ロッジク入れるですね？
SSLチェックしたあとに次のステップでhttps判断おこなう
これでよろしいでしょうか？

**Comment by trebla-on** [comment]
インストールの時httpsチェックありますね、入れるつもりでしたが既にssl確認ロッジク実装されてます。
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/install/step3.twig#L62-L69
インストールの時はSSL確認ありますので無限ループならないはずです、ただ
「app/config/eccube/config.yml」の中にforce_ssl:１すると無限ループなります

**Comment by trebla-on** [comment]
こちら対応するならtrusted_proxies入れるしかないですね
http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html

**Comment by Yangsin** [comment]
さくらのレンタルサーバーで起きている事象 （ http://xoops.ec-cube.net/modules/newbb/viewtopic.php?forum=17&post_id=79931&topic_id=18570#forumpost79931 ） も同じかも。

**Comment by ryo-endo** [comment]
さくらレンタルサーバーでSSLを使用した場合、通常のバランサーなどが付加する`X-Forwarded-Proto` などのヘッダーが渡されない。
代わりに`HTTP_X_SAKURA_FORWARDED_FOR `ヘッダが渡されるので、このヘッダーがあればSSL接続だと判断するしかなさそう。

Application.phpの初期化処理の中に、以下の処理を書くことで、リダイレクトループは回避可能。
```
$request = Request::getInstance();
if ($request->headers->has('HTTP_X_SAKURA_FORWARDED_FOR')) {
    $request->server->set('HTTPS', 'on');
}
```

**Comment by ryo-endo** [comment]
X-Forwarded-Proto などのヘッダーが渡される環境であれば、3.0.14で取り込み予定の以下の対応でリダイレクトループは解消するはずです。
https://github.com/EC-CUBE/ec-cube/pull/1357

**Comment by ryo-endo** [comment]
3.0.14からconfig.ymlに追加された以下のオプション設定することで、
リダイレクトループ発生した環境でも、現象解決することを確認しましたので、Isssueをクローズさせていただきます。

```
trusted_proxies_connection_only: true
trusted_proxies:
    - 127.0.0.1/8
    - '::1'
```

※サイトが信頼されたロードバランサー・プロキシサーバからのみアクセスされる場合は、`trusted_proxies_connection_only: true`で動的に対応可能です。
※個別にIPアドレス指定する場合は、`trusted_proxies`に追記して設定できます。
※X-Forwarded-Protoなど必要なHTTPヘッダーが渡ってくることが前提条件。
