### ISSUE TITLE
Entity の public プロパティ

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1373]
基本的に getter/setter をオーバーライドしないという方針で問題なければ、 public プロパティにしてはいかがでしょうか？
Doctrine 2.4 から public プロパティが利用できるようです。

**Comment by ttsuru** [comment]
@nanasess 
どんな問題があってプロパティをpublicにする必要があるのでしょうか。
また、何が解決されるのかも教えていただきたいです。

ちなみに、現状privateになっているのはDoctrineの自動生成です。

**Comment by nanasess** [comment]
@ttsuru
public プロパティにすることによって、 getter/setter の必要が無くなり、コードの記述量を減らすことができ、開発効率が向上します。
Java では何年も前から議論されていることですが、多くのフレームワークで public プロパティを利用できるようになっていたり、アノテーションで記述できるようになっています。
http://d.hatena.ne.jp/Nagise/20141010/1412930502
http://tbd.kaitoy.xyz/2015/07/22/getters-setters-evil/
http://d.hatena.ne.jp/nowokay/20130730#1375153790

Doctrine 2.4 から public プロパティの利用ができるようになっているようなので、変更の提案です。

#846 で、  「getter のオーバーライドは良くない」というコメントをいただいていたので、オーバーライドしないのであれば、 getter/setter を生成する必要は少ないと思います。
読み取り専用のプロパティを用意したい場合等、特別な理由がある場合のみ、 getter/setter を作成すれば良いと思います。

もちろん、互換性の問題もあるのでメジャーバージョンアップの際に、段階的に導入できたら良いと思います。

**Comment by shhirose** [comment]
@nanasess 
私としては public フィールドにすることで開発効率が上がっても、管理、保守する上できつくなるので反対です。
Java と違って PHP は型の制限がメソッドを通さなければできないため、不具合が発生した際のデバッグがきつくなります。（私としてはプリミティブ型の setter には型チェックを入れて IllegalArgumentException を記述したいくらいです。）
1人で開発している分には問題ありませんが、複数人で開発している場合など特に注意する必要があります。
※DBからデータを取得する時だけ Entity を使用するのであれば public フィールドのみにすることは賛成です。

2つ目のリンクは getter/setter を使用せず、public フィールドを使用するという趣旨ではなく、機械的に getter/setter を使用するのではなく、適切なメソッド名にするべきという内容が主だと思います。
3つ目の lombok も getter/setter の記述量を減らすだけであり、カプセル化はしています。

**Comment by nanasess** [comment]
@shhirose 基本的には、 DB から値を出し入れする場合のみと思っています。 DB の値を直接扱わないプロパティの場合は、何らかの処理を伴うものだと思いますので、必然的に accessor が必要になります。

リンク先の件は、言葉足らずで申し訳ございません。 Java の Seasar2 で public フィールドが利用できるようになった際の経緯で、「機械的な getter/setter は意味がない」「lombok のような機能はフレームワークでサポートすべき」などという議論があった記憶があるのですが、元ネタのページを喪失していたので引用したのでした。

ただ、データ型のチェックは何とかしたいですね。。
本題とは外れますが、せめて、 2系の頃の以下のような命名規約があれば、少しはわかりやすいかなと。(最近の PHP のトレンドから外れるかもしれませんが)

- リテラルを格納する (つまり配列・オブジェクト以外の) 変数名は, すべて小文字を使用し, アンダーバーで区切る.
- 配列・オブジェクトの変数名はキャメルケースを使用する.

**Comment by kiy0taka** [comment]
現状、getter/setterを使って統一しているので、PRの受け入れ基準としてはこれまで通り、getter/setterのあるものを標準とします。
