### ISSUE TITLE
Shippingで県番号を取得できない

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1377]
$Shipping->getAddr0()
を行うと住所の1爪が取得できるが

$Shipping->getPref()
を行うと県番号が取得できていない

**Comment by ttsuru** [comment]
@imgnation 
```
$Shipping->getPref()
```
で取得できるのは ``Eccube\Entity\Pref`` のオブジェクトです。

**Comment by imgnation** [comment]
すみません。
その場合、県番号を取得するにはどのようにすればよいのでしょうか？

**Comment by ttsuru** [comment]
@imgnation 
``$Shipping->getPref()->getId()`` とかですね。
