### ISSUE TITLE
Application インスタンスをシングルトンに変更

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1380]
#1378 をリクエストしましたが、課題管理のため issue を作成しておきます。

以下の検証が必要

- ~~プラグインが別トランザクションとなってしまう問題の回避ができているか~~ 別途 try/catch の対応が必要
- [x] 同時アクセス時の排他制御に問題ないか
- [x] sub request での処理に問題ないか
- [x] プラグイン/本体 の migration で問題が発生した場合、正常にロールバックされるか
- ~~処理の途中で Connection/transaction がクローズされても問題ないか~~  #1360 の対応が必要

**Comment by chihiro-adachi** [comment]
ありがとうございます。

元々の問題は、PRにコメントいただいたとおり、migration内で新しくApplicationインスタンスを生成しておりDBのコネクションが複数生成され、エラーハンドリングができない、という点かと思います。

こちらについては、プラグインのmigration時の挙動を確認します。
その他の検証は少し方法難しいのですが、正常系全体をできるだけ複数人で触ってみますね。

**Comment by chihiro-adachi** [comment]
@nanasess 
こちら確認結果です。
migration時の挙動については、SQLエラー発生時にロールバック確認できました。
また、正常系全体の試験に関しても特に問題はなかったです。

データベースのコネクションが複数生成されてしまう問題については、#1378 で解消できていると思います。

トランザクション等の問題については、別途検討が必要ですね。
ご対応ありがとうございます。

**Comment by nanasess** [comment]
Merged from #1378
