### ISSUE TITLE
プラグイン機能に関する課題

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1381]
プラグイン機構に関する現状の課題を整理しました。
3.0.9では主にこちらの課題について対応予定です。
各項目の仕様などは、随時issueに起案していきます。

# twigのID、クラス化

idやclassが適切に振られていないため、 テンプレートへの差し込みが行いにくい。
id、クラスの命名規約を整備し、全テンプレートへ適用します。

関連：#1139
参考：https://app.codegrid.net/entry/bem-basic-1

# フックポイントの拡張

- テンプレート全体に対するフックポイントがない
- フォームの成功・失敗のハンドリングができない
- 本体側で登録されたEntityのIDが取得しにくい

などの課題があります。symfony2やdoctrineのeventを精査し、必要と思われるフックポイントの定義を行います。

関連：#1292 #1293 #1332 #1137  #587
参考：

- http://symfony.com/doc/current/components/http_kernel/introduction.html
- http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html

# プラグインのインストーラの改善

プラグインのインストーラのエラー処理を適切に行われていないため、空白ページになる、ゴミデータが残る、といった問題を解消します。

関連：#1333 #1329 #1317 #1328 #1319 #1245 #1380

# トランザクション関連

関連：#1360  #1245 #1380

**Comment by ttsuru** [comment]
@chihiro-adachi 

> 本体側で登録されたEntityのIDが取得しにくい

これって、POST_BIND 以降ならイベントないで ``$event->getData()->getId()`` で取得できるんじゃないでしょうか。

全体的に例えば、どういう問題があるという例があると改善しやすい気がします。

**Comment by chihiro-adachi** [comment]
@ttsuru 
ありがとうございます。
上記ケースでいうと、編集時は取得できるのですが、新規登録時にIDが取得できないです。※IDの発番は$app['orm.em']でflushした後になるので。
現状ではURLに付いてくるIDをrequestで取得する、という少々トリッキーな実装になってしまうので、解消できればと考えています。https://github.com/EC-CUBE/related-product-plugin/blob/master/Event.php#L80

**Comment by ttsuru** [comment]
@chihiro-adachi 
ご指摘の内容だと他にやり方があるような気がします。

**Comment by chihiro-adachi** [comment]
@ttsuru 
はい、そうですね。
イベント(フックポイント)周りの機構だと、FOSUserBundleで実装されているイベントの仕組みやDoctrine, Symfony2のイベントを調査しています。週明けにはプロトタイプ的なものをだせそうなので、またそのタイミングでレビューいただけるとありがたいです。

**Comment by chihiro-adachi** [comment]
#1492
