### ISSUE TITLE
ec-cube3.0.6 / 注文直後にエラー

### ISSUE THREAD

**Issue by trendworks** [EC-CUBE/ec-cube#1382]
下記操作後にアップ画像のようなエラーが発生します。

1. 商品をカートに入れる
　↓
2. レジに進む
　↓
3. 「注文する」をクリック

![order-finish-error](https://cloud.githubusercontent.com/assets/16642751/12228353/8faee334-b87d-11e5-90bd-946e05c8797f.png)

エラーが発生するも正常に注文処理が完了しており、マイページから注文履歴と詳細も表示できております。

似たような現象の投稿がありましたが、IDのフィールドがNullによるNull制約違反のものではなさそうです。

エラーが起こったときのログを下記に添付します。

[2016-01-11 15:49:10] myapp.INFO: < 302 https://xxxx.sakura.ne.jp/sales/html/shopping/complete [] []
[2016-01-11 15:49:10] myapp.CRITICAL: Doctrine\ORM\ORMException: The EntityManager is closed. (uncaught exception) at /home/xxxx/www/sales/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 129 {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): The EntityManager is closed. at /home/xxxx/www/sales/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:129)"} []
[2016-01-11 15:49:10] myapp.INFO: < 500 [] []

サーバーはさくらインターネットのスタンダードプランです。

■ 各バージョンなどの環境：
・サーバーOS:
　FreeBSD www951.sakura.ne.jp 9.1-RELEASE-p24 FreeBSD 9.1-RELEASE-p24 #0: Thu Feb 5 10:03:29 JST 2015 root@www3304.sakura.ne.jp:/usr/obj/usr/src/sys/SAKURA17 amd64

・DBサーバ
　MySQL 5.5.38-log 

・WEBサーバ
　Apache/2.2.29 

・PHP
　5.4.45

■ 現在のインストールプラグイン
　[オーナーズストアプラグイン]
　・MailMagazine(MailMagazine)
　・チェックした商品(CheckedItem)
　・メンテナンス管理(MaintenanceManager)
　・メールテンプレート機能拡張プラグイン(MailTemplateEdit)
　・ 商品編集用csv(ProductEditCsv)
　・売上集計プラグイン(SalesReport)
　・配送伝票番号プラグイン(ShipNumber)
　・顧客トラッカー(CustomerTracker)
　[独自プラグイン]
　・OrderPdf(OrderPdf)　by EC-CUBEカスタマイズダウンロード(https://www.kaiplus.com/)

**Comment by shhirose** [comment]
プラグインを有効/無効を切り替えて試してみるか、テスト環境であれば以下の手順でデバッグモードで動作させエラーログを出力してみてください。
※可能であればローカルに同じ環境を作ることをおすすめします。

{EC-CUBEインストールディレクトリ}/html/index_dev.php
``` PHP
// ・・・
use Symfony\Component\Debug\Debug;
use Symfony\Component\Yaml\Yaml;

// This check prevents access to debug front controllers that are deployed by accident to production servers.
// Feel free to remove this, extend it, or make something more sophisticated.

$allow = array(
    '127.0.0.1',
    'fe80::1',
    '::1',
    '{ここに自身のネットワークのグローバルIPを指定}',
);

if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || !in_array(@$_SERVER['REMOTE_ADDR'], $allow)
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}
// ・・・
```

以下のURLでアクセスすればデバッグモードで閲覧できます。
https://xxxx.sakura.ne.jp/sales/html/index_dev.php/

※指定したグローバルIPからはデバッグモードで見れてしまうので、**ログを確認したら追加したIPは削除してください。**

**Comment by trendworks** [comment]
コメントありがとうございます。

デバッグモードで動作させてみたところ、ご指摘いただきました通りプラグインが影響しておりますことが確認できました。

影響を与えていたのは「顧客トラッカー(CustomerTracker)」ということがわかりまして、無効にして停止させたところ正常に注文受付完了画面が表示されるようになりました。
顧客トラッカープラグインそのもののバグ？
それともインストールされているプラグインの相性問題で競合が起きているのでしょうか？

デバッグモードで取得したエラーログを下記に添付させていただきます。

Whoops, looks like something went wrong.
------------------------------------------
1/1 　　ORMException in ORMException.php line 129: The EntityManager is closed.
---
    1. in ORMException.php line 129
    2. at ORMException::entityManagerClosed() in EntityManager.php line 708
    3. at EntityManager->errorIfClosed() in EntityManager.php line 544
    4. at EntityManager->persist(object(History)) in CustomerTracker.php line 62
    5. at CustomerTracker->recordHistory(object(FilterResponseEvent), 'eccube.event.app.renderafter', object(EventDispatcher))
    6. at call_user_func(array(object(CustomerTracker), 'recordHistory'), object(FilterResponseEvent), 'eccube.event.app.renderafter', object(EventDispatcher)) in EventDispatcher.php line 160
    7. at EventDispatcher->doDispatch(array(array(object(CustomerTracker), 'recordHistory')), 'eccube.event.app.renderafter', object(FilterResponseEvent)) in EventDispatcher.php line 48
    8. at EventDispatcher->dispatch('eccube.event.app.renderafter', object(FilterResponseEvent)) in CustomerTracker.php line 28
    9. at CustomerTracker->Plugin\CustomerTracker\{closure}(object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
    10. at call_user_func(object(Closure), object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher)) in WrappedListener.php line 61
    11. at WrappedListener->__invoke(object(FilterResponseEvent), 'kernel.response', object(EventDispatcher))
    12. at call_user_func(object(WrappedListener), object(FilterResponseEvent), 'kernel.response', object(EventDispatcher)) in EventDispatcher.php line 160
    13. at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(FilterResponseEvent)) in EventDispatcher.php line 48
    14. at EventDispatcher->dispatch('kernel.response', object(FilterResponseEvent)) in TraceableEventDispatcher.php line 124
    15. at TraceableEventDispatcher->dispatch('kernel.response', object(FilterResponseEvent)) in HttpKernel.php line 187
    16. at HttpKernel->filterResponse(object(RedirectResponse), object(Request), '1') in HttpKernel.php line 169
    17. at HttpKernel->handleRaw(object(Request), '1') in HttpKernel.php line 68
    18. at HttpKernel->handle(object(Request), '1', true) in Application.php line 586
    19. at Application->handle(object(Request)) in Application.php line 563
    20. at Application->run() in index_dev.php line 87

**Comment by shhirose** [comment]
@trendworks 
> 顧客トラッカープラグインそのもののバグ？
> それともインストールされているプラグインの相性問題で競合が起きているのでしょうか？

特定するには顧客トラッカー以外のプラグインを無効化してから再度動作させ、正常終了するか、異常終了するかを確認ください。

異常終了した場合は、プラグイン提供元のお問い合わせ先に環境と現象をご連絡ください。

※顧客トラッカーのソースを軽く追った感じだと問題ないように思えますが。もし正常終了したらその他のプラグインで`EntityManager`を`close`している可能性がありますね。

**Comment by Yangsin** [comment]
こちら本体の課題ではないようですので、クローズさせていただきます。
開発コミュニティもご利用ください。 http://xoops.ec-cube.net
