### ISSUE TITLE
複製した商品で、「規格の初期化」ができない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1383]
1. 規格を含む商品を複製する
2. 複製した商品を登録する
3. 複製した商品の規格の「商品規格を初期化」をクリック
4. 画面が真っ白になる

以下のエラーが発生する模様。

```
FatalErrorException in ProductClassController.php line 412: Error: Call to a member function setDelFlg() on a non-object
```

複製した商品は、デフォルトの商品規格(class_category_id1, class_category_id2 が null)が生成されていないのが原因

### 参考
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?forum=9&post_id=74189&topic_id=16859

**Comment by chihiro-adachi** [comment]
#1389 にて対応
