### ISSUE TITLE
Myページのお届け先を登録上限数を越えて登録しようとした場合のExceptionが不適切

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1387]
`NotFoundHttpException` をスローしているが HTTP Status 413 Payload Too Large または 406 Not Acceptable を返して、適切なエラーメッセージを表示するべき。

**Comment by nanasess** [comment]
`Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException` をスローするのが良さそう

**Comment by Yangsin** [comment]
#1735 に集約する形でクローズします。
