### ISSUE TITLE
マイページ-お届け先編集-変更ページにページレイアウトが適用されない

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1396]
マイページ-お届け先編集
に進み
「変更」
をクリックし、変更ページになると
Blockのいくつかが表示されなくなります。

**Comment by tomothumb** [comment]
追加報告です。

v3.0.10
管理画面で、「マイページ-お届け先編集」がページリストに表示されないため、「マイページ-お届け先編集」のページ編集/レイアウト編集できません。

フロントのマイページから、お届け先住所を変更しようとすると、ヘッダ・フッタなどへ全ページに反映させるようなブロックも表示されません。

**Comment by ryo-endo** [comment]
#1700 で対応済みのため、CLOSEします。
