### ISSUE TITLE
全ページ適用ブロックが未使用ブロックに表示されて、同一ブロックを複数配置できてしまう

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1405]
以下の手順で操作すると、ブロックが複数表示されてしまう。（フロント側でも複数表示される）

1.トップページ以外にブロック（A）を配置
2.トップページにブロック（A）を配置
3.トップページのブロック（A）を全ページ適応とする
4.1のページで同一ブロックが複数配置された状態となる

トップページ
![top](https://cloud.githubusercontent.com/assets/12494780/12406724/1d953750-be93-11e5-9a37-f611c7fcdf1e.png)

商品一覧ページ
![product_list](https://cloud.githubusercontent.com/assets/12494780/12406732/2b35cd02-be93-11e5-91b1-067749d3329d.png)

**Comment by Yangsin** [comment]
データ構造レベルで修正が必要なため3.1での検討事項とします。

**Comment by okazy** [comment]
4.0では「全ページ適用」という使用がなくなり、レイアウトグループを作成する方式になったため、こちらの問題はなくなりました。
