### ISSUE TITLE
プラグイン課題：共通フックポイント仕様

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1410]
現行のbefore/after等のフックポイントの改善

## 課題

#1292 #1293 #1332

### 変更点
- 既存のフックポイントは互換性維持のため残しておく
- symfony2 eventベースのフックポイントを追加する
    - http://symfony.com/doc/current/components/http_kernel/introduction.html
- 管理画面/フロント画面/ルーティングの単位で定義する

### フックポイント一覧

| 画面種別         | ec-cubeフックポイント名               | symfony2イベント名       | 実行タイミング                                                                                       |
|------------------|---------------------------------------|--------------------------|------------------------------------------------------------------------------------------------------|
| フロント画面     | eccube.event.front.request            | KernelEvents::REQUEST    | リクエスト生成時。既存のBeforeフックポイントに相当。ルーティング解決後、認証処理実行前に実行される。 |
| フロント画面     | eccube.event.front.controller         | KernelEvents::CONTROLLER | コントローラ実行前。マイページなど認証が必要な画面では認証処理実行済の状態、ただし未ログイン時は実行されない。                                   |
| フロント画面     | eccube.event.front.response           | KernelEvents::RESPONSE   | レスポンス生成時。既存のAfter/Renderフックポイントに相当。                                           |
| フロント画面     | eccube.event.front.exception          | KernelEvents::EXCEPTION  | 例外発生時。                                                                                         |
| フロント画面     | eccube.event.front.terminate          | KernelEvents::TERMINATE  | アプリケーション終了時。既存のFinishフックポイントに相当。                                            |
| 管理画面         | eccube.event.admin.request            | KernelEvents::REQUEST    | リクエスト生成時。既存のBeforeフックポイントに相当。ルーティング解決後、認証処理実行前に実行される。 |
| 管理画面         | eccube.event.admin.controller         | KernelEvents::CONTROLLER | コントローラ実行前。認証処理実行済、ただし未ログイン時は実行されない                                  |
| 管理画面         | eccube.event.admin.response           | KernelEvents::RESPONSE   | レスポンス生成時。既存のAfter/Renderフックポイントに相当。                                           |
| 管理画面         | eccube.event.admin.exception          | KernelEvents::EXCEPTION  | 例外発生時。                                                                                         |
| 管理画面         | eccube.event.admin.terminate          | KernelEvents::TERMINATE  | アプリケーション終了時。既存のFinishフックポイントに相当。                                            |
| ルーティング単位 | eccube.event.route.[route].request    | KernelEvents::REQUEST    | リクエスト生成時。既存のBeforeフックポイントに相当。ルーティング解決後、認証処理実行前に実行される。 |
| ルーティング単位 | eccube.event.route.[route].controller | KernelEvents::CONTROLLER | コントローラ実行前。マイページや管理画面など認証が必要な画面では認証処理実行済の状態、ただし未ログイン時は実行されない。                                   |
| ルーティング単位 | eccube.event.route.[route].response   | KernelEvents::RESPONSE   | レスポンス生成時。既存のAfter/Renderフックポイントに相当。                                           |
| ルーティング単位 | eccube.event.route.[route].exception  | KernelEvents::EXCEPTION  | 例外発生時。                                                                                         |
| ルーティング単位 | eccube.event.route.[route].terminate  | KernelEvents::TERMINATE  | アプリケーション終了時。既存のFinishフックポイントに相当。

**Comment by ttsuru** [comment]
@chihiro-adachi 
> eccube.event.route.[route].controller
> コントローラ実行前。認証処理実行済、ただし未ログイン時は実行されない。

こちらですが、「認証が必要な場合は」認証処理実行済、ただし未ログイン時は実行されない。のほうが良い気がします。

**Comment by chihiro-adachi** [comment]
@ttsuru 
ありがとうございます。すみません、おっしゃっていただいた挙動が正しいです。
マイページや管理画面など認証が必要な画面は、認証処理が実行済です。未ログインの場合は、CONTROLLERイベントは起動しないです。

**Comment by chihiro-adachi** [comment]
#1492
