### ISSUE TITLE
メールアドレスが新規登録も削除もできなくなる

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1412]
1.新規登録
2.メールアドレスを含む情報を入力して確認メール送信
3.確認メールをクリックしないうちに紛失する

すると使用したメールアドレスで
・新規登録しようとする
==> 「このメールアドレスは既に登録されています。」
・ログインしようとする
==> 「ログイン情報が間違っています」

となり、そのメールアドレスが二度と使用できなくなる

**Comment by nanasess** [comment]
#1178 こちらと重複ですかね。

**Comment by imgnation** [comment]
あ、同じですね

**Comment by nanasess** [comment]
重複ということでクローズしておきます
