### ISSUE TITLE
新規登録で仮登録メールが届かない

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1413]
新規登録を実行すると

・登録画面
==> 入力
・確認画面
==> 登録
・結果画面
==> 「仮登録メール送りました」

と表示されますが、実際に仮登録メールが届きません。
この場合、どのファイルからチェックしていくべきでしょうか？

**Comment by nanasess** [comment]
こちらを参考に、メールの送信ログを取得してみてください
http://qiita.com/nanasess/items/c80f4eb2dd9390b8e510

**Comment by imgnation** [comment]
ありがとうございます。
