### ISSUE TITLE
Admin\Content\FileController::create(), upload() の HTTP メソッドチェック

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1415]
POST かどうかのチェックを入れる必要がある

**Comment by nanasess** [comment]
upload() は、 `Symfony\Component\HttpFoundation\File\UploadedFile::move` で `is_uploaded_file()` をコールしていますが、念のため。

**Comment by trebla-on** [comment]
PR: #2025 で対応しました。
