### ISSUE TITLE
【機能改善/プラグイン】設置のみのプラグインを事故防止のため管理画面に一覧を表示する

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1420]
[ 前提 ]
・デベロッパー様の要望などで、置くだけで動プラグインが欲しいという要望がある。
・EC-CUBE3ではデフォルトで本要望を満たす機能を構築している。
[ 問題 ]
・どんなプラグインが稼働しているかわからない。
・稼働プラグインがわからないため、誤削除を引き起こす可能性がある
[ 対応方法 ]
・プラグインフォルダに設置しただけのプラグインも一覧に表示させる
※ただし、事故防止の観点から「アップデート・有効・無効 」は管理画面から行えない
※事故防止の観点から画面には「アップデート・有効・無効 」を行わないが、
機能事態は必要と考え、別Issue(#1421)で対応する。

**Comment by chihiro-adachi** [comment]
#1446 で対応しました。
