### ISSUE TITLE
【機能改善/プラグインコンソールコマンド】設置だけでプラグインを稼働させた場合マイグレーションを行える様にコンソールコマンドを追加

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1421]
【機能改善/プラグインコンソールコマンド】
[ 前提 ]
・デベロッパー様の要望などで、置くだけで動プラグインが欲しいという要望がある。
・EC-CUBE3ではデフォルトで本要望を満たす機能を構築している。
[ 問題 ]
・前提で述べた機能に対して、以下の不足があり、開発の容易性を妨げている
①マイグレーションの動的な実行
※マイグレーションファイルの呼び出しがインストール時にしか
呼び出されない
[ 対応方法 ]
・コンソールコマンドに設置プラグイン向けの、マイグレーション実行機能を追加する
・追加コマンドは「sandbox:install/sandbox:uninstall/sandbox:disable/sandobox:enable/reload」とする
・追加コマンドの一つ、「reload」は本件の趣旨からは関係がないが、
プラグイン開発時にインストール済みプラグインのマイグレーションをアンインストール→インストールできると
便利であるとの要望があったため、あわせて追加を行う

**Comment by ttsuru** [comment]
これって、本当に必要なんでしょうか。
管理画面に「未インストールプラグイン」的な内容を表示して、インストール/アップデートなどを行えれば良いと思いました。

**Comment by ttsuru** [comment]
refs #1423

**Comment by ttsuru** [comment]
あと、非常に重要なことだと思いますが、実装前にチケットを作って本当にその機能が必要かを意見を募ったほうがよいとおもいます。
issue と PR が同時と言うのはIssueを立てる意味がほとんど無いと思います。

**Comment by ttsuru** [comment]
本件ですが、「プラグインのマイグレーション実施」部分のみのコマンドであれば ``sandbox`` よりも ``migrate`` などのほうがなどのほうが直感的かと思います。

**Comment by geany-y** [comment]
@ttsuru
レビュー、コメント有難うございます。 
>非常に重要
>issue と PR が同時と言うのはIssueを立てる意味がほとんど無いと思います

こちら思慮不足でした。
今後改善いたします。

>これって、本当に必要なんでしょうか。
>管理画面に「未インストールプラグイン」的な内容を表示して、インストール/アップデートなどを行えれば

本機能の趣旨の説明が不足しているのかも知れません。
誤解を与えずお伝えしたいため、本内容のコメントは熟考のうえ、週明けにコメントさせていただきます。
>本件ですが、「プラグインのマイグレーション実施」部分のみのコマンドであれば sandbox よりも migrate な>どのほうがなどのほうが直感的

こちらも、機能の趣旨の説明不足からきているめんもあると思いますが、コマンド名は確かに悩んでいる
ところがあります。
migrateはもともとのコマンド自体にmigrateというものがあるため、混同を招きそうで避けた次第です。
dirty、dryなども考えましたが、何か妙案がないでしょうか?

**Comment by geany-y** [comment]
@ttsuru 
本件、@adachiと内容確認いたしましたが、機能説明が明確でなく、
意図が伝わってなかったと思いますので、再度以下にまとめた内容を掲載いたします。
お手数ですが、ご確認いただけますと幸いです。

##  前提

現状、プラグインのインストーラ(PluginManager)を開発する手順は以下のとおり

1. PluginManagerを作成
2. 該当のプラグインをアーカイブする
3. 該当のプラグインを削除
4. プラグインのインストール画面からインストール

## 課題

- プラグインのインストーラ(PluginManager)を作成する場合、前提の手順を踏む必要があり、開発しにくい
- 誤って開発中プラグインを削除してしまうケースもある

## 対応案

- PluginManagerのinstall/uninstall/disable/enableを直接呼び出せるとよい
- 既存のPluginCommandを拡張し、上記を実行できるコマンドを追加するようにする

**Comment by geany-y** [comment]
@ttsuru 
本件@adachiと再度確認いたしましたが、機能の説明が不明瞭で誤解を招く
内容でした。
以下に再度まとめましたので、ご確認いただけますと幸いです。

##  前提

現状、プラグインのインストーラ(PluginManager)を開発する手順は以下のとおり

1. PluginManagerを作成
2. 該当のプラグインをアーカイブする
3. 該当のプラグインを削除
4. プラグインのインストール画面からインストール

## 課題

- プラグインのインストーラ(PluginManager)を作成する場合、前提の手順を踏む必要があり、開発しにくい
- 誤って開発中プラグインを削除してしまうケースもある

## 対応案

- PluginManagerのinstall/uninstall/disable/enableを直接呼び出せるとよい
- 既存のPluginCommandを拡張し、上記を実行できるコマンドを追加するようにする

**Comment by ttsuru** [comment]
@geany-y 
ありがとうございます。
確かに現状のプラグイン作成手順は面倒だと思います。現状だと2系と変わらずですね。

``sandbox:disable`` ``sandobox:enable`` の2つについてはプラグイン自体の有効無効なので、そのまま、 ``plugin::enable`` ``plugin::disable`` でよいのではないでしょうか。

``reload`` は ``reinstall`` だとわかりやすいかなと個人的には思います。

コンテストに応募された方もプラグイン開発で困られた点があるとおもいますが、そのあたりっていかがでしょうか。

**Comment by ttsuru** [comment]
install / uninstall については現状のコマンドと一緒にしてしまっても良いのではと思いました。
オプションでコマンドのみ実行などでもよいのではないでしょうか。

refs https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Command/PluginCommand.php

**Comment by ttsuru** [comment]
元の `plugin:*` コマンドですが、1つのクラスになっていますが、複数のクラスに分けたほうがよさそうですね。
http://symfony.com/doc/2.7/components/console/introduction.html

**Comment by geany-y** [comment]
@ttsuru
早速のご確認、レビュー有難う御座います。

>確かに現状のプラグイン作成手順は面倒だと思います。現状だと2系と変わらずですね。
>コンテストに応募された方もプラグイン開発で困られた点があるとおもいますが、そのあたりっていかがでしょうか

→私自身多くの事例を知っているわけではありませんが、少なくとも、近親の開発者、私自身、いちいち圧縮をかけないと、データーベース情報が更新できない点について不満が残りました。

>plugin:sandbox:disable plugin:sandobox:enable の2つについてはプラグイン自体の有効無効なので、そのまま、 plugin:enable plugin:disable でよいのではないでしょうか。

→そうですね、こちらの方が直感的ですね。
本日一日本内容を、このままとして、他の妙案がなければ、採用させていただこうと考えています。

>元の plugin:* コマンドですが、1つのクラスになっていますが、複数のクラスに分けたほうがよさそうですね。

→こちらの内容は以下ともつながってきますね。

>install / uninstall については現状のコマンドと一緒にしてしまっても良いのではと思いました。
オプションでコマンドのみ実行などでもよいのではないでしょうか。

→私自身の咀嚼の問題もあるので、こちらは相談を行いながら進めていきたく思います。

**Comment by ttsuru** [comment]
@geany-y 

sandbox:install や sandbox:uninstall ですが、直感的には以下の様な感じが直感的かと思いました。

``php ./app/console plugin:install --only-db PluginName``
``php ./app/console plugin:db:install PluginName``

的な感じが直感的かなと思いました。

**Comment by geany-y** [comment]
@ttsuru
噛み砕いての説明有難う御座います。

>直感的には以下の様な感じが直感的かと思いました。
>php ./app/console plugin:install --only-db PluginName
>php ./app/console plugin:db:install PluginName

→なるほどです、クラスわけも考えつつ見直してみます。
有難う御座います。

**Comment by ttsuru** [comment]
@geany-y 
既存のコマンドにDBのコマンドのみを実行するオプションでも良いかなと思いました。

**Comment by geany-y** [comment]
@ttsuru
ご意見有難う御座います。

>既存のコマンドにDBのコマンドのみを実行するオプションでも良いかなと思いました。

→こちら、わかり易く、効率的に感じました。
→この路線で相談を行いたいと思います。

有難う御座います。

**Comment by ttsuru** [comment]
@geany-y 
他の方にも意見を聞いてみてください！
あと、uninstall はconfirmなしで実行できてしまうのは罠ですね。直接は関係ないので、本件が終わってからチケット化しておきます。

**Comment by geany-y** [comment]
@ttsuru

>他の方にも意見を聞いてみてください！
→有難う御座います、皆さんのお知恵もお借りいたします。

>あと、uninstall はconfirmなしで実行できてしまうのは罠ですね。

→ご指摘の現状仕様だと全てが台無しになってしまう可能性がありますね。。

>本件が終わってからチケット化しておきます。

→有難う御座います。
非常に助かります。

**Comment by chihiro-adachi** [comment]
#1446　で対応しました。
