### ISSUE TITLE
Admin\Order\MailController::mailAll() で $_GET を参照している

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1427]
`$_GET` の値を参照して、クエリストリングから order_id を取得しているが、お作法的に良くない。
フォームの値をきちんと POST して Request オブジェクトから取得するべき

**Comment by ttsuru** [comment]
refs https://github.com/EC-CUBE/ec-cube/blob/dfbacfecb32536b96f4fe72c001247ab3e96ed1f/src/Eccube/Controller/Admin/Order/MailController.php#L249

**Comment by nanasess** [comment]
すみません、、同じ URL をコピーまでしておいて貼りつけるの忘れてました汗
ありがとうございます

**Comment by ttsuru** [comment]
Symfony Form はなれるまで難しいですが、なれてしまうとフォームがクラス化されているので、バグや変なパラメーターが入りづらいですね。

**Comment by ryo-endo** [comment]
#1568 で対応。
