### ISSUE TITLE
プラグイン開発ルールについて

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1436]
プラグインの開発ルールのようなものを定められませんでしょうか。

例えば、app/Plugin 以下にはシステムから生成されるファイルを置かないなど、ルールづけできると嬉しいです。

**Comment by ryo-endo** [comment]
勝手ながら、github.ioのIssueに移動させていただきました。
https://github.com/EC-CUBE/ec-cube.github.io/issues/78
