### ISSUE TITLE
プラグイン改善：Twigテンプレートに対するID追加

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1442]
## 課題事項

idやclassが適切に振られていないため、 テンプレートへの差し込みが行いにくい。
idの命名規約を整備し、全テンプレートへ適用する。

## TwigのID命名について

BEMをカスタマイズし、命名規約を策定する

[BEMについて](https://app.codegrid.net/entry/bem-basic-1)

## 凡例

`id="B__E--M"`

## 共通事項

- jQueryやCrawlerでのテンプレート差し込みを容易にすることを目的とする
- classについては利用せず、idのみ付与する
- スネークケースで記述 (各名称で単語が区切れる場合は"_"(アンダースコア)を使う)
    - 例)`osaka_umeda__gozen_tenki--hare`
- 以下はスネークケースの規約から除外する
    - ※すでに他の要素で使用されているid名やclass名

### B(ブロック)

画面内表示項目の共通した情報のかたまりをブロックとし、以下に準ずる

- `[ページ名]_[表示情報の内容]_[表示形式]`
- 上記において「表示形式」は省けるものとする
- 例) `customer_search_box/product_result_list etc...`

### E(エレメント)

ブロックとの区切りは`「__ ( ダブルアンダースコア )」`とする

ブロックに内包されているものとし以下に準じ、状況に応じ以下優先順位で複数組み合わせる

- `[ページ名]_[表示情報の内容]_[表示形式]__[ブロックでの位置]（hreader/body etc... ）`
- `[ページ名]_[表示情報の内容]_[表示形式]__[部品の役割(名詞が望ましい)] ( menu/area etc.. )`
- `[ページ名]_[表示情報の内容]_[表示形式]__[Form要素などの部品名称] (payment/name/price etc..)`
    - 例) グローバルナビゲーションの`<li>`はmenu、商品リストの`<li>`はlistなど。
    - `<button>`はbutton など

### M(モディファイア)

原則、そのタグの役割や状態

- 例) `<a>`はlink、`<div>`はcolumn、`<td>`はunitなど
- ループされている箇所は、動的に引っ張ってくることができる数字(商品IDなど)
    
以下の書式に準ずる

- `[ページ名]_[表示情報の内容]_[表示形式]__[Form要素などの部品名称 (Twigの変数名) ]--[連番 or 要素の状態]`

### その他実装にあたっての注意事項

- 既についているidやclass名は変更しない。
- IDを付与する位置
    - 各部品(機能)毎の最上層ブロック ( 検索フォーム/リストテーブル/メニューなど )
    - 動的に変化する部品の最上層ブロック( アコーディオンなどJSで制御されているもの )
    - フォーム要素の各部品
    - ドロップダウンメニューの親要素
    - インラインメニューの親要素
    - ボタン
    - ボタンの役割を果たすアンカータグ
- ポイント
    - IDのブロックを見て、そのブロックの役割が理解できることが望ましい
    - 単語の選定に悩む際は、出来るかぎりページ内にある単語を組み合わせる
    - 編集画面最下部の「戻る」などのボタン及びリンクがあった際は、その親要素(div等)に以下の名称を用いる
        - 例) `product_edit_[button or link」`
    - Form要素(Elementの際)にIDを付与する際は、`<label>`タグがあれば、`<label>`タグの親要素、なければ、すぐ上のparentにIDを付与する
    - ボタンにIDがない場合は必ず名称をつける( ボタン・リンク形式ボタンに限り、BEMの限りではなく役割をつける )
        - 例) `link-back/buton-search`など
    - フロントの場合、headerやfooterなど、default_frame.twigで枠組みとして設定されているidは、ブロック位置が変わった時に使えなくなるので使わない。

### 参考実装

- 商品一覧/商品登録(管理画面)
  - https://github.com/EC-CUBE/ec-cube/compare/master...geany-y:bem_product

**Comment by tomothumb** [comment]
プラグイン作成時に、不便だと感じてた所の改善なので、興味を持ちました。
一読した所、違和感を感じる所や、ECCUBEプラグイン開発であれ、jQueryであれ、またハマるのではと感じるところがありますので、幾つか提案致します。

## BEMという名称について
BEMの原則に従うのは良いと思います。
ただ、BEM説明の項目、厳密には**BEMのECCUBE解釈の説明**のようですので、混乱を招きます。
この棲み分けで行くのであれば、
SBEM（Section,Block,Element,Modifier）みたいなネーミングにして（いまパッと考えただけです）、
BEMのECCUBE用の拡張解釈と近くに併記する方が混乱を招かないかなと。
もしくは、そのまま、「BEMのECCUBE解釈の説明」とするか。

------
以降、具体的な内容になります。

## ページ名のPrefixは不要ではないか
**BodyタグにそのページのID**を振ることで、BEMでのページ名プレフィックスが不要になります。
結果スマートで、複数ページにまたがるプラグインの作成も容易になります。
例えば、管理画面の場合、似たようなページが複数あります。

■リスト系
- /admin/content/page
- /admin/content/block

■編集ページ系
- /admin/product/product/new
- /admin/setting/shop
- /admin/setting/shop/tradelaw

このような場合、ページ名のPrefixがついてしまいますと、冗長になるケースがあります。
極端な例ですが、架空のコードサンプルですが、ページナビを操作にしたい場合、
```
$('#admin_content_page_[Section]__pagination').....
$('#admin_content_block_[Section]__pagination').....
```
のように、一つの処理に複数ページ分のコード記述を強制されます。
一方、ページプリフィックスをなくすと、1つのコードで、全ページの同じ箇所のページナビに適応できます。
```
$('#[Section]__pagination').....
```
もし、特定のページだけ処理させたいのであれば、BodyタグにIDが振られていれば、セレクタにページのIDを付与するだけで解決します。
```
$('#admin_content_page #[Section]__pagination').....
```


## 一意となるよう、セクション/ブロック名を設定
前項の、ページ名をプレフィックスを排除する流れになった場合、シンプルになりすぎてしまうIDがあるので、ID衝突の危険性をさけ、セクション名はしっかりつける。
例：
```
$('#[SectionA_BlockB]__button--save').....
$('#[SectionB_BlockA]__button--save').....
```


## IDのみでなく、classも部分的に併用
ぱっと思いつくのが、以下2ケース。

1）**複数ブロックの共存する要素を効率化**
例：ページナビゲーションで、一覧リスト上下に挿入される可能性があるページナビ、
```
<div id="pagenavi__above" class="pagenavi">...</a>
<div id="pagenavi__bellow" class="pagenavi">...</a>
```
これも、$(".pagenavi")とするだけで、同じ要素をまとめて変更できるようになります。

※ なお、この場合、surfixが揃うよりprefixが揃える方が解りやすいです。

- x : above__pagenavi--next
- x : bellow__pagenavi--next
- o : pagenavi__above--next
- o : pagenavi__bellow--next

----------

2）**状態の変更の可能性の要素**

DOMでゴニョゴニョする場合、class（BEMでいうModifierの部分)を操作し、状態を管理することが多いかと思います。IDで状態を管理することは、基本NGのはずです。
参考実装を拝見しましたが、if文で次のようなボタンがありました。
```
[Block__BUTTON]--enable
[Block__BUTTON]--disable
```
IDで状態まで管理してしまうと、今後、Ajaxなどを活用し、ページ遷移なしで、**レコードをアップデートするような非同期で処理を取り入れる場合、状態の切り替え不可能になります。** (親要素のDOMをごろっと書き換えることもできますがスマートじゃない）
ですので、状態はclassに移されるべきかと。
```
<button id="[Section__BUTTON]" class="disable">
```
DOM操作も、$("#[Section__BUTOON].disable").....のようにセレクタ指定できますし。

ちなみに、「#[Section__BUTTON]--disable」と、「#[Section__BUTTON]--enable」の２つのボタンが、同ページに共存するようなことがある場合、それはバグを生むシチュエーションのはずですし、もっと適切な命名があるはずと思います。

これらの原因を生みそうな、classに入れるべきか、慎重に考慮すべきモディファイアを、思いつく限り記載しておきます。

- disable/enable
- show/hide
- on/off
- active/deactive
- open/close（アコーディオンの開閉用途などでのケース）
- toggle
- checked
- （現在ページを表す、current も、classで操作したいところです）

ちなみに、エレメントの役割をあらわす、モディファイアの使い方が良いと思います。
例
#[BUTTON]--save
#[BUTTON]--pdf
#[TABLE_ROW]--1
#[TABLE_ROW]--2

--------

以上、思いついたところです。
フォーム要素などとことんユニークであるべき項目は厳密に、
一方、汎用的にスべき所は緩めにすべきでは。というところですね。

**Comment by ttsuru** [comment]
僕も、単純に長すぎるIDや命名規則は実装が大変になるだけで、あまり意味が無いように感じます。

refs
http://qiita.com/soarflat/items/4f2e3ada77477a1f4a32
http://tech.recruit-mp.co.jp/front-end/architecture-bootstrap-bem/

**Comment by ttsuru** [comment]
また、BEMはCSS実装のために行うものであって、プラグインのためであれば @tomothumb の内容のほうが良いと思います。
classを利用しないでidのみを付与するのでは、再利用性も低いように感じます。

Formに関しては、FormとTwigのみで実装する方法にすれば、Viewの書き換えなしに、プラグインからFormを拡張できると思います。

```
{{ form_widget(form) }}
```

関連して、IDについても Form Themeないで自動生成するようにすれば、手間もなくなるように感じます。
現状、一つづつ手動でformをrenderingしていますが、特に意味があるようには感じません。

**Comment by chihiro-adachi** [comment]
@tomothumb
ありがとうございます。

- プラグインやjQueryで拡張しやすく(css設計のため、というよりかは拡張しやすくする)
- bem知らなくても実装できるよう簡略化(idのみ利用)

という前提で考えてましたが、余計複雑になったり、少し考慮が足りなかったですね。

@tomothumb のご提案のほうが適切だと感じました。

ご提案いただいた内容にそってサンプル実装を再作成してみます。

よろしくお願いいたします。

**Comment by chihiro-adachi** [comment]
@ttsuru
ありがとうございます。基本的には@tomothumb のご提案通りclassも利用する方向で考えてます。

**Comment by chihiro-adachi** [comment]
@tomothumb
商品一覧、再実装してみました。
https://github.com/EC-CUBE/ec-cube/compare/master...geany-y:gean-y/draft/product_list

prefixは削除し、idの付与はあまり細かい単位ではなく、粒度を大きめにとっています。
一部classを併用する案については一覧では出てこなさそう(認識ちがったらおっしゃって下さい)かなという印象です。

引き続き詳細画面も見てみます。

**Comment by ttsuru** [comment]
@chihiro-adachi 
Typoが多いような気がします。
Formのレンダリング変えたほうがいいんじゃないでしょうか。

**Comment by chihiro-adachi** [comment]
@ttsuru 
ありがとうございます。

>Formのレンダリング変えたほうがいいんじゃないでしょうか。

うーん、Formのレンダリングについては確かにおっしゃるとおりなのですが、デザインをカスタマイズする際に、プログラマしか触れなくなるのが懸念です。
デザイン寄りの方に、Twigだけでなく、FormTypeやFormThemeまで把握してもらうのは中々むずかしいな、と感じてます。

**Comment by ttsuru** [comment]
@chihiro-adachi 
特に管理画面に関してはデザイナーの方は触らないのではないでしょうか。
また、Symfonyのドキュメントのように、デザイナーがカスタマイズしたいのであれば今のように書けばよいと思います。

プラグインでの拡張を重視するという方針をロックオンさんで言われているのに、Formのレンダリングを半端な状態にしているメリットがわかりません。
Formのレンダリングがテーマでできれば、テーマのみを変更するだけでデザインの変更も可能になり、プラグインから簡単にフォームの項目が追加できます。
現状のFormだとほとんどSymfony Formの利点をいかせていません。

現状のDOMを解析して項目を追加するという行為が非常に無駄で、かつデザインの変更を行ってしまうとプラグインでの対応が難しくなってしまうと思います。

「BEMの命名規則にしたがってフロントコーディングをしてくれ」
「Form Themeに則ってFormをdivからtableに変更してほしい」
の2点であれば、僕は下のほうがリテラシーの低い方でも対応ができると思います。

そもそもプラグインでフロントを変更を柔軟にするのであれば、Form Themeはdivとtableの2種類だけあれば良いと思います。
逆にそれ以上のデザインカスタマイズするような案件があるのであれば、それはそれでForn Themeを学べばいいと思います。

**Comment by ttsuru** [comment]
EC-CUBEの公開されている実績でも2系のサイトでも殆どのサイトがデフォルトのフォームをそのまま利用してサイトを構築しています。
とくにentryやcontactなどはデフォルトのテーブルのままのサイトがほとんどです。

リテラシーは低いけれどHTMLコーディングでどうにかしたいという層をそこまで大事にして、プラグインでの拡張で簡単にフォームを追加できるメリットを潰すまでの考慮は必要なのでしょうか。

数少ない例外のために、プラグインでの拡張性が低くなるのは順番が逆だと思います。

**Comment by tomothumb** [comment]
@chihiro-adachi 
すっきりしましたね！
私からは、命名についてのみコメントさせていただきます。

Typoがあるのはおいておいて、
非常に細かいことですが、個人的に、まれに、IDとclassをわざわざ別の単語を使ったんだろう？と、気になる箇所がありました。
（すでにclassが割り振られている場合は仕方ないと思いますし、理由があればいいんですけど）

```
 // IDはimageで、classはphoto？？
<div id="result_list_main__image--{{ Product.id }}" class="item_photo td">

 // 用途的に、IDをnameではなく、detailに統一すべきでは？？
<div id="result_list_main__name--{{ Product.id }}" class="item_detail td">
```

全て一致させるべきとは思っていませんが、わざわざ複雑にさせる理由もないかなと。

**Comment by chihiro-adachi** [comment]
@ttsuru
formの拡張について、DOM解析で行っているのは確かに問題ですね。

それについては、

- {{ form_rest(form) }} をテンプレートに追加する
- formへの拡張ポイントを設ける

で解消できると考えています。

このissueで解消したいのは、formの項目追加のためにdom解析をしやすくしたい、ではなく、
jQueryなりCrawlerなりで、もう少し要素を差し込みやすくしたい、です。

で、id割り当てるのにある程度命名規約は必要だろう、というところで本issueを立てています。

form_themeのメリットは重々承知ですが、正直そのへんまで学べ、は現時点では無理があるかなあ、と感じてます。
※関西では勉強会をかなり開催しているのですが、そこまで到達にするにはやはり相当な時間がかかります、、、将来てきには変わるかもと思ってはいますが。

**Comment by chihiro-adachi** [comment]
@tomothumb
ご確認ありがとうございます。

> IDとclassをわざわざ別の単語を使ったんだろう？
他のページ見てみると、classの方が一貫していない箇所もあり(それはそれで問題ですが、、、)、参照している変数名に合わせた、というところです。

**Comment by ttsuru** [comment]
@chihiro-adachi 
すべてを学ぶ必要はなく、必要な方が form theme を書き換えられれば良いのではないでしょうか。
すべての内容をすべての方が理解できなければいけないでは、メリットを享受できる内容がすくなくなり、保守が行いにくくなると思います。
IDの追加などをすべて手動で行っていくと、プラグインで追加される要素との統一感もなくなってしまうと思います。
Formに関してはTheme側と連動して自動で追加できるなどがあったほうが良いと思います。

**Comment by ttsuru** [comment]
私からのIssueへの提案内容はすべてのForm項目にIDを手動でふることは現実的ではないので、このタイミングで、 ``{{ form_widget(form) }}`` だけで自動でIDを振れるようにしたほうが良いのではという点です。

**Comment by ttsuru** [comment]
Formに関しては以下のURLにある内容だけで理解が済むと思います。
デザインカスタマイズなどの話を出されていますが、実際にデザインをカスタマイズする際にはCSSでの装飾の変更がほとんどではないでしょうか。
http://symfony.com/doc/current/book/forms.html

**Comment by ttsuru** [comment]
それに、Formを変えたいのであれば、それこそ、そういったプラグインをどなたかが開発すればよい問題ではないでしょうか。

**Comment by tomothumb** [comment]
@chihiro-adachi
そのような理由だったんですね。
どなたがコントリビュートされるかはわからないので、見本がバラけてますと、作業者の判断がぶれてしまわないかと、気になったした次第です。

全体を見渡してコードレビューを意識されていらっしゃるとのことですので、いらぬ心配でしたね。失礼いたしました。私からの提案は以上です。

**Comment by chihiro-adachi** [comment]
#1492
