### ISSUE TITLE
Eccube3 ログイン画面から進みません Vagrant PHPver5.4上

### ISSUE THREAD

**Issue by oneunited** [EC-CUBE/ec-cube#1449]
PHPver5.4上で
vagrant上にECCUBE　Version3.08をインストールしましたが

ログイン画面より進みません。

ログインID、パスワードは、きちんと入力後ログインボタンを押しているのですが
エラーメッセージも出ないでログイン画面に戻ってきます。

ログインボタン押した後1-2分読込されています。

ログインボタン押した後/app/logに下記logが出ています。

何卒ご教授お願い致します。

下記試しましたがダメでした。
https://github.com/EC-CUBE/ec-cube/issues/536

eccube.INFO: Matched route "管理画面ディレクトリ名_login_check". {"route_parameters":{"_controller":null,"_route":"管理画面ディレクトリ名_login_check"},"request_uri":"IPアドレス/eccube/html/管理画面ディレクトリ名/login_check"}
eccube.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\InvalidCsrfTokenException(code: 0): Invalid CSRF token. at eccube/vendor/symfony/security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:82)"} []
eccube.INFO: < 302 IPアドレス/eccube/html/管理画面ディレクトリ名/login [] []
eccube.INFO: Matched route "admin_login". {"route_parameters":{"_controller":"\\Eccube\\Controller\\Admin\\AdminController::login","_route":"admin_login"},"request_uri":"IPアドレス/eccube/html/管理画面ディレクトリ名/login"} []
eccube.INFO: Populated the TokenStorage with an anonymous Token. [] []
eccube.INFO: > GET /eccube/html/管理画面ディレクトリ名/login [] []

https://github.com/EC-CUBE/ec-cube/issues/536

**Comment by nanasess** [comment]
`Authentication request failed` と出ていますので、データベースに接続できていない等、何らかの原因で認証に失敗しているものと思われます。
(EC-CUBEの直接の不具合ではない可能性)

**Comment by Yangsin** [comment]
ご利用にあたっての質問などは
開発コミュニティをご利用いただくほうがスムーズかと存じます。

http://xoops.ec-cube.net/

**Comment by nanasess** [comment]
何回か書いていただいてるみたいですね...
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16982&forum=11&post_id=74584#forumpost74584

**Comment by Yangsin** [comment]
ほぼ同時に・・・(^_^;)
わかりづらくてすみませんが、やりとりも分散してしまいますので、あとは、開発コミュニティで継続いただいて、こちらはクローズさせていただきますね。
