### ISSUE TITLE
【提案】ページ管理から作成するページのテンプレートの初期表示

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1456]
ページ管理から新しくページを作成する際に、毎回`{% extends 'default_frame.twig' %}`などを記載しなければならず手間がかかるため、新規登録時のみデフォルト値を入れておいてはどうでしょうか。

以下のような値を`textarea`に初期表示することを想定しています。

```
{% extends 'default_frame.twig' %}

{% block javascript %}
{# ここに <script> タグを記載 #}
{% endblock %}

{% block stylesheet %}
{# ここに <style> タグ、<link rel="stylesheet"> タグを記載 #}
{% endblock %}

{% block main %}
{# ここにメインコンテンツを記載 #}
{% endblock %}
```

**Comment by ttsuru** [comment]
:+1:

**Comment by tomothumb** [comment]
同じことを感じていました。

理想を付け加えさせていただくと、
基本ページについてもそうなのですが、ページ管理の入力欄が、以下入力項目が４つにわかれてて、保存したらtwigが書き換えられるというようなことができれば便利だなと。

* text: テンプレtwig（extendsの引数に動的な値をいれれたかわかりません。）
* textarea: javascript
* textarea: stylesheet
* textarea: main

追加される固定ページって、静的要素のコンテンツになることが多いと思いますので、mainのところだけ、CMSらしくWYSIWYG導入できて、コーダー以外でも簡単に更新できるようになりますし。

**Comment by shhirose** [comment]
> 基本ページについてもそうなのですが、ページ管理の入力欄が、以下入力項目が４つにわかれてて、保存したらtwigが書き換えられるというようなことができれば便利だなと。

便利そうですけど、後方互換を考えるとロジックが面倒かもしれないですね。
新規登録時は楽ですけど、編集する際に twig ファイルの解析しないといけませんし。
（逆に言えば解析ができるツールがあれば良いと思います。あとは DB に保存するかですかね。）


> 追加される固定ページって、静的要素のコンテンツになることが多いと思いますので、mainのところだけ、CMSらしくWYSIWYG導入できて、コーダー以外でも簡単に更新できるようになりますし。

分割できるなら WYSIWYG 入れたいですね！

**Comment by okazy** [comment]
4.0で対応しました。
