### ISSUE TITLE
商品種別を設定できない

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1458]
管理画面から商品種別を設定したり変更したりする事はできますでしょうか？

**Comment by nanasess** [comment]
規格の無い商品は、商品管理画面から、
規格のある商品は、規格管理画面から設定できると思いますが、いかがでしょうか。

![default](https://cloud.githubusercontent.com/assets/815715/12876706/e3d6e674-ce48-11e5-8bff-ea0213456685.PNG)

![default](https://cloud.githubusercontent.com/assets/815715/12876715/2a1dc490-ce49-11e5-99ea-379ee59e330a.PNG)

もしくは、商品種別の名称を変更したい場合は、設定→システム情報設定→マスタデータ管理の **mtb_product_type** を変更することで可能です

**Comment by imgnation** [comment]
ありがとうございます。
質問が言葉足らずでした。
ご回答の下部に書いてある、
「商品種別の名称の変更」
の意味で質問させていただいておりました。
ありがとうございます。
