### ISSUE TITLE
管理ページをデバッグモードで開くことは出来るのか？

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1462]
お世話になっております。

管理ページでページの調整などを行っているとエラー画面となり、デバッグモードで開きたいと考えました。

管理ページは
http://ooo.xxx.com/sssssss/
といったURLですが
http://ooo.xxx.com/sssssss/index_dev.php
ですと、ページが見つかりませんになります。

管理ページをデバッグモードで開くことは可能なのでしょうか？

**Comment by Yangsin** [comment]
http://ooo.xxx.com/index_dev.php/sssssss/
でお試しいただければと存じます。

大変申し訳ございませんが、こちらは本体開発に関係した不具合情報の共有、新機能への意見交換などを目的としております。
通常の利用における疑問などのご質問は開発コミュニティをご利用いただけますようお願いいたします。

http://xoops.ec-cube.net
