### ISSUE TITLE
管理画面の各種一覧ページの表示内容

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1471]
管理画面にて、
- 商品一覧
- 受注一覧
- 会員一覧

これら、それぞれ詳細を確認する際に、検索ボタンをわざわざクリックさせるアクションが無駄に思います。それぞれの一覧トップページで、10件とかがデフォルトで表示されるようになっている方がよいのではと感じました。

特に受注一覧については、毎日の業務で、最新の受注状況を確認できればよいというケースが主だと思いますし。

**Comment by xuelian311** [comment]
4.0から検索ボタンを押さなくても表示されるようになりましたので、解決済みとしてクローズします。
