### ISSUE TITLE
受注管理などのフィルタリング。UI改善。

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1472]
商品管理の一覧では、「すべて  公開  非公開  在庫なし 」とフィルタリングできますが、
- 会員管理では、「すべて｜本会員｜仮会員」
- プラグイン管理では、「すべて｜有効のプラグイン｜無効のプラグイン」
- 受注管理では、「すべて｜新規受付｜入金待ち｜入金済み｜.......」。

といったようなフィルタができていると便利だなと感じます。

**Comment by xuelian311** [comment]
現状4系では受注管理と会員管理はフィルタリング機能が実装されています。
対応できてないプラグイン管理のフィルタリングについては、頻繁に利用されない想定であるため、本issueはクローズいたします。
引き続きプラグイン管理のフィルタリング機能の検討を希望される場合は、新しいIssueを立てていただけますと幸いです。
