### ISSUE TITLE
【提案】ページ管理の重複ページを編集不可（もしくは非表示）にしたい

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1495]
現在ページ管理に同一ページだが、レイアウトのためだけに存在するページがあります。
例）商品購入/配送方法選択 、商品購入/支払方法選択、・・・・

ページタイトルと実際に適応される画面が異なり、間違いの元になるので同一ページの場合はマスターとなるページ以外は修正不可にしたく思います。

例えば url が`shopping_shipping_change`のページはページタイトルが「商品購入/お届け先変更」となっていますが、実際には購入確認画面でお届け先変更ボタンがクリックされ、エラーが発生した場合にのみ表示され、表示されるページは購入確認画面（`shopping`）となっています。（ページ編集で編集できる twig も`Shopping/index.twig`です。）

以下実装した場合の案です。
- PageLayout にマスターとなるページの`page_id`を保存するカラムを追加（自身のFKをはる）

dtb_page_layout

| Column | Type | Modifiers |
| --- | --- | --- |
| page_id | integer | not null |
| device_type_id | integer |  |
| page_name | text |  |
| url | text | not null |
| file_name | text |  |
| edit_flg | smallint | default 1 |
| author | text |  |
| description | text |  |
| keyword | text |  |
| update_url | text |  |
| create_date | timestamp | not null |
| update_date | timestamp | not null |
| meta_robots | text |  |
| master_page_id | integer | <- 追加 FK to dtb_page_layout.page_id |
- ページ管理の一覧で非表示にするために`PageLayoutRepository::getPageList`に `master_page_id is not null`というwhere句を追加

``` PHP
$qb = $this->createQueryBuilder('l')
    ->orderBy('l.id', 'DESC')
    ->where('l.DeviceType = :DeviceType')
    ->setParameter('DeviceType', $DeviceType)
    ->andWhere('l.id <> 0')
    ->andWhere('l.Master is not null')
    ->orderBy('l.id', 'ASC');
```
- フロント表示時にマスターページのブロック配置を使用するために`PageLayoutRepository::getByUrl`の対象ページを取得後、マスターページが存在すればそれを使用する

``` PHP
$ownResult = $qb
    ->getQuery()
    ->setParameters(array(
        'DeviceType' => $DeviceType,
        'url'  => $url,
    ))
    ->getSingleResult();

if ($ownResult->getMaster()) {
    $ownResult = $ownResult->getMaster();
}
```

こんな形で実装はできると思いますが、対応可否、実装方法含めいかがでしょうか。

**Comment by okazy** [comment]
https://github.com/EC-CUBE/ec-cube/pull/2674
で対応済みのためクローズします。
