### ISSUE TITLE
商品レビュー管理プラグインをインストールしたら商品詳細ページでエラー

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1506]
3.0.8系を使用しています。
商品レビュー管理プラグインをインストールしたら商品詳細ページでエラーが表示されてしまいました。
メッセージは
Twig_Error_Runtime in Template.php line 436:
Variable "Category" does not exist in "Product/detail.twig" at line 56
です

**Comment by ryo-endo** [comment]
ご報告ありがとうございます。
私の環境でエラーが確認できなかったのですが、プラグインのバージョンはいつくでしょうか？

**Comment by imgnation** [comment]
ProductReview
の
0.0.2
です

**Comment by imgnation** [comment]
EC-CUBEを3.0.9にバージョンアップしても発生しました

**Comment by ttsuru** [comment]
> Twig_Error_Runtime in Template.php line 436:
> Variable "Category" does not exist in "Product/detail.twig" at line 56

このエラーだと、プラグインは関係ないんじゃないでしょうか・・・
デザインテンプレートはデフォルトのものですか？

**Comment by imgnation** [comment]
デフォルトではないですね

プラグインを無効
==> 正常表示

プラグインを有効
==> 上記のエラーメッセージ

となります

**Comment by imgnation** [comment]
バージョンを3.0.9に上げ、detail.twigをデフォルトにしたら正常表示できました。
また、詳細気づきましたら投稿いたします。
