### ISSUE TITLE
ブロック更新で空要素だとエラー

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1507]
管理画面
↓
コンテンツ管理
↓
ブロック管理
↓
ブロック選択＆編集
↓
データを空にして更新

エラー画面となります

**Comment by Yangsin** [comment]
エラーの詳細などを連携していただけますでしょうか。
ご自身で判断がつかなければ、ログやキャプチャなどを提示いただけますと幸いです。

また以下もご一読いただきますようお願いいたします。
https://github.com/EC-CUBE/ec-cube/wiki/Issues%E3%81%AE%E5%88%A9%E7%94%A8%E6%96%B9%E6%B3%95

こちらも一度クローズとさせていただきますことご了承くださいませ。
