### ISSUE TITLE
xampp上で3.0.9をインストールするとエラーになる

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1508]
windows7+xampp環境下で
3.0.9をインストールしようとするとエラーになりました

データベースを初期化しないでのインストールは出来ましたが一からインストールしようとするとエラーになります

---------- 以下エラーメッセージ ----------
Whoops, looks like something went wrong.

3/3
NotNullConstraintViolationException in AbstractMySQLDriver.php line 112:
An exception occurred while executing 'INSERT INTO dtb_member (member_id, login_id, password, salt, work, del_flg, authority, creator_id, rank, update_date, create_date,name,department) VALUES (2, :login_id, :admin_pass , :salt , '1', '0', '0', '1', '1', current_timestamp, current_timestamp,'ç®¡ç†è€…','EC-CUBE SHOP');' with params [null, "cd30de11e5435d0f76508d5e0448184df72ef189e14c5df73cf419ebe6a5b95e", "6fEHKNP6hoEWRc0Hk5UmvWXTm9qcGgJ0"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'login_id' cannot be null

**Comment by nanasess** [comment]
login_id が null になっているようですが、何らかの原因で、管理画面のログインIDが正常に渡ってきてないのではないでしょうか。

**Comment by imgnation** [comment]
ありがとうございます。
現在、再度インストールしてみたら無事に出来ました。
環境も前回と差はなかったように思いますが、詳細はもう少し調べてみます。
この度はありがとうございました
