### ISSUE TITLE
3.0.9で「おすすめ商品管理プラグイン」をインストールして有効にしたらエラー

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1509]
3.0.9の環境で
「おすすめ商品管理プラグイン」をインストールしました。

管理ページから「有効にする」をクリックしたら

システムエラーが発生しました

となりました。

**Comment by Yangsin** [comment]
原因が特定でき、本体側であることが明確であれば改めてご報告いただけますようお願いします。
単純な事象の相談などであれば、開発コミュニティをご利用いただけますようお願いいたします。
お手数おかけしますが、開発コミュニティとこちらの使い分けを再度お願いいたします。
