### ISSUE TITLE
DBのバックアップをとっておき復旧作業をしたが管理ページに入れなくなった

### ISSUE THREAD

**Issue by imgnation** [EC-CUBE/ec-cube#1511]
3.0.9を使用しております。

DBをまるごとバックアップしておき
一度DBを白紙に戻し
再度ファイルからインポートしたところ、
以前と同じIDとPWで管理ページに入れなくなりました。

特にdtb_memberのテーブルを注目し、以前と同じ状態にしたのですが、ログインできませんでした。
DBを直に操作することは出来ますので、管理ページにログインする方法は実装されていますでしょうか？

**Comment by Yangsin** [comment]
原因が特定でき、本体側であることが明確であれば改めてご報告いただけますようお願いします。
単純な事象の相談や仕様の質問などは、開発コミュニティをご利用いただけますようお願いいたします。
お手数おかけしますが、開発コミュニティとこちらの使い分けを再度お願いいたします。
