### ISSUE TITLE
カテゴリCSVダウンロードで子を持つ親が表示されない

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1515]
カテゴリのCSVダウンロードを行うと、以下の条件で表示されないカテゴリが存在する。

1.カテゴリを作成
2.そのカテゴリに子のカテゴリを作成
3.並び順を一番下に変更
4.CSVダウンロード

例）
親カテゴリおよび子カテゴリを作成し、並び順を一番下に移動
![image1](https://cloud.githubusercontent.com/assets/12494780/13492419/37e0fad0-e17b-11e5-87de-72f1f3b509c4.png)

CSV ダウンロードした結果は以下のとおりとなり、1で作成した親カテゴリが出力されません。

``` CSV
カテゴリID,"表示ランク",カテゴリ名,親カテゴリID,階層
2,8,インテリア,,1
8,7,子カテゴリ,7,2
1,6,キッチンツール,,1
6,5,新入荷,,1
4,4,調理器具,1,2
3,3,食器,1,2
5,2,フォーク,3,3
,,,,
```

**Comment by shhirose** [comment]
どうやらデータベースから取得した際のエンティティのクラス名が異なるため、値が空で出力されているようです。

通常の行のクラスは`Eccube\Entity\Category`ですが、
表示されない項目のクラスは`DoctrineProxy\__CG__\Eccube\Entity\Category`になっていました。
そのため、`CsvExportService::getData`の最初の条件文で`false`となり、`null`が返っていました。

どうしてこのような状況になるのか不勉強な私にはわからないため、対応できる方がいらっしゃいましたら対応をお願いします。

**Comment by nanasess** [comment]
Doctrine でキャッシュされたオブジェクトが返ってきているのですね

**Comment by shhirose** [comment]
キャッシュなんですね。
ざっと調べた感じだとキャッシュから元のクラス名が取れないような気がしますが、元のクラス名を取得する方法はあるんでしょうか。

**Comment by shhirose** [comment]
文字列として`DoctrineProxy\__CG__\`を除く方法で実装してみました。
もし他に良い方法があればご連絡いただければと思います。

**Comment by nanasess** [comment]
リフレクション使うとかですかね。文字列の操作で問題なければ、それでも大丈夫だと思います。

**Comment by shhirose** [comment]
マージされているのでクローズします。
