### ISSUE TITLE
商品にタグをつける機能

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1516]
2系の「商品ステータス」と同じように、商品に「タグ」をつける機能を追加する。

### フロント
* 商品詳細
 - タグの表示を追加する。
 - タグをクリックすると、タグ検索を行う。
	
* 商品リスト
 - タグ検索を行った場合は、  
検索結果のヘッダー部分にタグ名を表示する。

	
### 管理画面
* 商品登録/編集
 - タグを選択するUIを追加する。  
(チェックボックスで複数選択可能)

* 商品マスター 
 - Want：検索条件にタグを追加する。  
(コンボボックスで単一選択に限定する)

### その他
* タグは、管理画面のマスターデータ管理から手動で登録してもらう。(これは2系相当)
* Want：商品登録時にタグを新規追加できるようにする。

**Comment by chihiro-adachi** [comment]
#1524 #1534 で対応
