### ISSUE TITLE
beginTransaction() ではなく setAutoCommit(false) を使用する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1518]
現在、 `Connection::beginTransaction()` が使用されています。
この関数は、ネストしたトランザクションブロックを作ることができます。
この実装は、 savepoint を発行するのみなので、以下のようなケースで EXECUTE SQL 2 が ROLLBACK すると、 1 と 3 はコミットされてしまいます。

```sql
BEGIN 1
    EXECUTE SQL 1
    BEGIN 2
        EXECUTE SQL 2
    COMMIT 2
    EXECUTE SQL 3
COMMIT
```

`Connection::setAutoCommit(false)` を使用すれば、 `commit()` をコールした時点で新たなトランザクションが開始されますので、 `commit()` 時点までのロールバックが可能です。
プラグインの使用を考えると、  **setAutoCommit(false) を使用し、更新を反映させたい時点で commit()** という実装の方が直感的かつ安全かと思いますが、いかがでしょうか。

**Comment by seasoftjapan** [comment]
> 以下のようなケースで EXECUTE SQL 2 が ROLLBACK すると、 1 と 3 はコミットされてしまいます。

それは、最終行で `COMMIT` しているからですよね?

ならば、その動作の方が自然な気がしました。

現況の例外処理がどうなっているのか把握していませんが、例外処理に回った場合に、全体がコミットされなければ、それで十分なように思います。

**Comment by ttsuru** [comment]
refs http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/transactions.html

**Comment by nanasess** [comment]
@seasoftjapan 2 の BEGIN/COMMIT が、実は savepoint だというのを、実装者が意識できていれば問題ないと思いますが、そうでなければ **commit() の時点まで** の方が、安全で、わかりやすいかなと思いました。
特に、プラグインの中で commit() とか rollback() とかやられると、よくわからなくなるので...

**Comment by ttsuru** [comment]
@nanasess 
入れ子になった際に不思議な感じになりませんかね・・・

**Comment by ttsuru** [comment]
プラグインを考えると、commit以前にフックポイントがある事のほうが大事な気がしますがどうでしょうか。

**Comment by nanasess** [comment]
@ttsuru ちゃんと入れ子は savepoint だと意識して、 入れ子の中で `beginTransaction() / commit()` していれば、入れ子のみロールバックするので問題ないと思いますよ。
プラグインの中で beginTransaction() のみコールされると困ったことになりますが...

**Comment by ttsuru** [comment]
@nanasess 
それであれば、 ``Connection::beginTransaction()`` でいいのではないでしょうか。
refs のように ``setAutoCommit(false)`` は挙動が異なります。

savepoint という概念もここで登場することはわかりづらいと思います。

**Comment by shhirose** [comment]
Transaction を入れ子にしなければならないケースは稀ではないでしょうか？（何かしらの処理を行った記録を残す場合など？）
入力の項目追加などはプラグインで失敗した場合は、本体側もロールバックしてもらいたいと思います。

であれば、フックポイントの名称に Transaction が開始しているかどうかを判断できるような形にして、その後は開発者に委ねてしまって良い気がします。ただし、プラグインの開発手順にネストする場合は`try-cache`入れるとか、`commit`、`rollback`を確実に行うなどの記述は必要だとは思いますが。

**Comment by nanasess** [comment]
> 入力の項目追加などはプラグインで失敗した場合は、本体側もロールバックしてもらいたいと思います。

これを確実に実現するためには、 Controller 全体をトランザクションブロックで囲まねばならず、そうした時に setAutoCommit(false) の方が挙動が把握しやすく、安全ではないかと思ったのでした。

現在は問題が具現化しておらず、 setAutoCommit(false) にするメリットもわかりづらいと思いますので、一度再現ケースを作ってみようと思います。

**Comment by ttsuru** [comment]
``setAutoCommit(false)`` をしてしまうと、作法の悪いプラグインに勝手にcommitされてしまう気がします。

僕も @shhirose さんと以下の内容に同意見です。
> 入力の項目追加などはプラグインで失敗した場合は、本体側もロールバックしてもらいたいと思います。

また、本件が最も重要になるのは注文だと思いますが、現状改善すべきユースケースがプラグインの記載含め見当たりません。
逆にtry catch のcatchにhookpointが欲しいぐらいでしょうか。

**Comment by chihiro-adachi** [comment]
いくつかユースケースも合わせて検証してみました。

https://github.com/EC-CUBE/ec-cube/compare/master...chihiro-adachi:dev-autocommit

アプリケーションの開始/終了でコントロールするようにしています。
プラグイン側でシステムエラー等が発生した場合は、本体側も含めロールバックを行います。

- Requestイベントでbegin
- Terminateイベントでcommit
- 例外発生時やcommitできない場合はrollback

のような実装です。

```
BEGIN 1
    EXECUTE SQL 1
    BEGIN 2
        EXECUTE SQL 2
    COMMIT 2
    EXECUTE SQL 3
COMMIT
```
のユースケース例だと、

- EXECUTE SQL 2 で 例外が発生した場合：EXECUTE SQL 1/2はROLLBACKされる
- COMMIT2が正常に終了し、EXECUTE SQL 3の前に例外が発生した場合：ECUTE SQL 1/ 2 はROLLBACKされる
- COMMIT2が正常に終了し、EXECUTE SQL 3の後に例外が発生した場合：ECUTE SQL 1/ 2 /3 はROLLBACKされる

となります。

トランザクションは本体側の制御にまかせ、プラグイン側では扱わないようにしてもらえれば、本体側で一貫した制御が出来るかと思います。

**Comment by ryo-endo** [comment]
https://github.com/EC-CUBE/ec-cube/issues/1632
こちらの内容、PR取り込みましたのでIssueを閉じます。
