### ISSUE TITLE
default_frame.twigと各ページのtwigでIDの重複

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1519]
フロント側のtwigファイルに、default_frame.twigで使用しているIDと重複している箇所がある（contents, main)

```
Contact/index.twig

<div id="contents" class="main_only">
    <div class="container-fluid inner no-padding">
        <div id="main">
            <h1 class="page-heading">お問い合わせ</h1>
```

対象ファイルは以下のとおり
- Contact/confirm.twig
- Contact/index.twig
- Forgot/complete.twig
- Forgot/index.twig
- Forgot/reset.twig
- Help/about.twig
- Help/about.twig
- Help/agreement.twig
- Help/guide.twig
- Help/privacy.twig
- Help/tradelaw.twig
#1631 も合わせて修正必要。

**Comment by izayoi256** [comment]
重複ではありませんが、idの階層が誤っているであろう箇所
https://github.com/EC-CUBE/ec-cube/blob/3.0.12-p1/src/Eccube/Resource/template/default/Entry/index.twig#L121

参考) https://github.com/EC-CUBE/ec-cube/blob/3.0.12-p1/src/Eccube/Resource/template/default/Entry/confirm.twig#L102

**Comment by Yangsin** [comment]
EC-CUBEスタイルガイドラインの作成 #2075 で本件も解決しますのでクローズします。
