### ISSUE TITLE
メールアドレス入力チェックを行うときにegulias/email-validatorが利用されていない箇所がある。

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1520]
FormTypeにemailを利用してValidationを行う場合、
```php
new Assert\Email()
```
ではなく
```php
new Assert\Email(array('strict' => true)),
```
とstrictをtrueにして`egulias/email-validator`を使うようにする。

http://symfony.com/doc/2.7/reference/constraints/Email.html#strict

**Comment by chihiro-adachi** [comment]
#1636 で対応
