### ISSUE TITLE
Windows環境でオーナーズストア通信時にエラーが発生

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1521]
対応するにはWindows環境だとcacart.pemが取得できないため、
Guzzleに倣ってcacart.pemを同梱し、通信時は同梱したcacart.pemを参照させる。
- 同梱させるcacart.pem  
  https://curl.haxx.se/ca/cacert.pem

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17053&forum=13&post_id=75215#forumpost75215

**Comment by ttsuru** [comment]
Composer の実装を見ていると、同梱してしまったほうが良さそうです。
