### ISSUE TITLE
商品CSV登録機能の拡張性について

### ISSUE THREAD

**Issue by nkenji09** [EC-CUBE/ec-cube#1522]
CSVエクスポートの方は $app['eccube.service.csv.export'] に
実行クラスが格納されているので、プラグインからオーバーライドできるのですが
CSV登録の方は CsvImportControllerクラスに実行処理が直に書いてあるため
オーバーライドできずに困っています。

きっとCSV取込部分は、拡張したい人は多いと思っています。

**Comment by Yangsin** [comment]
拡張を高める一方でパフォーマンスの低下につながると、実用性が下がるのでどのような実装ができるか悩ましい。
もうすこし拡張に関するユースケースもほしいですね。

**Comment by okazy** [comment]
https://github.com/EC-CUBE/ec-cube/issues/3575

**Comment by chihiro-adachi** [comment]
#3575 に集約のため、こちらはクローズします
