### ISSUE TITLE
symfony 2.7.11

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1529]
2.7.9 -> 2.7.11への追随と、影響範囲の確認を行う.
リリースノートは以下の通り.

http://symfony.com/blog/symfony-2-7-10-released
http://symfony.com/blog/symfony-2-7-11-released

**Comment by nanasess** [comment]
2.7.15 がリリースされています。
http://symfony.com/blog/symfony-2-7-15-released

**Comment by ryo-endo** [comment]
2.7.16 がリリースされています。
http://symfony.com/blog/symfony-2-7-16-released

**Comment by ryo-endo** [comment]
https://github.com/EC-CUBE/ec-cube/pull/1660
symfony 2.7.16 にアップデートしたのでIssue閉じます。
