### ISSUE TITLE
Web APIの開発

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1530]
EC-CUBE Web APIのレポジトリを作成しました。

https://github.com/EC-CUBE/eccube-api

現時点で上がっている実装は以下のとおりです。
- 認証
  - OAuth2.0
  - OpenID Connect
- 商品操作API
  - 商品一覧取得
  - 商品詳細取得
  - 商品詳細取得(認証あり)

インストールや動作確認の手順は、READMEに記載していますので、実際の動作をご確認いただくことができます。

また、WebAPIの仕様や開発指針について、以下にドラフトを作成しています。

https://ec-cube.github.io/api.html

こちらについても、ご意見等いただけますと幸いです。
よろしくおねがいいたします。

**Comment by ttsuru** [comment]
> 分かりやすくするため/products/:id/xxxxx以上に深くなるURLは利用しない。

の表記は以下を参照したものかと思いますが、``xxxxx`` だとresouceを表すのか、identifierを表すのかわかりにくいかと思います。
 `/resource/identifier/resource` という意味でよろしかったでしょうか。

http://d.hatena.ne.jp/cou929_la/20130121/1358776754

> URL の階層を浅く保つ
> リソースの関係を表したい場合. 例えばオーナー 5678 が飼っている犬をあらわす URL は `/owners/5678/dogs`
> 目安として `/resource/identifier/resource` 以上に URL を深くすべきでない
> URL は浅く保ち, 複雑さはクエリパラメーターに押しこむ

**Comment by chihiro-adachi** [comment]
@ttsuru ありがとうございます。
> /resource/identifier/resource という意味でよろしかったでしょうか。

はい、そうです、おっしゃるとおりresourceの意味です。確かに少しわかりにくいですね。

**Comment by okazy** [comment]
このIssueは3系の内容なのでクローズします。
4系は以下のIssueで検討していきます。
https://github.com/EC-CUBE/ec-cube/issues/4447
