### ISSUE TITLE
オーナーズストアプラグインのインストール要件の緩和

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1531]
プラグインがサポートしていないバージョンのEC-CUBE本体からも、
オーナーズストア経由でプラグインをインストール/更新できるようにします。

ただし、この場合、プラグインが正常に動作しない可能性があるので、
`購入済みプラグイン一覧`の以下の箇所に警告を表示します。
![image](https://cloud.githubusercontent.com/assets/16891862/14338255/73cb0504-fcb0-11e5-970c-5164a90c3b1c.png)
  
  
また`インストール済みプラグイン一覧`から更新をするときに、
サポートしている本体バージョンがわからないため、以下の箇所に表示するようにします。
![image](https://cloud.githubusercontent.com/assets/16891862/14338286/bbd524c4-fcb0-11e5-8789-0bde845f72e7.png)

**Comment by chihiro-adachi** [comment]
#1531 で対応.
