### ISSUE TITLE
プラグイン利用時の注文フローの配送業者と配送時間帯

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1544]
注文フローの配送情報入力画面で、下記の手順を行なうと異なる組み合わせの配送業者と配送時間帯が選択可能になります。
1. プラグインで配送情報入力画面に任意の入力チェック付きのフィールドを追加する。
2. 追加したフィールドの入力エラーが発生する状態で、配送業者を変更する。
3. 画面遷移すると配送時間帯は変更前の配送業者に紐づくリストが表示されているが、配送業者は変更後のものが選択されている。

選択可能な配送時間帯のリストはDB上の受注の配送業者に紐づく時間帯のリストを利用しています。画面遷移によって画面上の配送業者は変わりますが、バリデーションエラーが発生するとDB上の受注は更新されないため上記の現象が発生するものと考えます。

プラグイン利用時に限った問題ですが、配送情報入力画面にフィールドを追加するケースにおいては高確率で発生するためご報告します。

**Comment by okazy** [comment]
以下のPRで修正されているか確認
https://github.com/EC-CUBE/ec-cube/pull/3650

**Comment by chihiro-adachi** [comment]
#3650 で対応
