### ISSUE TITLE
商品規格登録画面のフックポイント

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1546]
商品規格登録画面のフックポイントの実行順が「フックポイント→登録」となっているのは、何か意図があるのでしょうか？

「登録→フックポイント」に変更するPR(#1545)を投げましたが、登録の前にもフックポイントが必要でしょうか？

**Comment by ryo-endo** [comment]
3.0.11で対応完了していたので、CLOSEします。
