### ISSUE TITLE
インストール時、 セッションハンドラの Warning が発生する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1549]
インストール時、以下のような Warning が発生している

`Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in D:\home\site\wwwroot\vendor\symfony\http-foundation\Session\Storage\Handler\NativeFileSessionHandler.php on line 56`

**Comment by ttsuru** [comment]
refs #582

**Comment by ttsuru** [comment]
やっぱり出ますよね。

**Comment by nanasess** [comment]
たぶん、 出力バッファリングに隠れちゃってるんではないかなと

**Comment by ttsuru** [comment]
原因はSessionのトリッキーな扱いだと思います。

**Comment by ryo-endo** [comment]
#1621 で対応。
