### ISSUE TITLE
インストール時、 エラーが発生しました。

### ISSUE THREAD

**Issue by cnbillow** [EC-CUBE/ec-cube#1551]
インストール時、以下のような エラーが発生している

`create table...
./vendor/bin/doctrine:行1: ../doctrine/orm/bin/doctrine: そのようなファイルやディレクトリはありません
migration...`

`  [Doctrine\DBAL\Exception\TableNotFoundException]
  An exception occurred while executing 'select count(*) from dtb_member':
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.dtb_membe
  r' doesn't exist
`

**Comment by nanasess** [comment]
`app/config/eccube` 以下にある `*.yml` ファイルを削除してみてはいかがでしょうか?

**Comment by cnbillow** [comment]
すみませんが、試しませんでした。０から再度環境を作って出来ました。
