### ISSUE TITLE
テキストの不統一：受注マスターの検索ボックスのラベルを購入→注文へ

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1553]
受注管理画面で受注マスターの検索ボックスのラベルだけが「購入者」「購入者会社名」となっている
他の画面では「注文者」という表現を利用

検索ボックスも「注文者」「注文者会社名」と統一するのが望ましい

**Comment by ryo-endo** [comment]
3.0.11で対応済み。
