### ISSUE TITLE
テキストの不統一：受注編集の備考→お問い合わせに修正

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1554]
商品購入時のお問い合わせが、受注編集画面では、備考として表示される。

ショップが、顧客に表示される内容であることを理解できずに、利用する可能性があり危険。

顧客側の表記と同様に、受注編集時のラベルも「お問い合わせ」とするのが望ましい

**Comment by ryo-endo** [comment]
3.0.11で対応済み
