### ISSUE TITLE
管理画面マスターデータ管理の登録の改善

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#1555]
## 前提

マスターデータ管理を操作する際にIDを変更するということもあると思います。
また、登録したものを確認するという作業も発生するかと思います
## 問題・課題

IDを変更しようとしてIDの内容を書き換えて登録すると変えた内容が追加して登録されます。
また、登録後、セレクトボックスの内容が元に戻ってしまうため登録内容の確認に手間取るという状態です。
## 対応方法

IDを変更するというのはあまりしてほしくない動作ではあるので、この点は説明文を追加して対応するのでも問題ないかと思います。
登録後のセレクトボックスの内容の保持についてはパラメータをつけてリダイレクトすることでもともとの値を引き継いだらよいかと思います。

**Comment by izayoi256** [comment]
> 登録後のセレクトボックスの内容の保持についてはパラメータをつけてリダイレクトすることでもともとの値を引き継いだらよいかと思います。

この方法だとPOST時とGET時の処理を分けるのが煩雑になってしまいますから、ルーティングを下記のように変更してエンティティ名を保持した方が自然かと思いますが、影響大きすぎるでしょうか？

https://gist.github.com/izayoi256/94831f96d96c40b8fc386146b71af32c

**Comment by Yangsin** [comment]
#1702 #1703 #1581 で修正済み
