### ISSUE TITLE
商品登録画面で、カテゴリーの表示が実際のカテゴリー階層と一致していない

### ISSUE THREAD

**Issue by cnbillow** [EC-CUBE/ec-cube#1556]
下記の手順操作で不具合が発生しました。
①カテゴリー1を登録
②カテゴリー2を登録
③カテゴリー1の子カテゴリー1-1、1-2
④カテゴリー1とカテゴリー2の位置を交換
⑤カテゴリー1の子カテゴリーはなくなる、カテゴリー2の子カテゴリーになります。

**Comment by ryo-endo** [comment]
⑤についてですが、どの画面で現象をご確認されましたでしょうか？
・TOPページのカテゴリー表示では、⑤の現象は発生していませんでした。
・商品登録ページの商品カテゴリーでは、⑤の現象が発生しているように見えました。

**Comment by ryo-endo** [comment]
ref https://github.com/EC-CUBE/ec-cube/issues/1385

**Comment by chihiro-adachi** [comment]
フロント側でも発生していたため、#1813 で修正しています。

**Comment by lqdung-lockon** [comment]
This is additional patch for this vulnerability. Fixed product management interface and add unit tests. #1893
