### ISSUE TITLE
コマンドラインからControllerを呼び出す方法はありますか

### ISSUE THREAD

**Issue by h-tagami777** [EC-CUBE/ec-cube#1557]
お世話になります田上拡志（たがみひろし）と申します。

ECCube３のAdmin機能にある、CSVインポートのコントらーらをコマンドラインのPHPから呼び出したいのですがその方法がわからず、途方に暮れています。
何か良い方法があれば教えていただけないでしょうか。

**Comment by Yangsin** [comment]
お手数ですが、EC-CUBEの利用方法や個別のカスタマイズについては、開発コミュニティ（http://xoops.ec-cube.net/）をご利用いただけますでしょうか。
同じような疑問をもたれる方のためにも、ご協力をお願いいたします。
