### ISSUE TITLE
【提案】ショップマスターのメールアドレスのラベルを変更してはいかがでしょうか

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1562]
## 問題・課題
ショップマスターにあるメールのラベルについてですが、実態と合っていないので以下のように変更を行いたいのですが、いかがでしょうか。
例）email01 は会員登録完了メールなどでも使用しています。

## 対応方法
* 商品注文受付メールアドレス → 送信元メールアドレス
* 問い合わせ受付メールアドレス → 問い合わせ受付メールアドレス
* メール送信元メールアドレス → 返信受付メールアドレス
* 送信エラー受付メールアドレス → 送信エラー受付メールアドレス

もしくは以下のように用途まで記載してはどうでしょうか。
* 商品注文受付メールアドレス → 送信元メールアドレス(From)
* 問い合わせ受付メールアドレス → 問い合わせ受付メールアドレス(From, ReplyTo)
* メール送信元メールアドレス → 返信受付メールアドレス(ReplyTo)
* 送信エラー受付メールアドレス → 送信エラー受付メールアドレス(ReturnPath)

**Comment by ryo-endo** [comment]
変更PR取り込みましたので、Issueを閉じさせてもらいます。
