### ISSUE TITLE
お気に入りを押す→ログイン画面が表示される→ブラウザバックすると、購入ボタンを押してもお気に入りと認識される

### ISSUE THREAD

**Issue by maisumakun** [EC-CUBE/ec-cube#1564]
はじめまして、EC-CUBE 3.0.10を使っている時に、標記のような事象を発見しました（[デモサイト](http://demo3.ec-cube.net/)でも再現します）。

## 問題点の分析
お気に入りボタンを押した際に、`$('#mode').val('add_favorite');`と値が追加されていますが、ブラウザバックした際に、これがブラウザによってはそのままとなってしまうために発生する現象のようです。

## 解決策
テンプレートの`default/Product/detail.twig`で、最下部の`$('#favorite').click(...)`以下に追加して、購入ボタンを押した際には`mode`値をリセットする

```js
    $('#cart').click(function(){
        $('#mode').val('');
    });
```

ご検討のほど、よろしくお願い致します。

**Comment by nobuhiko** [comment]
これも同じ問題でしょうか
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17507&forum=8&post_id=76175#forumpost76175

**Comment by ryo-endo** [comment]
### 手順
1. ログアウトした状態にする
2. 商品詳細のページに移動
3. [お気に入りに追加]を押す
4. ログイン画面が表示されるのでブラウザバックで戻る
5. [カートに入れる]ボタンを押す
　⇒ お気に入り追加ページ（ログイン画面）に遷移してしまう(NG)

**Comment by ryo-endo** [comment]
@nobuhiko 
3.0.11でも再現したので、別要因みたいです。
#1782 作りましたので、こちらのIssueはCLOSEします。

**Comment by ryo-endo** [comment]
3.0.11で対応済み。
