### ISSUE TITLE
twig及びjsのインデントについて

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1569]
テンプレートファイルをいくつか見た限りではインデントサイズ2と4が混在している(1ファイル内に混在しているものもある)ようですが、EC-CUBE3のコーディング規約にはインデントに関する記載が見つかりません。

この辺りは開発者の裁量に任されているのでしょうか？

(jsは未確認ですが、こちらも規約には記載がないため併記。)

**Comment by nanasess** [comment]
コーディング規約には明記されていないですが、 Symfony2 にあわせて4スペースにしようということのようです。
https://github.com/EC-CUBE/ec-cube/pull/832#issuecomment-142782306

JavaScript に関しては、タブのものもありますね...

**Comment by izayoi256** [comment]
ありがとうございます。 https://github.com/EC-CUBE/ec-cube.github.io/pull/23 にて規約に追記しました。
