### ISSUE TITLE
メールが Quoted-printable だけど、Base64 の方が良くない?

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#1575]
日本では Base64 が標準的で、Quoted-printable は MUA/MTA の対応が不十分だったり、迷惑メールに振り分けられやすかったりする。というか、EC-CUBE 3 で実際に文字化けする苦情がある。

**Comment by ttsuru** [comment]
refs #1561

**Comment by nanasess** [comment]
#1597 の対応で改行コードに起因する文字化けは解消すると思われます。

**Comment by Yangsin** [comment]
文字化けの問題については、SwiftMailerのバージョン・アップで概ね解消されているので本件はクローズする予定で、Not Releaseに移動しました。
継続して議論したい点があればコメントください。

**Comment by kiy0taka** [comment]
クローズします。
