### ISSUE TITLE
FormTypeでrequiredを設定するとNotBlankが追加されるFormTypeを無効にする

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1577]
NameTypeやAddressType使用時に

```
'required' => true
```

を設定すると

```
'constraints' => array(
    new Assert\NotBlank(),
),
```

が設定されるが、
requiredとNotBlankの意味合いは異なるため修正が必要。

同様に`'required' => true`設定時にTwigで

```
{{ form_label(form.name) }}
```

を使用すると

```
<span class="required">必須</span>
```

と自動でタグが追加されるがデザインの汎用性がなくなるため、
表示させないように変更するかオプションで表示させるかを選ばせるようにすること。

**Comment by ttsuru** [comment]
@k-yamamura 
``'required' => true`` 時に ``<span class="required">必須</span>`` がでては困る時ってどんな時なのでしょうか。

**Comment by k-yamamura** [comment]
@ttsuru 
`'required' => true` としていても必須と表示させたくないデザインの時です。
default_frame.twigを修正すれば済む話しですが`'required' => true`で制御させて表示させるのも本来はすべきではありません。

**Comment by ttsuru** [comment]
@k-yamamura 
Symfonyで結構定番で必須を自動で出すのはやると思います。
やりたくないテンプレートでは form_label を使わないかそういうForm themeをつくればよいのではないでしょうか。
「本来すべきではない」という表現はなぜすべきではないのかを説明したほうが他の方が本チケットを理解できると思います。

**Comment by k-yamamura** [comment]
@ttsuru 
Symfony2のサイト上に「フォームのレンダリングのカスタマイズ方法」としても扱われていますので、カスタマイズ前提で利用者に委ねるのであれば現状のままで構いません。
http://docs.symfony.gr.jp/symfony2/cookbook/form/form_customization.html#required

`'required' => true`だから必須を表示するというのはデザインのカスタマイズ要件ですので、twig側で必須と記述しておき、必要であればform themaをカスタマイズして表示させるというのが本来すべきことです。

**Comment by ttsuru** [comment]
refs https://github.com/EC-CUBE/ec-cube/blob/76e072d6a1c9fa77c573d1af3357e832cf2830c3/src/Eccube/Resource/template/default/Form/form_layout.twig#L266

**Comment by ttsuru** [comment]
@k-yamamura 
現状、Form Themeで対応しているようでした。
「必須を外す場合にはForm Themeを使うなり、labelを手動で書く」でよいのではないでしょうか。

**Comment by shhirose** [comment]
`<span class="required">必須</span>` を表示したくないのであれば CSS で`.registration_page .required {display: none;}`のような形にすればテンプレートを修正する必要はないかと思いますがいかがでしょうか。

**Comment by kiy0taka** [comment]
#2616 に含まれますので、こちらはクローズします。
