### ISSUE TITLE
配送商品テーブルの意義

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1579]
配送商品(dtb_shipment_item)のフィールドの多くは受注商品(dtb_order_detail)のそれと重複していますが、この構造の意図が分かりません。

配送商品は、受注商品を配送先別に振り分けるためのテーブルという認識ですが、それならば主キー・配送先ID・受注詳細ID・数量程度のフィールドで事足りるはずです。

また配送商品テーブルには税に関するフィールドが存在しません。そのためマイページ/ご注文履歴詳細で注文時と税率が異なる受注を表示すると、下記画像のように2つの税込価格が表示されることになります。

http://i.imgur.com/VQ3gEhN.png

将来的に配送商品テーブルの構造を変更すべきと考えているのですが、皆様のお考えはいかがでしょうか？

もし私の認識に誤りがあったらご指摘いただけると幸いです。

**Comment by nanasess** [comment]
2.4.x までは、 `dtb_order_detail` のみでした。
2.4 から 2.11 にバージョンアップした際、複数配送先指定機能が実装され、配送先ごとの商品、数量等を指定する必要があるということで、  `dtb_shipment_item` が追加されました。
3系では #1289 のような問題もあり、多くの課題があるという認識です :worried:

**Comment by nobuhiko** [comment]
https://github.com/EC-CUBE/ec-cube/issues/654

**Comment by shinichi-takahashi** [comment]
@nobuhiko 探してました。ありがとうございます。

@izayoi256 僕もそう思ってIssueあげました。
残念ながら諸々の理由（時間がなかったわけではない）で変更できなかった箇所なんですよね...
@chihiro-adachi @Yangsin あたりが回答してくれると思います。

**Comment by Yangsin** [comment]
3.0リリース時点では、十分に検討しきれず、前例を残す形でのリリースとなっております。
その後 #654 をあげていただいておりますが、当然ながら、3.0.xで対応できるレベル感の修正でありません。
ただ、将来的にテーブルを見直すことは可能です。
というわけで、引き続き #654 でご意見、ご提案いただければ幸いです。
こちらはCloseさせていただきます。

**Comment by izayoi256** [comment]
過去に類似の問題提起があったこと、見逃しており申し訳ありませんでした。ご提示いただいたissueを拝読致します。
