### ISSUE TITLE
以前質問の関連です。(注文番号のカスタマイズ)

### ISSUE THREAD

**Issue by jef12suiken** [EC-CUBE/ec-cube#1587]
お世話になっております。
注文番号のカスタマイズで以前、プラグインとする際にアドバイスをいただきありがとうございました。

プラグインということで考えていました。また、仕様変更などがあった際にはプラグインのが対応はしやすいのかと思うのですがいろいろとファイルを作成しカスタマイズしてということでまだPHPやEC-CUBEへの知識の薄い者では難しいかなと思い
カスタマイズした注文番号をdtb_orderのテーブルに別カラム(ex:order_number)として持たせその値を表示やメールに乗せるようにしたいと考えております。

開発コミュニティにて質問させていただいた際に

・\Eccube\Entity\Order のコンストラクタか、
・\Eccube\Controller\ShoppingService::newOrder() に独自の機能を実装する。
というご助言をいただきました。

下の場合は
src\Eccube\Service\ShoppingService.php
の234行目のnewOrderに実装させればよいのでしょうか？

また、 $OrderStatus = $this->app['eccube.repository.order_status']->find($this->app['config']['order_processing']);

こちらは次にリポジトリ配下のOrderRepository.phpを呼び出しているのでしょうか？

ご知見のある方、お知恵をお貸しいただけると助かります。
よろしくお願いいたします。

**Comment by nobuhiko** [comment]
フォーラムに書いている内容をそのままこちらに書くのはやめましょう
また、こちらはカスタマイズに関する質問を書く場ではないのでフォーラムでお願いします

**Comment by jef12suiken** [comment]
閉じます
