### ISSUE TITLE
Outlook 2007 でメールを正しく受信できないことがある

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#1588]
(おそらく Subject: が長い場合に) Subject: の途中に余計な改行が入り、ヘッダーが終了と判定される。結果、ヘッダーの後半が欠落し、本文が文字化けしたメールとして受信される。

3.0.10 ユーザーから、Outlook 2007 で発現報告。

ググると、改行コードに LF と CRLF が混在した場合に発現するという情報を散見する。Outlook 2013 でも発現するらしい。

**Comment by nanasess** [comment]
この修正を試してみることは可能でしょうか？
https://gitter.im/EC-CUBE/ec-cube?at=573d5a15eea93e5742d3488c

これで直るのであれば SwiftMailer の不具合というのが濃厚です。採用してもらえるかどうか、わかりませんが、本家のほうに Pull Request 送ろうと思います。

**Comment by seasoftjapan** [comment]
ざっとソースを見ましたが、iso-2022-jp の場合の処理ですよね。utf-8 で発生した状況です。

ただ、iso-2022-jp でも同様の現象が発生し、`mb_encode_mimeheader` の方法で対応しました。結果、一旦は不具合を回避できたのですが、サイト名を変更したところ再発したという報告がありました。`str_replace` は試していなかったです。

utf-8 で本題の不具合があったために、iso-2022-jp を試した状況でして、本来は utf-8 に戻して不具合を回避したいと考えており、該当サイトで iso-2022-jp を深追いするのは現時点では難しい状況です。

**Comment by nanasess** [comment]
なるほど、、 UTF-8 でも発生するのですね。
SwiftMailer の issues を調べてみたところ、 改行コード関連の issues が山ほどでてきて閉口しました 😟 

しかし、 SwiftMailer 5.4.2 で修正された形跡があるので、 SwiftMailer をバージョンアップしてやれば直るかもしれません。(EC-CUBE3.0.10 時点では 5.4.1)
https://github.com/swiftmailer/swiftmailer/blob/v5.4.2/CHANGES#L15

それでも直らなければ、 [qdmail](http://hal456.net/qdmail/) などへの置き換えを検討したほうが幸せになれるかもしれません。。。

**Comment by seasoftjapan** [comment]
SwiftMailer 5.4.2 OK でした。

MUA のソース表示機能で見る限り、改行が スペースに変換されている感じに見え、怪しさは残っています。(EC-CUBE 2 も同様です。)

RFC の MUST のバイト数制限を無視しそうな動作に感じます。まぁ、そこまで長くなることは通常無さそうですが。

**Comment by nanasess** [comment]
> MUA のソース表示機能で見る限り、改行が スペースに変換されている感じに見え

どんなバイトコードになっているかが気になりますね。。。

**Comment by nanasess** [comment]
@seasoftjapan Outlook 2007 の検証環境を作ってみたのですが再現できませんでした。
 - mail.yml の transport は何になっていますでしょうか？
 - メールを送信している MTA は、何をお使いでしょうか？(バージョンなどもわかれば)

**Comment by nanasess** [comment]
以下の環境で再現しました。

- **MTA**: qmail
- **mail.yml の transport**: mail
- qmail-local にて Maildir に配送されたメールを IMAP で受信
- 受信したメールの Subject に LF と CRLF が混在している状況

mail.yml  > **charset_iso_2022_jp** の設定に係わらず再現するようです。

また、 SwiftMailer のバージョンを 5.4.2 へアップグレードすることで、  **charset_iso_2022_jp: false ** (UTF-8 のメール) のケースは解消できました。

**charset_iso_2022_jp: true ** で Outlook2007 で受信した場合は別途修正が必要な状況です。

**Comment by nanasess** [comment]
> charset_iso_2022_jp: true で Outlook2007 で受信した場合は別途修正が必要な状況です。

と書きましたが、よくよく調べてみると解消されていました。
ただし、UTF-8 で店舗名が全角36文字以上になると、 Outlook2007 で From が表示されなくなる不具合(もしくは Outlook2007の仕様？)が別途発生しています。

本題である文字化けは #1597 で解消されている模様ですのでクローズします。
