### ISSUE TITLE
カート複数配送の編集画面のtwigファイル内で、divのIDが重複している

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1589]
個数を分配して、複数配送先を指定しようとした際の、ループ処理の内部のIDが重複されます。

・お届け先
multiple_list__shipping_address--0_0
・数量
multiple_list__shipping_quantity--0_0
・削除ボタン
button__delete--0_0

Javascriptまわりは現状でも問題なく動作していそうです。

https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/default/Shopping/shipping_multiple.twig#L144
L149
L154

**Comment by ryo-endo** [comment]
こちら #2067 で対応してmasterにマージしましたので、Issueを閉じさせていただきます。
ご報告ありがとうございました。
