### ISSUE TITLE
項目に設定した値がnullとなってしまう

### ISSUE THREAD

**Issue by jef12suiken** [EC-CUBE/ec-cube#1591]
カスタマイズした部分となってしまうため、本来のここでの用途とは違うのかもしれませんが
該当箇所はカスタマイズ部分でなくデフォルトで存在するロジック部分のため
わかる方がいればご教示いただきたいと思い投稿させていただきます。

自分自身で新しく別カラムに注文番号を連番でないものを作成し表示やメールに載せるものとして作成しました。
注文番号を新たに作成した部分は問題なく動いており、採番しているのですが
注文後に届くメールで注文番号が空欄となってしまいました。

Entityにも追加をしており、twigも新しい項目に設定しております。

そこで、dumpさせ該当箇所を突き止めていった際に以下の部分で詰まってしまいました。
この先についてお聞きしたいのですが
vendor\doctrine\orm\lib\Doctrine\ORM
┗UnitOfWork.php
2041行目付近のdoRefreshメソッド内

$this->getEntityPersister($class->name)->refresh(
　　array_combine($class->getIdentifierFieldNames(), 　　　　　$this->entityIdentifiers[$oid]), $entity);

ここになります。

この先はどこが呼び出されるのか追えませんでした。
お分かりになる方がいましたら、ご教示いただければ幸いです。
よろしくお願いいたします。

**Comment by Yangsin** [comment]
カスタマイズに関するご質問は開発コミュニティ( http://xoops.ec-cube.net ) をご利用くださいませ。
各種サイトの用途の混同を避けるため、ご理解のほどよろしくお願いいたします。

**Comment by izayoi256** [comment]
フォーラムで疑問が解消されたようであれば本件をクローズして下さい。
