### ISSUE TITLE
path.ymlのadmin_route:の設定によってはフロント画面から管理画面に画面遷移してしまう

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#1594]
[ 現象 ]
購入フローの途中で、管理画面に遷移してしまう。

[ 再現方法 ]
①「path.yml」項目「admin_route:」を「shop」とする
②ユーザー画面で購入をすすめる
③カート画面でレジに進むボタンを押下
④管理用ログイン画面が表示される

[ 備考 ]
admin_routeの設定は例えば「s」でも「c」でもフロントで利用しているURLの前方一致の文字であれば、再現される

**Comment by chihiro-adachi** [comment]
#1613 で対応.
