### ISSUE TITLE
受注又は配送CSVダウンロード時、都道府県(ID)と都道府県(名称)が一部出力されない

### ISSUE THREAD

**Issue by ohtacky** [EC-CUBE/ec-cube#1595]
エラーの発生条件がわからないのですが、複数受注がある場合に受注又は配送CSVダウンロードすると都道府県IDと名称が一部出力されないようです。

https://github.com/EC-CUBE/ec-cube/blob/3.0.10/src/Eccube/Service/CsvExportService.php
getData内でnullが返っているわけではなく、
$data = $entity->offsetGet($Csv->getFieldName());
$Csv->getFieldName()がPrefの時、$dataの中身が空になっています。

**Comment by Yangsin** [comment]
再現がないためクローズします。
