### ISSUE TITLE
複数配送のある受注を更新すると、受注商品の数量が1になる。

### ISSUE THREAD

**Issue by ohtacky** [EC-CUBE/ec-cube#1596]
同一の商品が複数個購入され、なおかつ複数配送先がある場合、受注を編集・登録すると受注商品の数量が1になる。

**Comment by ohtacky** [comment]
src/Eccube/Form/Type/Admin/OrderType.php
266行目
$orderDetail['quantity'] = $shipmentItems[$j]['quantity'];

受注商品の数量にお届先の数量を代入している為だと思われます。

**Comment by chihiro-adachi** [comment]
現時点のmasterブランチ( https://github.com/EC-CUBE/ec-cube/commit/9c4361e27e0df01d2d28c3174a689dc19630106b )で確認したところ、再現しませんでした。

#1725 の修正により、こちらの不具合も修正されているようです。
