### ISSUE TITLE
dtb_memberのsaltがnot null になっているので2.4系からの移行ができない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1599]
not nullを外しても問題はないと思われます

**Comment by nanasess** [comment]
@nobuhiko 2.11 以降  not null になっているようですので、できればあまり変えたくないのですが、移行時のみの問題でしたら、空文字を入れる等して対応できませんでしょうか？

**Comment by okazy** [comment]
移行時に空文字を入れていただくことで移行可能です。
not null等の制約については別途検討します。
