### ISSUE TITLE
Testの整備

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#16]
現在、歴史的経緯からとお見受けしますが、``test``と``tests``に分かれておりわかりにくいと思います。
テストのカバレッジもあまり良くない状況だと思います。

こちらについて、何か整備指針などはありますでしょうか。

**Comment by shinichi-takahashi** [comment]
@ttsuru 
ベータ開発環境整備の中で、
* test/ の削除
* tests/class の削除
* Silex用のテスト環境の構築
  + tests/Eccube/Tests/Web/
  + tests/Eccube/Tests/Form/Type/
  + tests/Eccube/Tests/Service/
などを行いました。

テスト自体は継続して行っていく必要があるため、
本Issueはクローズし、テストポリシーとして提示するようにいたします。
