### ISSUE TITLE
受注編集時のdtb_order.taxの値が間違っている

### ISSUE THREAD

**Issue by nkhrk** [EC-CUBE/ec-cube#1606]
3.0.10で動作確認しています

admin/order
画面から受注情報を編集すると、`dtb_order.tax`に保存される値が間違っているようです。

taxはsubtotalの消費税分になると思いますが、商品1個分の消費税でupdateされているようです。

e.g.)
dtb_order_detailの値が
price:2800
quantity:3
tax_rate:8
の受注があった場合、編集前のdtb_order.taxの値は672になっています

この受注を編集すると dtb_order.taxの値が 224 で更新されます。
subtotal、total、payment_totalの値は正しく更新されています

**Comment by ryo-endo** [comment]
https://github.com/EC-CUBE/ec-cube/pull/1625
修正が取り込まれましたので、Issue閉じさせていただきます。
