### ISSUE TITLE
国際電話番号のバリデーション

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1609]
越境ECや多言語対応で国際電話番号の入力を考えると、tel01や検索条件電話番号の先頭に1文字以下の+を許容し、またtel_lenを増やすかtel01_lenを新設するのはどうでしょうか？

私個人は越境ECの利用経験が少ないため、頓珍漢なことを言っていたら申し訳ありません。

**Comment by nanasess** [comment]
個人的には、そもそも、3つのフィールドに分けている必要性があまり感じられないので、 `zipcode` のように 1フィールドにしてやって、国際電話番号も許容したバリデーションをすると良いのかなと。

**Comment by ryo-endo** [comment]
3.0.x系では、現状のバリデーションを修正したいと思います。ref #1649 
tel01_lenの新設や、フィールドを１つにまとめる変更は、既存へのインパクトがあるので、3.1のタイミングで議論できればと...

**Comment by tao-s** [comment]
フィールドひとつにまとめるのは賛成です。
検索もなにもかも面倒になるし。
