### ISSUE TITLE
商品の在庫数を管理しているカラムについての質問

### ISSUE THREAD

**Issue by kazunakamura** [EC-CUBE/ec-cube#1622]
ECcube3.0.10 のテーブル構造についての質問です。
dtb_product_class テーブルの stockカラム と dtb_product_stock テーブル のstockカラム、
特定の product_class_id 在庫数を管理するカラムが２箇所存在しています。

２つのテーブルで同じ値を持っている意味は何かありますでしょうか？
ソースを追いかけてみたところ、src/Eccube/Service/CartService.php の 309行目あたりに、
以下のコメントを発見しました。

         * 実際の在庫は ProductClass::ProductStock だが、購入時にロックがかかるため、
         * ここでは ProductClass::stock で在庫のチェックをする

上記のコメントの意味がよくわかりません。
２つのテーブルで管理している意味と合わせて、分かる方がいたらご教授いただけますと
幸いです！
現在、在庫周りのカスタマイズを行っているので、影響範囲を知りたいです。
よろしくお願いいたします。

**Comment by kazunakamura** [comment]
カスタマイズに関する質問はコミュニティなんですね、すみません。クローズいたします。

**Comment by chihiro-adachi** [comment]
内部仕様に関する有益な情報だと思うので、リンクしておきます。
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17797&forum=2&post_id=77157#forumpost77157

**Comment by ttsuru** [comment]
悲観的ロックをしなければもう少し処理を改善できそうな気がしますね。
