### ISSUE TITLE
URLからhtmlを削除する機能の追加

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1627]
レンタルサーバーなどDocumentRootを変更できない環境で、
EC-CUBEのURLから「html」を削除する機能を提供する。
## 現状について

該当環境でどうしてもhtmlを消したい場合は、
http://amidaike.hatenablog.com/entry/2015/07/18/151143
のような方法で、手動でファイル移動/書き換えを行っている。
## 対応内容

・管理画面に「URLからhtmlを削除する」ボタンを追加する。
・ボタンを押下すると、
　- EC-CUBE直下の.htaccessを書き換えて、mod_rewiteでhtmlにリダイレクトするようにする。
　　(IISの場合はweb.configを書き換え)
　- path.ymlを適切に更新する。
・ファイルのバックアップを.bak拡張子で保存する。（トラブル時に手動で戻せるように）
## 制限事項

・.htaccessを書き換える権限が無い/nginxなど.htaccessが利用できない環境ではこの機能を利用することはできない。
・URLからhtmlを削除した後に、元に戻すことはできない。（ロールバック機能は対応しない）

**Comment by nanasess** [comment]
関連 #558

**Comment by ryo-endo** [comment]
今回の対処は、mod_rewriteが利用できるサーバ環境が前提になります。

**Comment by ryo-endo** [comment]
EC-CUBE直下の.htaccessで、/html/index.phpにmod_rewriteするだけでは、サブディレクトリにインストールされた場合などを考慮すると、実現が難しいことがわかった。

本体変更1．
ルーティングのmountにベースパスの指定が必要。
Application.php
```
$this->mount('', new ControllerProvider\FrontControllerProvider());
　↓
$this->mount('/ec/', new ControllerProvider\FrontControllerProvider());
```

本体変更2.
`$app['request']->getPathInfo()`で取得できる値が「/ec/admin」のようになるので、`$app['request']->getPathInfo()`を使用している箇所をすべて修正必要。

**Comment by ryo-endo** [comment]
とくに「本体変更2」のほうが、影響度が大きい。
ルーティングのセキュリティにも関わってくるところなので、今回のタイミングでは、この使用での対応を見送る。

**Comment by ttsuru** [comment]
@ryo-endo 
全てのpathをmod_rewriteで web/ 以下にすれば、両方共必要ないのではないでしょうか。
おそらく、mod_rewriteの書き方に問題があります。

**Comment by ryo-endo** [comment]
@ttsuru 
いろいろトライしてみたのですが...
下記のようなディレクトリ構成にしたときに、requestで取得できるPathがどうしても`/ec/`や`/ec/products`みたいになってしまい、現状のままだと上手くルーティングできませんでした。（404になってしまう）
```
public_html/
   /ec/
       .htaccess
       /html/
           index.php
```
```
order allow,deny
allow from all
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^(.*)$ html/index.php [QSA,L]
</IfModule>
```
なにか上手いmod_rewriteの書き方や、Symfonyの設定方法などご存知でしたら教えていただきたいです。

**Comment by ttsuru** [comment]
@ryo-endo 
コメント気づきませんでした。
もう一つのチケットにコメントしときます。

**Comment by xuelian311** [comment]
#1750 で対応済みであるため、クローズいたします。
