### ISSUE TITLE
Serviceにプラグイン用フックポイントの追加

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1628]
EC-CUBEや各種プラグインは、Serviceを通してカートや受注のデータを変更しているが、イベントが無いためデータが変更されたタイミングを検知することができない。（一部はすでに用意されている）

以下のServiceの関数に対して、フックポイントの新規追加を行う。
あわせてテストコードも追加する。

**CartService**
　public function addProduct($productClassId, $quantity = 1)
　public function removeProduct($productClassId)
　public function clear()
　public function setProductQuantity($ProductClass, $quantity)

**ShoppingService**
　public function setCustomerUpdate(Order $Order, Customer $user)
　public function setDiscount(Order $Order, $discount)
　public function setOrderUpdate(Order $Order, $data)
　public function setStockUpdate($em, Order $Order)
　　＋
　購入トランザクションの通知をするためのイベントを新規作成（既存のnotifyCompleteと同様）
　public function notifyProcessPurchase(Order $Order)

**MailService**
　不要(すべてイベントある)
**OrderService**
　不要(すべてイベントある)
## 完了条件
- [ ] 上記の関数にフックポイントを追加
- [ ] 作成したフックポイントのTestコードを追加

**Comment by ryo-endo** [comment]
ServiceからServiceを呼び出したりしているので、末端の関数だけ洗い出してリストアップしました。
過不足あればコメントお願いします。

**Comment by Yangsin** [comment]
ここで求めていた範囲は、3.nのPurchaseFlowで対応できそうなので、Serviceにはいれない方向で検討。

**Comment by Yangsin** [comment]
PurchaceFlowの実装 #2424
