### ISSUE TITLE
idセレクタのcontents_topが重複している

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1631]
src/Eccube/Resource/template/default/Block/new_product.twig
内で記述されている

``` html
<div id="contents_top">
```

ですが、
src/Eccube/Resource/template/default/default_frame.twig
のレイアウト管理で使用されている

``` html
<div id="contents_top">
```

とIDが重複しています。

関連 #1438

**Comment by ryo-endo** [comment]
ref #1519

**Comment by Yangsin** [comment]
3.nでのスタイルガイドでの対応事項としてクローズ
