### ISSUE TITLE
全体的にもっさり

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#1634]
全体的にもっさりしているという意見がチラホラ聞こえます。
この辺心当たりありますか？

**Comment by seasoftjapan** [comment]
以前にベンチマーク的なデータもここに上がっていたような。ざっくり、2系の2倍とかでしたかね。
(フレームワークや ORM のコストも大きいかと推測していますが、プロファイル分析とか興味深いですね。)

**Comment by tao-s** [comment]
2倍！
そんな遅かったんですか...
どうにか早くしたいですね

**Comment by nanasess** [comment]
いろいろ調べてるんですが、 Doctrine の各種キャッシュを駆使したりして頑張らないといけないみたいです

**Comment by tao-s** [comment]
あー、concrete5でも色々やってますね

**Comment by nanasess** [comment]
#1638 具体的な改善案

**Comment by ryo-endo** [comment]
具体的な対策は、#1638 と #1639 で行っていきますので、こちらのIssueは`Not release`とさせていただきます。

**Comment by ryo-endo** [comment]
上記のとおり、具体的な対策のIssue作成しましたので、こちらのQAはCLOSEします。
