### ISSUE TITLE
【仕様確認】商品規格が存在する商品を、商品登録CSVアップロード機能を使って新規登録する方法について

### ISSUE THREAD

**Issue by kk580923** [EC-CUBE/ec-cube#1635]
【仕様確認】商品規格が存在する商品を、商品登録CSVアップロード機能を使って新規登録する方法について

１．商品IDを空、規格分類1(ID)、規格分類2(ID)に適切なIDを記入し、アップロードすると、別商品として登録されてしまう。

２．（１．）で登録されて商品IDを、商品IDに記入し、規格分類1(ID)、規格分類2(ID)に適切なIDを記入し、アップロードすると、登録される規格、登録されない規格とゆれが発生する。

**Comment by kk580923** [comment]
@ryo-endo 

お疲れ様です、岸田です。

下記２段階でCSVアップロードすることで、規格あり商品を登録できました。

１．規格なし商品として、新規登録する
２．（１．）で登録した商品に対して、規格あり商品として、更新する。

※　起票時のコメント（２．）では上記手順でうまくいかないと記載していましたが、ゴミデータがあり、上手くいってなかったようです。

以上、よろしくお願いいたします。

岸田

**Comment by xuelian311** [comment]
本件解決できたようですので、クローズいたします。
