### ISSUE TITLE
パフォーマンス改善(Doctrineチューニング)

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1639]
## 対応内容

**LazyLoadの最適化**
　n+1問題への対応。

**Resultキャッシュ**
　データの更新頻度が低いテーブルのSELECT結果をキャッシュしておくことで、パフォーマンスを向上させる。

**Comment by ryo-endo** [comment]
こちらの対応内容については、既存動作への影響が大きいと判断して、メジャーVerUp(3.1)対応としています。

**Comment by okazy** [comment]
N+1問題は以下のプルリクで対応
https://github.com/EC-CUBE/ec-cube/pull/3581

Resultキャッシュについては遅い部分を個別で対応していただく想定
