### ISSUE TITLE
受注編集時、複数配送の受注データで2件目以降の数量変更ができない

### ISSUE THREAD

**Issue by hyacinth1** [EC-CUBE/ec-cube#1641]
3.0.10ですが複数注文された受注データのうち
１個目は数量変更できますが
2個目以降は数量変更ができないです。

※１
dtb_shipment_itemテーブルのquantity値は変更されますがdtb_order_detailテーブルのquantity値が変更されませんでした

※２
SQLログから実際実行されるUPDATE文を見ましたが2商品目以降はupdate文からquantityカラム指定がなくなっていました。

**Comment by Yangsin** [comment]
#1758 #1725 の修正により修正されている可能性があります。

**Comment by chihiro-adachi** [comment]
3.0.13で動作確認したところ再現しませんでした。
dtb_order_detail.quantityの値も正しく更新されています。

修正済としてクローズさせていただきます。
