### ISSUE TITLE
本体拡張機構の追加（実験的な実装

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1642]
プラグイン作成ではなく、カスタマイズを行うにあたって、プラグイン機構を利用するケースを想定
現状の、手続きが煩雑な箇所を簡略化したい
## フックポイント利用の簡略化
- EventSubscriberInterfaceを実装したクラスを設置することで、フックポイントを利用できる
- 利用するフックポイント及び優先順位は、getSubscribedEventsで指定する
- ファイルは、app/Ext/Event.phpに配置する
## 汎用テーブルの作成
- 設定関連情報や生成される登録情報を保持する汎用テーブル
- テーブルレイアウト
  - id
  - plugin_code
  - option_key
  - option_value
## 実装

pull request 
https://github.com/EC-CUBE/ec-cube/pull/1663
## 拡張機構の利用方法

http://ec-cube.github.io/experimental.html

**Comment by okazy** [comment]
EventSubscriberとCustomizeディレクトリで対応可能なのでクローズします。
