### ISSUE TITLE
プラグイン一覧画面でREADMEを表示する

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1643]
## 前提

プラグインに関する情報がオーナーズストアにしかない。
契約等の関係でオーナーズストアに出せない独自プラグインがある。
## 問題・課題

オーナーズストアにしか情報がないため、使い方や操作方法、問い合わせ先の確認にオーナーズストアに行って、プラグインを検索しなければならない。
また、独自プラグインでは設定方法、問い合わせ先などがわからない。
よって、オーナーズストアを見に行かなくてもある程度の情報を表示できるようにしたい。
## 対応方法

プラグイン一覧画面に README を表示するリンクを追加
プラグインの config.yml に`const.readme`があればそれをモーダルウィンドウで表示する。
README は HTML の表示を可能とし、リンク等を貼れるようにする。

**Comment by ttsuru** [comment]
@shhirose 
素晴らしいと思います。
HTMLではなく、Markdownにしてはいかがでしょうか。

**Comment by shhirose** [comment]
対応案を PR しました。

@ttsuru 
Markdown にしたいですね。
できれば README.md があればそれを表示するようにしたいです。
Markdown 解析 or 変換するライブラリのおすすめはありますか？
探してみましたが結局使ったことがないものばかりなので、使用してよいかの判断ができませんでした X(

**Comment by nanasess** [comment]
どれも使ったことないですが、ご参考まで
[PHP用のMarkdownパーサーライブラリ比較](http://qiita.com/naga3/items/eb638d90e77fa0e1ae0b)

**Comment by ttsuru** [comment]
@shhirose 
PHPでMarkdown表示する機会がなかったので内容についてはわかりません・・・
Composerで管理できるもの、Markdown Extra に対応しているものがいいと思いました。

**Comment by shhirose** [comment]
@ttsuru 
ひとまず @nanasess さんの提示URLにあるもので、composer で提供されているもので検証はしてみます。

が、PRしてる内容でマージ後に改修、でも良いかなと思っています。
その場合は、README.md があればそれを使用して、そうでなければ config.yml を見るという形にしようと思います。
