### ISSUE TITLE
【提案】プラグイン同士でルーティングが被らない仕組みが必要ではないか

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#1648]
## 問題・課題

プラグインでどのようなURLを使用するかが、プラグインのソースコードを確認しなくてはわからない。
それにより、たまたま URL が被った場合に予期せぬ動作を行ってしまう。
- URLはプラグインAのbindを使用したが、ルーティングの登録順番により、プラグインBの画面が表示される
- 管理画面のURLと被った
## 対応方法
- オーナーズストアに使用するURLの一覧を入力してもらい、プラグインの詳細画面で表示する。
- プラグインの`config.yml`に使用するURLのパターン一覧を入力してもらい、プラグイン一覧に表示する。
- ルーティングの設定を`ServiceProvider`ではできなようにする。
- プラグインが有効になった際に同一のルーティングが複数あった場合に無効化する。

など、色々考えてみたのですが、良い実装方法が思い浮かびません。
何か妙案ありませんか？

**Comment by nanasess** [comment]
例えば、あるプラグインをカスタマイズするため、別のプラグインを作成するケースもあると思いますので、予期せぬ重複を防ぐ意味合いですよね。
根本的には、プラグイン同士の排他と依存を制御できて、かつ URL の重複が意図したものかどうかを制御できるといいですよね。

Yaml や JSON などの設定ファイルでルーティングを設定できるようにして、本体側でチェックできれば実現できそうですが、 Silex の作法から外れると思いますので、良いのかどうか、わかりません。。。

**Comment by Yangsin** [comment]
管理画面であれば規約などで整備できるがフロントのURLは自由に設定したいものだと思いますので個別でカスタマイズなり調整してもらうしかないかと思っています。

**Comment by xuelian311** [comment]
開発終了となった3系の質問で議論も進んでいないため、クローズさせていただきます。
