### ISSUE TITLE
nav.twigについて

### ISSUE THREAD

**Issue by e2haining** [EC-CUBE/ec-cube#1652]
管理画面にメニューを追加する際は、別ウィンドウや、cllassをつけたりしたいときに、nav.twigを確認すると、どうやらid, name, urlしか指定ができないようです。

classや、targetなども指定できると助かります。

**Comment by chihiro-adachi** [comment]
@e2haining 
別ウインドウ/同一ウインドウがメニュー中に混在すると操作感が混乱しそうなので、少し避けたいですね。
classについてはあまりイメージがつかないのですが、どんな利用をされるのでしょう。

**Comment by seasoftjapan** [comment]
外部サービスへリンクさせるなど、用途はありそうな。

拡張用に用意しておいて、標準実装では使わないというのは、ありだと思う。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
