### ISSUE TITLE
商品一覧。存在しないカテゴリへアクセス時のエラーメッセージ

### ISSUE THREAD

**Issue by tomothumb** [EC-CUBE/ec-cube#1658]
商品一覧で、存在しないカテゴリへリンクさせた場合、
/products/list?category_id=xxxx

エラーメッセージは「有効な値ではありません」と出る。

文言例
- ご指定のカテゴリは存在しません。

**Comment by ryo-endo** [comment]
ありがとうございます。
ご提案いただいた文言（ご指定のカテゴリは存在しません。）が、2系と同じなので、それでいいと思います。

**Comment by chihiro-adachi** [comment]
こちら確認しましたが、このエラーメッセージは意図せず表示されている様子。

- 検索パラメータをhiddenで保持するために、`freeze_type_text=false`でフォームの描画を非表示にしている
- が、エラーメッセージだけは、`freeze_type_text=false`でも表示されてしまっている

状態のようです。※こちらは別途issueを立てます。

修正としては、

- カテゴリが存在しない場合は、ページがありませんのエラー画面を表示(商品詳細画面に合わせる)
- 現状では適切な表示ではないですが、#1697 が取り込まれれば、2系と同様のレイアウト表示となります。

のように対応しようと思います。

**Comment by Yangsin** [comment]
#1697 は採用を見送っているため実装方針から再検討が必要

**Comment by chihiro-adachi** [comment]
存在しないカテゴリが指定された場合は、全てのカテゴリでの検索になっているため、こちらも考慮が必要

- ProductControllerで、$searchForm['category_id']のエラーチェックを行う
- エラーが有る場合は、ProductRepository::getQueryBuilderBySearchDataで、Categoryはnullでの検索を行う
- list.twigで、表示の制御を行う
  - ○件の商品が見つかりました-> ご指定のカテゴリはありません

くらいの実装で可能かと思われます。

**Comment by ryo-endo** [comment]
期待結果をまとめます
- 「有効な値ではありません。」というメッセージは表示されない。
- 「ご指定のカテゴリは存在しません。」という新規メッセージを表示する。
- 検索結果は、紛らわしいので表示しない。

**Comment by t-nagahashi** [comment]
動作確認OKです。
![default](https://cloud.githubusercontent.com/assets/13776434/22732543/ddbdfd86-ee31-11e6-9611-12c33d1e2693.PNG)
![default](https://cloud.githubusercontent.com/assets/13776434/22732545/dfab706a-ee31-11e6-9991-c1985ab584e4.PNG)
![default](https://cloud.githubusercontent.com/assets/13776434/22732547/e32f56d4-ee31-11e6-90eb-48128cce1ccd.PNG)

**Comment by ryo-endo** [comment]
対応してmasterへの取り込み完了しました。
