### ISSUE TITLE
商品管理画面で在庫数を変更しても更新日が変更されない。

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1671]
商品管理画面で表示している更新日はdtb_productのupdate_dateを参照している。

在庫数のみを変更した場合、dtb_product_classのupdate_dateしかDB更新されないため、
商品管理画面での更新日(dtb_product.update_date)は変更されずに表示されている状態となる。

**Comment by trebla-on** [comment]
issues 1671 商品管理画面で在庫数を変更しても更新日が変更されない #1863

**Comment by trebla-on** [comment]
対応しました。

**Comment by Yangsin** [comment]
#1704 を採用しました。
