### ISSUE TITLE
パフォーマンス改善 - HTTPキャッシュ対応

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1673]
パフォーマンス改善 #1638 の対応としてHTTPキャッシュの仕組みを用意する。
http://silex.sensiolabs.org/doc/1.3/providers/http_cache.html

デフォルトでは無効としておき、設定を変更することでHTTPキャッシュを使用できるようにする。
但しindex_dev.phpを使用時はキャッシュされない。

* フロント
`max-age`と`ETag`を設定してキャッシュを行う。
max-ageの秒数とHTTPキャッシュ適用画面は設定ファイルで変更可能とし、
Cache-Controlヘッダに`public`も追加する。
フロント画面でHTTPキャッシュを行う画面は、他者と共有されても良い画面及び、
tokenが使用されていない画面をキャッシュ対象とする。

* 管理画面
`ETag`のみ設定してキャッシュを行う。
管理画面ではCache-Controlヘッダに`private`も追加し、全ての画面をキャッシュ適用対象とする。

**Comment by k-yamamura** [comment]
フロントでHTTPキャッシュを適用する画面はrouteで指定し、
HTTPキャッシュの設定を有効にするとキャッシュが行われる。
デフォルトで以下の画面をキャッシュ対象として設定する。

- homepage
- product_list  
- block_category
- block_news
- block_search_product
- help_about
- help_guide
- help_privacy
- help_tradelaw
- help_agreement

上記以外の画面で適用したい場合、
` php app/console router:debug ` 
でrouteが確認可能。ただし、tokenが含まれる画面はキャッシュ対象外とすること。
また、キャッシュ対象外にしたい場合、route定義を削除すること。

**Comment by ryo-endo** [comment]
3.0.11で対応済み。
