### ISSUE TITLE
入力項目（単位：金額）で、カンマありで登録すると、エラーとならず、途中（カンマまで）までしか登録されない

### ISSUE THREAD

**Issue by kk580923** [EC-CUBE/ec-cube#1678]
再現手順、以下となります。

利用条件TOに、3,000を入力し、登録する。
http://site3.ec-cube.net/admin/setting/shop/payment/39/edit
↓
結果、途中（カンマまで）=>3で登録される。

岸田

**Comment by izayoi256** [comment]
Form::handleRequest()時に数値型にキャストしているようですね。

[grouping](http://symfony.com/doc/current/reference/forms/types/number.html#grouping)オプションを使えば入力時のカンマ区切りには対応できそうですが、

フォーム出力時にもカンマ区切りで表示されてしまうようです。

**Comment by ryo-endo** [comment]
対応するとなると、方針を決めて全体的に適用する必要がありそうですね。
直近の対応が難しそうですので、まずは`3.0.x`とさせていただきます。

**Comment by trebla-on** [comment]
対応中です
