### ISSUE TITLE
Symfonyログの出力内容を見やすくするためにライブラリを導入

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1679]
開発時に出力されるSyfmonyログの内容が見づらいため以下のライブラリが導入可能か検討する。

https://github.com/EasyCorp/easy-log-handler

**Comment by ryo-endo** [comment]
@chihiro-adachi そのままは利用できないようです。お時間あるときにご確認お願いします。

**Comment by Yangsin** [comment]
現状は利用できないためNotReleaseに動かします。

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
