### ISSUE TITLE
Entity をセッションに格納し、再取得した際に __PHP_Incomplete_Class となってしまう場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1680]
Entity をセッションに格納し、再取得した際に `__PHP_Incomplete_Class` となってしまう場合がある。

Lazy loading 対象となった Entity は Doctrine Proxy クラスを経由して取得するが、このインスタンスをセッションに格納し、再取得しようとすると、  `__PHP_Incomplete_Class` となってしまう。

通常、 `session_start()` の際に、対象となるクラスのファイルを読み込んでおく必要がある。
しかし、 Doctrine Proxy のキャッシュファイルを読み込むのは、 `session_start()` より後のタイミングになるため、  `__PHP_Incomplete_Class` となってしまう。

以下の検証コードで再現する。

``` php
class TopController
{

    public function index(Application $app)
    {
        $Customer = $app['eccube.repository.customer']->find(1);
        $session = $app['session'];

        if (!$session->has('pref')) {
            // XXX ここでは \Eccube\Entity\Master\Pref ではなく Doctrine Proxy オブジェクトが返ってくる
            $Pref = $Customer->getPref();
            $session->set('pref', $Pref);
        }
        $Pref = $session->get('pref');
        // __PHP_Incomplete_Class となってしまう
        dump($Pref);
        return $app->render('index.twig');
    }
}
```

解決には `unserialize_callback_func` を実装する必要がある
http://php.net/manual/ja/var.configuration.php#unserialize-callback-func

参考
https://github.com/doctrine/doctrine2/issues/2345#issuecomment-162358408

**Comment by nanasess** [comment]
以下のような修正で対応可能。


```diff
modified   src/Eccube/Application.php
@@ -292,6 +292,7 @@ class Application extends ApplicationTrait
 
     public function initSession()
     {
+        ini_set('unserialize_callback_func', 'Eccube\Application::proxymissing');
         $this->register(new \Silex\Provider\SessionServiceProvider(), array(
             'session.storage.save_path' => $this['config']['root_dir'].'/app/cache/eccube/session',
             'session.storage.options' => array(
@@ -997,4 +998,13 @@ class Application extends ApplicationTrait
         }
         return true;
     }
+
+    public static function proxymissing( $name ) {
+        $proxyDir = __DIR__.'/../../app/cache/doctrine';
+        if ( strpos($name, 'DoctrineProxy\__CG__\Eccube\Entity') !== false) {
+            $name = str_replace('\\', '', $name);
+            $name = str_replace('DoctrineProxy', '', $name);
+            require $proxyDir.'/'.$name.'.php';
+        }
+    }
 }
```


しかし、 Doctrine Proxy クラスファイルが存在しない場合はエラーになってしまうため、  console コマンドで生成しておく必要がある

参考
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/advanced-configuration.html#auto-generating-proxy-classes-optional

**Comment by nanasess** [comment]
本 issues の修正案を適用すると、ブロック管理で Doctrine のキャッシュが削除され、システムエラーが発生してしまう模様

https://github.com/EC-CUBE/ec-cube/issues/1953

**Comment by ttsuru** [comment]
SymfonyではEntityをSessionに入れない設計がベストプラクティス的な感じがあります。

**Comment by Yangsin** [comment]
「SessionにEntityを入れない」という内容を開発のガイドラインなどに追加することにします。

**Comment by chihiro-adachi** [comment]
本体側では解消されているため、クローズします。
