### ISSUE TITLE
お届け先編集画面のPageLayoutが存在しない

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1685]
mypage_deliveryとmypage_delivery_newのPageLayoutは存在するが、

mypage_delivery_editが存在しないためお届け先編集画面でブロックを利用できない。

**Comment by izayoi256** [comment]
EC-CUBEの本体開発方針として、dtb_page_layoutのようなテーブルにレコードを追加したいときはどのように記述すればよろしいでしょうか？

ID決め打ちだと重複する恐れがありますし、MAX(page_id)で動的に追加する感じでしょうか？

**Comment by chihiro-adachi** [comment]
@izayoi256 

マイグレーションで追加する際は、以下のように行っています。

https://github.com/EC-CUBE/ec-cube/blob/76e072d6a1c9fa77c573d1af3357e832cf2830c3/src/Eccube/Resource/doctrine/migration/Version20151116142354.php#L22

**Comment by izayoi256** [comment]
@chihiro-adachi 
私の確認不足でお手数をかけさせてしまい申し訳ありません。ありがとうございます。

**Comment by ryo-endo** [comment]
対応マージしましたのでCLOSEさせていただきます。
