### ISSUE TITLE
パフォーマンス改善 - 使用していないdtb_category_total_countとdtb_category_countテーブルの結合を削除する

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1686]
テーブルとして存在しているが現在使用されていない
`dtb_category_total_count`と`dtb_category_count` の結合を削除する。

Category.dcm.ymlファイルにoneToOneで結合されている条件を削除し、
Category.phpから該当の関数を削除する。

テーブル自体は残しておく。

**Comment by chihiro-adachi** [comment]
#1692 #1708 で対応
