### ISSUE TITLE
【提案】 新イベントの追加

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1687]
例えば注文画面のテンプレート介入でDOM操作をしたい場合、下記のようにevent.ymlにイベントを列挙する必要があります。

``` php~~~
eccube.event.route.shopping.response:
    - [onShoppingRender, NORMAL]
eccube.event.route.shopping_confirm.response:
    - [onShoppingRender, NORMAL]
eccube.event.route.shopping_delivery.response:
    - [onShoppingRender, NORMAL]
eccube.event.route.shopping_payment.response:
    - [onShoppingRender, NORMAL]
#以下続く
```

ApplicationTrait::render()で描画した後にもイベントを設定するのはどうでしょうか。

例: https://github.com/EC-CUBE/ec-cube/commit/0fc37a40f4c25a06a07db51eb44da87c8420faab (イベント名は適当です)

**Comment by kiy0taka** [comment]
テンプレート介入については競合の問題が多発するため、3.nでは #2440 の方針を進めています。
