### ISSUE TITLE
会員登録完了画面が表示されない

### ISSUE THREAD

**Issue by infactkato** [EC-CUBE/ec-cube#1689]
[OS] mac OSX
[PHP]   5.4.45
[データベース]    MySQL 5.6.22
[WEBサーバ]  Apache/2.4.20
[ブラウザ]  Chrome
[現象]    
B2B EC-cube http://www.ec-cube.net/b2b/ を利用して簡単なカスタマイズの構築をしています。
テーマはスピリットオブ様からライセンスを購入。

会員登録した際に仮会員になっていたのでパラメーターで
CUSTOMER_CONFIRM_MAIL　false
PRE_CUSTOMER_WAIT　0
に変更

会員登録した際に
メール　本会員登録完了
ECcube管理画面会員マスター　本会員で登録済

ですが実際会員登録をすると会員登録完了画面のみうまく表示されず
「システムエラー
システム管理者に確認してください」
と出ます。

再びパラメーターを
PRE_CUSTOMER_WAIT　1
にすると仮会員ですが問題なく会員登録完了画面が表示されます。

以下デバッグモードで出たエラーです。
▼▼▼ デバッグ情報ここから ▼▼▼
<home url>/entry/?

USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:47.0) Gecko/20100101 Firefox/47.0
Fatal error(E_ERROR): Call to undefined method SC_Customer_Ex::setAdjustCustomerData() on [/<ディレクトリ名>/data/class/SC_Customer.php(151)]
▲▲▲ デバッグ情報ここまで ▲▲▲

2つ同時にライセンスをとり構築していますが2つとも同様のエラーが出ました。
バグでしょうか？
よろしくお願いします。

**Comment by Yangsin** [comment]
ご報告ありがとうございます。
こちらはオープンソース版開発用のGitHubでのすので、EC-CUBE B2Bに関する質問はクローズさせていただきます。
ご報告の内容は、別途EC-CUBE B2Bの開発チームに連携させていただきます。

**Comment by infactkato** [comment]
かしこまりました。
ご確認ありがとうございます。
よろしくお願いいたします。
