### ISSUE TITLE
【レイアウト崩れ】ゲスト購入、ご注文内容確認のお客様情報編集フォーム

### ISSUE THREAD

**Issue by kk580923** [EC-CUBE/ec-cube#1696]
ゲスト購入で、ご注文内容確認ページで変更できるお客様情報編集フォームでレイアウト崩れが発生しています。

**Comment by ryo-endo** [comment]
![image](https://cloud.githubusercontent.com/assets/16891862/17844687/e1a3d90c-6876-11e6-80af-821a5770942d.png)
## 手順
1. ゲスト購入
1. 「ご注文内容のご確認」の画面で、お客様情報の「変更」ボタンをクリック。⇒キャプチャのようなフォームが表示される（NG）

**Comment by Yangsin** [comment]
#1267 の修正時にあわせてデザイン調整するくらいがよさそうですね。

**Comment by chihiro-adachi** [comment]
#2155 で対応
