### ISSUE TITLE
Directory Structure について

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#17]
今後のDirectory Structureについて、何か指針はありますでしょうか。
大幅に構造が変わるようですので、わかりやすく、トレンドな感じにまとめてはいかがでしょうか。

**Comment by shinichi-takahashi** [comment]
@ttsuru 
構造の変更に伴い、ディレクトリ構成が変わるのは自然だと考えているため、「変更してはいけない」という指針はありません。
トレンドな感じというとどんなイメージでしょうか？
* app
  + Controller
  + Model
  + View
* libs
* vendor

のような感じでしょうか？

**Comment by ttsuru** [comment]
@shinichi-takahashi 
現状、とくにイメージはありませんが、今のdata/smarty/templates みたいなのはわかりづらいので変えたほうがいいと思います。
後ほど、自分のフォークを更新しときます。

**Comment by shinichi-takahashi** [comment]
@ttsuru 
ご意見ありがとうございます。
psr-0準拠でおつくりいただいたので、基本はそちらから大きく変更しないということで、本issueをcloseさせていただきます。
