### ISSUE TITLE
ブロック挿入用の入れ子構造が、デザインと合っていない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1712]
管理画面で設定できるレイアウト編集のフレームと、`default_frame.twig`の構造にずれがある。
以下で修正をいただいているが、変更の影響が大きいため、3.xでの対応を検討する

refs #1438

**Comment by Yangsin** [comment]
3.nでstyle-guideでコーディング見直しのためこちらはクローズします。
