### ISSUE TITLE
【管理画面】会員編集の購入履歴に購入処理中のものが表示される

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1715]
3.0.10にて確認しております。
実際に運用されている複数の方から「購入履歴に載っているが決済されてない」という問い合わせをいただいております。
購入履歴には「購入処理中」のものは表示しないほうが良いのではないかと感じています。
ご検討のほどよろしくお願い致します。

**Comment by chihiro-adachi** [comment]
#1807 で修正
