### ISSUE TITLE
管理画面 - 複数配送時に同じ商品を別々のお届け先に追加すると、受注明細が重複する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1721]
1. **お届け先を新規追加** で、お届け先を2箇所追加する
2. それぞれ、 **パーコレーター** を追加する
3. 受注明細に **パーコレーター** が 2行表示されてしまう

![default](https://cloud.githubusercontent.com/assets/815715/18193848/69c9f1ec-711c-11e6-92ad-25bfa4809443.PNG)

受注明細は、各お届け先の商品がマージされ、表示されるのが正しい。

**Comment by nanasess** [comment]
更に、お届け先1の商品数を更新すると、商品明細1行目の数量は更新されるが、
お届け先2の商品数を更新した場合は、商品明細行に反映されない

**Comment by izayoi256** [comment]
https://github.com/EC-CUBE/ec-cube/pull/1725 の作業中に疑問を感じたのですが、EC-CUBE3としては「受注詳細内」及び「配送先ごとの配送商品内」に同じ商品規格が複数行存在することは許容される動作なんでしょうか？

もし許容するのであれば本issueは対応不要でしょうし、許容しないのであれば既存のデータをどのように扱うのか(同じ商品規格はマージする？税率や金額が違う場合は？マージするタイミングは？そもそも既存のデータはマージしない？等)を検討する必要があるように思います。

**Comment by chihiro-adachi** [comment]
@izayoi256 
仕様としては、2系同等マージされるのが望ましいかと考えています。
※意図して複数行になるようにしているわけではないです、すみません。

既存のデータ(過去バージョンで既に複数行になっているデータ)は考えないといけないですね。
ぱっとは思いつかないのですが、少し検討したいと思います。
もしアイデアあればご教示いただけるとありがたいです。

**Comment by ryo-endo** [comment]
ref #1092 一緒に修正できていないか確認。
