### ISSUE TITLE
商品詳細画面でid="cart"が重複

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1723]
3.0.10にて確認しております。
商品詳細画面で、ヘッダー部のカート要素と、
「カートに追加する」ボタンのidがどちらも「cart」となっていて重複しています。

**Comment by trebla-on** [comment]
商品詳細画面で以下のソース2回表示します
`id="cart"`
現在対応はでみません、プラグインでそのIDを使ってる鹿瀬あります。

※近藤同じことならないようにテストケースを追加したほうがいいかもしれません
　　そのテストは全ての画面で同じID一個以上ないチェックすること

**Comment by Yangsin** [comment]
#1519 などと同様

**Comment by Yangsin** [comment]
3.nのスタイルガイドでの対応済みの事項としてクローズします。
