### ISSUE TITLE
受注編集画面のtwigのdivのid重複

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1724]
配送商品の要素に対して配送先のインデックスを利用しているためidが重複する場合がある。

https://github.com/EC-CUBE/ec-cube/blob/3.0.10/src/Eccube/Resource/template/admin/Order/edit.twig#L548 (その他、配送商品の要素でidにshippingIndexを指定している箇所全て)

**Comment by Yangsin** [comment]
@izayoi256 
#1725 #1758 の修正でこちらも修正されている気がするのですがいかがでしょうか。

**Comment by izayoi256** [comment]
@Yangsin 
直っていません。複数配送先機能を有効にすると、同配送先内の配送商品のidが重複します。
![screenshot from 2017-01-10 13-19-54](https://cloud.githubusercontent.com/assets/1329505/21793786/cade8fd4-d737-11e6-9d21-42b31b3378f3.png)

**Comment by Yangsin** [comment]
そういうことですね。。。確認ありがとうございます。

**Comment by t-nagahashi** [comment]
本件、#2053 で同時に対応されているようです。

**Comment by t-nagahashi** [comment]
動作確認はOKです。

■修正前（デモサイト 3.0.13）
「shipment_item__id--0」が複数ある状態。
![default](https://cloud.githubusercontent.com/assets/13776434/22724825/300b988a-ee0c-11e6-9ca9-fc998d11b407.png)

■修正後（#2053 適用後）
「shipment_item__id--0--0」
「shipment_item__id--0--1」
と、インクリメントされた状態となっています。

![2053](https://cloud.githubusercontent.com/assets/13776434/22724854/67950a52-ee0c-11e6-9f99-69033155a6ad.png)

**Comment by t-nagahashi** [comment]
#2053 のソースチェックもOK。

**Comment by ryo-endo** [comment]
私のほうでも重複消えていること確認しました。
OKそうですのでCLOSEします。
