### ISSUE TITLE
受注登録・編集：複数配送時、商品の削除/お届け先の削除ができない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1729]
複数配送有効時に、
- お届け先に登録した商品
- 追加したお届け先

を削除するUIがありません。

![product-remove](https://cloud.githubusercontent.com/assets/8196725/18239028/58da394c-737d-11e6-8016-05cf15f1f255.png)

![shipping-remove](https://cloud.githubusercontent.com/assets/8196725/18239030/5db847f6-737d-11e6-91a8-ba0f5ac51491.png)

**Comment by ryo-endo** [comment]
#2053 で修正をmasterにマージしましたのでCLOSEします。
