### ISSUE TITLE
Block/LoginControllerで使用していない変数がある

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1730]
Eccube\Controller\Block\LoginControllerで、formやemailなどの変数をtwigへ渡しているが、Block/login.twig側では、変数を利用していない

twigのみで完結するため、LoginController自体不要と思われる。
※dtb_blockのlogic_flgを0に設定

**Comment by ryo-endo** [comment]
- 処理は走っているので、不要な処理時間が発生している。
- 削除すると LoginController 内のフックポイントに影響を与えるため、影響範囲を考慮した判断が必要。

**Comment by okazy** [comment]
4.0で対応済み
