### ISSUE TITLE
受注情報の編集の挙動がおかしい

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#1731]
バグっぽいです

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17966&post_id=77712&order=0&viewmode=flat&pid=77677&forum=9

**Comment by nanasess** [comment]
以下と同じ事象ですかね。

https://github.com/EC-CUBE/ec-cube/issues/1095
https://github.com/EC-CUBE/ec-cube/issues/1094

**Comment by tao-s** [comment]
@nanasess あ、そうですね。
このチケットは取り下げますね

**Comment by tao-s** [comment]
ん？取り下げられん！！
@Yangsin 取り下げお願いします

**Comment by Yangsin** [comment]
チケットは削除できませんのでクローズしておきます。
