### ISSUE TITLE
お届け可能日を「お取り寄せ」にしても、お届け日の指定ができてしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1732]
商品管理画面で、お届け可能日を **お取り寄せ(商品入荷後)** としても、購入確認画面で、お届け日の指定ができてしまう。

**お取り寄せ(商品入荷後)** とした場合は、お届け日の指定ができないのが正しいと思われる。

**Comment by chihiro-adachi** [comment]
#1749 で対応
