### ISSUE TITLE
受注商品検索でタイムアウト

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1733]
# 現象
受注編集画面の商品検索で、該当商品件数が増えれば増えるほど検索時間が増加し、いずれタイムアウトする。商品規格取得のSQLが商品件数分実行されていることが原因。 (n+1問題とは別)

# 解決方法
件数の上限やページング処理で一度に取得する商品件数を減らす。

**Comment by chihiro-adachi** [comment]
#1790 で修正
