### ISSUE TITLE
４０４ページでのユーザー情報取得方法

### ISSUE THREAD

**Issue by hainey** [EC-CUBE/ec-cube#1734]
４０４ページでユーザー情報取得方法がありません

{% if is_granted('ROLE_USER') %}

error.twigに上記を追加するとtokenがnullになってしまいます、PHP Fatal errorとなりました。

PHP Fatal error:  Uncaught exception 'Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException' with message 'The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.' in /var/www/eccube307/vendor/symfony/security/Core/Authorization/AuthorizationChecker.php:57
Stack trace:
#0 /var/www/eccube307/vendor/symfony/twig-bridge/Extension/SecurityExtension.php(41): Symfony\Component\Security\Core\Authorization\AuthorizationChecker->isGranted('ROLE_USER', NULL)
#1 /var/www/eccube307/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(52): Symfony\Bridge\Twig\Extension\SecurityExtension->isGranted('ROLE_USER')
#2 /var/www/eccube307/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_1042f7d7fdc85a9fa954a3aecb8e2e69490441e4b1e93d56b3abe3af3bdae8a7->doDisplay(Array, Array)
#3 /var/www/eccube307/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#4 /var/www/eccube307/vendor/ in /var/www/eccube307/vendor/twig/twig/lib/Twig/Template.php on line 396

４０４などのエラーページでユーザー情報の処理は不可能でしょうか？

**Comment by xuelian311** [comment]
開発関連でご質問がありましたらぜひ開発コミュニティのご利用お願いします。
長い間議論も進んでないため、クローズいたします。
