### ISSUE TITLE
複数配送で、購入商品数と配送商品数が合わないときにエラーメッセージがわかりにくい

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1736]
キャプチャのエラーメッセージです。
複数配送で、購入商品数と配送商品数が合わないときにでるエラーメッセージですが、大変わかりにくい。
```
数量の数が異なっています
```

![image](https://cloud.githubusercontent.com/assets/16891862/18302497/4515f698-7513-11e6-9f72-8a4030b34063.png)

### 手順
1. 数配送で、購入確認画面へ。
2. [お届け先を追加]ボタンを押し、お届け先の複数指定ページへ。
3. 購入商品数とお届け先の商品数を不一致にして、登録する。 ⇒ キャプチャのエラー表示される

**Comment by chihiro-adachi** [comment]
- エラー文言：`数量の合計が、カゴの中の数量と異なっています`
- message化されていないため、合わせて修正を行う

**Comment by ryo-endo** [comment]
#1752 で対応済み。
