### ISSUE TITLE
税率設定：共通税率設定の適用日時が、時刻がずれて登録される

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1737]
適用日時が、時刻がずれて登録されます。

手順

- 税率設定画面を開く
- 共通税率設定の、適用日時を選択
- カレンダーから日付を選択
    - 20xx-xx-xx 00:00が入力項目に表示される
- 登録ボタンを押下
    - 20xx-xx-xx 15:00 で登録される

期待値

20xx-xx-xx 00:00 で登録される

備考

- windows7 chrome/firefoxで発生

**Comment by kiy0taka** [comment]
Symfonyのバグのようです。2.7.19以降で修正されています。
https://github.com/symfony/symfony/issues/19721

**Comment by chihiro-adachi** [comment]
#1811 でsymfony2.7.19に更新しています。
