### ISSUE TITLE
税率設定：商品登録・編集時の挙動

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1738]
個別税率設定を有効にし、商品登録・編集時に税率を登録すると、以下の事象が発生します。

商品登録時
- dtb_tax_rule.apply_date（適用日時）に、商品登録日時が登録される
- dtb_tax_rule.calc_rule（課税規則）に、常に1(=四捨五入) が登録される

商品編集時
- 編集時に税率が上書きされる（履歴が保持されない)

**Comment by ryo-endo** [comment]
@chihiro-adachi 
マイルストーンが3.1になっていますが、

> dtb_tax_rule.calc_rule（課税規則）に、常に1(=四捨五入) が登録される

だけでもマイナーバージョンで対応はできないでしょうか？
その時点でアクティブな共通税率設定の課税規則を設定するなど。

**Comment by okazy** [comment]
4.0では以下の仕様とします。

https://github.com/EC-CUBE/ec-cube/pull/3732
