### ISSUE TITLE
お届け先の複数指定画面で、住所の表示順番が不正

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1742]
複数配送のお届け先の複数指定画面で、住所の表示順番に違和感があります。

[姓][番地][都道府県][市区町村]
　　↑
　番地が前に来ている

![image](https://cloud.githubusercontent.com/assets/16891862/18308683/87351082-7530-11e6-8fc3-812a0d2a731c.png)

#### 期待値
[姓][都道府県][市区町村][番地]

**Comment by chihiro-adachi** [comment]
#1810
