### ISSUE TITLE
お届け先の複数指定画面で、数量の初期値が設定されたり、しなかったりする

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1743]
複数配送の、お届け先の複数指定画面で、数量の初期値が設定されたり、しなかったりします。

- 同じ商品種別の商品のみカートに入っている時には設定されない（0になっている）
- 異なる商品種別の商品がカートに入っているときには設定される

![image](https://cloud.githubusercontent.com/assets/16891862/18309028/4a0657c8-7532-11e6-9b40-4401906ab697.png)

**Comment by trebla-on** [comment]
対応中です

**Comment by chihiro-adachi** [comment]
#1842 で対応
