### ISSUE TITLE
【管理画面】【メンバー管理】ログインID重複で変更を失敗するとアカウントが切り替わってしまう

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1744]
店舗オーナー権限アカウントにて、自身のログインIDを変更しようとしてすでに登録済みのログインIDを入力、保存すると重複エラーとなりますが、その時、ログイン中アカウントが、重複したログインIDのアカウントに切り替わってしまいます。

そもそもメンバー管理にアクセスできる時点で、他者のアカウント操作が可能なのでこれによる問題は特にありませんが、動作として気になったのでご報告致します。

**Comment by chihiro-adachi** [comment]
#1825 で修正
