### ISSUE TITLE
規格設定後に商品登録ができない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1757]
フォーラムより
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&topic_id=17942&forum=11

**Comment by chihiro-adachi** [comment]
以下の手順で確認しましたが、事象が再現しませんでした（masterブランチおよび3.0.10で確認)

- 商品を登録
- 商品規格を登録(規格1のみ/規格1・2の2パターンで登録)
- 上記で登録した商品を更新

**Comment by Yangsin** [comment]
再現できないためクローズします。
再現されましたら ReOpenか再作成をお願いします。
