### ISSUE TITLE
masterをmergeした状態でinstall.php/migration から次へ進むと画面真っ白

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1759]
phpのエラーログには2行エラーが出てますがこれが直接の原因かはわかりません

PHP Warning:  array_replace_recursive(): Argument #3 is not an array
PHP Catchable fatal error:  Argument 2 passed to Eccube\Application::parseConfig() must be of the type array, null given, called in

**Comment by nobuhiko** [comment]
index_dev.php でアクセスも出来ないです
ContextErrorException in Application.php line 1036:
Warning: array_replace_recursive(): Argument #3 is not an array

**Comment by nobuhiko** [comment]
原因は、想定されない形式のconfig.phpが app/config/eccube/ に置いてあったからですね
当初あったやつが残ってると死ぬようです

**Comment by Yangsin** [comment]
いったん報告の事象に対してはクローズします。エラー制御については別途起票orPullRequestいただけると幸いです。
