### ISSUE TITLE
シェルインストール時、*_urlpathの値が誤って生成される

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1763]
#1750 

以下の設置状態で、インストールシェルを実行した場合に発生する
- DocmentRoot/ec-cube/html
- http://localhost/ec-cube/html

インストールシェル側にも、${ROOT_PUBLIC_URLPATH}の定義が必要。
https://github.com/EC-CUBE/ec-cube/pull/1750/files#diff-76413970dbcc66042305e07b50187835R50

**Comment by ryo-endo** [comment]
#1768で対応済み。
