### ISSUE TITLE
管理画面URLの変更後、index_dev.phpでアクセスすると例外がthrowされる

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1765]
手順
- 設定＞システム情報設定＞セキュリティ管理から、ディレクトリ名を変更する
- index_dev.phpで管理画面にアクセスする

以下の例外がthrowされる

`An exception has been thrown during the rendering of a template ("User Warning: Unable to generate a URL for the named route "admin2_change_password" as such route does not exist.") in "default_frame.twig" at line 74.`

備考
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/admin/default_frame.twig#L74

パスワード変更のルーティングは、`change_password` 固定のため、動的に変更させる必要は無いと思われる。

**Comment by ryo-endo** [comment]
#1767で対応済み
