### ISSUE TITLE
テストケースでバリデーションエラーを捕捉していない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1772]
Order\EditControllerTest で、バリデーションエラーが発生しているのにもかかわらず、テストが正常終了する。

「受注情報を保存しました。」と「有効な値ではありません。」が同時に表示されてる模様。
https://github.com/EC-CUBE/ec-cube/pull/1722#discussion_r78679663

**Comment by chihiro-adachi** [comment]
バリデーションエラーが発生するテストデータに差し替え、テストを実行してみましたが、「受注情報を保存しました。」の出力は確認できませんでした(ローカル環境のため、travisでは異なるかもしれません)

ただ、

https://github.com/EC-CUBE/ec-cube/blob/master/tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php#L301

や

https://github.com/EC-CUBE/ec-cube/blob/master/tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php#L321

の箇所で、POSTした結果を確認せずにassertしている箇所があるため、そこは確認するように修正します。

**Comment by nanasess** [comment]
#2230 で修正済み
