### ISSUE TITLE
iOS/Firefoxからアクセスした場合に、オーバレイがかかってしまって戻らない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1782]
開発コミュニティより転記
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17507&forum=8&post_id=76175#forumpost76175

＜環境＞
iOS 9.2.1（iPad）のSafariなど、iOSのSafari環境

サーバ側はdemo3.ec-cube.netで再現

＜事象＞
商品の詳細画面を表示して、「お気に入りに追加」を押すとログイン画面が出るが、そこからブラウザバックするとグレーのオーバレイがかかったままとなり、何もできなくなる

**Comment by ryo-endo** [comment]
Firefoxでも発生を確認。

**Comment by chihiro-adachi** [comment]
#1848 で対応
