### ISSUE TITLE
支払い方法が更新不可

### ISSUE THREAD

**Issue by thanhlvt** [EC-CUBE/ec-cube#1783]
「ショップ設定　支払方法管理」画面では、支払い方法の名称、手数料などが設定できると思いますが、
dtb_paymentのcharge_flgが2の場合、手数料が表示されなくなります。
この時、手数料の入力チェックが行われて、いつでも必須チェックエラーになっているため、
支払い方法の名称、利用条件などは更新できなくなっています。
ご確認をお願いできますでしょうか？

**Comment by ryo-endo** [comment]
> dtb_paymentのcharge_flgが2の場合、手数料が表示されなくなる

2系の挙動に合わせて、表示されない動作になっています。

> 支払い方法の名称、利用条件などは更新できなくなっています。

これは不具合です。

**Comment by chihiro-adachi** [comment]
#1787 で修正
