### ISSUE TITLE
複数配送有効時、複数商品のカート追加時に必ずエラーになるケースあり

### ISSUE THREAD

**Issue by maeda-at-land** [EC-CUBE/ec-cube#1786]
【前提条件】
・ショップマスタで、複数配送を有効にする。
・配送方法設定で、配送業者をＡ、Ｂの２つのみにする。
・配送方法設定で、配送業者Ａの支払方法に郵便振替、現金書留、銀行振込の３つを設定する。
・配送方法設定で、配送業者Ｂの支払方法に代金引換のみを設定する。
※２業者の支払方法が重複していなければ任意の支払方法の組み合わせで再現可能。
※３業者以上でも、後述の【ロジック】に合致するよう支払方法を設定すれば再現可能。

【事象】
カートに任意の複数商品を入れる場合、２商品目を入れようとすると必ず
「お支払方法が異なるためこの商品は同時に購入することはできません。」
のエラーとなる。例え同一商品の２回目でも同様。

【ロジック】
PaymentRepository.php L117～ findAllowedPayments() では、
・１業者目と２業者目で共通する支払方法を抽出   ・・・ (1)
・(1)と３業者目で共通する支払方法を抽出 ・・・ (2)
・(2)と４業者目で共通する支払方法を抽出
以下同様にして全業者に共通する支払方法を抽出していきますが、これが０件だと
呼び出し元のCartService.php canAddProductPayment() で【事象】のエラーとなります。

【対応案】
「複数配送有効時は全配送先を通して少なくとも１つの共通支払方法が必要」
という仕様があっての本件処理なのであれば、「２回目のカート追加時」ではなく
「ショップマスタ更新時」及び「配送方法更新時」に検出できないでしょうか？
（微小ながらフロント画面軽量化にもなるかと。）

**Comment by okazy** [comment]
対応済です。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
