### ISSUE TITLE
idセレクタのmain、contentsが重複している

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#1789]
src/Eccube/Resource/template/default/default_frame.twig
内で記述されている

```
<div id="contents" class="{{ PageLayout.theme }}">
    ・
    ・
    <div id="main">
        {# ▼メイン上部 #}
        ・
        ・
        <div id="main_middle">
            {% block main %}{% endblock %}
        </div>

        {# ▼メイン下部 #}
        ・
        ・
    </div>
</div>
```

の部分で `id="main"` 内の `{% block main %}{% endblock %}` に各コンテンツが表示されるが、
呼び出されるtwigの中に `id="main"` と `id="contents"` が記述されているものがありIDが重複している。
### 対象twig
- error.twig
- Contact/confirm.twig
- Contact/index.twig
- Forgot/complete.twig
- Forgot/complete.twig
- Forgot/index.twig
- Forgot/reset.twig
- Help/about.twig
- Help/agreement.twig
- Help/guide.twig
- Help/privacy.twig
- Help/tradelaw.twig

関連 #1631

**Comment by Yangsin** [comment]
3.nではスタイルガイドの対応で解決していますのでクローズします。
