### ISSUE TITLE
eccube_install.sh の調整

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#179]
* 環境毎に調整が必要な値のデフォルト値の修正汎用的なものにする
- test.local 等ではなく [eccube-vagrant](https://github.com/EC-CUBE/eccube-vagrant) に合わせるか、localhost のように汎用的なホスト名とする、もしくは必須入力とする。DB_NAME等も同様

* エラーがでている  
   - chmod: cannot access `./src/Eccube/page': そのようなファイルやディレクトリはありません
    - ERROR:  リレーション"dtb_bloc_bloc_id_seq"は存在しません
行 1: SELECT SETVAL ('dtb_bloc_bloc_id_seq', 10000);
    - ERROR:  リレーション"dtb_pagelayout_page_id_seq"は存在しません
行 1: SELECT SETVAL ('dtb_pagelayout_page_id_seq', 10000);
他。

* 一番上の使い方のコメントが間違っている。

**Comment by chihiro-adachi** [comment]
#942 で再度PRおこなったため、本PRはクローズします

**Comment by chihiro-adachi** [comment]
#942 にて、コメントの修正も合わせて行いました。指摘事項は既に修正すみかと思いますので本Issueはクローズします。
