### ISSUE TITLE
受注編集画面の商品検索で商品コード検索ができない

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1791]
https://github.com/EC-CUBE/ec-cube/blob/3.0.11-RC/src/Eccube/Resource/template/admin/Order/edit.twig#L790

実際には商品コードによる検索はできないため、商品コードによる検索を実装するか、コード表記を削除するか。

検索ロジックはフロント側と同じ。 see also #1566

**Comment by Yangsin** [comment]
店舗主の運用時の期待としては、商品コード検索もできたほうが良いので、実装漏れと判断します。
