### ISSUE TITLE
検索で大文字小文字の区別を無くす

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#1792]
フォーラムより
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=18048&forum=12&post_id=78012#forumpost78012

postgresなら ilike mysqlなら collate utf8_unicode_ci like  など doctrineでうまく吸収出来ないですかね

**Comment by shinichi-takahashi** [comment]
これでどうでしょ？
http://stackoverflow.com/questions/4127990/doctrine-like-case-insensitive

**Comment by nobuhiko** [comment]
これだと日本語のひらがな・カタカナ問題が残る気がします

**Comment by izayoi256** [comment]
#1797 にて作ってみましたが、sqliteでひらがな・カタカナ検索を実現する方法がありません。 (そもそもsqliteはシステム要件に含まれていませんが)

**Comment by Yangsin** [comment]
sqlite は対象外としてこちらでクローズします。
