### ISSUE TITLE
Postgresqlでペイメント方法を登録するとき、Validationエラー

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#1799]
環境
   1.IIS
   2.Postgresql
バグ再現
　1．Access ショップ設定 ＞　支払方法管理
　2．支払方法新規登録ボタンクリック
    3.   利用条件に1 ~ 9999999999999 を入力
結果
　System Error => NG
要望結果
　Validation エラーメッセージを表示します。
Note
   Mysqlは大丈夫です。

**Comment by ryo-endo** [comment]
#1784 と重複。
