### ISSUE TITLE
お届け先変更画面で不正なIDを渡した場合のエラー処理が不適切

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#1801]
環境
　　1. PHP
　　2. Postgresql

再現
　　1．注文確認画面にお届け先の「変更」ボタンをクリックする。
　　2．お届け先の指定画面にF12をクリックして、RadioボタンのValueを0に変更する。
　　3．Submitをクリックする。
　　4．-　https://github.com/eccubevn/ec-cube/blob/master/src/Eccube/Controller/ShoppingController.php#L528
     - https://github.com/eccubevn/ec-cube/blob/master/src/Eccube/Controller/ShoppingController.php#L541

結果
　　1．exception of type "Doctrine\DBAL\Exception\DriverException".
    　https://travis-ci.org/eccubevn/ec-cube/jobs/158127659#L301

要望結果
　　　DBの例外じゃなくて、"Symfony\Component\HttpKernel\Exception\NotFoundHttpException".
   Or return error: https://github.com/eccubevn/ec-cube/blob/master/src/Eccube/Controller/ShoppingController.php#L530

**Comment by Yangsin** [comment]
#1303 が原因。

**Comment by trebla-on** [comment]
対応ずみみたい（404エラー表示します）

**Comment by lammn** [comment]
注文確認画面にお届け先の「変更」ボタンをクリックしてお届け先の指定画面に移動します。

![1](https://cloud.githubusercontent.com/assets/17536702/22723069/fb2bc46e-eded-11e6-8ffb-40862c68daa6.PNG)

F12でラジオボタンの価値を０に設定してSubmitをクリックする。

![22](https://cloud.githubusercontent.com/assets/17536702/22723090/205b8db4-edee-11e6-9f6f-84d9f1f5dba5.PNG)

４０４エラーを表示します。

![4444](https://cloud.githubusercontent.com/assets/17536702/22723098/33f3e7d6-edee-11e6-97d2-de0b45a5cf01.PNG)

index_dev.phpの場合はNotFoundExceptionを発生する。

**Comment by t-nagahashi** [comment]
以下、理由により対応の必要がないと判断したためCloseします。

・一般ユーザ使用時は、「ページが見つかりません」のEC-CUBE標準エラー画面のため正常な状態である。
・エラー発生時、@lammn さん指定時、「"Doctrine\DBAL\Exception\DriverException".」であったが、index_dev.phpで確認した結果、期待されている「Not Found Http Exception」であったので、正常なエラーハンドリングがされている状態である。

**Comment by ryo-endo** [comment]
@t-nagahashi 了解です。
問題ない状態になっているようですので、CLOSEします。
