### ISSUE TITLE
Myページ-購入履歴で購入処理中のステータスの受注を表示できてしまう

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#1802]
環境
-    PHP
-   Mysql

再現
-  受注Aは購入処理中のステータス
-   My page -> history order list -> 受注Aを表示しない
-  直接URLをアクセスすると、受注Aを表示してしまいました。

原因:
-  購入処理中のステータスをブロックしていない
- src/Eccube/Controller/Mypage/MypageController.php:171

結果
- 購入処理中のステータスの受注をアクセスしてしまいました。

要望結果
-  Not found page.
-   Show on the history page.

**Comment by Yangsin** [comment]
関連 #1715

**Comment by trebla-on** [comment]
対応中です

**Comment by trebla-on** [comment]
対応済みです
