### ISSUE TITLE
admin などの後ろの "/" について

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#181]
一般的なRESTful URLでは `/` をつけない方が多いと思いますが、SymfonyのSecurity を使った際に `/admin` のみだと `/adminxxx` など前方一致となるため、 2系の `index.php` の省略の場合には後ろの `/` までをURLとした方が良いかと思います。

**Comment by nobuhiko** [comment]
後ろの / がある場合とない場合で挙動が変わっちゃうのは致し方ない感じでしょうか？

**Comment by ttsuru** [comment]
@nobuhiko 
挙動が変わってしまうというのはどういうことでしょうか。
実は routing で `/admin/` になっているので、 `/admin` にアクセスすると `/admin/` にリダイレクトされていると思います。

**Comment by nobuhiko** [comment]
/help/tradelaw ではアクセスできますが /help/tradelaw/ だとエラーになります

**Comment by ttsuru** [comment]
@nobuhiko 
前者の方は正しい挙動だと思います。
.php の拡張子が省略された(と思われる)ので、`/help/tradelaw` がroutingに定義されています。
下の方は 本来は `/admin/` でアクセスできる方が正しいと思われます。

**Comment by ttsuru** [comment]
一度closeします。
admin で一致してもいいかもしれません・・・

**Comment by ttsuru** [comment]
ただし、管理画面のトップページは後ろにスラッシュがつく、admin/ が正しいURLですね。

**Comment by Yangsin** [comment]
mypage/ admin/  に関しては領域として、/終わりで検討してます。
