### ISSUE TITLE
プラグインの Yamlパースのキャッシュ生成

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1812]
プラグインの `config.yml` をリクエストごとに探索、パースしており、プラグインをインストール数が増加するごとにパフォーマンスが劣化してしまう

PluginServiceTest を実行し、 `config.yml` のみのダミープラグインを生成。処理にかかる時間を計測した。
(Windows7, SSD256GB, Corei5, メモリ8G)

以下のような修正をしています。
https://gist.github.com/nanasess/ece7de62298dea3a9924cd13da8519eb

### プラグイン無し

```
./vendor/bin/phpunit tests/Eccube/Tests/Service/PluginServiceTest.php
PHPUnit 4.6.10 by Sebastian Bergmann and contributors.

Configuration read from C:\Users\user\git-repos\ec-cube\phpunit.xml.dist

.initLocale: 0.11902379989624
initSession: 0.0045011043548584
initRendering: 0.0070009231567383
initProvider: 0.035006999969482
initMailer: 0.0040009021759033
initDoctrine: 0.46609306335449
initSecurity: 0.32506513595581
initServiceProvider: 0.057511806488037

...snip
Time: 7.72 seconds, Memory: 12.00MB
```

### プラグイン30個インストール時

```
./vendor/bin/phpunit tests/Eccube/Tests/Service/PluginServiceTest.php
PHPUnit 4.6.10 by Sebastian Bergmann and contributors.

Configuration read from C:\Users\user\git-repos\ec-cube\phpunit.xml.dist

.initLocale: 0.12052416801453
initSession: 0.0050008296966553
initRendering: 0.0085010528564453
initProvider: 0.03850793838501
initMailer: 0.0050010681152344
initDoctrine: 0.74164891242981
initSecurity: 0.32206416130066
initServiceProvider: 0.056010961532593
initialize: 1.3077611923218
finder: 0.0045008659362793
handler: 0.50360107421875
load: 0.45759201049805

...snip
Time: 10.37 seconds, Memory: 12.00MB
```

### 解決案

プラグインのパス、 `config.yml` 及び `event.yml` を PHP ファイルでキャッシュすることで解消できると思われる。
キャッシュの更新は、プラグインの install/enable/disable/uninstall のタイミングで行う

**Comment by nanasess** [comment]
PHP でキャッシュするよう試験実装してみたところ `Yaml::parse()` をコールしていた `Application::initDoctrine()` で 3.6倍程度の性能向上が見られました
(プラグイン30個インストール時, Windows7, SSD256GB, Corei5, メモリ8G)


|  | キャッシュ無し |  キャッシュ有り |      |
|----------------|----------------|-------------|------|
| 1回目          | 0.282557011    | 0.072000027 | 3.92倍 |
| 2回目          | 0.263552904    | 0.098999977 | 2.66倍 |
| 3回目          | 0.352070808    | 0.076499939 | 4.60倍 |
| 平均           | 0.299393574    | 0.082499981 | 3.63倍 |

**Comment by Yangsin** [comment]
関連とみられる不具合が一部発生しており確認中です。
#1888 #1890
