### ISSUE TITLE
YamlDriver の置換に失敗する場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1819]
因果関係は不明だが、大量のデータ(商品及び受注件数60万件程度)が投入された環境で、時折 YamlDriver の置換に失敗し、 `MappingException` がスローされる場合がある

```
MappingException in MappingException.php line 75: No mapping file found named 'Eccube.Entity.Member.dcm.yml' for class 'Eccube\Entity\Member'.
```

スタックトレースを見てみると、  `\Doctrine\ORM\Mapping\Driver\YamlDriver` を参照している

参考 https://github.com/EC-CUBE/ec-cube/pull/1691

**Comment by nanasess** [comment]
頻発するような状況であれば、以下のようにテスト時のみパッチを当てる等の対応が良いと思います。
https://github.com/EC-CUBE/ec-cube/pull/1664

**Comment by Yangsin** [comment]
現状頻発する状態ではなく、根本的な修正方法もないため、一度見送ります。

**Comment by yuitsubasapapa** [comment]
再インストール時に、元のDBを残したまま”sh eccube_install.sh mysql”を実行すると、Yaml Driverが無いと怒られます。
PHP Fatal error:  Uncaught Error: Class 'Doctrine\ORM\Mapping\Driver\YamlDriver' not found in /opt/ec-cube/vendor/dflydev/doctrine-orm-service-provider/src/Dflydev/Pimple/Provider/DoctrineOrm/DoctrineOrmServiceProvider.php:170
Stack trace:
#0 /opt/ec-cube/vendor/pimple/pimple/lib/Pimple.php(126): Dflydev\Pimple\Provider\DoctrineOrm\DoctrineOrmServiceProvider->Dflydev\Pimple\Provider\DoctrineOrm\{closure}(Object(Eccube\Application))
#1 /opt/ec-cube/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Eccube\Application))
#2 /opt/ec-cube/vendor/dflydev/doctrine-orm-service-provider/src/Dflydev/Pimple/Provider/DoctrineOrm/DoctrineOrmServiceProvider.php(419): Pimple->offsetGet('orm.ems.config')
#3 /opt/ec-cube/vendor/pimple/pimple/lib/Pimple.php(126): Dflydev\Pimple\Provider\DoctrineOrm\DoctrineOrmServiceProvider->Dflydev\Pimple\Provider\DoctrineOrm\{closure}(Object(Eccube\Application))
#4 /opt/ec-cube/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Eccube\Application))
#5 /opt/ec-cube/vendor/dflydev in /opt/ec-cube/vendor/dflydev/doctrine-orm-service-provider/src/Dflydev/Pimple/Provider/DoctrineOrm/DoctrineOrmServiceProvider.php on line 170
migration...
