### ISSUE TITLE
`app/cache` 以下の `.gitkeep` について

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#182]
app/cache/ 以下はそれぞれのロジックで自動的にディレクトリが作られるので、トラブルやインストールの簡素化のためにも、`cache` のみをパーミッション777で置いておくようにしてはどうでしょうか。

**Comment by Yangsin** [comment]
手元で確認してみました。
2系のソースで動いているようなページでディレクトリが存在しないというエラーになってしまいます。
mtb_constants.phpと、smartyのキャッシュ生成のなかでディレクトリまではつくっていないので、
app/cache/eccube/　app/cache/smarty/ はディレクトリを用意しておく必要がありますね。

インストーラーでやるか、のこすかになりますが、どちらにしろ2系のソースがなくなれば消すことになるので、
app/cache/profiler/ は消しても、他は現状のままでもよいかと。

**Comment by Yangsin** [comment]
すでに、app/cache 自体もフォルダがリポジトリ上は削除されているのでこちらのIssueはクローズします。
