### ISSUE TITLE
受注編集画面内 会員/商品検索画面の検索結果項目が不足している

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1820]
### 会員検索画面

**会員ID・メールアドレス・お名前** で検索できるが、検索結果で表示される項目は **会員ID・お名前・電話番号** となっている。
メールアドレスで検索した場合は、どの会員が該当するのか解らない。

### 商品検索画面

**商品名・ID・コード** で検索できるが、検索結果で表示される項目は **商品名・商品コード・商品規格** となっている。
商品ID で検索した場合は、どの商品が該当するのか解らない。

**Comment by chihiro-adachi** [comment]
#1836 で修正
