### ISSUE TITLE
twig内でプラグイン拡張項目を表示するための正規表現の改善

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1822]
`{% if f.vars.name matches '[^plg*]' %}`

この正規表現ですと、plから始まるものに該当してしまいます。

`{% if f.vars.name matches '[^plg_.+]' %}`

のような感じが良いのではないでしょうか。

**Comment by Yangsin** [comment]
3.Nではプラグインからの介入方針んを見直し、Twig内の記述を削除します。

**Comment by Yangsin** [comment]
テンプレートへの介入方法の見直し #2440 にのっとりこちらは対応しないものとしてクローズします。
