### ISSUE TITLE
composerの最適化

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1823]
`composer dump-autoload -o`で生成されるclassmapファイルが結構大きい(3000行くらい)

exclude-from-classmap
https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps

autoload-dev
https://getcomposer.org/doc/04-schema.md#autoload-dev

とかで削減できないかどうか試してみる

**Comment by Yangsin** [comment]
#1828 で対応
