### ISSUE TITLE
Translatorのキャッシュディレクトリを指定する

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1824]
`$app['translator.cache_dir']`でパスを設定しておくことで、キャッシュの設定ができそう。

https://github.com/silexphp/Silex-Providers/blob/master/TranslationServiceProvider.php#L38
http://symfony.com/blog/new-in-symfony-2-6-improvements-for-the-translation-component

**Comment by Yangsin** [comment]
関連する不具合調査中

#1882 #1885
