### ISSUE TITLE
管理画面>受注管理>受注登録 商品削除後に商品追加ができない

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1826]
3.0.11にて確認しました。

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=18096&forum=9
こちらに投稿されております。

商品削除後に計算結果の更新をせず商品の追加を行うと、追加することができません。
また、計算結果の更新をしてから商品の追加を行った場合、商品名が別のものとなります。

**Comment by izayoi256** [comment]
恐らく #1758 で解決します。
