### ISSUE TITLE
購入時やお問い合わせがあった際の自動メール送信機能について

### ISSUE THREAD

**Issue by asamiile** [EC-CUBE/ec-cube#1829]
購入時やお問い合わせがあった際の自動メール送信機能についてですが、自動で送信されるメールはユーザのみでしょうか？

ショップマスターに登録しているメールアドレス宛にメールが送信されてこないので気になり質問させて頂きました。mail.yml の設定は デフォルトの mail のままで設定しています。

**Comment by Yangsin** [comment]
管理者側にも送信されております。
環境や設定の問題とお見受けしますので、こちらはクローズさせていただきます。

利用方法に関するご質問は、開発コミュニティ(http://xoops.ec-cube.net)をご利用ください。
