### ISSUE TITLE
カテゴリツリー構造の見直し

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1854]
## 概要(Overview)

隣接リストモデルの構造ではカテゴリが巨大になってくると性能が劣化しやすいため入れ子集合モデル(MPTT / Nested Set Model)を適用し巨大なカテゴリーツリーを扱いやすくする

+ メリット
	+ SELECTの回数がへり検索がしやすくなる
+ デメリット
	+ マイグレーションへの課題
	+ Updateは遅くなるかも

## やる事
- [x] データ構造変更
- [x] 技術調査：インターフェースを検討
	- [x] クエリを理解する
	- [x] Doctrineで使えるのないか探す
	- [x] 他のフレームワークを参考に探す
- [ ] インターフェースの実装を行う
	- [x] リポジトリのインターフェース
	- [x] カテゴリリポジトリの実装
	- [ ] プロダクトリポジトリの実装
	- [ ] テストコードの実装

- [ ] 各画面・Controllerに実装
	- 管理画面
		- [ ] カテゴリ管理・登録編集
		- [ ] カテゴリCSVアップロード
		- [ ] 商品登録
		- [ ] 商品マスタ・商品検索
		- [ ] 受注の商品検索
	- フロント
		- [ ] カテゴリブロック
		- [ ] 商品検索・一覧
		- [ ] 商品詳細

## 関連情報 (Ref)

**MPTT(Modified Preorder Tree Traversal)** ロジックを使用すると良いのではないか。
https://www.sitepoint.com/hierarchical-data-database-2/
http://book.cakephp.org/2.0/ja/core-libraries/behaviors/tree.html
http://www.geocities.jp/mickindex/database/db_tree_ns.html

データ移行のヒント
[隣接リストモデルから入れ子集合モデルへ変換する](http://www.geocities.jp/mickindex/database/db_tree_ns.html#LocalLink-adj_to_set)

再帰クエリが使えるなら、従来の parent-child model の方がいいらしい
https://explainextended.com/2009/09/24/adjacency-list-vs-nested-sets-postgresql/
http://stackoverflow.com/questions/31641504/adjacency-list-model-vs-nested-set-model-for-mysql-hierarchical-data/31642680#31642680

その他の解決案
http://blog.amedama.jp/entry/2016/05/05/215954
http://blog.amedama.jp/entry/2016/05/06/035437
http://blog.amedama.jp/entry/2016/05/18/234343
http://lab.kochlein.com/FertileForest

~~DoctrineMPTT というものがあるが、そのままでは動かないっぽい~~
~~https://github.com/Kappa-org/DoctrineMPTT~~

Atlantic18/DoctrineExtensions を検証中
- https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md
- http://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html

- 一通りの仕様は満たしてる模様
    - https://gist.github.com/nanasess/c3a35e64bbabb6bb6fdf45ea3b6537c4
    - ORM を駆使しているため、パフォーマンスは悪そう
    - 論理削除には対応できない可能性
- [Laravel 向けの実装である etrepat/baum](https://github.com/etrepat/baum) は、更新時はネイティブ SQL を使用している

**Comment by nanasess** [comment]
[Atlantic18/DoctrineExtensions](https://github.com/Atlantic18/DoctrineExtensions/) の Tree を手元の環境に組み込んでみました。
https://github.com/nanasess/ec-cube/tree/experiments/mptt

`$Categories = $app['eccube.repository.category']->childrenHierarchy(null, false);` で、ツリー構造の連想配列(オブジェクトではない)が取得できるのを確認しました。

**Comment by nanasess** [comment]
- 本質的には、再帰クエリを使用した parent-child mode の方がよい
- MySQL8 からは再帰クエリが使用できる

上記の観点から、 MPTT よりも、再帰クエリを使用するのが良いと思われます。

**Comment by okazy** [comment]
こちら実装は見送ります。
何かアイデアがあればコメントください。
