### ISSUE TITLE
EC-CUBE3　β版admin画面について

### ISSUE THREAD

**Issue by mfujii1** [EC-CUBE/ec-cube#186]
EC-CUBE3β版のインストールを行いましたが404エラーとなりadminが表示されません。
http://[URL]/html/adminと入力しています。
商品購入のトップ画面は表示されます。
html/adminを認識していないようですが、インストールを失敗しているのでしょうか？
html/adminの中はload_module_config.php　load_plugin_config.php　require.php　cssとなっています。
パスか環境設定の問題だと思うのですが、対処方法があればご教示下さい。
よろしくお願いします。
なお、環境は下記の通りです。
centOS7
apache 2.4.6
PHP 5.4.16
MariaDB

**Comment by shinichi-takahashi** [comment]
@mfujii1 
httpd.confのAllowOverrideがNoneになっていることが考えられます。
mod_rewirteは有効になっていますでしょうか？

.htaccessが正しく設定されている場合、
adminにアクセスしたとき、.htaccessによってhtml/index.phpが読み込まれるようになっており、
エラーはRoutingNotFoundのようなものが表示されるはずです。

**Comment by mfujii1** [comment]
ご回答ありがとうございます。
httpdの設定は行いました。
mod_rewirteはhttpdのログを確認して無効になっていたので有効しました。
その後TOPページは表示されるようになりました。
http://XXXXXX/html/adminにアクセスしたところ、
エラーは404でThe requested URL /XXXXXX//html/index.php was not found on this server.
と表示されています。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
トップページが表示されているのに `/html/index.php` がないというのは不自然ですね。。
#181 と関係があるかもしれません。

`eccube_install.sh` を叩く際にパスやURLの設定を正しく行っていたか再度ご確認いただけますか？

**Comment by mfujii1** [comment]
ADMIN_DIR=${ADMIN_DIR:-"admin/"}の設定をいろいろ変えてみましたが、だめでした。

ROOT_URLPATHのところはどのような設定にすればよいのでしょうか？
ec-cubeをインストールしているディレクトリは/home/*/public_html/ec3betaに入れています。（*はユーザー名です）
HTTP_URL=${HTTP_URL:-"http://[ドメイン名]/~*/ec3beta/html/"}
HTTPS_URL=${HTTPS_URL:"http://[ドメイン名]/~*/ec3beta/html/"}
ROOT_URLPATH=${ROOT_URLPATH:-"/~*/ec3beta/html/
としています。（*はユーザー名です）
この設定でトップページが表示されるようになりました。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
`/home/{ユーザ名}/public_html/ec3beta` とのことですが、DocumentRootは /home/{ユーザ名}/public_html/` でよろしいでしょうか？
その場合、ROOT_URLPATHには `/ec3beta/` と記載するのが正しいかと思います。


また、 `eccube_install.sh` を編集したあとは、同shを叩き直すか、`/app/config/` 以下の `config.php` `config.yml` を編集する必要があります。

**Comment by mfujii1** [comment]
DocumentRootは /home/{ユーザ名}/public_html/となっています。
ROOT_URLPATHを/ec3beta/に直してshを叩き直しましたが、同様のエラーになります。
また、トップページが左に寄った表示になってしまいます。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
`/app/log/site.log` にはどのようなエラーが出力されてますか？
もしくは、デバッグモードで開くとどのようになりますか？
デバッグモードへの切り替え方はREADME.mdを参照ください。

**Comment by nobuhiko** [comment]
HTTP_URL=${HTTP_URL:-"http://[ドメイン名]/ec3beta/html/"}
HTTPS_URL=${HTTPS_URL:"http://[ドメイン名]/ec3beta/html/"}
ROOT_URLPATH=${ROOT_URLPATH:-"/ec3beta/html/"}
では

**Comment by mfujii1** [comment]
デバッグモードに切り替えて開いても下記のエラーのみです。
Not Found

The requested URL /home/*/public_html/ec3beta/html/index.php was not found on this server.

/app/log/site.logにはエラーが出ていません。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
@nobuhiko の通りにやってもダメですか？？

**Comment by mfujii1** [comment]
@nobuhiko の通りにやってみてもだめでした。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
以下のファイルは存在しますか？
`/home/*/public_html/ec3beta/html/index.php`

**Comment by mfujii1** [comment]
存在しています。デバッグモードもこちらのファイルの修正でよろしいかったですよね？

**Comment by shinichi-takahashi** [comment]
@mfujii1 
そうですね。 `Eccube/Application.php` をよんでいるファイルです。
Routing定義がないよ、というエラーならわかるのですが、そのファイルがないとなると、サーバ設定などの方があやしいかもしれませんね。。

**Comment by mfujii1** [comment]
ありがとうございます。
サーバーの設定を調査してみます。

**Comment by mfujii1** [comment]
/etc/httpd/conf.d/userdir.confの設定でAliasMatch ^/ユーザー名(.*) /home/ユーザー名/public_html/$1を追加しました。
httpdを再起動し、ec_cube_install.shの設定を下記のように変更しました。
HTTP_URL=${HTTP_URL:-"http://[サイト名]/ユーザー名/ec3beta/html/"}
HTTPS_URL=${HTTPS_URL:-"http://[サイト名]/ユーザー名/ec3beta/html/"}
ROOT_URLPATH=${ROOT_URLPATH:-"/ユーザー名/ec3beta/html/"}

shを叩き直したら、トップ画面は正常に表示されて、http://[サイト名]/ユーザー名/ec3beta/html/admin/では/home/ユーザー名/public_html/ec3beta/html/admin/の中つまりload_module_config.php　load_plugin_config.php　require.php　cssがブラウザ上で表示されるようになりました。
エラーログ及びログは出力がありませんでした。
他に修正や設定の見直しなどありますでしょうか？

**Comment by shinichi-takahashi** [comment]
@mfujii1 
#181 こちらに関連して `/ec3beta/html/admin` (最後の／なし)でアクセスするとどうでしょう。
また、ブラウザ上で表示されるのはDirectoryIndexの問題ではないでしょうか？

**Comment by mfujii1** [comment]
管理画面は表示されないですね。
#191もやってみたのですが、だめでした。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
長らく返答できておらずすみません。
こちら現状いかがでしょうか？

**Comment by mfujii1** [comment]
@shinichi-takahashi

上手く行きませんので、RC版を待っています。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
大変失礼いたしました。

`index_dev.php` というデバッグ用のindexを用意しておりますので、
再インストールをしたのちに `eccube-3.0.0-dev` ブランチへ切り替え、
 `http://XXXXXX/index_dev.php/admin` にアクセスしてみていただけますか。

**Comment by mfujii1** [comment]
＠shinichi-takahashi

ありがとうございます。
現在、時間が取れないので、暇を見つけて試してみます。

**Comment by shinichi-takahashi** [comment]
@mfujii1 
よろしくお願いいたします。
時間が取れないとのことでしたら、今月末リリース予定のプロダクト版をお試しいただければと思います。
