### ISSUE TITLE
カテゴリの並べ替えで子孫カテゴリ（のrank）を置き去りにしている

### ISSUE THREAD

**Issue by maeda-at-land** [EC-CUBE/ec-cube#1867]
【再現手順】
※インストール直後のカテゴリ順（インテリア、キッチンツール、新入荷）の場合。
「商品管理＞カテゴリ登録」画面で「インテリア」を「キッチンツール」の下に移動する。

【不具合事象】
「フロント画面の検索用カテゴリドロップダウンリスト」および
「商品マスタ登録／編集画面の商品カテゴリ欄」において、
本来、キッチンツールの下に表示されるべき「調理器具」「食器＞フォーク」が
インテリアの下に表示されてしまう。

一般化すると・・・
カテゴリＡ
└カテゴリＡＡ
カテゴリＢ
という構成で、ＡをＢの下（或いはＢをＡの上）に移動すると、rank順で表示される欄では
カテゴリＢ
└カテゴリＡＡ
カテゴリＡ
と表示されてしまいます。

【ロジック】 ※表示側が、階層に関係なくrank順で表示する動作自体は正しいことが前提。
admin/Product/category.twigのupdateRank() JavaScript関数では現階層のみのrank群を
サーバ側のCategoryController::moveRank()に渡しています。（moveRankは素直にUPDATEするだけ。）
本来、子孫カテゴリも考慮すると現階層以下全てのカテゴリのrankを更新すべきと考えます。
（もちろん計算の結果、rank変更のないカテゴリもありますが。）

【対応案】
クライアント側には荷が重いと思われるので、「どのカテゴリをどこに移動するか」程度の情報を
moveRankに渡して、あとはサーバ側で計算＆更新するのは如何でしょうか？
他に付け焼刃的な方法ですが、
いったん現行のmoveRank処理でDBに書いた後、
トップからCategoryRepository::getList()を再帰呼び出しして、
出現するカテゴリ順にrankを振り直してUPDATEすれば正常になります。
（→嬉しい副作用として過去のrank不整合も修正できます。）
但し降順に振るので、カテゴリ数を前もってcountする必要はあります。

余談ですが、カテゴリ画面で並べ替え後に画面右のツリー表示も書き換えられると
よりスッキリするのですが・・・。

**Comment by Yangsin** [comment]
関連 #1854

**Comment by chihiro-adachi** [comment]
#1893 #1813  #2832 で修正

**Comment by ryo-endo** [comment]
こちらmasterに取り込み完了したためCLOSEします。
