### ISSUE TITLE
注文確認画面で入力値エラーを発生させた後、支払方法の選択値がデフォルト値で送信される

### ISSUE THREAD

**Issue by ensomai** [EC-CUBE/ec-cube#1868]
下記不具合が発生しているためご報告します。

・確認画面で支払方法を変更
・文字数超過などで入力値エラーが発生
↓
この時、画面上は支払方法変更後の状態になっていますが、
注文確定ボタンをクリックすると、
デフォルト値で送信・登録される不具合が発生しています。

下記を修正すれば問題ないようです。

src/Eccube/Controller/ShoppingController.php

```
         $form->handleRequest($request);

-        if ($form->isSubmitted() && $form->isValid()) {
+        if ($form->isSubmitted()) {
             $data = $form->getData();
             $payment = $data['payment'];
             $message = $data['message'];
```

**Comment by Yangsin** [comment]
バリデーションをスルーしてしまうような気がしますので、修正方法については一度確認してみます。

**Comment by nanasess** [comment]
#2175 にて修正済み
