### ISSUE TITLE
【基本情報管理＞会員規約設定】データ構成変更

### ISSUE THREAD

**Issue by tamagoya** [EC-CUBE/ec-cube#187]
現在、会員規約設定は、dtb_kiyaku内に規約単位のリストで保存されています。

会員規約設定の管理をシンプルにするため、dtb_kiyakuを廃止し、dtb_baseinfoにagreement(text)を追加して、そちらに保存するようにしたいです。

この方針で問題ないでしょうか。
よろしくお願いいたします。

**Comment by Yangsin** [comment]
ガラケーの対応が標準ではなくなるため、規約をシンプルに1カラムでもつ方針で考えています。

ただ、Baseinfoがかなりなんでもテーブルになってしまっているので、整理が必要かと。  
ルーティングでは、特商法などが、SITE_URL/help/hoge  としてまとめられているので  
dtb_help を用意してそちらに放り込み、baseinfo は様々なページで参照される可能性がある内容とショップの基本情報だけに留めたいです。  

dtb_help を作って customer_agreement でいかがでしょうか？

**Comment by tamagoya** [comment]
なるほど、ではdtb_helpを用意したいと思います。
