### ISSUE TITLE
デフォルトの配送先を会員登録の住所にする

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#1877]
2系では配送先選択画面に会員情報(dtb_customer)とお届け先(dtb_other_deliv)が表示されていたのが、3系ではお届け先(dtb_customer_address)のみ表示される。

会員情報を変更することでお届け先も変更できたものと誤解するケースもあるかと思われるため、当該機能を復活してはどうでしょうか。

**Comment by Yangsin** [comment]
#1202 と重複のためクローズ
