### ISSUE TITLE
[ゲスト購入]お客様情報のお名前(フリガナ)が変更できない

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#1878]
1. ログインしていない状態でカートに商品を入れてカート->レジへ進む
2. ゲスト購入を選択
3. お客様情報を入力して次へ
4. ご注文内容のご確認画面でお客様情報の変更ボタンをクリック
5. お名前(フリガナ)を変更する箇所がない

**Comment by Yangsin** [comment]
#1267 と重複
