### ISSUE TITLE
macOSのChrome/SafariでCSVダウンロードするとネットワークエラーになる

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#1880]
以下のクライアント環境を使ってデモサイト(EC-CUBE 3.0.11)で現象を確認
- macOS Sierra 10.12.1
- Chrome 54.0.2840.71
- Safari 10.0.1

(Firefoxでは問題なくダウンロードできます。)

対象
- 商品管理-商品マスター-CSVダウンロード
- 商品管理-カテゴリ登録-CSVダウンロード
- 受注管理-受注マスター-受注CSVダウンロード
- 受注管理-受注マスター-配送CSVダウンロード

**Comment by t-nagahashi** [comment]
私の環境でもは問題なくダウンロードできました。
macOS:10.12.3（16D32）
safari:バージョン10.0.3 (12602.4.8)
chrome:バージョン 56.0.2924.87 (64-bit)
firefox:49.0.1

**Comment by t-nagahashi** [comment]
こちら、長らく再発されていないようですので、Closeさせていただきます。
現行バージョンでも再度発生するようであれば、
再度、issue登録をお願い致します。
