### ISSUE TITLE
プラグインのmessage.ja.ymlに定義しているメッセージが表示されない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1882]
3.0.12のEC-CUBEにプラグインをインストールすると、
プラグインのmessage.ja.ymlに定義しているメッセージが表示されません。

![image](https://cloud.githubusercontent.com/assets/16891862/19711089/2e9ee92a-9b6e-11e6-87f7-69bf5adba4c4.png)

### 原因
3.0.12から`app/chache/translator`にメッセージのキャッシュを行うようになたっため。

プラグインインストール前に、すでにtranslatorのキャッシュが生成されます。
このキャッシュの中に該当するメッセージが見つからないため、メッセージの表示ができていないようです。

### 手動操作での回避方法
プラグインインストール後に、キャッシュ管理から、translatorのキャッシュ削除を行う。
（プラグインで定義しているメッセージも含めて、translatorのキャッシュが再生成されるので直る）

**Comment by chihiro-adachi** [comment]
#1885 で対応
