### ISSUE TITLE
マスタデーター管理「登録ボタン」押下時の不正な挙動の修正

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#1884]
現象
- すでに登録されている行のNameをブランクにして登録 -> 元のNameが表示されて「登録が完了しました。」となる
- 新しい行にIDを正しく入力してNameはブランクで登録 -> 新しい行は登録されずに登録が完了しました。」となる

期待値
- 必須入力エラーが表示される

**Comment by trebla-on** [comment]
対応中。。。

**Comment by t-nagahashi** [comment]
以下、仕様で決定とします。

◯：入力値あり
×：入力値なし

|ID|Name|新規登録時|更新時|
|◯|◯|登録OK|更新OK|
|◯|×|エラーを表示|エラーを表示|
|×|◯|エラーを表示|エラーを表示|
|×|×|登録なし|データを削除|


※動作確認として、DBの値・ヘッダーに表示される成功/失敗メッセージの表示非表示も確認お願いします。

**Comment by hoand-vn** [comment]
@t-nagahashi 
fix base on your above commented

**Comment by t-nagahashi** [comment]
PullRequestがマージされたためクローズいたします。
