### ISSUE TITLE
Installに利用されるFormTypeが内容を表していない

### ISSUE THREAD

**Issue by denkiryokuhatsuden** [EC-CUBE/ec-cube#1889]
FormTypeの名前は、どういったデータを入力するかによってつけられるものであり、
その使われ方/呼び出され方によって決められるべきではありません。
- Step1Type
- Step3Type
- Step4Type
- Step5Type

createBuilderなどで呼び出すtype名(install_step1, ...)も同様です。

**Comment by Yangsin** [comment]
ありがとうございます。
プラグインやカスタマイズの入る箇所ではないので、マイナーレベルで修正可能（3.0.x）とさせていただきます。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
