### ISSUE TITLE
Controllerで定義されているtitleについて

### ISSUE THREAD

**Issue by amidaike** [EC-CUBE/ec-cube#189]
Controllerのコンストラクタに定義されているtitleですが、
Controllerで毎回titleをtwig側に渡す方法が煩わしいのでtwigの方で継承する方法はいかがでしょうか。

blockを使って、子テンプレートで置き換える方法です。
http://docs.symfony.gr.jp/symfony2/book/templating.html

画面によってはこの方法で不都合があるかと思いますが、
その時はContorller側で渡せば良いかと思います。

ご検討よろしくお願い致します。

**Comment by shinichi-takahashi** [comment]
@amidaike 
ありがとうございます！
現在私の方で管理画面のデザイン変更を全体的にしていってますので、合わせて変更していこうとおもいます。

**Comment by Yangsin** [comment]
@shinichi-takahashi  すでにいただいているPRに該当部分が含まれているようでしたら、実際にどのように実装しているのか、こちらからも参照可能なようにお願いします。

**Comment by shinichi-takahashi** [comment]
@Yangsin 
まだ全ページタイトルを決めていないため、実装にいれこんでませんが、 `{{ block title}}` のような形での実装を考えています。

**Comment by shinichi-takahashi** [comment]
補足
ControllerからViewに渡すのではなく、親にViewに対して子のViewで定義したものを渡す、という形です。
