### ISSUE TITLE
設定のキャッシュを Symfony Config Component の Cache に移行

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#1897]
``Symfony\Component\Config\ConfigCache`` にてキャッシュを行うことで、独自実装が不要となるため、どこかのタイミングで移行を検討できればと思います。

refs
http://symfony.com/doc/2.7/components/config/caching.html
http://api.symfony.com/2.7/Symfony/Component/Config/ConfigCache.html

``isFresh`` により更新を確認し、自動更新を実装可能です。

**Comment by nanasess** [comment]
`Symfony\Component\Config\ConfigCache` の使用も検討していましたが、

- #1812 ディレクトリ探索させたくないので、ディレクトリ情報までキャッシュさせている
- #1695 キャッシュではなく、 config ファイルを PHP で記述できるようにする対応

上記のような理由で、独自実装となっています。
`Symfony\Component\Config\ConfigCache` で解決可能な課題であれば、移行して問題ないと思います。

**Comment by ttsuru** [comment]
@nanasess 

情報ありがとうございます。

> #1695 キャッシュではなく、 config ファイルを PHP で記述できるようにする対応

https://github.com/symfony/config/blob/2.7/ConfigCache.php#L120 
こちらはserializeだと速度的な問題がありそうなのでしょうか。

**Comment by nanasess** [comment]
@ttsuru
僅差みたいですね。 http://blog.tojiru.net/article/133500110.html 
laravel でも、 config は PHP ファイルですし、short array syntax 使えば可読性も悪くないので、わざわざ Yaml にしてキャッシュするまでもないかなぁと思っています。

**Comment by ttsuru** [comment]
@nanasess 
本件、ずばり探していたソースでした。ありがとうございます。
Symfony で var_export を使わずに serialize を利用している理由は後ろの方にある外部ファイルにした場合のパフォーマンスっぽいですね。

``isFresh`` を利用できれば、キャッシュの確認などをプラグイン側で意識しなくても良さそうなので、良い実装があれば移行できると嬉しいです。

**Comment by Yangsin** [comment]
3.nではYaml自体を廃止することとしましたので、クローズいたします。
