### ISSUE TITLE
Model クラスの実装

### ISSUE THREAD

**Issue by pineray** [EC-CUBE/ec-cube#19]
改善したい点は数多く有りますが、ひとつだけ挙げるならこれです。

ページクラスからビジネスロジックを切り離し、処理の対象毎にまとめて Model クラスとして再構築します。

また、従来からのコードで Model と同様の働きをするクラスを Model として再定義します。
例）
SC_Product → ¥Model¥Product¥Product
SC_Helper_Category → ¥Model¥Product¥Category
SC_Helper_Purchase → ¥Model¥Order¥Order
SC_Customer → ¥Model¥Customer¥Customer

**Comment by shinichi-takahashi** [comment]
@pineray 
ご返答遅くなりすみません。
こちらは、
\Model\Orderは$Order->find();みたいに利用できる想定ですか？
抽象化はしないが、Modelだけ切り出したいという形でしょうか。

**Comment by pineray** [comment]
@shinichi-takahashi 
> \Model\Orderは$Order->find();みたいに利用できる想定ですか？
はい。
処理を切り出したうえで、再利用しやすいように加工します。

**Comment by shinichi-takahashi** [comment]
@pineray 

質問ばかりですみません。
すべてのModelで共通して使えるメソッド
Model固有のメソッド
の２つがあるという認識であってますか？

**Comment by pineray** [comment]
@shinichi-takahashi 

> すべてのModelで共通して使えるメソッド
Model固有のメソッド

そうですね。
なるべく共通のメソッドが多くなれば良いとは思います。
旧バージョンで Model を想定して作っていたヘルパークラスでは、
同じような処理を get や save といった共通するメソッド名に当初していました。

**Comment by shinichi-takahashi** [comment]
Enitty / Repositoryとして実装したため、こちらCloseさせていただきます。
ご意見ありがとうございました。
