### ISSUE TITLE
Controller内で利用するrequestオブジェクトについて

### ISSUE THREAD

**Issue by amidaike** [EC-CUBE/ec-cube#190]
Controller内で扱うRequestオブジェクトですが、
$app['request']
として$appから取得する方法と
public function index(Application $app, Request $request)
と引数でもらう方法があります。

例えばRequestオブジェクトが必要のない箇所もあると思いますので、
こちらは適宜使い分ける方法で良いでしょうか。

**Comment by shinichi-takahashi** [comment]
@amidaike 
通常どちらでしょうか？
個人的には、Requestオブジェクトの名前空間が長いので書きたくないのと、引数が増えるのを嫌って
`$app['request']` にしたいですが、多数が馴染みのある方がよいかと思うので、ご意見を聞きたく存じます。

**Comment by amidaike** [comment]
私がSymfony2で開発する際には、
ドキュメントに書いてあるようにRequestを引数として渡しています。
http://docs.symfony.gr.jp/symfony2/book/controller.html#request

これは好みだと思いますので、開発指針として決めておけば良いかと思います。

**Comment by shinichi-takahashi** [comment]
@amidaike 
ありがとうございます。
他の方の意見も聞きながら開発指針を決めたいと思います。

**Comment by nanasess** [comment]
$app から取得すると、メソッドがステートフルになってしまうので、引数の方が良いと思います。

(最近の PHP では、あまりこだわらないのかもしれませんが...)

**Comment by chihiro-adachi** [comment]
IDEで確実に補完が効くのと, 多くの方はSymfonyのドキュメントを参照しながらコードを見ると思うので、引数で渡す、に賛成です。

**Comment by Yangsin** [comment]
まだ、なってない箇所も見受けられますが、
「引数で渡す」を基本として、ここはクローズします。
