### ISSUE TITLE
【管理画面】受注一覧のページング結果が正しくない場合がある

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1905]
現在、update_dateが条件指定されていますが、更新日は同一になる可能性があるため、
第二条件としてidを指定するなどしたほうが良いのではないかと考えます。

更新日の同じレコードが1ページ目の一番下と、2ページ目の一番上に存在する状態で、
2ページ目の関係のない（更新日が違う）受注データを削除したとき、
再度ページングを試すと、1ページ目の一番下に表示されたレコードが2ページ目の一番上にも表示される、という現象が起こりました。（MySQL5.6）
（この現象を確認できたのは、削除されたデータがある場合のみです）

order byで指定したカラム以外の順序は保証されていないために起こるのだと思いますが、
ご確認のほどよろしくお願いいたします。

**Comment by nanasess** [comment]
関連 #1837
