### ISSUE TITLE
3.0.12へのアップグレードでマイグレーション実行エラー

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1911]
Version20161014100031.phpにて、
dtb_customer.email,dtb_order.order_emailに対してインデックスを作成する際にエラーとなります。
私の環境はMySQL5.6ですが、サイズ制限のようです。

**Comment by Yangsin** [comment]
環境に依存するようです。もうすこし詳細な環境設定をいただけますでしょうか？

**Comment by hiroo2016** [comment]
MySQLの制約のようです。
https://dev.mysql.com/doc/refman/5.6/ja/create-index.html

プレフィックス長を256で指定されているところを、255にすれば良さそうです（試してません）

**Comment by nanasess** [comment]
@hiroo2016 手元の MySQL5.1.73 では、勝手に 255 byte になるようです

```
Server version: 5.1.73 MySQL Community Server (GPL)
mysql> show create table dtb_order;
... snip
  KEY `dtb_order_order_email_idx` (`order_email`(255)),
```

エラーが発生しているとのことですが、エラーメッセージを共有いただけますでしょうか。
エラーで落ちるのは問題ですので、 utf8mb4 なテーブルは 191 byte にしなければならないと思いますし。

**Comment by hiroo2016** [comment]
エラーは以下のとおりです。
よろしくお願い致します。
```
Server version: 5.6.34 MySQL Community Server (GPL)
mysql> CREATE INDEX dtb_customer_email_idx ON dtb_customer(email(256));
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

**Comment by nobuhiko** [comment]
MySQL5.6から厳しくなったのでそのへんが原因じゃないでしょうか
http://blog.seeds-std.co.jp/entry/1035.html

**Comment by nanasess** [comment]
まだ時間がとれず、再現確認できてないんですが、https://travis-ci.org/EC-CUBE/eccube-codeception の mysql:latest が何ごともなく通ってるので、実際はどうなのかなと。

**Comment by ttsuru** [comment]
utf8mb4だとこのエラーよくでますよね。

**Comment by ttsuru** [comment]
カスタマイズで `utf8mb4 ` にして絵文字の保存を可能にしているのではないでしょうか。

/etc/my.cnf に以下を追加すれば良いと思います。

```
[mysqld]
innodb_file_format = Barracuda
innodb_file_per_table = 1
innodb_large_prefix
```

**Comment by ttsuru** [comment]
原因はMySQLのIndexに関する問題です。 5.6で発生しますが、5.7でデフォルトが変わったので発生しません。

**Comment by nanasess** [comment]
MySQL5.6 のみの問題ですか。
RFCでは256文字以下となっているので悩ましいですね...

参考
http://d.hatena.ne.jp/tanamon/20090930/1254332746

**Comment by ttsuru** [comment]
@nanasess  
参考の内容は古いですね。  
寿司ビール問題の典型なので、EC-CUBEでMySQLのutf8mb4に対応するまでは発生しない問題かと思います。

**Comment by ttsuru** [comment]
refs https://techracho.bpsinc.jp/hachi8833/2016_08_25/25044

**Comment by nanasess** [comment]
@ttsuru 
> 寿司ビール問題の典型なので、EC-CUBEでMySQLのutf8mb4に対応するまでは発生しない問題かと思います。

メールアドレスの文字数が RFCで256文字以下なので、 256文字の INDEX をメールアドレスのカラムに貼ろうとして、現状の utf8 で発生しているんです。
/etc/my.cnf の修正ができない環境も考慮しないといけません。

対処法としては 1 が妥当ですかね。長大なメールアドレスが紛れ込んでいたときの挙動はどうなるんでしょう？

1. RFCを守らず、かつ utf8mb8 のカスタマイズも考慮して 191 を指定する
2. RFCを守らず、 utf8mb8 も考慮せず 255 を指定する
3. INDEX を張らない
4. 他にもっと良い方法がある
5. MySQL 5.6 は非推奨とする

**Comment by seasoftjapan** [comment]
インデックスの話なので、「RFCを守らず」とはならないのでは?
(UNIQUE だと、厄介ですが)

・・・と思いましたが、もしかして、ORM 都合で、実データとインデックスの文字数を別々にできない感じですか?
(なら、知らない。。。)

**Comment by hiroo2016** [comment]
@seasoftjapan 
インデックス長を255にして試してみましたが、問題なくインデックスが作成されました。
ORM都合ということはなさそうです。
ちなみにemailカラムはlongtextです。UNIQUEでもないです。
なので、nanasessさんの案1が良いのではないでしょうか。

**Comment by Yangsin** [comment]
@hiroo2016 検証ありがとうございます。

nanasess の１案でいけそうですね。
3.0.13 では、Version20161014100031.php  のIndexを貼る記述の修正と、3.0.12からのアップデート向けに、1案にしたIndexを貼り直す形が、できれば大丈夫そうでしょうか。

**Comment by nobuhiko** [comment]
Travisは5.7なんですかね？
MySQL 5.6は手動で入れないとダメそうです
https://docs.travis-ci.com/user/database-setup/#MySQL-5.6

**Comment by ttsuru** [comment]
本件、何か違うような気がします。

@nanasess  
`utf8mb8` は `utf8mb4` のことでしょうか。  
今回のエラーはMySQL5.6におけるINDEX上限のデフォルトが 767 bytes になっていることに起因しているかと思います。
そもそもemail のカラムには英数字しか入らないので何か他の方法がありそうな気がしますが・・・  
他にも同様の問題は発生しそうですので、今回のみのpatchとしてではなく、しっかりと確認した方が良さそうですね。

**Comment by nanasess** [comment]
@ttsuru utf8mb4 の typo でした。すみません。修正しておきます。

**Comment by ttsuru** [comment]
@nanasess  
こちらこそ、今回はutf8mb4は関係ありませんでした。
5.6のデフォルトで、厳密なチェックが行われているために問題が発生しているようです。
Doctrineでも同様の話は議論されていたようです。

**Comment by nanasess** [comment]
MySQL 5.6.32 にて

`sql_mode = STRICT_TRANS_TABLES` でエラーが再現することを確認

```
mysql> SET @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@GLOBAL.sql_mode;
+--------------------------------------------+
| @@GLOBAL.sql_mode                          |
+--------------------------------------------+
| STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.00 sec)
```
