### ISSUE TITLE
【管理画面】商品登録でカテゴリの解除ができない

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/ec-cube#1914]
商品にカテゴリを設定すると、変更はできても解除（どのカテゴリにも属させない）ができません。

**Comment by chihiro-adachi** [comment]
@hiroo2016 
ctrlキーを押しながらクリックで解除できないでしょうか？

**Comment by hiroo2016** [comment]
普通にできました・・・
確認不足で申し訳在りません。
