### ISSUE TITLE
退会した会員のパスワード再発行時の画面出力の変更

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1919]
既に退会した会員、または仮登録中の会員が、パスワードの再発行をしようとすると、 **パスワード変更(完了ページ)** へ遷移する。
この場合、エラーメッセージや、ログなど何も出力しない。

未登録の旨のエラーを画面に表示してしまうと、セキュリティ上好ましくない場合があるが、せめてログに出力してほしい。

**Comment by Yangsin** [comment]
パスワード変更（完了ページ）には、遷移させつつ、管理者向けてログには出力するようにしたいと思います。
出力レベルは、Warning くらいで。
