### ISSUE TITLE
メール設定で本文を編集可能にし対象のメールテンプレートも増やす

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1924]
### メール設定の3.0.12での仕様

+ メール設定から受注メールの件名、ヘッダー/フッター が編集できる
+ メール本文については直接
```
ECCUBEROOT/src/Eccube/Resource/template/default/Mail
```
直下にあるtwigファイルを修正する

### メール設定の機能強化案

+ メール設定からシステムで送信している各メールの件名、ヘッダー/フッター、本文（Twig)を編集可能とする
+ 編集対象
    - お問い合わせメール
    - 会員仮登録メール
    - 会員本登録メール
    - 会員退会メール
    - パスワードリマインダー
    - パスワードリセット
    - 受注メール

### 注意点

受注メールの送信が`dtb_mail_template`のIDが1のデータでヘッダー、フッターの内容が送信されるように、MagicNumberになっているため、constant.yml への設定の切り出しを伴う想定

### テンプレートの編集時の挙動

まだ編集されたメールテンプレートが存在しない場合メール設定からメール本文を編集しようとすると
```
ECCUBEROOT/src/Eccube/Resource/template/default/Mail
```
からオリジナルを読み出し、保存する際に
```
ECCUBEROOT/app/template/[tepmaltecode]/Mail
```
に保存され、メール送信時は`app/template`へ新しく保存されたメールの内容で送信される。

### メールに関する関連Issue / PullRequest
#220 3.0.0-beta時の仕様検討
#728 メールでの問い合わせ運用についての質問
#755 メールテンプレート編集機能についての質問
#1913 メールテンプレートの編集機能のPullRequest

**Comment by okazy** [comment]
#2672 で対応済みのためcloseします。
