### ISSUE TITLE
地図表示の削除

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1925]
APIキーが必須となっているため、緯度経度を入力しても表示しない

```
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
```

**Comment by nanasess** [comment]
このような画面が表示される

![2016-11-15 10 24 40](https://cloud.githubusercontent.com/assets/815715/20289517/bfeebb4e-ab1d-11e6-8ac7-b5e63b66e4af.png)

**Comment by Yangsin** [comment]
単純になおすだけでなく、そもそも機能を削除するのもありかもしれませんね。。。

**Comment by Yangsin** [comment]
3.1で削除の方針で。

**Comment by chihiro-adachi** [comment]
#2649 で対応
