### ISSUE TITLE
`plg_`から始まるtwig関数の場合、未定義でもエラーを無視したい

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#1936]
### 背景
Twigの拡張functionを追加するプラグインを作成しています。

例えば、プラグインインストール後に、
twigファイルの任意の位置に下記の記述をすると、値引率を表示できるようなプラグインです。
`{{ plg_discount_rate(Product) }}`

### 困っていること
プラグインを無効化or削除すると、Twigの解析処理でエラーとなってしまい、プラグインを使う側からすると結構混乱します。
`Unknown "plg_discount_rate" function in "__string_template__327......`

### 提案
`plg_`から始まるtwig関数の場合、未定義でも無視をするようにできないでしょうか？

実装イメージ
```
$twig->registerUndefinedFunctionCallback(function ($name) {
    if (strpos($name, 'plg_') === 0) {
        return new \Twig_SimpleFunction($name, function () {
            log_info('unknown twig function', array($name));
        });
    }

    return false;
});
```

### その他やってみたこと
`loaded`という拡張Testを作成して
```
{% if 'plg_discount_rate' is loaded %}
    {{ plg_discount_rate() }}
{% endif %}
```
みたいな実装も試してみましたが、if文とか関係なく`{{ plg_discount_rate() }}`と書いてあるだけでTwigの解析エラーになるのでダメでした。

**Comment by ttsuru** [comment]
逆のアプローチで、削除前にテンプレート内を探索して警告を出してはいかがでしょうか。
エラーがでないことよりもエラーを出さないほうが運用時に安全なのではないでしょうか。

**Comment by Yangsin** [comment]
様々な理由でTwigで存在していない拡張Functionが残ってしまうということはありそうですので、エラーを無視してログに出すようにする事自体はあって問題なさそうです。
エラーが黙殺されたまま運用されないようにエラーレベルはInfoよりも上げてはどうでしょうか。

課題としては分けることになりそうですが、Twigの拡張Functionを利用するプラグイン側では、削除時の処理で警告だす方法を決めたほうがよさそうですね。できれば、プラグイン側で意識しなくてもできるように本体側の仕組みでやりたいです。

**Comment by ryo-endo** [comment]
そうですね。
明らかにおかしいコードがtwigに混じっているので、`log_error`でよさそう。

あと、「plg_から始まる～」と限定してIssue立てたのですが、またひとつプラグインのお作法を増やしてしまうことになるのは避けたいです。そもそも未定義の関数すべてを対象にしてもよろしいでしょうか？

**Comment by Yangsin** [comment]
テンプレート介入のルール自体を3.nから見直すため、本件はクローズとします。
テンプレートへの介入方法の見直し #2440
