### ISSUE TITLE
Symfony、SilexのFormt/Typeを使用した形で、【生年月日を和暦】で表示したい

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#1938]
調査しましたが、解決できておりません。
EC-CUBE本体に表示切替ができると便利です。
検討お願いします。

**Comment by Yangsin** [comment]
http://qiita.com/chiyoyo/items/3d12e5b1ef63e7f332ba
みたいな拡張が必要そうですね。

**Comment by Yangsin** [comment]
https://github.com/mbilbille/jpnforphp
こういうの使うといけそうな気もします。

**Comment by ttsuru** [comment]
Symfony の i18n の仕組みを使って、select タグの中身を和暦込みで表示したらいけそうですね。  
FormType の Choice はデフォルトでi18nを利用していた気がします。

**Comment by kiy0taka** [comment]
カスタマイズの範疇として標準では対応しない方向でこちらはクローズします。

**Comment by nanasess** [comment]
ちなみに intl を使用すると和暦の表示ができます
```php
<?php
$date = new \DateTime('645-12-31');
// 大化01年
$dateFormatter = \IntlDateFormatter::create(
    "ja_JP@calendar=japanese",
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::FULL,
    "Asia/Tokyo",
    \IntlDateFormatter::TRADITIONAL,
    'Gyy年'
    );
echo $dateFormatter->format($date);
```

see https://gist.github.com/hidenorigoto/2327195
