### ISSUE TITLE
商品の規格登録画面で規格数が多い時にメモリ不足でシステムエラーになる

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#1939]
商品の規格登録画面で規格数が多い時にメモリ不足でシステムエラーになる

規格数19×31で下記のエラーが発生。

PHP Fatal error:  Maximum execution time of 30 seconds exceeded in vendor/symfony/yaml/Parser.php on line 405
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2326528 bytes) in vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code on line 463

**Comment by Yangsin** [comment]
どれくらいのスペックで、どの程度の規格の組み合わせまでをスコープとするか検討いたします。

**Comment by jumemoto** [comment]
規格数が多くなると、商品の規格を追加出来なくなる事象が発生。
PHPのデフォルトmax_input_varsが1000になっていることが原因。

**Comment by izayoi256** [comment]
規格数2000でページの表示を試みたところ、メモリー消費が1109MBでした。

**Comment by Yangsin** [comment]
次のバージョンでは規格自体の在り方を大きく考え直すほうが良い気がしてます・・・

組み合わせ数があふれてしまうものって、同じサイズやカラーでも、メーカーや商品シリーズのパターンで言い回しが違うのに対応しようとしてという気がしてます。

解決策として、規格名を、たとえば「トヨタレクサス:カラー」、「ホンダデミオ:カラー」とか管理者がわかりやすい名前で登録しようとすると
登録したものがそのままフロントのセレクトボックスに出てしまう・・・

それが嫌なら「カラー」の下にズラズラと似たような言い回しの物が並んで膨大になる。
既に登録済みのものを見落として新規登録してしまったり、微妙な入力の癖(半角全角など)の違いが反映されたもので更に増殖。
みたいな問題があるのかなと。

規格登録画面は全組み合わせを表示するのではなく、必要な組み合わせを追加する方式や、あまり使いまわさないのであれば、そもそも規格管理していくのではなく、商品毎に設定するのでもいいのかなと。

もしくは、管理用の名前をもてるだけでもかなり楽になってくるのかも？

**Comment by Yangsin** [comment]
関連 #657

**Comment by kiy0taka** [comment]
#2586 の方法で進めていきますので、こちらはクローズします。
