### ISSUE TITLE
新規お届け先を追加画面のMobile表示で変更ボタンが表示されていない

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#1941]
**環境**

1. PHP
2. Postgresql

**再現**

- マイページ/お届け先編集に移動する
- 新規お届け先を登録
- SmartPhoneで表示する

**結果**

お届け先変更ボタンが表示されない
![ok](https://cloud.githubusercontent.com/assets/17536702/20613507/4efdad14-b2f7-11e6-95de-2066353c8590.PNG)

**要望結果**
お届け先変更ボタンを表示する。

**Comment by t-nagahashi** [comment]
PullRequestがマージされたためクローズいたします。
