### ISSUE TITLE
How to load product in template!

### ISSUE THREAD

**Issue by baoviet** [EC-CUBE/ec-cube#1948]
Hi, I'm new for EC-cube 3. I have a problem when try to load some products to top page. 
But I see in this [file](https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/default/Block/new_product.twig).

    <div class="row">
        <div class="col-sm-4 col-xs-12">
            <div class="pickup_item">
                <a href="{{  url('product_detail', {id : 2}) }}">
                    <div class="item_photo"><img src="{{ app.config.front_urlpath }}/img/top/img03.jpg"></div>
                    <dl>
                        <dt class="item_name text-warning">お気に入りのエスプレッソタイム</dt>
                        <dd class="item_comment">コーヒータイムを上質な時間にしてくれる、口当たりのよさとデザイン性を兼ね備えたエスプレッソカップを集めました・・・</dd>
                        <dd class="more_link text-warning">read more</dd>
                    </dl>
                </a>
            </div>
        </div>

This Block should be shown out the new products. But in this code jus display HTML code.
So how to I can get products and show out to .twig file. without modifying Controller
Thank you!

**Comment by Yangsin** [comment]
This issue is not about EC-CUBE core development. I close it.
If you have any questions about customize,  post on user community (http://xoops.ec-cube.net  or  http://en.ec-cube.net )  please
