### ISSUE TITLE
開発時のメール送信の扱い方について

### ISSUE THREAD

**Issue by amidaike** [EC-CUBE/ec-cube#195]
開発中はメール誤送信を防ぐために以下のような機能があれば助かります。
http://docs.symfony.gr.jp/symfony2/cookbook/email/dev_environment.html#id3

私の方でSwiftmailerServiceProviderクラスを拡張して上記機能を実装してみたのですが、
このような機能が必要とないと判断されるのであれば無視してください。

**Comment by Yangsin** [comment]
ブラックボックスの脆弱性ツールや負荷試験でも、有効活用できそうですね。

**Comment by Yangsin** [comment]
こちらマージ済みですので、Issueクローズさせていただきます。
ご対応ありがとうございました。
