### ISSUE TITLE
PHP7.1 対応

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/ec-cube#1957]
■問題：ユニットテストは失敗する
Eccube\Tests\Repository\TaxRuleRepositoryTest::testGetByRuleWithCountry
Failed asserting that 533 matches expected 532.

■説明：そのテストの中に「Eccube\Entity\TaxRule::compareTo()」を使ってます、メッソドの中に
DateTimeを比べてます、PHP7.1からmicrosecondsも含めています。
if ($this->getApplyDate() == $Target->getApplyDate()) {
PHP7.1のドキュメントｈこちらです
http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.datetime-microseconds

■対応方法：フォーマトした日付を比べる
if ($this->getApplyDate() == $Target->getApplyDate()) {
↓
if ($this->getApplyDate()->format('YmdHis') == $Target->getApplyDate()->format('YmdHis')) {

**Comment by Yangsin** [comment]
7.1環境で動作確認を行えればシステム要件に追加したいと思います。

**Comment by t-nagahashi** [comment]
以下2種類の確認をもって、動作確認とします。
・codeceptionにて確認
・時期バージョンアップの動作確認テストにて、手動テスト

**Comment by nanasess** [comment]
EC-CUBE API で以下の対応が必要です。
https://github.com/EC-CUBE/eccube-api/issues/62

**Comment by t-nagahashi** [comment]
codeception, 受入テストがOKとなりましたので、
3.0.14以降、PHP7.1をシステム要件に追加したいと思います。
