### ISSUE TITLE
PageLayout に登録されていないページの表示

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#1963]
PageLayout(dtb_page_layout) に登録されていない URL を表示しようとすると、ヘッダー・フッターが取得できない仕様となっている。

しかし、プラグインから新規ページを追加した場合など、 PageLayout に逐一登録するのは大変なので、 PageLayout への登録簡素化または、デフォルトでヘッダー・フッターを表示するようにしたい。

**Comment by kiy0taka** [comment]
PageLayout への登録簡素化の仕組みを検討したいと思います。
