### ISSUE TITLE
【提案】 設定ファイルの改善

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/ec-cube#1965]
#http://qiita.com/mikakane/items/9bf87b9eb23b124f916e 

パット見ですが上記内容のようなHeorku 運用上の問題があり、幾つかの改善を加えました。

https://github.com/mikakane/ec-cube/tree/ask_admin_credential_on_setup

https://github.com/mikakane/ec-cube/tree/support_heroku_pg_config

特にHeroku Postgresの運用については、初心者がハマりやすいところなので対応必要かと思うのですが、設定ファイルをYaml からphpに移すのはどうなんでしょうか…？
(個人的にはyml 設定ファイル全廃して .env など導入するほうがわかりやすいような気もしています。) 

# 管理画面のユーザIDについて

## 前提

Heroku Button でのセットアップ時にデフォルトのパスワードが利用される。

## 問題・課題

デモ目的で放置されることも多いアプリでデフォルトパスワードは非常に危険

## 対応方法

環境変数をHeroku Button セットアップ画面から入力できるよう対応

# Heroku Postgres の接続設定について

## 前提

Heroku Postgres の接続情報は任意のタイミングで更新される。

## 問題・課題

Yaml を利用した設定ファイルでは、メンテナンス等、Heroku PostgresのURL変更にアプリケーションが追従できない。

## 対応方法

設定ファイルをphp のものに変更。環境変数から動的にこれを取り込む

**Comment by Yangsin** [comment]
Herokuだけに限らず設定ファイルのありかたの議論が必要そうなのでタイトル含め調整しました。
3.1では見直しをかけたいと思います。

> 個人的にはyml 設定ファイル全廃して .env など導入するほうがわかりやすいような気もしています

開発環境から本番前スムーズにデプロイできつつ、レンタルサーバーでも扱えて
管理画面の設定からでも編集可能な感じにしたいですね。

**Comment by nanasess** [comment]
参考 https://github.com/EC-CUBE/ec-cube/pull/1695

**Comment by okazy** [comment]
4.0系では.envファイルで設定が可能となりました。
また、Heroku設定時にパスワードを設定できるようになりました。
