### ISSUE TITLE
商品別税率設定が動作していない

### ISSUE THREAD

**Issue by kk580923** [EC-CUBE/ec-cube#1969]
EC-CUBE3で、商品単位で消費税を設定したいのですが、反映されないようです。

サンプルサイトでも試してみたのですが、共通の８％が有効になり、
個別に５％、１０％等設定してみても反映されませんでした。
http://site3.ec-cube.net/admin/setting/shop/tax
http://site3.ec-cube.net/admin/product/product/84/edit
http://site3.ec-cube.net/products/detail/84?admin=1

下記、サイトを参考にしたのですが、追加で何か設定等が必要だったりしますか？
http://ec-cube.github.io/spec_tax

**Comment by chihiro-adachi** [comment]
apply_dateをtimestampで比較しようとしており、登録したタイミングでは反映されないようです。
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Repository/TaxRuleRepository.php#L132

```
->where('t.apply_date < :apply_date');
->setParameter('apply_date' , new \Datetime());
```
のようにdatetimeで比較する必要があると思われます。
