### ISSUE TITLE
マスタ検索の簡易検索を部分一致にする

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#1972]
管理画面の全検索の簡易検索について、
現在完全一致ですが、顧客名での検索等は業務上部分一致で実施することが多いため、
部分一致の方が望ましいかと考えております。

ご検討お願いします。

![image](https://cloud.githubusercontent.com/assets/13776434/21165051/284d0b2c-c1e0-11e6-8f5c-fa8a77d5cbda.png)

**Comment by Yangsin** [comment]
半角の数値のみの場合、ID検索で完全一致とし、それ以外は名前・メールアドレスの部分一致で検索とする ようにしたいと思います。
その他、ご意見あればいただければと。

**Comment by t-nagahashi** [comment]
対応箇所は、商品/受注/顧客の3箇所対応でいかがでしょうか？

**Comment by trebla-on** [comment]
現在の動作を確認しました。
結果はこちらです
■会員マスタ
　□半角数のみ　（会員ID完全一致、その他カラム使用してない）
　　customer_id = ?
　□半角数以外　（会員名、会員カナ、メールを部分一致、会員ID使用してない）
　　CONCAT(d0_.name01, d0_.name02) LIKE '%?%' 
  OR CONCAT(d0_.kana01, d0_.kana02) LIKE '%?%' 
  OR d0_.email LIKE '%?%'
■商品マスタ
　□半角数のみ　（商品ID完全一致、その他カラム部分一致）
　　d0_.product_id = ? 
  OR d0_.name LIKE　'%?%'
  OR d1_.product_code LIKE '%?%'
　□半角数以外　（商品ID完全一致、その他カラム部分一致）
　　d0_.product_id = null <--　ここはNULLを設定されてます
  OR d0_.name LIKE '%?%'
  OR d1_.product_code LIKE '%?%'
■受注マスタ
　□半角数のみ　（受注ID完全一致、その他カラム部分一致）
　　d0_.order_id = ? 
  OR d0_.order_name01 LIKE '%?%'
  OR d0_.order_name02 LIKE '%?%'
  OR d0_.order_kana01 LIKE '%?%'
  OR d0_.order_kana02 LIKE '%?%'
  OR d0_.order_company_name LIKE '%?%'
　□半角数以外　（商品ID完全一致、その他カラム部分一致）
　　 d0_.order_id = null <--　ここはNULLを設定されてます
   OR d0_.order_name01 LIKE '%?%'
   OR d0_.order_name02 LIKE '%?%'
   OR d0_.order_kana01 LIKE '%?%'
   OR d0_.order_kana02 LIKE '%?%'
   OR d0_.order_company_name LIKE '%?%'

**Comment by ryo-endo** [comment]
@t-nagahashi 
3.0.8までさかのぼって確認しましたが、以前から部分一致のようです。

@trebla-on 
会員マスタを、他のマスタと検索条件を統一するように修正お願いします。

**Comment by ryo-endo** [comment]
#2060 でmasterにマージしましたのでCLOSEします。
