### ISSUE TITLE
デフォルトのテンプレートの初期状態を微調整

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1980]
デフォルトのテンプレートのリンク先やダミーのテキストがわかりづらい

### 今

一覧を見る→ リンクがダミー
商品画像 → 全てパーコレーター
5000円以上送料無料 → 完全なテキスト

### 期待

一覧をみる → 商品一覧へ
商品画像 → ダミーであればリンクしないか、ダミーへの遷移であることがわかるように
5000円以上送料無料 → 設定にあわせて変わる

**Comment by lammn** [comment]
＠nagahashi 
期待

一覧をみる → 商品一覧へ
商品画像 → ディナーフォーク画像以外はダミーになります。
5000円以上送料無料 → どこに移動したらいいですか。

**Comment by t-nagahashi** [comment]
期待値を整理しました。

EC-CUBEの初期インストール時の状態を変更する修正です。

■対象画面
TOPページ
■修正内容
◯一覧を見るをリンクにし、文言を変更。
文言：「商品一覧へ」
リンク先：商品一覧
◯商品画像で、リンク先が誤っている箇所のリンクを"#"とする。
◯「5,000円上送料無料」現在テキスト表示機能を変更する
・ショップマスタの設定から動的に取得する。
　1未満 or 値設定なしの場合は、0円以上とする。
・「5,000以上」となっているものに、円をつける。
例）5,000円以上

**Comment by t-nagahashi** [comment]
PullRequestがマージされたためクローズいたします。
