### ISSUE TITLE
カテゴリCSV登録は、列順が異なっていてもカラム名が一致していれば、登録可能とする

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1981]
カテゴリCSVダウンロードでダウンロードできる項目がカテゴリ登録CSVのフォーマットの項目と大きくちがっている
デフォルトの項目であればダウンロードして再アップロードが可能なようにしたい

**Comment by nanasess** [comment]
参考 #620

**Comment by trebla-on** [comment]
対応中。。。

**Comment by t-nagahashi** [comment]
@trebla-on さんの意見を採用する場合、商品CSV出力登録も同様に対応が必要かと思います。

**Comment by t-nagahashi** [comment]
以下仕様でいこうと思います。

◯CSV登録画面に表示されているヘッダー名と、CSVファイルのヘッダー名を一致させている状態であれば取り込む。
◯ただし、カラムの順序は問わない。
（ヘッダー名の一致を元に、登録する値とカラムのヒモ付を行う）

**Comment by t-nagahashi** [comment]
#2081 も同様の仕様とします。

**Comment by nanasess** [comment]
#2293 にて修正済み
