### ISSUE TITLE
機能カスタマイズ性の向上に向けた機構改善

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#1984]
3.1に向けて、3.0でプラグイン開発、本体カスタマイズ共に更に開発をしやすいように機構の改善を行っていきたいと思っています。
どの程度の規模の改修が必要になるかは、検討が必要ですが以下のような、大きく2つの変更を検討しています。

### 1. デザインパターンを適用したカスタマイズ性の向上

+ イメージ
  - 購入処理などユースケースに合わせた処理の流れをきちんと定義しデザインパターンを適用しサービス化の強化
  + Strategy Pattern で処理を置き換える事を可能にする

### 2. ECのためのFrameworkとしての構造の強化

+ イメージ
  - デザインパターンの適応だけではむずかしいような内容について対応
  - 決められた流れを大きくかえるようなパターン（DLに商品、会員限定購入サイトなど）
  - カスタマイズの敷居を下げるようなしくみ
     - WordpressのFunction.php のようにライトなイメージ

### 参考
#694  #83

### ユースケースのリストアップおよび分類
https://drive.google.com/open?id=1aT_nZKY6YEH8bi0cbUxaFoTTc9zU0_qfBfl8aN-HYyU

**Comment by nanasess** [comment]
#1985 で Pull Request してます

**Comment by nanasess** [comment]
独自のアノテーションではなく、 SensioFrameworkExtraBundle のアノテーションを使えるようにしてみました。

https://github.com/EC-CUBE/ec-cube/pull/1985/commits/ab655faab1809f66d45227dd1759266b3bfcb3a0?diff=unified#diff-41b521fbeda50e9e5b3857414ff7b111

**Comment by nanasess** [comment]
実現したいこと。目標としては、 `app/Eccube/Controller` 以下に、簡潔に記述可能な、カスタマイズ用のコントローラを置くことで、簡単に振舞いを変更できるようにしたい。

- [ ] ビジネスロジックに Strategy や、 Adapter パターンを適用し、簡潔にカスタマイズできるようにしたい
- [ ] SensioFrameworkExtraBundle アノテーションの利用
- [ ] Doctrine アノテーションの利用
       - Yaml との共存が難しそう
       - SensioFrameworkExtraBundle アノテーションとの共存が難しそう
- [ ] SubRequest(forward) を使用して Controller をチェーンのようにつなげられるようにしたい

**Comment by nanasess** [comment]
継承を使用せずに、コントローラの一部をオーバーライドできるようになりました。
https://github.com/nanasess/ec-cube/commit/e4278ce6d050cb93da98350a087f2b405492d1a7

`forwardChain` で、 Controller をチェーンのようにつなげることも可能です。

**Comment by chihiro-adachi** [comment]
4.0の反映された機構は以下にまとめています。
http://doc4.ec-cube.net/#%E6%9C%AC%E4%BD%93%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA
