### ISSUE TITLE
レイアウト編集で新規追加ブロックの配置が１番上になる。

### ISSUE THREAD

**Issue by idsnakamura** [EC-CUBE/ec-cube#2002]
【現象】
　プラグインで新規追加したブロックを、TOPページ以外で全ページ表示ブロックの間に
　配置することができない。全ページ表示ブロックの１番上に配置されてしまう。

【手順】
　①コンテンツ管理＞ページ管理＞TOPページ＞レイアウト編集で、下記の状態になっている。
　　「全ページ」表示になっている標準ブロックが5つ配置されている。
　②新規ブロックを追加するプラグインを有効にする。
　③コンテンツ管理＞ページ管理でTOPページ以外のレイアウト編集を開く。
　　「全ページ」表示になっている標準ブロックの間に、プラグインの新規ブロックを配置して、登録する。
　④登録すると、「全ページ」表示になっているブロックの１番上に配置されてしまう。

【修正方法】
　下記いづれかの修正が必要
　　・DBのデータ
　　・プログラム

**Comment by okazy** [comment]
4.0系ではレイアウト編集機能を見直しましたので、こちらの問題は発生しなくなりました。
