### ISSUE TITLE
SSLを強制した状態で、httpのURLでログイン画面にアクセスした場合ログインが行えない

### ISSUE THREAD

**Issue by h-kida** [EC-CUBE/ec-cube#2011]
[現象]
管理画面の「セキュリティ設定＞SSLを強制」にチェックをいれ、SSL強制した場合に「https」ではなく「http」 のURL(※1)で管理画面や、フロント側のログイン画面にアクセスした場合、正しいIDとパスワードを入力してもログインが行えない。

※1 例)
http://xxx.jp/mypage
http://xxx.jp/admin

**Comment by Yangsin** [comment]
ログインができないことよりも、ForceSSLが有効な状態でhttpでアクセスできることが問題ですね。

**Comment by h-kida** [comment]
こちら、遷移後のURLは正しく「https」となっているようなのですが、リダイレクトが上手く行えていないのか、こちらの現象が起きるようです。

修正方法として、正しいのか自信がないのですが、後程修正を行ったもののPull Requestを投げさせて頂きます。

**Comment by chihiro-adachi** [comment]
@h-kida 
prありがとうございます。

すみません、1点確認なのですが、httpsへリダイレクト後の画面でID/パスワードを入力するとエラーになる、という事象であっていますか？

- httpでログイン画面にアクセス
- httpsのログイン画面へリダイレクトする
- ID/パスワードを入力するとログインできない

**Comment by h-kida** [comment]
はい。合っております。

httpのURLで、ログインが必要な画面に直でアクセス（ブラウザ上のURLは、リダイレクトされてhttpsになっている状態）。
その状態でIDとパスワードを入力すると、エラーメッセージ等は表示されず、再度ログイン画面が表示される状態となります。

**Comment by chihiro-adachi** [comment]
ありがとうございます。
こちらでも事象確認できました。修正も問題ないかと思います。
