### ISSUE TITLE
mac, safariにて、商品登録等の登録系画面の右側にある「登録」ボタンが、画面スクロール時追従しない。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2016]
mac、chromeやwindowsでは正常に動作しておりますが、
mac, safariのみ非対応です。

以下バージョン情報です。
macOS：10.12.2
safari：10.0.2

**Comment by t-nagahashi** [comment]
追加の情報です。
画面によって追従する画面としない画面が存在します。
■追従する画面
ショップマスター
特定商取引法
■追従しない画面
商品管理
会員管理

**Comment by ryo-endo** [comment]
#2057 で対応済みです。
