### ISSUE TITLE
【要望】PHPExcelを標準に含めて欲しい

### ISSUE THREAD

**Issue by SumikoTohyama** [EC-CUBE/ec-cube#2019]
## 前提
プラグインの開発で、Excelで出力する帳票を作成する。

## 問題・課題
①Excel出力するには、PHPExcelを使用する。
②プラグインで出力できるようにするには、PHPExcelをプラグイン内に含めないといけない。
③コンポーネントのサイズが大きいため、PHPのアップロードサイズの上限を変更する必要がある。
④他のプラグインでも使用する場合、重複する。

## 対応方法
PHPExcelコンポーネントをEC-Cube3の標準に含める。

**Comment by pineray** [comment]
PHPExcelを標準に含めるよりは、プラグインの機構に依存情報を含めるほうが良いと思います。
PHPExcelのみのユーティリティプラグインを別途作成して、それがインストールされている場合にのみ動作する、というようにすれば他にも応用できます。

アップロードサイズの上限については、WordPressのような管理画面からの直接ダウンロードを実現していただけるのではないかな、とロックオンさんには期待しています。

**Comment by Yangsin** [comment]
PHPExcelにかぎらず、プラグインで外部のコンポーネントをどう利用するかという作法を決めるというのが必要そうですね。

**Comment by nanasess** [comment]
使ったことないですが、 Composer に関していえば、こういうの使えませんかね?
https://github.com/wikimedia/composer-merge-plugin

コマンドラインで叩けないような環境では難しいかもしれません。。。

**Comment by okazy** [comment]
#2034 でプラグインでもcomposerが使えるようになりますので、こちらのissueはクローズします。
