### ISSUE TITLE
フロントのデザインテンプレートでのフォームヘルパーの利用の見直し・分解

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2033]
## 課題

EC-CUBE 3系の デザインテンプレートの制作、特にフォームのデザインカスタマイズにたいして、Webデザイナー・マークアップエンジニア・フロントエンドエンジニアといった層での利用ハードルが高い。
要因として、Twigを利用したテンプレートの作り方として、form_type、form_layout.twigで、抽象化されていたり、コアコード側にラベルの記述があるため、手が出しづらい状況になっている。

## 検討方向性

フロント側のTwigについては、冗長な記述になったとしても、各ページで上記のようなユーザーであっても、カスタマイズ部分の影響が限定的で理解しやすいように見直しを行う

**Comment by chihiro-adachi** [comment]
form_layout.twig(form_widgetやform_errors)を使用せず、twigにformのコードを直接記述するサンプルを作成しました。

会員登録画面
https://github.com/EC-CUBE/ec-cube/compare/master...chihiro-adachi:exp/twig?expand=1#diff-f441d943459a592bc1fbc59dbf2b0f25

2系のSmartyとほぼ同様の記述になります。
https://github.com/EC-CUBE/eccube-2_13/blob/master/data/Smarty/templates/default/contact/index.tpl

所感
- 記述量がだいぶ増える代わりに、html/css上の細かい調整はやりやすい
- twig上の記述とどのFormTypeの項目と紐付いているかは、少し見通しが悪い
    - NameTypeやAddressTypeなど、共通化されているFormType
    - FormTypeの仕組みを理解していないと追えないので、ベタに書いてしまったほうがよいかも
- `form.xxx.vars.xxx`を大量に書かないといけないので、ショートカット関数などは必要そう
    - http://qiita.com/ponko2/items/fd7ac38b964e10f16f52 くらいのイメージでかけると良さそう

**Comment by ttsuru** [comment]
form_widget 使わないとだいぶ大変になりますね。

**Comment by nobuhiko** [comment]
使用せずのほうはデザイナーの敷居が下がったのでしょうか？
プラグインからの拡張を考えると最悪な展開な気がします

**Comment by Yangsin** [comment]
@ttsuru 
手間はかかると思いますが、画面ごとに調整はしやすくなるのではないかと見込んでます。

@nobuhiko 
具体的に変更したコードを見せてのヒアリングはこれから進めていくところですが、イメージレベルで2系の頃にSmartyを触れてたマークアップエンジニア数名にお伺いした課題からきております。
プラグインからの拡張で危惧されている点はどういったユースケースでしょうか。

**Comment by konotakanobu** [comment]
横からすみません！
form_widgetやform_errors を使わないなら、そもそもなんでtwigなんだ論が出てきてしまう気が・・・
そもそものEC-CUBE3がそういう自由度落とす代わりにメンテナンス性とか拡張性を優先していると思いますので、そこを戻すのはちょっとリスキーな気が。。
あとデザイナー視点で言わせてもらうとtwigの時点でもう敷居高いのでw
むしろtwigでどうすれば上手くできるのかのドキュメントとかマニュアルを充実させる方がEC-CUBE 3にとっていい気がします！

**Comment by Yangsin** [comment]
@konotakanobu 
ご意見ありがとうございます。大きな見直しになりますので、積極的に声をいただきうれしです。
form_widgetやform_errorsを使わないことで、メンテナンス性や拡張性を大きく損なうと思われる点がありそうってことでしょうか？
EC-CUBEは２であれ３であれ、やはり独自性の高いサイトを作りたいお店に支持いただいており、特に直感的に独自性を表現するフロントのテンプレートは自由度の高さをもっと高めていきたいのです。

デザイナー視点で、twigというだけで敷居が高いとなっている点は、いろいろとお話お伺いしていくなかで、twigが「どうだから」というよりは、現在のテンプレートの作り。特にform周りと、CSSの組み方に影響をうけている印象をうけており、まずは form周りについて、Issueをたてさせていただきました。
もちろんドキュメントも充実させていきますが、触ろうとおもった時に新しく覚えることをすこしでも減らしていいとこ取りできないものかと悩んでおります

ちなみに、CSSの組み方については、別途Issueを立てますが、今のclassの命名や、bootstrapが中途半端になっている点を見直し、bootstarpのドキュメントを参考に、CSSとHTMLの知識をベースにがんばれるくらいまでもっていきたいと思ってます。

**Comment by ttsuru** [comment]
僕も使用しない場合は最悪な展開だと思います。できることをどこかでドキュメントにしておくのはいいと思いますが、デフォルトでform_widgetを利用しないのはメンテ性からも非常に悪いと思います。

**Comment by Yangsin** [comment]
@ttsuru 
ご意見ありがとうございます。皆さんのご懸念に私がおいついけてないのですが、form_widgetを利用することでメンテナンス性を高く感じられえている点や、逆に使わないと非常に悪くなると感じられている点をもうすこし教えてもらってもいいでしょうか。

form_widgetを使うか使わないかというよりは、フロントのテンプレート実装難易度を下げるためにtwigのコードから最終的なアウトプットのコードを把握しやすく、影響範囲を理解しやすい形にできるアイデアを募集してます。

**Comment by nobuhiko** [comment]
#587 から意見はかわっていなくて、Formはtwigをいじる必要ない状態が一番楽だと思っています。

**Comment by Yangsin** [comment]
@nobuhiko
ありがとうございます。
今のままだとformのちょっとしたラベルを変更するだけでもプラグインかform_typeにまでおりないといけないという状況なんですが、formの並びやラベルくらいはTwigで変えれるようにできないものでしょうか。

**Comment by ttsuru** [comment]
@Yangsin 
> 今のままだとformのちょっとしたラベルを変更するだけでもプラグインかform_typeにまでおりないといけないという状況なんですが

label は使わなくても大丈夫ですよ。何か `<label>なんたら</label>` と書くことに問題がありますか？
form_widget も個別のformのレンダリングは、それぞれ変更可能です。

**Comment by ttsuru** [comment]
思ったのですが、 `form_widget` で本当にシンプルな `<input>` をだすthemeを同梱してはどうでしょうか。
使いたい方がそれを使えばどうでしょうか。

**Comment by chihiro-adachi** [comment]
実装してみての所感としては、開発者からすると少なからずデメリットもありそうです。

- html/cssを意識する必要がでてくる
- 表示やエラー出力の制御を実装しないといけない
- 純粋に記述量が多くなり、メンテナンス性が落ちる
- formのhtmlが統一されないので、プラグインから拡張する際にデザイン崩れは発生しやすくなると思われる

あたりでしょうか。

逆にデザイナーさん・コーダーさんからすると、twigやform type、form themeなどの制約を考える必要がなくなるので、デザインの自由度は上がりそう(コーディングの難易度は下がりそう)、とは感じます。

最小限のinput タグのみを出力するform theme があれば、もう少しバランス取れるような気もするので、一度検証コード作成してみます。

**Comment by chihiro-adachi** [comment]
最小限のform themeで実装したらどうなるか、のサンプルを作成しました。
https://github.com/EC-CUBE/ec-cube/compare/master...chihiro-adachi:exp/twig-simple

- form themeは、form_div_layout.html.twigを使用
- 汎用的なform_errors, form_labelと、確認画面用にchoice_widget のみ独自定義
- bootstrapのクラス(form-control)は attrで指定
- freeze/freeze_display_textは使わず, `form.xxx.vars.data`での表示と, form_widgetのtype:hidden指定で出力
- AddressTypeやNameTypeなど共通化されているものは、一括ではなく個別にレンダリング

ような実装を行っています。

所感としては

- html/cssの調整も現状よりは行いやすい
    - おそらくbootstrap以外のデザインでも適用できるはず
- formのレンダリングは個別に行うほうがよさそう
    - デザイナさん、コーダさんにform themeを意識させなくて済む
- 記述量もform_widget使わない版と比較してそこまで増えない
    - form_widget使わない版は書いてて辛い

というところでしょうか。
冗長な部分もありますが、まだこちらのほうがデメリットは少ないかと感じます。

**Comment by chihiro-adachi** [comment]
こちらの方針通り、4.0ではテンプレートを実装しています
https://github.com/EC-CUBE/ec-cube/issues/2033#issuecomment-273428771
