### ISSUE TITLE
validator.xx.yml

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2036]
ValidatorServiceProviderは@deprecatedになっていますが、validator.xx.ymlはどうなるんでしょうか？

いかにもなファイル名なのに記述内容が一切利用されておらず、「このファイルに追記したのに文言が変わらない何故？」と勘違いされる方が少なからずいらっしゃいます。

全てのメッセージがmessage.xx.ymlに記述されている現状を維持するなら、validator.xx.ymlは削除してしまったほうが紛らわしさ回避になると思うのですが…。

**Comment by chihiro-adachi** [comment]
@izayoi256 
Symfonyのバリデーションエラーのメッセージは以下で定義されていますが、標準の翻訳文言が少しわかりづらく、上書きするために`validator.ja.yml`を置いた、というのが経緯です。
https://github.com/symfony/validator/blob/master/Resources/translations/validators.ja.xlf

単純に削除すると、NotBlankのエラーメッセージが`空であってはなりません`と表示されます。
もう少しスマートなやりかたがあればよいのですが...

**Comment by izayoi256** [comment]
@chihiro-adachi 
https://github.com/EC-CUBE/ec-cube/pull/484 この辺りでしょうか。本件については仕様ということで理解しました。ありがとうございます。
validator.ja.ymlにコメントで一言あると分かりやすいかもしれませんね。
