### ISSUE TITLE
【管理画面】【売上集計】月度集計時の年月日の選択が必要となっている。

### ISSUE THREAD

**Issue by kk580923** [EC-CUBE/ec-cube#2037]
【管理画面】【売上集計】月度集計時の年月日の選択が必要となっているので、年月の選択とする。

**Comment by chihiro-adachi** [comment]
@kk580923 
売上修正プラグインのissueかと思いますので、以下に作成しました。
https://github.com/EC-CUBE/sales-report-plugin/issues/33
