### ISSUE TITLE
パラメーター管理：mtb_constansの見直し

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#205]
## 見直し内容  

* 3になって不要になるパラメーターの精査
* マスターをシンプルにする（mtb_constants_init.phpの廃止）
  - mtb_constsntsのみがマスター（DBがマスターとする）  
* ポリシーにそって定数以外は分離していく

### ポリシー  
* サーバー・ホスティング環境に依存するものはconfig.yml
* ルーティングに利用しているものは不要
* パス類でまだ必要なものはpath.yml(仮称）などでまとめる
* ログ出力はmonologに渡しやすいように、log.yml(仮称）に別まとめにする  
* 店舗機能設定や業務ロジックの制御は、BaseinfoやPointで実装する
  + ただし店舗に簡単に変更させたくないもの（1ポイントの単価など）はconstantにおく
* 通常価格・販売価格のようなラベルはView もしくは言語ファイルに任せる
* 配送料金などTRUEが標準と考えられるものは標準仕様としてパラメーターは無くす

**Comment by chihiro-adachi** [comment]
mtb_constantsの精査結果を以下に保存しています。
https://docs.google.com/a/lockon.co.jp/file/d/0B9GUvngXP1KGSU1lUkRlYXVDR0U/edi

t

**Comment by k-yamamura** [comment]
EC-CUBEとしての定数をeccube.ymlとして新たに作成して定義したいのですが。
例えば、有効(1)、無効(0)とかを表す定数をeccube.ymlとして定義しておき、
それ以外で変更される値についてはmtb_constantに定義するという方法です。

アプリケーションとして変更されたら絶対にダメという値です。

**Comment by chihiro-adachi** [comment]
以下仕様ですすめられればと思います。

* src/Resouce/config/constant.ymlをマスターとする
   + mtb_constant上には保持しない.
   + 変更は不可とする.
* 変更したい場合や独自定義を行う場合, app/config/constant.ymlに定義する
   + こちらで定義された内容でマスタを上書きする.
   + パラメータ管理は上記ファイルの生成/更新を行う
* path.ymlおよびlog.ymlはconfig.ymlに統合.
   + ファイルは分けず, config.yml内に定義(ただしlog: xxx, path: xxxのように階層分ける)
   + ※install.shから生成する必要あるため
* 削除フラグ等の定数値
   + src/Eccube/Common/Constant::VERSION = 3.0.0-beta3 ※Applicationが適切か
   + src/Eccube/Common/Constant::TRUE/FALSE = 1/0 ※ホントのtrue/falseしたい場合はtrue/falseつかう
   + src/Eccube/Common/Constant::ENABLE/DISABLE = 1/0

以下の切り分けを想定しています。
1. 公開ステータスや税別など業務的に変更されたらダメな定数値(テーブルとして存在するもの)
2. 削除フラグなどのシステム的に統一されて使用される定数値
3. 文字数などのデフォルトで定義されているが別に変更されても問題ない定数値

1および3はconstant.ymlに定義する
2はConstantsに定義する

**Comment by chihiro-adachi** [comment]
実装内容を以下にまとめます。

# configファイル一覧
| ファイル     | 設定内容             | 備考                                      |
|--------------|----------------------|-------------------------------------------|
| config.yml   | ユーザ変更不可の設定 | auth_magicなど                            |
| database.yml | DBサーバの設定       | configから分離                            |
| mail.yml     | メールサーバの設定   | configから分離                            |
| path.yml     | パス関連の設定       | アプリケーション内で利用するパス変数。    |
| constant.yml | ユーザ変更可能な設定 | 旧mtb_constants。ユーザが設定を変更できる |

# 定数の取り扱いについて

1. 公開ステータスや税別など業務的に変更されたらダメな定数値
    + 変更を許容しないもの
        + エンティティで定数として定義(Eccube\Entity\PageLayoutなど)
    + カスタマイズによる変更が想定されるもの(受注ステータスなど)
        + constant.ymlに定義
2. 削除フラグなどのシステム的に統一されて使用される定数値
    + src/Eccube/Common/Constant.phpに定義.
3. 文字数などのデフォルトで定義されているが別に変更されても問題ない定数値
    + constant.ymlに定義する

# constant.ymlの取り扱いについて
+ src/Resouce/config/constant.yml.distをマスターとする
    + mtb_constant上には保持しない
    + 上記ファイルの変更は不可とする
+ 変更したい場合や独自定義を行う場合, app/config/constant.ymlに定義する
    + こちらで定義された内容でマスタを上書きする.
    + パラメータ管理は上記ファイルの生成/更新を行う
+ 削除フラグ等の定数値
   + src/Eccube/Common/Constant::VERSION = 3.0.0-dev
   + src/Eccube/Common/Constant::TRUE/FALSE = 1/0
   + src/Eccube/Common/Constant::ENABLE/DISABLE = 1/0
