### ISSUE TITLE
キーワード検索において、SQLエラーが発生する。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2051]
環境依存の問題のようです。
情報元ページ：http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=18435&forum=2&post_id=79797#forumpost79797

**Comment by izayoi256** [comment]
私が作業した https://github.com/EC-CUBE/ec-cube/pull/1797 によるものですね…。
半角全角英数字の検索対応のためにCOLLATE utf8_unicode_ciにしてあります。

**Comment by t-nagahashi** [comment]
@izayoi256 さん
修正方法はありますでしょうか？

**Comment by izayoi256** [comment]
@t-nagahashi 
調査が必要ですが、現在のリソースの都合上すぐには対応できない状態です。カゴヤ環境が手元にないため環境の再現が必要なことも踏まえると、2月に入ってしまう見込みです。
緊急度高めの判断、かつすぐに分かる方がいらっしゃらなければ、一旦当該機能を無効化(COLLATE utf8_unicode_ciを削除)していただいた方がいいかもしれません。

**Comment by trebla-on** [comment]
エラーなって流は以下のファイルに
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Doctrine/ORM/Query/Normalize.php#L55
COLLATE utf8_unicode_ci追加になったから

カラムタイプテキストの時CharsetとCollation設定できますが設定されてない場合はグロバールのCharsetになります。
こちらの問題はカラムタイプはテキストではないと思います、blobなってるかもしれません、
それを確認のために以下のSQLクエリー結果を確認したいです
SHOW CREATE TABLE dtb_product; 

多分dtb_product.nameかdtb_product.search_wordカラムはblobなってると思います

**Comment by trebla-on** [comment]
対応は何個かあります
■　カラムのCharsetはutf8の時だけ｛COLLATE utf8_unicode_ci｝を使うことができます。
　毎回カラムは正しかどうかチェックよくないですので例外あった時エラーパースして対応方法書くなか？
■　SELECTの時COLLATE使わない方が、インストールの時確認が必要

**Comment by tao-s** [comment]
すいません、コード確認してないんですが最初のインストール時にカラムの照合順序を指定していないって事ですか？

**Comment by chihiro-adachi** [comment]
@tao-s 
インストール時は以下が指定されているはずですなのですが、環境によってはうまく行かないのかも知れません。
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/config/database.yml.dist#L9

**Comment by ryo-endo** [comment]
#2092 の対応で、該当環境(カゴヤ様)でも、問題発生しないことを確認しました。
master反映したのでCLOSEします。
