### ISSUE TITLE
送料無料の除外条件

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2059]
複数配送時でも、送料無料条件の金額を越えると送料無料になってしまう。
単一配送の時は良いのですが、複数配送になると店舗の負担が増えるので、除外条件を設定できるようにしたい。

- 複数配送の場合は除外
- 商品別送料設定は除外
- 離島扱いの住所の場合は除外など

**Comment by okazy** [comment]
以下の仕様でどうでしょうか。
- 複数配送の場合
  - 配送先の配送方法ごとに送料無料条件の判定をする
    - 例：配送無料条件5000円以上の設定で
    - Aに6000円分、Bに4000円分配送する場合はAのみ送料無料になる

**Comment by okazy** [comment]
4.0系では配送先ごとに送料無料条件が適用されるようになりました。
