### ISSUE TITLE
会員登録の項目見直し

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#206]
会員登録の項目を一部見直します。

他にご意見あれば。こちらまで。

## 見直し案

Update:2015/5/26 10:27

|項目名|必須|変更内容|
|------------|----------|-----------------|
|お名前 | 必須 | 変更なし |
| お名前(フリガナ) | 必須|変更なし|
| 会社名 | 必須でない|変更なし|
| 郵便番号 | 必須|変更なし|
| 都道府県 | 必須|変更なし|
| 住所1 | 必須|変更なし|
| 住所2 | 必須|変更なし|
| 電話番号 | 必須|変更なし|
| FAX | 必須でない|変更なし|
| メールアドレス | 必須|変更なし|
| 性別 | 必須でない|必須をやめる|
| 職業 | 必須でない|変更なし|
| 生年月日 | 必須でない|変更なし|
| 希望するパスワード | 必須|変更なし|
| メールマガジンの送付について |必須 |受け取る/受け取らないのみにする|
|利用規約への同意|必須| 規約画面との統合により追加|

### 廃止項目
+  モバイルメールアドレス → フィーチャーフォン非サポートのためデフォルト不要と判断
+  パスワードを忘れた時のヒント → メールでの認証のみとする別途、パスワードリマインダーの仕様を起こす

**Comment by nobuhiko** [comment]
FAXは必須ですか？

**Comment by Yangsin** [comment]
フォローありがとうございます。FAXが必須は間違いでしたのでアップデートしました。

**Comment by Yangsin** [comment]
パスワードを忘れた時のヒント も廃止しようかと思っていますが、何かご意見ありますでしょうか。

パスワードを忘れた方へで、そのまま画面にパスワードをだすのを廃止して、かならずメール送信を行う。
メール送信タイミングでパスワードをリセットするのではなく、確認用のメールを送ってから、メールからのActivateKey的なもので、パスワードをリセットする仕様にする。
という仕様変更で、パスワードを忘れた時のヒントより良いかと。

**Comment by seasoftjapan** [comment]
モバイルメールアドレスは、既に削除済みということでしょうか?

**Comment by aminotsukasa** [comment]
過去のEC-CUBEにどういう経緯で"パスワードを忘れた時のヒント"なる機能が入ったのかはよく知らないのですが、個人的にはこの機能は廃止すべきだと思っています。

http://it.srad.jp/story/15/05/22/0624243/
パスワードのヒント機能はもう破綻しているという意見があり、これに同意します。

ちなみに、個人的にはパスワードのヒントの入力を求められた場合、ペットの名前や母親の旧姓などは今までどこで何回話したものか見当もつかないため、必ず
php -r 'echo sha1(openssl_random_pseudo_bytes(1024));'
の戻り値を設定しております。

**Comment by Yangsin** [comment]
@seasoftjapan 
モバイルのメールアドレスについて、言及していませんでしたが  
デフォルトではフィーチャーフォンをサポートしないのため、モバイルとPCのアドレスそれぞれ登録する必要はなく、削除でいいかと思いますが、ご懸念などありますか？

@aminotsukasa 
ご意見ありがとうございます。  
やはりそうですよね。  
廃止で進めます。パスワードリマインダーの仕様も別途おこしますね。

**Comment by seasoftjapan** [comment]
@Yangsin 良いと思います。

**Comment by Yangsin** [comment]
@seasoftjapan ありがとうございます。

#229 であらためて実装していきます。

**Comment by Yangsin** [comment]
実装にすすみますので、こちらでの検討は終了。クローズします。
もしなにか追加があれば #229 にて。
