### ISSUE TITLE
配送先選択のエラー画面でブロックが一切読み込まれません。

### ISSUE THREAD

**Issue by pn-yu-n** [EC-CUBE/ec-cube#2062]
お世話になります。

商品をカートに入れ、配送先を選択する画面にて、問題が発生いたしました。
お支払方法を選択するラジオボタンに何もチェックが入っていない状態で注文確定ボタンを押し、当然必須項目不足のエラーになりますので https://ドメイン/shopping/confirm にアクセスすると、本来表示されるはずのショップロゴやサイドバーなどのブロック要素が一切表示されません。
こちら http://demo3.ec-cube.net/ のデモサイトにて、ブラウザの検証モードから意図的にラジオボタンのチェックを外して確定を押しても同じ現象が発生いたしました。
回避する方法などがあれば、ご教示をお願いします。

環境は、下記です。
ECCUBE：3.0.12-p1
PHP：5.5.15
よろしくお願いいたします。

**Comment by t-nagahashi** [comment]
EC-CUBE標準では発生し得ないですが、
プラグインを使用した場合に、プラグインで追加されたバリデーションエラーに引っかかると同様の問題が発生すると思います。
別issueとして、たてさせていただきました。
https://github.com/EC-CUBE/ec-cube/issues/2063

対応がお急ぎのようであれば、
コミュニティサイトよりご質問いただければ、
他開発様から回避策等のアドバイスが頂けるかもしれません。
http://xoops.ec-cube.net/
