### ISSUE TITLE
注文確定時バリデーションエラーが発生した場合、ヘッダー等が消えてしまう。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2063]
■発生画面
購入確認画面（http://demo3.ec-cube.net/shopping）
■再現方法
お支払方法の選択をブラウザの開発者モードでクリアする。
「注文する」ボタンを押下。
→ ヘッダーが消えた状態で画面が再描画される。
（URLは、http://demo3.ec-cube.net/shopping/confirmとなる。）
■補足
本体の機能だけでは発生しないが、プラグインの使用を考慮すると発生する問題です。
（プラグインにて、バリデーション項目を追加すると発生する）

元issue：https://github.com/EC-CUBE/ec-cube/issues/2062

**Comment by trebla-on** [comment]
問題見つけました。
注文バーリデト失敗した場合は「/shopping/confirm」にリダイレクトを行います
ページ情報はこちらで取得する
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Application.php#L376
条件は「url = shopping_confirm）」
dtb_page_layoutのテーブルを見るとこんなレーコドがありません。

対応は何個かありますが先に使用確認したいです
１．shopping_confirmはshoppingと同じ場合はリダイレクトurlは「/shopping/confirmから/shoppingに」変更
２．レーコド見つかれなかった場合はnewPageLayoutメッソドを呼びに聞きますその新規レコードのフッターとヘッダを直す？
```
$PageLayout = $app['eccube.repository.page_layout']->newPageLayout($DeviceType);
３．dtb_page_layoutテーブルにshopping_confirmレーコドを追加する
```

**Comment by chihiro-adachi** [comment]
@trebla-on 

3でお願いします。
対応方法は以下が参考になるかと思います。

#1685 #1700

**Comment by trebla-on** [comment]
>3. dtb_page_layoutテーブルにshopping_confirmレーコドを追加する
新規レコド追加するようにのmigratingクラスを作成しました
https://github.com/EC-CUBE/ec-cube/pull/2135

**Comment by ryo-endo** [comment]
こちら #2135 で対応完了しました。
