### ISSUE TITLE
インストール時、オフライン環境においてローカルで保持しているJSファイルを参照するように変更

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2068]
refer:http://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&order=ASC&topic_id=18558&forum=14

■再現方法
インストール時、オフライン環境において「オプションを表示」でメニューを表示させることができないため、その対応。
■問題点
インストール時、オフライン環境においてネットワーク上からJSファイルを取得できないため発生。
■対象画面
インストーラ画面
■対応方法
GoogleのJSを見に行っている箇所に関して、
オフライン環境の場合は、自前で持っているJSを参照しにいく。
（管理画面/フロント画面と同様の動きとする）

**Comment by ryo-endo** [comment]
#2130 で対応完了しました。
