### ISSUE TITLE
プラグインジェネレータコマンドの修正

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2069]
#2061 のPullRequestに関して整理した情報です。

■概要
以下１件の[動かない機能]と、[軽微な修正数件]が存在。
[動かない機能]
　プラグインgenerate時、symfonyイベントを追加した場合、プラグインの有効化のタイミングでエラーが発生する。
[軽微なbug数件]
　後述。
■詳細情報（不具合内容、解決方法を記載）
以下、生成されるプラグインのコードベースで、不具合ポイントを列挙。
（実際のコードは添付ファイルを参照ください。）

------------------------------------------------------------------------------------------

1.プラグインgenerate時、symfonyイベントを追加した場合、プラグインの有効化のタイミングでエラーが発生する
　Symfonyイベントの引数が間違っているたため発生（EC-CUBEフックポイントと同じになっている）
　→ 「Event.php」に出力される関数の引数を修正
　例）
　　修正前：public function onAdminRequest(EventArgs $event)
　　修正後：public function onAdminRequest(GetResponseEvent $event)
2.生成される全PHPファイルのauthorが「プラグイン名」となっている。
　→ 「author」となるよう変更
　例）
　　修正前： * Copyright (C) 2017 testPlugin
　　修正後： * Copyright (C) 2017 t-nagahashi
3.index.twigが、管理画面用のconfig.twigと同じソースが出力されている
　→フロント画面で使用する用のテンプレートに修正
4.TestPluginServiceProvider.php内のURL定義の一部に変数が使用されている。
　→ 本来は、テキストで出力すべきだったので、プラグインコードに修正
　例）
　　修正前：[lower_code]
　　修正後：testPlugin
5.generate時の出力コメント修正
　変更前：[+]Please enter Plugin Name (only pascal case letters numbers are allowed)
　変更後：[+]Please enter Plugin Code (First letter is uppercase alphabet only. alphabet and numbers are allowed.)
6.「Event.php」内の関数のdocCommnetがなかったため追加

------------------------------------------------------------------------------------------

[修正前後のスケルトンプラグイン.zip](https://github.com/EC-CUBE/ec-cube/files/746685/default.zip)

**Comment by ryo-endo** [comment]
https://github.com/EC-CUBE/ec-cube/pull/2061 で対応マージ済み。
