### ISSUE TITLE
開発環境と本番環境の設定ファイル(config.yml等)について

### ISSUE THREAD

**Issue by amidaike** [EC-CUBE/ec-cube#207]
Symfony2では異なる環境ごとでそれぞれの設定ファイルが扱うことができます。
http://docs.symfony.gr.jp/symfony2/cookbook/configuration/environments.html#index-1

DBの接続情報は本番環境と開発環境では異なる事が多いと思いますので、
EC-CUBEでも開発環境であれば
config_dev.yml
というようなファイルを用意して分けて使えるようにしてくれればありがたいです。

EC-CUBEのインストール時には本番環境の設定を行い、
開発環境では開発者がconfig_dev.ymlを作成して書き換えれば良いかなと思います。

一度ご検討ください。

**Comment by Yangsin** [comment]
:+1: 
不勉強ですみません。
その場合、今アクセスしている環境がdevだとかprodだとかはどこで設定することになりますか？

今のReadmeにかいているデバックモードと同じわたしかたになるのでしょうか？

**Comment by amidaike** [comment]
今のReadmeに書いているようにdevが設定されていれば
config_dev.ymlを参照し、
devと記述されていなければconfig_dev.ymlが存在していても無視されます。

**Comment by ttsuru** [comment]
たしかにenvごとに設定ファイルを追加で読んでくれると便利ですよね

**Comment by Yangsin** [comment]
そうですか。
本題とははずれますが、index.php にデバックのために、配列でevnをいちいち書き足す以外に何かいい方法はないかなと思っていたのですが、なさそうですね。   
すこしでも環境切替楽にするには
デフォルト prod  して、配布するくらいがいいんでしょうか？

```php
<?php

require_once __DIR__.'/../vendor/autoload.php';

$app = new Eccube\Application(array(
    'env' => 'prod',
));
$app->run();
```

お二人は .gitignore にしてたりとかしますか？

**Comment by amidaike** [comment]
Apacheの設定ファイルに
SetEnv ECCUBE_ENV dev
と記述したり、ユーザの環境変数設定ファイルにbashであれば
export ECCUBE_ENV=dev
と記述して、
```
$app = new Eccube\Application(array(
   'env' => isset($_SERVER['ECCUBE_ENV']) ? $_SERVER['ECCUBE_ENV'] : 'prod',
));
```
としていました。
ただ、環境切替の方法は今の方法から変更すると聞きましたのでそれに合わせるようにします。

**Comment by Yangsin** [comment]
#205 のほうに記載させていただいていますが、constant は、パラメーター管理のテーブルから生成される、サーバー環境に依存しないショップの機能設定のようなものに限定したいと思っています。
サーバー環境に依存するものをconfig.ymlやlog.yml として分けようとおもってますので、とりいそぎは config.yml を環境ごとに読み分けるだけでいかがでしょうか。  

環境設定の方法は、Apcheの設定ファイル等いじれないような方でも、デバックモードで確認したい場合などを想定して、実装を考える必要がありますが、うまい感じが思いつかないですね・・・
2.13までは管理画面＞システム管理＞パラメーター設定 でデバックモードのOn/Offができるようになっていました。

**Comment by nanasess** [comment]
#209 は、ぜひ欲しいです。 SimfonyProfiler を無効にしたくて、ぐぐったら config_dev.yml に書いたらいいよ的なことがでてきて、書いてみたけど反映されないといった哀しい事案を減らしたいです。

**Comment by ttsuru** [comment]
:+1:

**Comment by amidaike** [comment]
#209 ですがconstant_dev.ymlを読み込まない様にソースの修正を行いました。
config_dev.ymlのみ読み込みます。
インストール時にconfig_dev.ymlを標準で用意するかどうかは検討する必要がありますが。

**Comment by ttsuru** [comment]
@amidaike 
array_replace_recursive を利用されているようですが、mergeで良いかなと思いました。
上書きしたい場合にはキーごと置き換えで良いような気もしますがどうでしょうか。

**Comment by amidaike** [comment]
array_replace_recursiveを使用している理由ですが、
array_mergeだけの場合、
```
database:
    dbname: eccube_dev
```
とdbnameしかconfig_dev.ymlに記述されなかった場合、
```
{"driver":"pdo_mysql","host":"127.0.0.1","dbname":"eccube_dev","port":3306,"user":"root","password":"root","charset":"utf8"}
```
と設定されて欲しいところですが多次元配列のため、
```
{"dbname":"eccube_dev"}
```
しかdatabaseには値が設定されません。
同様にarray_merge_recursiveの場合、
```
{"driver":"pdo_mysql","host":"127.0.0.1","dbname":["eccube","eccube_dev"],"port":3306,"user":"root","password":"root","charset":"utf8"}
```
とecdube_devがdbnameのvalueとして追加されます。

それらを回避するために
array_replace_recursive
を使用しています。

config_dev.ymlに
```
database:
    driver: pdo_mysql
    host: 127.0.0.1
    dbname: eccube_dev
    port: 3306
    user: eccube
    password : eccube
    charset: utf8
```
と記述すれば済む話なので、
config_dev.ymlに記述するには階層のあるパラメータ(databaseやmail等)は
全て記述するというルールにすればarray_mergeで問題ありません。

**Comment by nobuhiko** [comment]
https://github.com/deralex/YamlConfigServiceProvider
こんなん見つけました
こちらも実装はarray_replace_recursiveですね

**Comment by amidaike** [comment]
開発環境の切り替え方法ですがSymfony2のように、
index_dev.php
みたいなファイルを用意して、
開発時は、
http://localhost/index_dev.php/mypage
でアクセスし本番時は、
http://localhost/mypage
というように開発時はindex_dev.phpを付加する方法であれば、
わざわざenvを設定する必要がなくなりますがいかがでしょうか。

http://docs.symfony.gr.jp/symfony2/quick_tour/the_big_picture.html#quick-tour-big-picture-environments

実装可能かどうかまでの検証は全く出来ておりませんし、
この方法が適切かどうかは微妙ではありますが。

**Comment by shinichi-takahashi** [comment]
@amidaike 
どうせならファイルを用意するのではなく `/dev` はじまりでアクセスしたらdev環境になるようにした方がきれいかなーと思うんですが難しいでしょうか。

**Comment by ttsuru** [comment]
@shinichi-takahashi  
僕も @amidaike なんの方が良いかと思います。
/dev で始めた場合にdevにすると、routingで追加することになりませんか？

**Comment by shinichi-takahashi** [comment]
@ttsuru 
リリース時削除する前提ならそれでいいと思います。
開発用として使うソースがパッケージに残るのだけ避けたいです。

**Comment by ttsuru** [comment]
@shinichi-takahashi 

Symfony の場合はIPで制限をかけています。
何かしらfail safeは必要だと思います。

**Comment by shinichi-takahashi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/209 にて対応していただいたため、本件クローズいたします。
