### ISSUE TITLE
EC-CUBEスタイルガイドラインの作成

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2075]
## 概要(Overview)

テンプレートのデザイン修正をわかりやすく、シンプルにするため。
EC-CUBE 3のフロントテンプレートのスタイルガイド制作を行う。
BootstrapやOnsen UIなど様に、スタイルガイドを見ながらテンプレートを修正したり、拡張したり出来るようにしていきたい。

## 期待する内容(Expect) 

+ Bootstrapをすべて採用しBootstrapのドキュメントからコピペで利用できるようにする。
  - 3.0では、Bootstrapが一部のみ採用されていたためコピペで持ってこれないものがあった。
+ EC-CUBE独自のclass についてPrefixを設けわかりやすくする
  - 3.0では、Bootstarpや他とEC-CUBEオリジナルのCSSのクラスやIDの命名規則が混在し、カスタマイズ時に理解しづらい状態になっていため
+ スタイルガイドラインを先行し、各要素をコンポーネント化していき、コピペで再現可能な様に組み直す。
  - 3.0では、CSSが親子関係をもっているなどにより再利用が難しくなっていた
+ デフォルトはできるだけシンプルなテンプレートとする。
  - 3.0では、複数のブロック配置に対応したり、複雑なアクションを伴うために、ブロックのコードが複雑化してしまっていた。
+ スタイルガイドとして提供されておりコピペ利用可能なものとにわける
  - デフォルトのコードの複雑化をさけ、デフォルトでは利用されていないが、利用可能なコードをスタイルガイドとして提供する

## 関連情報 (Ref)

[Bootstrap](http://getbootstrap.com/)
[Onsen UI](https://ja.onsen.io/)

[スタイルガイド用リポジトリ](https://github.com/EC-CUBE/Eccube-Styleguide)
[本体組み込み用ブランチ](https://github.com/EC-CUBE/ec-cube/tree/experimental%2Fstyleguide)

**Comment by tao-s** [comment]
プレフィックス付けるんじゃなくて、cssファイル分けて欲しいです。
それかsassファイル同梱して、sass分けるとか

**Comment by Yangsin** [comment]
@tao-s ファイルレベルでもわけたうえで、prefixもつけておくほうがHTML側から探しやすそうな印象だけどどうでしょう？
sassも本体のメンテナンスを考えるとあったほうが楽がきがしてるんですが、カスタマイズするときの需要はどうなんでしょう。

**Comment by shinichi-takahashi** [comment]
ベンダープレフィックス賛成です。
sassは複数ファイル、ビルドしたらひとつのcssファイルとなるようにするとモダンかなーと。
今ならwebpack2がでたのでビルドはwebpackをおすすめします。

**Comment by ttsuru** [comment]
Symfony だと Assetic が使い勝手もよかったです。

symfony.com/doc/current/assetic/asset_management.html

**Comment by Yangsin** [comment]
スタイルガイド自体は別リポジトリで保守していくことにして、本体にはビルドされたものを入れる形でいこうと思っています。
スタイルガイド用リポジトリ： https://github.com/EC-CUBE/Eccube-Styleguide
本体への組み込みは以下のブランチをつかって、いったん3.0のソースベースで組み込みすすめます。
https://github.com/EC-CUBE/ec-cube/tree/experimental%2Fstyleguide

**Comment by chihiro-adachi** [comment]
レポジトリ；https://github.com/EC-CUBE/Eccube-Styleguide
スタイルガイド：http://eccube3-styleguide.herokuapp.com/
ビルド方法やPR時の運用について：#2863 3582
