### ISSUE TITLE
4.0 リリース計画

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2076]
## 概要

4.0(旧3.n) リリース計画・リリース内容・計画のまとめIssueです
4.0のリリース計画について、検討中の事項をまとめていきます。
変更などあれば随時アップデートしていきます。

機能要望やご意見は新規にIssueを立てていただくか、関連するIssueがあればそちらにお願いします。

### スコープについて

+ カスタマイズの学習コストの低下を目指す
+ イレギュラーパターンにも対応しやすいプラグイン機構の改善を目指す
+ プラグイン間の依存関係を解決を目指す
+ リリース後に3.0からの移行方法（プラグインなど）を提供する

## システム要件

http://doc3n.ec-cube.net/quickstart_requirement

### コアの機構見直し

方針：  機能カスタマイズ性・デザインカスタマイズ性の向上

+ Silex  → Symfony3.4 にフレームワークのアップデート
+ 各種拡張APIの整備
+ プラグイン依存関係の整備
+  データ型変更
+ フロントテンプレートのコーディングルール整備
+ フロントテンプレートのスタイルガイドの提供
+ レイアウトグループによるブロックレイアウトの利便性向上

### 新機能・機能改善

方針： 運用者や購入者の利便性を高める

+ 受注・出荷関連機能の強化
+ デザイン管理の機能強化
+ タグ管理機能
+ カートの永続化 

### 管理画面UIの見直し

方針： 1280px程度の画面でも一覧画面での操作・検索性の向上
参考） プロトタイプ https://invis.io/5QE7O06WV#/249224959_------
+ デザインガイドの作成
+ ツールチップの導入（用語・用途の分かり辛いものを中心に）
+ ホーム画面のUI見直し

### 国際化対応

方針：多言語サイトや越境ECサイトのカスタマイズに対応しやすくする

+ 住所や会員情報を国際標準へ対応 
+ MessageIDに言語を切り出す 
+ 通貨の切り替え機構を追加 

## リリース時期

2018年 9月末

### EC-CUBE 4.0 RC
- コード凍結バージョン 
- 2018年 9月初旬を予定

### [EC-CUBE 4.0-beta](https://github.com/EC-CUBE/ec-cube/releases/tag/4.0-beta)
- 2018/8/6 リリース
- 4.0 対応プラグイン・周辺サービス開発者向け先行検証パッケージ

[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://dashboard.heroku.com/new?button-url=https://github.com/EC-CUBE/ec-cube/tree/4.0-beta&template=https://github.com/EC-CUBE/ec-cube/tree/4.0-beta)

### [EC-CUBE 3.n-α5](https://github.com/EC-CUBE/ec-cube/releases/tag/3.n-alpha5)
  - 2018/4/27 リリース
  - 管理画面UIのデザイン反映

### [EC-CUBE 3.n-α4](https://github.com/EC-CUBE/ec-cube/releases/tag/3.n-alpha4)
  - 2018/2/27 リリース
  - FW移行 (silex -> symfony)
  - 多言語切り替えの仮実装

### [EC-CUBE 3.n-α3](https://github.com/EC-CUBE/ec-cube/releases/tag/3.1.0-alpha3)
  - 2017/10/20 リリース
  - プラグインでComposerを利用可能に

### [EC-CUBE 3.1.0α2](https://github.com/EC-CUBE/ec-cube/releases/tag/3.1.0-alpha2)
  -  2017/5/19
  - デザインカスタマイズ性の向上
        - スタイルガイド適用
        - フォームヘルパーの見直し
        - デバイスごとにテンプレート/レイアウト切り替え
  - 出荷管理機能
  - 機能改善・拡張機構の実装
  - 詳細は[リリースノート](https://github.com/EC-CUBE/ec-cube/releases/tag/3.1.0-alpha2)を参照

### [EC-CUBE 3.1.0α](https://github.com/EC-CUBE/ec-cube/releases/tag/3.1.0-alpha) 
  - 2017/03/01 リリース
  - 機能カスタマイズ性の向上に関する機構の改善の先行実装[[詳細](https://github.com/EC-CUBE/ec-cube/issues/2127)]など
 
## 関連ドキュメント

+ ドキュメントサイト http://doc3n.ec-cube.net
+ 仕様関連Issue/PullRequest https://github.com/EC-CUBE/ec-cube/issues?q=label%3Adocument+milestone%3A4.0
+ フロントテンプレートスタイルガイド http://eccube3-styleguide.herokuapp.com/
+ プラグイン先行開発Q&A https://goo.gl/wkhVdp
+ 不具合改修状況 https://goo.gl/Y8Vp8F
+ 3.nドキュメント化に向けた情報や実装の参考にしたい情報 #3380
+ 開発進捗説明会スライド
    - 2018年3月 https://www.slideshare.net/ec-cube-official/clipboards/201803_ec-cube
    - 2017年10月 https://www.slideshare.net/ec-cube-official/clipboards/201710_ec-cube
    - 2017年6月 https://www.slideshare.net/ec-cube-official/clipboards/201706_ec-cube3-1
    - 2017年3月  https://www.slideshare.net/ec-cube-official/clipboards/201703_ec-cube3-1

**Comment by k-yamamura** [comment]
3.1に追加して欲しいライブラリです。

https://github.com/danielstjules/Stringy
https://github.com/cocur/slugify
https://github.com/filp/whoops

**Comment by Yangsin** [comment]
@k-yamamura 
ご意見ありがとうございます。
ぱっと見た感じ、開発者向けにエラーをみやすくしたり、文字列変換のUtil的なものってイメージです。
どんな利用を見込んでのものになりますでしょうか？

**Comment by k-yamamura** [comment]
@Yangsin 
開発者時にエラー内容を見やすくしたいのと、文字列の扱いを簡単に扱えるようにしたいため利用したいです。

**Comment by nanasess** [comment]
ルーティング名をスラッシュ区切りにしたいです
https://github.com/EC-CUBE/ec-cube/issues/2111

**Comment by k-yamamura** [comment]
EC-CUBEインストール時に、

- サンプルデータのインストール

とJoomlaのようにサンプルデータの利用可否を選択できる機能が欲しいです。

### サンプルデータ対象例
- dtb_block
- dtb_block_position
- dtb_category
- dtb_class_name
- dtb_class_category
- dtb_delivery
- dtb_payment
- dtb_payment_option
- dtb_delivery_fee
- dtb_delivery_time
- dtb_delivery_date
- dtb_help
- dtb_news
- dtb_product
- dtb_product_category
- dtb_product_class
- dtb_product_stock
- dtb_product_image

**Comment by Yangsin** [comment]
@k-yamamura ご意見ありがとうございます。他の方のご意見もうかがえるように別途Issueをたてていただけると助かります。

**Comment by tao-s** [comment]
商品一覧とか商品詳細も全部ブロックにして、テーマから切り離して欲しい

**Comment by tao-s** [comment]
METAタグのタイトルとdescriptionは商品、カテゴリ単位で設定できるようにして欲しい

**Comment by Yangsin** [comment]
@tao-s レイアウト系の要望色々とありそうなので、Discussionスレッド用のIssue用意しました。 https://github.com/EC-CUBE/ec-cube/issues/2289

**Comment by Yangsin** [comment]
α2まで進めきたなかでのフィードバックとして、3.1というには非常に多くの変更を含むためバージョンの見直しを検討しています。
現状としては、3.nとさせていただきます。

また、α2リリース後に行った開発合宿で話あわれた内容をシェアしておきます。
https://docs.google.com/presentation/d/11ROpkm-NVHFyd61JAaOSN3g-l0noxQ8G9Yz85DPSf1A/edit?usp=sharing
これを参考にα3で3.nのスコープをフィックスさせます。

**Comment by Yangsin** [comment]
決定
・PHP5.5もサポートが切れており、関連のコンポーネントで3.nの環境から切り離す
検討
・PHP5.6も切り離すか？
・PHP7.0をスキップし、PHP7.1以上の対応に進めていくながれもありPHP7.1以降にするか？

**Comment by Yangsin** [comment]
管理画面のUI見直しを進めていきますのでIssueなど追加予定を更新。
タグについても専用の管理ページを用意する予定で更新

**Comment by nobuhiko** [comment]
504 件の規格の組み合わせで登録ができない。
エラーも出ないです。

**Comment by nobuhiko** [comment]
3.n をダウンロードしてみたのですが以下エラーですすめませんでした
PHP7.0.15 です

`php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 149 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.2.0): Loading from cache

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /ec-cube-3.n-alpha5/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 95
`

**Comment by Yangsin** [comment]
現在把握している不具合のリストを掲載しておきます。現状大量にあるのでIssueにおこしきれておりませんが、試されているかたで何かあればIssueと合わせ確認いただければ幸いです。
https://docs.google.com/spreadsheets/d/13QfVE1STE6RrAEJ1jMTNptzlyT0zHJjTDuWdNti4fwA/edit#gid=0
