### ISSUE TITLE
管理画面の受注登録・編集時の在庫の増減に関する仕様の変更

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2084]
## 概要

管理画面の受注登録・編集時の挙動について、2系と同様の挙動に変更する

## 2系と現行の3系の挙動比較

|アクション        |2系の挙動  |3系挙動     |3系見直し後の挙動|
|----------------|----------|-----------|-------------|
| 受注新規登録     | 在庫減る  | 減らない    | 減る        |
| 受注編集数量変更 | 在庫減る   | 減らない   |  減る        |
| 受注編集商品追加 | 在庫減る   | 減らない    | 減る        |
| 受注削除        | 在庫戻る   | 戻らない   |  戻る        |
| 在庫が0の商品   | 選択できない | できる    |  できない    |
| 非公開商品      | 選択できる  | できる    |  できる     |
>販売制限数、商品種別の各チェックは2系、3系ともに行わない

## 在庫処理で想定されるケース

* 管理者から受注登録する時に在庫を考慮するケース
在庫の整合性をあわせたいため減る事が望ましい

* 管理者から受注登録する時に在庫を考慮しないケース
在庫を店舗側で別途把握している、発注後に実際には商品を注文するなどの場合
在庫の増減には大きく影響を受けないため、在庫無制限で運用可能と想定

* 在庫がなくても緊急で受注登録したいとき
在庫を一時的に増やして対応する
その間にフロントから商品を購入される事が危惧さえるような場合は非公開で商品を登録するなどでも対応可能と想定

## 関連

受注管理での商品追加で、在庫の無い商品が追加可能 #1094
受注管理での商品追加で、在庫数が減らない #1095

**Comment by okazy** [comment]
4.0系ではキャンセルと返品のステータスを用意して在庫数の増減に対応しました。
以下がそのプルリクです。
#3325
