### ISSUE TITLE
プラグイン配下のテンプレートを参照するPageLayoutとBlock

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2086]
refs #2077 

PageLayoutについては上記PRで対応済みだが、Blockに関しても対応が必要と思われる。

**Comment by izayoi256** [comment]
例えばプラグインで追加したブロックのfile_nameが```SomePlugin/Resource/template/default/Block/block.twig``` だとしたら、app/template以下に複製されるファイルのパスは```app/template/default/Block/SomePlugin/Resource/template/default/Block/block.twig``` になる。

defaultやらBlockやらが二重に作られてしまってもいいなら、#2077 と同じ方法で実現は可能。

**Comment by izayoi256** [comment]
dtb_page_layoutのurlとfile_nameを、dtb_block.file_name一つで賄っている状態。

dtb_blockでもurlとfile_nameは分割すべき。さもないと```block_SomeTemplate/Resource/template/default/Block/block``` とかでbindする羽目になる。

**Comment by izayoi256** [comment]
```admin.content.block.edit.initialize``` イベントを使えば、プラグインのBlockのテンプレートをブロック編集画面で扱うことも可能。

**Comment by okazy** [comment]
現状の3.0系ではプラグインのブロックの読み込みの互換性を考慮すると、対応が難しいと考えています。
3.nでの検討事項とさせてください。
