### ISSUE TITLE
バリデーションエラーメッセージの拡張

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2087]
バリデーションエラーメッセージにlabelを含める方法が分からないという質問を多くいただきます。
下記のコードで実現は可能ですが、全てのメッセージを書く必要があるため、一旦issueとして上げます。
実装方法についてご意見があればお聞かせ下さい。

validator.ja.yml
``` yaml
This value should not be blank.: "{{ label is defined and label is not empty ? label ~ 'が' : '' }}入力されていません。"
```

bootstrap_3_horizontal_layout.html.twig
``` twig
{# 前略 #}
<p class="errormsg text-danger">{{ include(template_from_string(error.message|trans)) }}</p>
{# 後略 #}
```

**Comment by izayoi256** [comment]
twig以外でバリデーションメッセージを利用する場合、twigのタグがそのまま出てしまう問題は今思い当たりました。

**Comment by k-yamamura** [comment]
項目定義がですがめんどくさいですが、この方法で項目名を表示しています。
http://amidaike.hatenablog.com/entry/2017/01/18/105414

**Comment by izayoi256** [comment]
@k-yamamura 
項目定義の手間がある、「てにをは」が合わない、同じ名前で異なるlabelに対応できないといった問題があり、本体に実装する方法としては微妙な気がします。

**Comment by k-yamamura** [comment]
@izayoi256 
項目定義については全て定義すれば済むだけだと思いますが、
同じ名前で異なるlabelに対応できないとはどういう問題でしょうか。

**Comment by izayoi256** [comment]
@k-yamamura 
項目定義は、フォーム定義側と```message.ja.yml``` で二重に定義することになるか、あるいはフォーム定義側で```'label' => $app->trans('field_name')```とすることになりますね。あ、でも国際化対応を考えるならそれが正しいのかもしれません。

同じ名前で〜については、例えば```\Eccube\Form\Type\Admin\ProductType``` と```\Eccube\Form\Type\Admin\BlockType``` では、```name``` という共通の名前のフィールドが存在します。仮に
```yaml
name: 商品名
```
とした場合、ブロック登録画面で「商品名：入力されていません。」というエラーメッセージが表示されることになりませんか？

**Comment by Yangsin** [comment]
#2480 の修正で同様に対応ができていますのでこちらクローズします。
