### ISSUE TITLE
本体開発用のSlackの公開

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2099]
EC-CUBE の開発の意見交換や情報交換にSlackを用意しました。
以下よりご自身のメールアドレスに招待リンクを発行してご利用ください。
https://join.slack.com/t/ec-cube/shared_invite/enQtNDA1MDYzNDQxMTIzLTY5MTRhOGQ2MmZhMjQxYTAwMmVlMDc5MDU2NjJlZmFiM2E3M2Q0M2Y3OTRlMGY4NTQzN2JiZDBkNmQwNTUzYzc

[開発コミュニティ](http://xoops.ec-cube.net) も合わせてご利用ください。
個別のカスタマイズに関する回答や、EC-CUBE開発チームによる回答を保証するものではありません。

**Comment by Yangsin** [comment]
当面はテスト運用とさせていただきます。

**Comment by Yangsin** [comment]
こちら正式運用としています。
オフィシャルサイトの最新情報や開発コミュニティの投稿なども確認できるのでぜひご参加ください。
https://ec-cube-slack-invite.arukascloud.io/

**Comment by chihiro-adachi** [comment]
招待URLはREADME.mdに記載済のためクローズします。
