### ISSUE TITLE
Eccube-Upgrade-Fixerの開発

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2102]
# 概要
EC-CUBE 3.1でSymfony3系、Silex2系に置き換えることを検討している。
その際、プラグインなどの開発者がアップグレード対応をしやすいように、[Symfony-Upgrade-Fixer](https://github.com/umpirsky/Symfony-Upgrade-Fixer) をForkし、
[Eccube-Upgrade-Fixer](https://github.com/EC-CUBE/Eccube-Upgrade-Fixer)を提供

# 対象

+  アップグレードにともなってエラーになってしまう箇所の修正
+  プラグインの3.1対応を支援するものであり3.1対応を保証するものではない

## FormType

- [x] 名称をクラスに変更その1

        $builder->add('name', 'name')
        $builder->add('name', NameType::class)

- [x] 名称をクラスに変更その2

        $app['form.factory']->createBuilder('hoge');
        $app['form.factory']->createBuilder(HogeType::class);

- [x] 名称をクラス名に変更その2

        $app['form.factory']->createNamedBuilder('', 'customer_login');
        $app['form.factory']->createNamedBuilder('', CustomerLoginType::class);

- [x] `ChoiceType`の`choices`のキーを値を入れ替え

        $builder->add('gender', 'choice', array(
            'choices' => array('m' => 'Male', 'f' => 'Female')
        ));
        $builder->add('gender', 'choice', array(
            'choices' => array_flip(array('m' => 'Male', 'f' => 'Female'))
        ));

- [x] `EntityType`の`property`を`choice_label`に変更

        ->add('DeviceType', EntityType::class, array(
            'class' => 'Eccube\Entity\Master\DeviceType',
            'property' => 'id',
        ))
        ->add('DeviceType', EntityType::class, array(
            'class' => 'Eccube\Entity\Master\DeviceType',
            'choice_label' => 'id',
        ))

- [x] `EntityType`の`empty_value`を`placeholder`に変更

        'empty_value' => '指定なし',
        'placeholder' => '指定なし',

- [x] `CollectionType`の`type`を`entry_type`に変更

        'type' => '_shopping_shipment_item',
        'entry_type' => ShipmentItemType::class,

- [x] `empty_data`の削除
 - https://github.com/EC-CUBE/ec-cube/pull/1985/commits/4e4b980089744e52f7a3fe38856cb2e60f43e9ac

## ServiceProvider

- [x] extendの変更

        $this['translator'] = $this->extend('translator', function ($translator, \Silex\Application $app) {
        $this->extend('translator', function ($translator, \Silex\Application $app) {

- [x] shareの変更

        $app['eccube.service.system'] = $app->share(function () use ($app) {
        $app['eccube.service.system'] = function () use ($app) {

## 対象外
+ コーディング規約の変更など

**Comment by shinichi-takahashi** [comment]
> ChoiceTypeのchoicesのキーを値を入れ替え
第二引数が `ChoiceType::class` になります。
あとそろそろ `array()` は `[]` にしちゃってもいいんじゃないかなーって気がするんですがどうでしょう？

**Comment by nanasess** [comment]
> あとそろそろ array() は [] にしちゃってもいいんじゃないかなーって気がするんですがどうでしょう？

まとめてやってないだけで、開発中のブランチでは、手をつけたものから変更していってますよ〜

**Comment by izayoi256** [comment]
3.1でPHP5.3は動作対象外になるんでしたっけ？

**Comment by kiy0taka** [comment]
@shinichi-takahashi 
> 第二引数が ChoiceType::class になります。
ご指摘ありがとございます。これも「名称をクラス名に変更」で対応する予定です。

**Comment by Yangsin** [comment]
@shinichi-takahashi 

> あとそろそろ array() は [] にしちゃってもいいんじゃないかなーって気がするんですがどうでしょう？

ご意見ありがとうございます。
そうですね。Symfony3系のシステム要件で、PHP5.5以上になっていくるので対応可能そうですね。
ここでのスコープとしては、コーディング規約を含めてしまうとややこしいので、別での検討項目としておいておきますね。

@izayoi256 

こちらのIssueの前提としては、Symfony3系へのアップデートを想定しているので PHP5.5.9 以上を想定しています。
https://github.com/symfony/symfony/blob/3.0/composer.json#L18

**Comment by ghost** [comment]
当初はEC-CUBE4.0リリースに合わせてプラグインのマイグレーションのために開発していましたが、
予定していたより大きく変更が入ったため全てのコードの変換は難しいのでCloseします。

FormTypeの変換であれば、[Upgrade-Fixer](https://github.com/umpirsky/Symfony-Upgrade-Fixer)を使っていただくことである程度マイグレーションすることが可能です。
