### ISSUE TITLE
ルーティング名をスラッシュ区切りに変更

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2111]
## 概要(Overview)

`$app->path("shopping/complete") ` のような感じで、ルーティング名はスラッシュ区切りの方が直感的で、わかりやすいのではないでしょうか。
手元の環境では、スラッシュ区切りでも動作している模様

## 関連情報 (Ref)

Symfony や Silex のドキュメントでは、アンダーバー区切りになっている

- http://symfony.com/doc/current/routing.html
- http://silex-users-jp.phper.jp/doc/html/usage.html#named-routes

**Comment by ttsuru** [comment]
Routingがスラッシュ区切りだと、実際のパスとの違いで混乱するのではないでしょうか・・・

**Comment by Yangsin** [comment]
たしかに直感的な気もしますが、URLとNameが異なってくるケースはないのでしょうか？
SymfonyやSilexのドキュメントから外れることで、余計になぜEC-CUBEは変えてるのか？という事を気にさせてしまう気もするので、メリットとデメリットを見極めたいですね。

**Comment by nanasess** [comment]
単純に視認性の問題ですね。

**shopping/complete** をカスタマイズしたい時に、 `shopping_complete` が処理しているメソッドを探しだすのは困難です。
(ルーティングの仕組みを理解している Symfonyマスターなら簡単に探しだせるのかもしれませんが)
ルーティング名とパス名を極力揃えておけば、コントローラ内を grep するだけでよく、カスタマイズ箇所を見つけるのが楽になると思った次第です。

**Comment by ttsuru** [comment]
他のフレームワークでも `controler_action` の形式の命名が定番かと思います。
EC-CUBEではまだあまりみられませんが、postとgetでrotingを分けた場合に 
`user_edit_post` `user_edit_get` と `user/edit/post` `user/edit/get` であれば他の多くのフレームワークを見ても前者が採用されており、フレームワーク以上のEC-CUBE独自のルールが多くなる方が難しいと思います。

**Comment by okazy** [comment]
3.nではアノテーションでルーティングの設定をしているので、3.0より検索がしやすくなっています。
また、3.0と3.nで命名規則が微妙に異なると開発者が混乱することも予想されますので、3.nでは3.0同様に `_` での記載でいきます。
