### ISSUE TITLE
管理画面：カスタマイズした場合に、会員検索で__PHP_Incomplete_Classエラーが発生する

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#2112]
## 概要(Overview)

会員マスタで、都道府県を「兵庫県」で検索後、2ページ目に遷移するとシステムエラー
#1680 と同様の事象が発生する

## 再現手順(Procedure)

※ カスタマイズ環境のため、現状のmasterでは発生しない

前提：ページングができるデータ件数があること

- 会員マスタで、検索条件に都道府県「兵庫県」を選択して検索
- 検索結果の2ページ目に遷移する
- __PHP_Incomplete_Classのエラーが発生する

※他の都道府県を選択した場合は発生しない

### 環境 (environment)

+ EC-CUBE: 3.0.10
+ PHP: 5.4
+ DB:
  - PostgreSQL

## 関連情報 (Ref)

#1680 

## 修正案

エンティティを直接セッションに保持せず、POSTされたarrayを保持し、復元するように修正
http://qiita.com/tarokamikaze/items/b6cb73be0294fe6b14c1#13%E7%A2%BA%E8%AA%8D%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E3%81%A3%E3%81%A6%E3%81%A9%E3%81%86%E3%82%84%E3%81%A3%E3%81%9F%E3%82%89%E5%87%BA%E3%81%9B%E3%82%8B%E3%81%AE

**Comment by ryo-endo** [comment]
こちら #2113 で対応してmasterにマージしましたので、Issueを閉じます。
問題が継続して発生する場合は、またご連絡いただけたらと思います。
