### ISSUE TITLE
個別税率を設定した商品は、課税規則が常に「四捨五入」で計算されている

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#2114]
## 概要(Overview)
個別税率を設定した商品の場合、課税規則が常に「四捨五入」で計算されている。

※課税規則：税込み金額計算時の端数処理の方法（四捨五入,切り上げ,切り捨て）

## 期待する内容(Expect)  or 要望 (Requirement)

- 税率設定>共通税率設定の課税規則に連動する。

または

- 商品ごとに課税規則を設定できる。

## 再現手順(Procedure)

1. 基本情報設定>税率設定で、商品別税率機能を"有効"にする。
1. 税率一覧を編集し、課税規則を「切り上げ」に変更する。
1. 商品を作成する。  
・販売価格:123円  
・税率:1%
1. フロント画面から、作成した商品をカートに入れる。
1. 商品の金額が124円(123*1.01=124.23)になっている。⇒ 「四捨五入」になっている（NG）

### 環境 (environment)
+ EC-CUBE: 3.0.13
+ PHP: 7
+ DB:
  - MySQL 5.5.49-0ubuntu0.14.04.1

**Comment by ryo-endo** [comment]
まずは、
> 税率設定>共通税率設定の課税規則に連動する。

の対応かと考えております。

**Comment by kazumiiiiiiiiiii** [comment]
こちら、マージされましたので、クローズいたします。
#4189
