### ISSUE TITLE
appディレクトリやhtmlディレクトリを含まないテンプレートファイルアップロード時にフォルダを自動作成する

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2115]
## 概要(Overview)
テンプレートアップ時のapp, html, appディレクトリ配下のファイル有無による登録可否条件を変更します。

## 期待する内容(Expect)  or 要望 (Requirement)
・app. htmlディレクトリは必須
（app、htmlディレクトリが存在しない場合には作成を行う）
・appディレクトリ配下にFileがなくてもアップロード自体は可能

## 再現手順(Procedure)
[例１]
1.テンプレートアップロード画面を表示（admin/store/template/install）
2.以下状態のzipFileをアップロード
   「app、htmlディレクトリはあり。app配下にdirectoryとFileがない状態」
3.エラーが発生
→ エラーとならないようにする
[例2]
1.テンプレートアップロード画面を表示（admin/store/template/install）
2.以下状態のzipFileをアップロード
   「htmlディレクトリはあり、appディレクトリが存在しない状態」
3.エラーが発生
→ appディレクトリを自動で作成

### 環境 (environment)
+ EC-CUBE: 3.0.13
+ PHP: 5.5.9
+ DB:
  - SQLite version 3.8.2

## 関連情報 (Ref)
本issueのきっかけとなったissue
  https://github.com/EC-CUBE/ec-cube/pull/2100
  https://github.com/EC-CUBE/ec-cube/issues/1363

**Comment by ttsuru** [comment]
> 期待する内容(Expect) or 要望 (Requirement)

の部分で、

> app. htmlディレクトリは必須で必要とし、
> appディレクトリ配下にFileがなくてもアップロード自体は可能とする。 ←今回の修正点

とありますが、以下の方が実際の内容に則していると思います

app/ html/ ディレクトリが存在しない場合には作成を行う。  
app/ html/ ディレクトリ自体は必須。

**Comment by ttsuru** [comment]
それとも、実際に `html/` が不要なのでしょうか？

**Comment by t-nagahashi** [comment]
@ttsuru さん
確認ありがとうございます。

> それとも、実際に html/ が不要なのでしょうか？
appディレクトリと、htmlディレクトリはそれぞれ必須とするつもりです。

**Comment by t-nagahashi** [comment]
@ttsuru さん

> app/ html/ ディレクトリが存在しない場合には作成を行う。

この方が親切だと思いますし、ご提案いただいている仕様であわせようかと思います。

> app/ html/ ディレクトリ自体は必須。

こちらは同じ考えです。



なお、appディレクトリ配下にファイルもしくはディレクトリがないと登録できないので、
この問題もあわせて解消しようと考えております。

**Comment by ttsuru** [comment]
@t-nagahashi  
すいません、チケットの意図がどちらなのか読み取れなかったので、コメントさせていただきました。

どちらを意図とされているのか教えていただければと思います。

**Comment by t-nagahashi** [comment]
@ttsuru 
混乱させてしまい、すみません。
タイトル、仕様内容を書き換えました。
https://github.com/EC-CUBE/ec-cube/issues/2115#issue-208027510

**Comment by ryo-endo** [comment]
master取り込みました。
