### ISSUE TITLE
管理画面のページ管理を表示した時にタブレットサイズの幅だと項目がずれて表示される。

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#2126]
PCとスマホだと「レイアウト編集」が押せるがタブレットだと項目が1つずれて表示されているため押せなくなっている。

**Comment by t-nagahashi** [comment]
以下問題箇所です。
![2017-02-20_14h09_08](https://cloud.githubusercontent.com/assets/13776434/23112777/5cb364a8-f776-11e6-88c6-90daf6946bee.png)

**Comment by ryo-endo** [comment]
#2134 で対応済み。
