### ISSUE TITLE
新たなmetaタグを追加できるようにする

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#2128]
新規ページ作成時に定義可能なmetaタグとして、

- author
- description
- keyword
- robots

が定義可能だが、上記以外のmetaタグをページごとに追加する方法がないため、
` default_frame.twig `に新たに
```
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block metas %}{% endblock %}
<link rel="icon" href="{{ app.config.front_urlpath }}/img/common/favicon.ico">
```
と ` {% block metas %}{% endblock %}` を追加し、個別のtwigファイルからmetaタグを追加できるようにするか、

または、ページ管理から上記で定義しているタグ以外の項目を追加できるように、
`robots`項目の後にフリーエリアのような項目を用意し新たなmetaタグを追加できるようにする。

<img width="804" alt="2017-02-20 15 24 17" src="https://cloud.githubusercontent.com/assets/12592005/23114222/168def9c-f781-11e6-96d1-870113db79d5.png">

**Comment by trebla-on** [comment]
@t-nagahashi 
実装の前に仕様を確認したいです。
以下の項目追加したいと思います大丈夫でしょうか
■DBカラム追加
テーブル： ---- dtb_page_layout
カラム： ----- meta_tags
タイプ： ----- longtext
NULL可能： - YES

■フォーム項目追加
項目名：　フリーエリア
タイプ：　　テキストエリア
バーリデト：50文字以内のみ（robots、keyword、descriptionと同じ）

**Comment by t-nagahashi** [comment]
@trebla-on 
以下仕様で実装お願いできますでしょうか？


# 実現機能  
## 1:twigにブロックを追加  
{% block meta_tags %}{% endblock %} を追加し、個別のtwigファイルからmetaタグを追加可能にする  

## 2:ページ管理に、フリーエリアを追加  
ページ管理から上記で定義しているタグ以外の項目を追加できるように、  
robots項目の後にフリーエリアのような項目を用意し新たなmetaタグを追加可能にする  
 - DBカラム追加
テーブル： ---- dtb_page_layout
カラム： ----- meta_tags
タイプ： ----- longtext
NULL可能： - YES

 - フォーム項目追加  
項目名：　フリーエリア  
タイプ：　　テキストエリア  
バーリデート：300文字以内のみ（robots、keyword、descriptionと同じ）  
（複数のメタタグを入れることを許可したいため。  
　また、検索エンジンによっては1024バイトを超えるとよくないとのことなので、300文字上限とます。）  
placefolder：以下のように表示して下さい。
複数のメタタグを記述することが可能です  
(例)  
<meta name="copyright" content="著作権を入力してください" />  
<meta name="classification" content="webページのジャンルを指定してください" />

**Comment by ryo-endo** [comment]
#2148で対応を取り込みましたので、こちらCLOSEさせていただきます。
