### ISSUE TITLE
TOPページの在庫切れ数を、規格単位から商品単位に変更

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2131]
## 概要(Overview)
TOPページに表示されている「在庫切れ数」を、規格単位から商品単位に変更する。

## 再現手順(Procedure)
 - 前提  
以下商品を登録する。（B-1,2,3は商品規格）  
商品A（在庫数:1）
商品B-1（在庫数:0）
商品B-2（在庫数:1）
商品B-3（在庫数:0）
商品C（在庫数:0）
 - 再現手順
1.TOPページを表示（在庫切れ数は、３を表示されている）
2.（在庫切れリンクを押下）商品一覧に、商品が２件表示される ← TOPページと商品一覧に表示件数の乖離がある状態

## 期待する内容(Expect)  or 要望 (Requirement)
TOPページの表示件数を、商品単位に変更する。（再現手順の場合２件）

### 環境 (environment)
+ EC-CUBE: 3.0.13
+ PHP: 7.0.11
+ DB:
  - SQLite version 3.7.17

## 相談事項
修正意図としては、TOPで参考にするのは数値ではなく、０件or１件以上という考えから、
本仕様で考えております。

**Comment by ryo-endo** [comment]
#1968で対応完了しました。
