### ISSUE TITLE
[管理画面]商品検索画面の「表示件数」と「すべて/公開/非公開/在庫なし」を同時に使用できるように変更

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2138]
## 概要(Overview)
[管理画面]商品検索画面の表示件数と、「すべて/公開/非公開/在庫なし」を同時に使用できない状態なので、同時に使用できるように解消する

### case1  
1. 「非公開」を選択
2. 「表示件数」を20件に変更する
→ 表示件数は変更されるが、検索対象は「非公開」から「すべて」に戻ってしまう。
（検索条件は保持されている）

### case2
1. 「表示件数」を20件に変更する
2. 「非公開」を選択
→ 検索対象が「非公開」のみに絞られるが、表示件数が10件に戻ってしまう。
（検索条件は保持されている）

## 期待する内容(Expect)  or 要望 (Requirement)
どちらも同時に使用できるようにする。  
case1,2どちらでも、検索対象「非公開」、表示件数20件の状態で表示される。

デフォルトの件数に戻すタイミングは、
左のサイドナビより再度メニューが選択された場合のみとする。
検索時は、表示件数をデフォルトには戻さない。
（2系と同様かつ、使い勝手を考慮し、上記挙動とします。）

### 環境 (environment)
+ EC-CUBE: 3.0.13
+ PHP: 7.0.11
+ DB:
  - SQLite version 3.7.17

**Comment by trebla-on** [comment]
@t-nagahashi 
リセットタイミングについて
初めて商品マスタ画面入ると表示件数は「10件」です、変更した後にデフォルトの数字戻すタイミングいつですか？
例えば：検索するボタン押した時に「10件」にもどす？

**Comment by t-nagahashi** [comment]
@trebla-on 

> 期待する内容(Expect) or 要望 (Requirement)
上記箇所の期待値に挙動を追記しました。

**Comment by trebla-on** [comment]
テストの時に新使用増えました。
１．検索して、
２. 20件に変更する
３．商品編集画面へ移動する
４．商品編集から戻ったあと20件件数を表示します、これは大丈夫ですか？
備考：もし４番の使用あってます場合は同じロッジク受注と顧客マスタ入れる必要ですか？

**Comment by t-nagahashi** [comment]
@trebla-on 
4の挙動でOKです。
理由は、EC-CUBE2系も同様の仕様となっているかつ、そのほうが使いやすいと判断しました。

元々のissueの対応とわけて対応することは可能でしょうか？
confilictしないのであれば、
「検索時、実行前の表示件数を引き継ぐ」「編集画面から戻ってきた場合、遷移前の表示件数を引き継ぐ」の上記対応は別issueをたてて対応お願いできますか？
（商品、受注、顧客の3機能について対応お願いします。）

**Comment by trebla-on** [comment]
管理画面の商品コントローラコンフリクトなるから同じPRで対応しました、
大丈夫ですね？

**Comment by trebla-on** [comment]
新規PRを作成しました　#2217
