### ISSUE TITLE
Docrtine-Migrationsを使ったDBマイグレーション

### ISSUE THREAD

**Issue by aminotsukasa** [EC-CUBE/ec-cube#214]
EC-CUBE3以降のバージョンアップを容易にするため、DB定義のマイグレーション方法を検討してみました。
コメントお待ちしています。

**概要**

 - EC-CUBE3系のマイナーバージョンアップに伴って変更されたDB定義の稼働環境への反映を自動化します。
 - DB定義の変更とは、テーブルの作成、削除、フィールドの作成、削除、インデックスの作成、削除、レコードの挿入、更新、削除等です。
 - マイグレーション処理はDoctrime migrationモジュールを使用します。
 - Doctrime migrationモジュールを使用することで、EC-CUBEのソースコードに定義されたDB定義とDBサーバ上のDB定義を比較し、必要なDB定義の変更だけをDBサーバに適応します。

**DBマイグレーション処理の構成**

 - migrationにはDoctrine-migrationモジュールを使用し、Silexから呼び出すためのServiceProvider(**https://github.com/dbtlr/silex-doctrine-migrations**)をラッパーとして使用します。
 - マイグレーション処理は当初はコンソールから起動する前提です。
 - Webインストーラ作成の際にはインストーラから起動可能にします
 - マイグレーションファイルはsrc/Eccube/Resource/doctrine/migrationに配置します。

**マイグレーションの作成手順**

 - Doctrineのテーブル定義ファイル(src/Eccube/Resource/doctrine/)を修正します。
(テーブル定義を変更しない場合は不要です)

 - 空のマイグレーションファイルを作成します。

   $ php app/console migrations:generate

    Generated new migration class to "/var/www/html/ec-cube/src/Eccube/Resource/doctrine/migration/Version20150519204013.php"

 - 上で作成したマイグレーションファイルのupメソッド定義に変更内容を記述します。 変更の処理は以下の方法で記述が可能です。
-   SchemaManagerを使ったテーブル定義の操作($table=$schema->createTable("foo")など)
-   EntityManagerを使ったレコードの操作($em->persist($customer)など)
-   リテラルとして埋め込んだSQLを直接実行（非推奨）

- 同様にdownメソッド定義にDB定義のロールバックに必要な処理を記述します。

**マイグレーションの受け入れ手順**

 - EC-CUBEのソースコードを更新します。
 - 作成されたマイグレーションをDBに反映します。

   $ php app/console migrations:migrate
    
       Doctrine Database Migrations
    
       WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y

   (何も出力されませんが反映されています。既にDB定義がソースコードに追従済みの場合は、Nothing to migrateと表示されます)

**マイグレーション状況の確認**

 - 適応が必要なマイグレーションの有無や現状のDB定義のバージョンを確認するには、migrationのステータスを取得します。

   $ php app/console migrations:status

2系からのバージョンアップは別途検討します....

**Comment by ttsuru** [comment]
:+1: 
クレジットカードなどで使っていたorderないのmemoなどをどうマイグレーションするかも検討しないといけないですね。

**Comment by aminotsukasa** [comment]
ちょっとマイグレーションファイルのサンプル代わりの書き方メモです。

 - テーブル作成

       $table=$schema->createTable("foo");
       $table->addColumn('id', 'integer', array(
            'autoincrement' => true,
        ));
       $table->setPrimaryKey(array('id'));

 - レコードの挿入
       $app = new \Eccube\Application();
       $app->boot();

       $customer = new \Eccube\Entity\Customer();
       $customer->setName01("a")->setName02("b")->setEmail("hoge@hoge.com")->setSecretKey(rand())->setPoint(1)->setDelFlg(0);

       $em=$app["orm.em"];
       $em->persist($customer);
       $em->flush();

 -

**Comment by Yangsin** [comment]
今後の本体開発の手法にも影響あると思いますが、イメージあっているか確認です。

### 前提
開発中にクリーンインストールを頻繁に繰り返すことがないように、今後の開発のDB変更はマイグレーションで用意したい  
開発中にマイグレーションの場合と、クリーンインストールの場合にあわあせて、SQL等修正する箇所を増やしたくない。  

なので、今後の開発としては、DBに変更を加えた開発を行う時は以下のような手順

### DB変更時の開発手順

1. src/Eccube/Resource/doctrine/*.yml を修正
2. マイグレーションファイルの作成（テーブル作成・変更、初期データ登録）
3. 実際に自分でマイグレーションしてみる → DBの変更が反映されることを確認
4. 機能開発のPRと合わせてマイグレーションファイルもアップ


あわせて、現状のインストーラーでのイメージとしては、
`eccube_install.sh` に `php app/console migrations:migrate` を追記しておけば
現時点のDBで、クリーンインストールされて、今後の差分はマイグレーションで適用される。

というようなイメージで大丈夫でしょうか。

**Comment by aminotsukasa** [comment]
今後のバージョンアップに備えて、以下の様な実際に発生する可能性が高いケースに対して、マイグレーションファイルと関連するファイルの作成を行い、クリーンインストールとバージョンアップ時の双方で期待通りの定義変更が実施するかどうか確認しました

### シナリオ
* シナリオ1 テーブルを追加する(dtb_migrationtest)を追加する
* シナリオ2 フィールドを追加する(mtb_countryにdel_flg)
* シナリオ3 フィールドの名前を変更(mtb_countryのrankからnew_rank)する
* シナリオ4 フィールドを削除する(mtb_jobのrankを削除)
* シナリオ5 テーブルを削除する(mtb_zipを削除)
* シナリオ6 レコードを挿入する

### 手順
いずれも以下の手順で問題なく実施できました
1.マイグレーションファイルを作成し、テーブル定義を記述
2.doctrineのDB定義ファイル(yml)を修正(追加、削除、修正)
3.entityとrepositoryを2.に対応する内容に修正
4.マイグレーションの実施

### 問題点
* クリーンインストール時、doctrineのschema-toolでymlファイルに基いてテーブルが作成された後にマイグレーションファイルが実行されるため、同じDDLが二回実行されていエラーとなる。マイグレーションファイル内に予定のDB定義が実施済みの場合何もしないように記述することで回避可能。
 (これについては別途マイグレーションガイド文書に記載します)
* フィールドの名前変更、型変更ができないので、dropしてcreateで代用する必要がある。どうしても必要な場合はべたにALTER文を書く必要がある

作成した実際に作成したファイルは

https://github.com/aminotsukasa/ec-cube/tree/migration_test/src/Eccube/Resource/doctrine/migration

です

**Comment by aminotsukasa** [comment]
# EC-CUBE 開発者向けDBマイグレーションガイド

## テーブル定義の変更手順

### はじめに
マイグレーション機構の用途としては、DDL(テーブル定義変更)の実行とDML(初期レコード定義)の実行の二種類があります。
それぞれ作成手順を記載します

# DDL用のマイグレーションファイルの作成手順

1.マイグレーションファイルを作成
  (php app/console migrations:generate)
2.マイグレーションファイルのup,downメソッド内に変更手順を記述する
  ただし、既に予定の変更の内容が実施済みの場合は無視するように設定すること
  (クリーンインストール時のorm:schema-tool:createを実行した場合の動作と重複してしまうため)

    テーブル追加例
    if($schema->hasTable(TABLENAME)){
        return true;
    }
    $table=$schema->createTable(TABLENAME);

    フィールド追加例
    $t=$schema->getTable(TABLENAME);
    if(!$t->hasColumn(FIELDNAME)){
        $t->addColumn(FIELDNAME,'smallint',array('NotNull'=>true,'default'=>0));
    }

3.doctrineのテーブル定義ファイル(yml)を2の内容に合わせて作成又は編集する
4.doctineのentity、repositoryを3の内容に合わせて編集する
5.コマンドラインからマイグレーションを実行(php app/console migrations:migrate)し、想定したDB定義となることを確認する
6.Webインストーラからクリーンインストールを実行し、5と同じDB定義になることを確認する


# DML用のマイグレーションファイルの作成手順

1.マイグレーションファイルを作成
  (php app/console migrations:generate)
2.マイグレーションファイルのup,downメソッド内に変更手順を記述する
  DML用の場合はDDLと違い実施内容のチェックは必要なし

    $m = new \Eccube\Entity\MigrationTest();
    $m->setMemo0('a')->setMemo1(1)->setMemo2(new \DateTime());
    $em->persist($m);
    $em->flush();

3.コマンドラインからマイグレーションを実行(php app/console migrations:migrate)し、想定した初期データが挿入されることを確認する

**Comment by aminotsukasa** [comment]
3.0.1から3.0.2へマイグレーションできるかどうか確認しました
以下の手順でPHP5.4.16、MySQL5.5、PostgreSQL9.2の環境で実施しています。

1.ver3.0.1をクリーンインストール
2.フロント画面から会員登録後にパーコレータを購入
3.ソース(src/Eccube,vendor)を最新版に更新
4.Apacheを再起動
5.マイグレータ(install.php/migration)を実行
6.フロント画面から会員登録後にパーコレータを購入
7.管理画面から手順2,5の受注情報、会員情報、商品情報を検索
8.CSV出力項目画面からCSV出力項目を設定

問題点
1.ソースを更新後にApacheを再起動しないと以下のエラーで白画面になってしまう
レンタルサーバ等で手動再起動できない場合が厳しい…
[Tue Jul 28 15:39:50.118465 2015] [:error] [pid 18916] [client 221.250.87.66:64090] PHP Warning:  require(/var/www/html/eccube-3.0.1.my/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernelInterface.php): failed to open stream: No such file or directory in /var/www/html/eccube-3.0.1.my/vendor/symfony/class-loader/ApcClassLoader.php on line 114

2.バージョンアップに伴いcomposer.jsonを更新した場合、src/Eccube以外にvendor、compose.json、composer.lockを更新する必要がある

**Comment by aminotsukasa** [comment]
マイグレーション時にapc_clear_cache()追加で回避可能ですので、まずはinstall.phpにapc_clear_cache を追加します

**Comment by Yangsin** [comment]
記述自体はもうすこし精査しますが、いったんWikiにうつしてこちらはクローズします。

https://github.com/EC-CUBE/ec-cube/wiki/マイグレーションガイド
