### ISSUE TITLE
プラグインジェネレータコマンドの修正のエラー

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2145]
## 概要(Overview)
コマンドでプラグインジェネレータするとき、エラーです。

## 期待する内容(Expect)  or 要望 (Requirement)
http://ec-cube.github.io/plugin_tutorial-generate
プラグイン利用方法のとおり、プラグインをうまく作成したい。

## 再現手順(Procedure)

1) `php app/console plugin:develop update --code[=CODE] `==> path is required.
チュートリアルのようなコードだけ必要ですが、実際は完全プラグインパスが必要です。

2) `php app/console plugin:develop enable --code[=CODE]` ==> error on console ( cache + doctrine )

3) p`hp app/console plugin:develop disble - code[=CODE]`==>error`[Doctrine\DBAL\ConnectionException] There is no active transaction.
`
有効化, 無効化実行時に関して、実行方法によってエラーになる場合がある。
プラグイン一覧から実行：OK
コンソールから実行：NG （おそらく、cacheが原因）

4) `php app/console plugin:develop entity`
Entity生成実行時、例外が発生する。

5) `php app/console plugin:develop install --path=./Point.0.0.tar.gz `
=> 権限例外を発生（app/cache/doctrine/proxy フォルダ）

chmod -R 777 app/cache/doctrine/proxyで実行すると、別の例外、

> [Eccube\Exception\PluginException] アップロードに失敗しました。圧縮ファイルを確認してくだい。になります。　

インストール実行時、権限を付与する必要がある（chmod実施が必要）

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 5.4
+ DB:
  - MySQL 
  - SqlLite

**Comment by t-nagahashi** [comment]
1) `php app/console plugin:develop update --code[=CODE] `==> path is required.
 - 問題点  
上記のようにチュートリアルに記載されている形での、「code」のみの入力でなく、プラグインルート直下からのパスを書く必要がある状態。  
 - 修正方針  
「code」のみの入力でプラグイン更新可能となるようジェネレータを修正

2) `php app/console plugin:develop enable --code[=CODE]` ==> error on console ( cache + doctrine )
 - 問題点
コンソールからのコマンド入力では実行時エラーとなる。（管理画面からは実行可能）
Doctrineのキャッシュが影響している可能性あり。
 - 修正方針  
コンソールから実行できるよう問題を解消する。

3) p`hp app/console plugin:develop disble - code[=CODE]`==>error`[Doctrine\DBAL\ConnectionException] There is no active transaction.
`
有効化, 無効化実行時に関して、実行方法によってエラーになる場合がある。
プラグイン一覧から実行：OK
コンソールから実行：NG （おそらく、cacheが原因）
 - 問題点
`2)` と同じくコンソールから実行時エラーが発生。
 - 修正方針  
`2)` と同様。

4) `php app/console plugin:develop entity`
Entity生成実行時、例外が発生する。
 - 問題点
管理画面、コンソールともに実行できない。
 - 修正方針  
実行できるよう修正する。

5) `php app/console plugin:develop install --path=./Point.0.0.tar.gz `
=> 権限例外を発生（app/cache/doctrine/proxy フォルダ）  
chmod -R 777 app/cache/doctrine/proxyで実行すると、別の例外、  
> [Eccube\Exception\PluginException] アップロードに失敗しました。圧縮ファイルを確認してくだい。になります。　
インストール実行時、権限を付与する必要がある（chmod実施が必要）

 - 問題点
権限エラーが発生し、その後権限付与後もエラーが発生実行できない。
 - 修正方針  
環境依存の可能性もあるが、複数環境で検証後、問題があれば修正する。

**Comment by trebla-on** [comment]
```
[root@os ~]# cd /var/www/eccube/
[root@os eccube]# sudo -u apache php app/console plugin:develop enable --code=Maker
success
[root@os eccube]# sudo -u apache php app/console plugin:develop disable --code=Maker
success
[root@os eccube]# sudo -u apache php app/console plugin:develop entity                                                                      

[entity]How to generate entities from db schema or yml? [d => db, y => yml] : d
------------------------------------------------------
---Plugin Generator for Entity
---[*]You need to create table schema first.
---[*]You can exit from Console Application, by typing quit instead of typing another word.
------------------------------------------------------

[+]Please enter Plugin Code (First letter is uppercase alphabet only. alphabet and numbers are allowed.)
Input[1] : quit
Quitting Bye bye.
[root@os eccube]# sudo -u apache php app/console plugin:develop install --path= app/                                                        
.htaccess               Plugin/                 config/                 log/                    
Coupon_20151229.tar.gz  cache/                  console                 template/               
[root@os eccube]# sudo -u apache php app/console plugin:develop install --path=./app/Coupon_20151229.tar.gz 
success

```

**Comment by trebla-on** [comment]
エラーメッセージがないと調査しにくいのでエラー内容教えていただけますか？

**Comment by ryo-endo** [comment]
@lammn エラーメッセージの共有お願いします。
