### ISSUE TITLE
管理画面：規格管理・規格分類管理

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#216]
# 仕様変更

UI変更に伴うデザインテイストの変更のみ

# DB定義の変更

dtb_class

テーブル名の変更
変更前：dtb_class
変更後：dtb_class_name

dtb_classcategory

テーブル名の変更

変更前：dtb_classcategory
変更後：dtb_class_category

dtb_products_class

テーブル名の変更
変更前：dtb_products_class
変更後：dtb_product_class

**Comment by shinichi-takahashi** [comment]
マージされたため、クローズします。
