### ISSUE TITLE
商品CSV登録時ProductImageの異常と管理画面操作での削除による全画像消失

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#2160]
### 問題１
管理画面「商品CSV登録」にて、「商品画像」の列の先頭や末尾にカンマがある等場合にfile_nameが空のProductImageエンティティが生成されます。

### 考えられる対応

- CSVImportControllerで$images = explode(',', $row['商品画像']);した際の空白要素チェックを行う。

- 画像ファイルの存在チェックを行う

### 問題２
また、file_nameが空になっている画像を管理画面から削除すると、
html/upload/save_imageディレクトリ自体が削除されます。
（または、save_imageの中のファイルが削除される？）

### 考えられる対応

- 画像削除の際にファイル存在チェックを行う

- そもそも空白のデータの場合ファイルの削除を行わない

### 環境 (environment)
+ EC-CUBE: 3.0.13

フォーラムで報告があがっています。
[商品画像が消えてしまいます](https://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&topic_id=18636&forum=11)

**Comment by ryo-endo** [comment]
#2161 で、空白のデータを登録しない・削除しないように対応の取り込みを行いました。
ご報告ありがとうございました。
