### ISSUE TITLE
データベースのデータ型とカラム名の変更（for 3.n)

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2163]
## 概要(Overview)

以下のような目的のためにデータベースのデータ型やカラム名を変更する

+ パフォーマンスの向上
+ APIへの対応
+ クラウド環境などでの時差の考慮
+ 他DBへの対応ハードルの低下

## 要望 (Requirement)

+ TEXT型のカラムの変更
  - [ ] TEXT型が指定されているカラムに桁数制限をつける
+ カラム名の変更
  - [ ]  #295 の dtb_category.levelのみ対応
+ 日時型の変更
  - [ ] DateTime 型はDateTimeTz 型に変更
  - [ ] MySQLの場合に時差を調整するコードの追加
+ 変更箇所まとめる 
  - [ ] entity.ymlのDiffを整形
  - [ ] markdown形式の表を用意

+ 3.0.xからのデータ移行については別途課題とする

## 関連情報 (Ref)

 #537
 #276  
 https://github.com/k-yamamura/ec-cube3-modify-type-database
 http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html
 https://github.com/k-yamamura/ec-cube/tree/feature-utc

**Comment by okazy** [comment]
対応済みのためクローズします。
