### ISSUE TITLE
管理画面：設定＞システム設定＞メンバー管理

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#217]
## 画面UIの変更点
新規登録、編集画面への遷移はポップアップではなく、通常の画面遷移に変更する

## ER・テーブル定義の変更点
なし

## 関連機能・仕様

以下は、別途開発とする
* 権限機能
* 変更履歴(creator_id/updator_id)

## PR
#213

**Comment by shinichi-takahashi** [comment]
PRマージいただいているため、クローズします。
