### ISSUE TITLE
パスワード再発行時に、EC-CUBEが自動生成した初期パスワードが、管理者にも送信されている

### ISSUE THREAD

**Issue by hideki-okajima** [EC-CUBE/ec-cube#2180]
## 概要(Overview)
フロント画面からパスワード再発行の手順でパスワードを再発行すると、BCCで管理者にも同じメールが送信されてしまいセキュリティの面で問題がある。

## 期待する内容(Expect)  or 要望 (Requirement)
パスワード変更に関して管理者にはメールが飛ばないようにする。

## 再現手順(Procedure)
フロント画面からパスワードの再発行をする。

### 環境 (environment)
+ EC-CUBE: 3.0.13

**Comment by hideki-okajima** [comment]
以下で修正のプルリクを出しました。
https://github.com/EC-CUBE/ec-cube/pull/2181

**Comment by ryo-endo** [comment]
補足：
メールで送られるのは、**EC-CUBEが自動生成した初期パスワード**です。
会員がMYページの"会員情報変更"でパスワードを変更したときには、メールは送信されません。

```
パスワードを変更いたしました。
新しいパスワード：g66vwePc
このパスワードは一時的なものですので、お早めにご変更下さい。
```

**Comment by hideki-okajima** [comment]
補足ありがとうございます。
それではよろしくお願いいたします。

**Comment by nanasess** [comment]
関連 https://github.com/EC-CUBE/ec-cube/issues/740

**Comment by hideki-okajima** [comment]
プルリク再申請しました。
https://github.com/EC-CUBE/ec-cube/pull/2189
