### ISSUE TITLE
【購入完了】問い合わせ用に購入完了画面で受注ID表示をした方が良い

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#2186]
## 概要(Overview)
一般的なECとして、購入完了画面で受注IDは表示されるので、表示しておいた方が良い。
※メールアドレスが誤っていて、メールが届かない、なども考えられるため。

## 期待する内容(Expect)  or 要望 (Requirement)
購入完了画面で受注IDを表示

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by dk-umebius** [comment]
いつも上記コミットのような感じで簡易的に表示しているのですが、
セッション'eccube.front.shopping.order.id'を削除するためブラウザリロードされると表示されなくなります。
今の構造ですとこれが精一杯でしょうか。何か良い方法、方針があればご教示いただけますと幸いです。

**Comment by ryo-endo** [comment]
#2192 でデフォルトのテンプレートに、注文番号を表示する対応を取り込みました。

dk-umebiusさんのコメントの通り、購入完了画面でのブラウザリロードには対応していないのですが、Issueに記載されている課題はクリアできていると判断して、CLOSEさせていただきます。
