### ISSUE TITLE
mail.yml.distにspool設定を追加

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#2194]
## 概要(Overview)

Application.phpに既にspoolを設定する処理は記述されていたが、
mail.yml.distに設定されていなかったため、
mail.yml.distに
```
spool: true
```
を追加する。
(デフォルトはtrue)
http://silex.sensiolabs.org/doc/1.3/providers/swiftmailer.html#parameters

## 期待する内容(Expect)  or 要望 (Requirement)

SwiftmailerServiceProviderはKernelEvents::TERMINATEイベントを使用してメール送信されます。
このイベントは応答が送信された後に発生するため、
このイベントが発生しない限りメールは送信されません。

また、このイベントはコンソールコマンドでは起動されないためメールが送信されません。
そのため、コマンドコンソールを使用してメールを送信する場合は、
```
spool: false
```
を設定することで送信可能になります。

index_dev.phpにも
```
if (isset($app['config']['mail']['spool']) && is_bool($app['config']['mail']['spool'])) {
    $app['swiftmailer.use_spool'] = $app['config']['mail']['spool'];
}
```

を追加しておくこと。

**Comment by ryo-endo** [comment]
#2195 での対応を取り込みましたのでCLOSEします。
