### ISSUE TITLE
DBスキーマの移行サポートについて

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#22]
今まで、EC-CUBEではDBのスキーマを変更した際にmigrationを作成していませんでしたが、今後は何からの形でcommitに含めませんか？

バージョンアップしやすいように開発することも安全なウェブシステムに重要ではないでしょうか。

**Comment by nanasess** [comment]
ALTER だけの追加ではなく、CREATE TABLE もメンテするという認識であってますか？

**Comment by ttsuru** [comment]
@nanasess 
その方がよいと思います。
スキーマの変更に伴うcommitをされる方が作成するなりがよいのではないでしょうか。
MDBも含め置き換える時期なのかもしれません。

**Comment by nanasess** [comment]
@ttsuru 
MDB2 は置きかえて良いと思いますが、シーケンスの違いを吸収するフレームワークって他にありますかね？？

**Comment by ttsuru** [comment]
@nanasess 
Doctrine DBAL あたりはどうかなと思います。
http://www.doctrine-project.org/projects/dbal.html

以下メリットです
・Migration対応や CREATE / ALTER文もSQLを書かなくてよい。
・テストカバレッジがよい。
・Oracle、SQL SRVへの対応もある程度は行けそうな気がします。

ORマッパを利用するのであれば、別途検討が必要だと思いますが。
残る案として、ピュアPDO、Zend DB、PHP ActiveRecord、Doctrine ORM あたりでしょうか。

**Comment by nanasess** [comment]
@ttsuru ありがとうございます。 Azure でも動けばいうことないです。 :+1:

**Comment by ttsuru** [comment]
@nanasess 
本体では対応しなくでも、DBのマスター／スレーブにもある程度対応できる道筋が欲しいと個人的には思っています。

**Comment by nobuhiko** [comment]
http://auraphp.com/packages/v2 もありますね

https://github.com/auraphp/Aura.Sql
https://github.com/auraphp/Aura.SqlQuery
https://github.com/auraphp/Aura.SqlMapper_Bundle

**Comment by ttsuru** [comment]
@nobuhiko 
Aura は知りませんでした。
やはりDoctrine DBALと同様にPDOのラッパなんですね。

**Comment by Yangsin** [comment]
Doctrine Migrationを採用。
詳細は以下で・
https://github.com/EC-CUBE/ec-cube/issues/214
