### ISSUE TITLE
管理画面：設定>基本情報管理＞メール設定

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#220]
# 仕様変更

* UI変更に伴うデザインテイストの変更のみ
* 初期登録のテンプレートから携帯用のものを削除する

# DB定義

dtb_mailtemplate
変更前：dtb_mailtemplate
変更後：dtb_mail_template

# 関連するマスターデータ

mtb_mail_template ： メールテンプレートIDとテンプレート名
mtb_mail_tpl_path ： メールテンプレートIDとテンプレートのファイルパス

# 機能

* 既存のメールテンプレートのヘッダー・フッターを編集
* テンプレートファイルはdtb_mail_templateに保存
* 編集できるテンプレート
    + 注文受付メール
    + 注文キャンセル受付メール
    + 取り寄せ確認メール
    + お問い合わせ受付メール
    + 入力文字数カウント（ヘッダー、フッター共に）-> 削除

**Comment by chihiro-adachi** [comment]
2系仕様の考慮漏れがあったので、追記します。
* 新規登録はなく、更新のみ発生する
* プルダウンのリストはmtb_mail_templateから取得する

**Comment by Yangsin** [comment]
仕様の考慮漏れがありましたが、この機能自体を見なおして、以下のようにしたいと思いますがいかがでしょうか。

## 仕様の変更

現行：  特定のメールテンプレートヘッダー・フッターを編集できる
変更案： メールテンプレート全体を変更できる

テンプレートの保存ロジックの変更
ブロックなどと同じテンプレートファイル編集のロジックを利用する。ファイル探査順も同様。
or DB自体にテンプレートファイルを保存する

### テーブル定義の変更案
mtb_mail_template 、mtb_mail_tpl_path を廃止し、
dtb_mail_template にテンプレート名、テンプレートファイルへのパスも保存して１つのテーブルに統合

理由： 1:1:1でdtbとmtbｘ２が紐付いているため、シンプルに１テーブルで扱うようにする。プルダウンのセレクトボックス生成のために主に利用されているが、mtbを利用したセレクトボックスを作るような機能がないためmtb_mail_templateやmtb_mail_tpl_pathの存在価値が薄い。

**Comment by Yangsin** [comment]
あらためて確認しましたが、受注メールのテンプレートとか結構複雑で変にイジれるのも事故の元かなとおもいなおし、実装するうえで無駄に重くなるDB定義は見直し、dtb_mail_templateに集約。動的部分のテンプレートはこれまで通り編集不可。ヘッダー・フッターをDB保存が安全そうです。

**Comment by nobuhiko** [comment]
いやいやいや、管理画面だけで基本的には完結できるようにしましょうよ・・
その理屈なら商品一覧も複雑だからデザインいじらせないって言ってるのと変わらないです

**Comment by seasoftjapan** [comment]
とりあえず、Smarty テンプレートを DB 格納するのは避けて欲しいです。

本文・ヘッダー・フッターとか、分けなくて、1枚のテンプレートでも良い気もしますが、、、
現況の「1 テンプレートファイル : n テンプレート」みたいな構造も便利なことが多々あるので、一概に否定はできないですね。

**Comment by Yangsin** [comment]
@nobuhiko 
管理画面から更新できるとして、その場合のテーブルのイメージってどうでしょうか？
ヘッダーフッターを分ける必要はありますか？

@seasoftjapan 
テンプレートをDBに格納せず、ファイルで管理するブロックのようなパターンであれば、動的部分の編集も有りと思われますか？
1:n テンプレートといわれているのは、PC・携帯共通でとかのイメージでしょうか？

**Comment by ttsuru** [comment]
@Yangsin 

テンプレートの編集機能は `template/__name__` 以下をすべてテンプレート編集から編集できるようにして、別にヘッダー・フッター部分を管理画面から入れられるようにしてはどうでしょうか。

ヘッダー・フッター部分は動的に変更したいメッセージのようなものを入れる際にはよく使われていると思います。

**Comment by seasoftjapan** [comment]
@Yangsin 

編集自体は有りだとは思います。個人的な需要は極めて低いのですが (むしろ不要)、サイトオーナーさんに依っては使うかも、といった感じでしょうか。
(細かいこと言うと、変更が無かった時には、テンプレートファイルを上書きしないで欲しいです。それを言い出したら、この処理に限らずですが・・・)

「1 テンプレートファイル : n テンプレート」は、この部分の事でした。
```sql
INSERT INTO mtb_mail_tpl_path (id, name, rank) VALUES (1, 'mail_templates/order_mail.tpl', 0);
INSERT INTO mtb_mail_tpl_path (id, name, rank) VALUES (2, 'mail_templates/order_mail.tpl', 1);
INSERT INTO mtb_mail_tpl_path (id, name, rank) VALUES (3, 'mail_templates/order_mail.tpl', 2);
INSERT INTO mtb_mail_tpl_path (id, name, rank) VALUES (4, 'mail_templates/order_mail.tpl', 3);
```

**Comment by Yangsin** [comment]
皆様ご意見ありがとうございます。

まずは、これまで通りの実装で進めさせていただき、
 @ttsuru の意見のような、テンプレートファイルの編集機能を今後のIssueとします。

ちょっと混乱するのでまとめます。

## 仕様変更

UI変更に伴うデザインテイストの変更のみ
初期登録のテンプレートから携帯用のものを削除する


## DB定義

https://github.com/EC-CUBE/eccube3-doc/blob/eccube-3.0.0-beta/ER-D/ER-mail.xls

dtb_mail_template にtemplate_path,description を追加し、
mtb_mail_template と、mtb_mail_tpl_path を廃止

## 機能

+ 既存のメールテンプレートのヘッダー・フッターを編集
+ 編集できるメールの種類
  + 注文受付メール
  + 注文キャンセル受付メール
  + 取り寄せ確認メール
  + お問い合わせ受付メール

注記
+ 動的部分のテンプレートファイルは編集できない
+ メールテンプレートを新規追加はできない

**Comment by seasoftjapan** [comment]
> お問い合わせ受付メール

2系にて、受注系のメール通知に、これが混ざるのは、不自然に感じていました。反面、ヘッダー・フッターを編集できれば良いという観点では、ここで良い気もします。
たとえば、受注に対するメールかを、テーブルに持たせるなどで対応できないでしょうか?

> メールテンプレートを新規追加はできない

サイト運営サイドで追加しているケースも散見するので、できれば対応するのが親切には思います。
(できなければ、カスタマイズ依頼ありそうなので、それはそれで個人的には嬉しいです。)

**Comment by Yangsin** [comment]
@seasoftjapan 
> たとえば、受注に対するメールかを、テーブルに持たせるなどで対応できないでしょうか?  
たとえば、mail_type みたいなものを持たせて、1 ならCustomer、2ならContact、3ならOrderとかわけていくような感じですかね？
現状はできませんが、会員登録メールなども結構カスタマイズの要求が強いのではないかと思ってます。

新規登録は需要はありそうですが、動的部分のカスタマイズ方法とあわせて実装を検討したほうがよさそうなので、まずは見送りでいいかなと思ってます。
