### ISSUE TITLE
配送方法が異なる商品がカートにある場合に、片方の配送方法でしか利用できない支払い方法が表示されている

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2211]
## 概要(Overview)
配送方法が異なる商品がカートにある場合に、片方の配送方法でしか利用できない支払い方法が表示されている。

## 期待する内容(Expect)  or 要望 (Requirement)
共通支払い方法の**現金書留**しか表示しない。

## 再現手順(Procedure)

1. パーコレーターとディナーフォークを両方を商品種別Bを設定する。
2. 配送方法設定で  
サンプル業者　：商品種別B - **現金書留、代金引換**　を設定する。  
サンプル宅配　商品種別B - **郵便振替、現金書留**を設定する。
3. パーコレーターとディナーフォークをカートに入れて、購入確認画面にいく。  
⇒共通の支払い方法は**現金書留**ですが、注文確認画面に**現金書留、 代金引換**を表示しています。

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 5.5
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by t-nagahashi** [comment]
重複 #2286
