### ISSUE TITLE
[管理画面]受注登録で、配送業者・お届け時間で不必要な表示がある

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2212]
![cap111](https://cloud.githubusercontent.com/assets/17536702/23883134/aedf71ea-0897-11e7-91e7-6c84136fefb2.PNG)
## 概要(Overview)
[管理画面]受注登録で、配送業者・お届け時間で不必要な表示がある

## 期待する内容(Expect)  or 要望 (Requirement)
重複しないように表示する。

## 再現手順(Procedure)
受注を編集して、以上の配送業者とお届け時間を重複しています。

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 5.5
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by t-nagahashi** [comment]
本issueは、以下理由によりクローズいたします。

・以下ユースケースを想定しているため、必要であると考えております。
「顧客注文後、受注の変更があった際に変更内容を伺った後、再確認実施時に変更前→変更後の内容を確認するため」
