### ISSUE TITLE
カート画面のエラーメッセージが、購入確認画面で表示されるケースがある

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#2213]
## 概要(Overview)
カート画面で、在庫数上限を上回るまで「＋」ボタンを連続クリックしたあと、
カートページの再表示をまたずに、「レジに進む」ボタンをクリックすると、
本来は購入確認画面に表示するエラーメッセージが、購入確認画面に表示される。

## 期待する内容(Expect)  or 要望 (Requirement)
エラーがある場合は、カート画面を再描画すべき？
（要ディスカッション）

## 再現手順(Procedure)
概要の通り

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 5.5
+ DB:
  - PostgreSQL 9.3.14

**Comment by okazy** [comment]
こちらは発生条件が限定されており、発生時も致命的な問題とはならないと思いますので優先度は低いと考えています。
