### ISSUE TITLE
【3.1/要望】 カート関係の抽象化

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2219]
## 要望 (Requirement)

例えばカート商品追加時に追加の商品オプション(熨斗やラッピング等)も考慮するカスタマイズをプラグインで実装する場合、現状では```eccube.service.cart```の実体を丸ごと置き換える必要がある。

カート内商品存在チェックや単価(あるいは小計)計算等をデザインパターンを用いて柔軟に対応できるようにして欲しい。

**Comment by okazy** [comment]
以下で実装済みのためcloseします。
https://github.com/EC-CUBE/ec-cube/issues/2613
