### ISSUE TITLE
管理画面：商品管理＞カテゴリ登録

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#222]
# 仕様変更

UI変更に伴うデザインテイストの変更のみ

# DB定義

dtb_products_categories

* テーブル名の変更
    * 変更前：dtb_products_categories
    * 変更後：dtb_product_category

constant.yml

* 最大登録数： constant.yml - category_max
* 最大階層数： constant.yml - level_max
    * 定数名の変更: category_nest_level

# 機能

商品のカテゴリー階層を登録することができる。

* カテゴリの新規登録
* カテゴリの編集
* カテゴリの並び替え（同じ階層内に限る）

# 関連機能・仕様

以下は、別途開発とする

* カテゴリーのCSVダウンロード
* CSV項目設定

**Comment by nobuhiko** [comment]
https://github.com/blt04/doctrine2-nestedset
こういうの使えば、カテゴリの並び替え（同じ階層内に限る）という変な縛りはなくせるんじゃないでしょうか

**Comment by ttsuru** [comment]
@nobuhiko 
本当にスキーマ変更するのであればこれ使うとすごい楽ですね。

**Comment by Yangsin** [comment]
3.0.0 では一旦現行の仕様とさせていただき、カテゴリの構造の見直しは3.0.x以降とさせていただきます。
おそらく、3.1.x以降となりますね。

**Comment by Yangsin** [comment]
#250 に移しました。こちらはクローズします。
