### ISSUE TITLE
決済プラグイン無効時のエラー

### ISSUE THREAD

**Issue by toshiaki-h** [EC-CUBE/ec-cube#2220]
## 概要(Overview)
配送方法設定でプラグインで追加した支払方法にチェックが入った状態で支払プラグインを無効にするとカート画面でエラーになる。

## 期待する内容(Expect)  or 要望 (Requirement)
支払い方法にチェックが入った状態でプラグインを無効にしてもエラーにならないようにしてほしい。

## 再現手順(Procedure)
概要と同じ

### 環境 (environment)
+ EC-CUBE: 3.0.13
+ PHP: 7.0.8
+ DB:
  - PostgreSQL 9.5.3

**Comment by t-nagahashi** [comment]
@toshiaki-h 
プラグインの挙動のため、本体側で制御すべき（そもそもできる？）かどうか検討する必要があります。
具体的にどの決済プラグインか教えて頂けますでしょうか？

**Comment by toshiaki-h** [comment]
@t-nagahashi 
本体側でするべきところなのか、プラグインでそもそも考慮するべきところなのか判断がよくわからなかったところもあるので、issueに挙げさせていただきました。
1つ例を挙げさせていただきますと、「クロネコヤマト　カード・後払い一体型決済サービス(3系)」で同現象が確認できるかと思われます。

**Comment by t-nagahashi** [comment]
> 支払い方法にチェックが入った状態でプラグインを無効にしてもエラーにならないようにしてほしい。
支払方法の問題にかかわらず、
エラーにならいないように、メッセージを出すなど、何かしらの対応は必要ですね。
時期バージョンで検討してみます。

**Comment by t-nagahashi** [comment]
> 支払い方法にチェックが入った状態でプラグインを無効にしてもエラーにならないようにしてほしい。

支払方法の問題にかかわらず、
エラーにならいないように、メッセージを出すなど、何かしらの対応は必要ですね。
時期バージョンで検討してみます。

**Comment by ryo-endo** [comment]
@toshiaki-h 
以下の手順で確認しましたが再現できませんでした。
手順で異なるところがありましたら教えていただけますでしょうか？

### 手順
1. [管理画面]クロネコヤマト決済プラグインインストール、有効化、設定
1. [管理画面]配送方法>サンプル業者で、支払い方法にクレジットカードを追加
1. [フロント画面]からパーコレーター(=サンプル業者)をカートに追加
1. [フロント画面]カートのページを表示
1. [管理画面]クロネコヤマト決済プラグインを無効化
1. [フロント画面]カートのページを再表示  
→エラー無く通常表示される(OK)  

### 環境
EC-CUBE: 3.0.13
クロネコヤマト　カード・後払い一体型決済サービス: 1.1.0

**Comment by toshiaki-h** [comment]
@ryo-endo 
確認ありがとうございます。
現在こちらで確認できる環境がないため試すことができないのですが、手順はおそらくあっていると思います。

当時の作業ログを見てみると、配送業者に関連付けられた支払い方法がプラグインで無効化されているとエラーになっていたようです。
カート画面で支払い方法を取得してくる際に、配送業者と関連付けしているテーブルの削除フラグを見てなさそうだと書いてありました。

クロネコヤマトのプラグインも1年前から数回バージョンアップされているのでその間に修正性が入っている可能性もありそうですね。

**Comment by ryo-endo** [comment]
@toshiaki-h 
お返事ありがとうございます。
現時点のプラグインで再現しないため、こちらのIssueはCLOSEさせていただきます。
レポートありがとうございました。
