### ISSUE TITLE
[管理画面]検索条件の電話番号を、ハイフンありでも検索できるようにする

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#2225]
## 概要(Overview)
管理画面 - 受注マスター、会員マスター
検索条件の「電話番号」をハイフンありでも検索できるようにする。

お問い合わせメールのTEL（ハイフンあり）をそのままコピーして検索するシナリオを想定。

## 期待する内容(Expect)  or 要望 (Requirement)
概要に記載の通り。

## 再現手順(Procedure)
なし

### 環境 (environment)
+ EC-CUBE: 3.0.14

## 関連情報 (Ref)
なし

**Comment by tao-s** [comment]
あああ。ごめんなさいやりますやります

**Comment by ryo-endo** [comment]
なんか急かしたみたいですみません。
お待ちしております。

**Comment by tao-s** [comment]
@ryo-endo 

> なんか急かしたみたい

急かされましたーw

**Comment by ryo-endo** [comment]
こちら #2228 で対応終わっていたのでCLOSEします。
