### ISSUE TITLE
DocumentRootをhtmlから変更する

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2232]
## 概要(Overview)

DocumentRootのデフォルトをhtmlディレクトリからRootディレクトリとする

## 期待する内容(Expect)

長らくhtmlディレクトリをDocumentRootとする事を標準としてきたが、特にレンタルサーバーやサブディレクトリでの利用者が、htmlをDocumentRootに設定ができない。
開発ドキュメントでも方法をhtmlをURLから削除する方法を案内してきたが、開発者や運用者の手間も多く、バージョン・アップ時のミスも聞くため。
3系の次期メジャーバージョンでDocumentRootのデフォルトをRootディレクトリとする

## 関連情報 (Ref)

#558 #2231 
http://doc.ec-cube.net/quickstart_remove-html

**Comment by okazy** [comment]
3.nでは既に対応済みのためdiscussion外します。

**Comment by okazy** [comment]
4.0では対応済みのためクローズします。
