### ISSUE TITLE
Cart/index.twigの</div>の数が間違っている

### ISSUE THREAD

**Issue by hideki-okajima** [EC-CUBE/ec-cube#2239]
## 概要(Overview)
Cart/index.twigの</div>の数が間違っていた

## 期待する内容(Expect)  or 要望 (Requirement)
プルリク作成中

### 環境 (environment)
+ EC-CUBE: 3.0.14

**Comment by t-nagahashi** [comment]
@hideki-okajima 
ありがとうございます。
プルリクお待ちしております。

**Comment by hideki-okajima** [comment]
紐づけ忘れていました。
以下でプルリク作成済みです。

https://github.com/EC-CUBE/ec-cube/pull/2240

よろしくお願いいたします。

**Comment by t-nagahashi** [comment]
対象PRが既にMergeされているため本issueを閉じます。
