### ISSUE TITLE
[管理画面] 支払方法設定でRankが連番になっていないと「上へ」「下へ」がエラーになる

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#2241]
## 概要(Overview)
支払方法設定にて支払方法のRankが「1 2 3 4 6」のように飛んでいると「上へ」「下へ」で4と6の順番交換ができません。

## 期待する内容(Expect)  or 要望 (Requirement)
支払方法の並び替えができる。
Rankは「1 2 3 4 5」と整理される

## 再現手順(Procedure)
支払方法のRankが「1 2 3 4 6」になっている状態で、Rank6の「下へ」をクリック
連番になっていないRankで支払方法を登録するプラグインがあったためエラーが発生しました。

**Comment by t-nagahashi** [comment]
@dk-umebius 様
本件、長らくそのままですので、一旦Closeさせていただきます。
引き続き、不具合が発生している場合は、再度issueもしくはPullRequestをお願いします。
