### ISSUE TITLE
商品規格登録ページから商品登録ページに戻りたい

### ISSUE THREAD

**Issue by moritahiroo** [EC-CUBE/ec-cube#2245]
## 概要(Overview)
商品規格登録ページの「前のページに戻る」リンクは商品マスターページに遷移しますが、
「前のページ」であれば商品登録ページに戻すのが良いと思いました。

## 期待する内容(Expect)  or 要望 (Requirement)
該当商品の登録ページに戻るようにするか、もしくは、「前のページに戻る」ではなく「商品マスターに戻る」に変更するか、どちらかが良いと思います。

## 再現手順(Procedure)
管理画面＞商品マスター
規格が登録されている商品の登録画面へ
商品登録画面の「規格設定」を押下して商品規格設定画面へ
一番下の「前のページに戻る」リンクを押下

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 7.0
+ DB:
  - MySQL 5.7

**Comment by trebla-on** [comment]
対応意見
■商品編集リンク追加
規格画面入ると必ず商品が登録されてますので「商品編集へ」リンクあってもいいかもしれません
■検索一覧に戻る
検索一覧から必ず来る判断できないので条件で以下のリンク表示する
SESSIONに「eccube.admin.product.search.page_no」あった場合は検索にリンク追加するただ名前は「商品マスターへ」

例：1 (商品一覧で「規格」ボタン押す)
ボッタン表示方法
「更新」
「商品編集へ」
「商品マスタへ」（SESSIONに検索キーある時表示）

例：2 (商品検索せずに商品編集画面で規格押す)
ボッタン表示方法
「更新」
「商品編集へ」

備考：現在はどこからきたURLパラメターがないので規格画面で前のページ判断できないです
