### ISSUE TITLE
商品複製時に個別税率設定がコピーされない

### ISSUE THREAD

**Issue by moritahiroo** [EC-CUBE/ec-cube#2249]
## 概要(Overview)
個別税率が設定されている商品を「複製」したときに、消費税率がコピーされません

## 期待する内容(Expect)  or 要望 (Requirement)
個別税率が設定されている商品を複製したときは、消費税率もコピーされるのが良いと思います。

## 再現手順(Procedure)
1. 商品別税率の有効化
　　[管理画面] - [設定] - [基本設定] - [税率設定] - [商品別税率機能]を有効
2. 商品情報の複製
　　[商品管理] - [商品マスター]で既存商品を検索し、編集画面に入る
　　商品編集画面で[詳細な設定] - [消費税率]を設定し、いったん保存（[商品を登録]ボタンで保存）
       [複製]ボタンを押して複製
　   複製された商品の全データがコピーされるが、[消費税率]だけコピーされない

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 7.0
+ DB:
  - MySQL 5.7

**Comment by moritahiroo** [comment]
プルリク作成中です

**Comment by moritahiroo** [comment]
見当違いのことしていたらご指摘いただきたいのですが、
この修正の動作確認を行なっていたところ、個別税率の設定がフロントの一部ページで反映されない現象が起こりました。

[反映されるページ]
商品一覧
購入確認
（受注データには反映されています）

[反映されないページ]
商品詳細
カート

3/29時点のmasterを使ってローカルに環境作りました。
私の環境の問題なのか、何かバグがあるのか、いまのところ見当がつきません。
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=18796&forum=2
こちらにも投稿させていただいております。

確認ポイントなど、ご教示いただけると助かります。
よろしくお願いいたします。

**Comment by moritahiroo** [comment]
#2251 issue登録しました。

**Comment by okazy** [comment]
#2255 で修正されておりますのでクローズさせていただきます。
