### ISSUE TITLE
Where is the database's strutcure script?

### ISSUE THREAD

**Issue by smelike** [EC-CUBE/ec-cube#2257]
## 概要(Overview)

I download the ec-cube install package. And then I install ec-cube, but I cannot found the sql script.

At the last step, there is an error happen.

> > An exception occurred while executing 'SELECT member_id FROM dtb_member WHERE login_id = :login_id;' with params ["admin"]:
> 
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eccube.dtb_member' doesn't exist

## 期待する内容(Expect)  or 要望 (Requirement)

Where is the ec-cube's mysql script?

## 再現手順(Procedure)

> An exception occurred while executing 'SELECT member_id FROM dtb_member WHERE login_id = :login_id;' with params ["admin"]:
> 
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eccube.dtb_member' doesn't exist

### 環境 (environment)
+ EC-CUBE: 3.1
+ PHP: 5.6
+ DB:

  - MySQL 5.7

**Comment by chihiro-adachi** [comment]
@smelike
try below command.
`php eccube_install.php mysql`

**Comment by smelike** [comment]
@chihiro-adachi But there is somehing else happen. **I use WampServer beyond Windows 7.**

> PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000
> ] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\
> www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43
> Stack trace:
> #0 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.ph
> p(43): PDO->__construct('mysql:host=loca...', 'root', 'password', Array)
> #1 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.
> php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', '
> root', 'password', Array)
> #2 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(360): Do
> ctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'password', Array)
> #3 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(429): Do
> ctrine\DBAL\Connection->connect()
> #4 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(389): Do
> ctrine\DBAL\Connection->getDatabasePlatformVersion()
> #5 D:\www\eccube3\vendor\doctrine\dbal\lib\Doc in D:\www\eccube3\vendor\doctrine
> \dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 103
> 
> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [10
> 45] Access denied for user 'root'@'localhost' (using password: YES)' in D:\www\e
> ccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43
> Stack trace:
> #0 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.ph
> p(43): PDO->__construct('mysql:host=loca...', 'root', 'password', Array)
> #1 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.
> php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', '
> root', 'password', Array)
> #2 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(360): Do
> ctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'password', Array)
> #3 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(429): Do
> ctrine\DBAL\Connection->connect()
> #4 D:\www\eccube3\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(389): Do
> ctrine\DBAL\Connection->getDatabasePlatformVersion()
> #5 D:\www\eccube3\vendor\doctrine\dbal\lib\Doc in D:\www\eccube3\vendor\doctrine
> \dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 103

**Comment by xuelian311** [comment]
The discussion was stopped for 5 more years, so we are going to close the issue. If you have any more question, please use the development community site.
