### ISSUE TITLE
レイアウト管理の単純化とブロックの見直し

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2266]
## 概要(Overview)

レイアウト管理をHTML5の主要な構造に合わせてブロックの記載順番を調整するレベルのシンプルな構造に変更し、横並びのレイアウトについては、ブロック内でコードレベルでの調整を行う形にする
必然的にブロックのサイズが3.0までより大きくなるが、3.0までのブロックは更にスタイルガイドラインにあわせたコンポーネント毎にTwigを分解し、ブロック内で各Twigを呼びだすことで再利用性を担保する

### レイアウト管理
HTML5ベースの<head><body><header><main><footer></body>の簡易な区切りとし、各タグ内でのコードの表示順のみを管理し、管理画面のイメージを出力されるコードにより近いかたちでの扱い、フロントエンドのコーダーがより理解し扱いやすいようにする。

+ レイアウト管理変更イメージ
<img width="1070" alt="screen shot 2017-04-11 at 15 34 12" src="https://cloud.githubusercontent.com/assets/8196511/24896176/a65cff68-1ece-11e7-93a5-a6632fca2d21.png">

###  ブロックの見直し

これまでのレイアウト管理で扱ってきた枠の横枠レベルをブロックのサイズとして、ブロック内にHTMLやCSSのコードでレイアウトを調整する形とする。
これまでのブロックで扱ってきた機能単位のものについては、個別にTwigをincludeするコードを書いてもらうことで再利用性を担保する

+ ブロックの変更イメージ
<img width="1054" alt="screen shot 2017-04-11 at 15 50 07" src="https://cloud.githubusercontent.com/assets/8196511/24896166/9d610648-1ece-11e7-944f-242c306724fd.png">

## 関連情報 (Ref)

#2075 
スタイルガイド：  https://github.com/EC-CUBE/Eccube-Styleguide

**Comment by mikakane** [comment]
横の列がなくなるのは助かりますが、仕様的には大丈夫ですかね…

横メニュー的なものを作る場合は、main部分に常に表示させるメニューがある、みたいな仕様になると思うのですが、そのサンプルテーマみたいなものがあると 2カラム希望にも対応しやすいかもしれません。

**Comment by Yangsin** [comment]
> ブロックの見直し
> これまでのレイアウト管理で扱ってきた枠の横枠レベルをブロックのサイズとして、ブロック内にHTMLやCSSのコードでレイアウトを調整する形とする。

について、再度検討中ですが、main 部分については、既存のままシステム側で動的にブロックの有無で１Columnから３Columnまでクラスを出し分けるようにしようとしてます。

**Comment by chihiro-adachi** [comment]
デザイン関連について、以下にドキュメントを作成しています。
http://doc4.ec-cube.net/#%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA
