### ISSUE TITLE
iOSで管理画面-メール配信履歴のメール本文がスクロールできない

### ISSUE THREAD

**Issue by yt1969** [EC-CUBE/ec-cube#2272]
## 概要(Overview)
管理画面-受注管理-メール通知-メール配信履歴-メール本文表示のモーダル画面において、
iOSではメール本文がスクロールできない。

## 期待する内容(Expect)  or 要望 (Requirement)
当該画面でメール本文のスクロールができ、内容確認および閉じるボタンが押せる。

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 7.1.1
+ DB: MySQL 5.6.35

## 関連情報 (Ref)
以下の環境で同様の症状
- iPhone 6s Plus iOS10.3.1 Safari, Chrome
- iPad Air2 iOS10.3.1 Safari, Chrome
- iOS Simulator iOS10.3 Safari

**Comment by yt1969** [comment]
[src/Eccube/Resource/template/admin/Order/mail.twig](https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/admin/Order/mail.twig) にこのスタイルを書いてやると解消するようですが、
ここに書いてしかるべきなのかどうか、どのソースに手を加えるのが妥当なのか判断つきません。
`#mailModal .modal-dialog { height: 100%; }`

**Comment by t-nagahashi** [comment]
@yt1969 様
以下環境にて、動作確認いたしましたがスクロール、閉じるボタン押下ともに動作しております。
端末依存の可能性もあるかもしれませんが、
再度ご確認いただくことは可能でしょうか？

### 検証端末  
 iPhone 6 Plus iOS10.3.1 Safari, Chrome

### 検証サイト  
http://site3.ec-cube.net/

**Comment by yt1969** [comment]
@t-nagahashi 様
確かに検証サイトでは問題ありませんでした。
ローカルMAMPの開発環境、レンタルサーバ上のテスト、本番環境、全てで当該事象になること、
ローカルMAMPで全プラグイン停止、全TWIGテンプレートをオリジナルにしても当該事象になること、
以上よりIssue出しましたが、当方の環境のみの問題かもしれません。
もう少し追い込みます。

**Comment by t-nagahashi** [comment]
@yt1969 様
その後、いかがでしょうか？
解決済もしくは、その後発生しなくなる等であれば、
一旦本issueはクローズさせていただきたいと思います。

**Comment by yt1969** [comment]
@t-nagahashi 様
承知しました。Closeします。

その後いろいろ試行しても状況変わらずお手上げでした。
iPhoneを一度でもローテートさせるとモーダル画面側がスクロールしだすのでそれで逃げています。。。
