### ISSUE TITLE
受注新規登録時、複数配送ができない。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#2279]
## 概要(Overview)
「お届け先を新規追加」ボタンが表示されていません。
（保存後の編集画面では、ボタンが表示され複数配送ができます。）

## 期待する内容(Expect)  or 要望 (Requirement)
受注新規登録時、ボタンが表示され複数配送設定できるようになること。

### 環境 (environment)  
デモサイトにて確認。（http://site3.ec-cube.net/admin/setting/system/system）
+ EC-CUBE: 3.0.14
+ PHP: 7.0.11
+ DB:
  - SQLite version 3.7.17

**Comment by moritahiroo** [comment]
@t-nagahashi いまデモサイトで確認してみたのですが、複数配送を有効にしたら、新規登録時に「お届け先を新規追加」ボタンが表示されました。

**Comment by trebla-on** [comment]
http://site3.ec-cube.net/admin/order/new
動作確認は上の環境で行いました
基本情報設定のSHOPマスター画面で「複数配送を有効にする」を変更しましたその後受注登録画面で「お届け先を新規追加」ボタン表示確認しました。
自分の環境でも同じでした。
特に問題ありませんみたい

ソースも確認しました
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/admin/Order/edit.twig#L517-L520
ボタンの表示条件はDBのdtb_base_info.option_multiple_shippingです

**Comment by t-nagahashi** [comment]
@moritahiroo さん
@trebla-on さん
ご確認ありがとうございます。
たしかに表示されておりました。

見落としかもしれません。
本issueはcloseにいたします。

ありがとうございました。
