### ISSUE TITLE
クローンオブジェクトの場合、関係オブジェクトを複製できません

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2284]
## 概要(Overview)
クローンオブジェクトの場合、関係オブジェクトを複製できません

## 期待する内容(Expect)  or 要望 (Requirement)
関係オブジェクトを複製するようになりたい。

## 再現手順(Procedure)
ドクトリン関係オブジェクトを複数するとき、全て関係オブジェクトをクーロンできません。
例えば、Orderオブジェクトをクーロンする時、関係があるOrder detail/ Shipping/ Shipment item
をクーロン出来ていない。データベースにもOrder detaiなどのレコードを作成しません。

https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Controller/Admin/Order/EditController.php#L63
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Controller/Admin/Order/EditController.php#L71
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Controller/Admin/Order/EditController.php#L78
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Controller/Admin/Order/EditController.php#L81

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: 7.0
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
現時点でcloneが必要な機能がないので実装はしない方針です。
必要なケースがあれば教えてください。
