### ISSUE TITLE
 配送方法が異なる商品がカートにある場合に共通配送方法を正しくない

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2286]
## 概要(Overview)
配送方法が異なる商品がカートにある場合に共通配送方法を正しくない

## 期待する内容(Expect)  or 要望 (Requirement)
配送方法が異なる商品がカートにある場合に共通配送方法を正しく表示できます。

## 再現手順(Procedure)
パーコレーター　：　**商品種別B**
ディナーフォーク　：　**商品種別A**

配送１を設定
![c1](https://cloud.githubusercontent.com/assets/17536702/25167062/341d4c42-2508-11e7-91a8-b1f66c42f2e2.PNG)

配送２を設定
![c2](https://cloud.githubusercontent.com/assets/17536702/25167070/3a07cd94-2508-11e7-8fc9-1c9243f5fe17.PNG)

カートに入れる
![c3](https://cloud.githubusercontent.com/assets/17536702/25167080/47ff9d3c-2508-11e7-8b2a-b72c18ebe034.PNG)

注文確認
![c4](https://cloud.githubusercontent.com/assets/17536702/25167104/54fa7f02-2508-11e7-84a0-a9004a3b17d1.PNG)

共通支払い方法は郵便振替、現金書留、銀行振込ですが、表示しているは現金書留、銀行振込だけ表示しています。

### 環境 (environment)
+ EC-CUBE: 3.0.14
+ PHP: x7.0
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by t-nagahashi** [comment]
重複#2211
