### ISSUE TITLE
２個目の商品をカートへ投入する際、共通支払方法の設定によってカートへ投入できない場合がある。

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2288]
## 概要(Overview)
２個目の商品をカートへ投入する際、共通支払方法の設定によってカートへ投入できない場合がある。

## 期待する内容(Expect)  or 要望 (Requirement)
エラーを表示せず、カートに投入できるようにする。
例）再現手順の場合、カートへ投入でき、支払方法：郵便振替が選択できるようになる。

## 再現手順(Procedure)
ディナーフォーク : 商品種別 A

パーコレーター : 商品種別 B

ショップ設定配送方法管理でDelivery 3という新しい配送方法を作成します。 以下のように配送方法を編集します。

１．Delivery 3　：　郵便振替　　　　　　　　商品種別A

２．サンプル業者2　：現金書留、銀行振込　　商品種別A

３．サンプル宅配1　：　郵便振替、現金書留　商品種別B

設定された後に、ディナーフォークとパーコレーターをカートに入れます。

共通支払い方法がありますが、「お支払方法が異なるためこの商品は同時に購入することはできません。」を表示しています＝＞NG
### 環境 (environment)
+ EC-CUBE: 3.０.14
+ PHP: 7.0
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
#2325 で修正済み
