### ISSUE TITLE
ページレイアウトやブロックに関連した機能改善のご意見相談板

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2289]
## 概要(Overview)

３系のメジャーバージョンアップに向けてページレイアウトやブロックに関連した機能改善のご意見の相談板。
機能の改善方法について、コメントいただいて、議論や 👍  などしてほしいです。

デザインカスタマイズ関してのアンケートも実施中ですので、Issueに直接書きづらい方はアンケートフォームからご意見ください。
https://goo.gl/forms/LqDs0FCD6bd6Yy7u2

## 関連情報 (Ref)

レイアウト管理の単純化とブロックの見直し #2266
フロントのデザインテンプレートでのフォームヘルパーの利用の見直し・分解 #2033

**Comment by Yangsin** [comment]
### ページ毎のレイアウトではなく、レイアウトのパターン化

ページ毎にこまかくレイアウトを設定したり全ページ用のブロックを設定するのではなく、レイアウトパターンを登録できるようにして、各ページのどのレイアウトを適用する

+ メリット
    - 全ページブロックにまつわる変な挙動が置きづらい（ref  #1467)。
    - 複数ページのレイアウトを簡単に変更できる。
+ デメリット
    - 全ページを違うレイアウトにしようとすると前ページ分レイアウトを調整しなければいけない。

**Comment by Yangsin** [comment]
## ページ管理のTOPをページ一覧からレイアウト管理に変更

ページ一覧と同様のことはレイアウト管理のセレクトボックスにあるのでとっとレイアウト管理にいきたい。

**Comment by Yangsin** [comment]
### レイアウト管理からブロックやページの編集に行きたい

レイアウト管理でブロックやmain の部分の編集に遷移できるようにしたい。
遷移せずに編集できるとGood

**Comment by Yangsin** [comment]
### ブロックの絞り込み、ブロックのカテゴリ化

ブロックをこまかく出し分けていると、ブロックの数が大量になってくるので、カテゴリ・グループ化して絞りこめるようにしたい

**Comment by tao-s** [comment]
# ブロックグループの導入
concrete5でもあってとっても便利
- 複数のブロックをまとめたブロック
- 並び順を変えられる
- 何も無いレイアウトの様なもの

**Comment by tao-s** [comment]
# ページ詳細:Mainのブロック化
- 商品一覧とか商品詳細とか丸っとブロックの方が使いやすい

**Comment by pineray** [comment]
ブロックのレイアウトをパターンで制御するのは、パターンが少ないうちは分かりやすいのですが、パターンの数が多くなると逆に管理がしづらくなりそうです。
ただ、パターンが分かれるのは主に表示/非表示だと思うので、そこはブロックごとに制御できるようにすれば良いのではないかと思います。

ブロックごとの表示制御について、たとえばDrupalではブロックごとにどのページで表示するか（表示しないか）を設定できます。

まず、表示設定の選択肢として以下の3つがあり、その下にあるテキストエリアに表示するページのパスを1行ごとにひとつずつ入力します。
・以下のページで表示
・以下のページで非表示
・以下のPHPがTRUEの場合に表示

例えば、「以下のページで表示」を選択して、パスに「cart」とあれば、カートのページでだけ表示されます。

また、「*」がワイルドカードになっていて、たとえば「products/detail/*」と入力すれば、すべての商品詳細ページにその設定が適用されます。

このように、パターンとブロックごとの制御を組み合わせれば、かなり柔軟かつ管理しやすいレイアウトとなるのではないでしょうか。

**Comment by tao-s** [comment]
## ブロックの横幅を制御したい
bootstrapで言うところのcol-sm-6とかの数字の部分を指定できる様にしたいです

**Comment by chihiro-adachi** [comment]
デザイン関連について、以下にドキュメントを作成しています。
http://doc4.ec-cube.net/#%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA
