### ISSUE TITLE
デフォルト機能のプラグイン化

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#23]
2.13系にデフォルトで含まれている機能だが、

* ECとしての役割がうすいもの
* フラグでON/OFF切り替えているもの

を、デフォルトでインストールされているプラグインとして扱う

* 商品レビュー投稿機能
* ポイント機能

**Comment by nanasess** [comment]
現状のプラグインの仕組みでプラグイン化を進めていくのは危険かと。
DI や AOP を使わないと難しいのではないかなーと感じていますが、どこかで話題になってたりしますか？

**Comment by Yangsin** [comment]
[3.0.0の要件](https://github.com/EC-CUBE/ec-cube/wiki/EC-CUBE3.0.0%E3%81%AE%E8%A6%81%E4%BB%B6#%E6%A9%9F%E8%83%BD%E8%A6%81%E4%BB%B6%E8%A9%B3%E7%B4%B0)としてWikiに書きましたが以下で検討しております。

+ 2.13までの標準機能の一部をプラグインに分離予定  
  + メーカー管理
  + レビュー
  + 定休日設定
  + バックアップ
  + 高度なDB設定
  + ガラケー対応

**Comment by Yangsin** [comment]
3.0.0の仕様に関するもののためクローズとします。
