### ISSUE TITLE
管理画面：会員管理＞会員登録・編集

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#231]
## 仕様変更概要

+ 新UIに伴うデザイン調整
+ 登録項目の見直し
  + 必須/非必須の変更 #206
  + 住所自動入力の変更(AjaxZip化)
  + 秘密の質問の廃止
  + ポイント/メルマガのプラグイン化

## 新UIイメージ

http://ec-cube.github.io/eccube3-design/admin/member_regist.html

## 機能

+ 会員登録/編集を行う
+ 国及びZIPコード入力
  + [mtb_constant.form_coutry_enable]が有効な場合、国およびZIPコード入力フォームが有効となる
+ 購入履歴を表示する(編集時のみ)
  + 該当顧客の購入履歴一覧を表示する
      + 受注IDにリンク(受注編集画面へ遷移)

## ER図・DB定義

https://github.com/EC-CUBE/eccube3-doc/blob/eccube-3.0.0-beta/ER-D/ER-customer.xls

## 登録フォーム項目

|項目名|必須|変更内容|
|------------|----------|-----------------|
|会員ID | 必須 | 自動採番 | 
|会員状態 | 必須 | mtb_customer_status、 仮会員・本会員 | 
|お名前 | 必須 | 変更なし |
| お名前(フリガナ) | 必須|変更なし|
| 会社名 | 必須でない|変更なし|
| 国コード | 必須でない | mtb_constant.form_coutry_enable がTRUEの場合|
| Zipコード | 必須でない | mtb_constant.form_coutry_enable がTRUEの場合|
| 郵便番号 | 必須|変更なし|
| 都道府県 | 必須|変更なし|
| 住所1 | 必須|変更なし|
| 住所2 | 必須|変更なし|
| 電話番号 | 必須|変更なし|
| FAX | 必須でない|変更なし|
| メールアドレス | 必須|変更なし|
| 性別 | 必須でない|必須をやめる|
| 職業 | 必須でない|変更なし|
| 生年月日 | 必須でない|変更なし|
| 希望するパスワード | 必須|変更なし|
| メールマガジンの送付について |-- |項目削除|
|SHOP用メモ| 必須でない | |
|所持ポイント | -- | 項目削除 |

## 購入履歴

+ 購入履歴があれば表示
  +  購入日
  + 注文番号
  + 購入金額
  + 発送日
  + 支払い方法

**Comment by tamagoya** [comment]
仕様の変更点を追加
* 電話番号の個々の桁数
  * 2.12系 tel_item_len(6)以下かどうかをチェック
  * 3系 tel_item_lenを使わず2～3(or4)の範囲でチェック

**Comment by Yangsin** [comment]
バグは別途Issue報告もらっていますので、初期実装として本件はクローズします
