### ISSUE TITLE
論理削除の見直し

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#2314]
## 概要(Overview)
現状、`del_flg`を使った論理削除と`SoftDeleteFilter`によって整合性が取れていない場合がある。また、論理削除したデータを容易に戻すことはできない。
論理削除するのではなく、それぞれに合ったステータスに変更することで整合性を保つようにする。
すべてテーブルにおいて論理削除をやめるには影響範囲が大き過ぎるため、主要なテーブルのみ対応する。

## 期待する内容(Expect)
以下のテーブルをそれぞれステータス変更によって論理削除しないようにする。

|テーブル|削除に代わるステータス|
|---|---|
|dtb_customer|退会|
|dtb_order|キャンセル/現状の削除機能はなくす|
|dtb_product|廃止|
|dtb_product_class|廃止|
|dtb_shipping|キャンセル|

- テーブルの`del_flg`は削除
- Entityの`delFlg`は`deprecated`にして残す
- プラグイン側は個別に対応が必要

## 関連情報 (Ref)
#846

**Comment by Yangsin** [comment]
削除フラグではなくステータスであつかうので、管理画面からも見える状態となる予定。

**Comment by kiy0taka** [comment]
https://gist.github.com/kiy0taka/91718c9ae59c098fec573b9bd1644db4

**Comment by okazy** [comment]
4.0系で対応済のためクローズします。
