### ISSUE TITLE
【管理画面】icon_sortableの横幅が画面幅に左右されることによる不具合

### ISSUE THREAD

**Issue by arkikushima** [EC-CUBE/ec-cube#2344]
## 概要(Overview)
カテゴリ編集画面等にあるicon_sortableがブラウザの画面幅によって横幅が変わるため、
カテゴリ名のリンクに重なってしまうことがあり、リンクがクリックできなくなります。

## 期待する内容(Expect)  or 要望 (Requirement)
icon_sortableのwidthを固定の値にし、画面幅に左右されないようにしたい。

**Comment by t-nagahashi** [comment]
@arkikushima 様
以下のデモサイトにて確認をしましたが、
再現できませんでした。（もしくは、現象を勘違いしているかもしれません。）
http://site3.ec-cube.net/admin/product/category/4

画面キャプチャをはっていただくことは可能でしょうか？

**Comment by arkikushima** [comment]
@t-nagahashi 様

うまく説明ができずすみません。

![icon_sortableの横幅が画面幅に左右されることによる不具合](https://cloud.githubusercontent.com/assets/20698371/26568763/070ce290-4541-11e7-8cb1-559a396cd8d5.JPG)

icon_sortableのdivの横幅が画像のようにタイトルに被ってしまいます。
タイトルが長ければそれほど気にはなりませんが、短いものだとリンクの検知がシビアになります...。
ウィンドウサイズは横 : 1920  ×  縦 : 950で表示しています。
