### ISSUE TITLE
3.1.0-alpha2のインストール

### ISSUE THREAD

**Issue by shiro8** [EC-CUBE/ec-cube#2362]
## 概要(Overview)
/src/Eccube/Resource/doctrine以下のファイルが削除されない？

## 期待する内容(Expect)  or 要望 (Requirement)
こちらで、聞いて良いのか良くわかりませんでしたが・・・
3.1.0a2を色々触って見ようと思っているのですが、インストールでコケてます。
GitHub内でのテストリリース版のパッケージ内ファイル構成もどのような流れなのかが良くわかっていないので、恐縮なのですが、どなたか教えて頂けませんでしょうか。

3.1では、使用していない不要なテーブルを削除するというISSUEに対応した？ような事を読みましたが、3.1.0a2のインストール時にコケる原因を追ってみると、どうも、

/src/Eccube/Entity以下のファイルは削除されているのですが、
/src/Eccube/Resource/doctrine以下のファイルが削除されておらず、

そこで不整合が起きているように思えます。

symfony doctrineの仕組み上、この状態ではエラーが出るのが通常のような気がするのですが、3.1.0a2をインストールされる際に、そのようなエラーは出ませんでしょうか？
弊社環境だけなのかな？

## 再現手順(Procedure)
3.0系と同様のインストール手順
インストーラー起動して画面は進みますが、DBクリエイトでエラー。

【インストールlog】
app.CRITICAL: Doctrine\Common\Persistence\Mapping\MappingException: Class 'Eccube\Entity\CategoryCount' does not exist (uncaught exception) at /vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php line 96 {"exception":"[object] (Doctrine\\Common\\Persistence\\Mapping\\MappingException(code: 0): Class 'Eccube\\Entity\\CategoryCount' does not exist at /vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:96)"} []

ファイルを修正諸々やって試そうかとも思いましたが、そもそも、テスト版リリースパッケージの同梱内容の流れ（差分だけ追加？または必要なファイルは自分で正式版から持ってくる必要がある？）などが良く理解できていない為、愚問かも？・・・とか、思いましたが、こちら質問させていただきました。
どなたか教えて頂ければ幸いです。

### 環境 (environment)
+ EC-CUBE: 3.1.0a2
+ PHP: 5.6.29 
+ DB: 
  - MySQL 5.6.35

**Comment by chihiro-adachi** [comment]
@shiro8 すみません、3.1-a2はwebインストーラに不具合があり、DBの作成の部分でこけるるかと思います。

[コマンドラインのインストーラ](http://doc.ec-cube.net/quickstart_install#インストールスクリプトを利用したインストール方法)を試していただくか、[experimental/3.1ブランチ](https://github.com/EC-CUBE/ec-cube/tree/experimental/3.1)の最新のコードであれば修正済なので更新してみていただけますでしょうか。
