### ISSUE TITLE
管理画面：会員管理＞会員登録・編集の画面の修正漏れ

### ISSUE THREAD

**Issue by tamagoya** [EC-CUBE/ec-cube#239]
会社名の入力項目が無い。

**Comment by tamagoya** [comment]
zipcodeと、country情報も入力項目が無い。

**Comment by Yangsin** [comment]
> zipcodeと、country情報も入力項目が無い。
ZipcodeとCountryは越境との統合を改めて見なおすタイミングで実装するものとして、3.0.0では見送ります。
