### ISSUE TITLE
金額入力項目にカンマつきで保存した場合、エラーになる

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2392]
## 概要(Overview)
タイトルに同じ。

## 期待する内容(Expect)  or 要望 (Requirement)
`,`の場合は、エラーにならないように制御。
※海外の場合`,`のかわりに`.`を使用する場合があるので、その辺を考慮するかどうか要検討
※対象画面の洗い出しが必要。

## 再現手順(Procedure)
受注編集、ショップマスターの金額画面にて確認（他画面も同様の動きのはずです）
金額2800円入力
→編集画面を開き、2,800→2,8002とする
→エラー発生

### 環境 (environment)
+ EC-CUBE: 3.0.15
+ PHP: 7.0.9
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by t-nagahashi** [comment]
現状の仕様で問題無しとします。
金額の誤入力を防ぐため、カンマ区切り入力時はカンマの位置をチェックする仕様のままとします。
