### ISSUE TITLE
非公開商品でも商品詳細画面にて表示される

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/ec-cube#2395]
## 概要(Overview)
when product is set 非公開, Customer can see product detail

## 期待する内容(Expect)  or 要望 (Requirement)
非公開商品は表示しない。（2系と同じ挙動）

## 再現手順(Procedure)
直接URLをアクセスするとき、非公開商品でも商品詳細画面を表示する。
パーコレーター　：非公開
例：http://localhost:27560/html/products/detail/2
をアクセスすると、表示する。

### 環境 (environment)
+ EC-CUBE: 3.0.15
+ PHP: 7.0.9
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by k-yamamura** [comment]
管理画面にログインしていれば同一ブラウザだと非公開商品でも表示されます。
管理画面にログインしていない状態か、別ブラウザで再度ご確認ください。

**Comment by t-nagahashi** [comment]
https://github.com/EC-CUBE/ec-cube/issues/2395#issuecomment-312764240 に記載いただいている内容と同様の挙動をしており、仕様のため本件Closeします。
