### ISSUE TITLE
出荷管理機能の実装（購入と配送関連のデータの見直しを伴う）

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2408]
## 概要(Overview)

受注管理機能を実装し、複雑な出荷情報への対応や配送業者との連携をしやすくする

## 期待する内容(Expect)  or 要望 (Requirement)

複数配送や別送・同梱など集荷と受注は必ずしも１；１ではないが、EC-CUBEでは受注に情報が集約されているため、受注管理画面が複雑化・複数配送の仕様が扱いづらい状況になっている。
配送システムやサービスとの連携、同梱や別送などのカスタマイズ性の向上のために、受注データの構造も見直す

これに併せて、受注編集画面でのお届け先編集機能は、出荷編集機能へ移行する

### 出荷マスター

出荷伝票ごとに、出荷先を一覧表示する。
以下の項目を表示する。(表示項目は要検討)

- 配送番号
- 出荷伝票番号
- お届け先名
- お届け先住所
- お届け予定日
- 発送日

また、外部システムと連携用の出荷CSVファイルをダウンロードできる

### 出荷登録・編集

- 出荷対象の注文を表示する。注文番号、注文名、住所を表示する。注文番号から、受注編集画面へリンクする
- お届け先内容を編集できる
- 出荷対象の受注明細一覧を表示する。値引きや支払い手数料など、出荷対象と関係ない明細は表示しない
- 出荷伝票に記載するメモを登録・編集できる
- 出荷済みとして、出荷日時を登録できる
- 出荷管理に登録されていない、注文の明細を検索し、登録できる
- 出荷伝票番号を登録・編集できる

その他、運用に必要な機能は随時検討し、実装する

## 関連情報 (Ref)

#654
#2322

**Comment by Yangsin** [comment]
[出荷管理ユースケース図.pdf](https://github.com/EC-CUBE/ec-cube/files/1413277/default.pdf)

**Comment by okazy** [comment]
4.0系ではユーザヒアリングの結果、受注管理を充実させることで対応しました。
