### ISSUE TITLE
プラグインの優先度制御仕様

### ISSUE THREAD

**Issue by aminotsukasa** [EC-CUBE/ec-cube#242]
プラグイン毎の優先度制御の方法を考えてみました。
ご意見よろしくお願いします。

# EC-CUBE3 Plugin間の優先度制御

## 課題
稼働環境に同じイベントをフックする複数のプラグインを同時にインストールし、各プラグインのイベントハンドラがパラメータを書き換える場合、書き換える順序によっては想定しない動作が発生する恐れがある。
さらに、監査、ロギング、デバッグ用等で他のプラグインより必ず先又は後で起動する必要のあるハンドラの起動順序を制御したい

##### 例
購入時のFormEventをカード決済プラグインと後払いプラグインのイベントハンドラが書き換える場合、後のハンドラが書き換えるフォーム要素を前のプラグインが削除している可能性がある

## 対策
管理画面からユーザが各イベントのハンドラの起動順を設定できるようにする
例：後払い(3)→カード決済(2) →監査(1)の順でFormEventのイベントハンドラが起動
起動順序は管理画面等からDB上のハンドラ優先度テーブル（仮）に保持する。
SymfonyのEventDispatcher の仕様に合わせて実行順は-511～+511の降順とする

### テーブル構成
ハンドラ優先度テーブルは以下のフィールドを保有する

* id:int    (サロゲートキー)
* event:string not null (イベント名)
* priority:int not null (優先度)
* plugin_id:int not null(プラグインID)
* handler:string not null(ハンドラ名)

    event,priorityの2フィールドでユニーク

## 起動優先度とハンドラ種別

* 優先度は+400～-399は**通常型ハンドラ**用とする
* 優先度-400～-499は**後発型ハンドラ**用とする(デバッグ、監査用を想定)
* 優先度+500～+401は**先発型ハンドラ**用とする(同上)
* 優先度0は実行時にハンドラを登録しない(ハンドラを無効化)

## プラグインインストール時の動作

* 各プラグインのgetSubscribedEvents内のイベントハンドラと優先度をハンドラ優先度テーブルに挿入する
* 当該イベントにハンドラが1件も登録されていない場合のデフォルト優先度は以下のとおり
* * 先発型:500
* * 通常型:400
* * 後発型:-400

* ハンドラが既に登録されている場合、既に存在する同型ハンドラ
のイベントの優先度の最大値-1を登録する
（ハンドラが既に400に登録されている場合に通常ハンドラを登録すると399に登録される）
* ハンドラ種別毎に決められた優先度枠に空きがない場合、プラグインのインストールは失敗する

## Webアプリケーション実行時の動作

* プラグインのイベンドハンドラをディスパッチャに登録する際(Application.php等)、優先度テーブルの優先度(昇順)に各ハンドラを登録する
* イベントが実際に発生すると登録された順にハンドラが起動する
* 優先度テーブルに登録されていないイベントハンドラがプラグインに定義されている場合、優先度-500(全てのハンドラの後)とみなされる

## ハンドラ優先度変更画面の動作
* 各ハンドラの優先度をユーザ入力に基づいてアップデートする
* ただし、優先度はハンドラ種別（通常、先発、後発）毎の範囲内に限定される

## プラグイン開発者への影響

* getSubscribedEventsはハンドラのメソッド名と優先度（数値）を返すが、メソッド名と種別（通常、先発、後発）を返すように変更
* （開発者向けの指針）通常型プラグインとの衝突を防ぐため、先発型、後発型のハンドラでは渡されたパラメータを書き換えないことが望ましい

**Comment by aminotsukasa** [comment]
優先度ベースのSysVのinitスクリプト風にしてみました

**Comment by aminotsukasa** [comment]
UpstartやSystemdの起動スクリプトのような依存関係を設定するというのも考えたのですが、

例：
Apacheの起動スクリプトにAfter:Network,MySQL と設定するとNetworkとMySQLが起動してからApacheが起動する

ちょっとユーザにとって複雑になりすぎるかもしれないので、シンプルにしてみました。

**Comment by ttsuru** [comment]
少し関連が少ないかもしれませんが、Bolt (https://github.com/bolt/bolt) のような形のプラグインローディング構造としていただきたいです。

https://docs.bolt.cm/extensions/introduction

Composerでのインストールと同様の形式として、composer.json によりインストールやautoloadに対応して欲しいと思います。

理由として、PHP界のデフォルトとなっていること、プラグインのテストが容易なこと、外部のプラグインの依存関係を自動で解決してくれることがあります。
現状の自動登録型ですと、外部ライブラリを使うこともできません。

**Comment by aminotsukasa** [comment]
@ttsuru 
大変ご尤もです。
是非プルリクをお待ちしています。

**Comment by Yangsin** [comment]
@ttsuru @aminotsukasa 
プラグインの優先度制御の対象として想定しているものは現行の決済モジュール等のオーナーズストアで配布されているものの制御が基本だと思います。
優先順位の調整を行う仕組みとしては aminotsukasa の方法でよいかと思います。

ただ、3系の開発スタイルとして、2.13系までのコードを直接カスタマイズするスタイルは推奨されず、できるだけプラグインのように開発していくことを考えると、ttsuruのような、ソースを直接配置型も、ハンドラテーブルに加えられるか、ハンドラにないプラグインをロードする仕組みは必要そうですね。
ただ、ソース配置型も優先順位の制御をしたければハンドラテーブルを利用するようにプラグインを作る事になると思います。

念のため、ふれておきますが、オーナーズストアの仕組みを無くすようなことはありません。

**Comment by ttsuru** [comment]
@Yangsin 
Boltの場合にはComposerのPackageやAutoloadの仕組みを利用してますが、インストールはモジュールのようにオンラインから直接インストールできる仕組みになっています。

**Comment by Yangsin** [comment]
@ttsuru 
既存の仕組みを3のPlugin機構の仕組みに合わせて変えるべきところは変えますが、プラグインのインストールの特に通信周りの仕様は、Silexの機構とは別でEC-CUBE全体のビジネスとも影響するので、現時点では既存のオーナーズストアのモジュールの仕様・仕組みから大きく変える必要性はないと思っています。
特に有料のプラグインなどもありますので、Composerを完全に主とするには課題がおおいと思ってます。

もちろん、選択肢として、Composerを使ったインストールの仕組みをなどを利用したい方は利用しても動くようにはしておかなければというとこですね。

**Comment by ttsuru** [comment]
@Yangsin 
おそらく、現状のようなzipで固めた形式も、Boltでは対応しており、同様の方向で解決するかと思います。
Yangsin さんがおっしゃられているのはおそらく、Composerではなく、Packagistでの配布という話ではないでしょうか。
Composerはインストールの依存関係を解決する仕組み(RailsでいうBundler)で、Packagistが配布パッケージの登録サイトになっています。(以前のpear.php.netのようなもの)

Composerと言っているのはインストールやAutoload、依存解決の話のことで、配布と言った話ではありません。

**Comment by Yangsin** [comment]
@ttsuru 
私もまだまだ理解ができていない部分が多いですが、採用できる可能性もありそうですね。インストールについては、3.0.0に入れるのは難しいかもしれませんが、一度実装イメージをPRいただくか、別Issueで一度もませていただければと存じます。
本スレの主題である、優先度制御など、競合に関するアプローチや実装イメージについてはどうでしょうか。

**Comment by ttsuru** [comment]
@Yangsin 
了解しました。こちらは別件として捉えておきます。
優先度制御については私の方では特に気になったことはありません。
競合に関しては現状の仕組みではある程度は致し方ない部分もあるのかなと思います。

1点だけあるとすれば、フックポイントで使われている routing_name を_から.に置き換えている部分は置き換えない方が良いかと思います。

Routing名が product_detail の場合
```
product.detail.before
-> eccube.product_detail.before など
```

**Comment by Yangsin** [comment]
@ttsuru 
ご意見ありがとうございます。

> フックポイントで使われている routing_name を_から.に置き換えている部分は置き換えない方が良いかと思います。

確かにそうですね！

**Comment by aminotsukasa** [comment]
SymfonyのEventDispatcher を調べていたら、同じイベントに優先度の違うハンドラが複数登録されている場合、降順に実行されるようです。

というわけでこの仕様の優先度も降順に変更しますorz

**Comment by Yangsin** [comment]
現仕様でWikiにおこしましたので一度Issueはとじます。

https://github.com/EC-CUBE/ec-cube/wiki/Plugin%E3%83%8F%E3%83%B3%E3%83%89%E3%83%A9%E3%83%BC%E3%81%AE%E5%84%AA%E5%85%88%E5%BA%A6%E5%88%B6%E5%BE%A1%E4%BB%95%E6%A7%98
