### ISSUE TITLE
テンプレートへの介入方法の見直し

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#2440]
## 概要(Overview)

3.0ではテンプレートへの介入方法には以下の2種があります。

- Templateフックポイント
  - twigのテンプレートコードに対する介入
- Responseフックポイント(〜3.0.8まではAfter/Renderフックポイント)

  - レンダリングされたhtmlに対する介入

いずれも、htmlのidやclassを目印に追記や書き換えを行うもので、以下のような課題がありました。

- パーツが表示されないなど、プラグイン間の競合やカスタマイズ時の影響を受けやすい
- デザイン、コーディング時に、html構造を標準のテンプレートに準拠させる必要があり、デザインの自由度を下げる

EC-CUBE本体としても以下の課題を抱えています。

- テンプレートのhtml要素に大量のidが振られており、可読性を下げる
- html構造の変更を伴う不具合修正を行いにくい

## 見直し案

プラグインから介入する形式ではなく、利用者にショートコードを埋めてもらう形式を推奨します。

現状でも、任意の位置にショートコードを埋めて表示させるような実装を行っているプラグインは、いくつか見受けられます(クーポンプラグインなど)。

ショートコードの作成には、#2263 で実装された、ユーザ定義ブロックを追加する仕組みを利用します。

### ブロックの作成
app/Plugin/TwigUserFunc/Resource/template/hello_block.twig
```twig
{% block hello %}
    <h1>Hello, {{ name }}!</h1>
{% endblock %}
```
### サービスプロバイダでブロックを追加
app/Plugin/TwigUserFunc/ServiceProvider/TwigUserFuncServiceProvider.php
```php
$app->extend('eccube.twig.block.templates', function($templates) {
    $templates[] = 'TwigUserFunc/Resource/template/hello_block.twig';
    return $templates;
});
```

`eccube.twig.block.templates`をextendし、作成したブロックを追加します。

### 呼び出し側のコード
xxx.twig
```
{{ eccube_block_hello({'name':'EC-CUBE'}) }}
```
`eccube_block_[作成したブロック名]()`で呼び出すことができます。

### プラグインからブロックへのデータの受け渡し

プラグインからブロックにデータを受け渡す場合は、Templateフックポイントを使用してください。

XxxEvent.php
```php
public function onTemplateXxx(TemplateEvent $event)
{
    $args = $event->getArguments();
    $args['name'] = 'hoge';

    $event->setArguments($args);
}
```

ブロックの作成サンプル
https://github.com/EC-CUBE/ec-cube/tree/experimental/3.1/app/Plugin/TwigUserFunc

**Comment by okazy** [comment]
twigブロックを使う必要はなく、includeで対応可能です。

**Comment by chihiro-adachi** [comment]
更新済のため、クローズします
https://github.com/EC-CUBE/sample-payment-plugin/pull/28
