### ISSUE TITLE
タグ管理機能の実装

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2464]
## 概要(Overview)

タグもカテゴリの様に専用の編集機能を用意する

## 期待する内容(Expect)  or 要望 (Requirement)

タグはマスターデータ扱いになっており、追加方法がシステム設定→マスターデータ管理でテーブルを選択して追加という形になっておりわかりづらい。
ショップの運用に合わせて追加・削除・変更が行いやすいようにカテゴリーと同様に専用の画面を用いたい

ワードプレスの用に商品登録時にその場で追加していく方法もあるが、簡単に追加できるようにしすぎると、ご表記やその商品だけのものとなってしますため、ECサイトの運用ではタグ自体は別途リスト管理するような形にして商品登録画面でタグが追加できるようにはしない想定

**Comment by okazy** [comment]
タグ機能の仕様について考えました。
改善点がございましたらご指摘よろしくお願いいたします。

## 方針
- 以下の2種類の方針がある。
  1. タグ管理の画面で共通タグを登録し、商品編集画面でタグを選択する
  2. 商品編集ページで自由にタグの登録ができる
- 以下の理由によりEC-CUBEでは `i.` の方針とする
  - 商品間で表記を統一したい。また、誤表記を避けたい。
  - 共通のタグの方が管理がしやすく、機能拡張も容易である。

## 仕様案
- `管理画面 -> 商品管理 -> タグ管理` の画面を新しく追加する
  - タグ登録
    - 入力項目
      - ID        : 自動採番。現在は入力項目となっているが、変更する必要もないので自動採番の方が問題が起きにくいと思います
      - タグ名    : 画面表示名、テキスト入力、日本語入力可能
  - タグの削除
    - `mtb_tag` から物理削除
    - 商品とタグの紐づけはすべて削除
      - 商品ごとにタグを取っていく作業は商品数が多い場合に現実的ではない
      - 削除前に紐づく商品が存在する場合は確認のアラートを表示
- `フロント画面 -> 商品一覧` の画面
  - 商品ごとにタグを表示する

**Comment by Yangsin** [comment]
タグ管理の画面イメージ
https://invis.io/F8E5814UV#/258987314_-----

**Comment by okazy** [comment]
4.0で実装済のためクローズします。
