### ISSUE TITLE
3.0.15正式リリース版のショッピングカートページの不具合

### ISSUE THREAD

**Issue by shiro8** [EC-CUBE/ec-cube#2472]
## 概要(Overview)
既知の問題かもわかりませんが、3.0.15リリース版のショッピングカートページで、drawerの表示ができないようです。

## 期待する内容(Expect)  or 要望 (Requirement)
修正版のリリース、もしくはユーザーに告知。

## 再現手順(Procedure)
調査した結果、おそらくですが
/src/Eccube/Resource/template/default/Cart/index.twig

の最後(194行目付近)の</div>タグが1つ多い気がしますがいかがでしょうか。

削除すると正しいと思われる動作になります。

※一応、ロックオン様のデモサイトでも同現象が再現しているようです。
※3.0.14までは</div>タグの数はあっていると思われます。

ご確認の程よろしくおねがいいたします。

### 環境 (environment)
+ EC-CUBE: 3.0.15
+ PHP: 5.6.29 
+ DB:
  - MySQL 5.6.35

**Comment by t-nagahashi** [comment]
@shiro8 様
ご報告ありがとうございます。
たしかに、表示されなくなっております。
こちらで対応いたします。

![image](https://user-images.githubusercontent.com/13776434/29950821-4964f310-8ef9-11e7-95fe-59dfe7bd2904.png)

**Comment by ryo-endo** [comment]
#2488 で修正を行いましたので、こちらのIssueをCLOSEさせていただきます。
