### ISSUE TITLE
dtb / mtb テーブル名等の見直し

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#2505]
## 概要(Overview)
既存のdtb / mtbテーブルで利用していないテーブルや、適切でないテーブル名の見直しを行う。

## 期待する内容(Expect)  or 要望 (Requirement)
* 現在のテーブル一覧

|テーブル名|論理テーブル名|見直対象|
|:-|:-|:-:|
|dtb_authority_role|権限テーブル|-|
|dtb_base_info|店舗情報|-|
|dtb_block|ブロック情報|-|
|dtb_block_position|ブロック記事情報|-|
|dtb_category|カテゴリ情報|-|
|dtb_class_category|規格分類情報|-|
|dtb_class_name|規格情報|-|
|dtb_csv|CSV情報|-|
|dtb_customer|会員情報|-|
|dtb_customer_address|お届け先情報|-|
|dtb_customer_favorite_product|お気に入り商品情報|-|
|dtb_delivery|配送業者情報|-|
|dtb_delivery_date|商品発送日|-|
|dtb_delivery_fee|送料情報|-|
|dtb_delivery_time|配送時間除法|-|
|dtb_help|会員規約情報|-|
|dtb_layout|レイアウト|◯|
|dtb_mail_history|受注メール送信履歴|-|
|dtb_mail_template|メールテンプレート情報|-|
|dtb_member|管理者情報|-|
|dtb_news|新着情報|-|
|dtb_order|受注情報|-|
|dtb_order_detail|受注詳細情報|-|
|dtb_page_layout|ページレイアウト情報|◯|
|dtb_page_layout_layout|ページレイアウト関連情報|◯|
|dtb_payment|支払い方法情報|-|
|dtb_payment_option|配送支払関連情報|-|
|dtb_plugin|プラグイン情報|-|
|dtb_plugin_event_handler|プラグインイベントハンドラー用|-|
|dtb_product|商品情報|-|
|dtb_product_category|商品カテゴリ関連|-|
|dtb_product_class|商品規格情報|-|
|dtb_product_image|商品画像|-|
|dtb_product_stock|商品在庫情報|-|
|dtb_product_tag|商品タグ関連|-|
|dtb_shipment_item|配送商品情報|◯|
|dtb_shipping|お届け先情報|-|
|dtb_tax_rule|消費税ルール|-|
|dtb_template|テンプレート情報|-|
|mtb_authority|管理者権限マスタ|-|
|mtb_country|国マスタ|-|
|mtb_csv_type|CSV出力情報|-|
|mtb_customer_order_status|会員表示用受注ステータス|-|
|mtb_customer_status|会員ステータス|-|
|mtb_db|データベース種別|◯|
|mtb_device_type|端末種別|-|
|mtb_disp|公開フラグ|-|
|mtb_job|職業マスタ|-|
|mtb_order_item_type|受注明細種別|-|
|mtb_order_status|受注ステータス|-|
|mtb_order_status_color|受注ステータス色|◯|
|mtb_page_max|ページ最大表示数|-|
|mtb_pref|都道府県マスタ|-|
|mtb_product_list_max|商品一覧最大表示数|-|
|mtb_product_list_order_by|商品並べ替え情報|-|
|mtb_product_type|商品種別マスタ|-|
|mtb_sex|性別マスタ|-|
|mtb_tag|タグ|-|
|mtb_taxrule|課税規則マスタ|◯|
|mtb_tax_display_type|課税表示種別|-|
|mtb_tax_type|課税種別|-|
|mtb_work|管理者稼稼働状況|-|
|mtb_zip|郵便番号|◯|

### 変更対象テーブル

* 利用していないため削除するテーブル

|テーブル名|論理テーブル名|
|:-|:-|
|mtb_db|データベース種別|
|mtb_order_status_color|受注ステータス色|
|mtb_zip|郵便番号|

* テーブル名を見直しするテーブル

|テーブル名|論理テーブル名|名称変更|
|:-|:-|:-|
|dtb_layout|レイアウト情報|dtb_layout|
|dtb_page_layout|ページレイアウト情報|dtb_page|
|dtb_page_layout_layout|ページレイアウト関連情報|dtb_page_layout|
|dtb_shipment_item|配送商品情報|dtb_order_item|
|mtb_taxrule|課税規則マスタ|mtb_rounding_type|

* 新規に追加するテーブル

テーブル名|論理テーブル名|備考|
|:-|:-|:-:|
mtb_product_status|商品ステータス|mtb_dispに変わり商品用ステータスを新規作成

## 関連情報 (Ref)
変更したい、したくないテーブル名等があればコメントに追加をお願いします。

**Comment by nanasess** [comment]
課税規則マスタは、丸め処理種別なので `mtb_rounding_type` とかが妥当ですかね。
Java では RoundingMode ですね。
https://docs.oracle.com/javase/7/docs/api/java/math/RoundingMode.html

**Comment by chihiro-adachi** [comment]
dtb_category.hierarchy、エンティティではCategory.levelのままなので、合わせてしまってもいいかもしれません。

**Comment by chihiro-adachi** [comment]
フラグ系のカラムもsmallintではなくbooleanに統一でよいかもしれません。

**Comment by kiy0taka** [comment]
主キーが`id`だったり`<テーブル名>_id`だったりするので、`id`に統一したいです。

**Comment by okazy** [comment]
対応済のため完了します。
