### ISSUE TITLE
Order / ShippingItem / Shipping で紐付いているオブジェクト達の関連を見直したい

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2507]
## 概要(Overview)

- Product, ProductClass, Payment, Delivery 等、関連するテーブルにおいて、購入時点のスナップショットを文字列として保持しているが適切に扱えてない箇所がある
- 画像も適切に扱えていない
- そもそも、外部参照制約は不要ではないか

## 検証した内容(Experiments)

Payment の参照をはずしてみましたが、 Form まわりが 関連するオブジェクトを参照しているので、かえって複雑化してわかりづらい。
https://github.com/nanasess/ec-cube/commit/d3f583fc370942d25de452cfdb3f695b6c760b4a

- データ構造としては、 Payment や Delivery, Product の関連テーブルは、参照ではなく、購入時点のコピーを持つのが正しい
- Symfony や Doctrine としては、外部参照制約の方が扱いやすい
- 画面に表示する名称や、お届け時間などのみ、購入時のコピーを保持し、オブジェクトは外部参照させるのが適切と思われる

## 期待する内容(Expect)  or 要望 (Requirement)

- 購入履歴、受注の初期表示など、過去のデータを参照する場合は、購入時のコピーである文字列を表示し、外部オブジェクトを参照しない
  - 商品名
  - 規格名
  - 規格分類名
  - 単価
  - 税率
  - 支払方法
  - 配送業者
  - お届け予定日
  - お届け時間
  - 送料
- 受注編集時は、編集した箇所の文字列を更新する
- お届け時間について #2358 の問題があり、Shipping に関連していても、削除しなければならないケースがある
  - 送料(DeliveryFee) についても同様
  - **Shipping の外部参照制約には不要と思われる**
## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/issues/2236
配送業者関連の実装が不十分

https://github.com/EC-CUBE/ec-cube/issues/2358
3.n からは物理削除できない

https://github.com/EC-CUBE/ec-cube/issues/1932
物理削除できない、が正しい

https://github.com/EC-CUBE/ec-cube/commit/cd55ae9468ab6c1c9c48625cf2a639f05f48ce38
関連テーブルは nullable=true にする

**Comment by okazy** [comment]
対応済のためクローズします。
