### ISSUE TITLE
EC-CUBE3 beta 2 のインストールがうまくいきません

### ISSUE THREAD

**Issue by benzookapi** [EC-CUBE/ec-cube#251]
以下のサイトから入手、およびこのリポジトリからダウンロードしたzipでVer3のBeta2のインストールをしましたが、正しく動作していないように思えます。
http://www.ec-cube.net/product/info_3.php#page4

Beta1は同じ環境、同じ手順で正しくインストールできたので、Beta2になって何かインストール方法や依存環境が変わっていたら教えてください。

事象：

１）インストール後の画面が崩れていたり、デザインが欠けている。
（MacのChrome、Fireofox、Safatiすべてダメでした。Chromeでデバッグするとfunction.jsで大量のエラーが出ているようです）
会員メニューなどが表示されてないので、登録は購入フロー内で行いました。
会員登録と購入自体はできます。

２）adminがモック画面しかでない。（ログインして使えない）

やったこと：

Beta1のディレクトリは退避して、同じ名前のディレクトリにBeta2をインストール。
DBも同じものだが、一回DROPして再作成。
.composerなどのキャッシュはBeta1時から削除などしていない。

１）上記からダウンロードしたzipを/var/www/html以下に展開し、以下のようにeccube_install.shを修正して、実行。

SHOP_NAME=${SHOP_NAME:-"EC-CUBE3 Beta2"}
HTTP_URL=${HTTP_URL:-"http://*********/eccube3/html/"}
HTTPS_URL=${HTTPS_URL:-"http://*********/eccube3/html/"}
ROOT_URLPATH=${ROOT_URLPATH:-"/eccube3/html/"}
DOMAIN_NAME=${DOMAIN_NAME:-""}
ADMIN_DIR=${ADMIN_DIR:-"admin"}

DBSERVER=${DBSERVER-"127.0.0.1"}
DBNAME=${DBNAME:-"eccube3"}
DBUSER=${DBUSER:-"root"}
DBPASS=${DBPASS:-"*********"}

＊Beta1も同様の設定

２）途中、symfony/console suggests installing ...系のダンプが大量にでるが（これはBeta1もだった気がします）、インストール自体は成功する。最後のmigrationだけエラー（Beta1ではこの処理はなかったです）

３）http://*********/eccube3/html/　にアクセスすると真っ白
ap.cponf/.../constant.ymlとほかいくつかのファイルのオーナーがwww−dataになっていて、パーミションが異なっていたので、とりあえず、ディレクトリ全部のパーミションを777にして回避

４）画面はでるようになり、上記の操作はできるようになるが、http://*********/eccube3/html/adminにアクセスするとモック画面がでてログインできない

５）app/.../log/site.logをみると、favicon.icoがないなどのエラーあり。

６）ためしにおなじ手順をBeta1のzipで試すが、こちらだとうまくいく。（Beta1だと３のパーミション変更はいらない）

＊所感では、Viewまわりのセットアップがうまくいってなくて、UIとroutingがうまく動いていない印象をうけます。

スクリーンショットを添付します。

ご回答よろしくお願いします。
![e1](https://cloud.githubusercontent.com/assets/899580/7955965/50504422-0a17-11e5-9391-6c607689c821.png)
![e2](https://cloud.githubusercontent.com/assets/899580/7955966/50535e0a-0a17-11e5-8a29-0c18c4a3811d.png)
![e3](https://cloud.githubusercontent.com/assets/899580/7955967/5056cc48-0a17-11e5-9840-415e5edded41.png)

**Comment by shinichi-takahashi** [comment]
@benzookapi 
取り急ぎの回答となりますが、スクリーンショットの１枚目、２枚目は、現状その表示が正しい状態です。
本バージョンでは、商品と会員まわりの動作・デザインをご確認いただけるバージョンとなっております。
（トップページはダミー画像をいれた状態、購入ページはデザインをまだあてておりません。）

３枚目の画像は、 `index.html` を参照しているようです。
URLが `https://example.com/admin/index.html` となっていないでしょうか？
もしくは、サーバのDirectoryIndexの指定 or mod_rewriteが無効になっていないでしょうか？

お手数をかけ、恐縮ですが、一度ご確認いただけますでしょうか。

**Comment by benzookapi** [comment]
@shinichi-takahashi   
ご回答ありがとうございます。

管理画面のURLはadminで終わっていましたが、index.htmlを参照していたようでこのファイルを消すとログインできるようになりました。
こちらは正式リリースでは対応される予定でしょうか？（index.htmlを表示してしまう設定のサーバーは多いかと思います）

それと、管理画面でいくつかエラーとなる画面がありますが、これも想定内の動きでしょうか？
「設定」->「基本設定」->「支払い方法設定」などです。
この場合のログには以下のように表示されていたので、まだ画面ができていないということでしょうか？
Template \"Basis/payment.twig\" is not defined

よろしくお願いいたします。

**Comment by shinichi-takahashi** [comment]
@benzookapi 
ログインできるようになったとのこと、よかったです。
`/admin/index.html` は開発時にデザインを確認しやすいように仮で置いているもので、正式リリース時（RCのタイミングで対応予定）には削除される予定となっておりますので、ご安心くださいませ。

ver.β2では、商品管理と会員管理についてのみ動作確認しており、その他のページにおいては鋭意開発中となっております。
ですので、支払方法設定ページ含め、正常に表示されないことは想定しております。
順次対応してまいりますので、それまでお待ちくださいませ。

どうぞよろしくお願いいたします。

**Comment by benzookapi** [comment]
@shinichi-takahashi 

 ありがとうございます。了解しました。

それでは、後続バージョンをお待ちしております。

**Comment by Yangsin** [comment]
こちら疑問解消できたようですのでクローズします。
