### ISSUE TITLE
受注IDとは別で単純な連番でない受注コードを設ける

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2527]
## 概要(Overview)

受注IDが連番になってるのが嫌だ＆決済とかでトラブルが過去にあったりもしたので、単純な連番でないなんか受注コードを用意する

## 期待する内容(Expect)  or 要望 (Requirement)

受注番号を配送伝票に転記する場合があるので、あまりにも長い桁数に固定はしない

できれば固定ではなく
`${dd}${yyyy}${number,5}${mm}` という感じで採番ルールをconfigなどカスタマイズしたい

## 関連情報 (Ref)

案）
年月日 + 店コード（任意）+連番（4桁）
日 + 年 + 5桁連番 + 月
顧客番号のハッシュ値の先頭5桁+連番+チェックサム

**Comment by saiteisan** [comment]
これ、一旦
${dd}${yyyy}${number,5}${mm}
をデフォルトにしておいて
5の部分の数値変更したら桁数変わるくらいにしておけば良いでしょうか？
ハッシュ値・チェックサム等の追加はそれこそプラグインでも良いような気がしますが

**Comment by Yangsin** [comment]
そうですね、ご提案の形でも充分かと思ってます

**Comment by okazy** [comment]
対応済
