### ISSUE TITLE
【Vote：投票募集】スマホでの商品一覧表示をグリッド表示から一覧表示にしてはどうか？

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2540]
## 概要(Overview)

デフォルトのフロントテンプレートでのデザインが現状は、2列でグリッド表示だが、スマホの場合一覧表示の方が需要があるのではないか？

## 関連情報 (Ref)
https://github.com/EC-CUBE/Eccube-Styleguide/issues/126

**Comment by okazy** [comment]
要望がないためクローズします。
