### ISSUE TITLE
MySQL8 でインストールができない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2556]
## 概要(Overview)
MySQL8 でインストールができない

以下のようなエラーでインストールができない

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank SMALLINT UNSIGNED NOT NULL, news_title VARCHAR(255) NOT NULL, news_comment ' at line 1 in /Users/nanasess/git-repos/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
```

`RANK()` 関数ができたため、 カラム名に `rank` を使用する場合は引用符が必要となった
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-2.html#mysqld-8-0-2-optimizer

## 期待する内容(Expect)  or 要望 (Requirement)
MySQL8 でインストールができる

## 再現手順(Procedure)
MySQL8 でインストールする

### 環境 (environment)
+ EC-CUBE: master
+ PHP: 7.1.8
+ DB: MySQL8.0.3-RC

**Comment by t-nagahashi** [comment]
3.n.0の方で検討します。

**Comment by nanasess** [comment]
https://travis-ci.org/nanasess/ec-cube/builds/287340411
PHP7, 7.1 では、 rank を position に変更することで、テストが通るのを確認できました。
5.6 はダメみたいです。

https://bugs.php.net/bug.php?id=74461
https://bugs.mysql.com/bug.php?id=85946

**Comment by okazy** [comment]
対応済
