### ISSUE TITLE
メンテナンス管理の機能

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#2568]
## 概要(Overview)
本体の機能としてメンテナンス画面への切り替え機能を提供したほうがいいと思いましたので仕様を考えてみました。
改善点等あればアドバイスをいただきたいです。

### 環境 (environment)
+ EC-CUBE: 4.0.x

## 想定する利用者
- ショップオーナー等の技術の専門家ではない人
- プラグインと簡単なカスタマイズで利用したい人
※大規模なカスタマイズを行っている場合などはエンジニアが状況を見て適切な方法でメンテナンス対応ができる想定ですので今回の対象に含みません。

## 課題
- プラグインのスキーマ更新の影響範囲が本体にも影響するようになる
  - 3.0では独立したテーブル作成、4.0からは本体テーブルにも影響する
  - アクセス中にプラグインの更新作業を行うとエラー等発生する可能性がある

## 仕様案
- .maintenanceファイルでメンテナンスの制御をする
  - ファイルにはメンテナンス開始時刻のタイムスタンプを記述
    - フォーマットは`date("Y/m/d H:i:s")`を想定
  - .maintenanceに記載されている開始時刻になったらメンテナンス状態となる
  - .maintenanceを削除するとメンテナンス状態が解除される
  - ファイルパスはディレクトリ直下 `/.maintenance` を想定
- `設定 -> システム情報設定 -> メンテナンス管理`に画面を新しく作成する
  - サイトの停止を伴う設定変更となり、誤操作を避けるため単独で画面を用意する
  - 管理画面では2種類の操作が可能
    - .maintenanceファイルが存在しない場合
      - メンテナンス開始時間を指定してメンテナンスの設定をする
        - 指定された日時のタイムスタンプが記載された.maintenanceファイルを作成
        - デフォルトで現在時刻を指定しておくことで即時メンテナンスへの切り替えが可能
    - .maintenanceファイルが存在する場合
      - メンテナンスの設定を削除する
        - .maintenanceファイルの削除
        - メンテナンス状態の場合はメンテナンスが解除となる
        - メンテナンス開始時刻が未来の場合にはメンテナンスファイルの削除のみとなる
- メンテナンス状態ではフロント画面にアクセスをするとメンテナンス画面が表示される
  - httpステータスコードは503
  - `コンテンツ管理 -> ページ管理`でメンテナンスページの編集ができる
    - メンテナンス終了予定時刻等をメンテナンス画面に表示させてたい場合にはこちらで編集できる
- メンテナンス状態でも管理画面にはアクセス可能とする
  - メンテナンス状態の時にはヘッダ部分にメンテナンス状態であることを強調して表示させる
  - 管理画面にログイン中の状態でフロント画面にアクセスするとメンテナンス状態とはならない

**Comment by okazy** [comment]
以下の内容を変更させていただきました。

## 修正履歴
- .maintenanceファイルのファイルパス変更
- メンテナンス時のステータスコードを追記
- 想定する利用者を追記

**Comment by okazy** [comment]
## 必須で満たしたい要件

- アップデート中にフロントのアクセス制限をする
  - データの不整合が起きないようにするため
- 管理画面についてはアクセス可能
  - プラグイン等のアップデートがあるので

※イレギュラー対応についてはドキュメント等で補足

**Comment by okazy** [comment]
#3998 で最小限のメンテナンス機能を実装
- .maintenanceファイル設置でメンテナンスモードへ切り替え
- 管理画面はメンテナンス画面にしない

**Comment by ghost** [comment]
メンテナンス管理機能については、4.0.1で実装したので一旦こちらはCloseします。

尚、管理者もフロント画面が見えなくなる問題があるため別Isuueを立てます。

別途ご意見などあれば、新たにIssueを立てて頂きますようお願いいたします。
