### ISSUE TITLE
Codeceptionの導入

### ISSUE THREAD

**Issue by tamagoya** [EC-CUBE/ec-cube#257]
シナリオテストのため、Codeceptionのテストコードを同梱する。

ローカル環境で動作での動作を想定している。
動作確認済み環境: EC-CUBE/eccube-vagrant
```
# 実行方法
vendor/bin/codecept run
```

今後、Travice-ciなどCIツール上で動作にさせたい。

**Comment by Yangsin** [comment]
別途すすめているので、このIssue自体は一度閉じます。

**Comment by nanasess** [comment]
https://github.com/EC-CUBE/eccube-codeception を用意いただきましたのでクローズします。
