### ISSUE TITLE
受注キャンセル時の在庫連動を行うべきか

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2573]
## 概要(Overview)

3系では受注キャンセル時に商品の在庫は手動で戻す仕様になっているが、店舗によっては自動で戻してほしいという声もあり、仕様を再度検討したい。

## 期待する内容(Expect)  or 要望 (Requirement)

+ 中古品など商品数が多く、在庫数がすくない店舗
   - 在庫を早くもどして売りたいが、キャンセルの都度、商品を探して在庫を戻し運用が手間
+ 基幹システムなど在庫を他サービスと連動している店舗
   - EC-CUBE単体で在庫の変動がおきると不整合がおきやすくなるため戻してほしくない

## 関連情報 (Ref)

2.13系では自動で戻す仕様

**Comment by Yangsin** [comment]
説明会などでヒアリングの結果、自動ではもどしてほしくないが、在庫の加減算を調整する機能がほしいという要望を多くお伺いしました。
標準では、キャンセル時の自動での在庫戻しません。
別途、在庫管理CSV機能については検討します。
https://github.com/EC-CUBE/ec-cube/issues/2591

**Comment by okazy** [comment]
別issueになっているたもこちらはcloseします。
