### ISSUE TITLE
税区分マスタによる税率設定についての検討

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#2587]
## 概要(Overview)
軽減税率対応に向けて、以下の方法を検討します。

### 税率の設定方法
今までのEC-CUBEでは商品規格に販売税率という項目を用意し、  
dtb_tax_ruleに対して商品規格毎に設定された販売税率を登録していたが、  
今後は商品規格毎に税率を設定するのではなく税区分マスタを新規に用意する。

* 税区分マスタ  

|ID|名称|
|---|---|
|1|対象外|
|2|一般品|
|3|その他|
|・|・|
|・|・|
|・|・|

軽減税率を設定する場合、商品(dtb_product)に対して上記の税区分を設定させて商品が軽減税率対象かどうかを判断させるようにする。  
→商品規格毎ではなく商品毎で設定させるように変更

計算させる税率については、新たに軽減税率テーブルを用意し期間をもたせて計算させるようにする  
→消費税計算と同じ方法

* 軽減税率テーブル

|名称|
|---|
|id|
|税区分ID|
|軽減税率名|
|軽減税率(%)|
|適用開始日|
|適用終了日|
|適用ルール(四捨五入、切り上げ、切り捨て)|

軽減税率対象は上記テーブルのルールに則り計算を行う。

商品購入時には受注明細(dtb_order_item)に税区分、税率をコピーとして持たせることで軽減税率が適用されているかどうかを判断させる。

※商品規格毎に設定された販売税率はそのまま残しておきます。

**Comment by okazy** [comment]
合わせて以下のissueも検討が必要です。
#2251

**Comment by tao-s** [comment]
今度適用される軽減税率だけに合わせてこの様な機能を実装するのには反対です。
税制の変更に右往左往させられる事になります。
個人的には現段階でこういった税マスタの実装は、より複雑なプロダクトとなってしまうので反対です。

仮に、税マスタを実装するのであれば、他のプロダクト等も参考にもう少し汎用的に作り、将来的な税制変更にも容易に対応できるようにするべきだと思います。ただ、原則として現在不要な物を作る事には反対です。

**Comment by xuelian311** [comment]
軽減税率対応は終了しているのと、議論が長い間進んでないため、本issueはクローズします。
