### ISSUE TITLE
MessageIDに言語を切り出す

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2597]
## 概要(Overview)

多言語対応に向けてシステム出力のテキストをすべてmessage.ymlに切り出す

## 期待する内容(Expect)  or 要望 (Requirement)

現状のシステムテキストをすべて言語ファイルに切り出す
MessageIDは2系の英語版同様に自然な英語であることが望ましいが、まずはテキストを切り出す事から入る

## 関連情報 (Ref)

もう少し越境とかで使いやすくしたい #2229

**Comment by chihiro-adachi** [comment]
以下にIDの規約案を作成しています。

### フォーマット

以下のフォーマットで定義する

`[機能].[種別].[操作|名称]`

- [機能 or 画面]
  - common：共通
  - admin：管理画面|機能 固有
  - admin_xxx_xxx：管理画面|機能  固有
  - front：フロント画面|機能 固有
  - front_xxx_xxx：フロント画面|機能 固有
  
- [種別]
  - label：単語名称, ラベル
  - text：説明文等のテキスト
  - flash：フラッシュメッセージ
  - placeholder：プレースホルダ
  - validator：バリデーションメッセージ
  - nav：管理画面メニュー

- [操作|名称]
  - 操作や名称にあたるもの
  - register_completed, email, product...etc

### 実装例

- 管理画面＞設定＞ショップマスタを上記に沿って実装したサンプルです。
- https://github.com/chihiro-adachi/ec-cube/commit/5643d1b01b4c50db9c1cccb589978a4c032ca8d1

**Comment by okazy** [comment]
以下で対応しました。

https://github.com/EC-CUBE/ec-cube/pull/3593

規約等も更新しています。
