### ISSUE TITLE
住所や会員情報を国際標準へ対応

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2598]
## 概要(Overview)

OpenID ConnectのAddressClaimを参考にTEL01などの統一、国際標準にしていく。

## 期待する内容(Expect)  or 要望 (Requirement)

・TEL01・・・→TEL
・Fax ・・・ → カラムだけのこして画面からは消す
・Zip01 → postalcode
・Addr01 → Street, City, Pref, 
・Name01 → FirstName, FamilyName, Middle はカラムのみ
・カナ必須やめる
・sex→Gendar

デフォルトのフォームの並びはカスタマイズで変えてもらう想定
 http://openid.net/specs/openid-connect-core-1_0.html#AddressClaim

## 関連情報 (Ref)
国際電話番号のバリデーション #1609
OpenID Connect の要件 http://openid.net/specs/openid-connect-core-1_0.html#AddressClaim

**Comment by nanasess** [comment]
以下、修正案です

## dtb_customer

| 変更前             | 変更後                 | JSON format            |
|--------------------|------------------------|------------------------|
| customer_id        |                        |                        |
| status             |                        |                        |
| sex                | gender_id              |                        |
| job                | job_id                 |                        |
| country_id         |                        |                        |
| pref               | region_id              |                        |
| name01             | family_name            |                        |
| name02             | given_name             |                        |
|                    | middle_name            |                        |
| kana01             | family_name_ja_kana_jp | family_name#ja-Kana-JP |
| kana02             | given_name_ja_kana_jp  | given_name#ja-Kana-JP  |
| company_name       |                        |                        |
| zip01              | 廃止                   |                        |
| zip02              | 廃止                   |                        |
| zipcode            | postal_code            |                        |
| addr01             | locality               |                        |
| addr02             | street_address         |                        |
| email              |                        |                        |
| tel01              | phone_number           |                        |
| tel02              | 廃止                   |                        |
| tel03              | 廃止                   |                        |
| fax01              | 廃止                   |                        |
| fax02              | 廃止                   |                        |
| fax03              | 廃止                   |                        |
| birth              | birthdate              |                        |
| password           |                        |                        |
| salt               |                        |                        |
| secret_key         |                        |                        |
| first_buy_date     |                        |                        |
| last_buy_date      |                        |                        |
| buy_times          |                        |                        |
| buy_total          |                        |                        |
| note               |                        |                        |
| reset_key          |                        |                        |
| reset_expire       |                        |                        |
| create_date        |                        |                        |
| update_date        |                        |                        |
| discriminator_type |                        |                        |

## dtb_baseinfo

| 変更前                             | 変更後                  | JSON format             |
|------------------------------------|-------------------------|-------------------------|
| id                                 |                         |                         |
| country_id                         |                         |                         |
| pref                               | region_id               |                         |
| company_name                       |                         |                         |
| company_kana                       | company_name_ja_kana_jp | company_name#ja-Kana-JP |
| zip01                              | 廃止                    |                         |
| zip02                              | 廃止                    |                         |
| zipcode                            | postal_code             |                         |
| addr01                             | locality                |                         |
| addr02                             | street_address          |                         |
| tel01                              | phone_number            |                         |
| tel02                              | 廃止                    |                         |
| tel03                              | 廃止                    |                         |
| fax01                              | 廃止                    |                         |
| fax02                              | 廃止                    |                         |
| fax03                              | 廃止                    |                         |
| business_hour                      |                         |                         |
| email01                            |                         |                         |
| email02                            |                         |                         |
| email03                            |                         |                         |
| email04                            |                         |                         |
| shop_name                          |                         |                         |
| shop_kana                          | shop_name_ja_kana_jp    | shop_name#ja-Kana-JP    |
| shop_name_eng                      | shop_name_en            | shop_name#en            |
| update_date                        |                         |                         |
| good_traded                        |                         |                         |
| message                            |                         |                         |
| latitude                           |                         |                         |
| longitude                          |                         |                         |
| delivery_free_amount               |                         |                         |
| delivery_free_quantity             |                         |                         |
| option_multiple_shipping           |                         |                         |
| option_mypage_order_status_display |                         |                         |
| nostock_hidden                     |                         |                         |
| option_favorite_product            |                         |                         |
| option_product_delivery_fee        |                         |                         |
| option_product_tax_rule            |                         |                         |
| option_customer_activate           |                         |                         |
| option_remember_me                 |                         |                         |
| authentication_key                 |                         |                         |
| discriminator_type                 |                         |                         |

##  dtb_help

| 変更前             | 変更後             | JSON format |
|--------------------|--------------------|-------------|
| id                 |                    |             |
| law_country_id     |                    |             |
| law_pref           | law_region_id      |             |
| customer_agreement |                    |             |
| law_company        | law_company_name   |             |
| law_manager        |                    |             |
| law_zip01          | 廃止               |             |
| law_zip02          | 廃止               |             |
| law_zipcode        | law_postal_code    |             |
| law_addr01         | law_locality       |             |
| law_addr02         | law_street_address |             |
| law_tel01          | law_phone_number   |             |
| law_tel02          | 廃止               |             |
| law_tel03          | 廃止               |             |
| law_fax01          | 廃止               |             |
| law_fax02          | 廃止               |             |
| law_fax03          | 廃止               |             |
| law_email          |                    |             |
| law_url            |                    |             |
| law_term01         |                    |             |
| law_term02         |                    |             |
| law_term03         |                    |             |
| law_term04         |                    |             |
| law_term05         |                    |             |
| law_term06         |                    |             |
| law_term07         |                    |             |
| law_term08         |                    |             |
| law_term09         |                    |             |
| law_term10         |                    |             |
| create_date        |                    |             |
| update_date        |                    |             |
| discriminator_type |                    |             |

## dtb_shipping

| 変更前                 | 変更後                          | JSON format                     |
|------------------------|---------------------------------|---------------------------------|
| shipping_id            |                                 |                                 |
| shipping_country_id    |                                 |                                 |
| shipping_pref          | shipping_region_id              |                                 |
| delivery_id            |                                 |                                 |
| shipping_status        |                                 |                                 |
| shipping_name01        | shipping_family_name            |                                 |
| shipping_name02        | shipping_given_name             |                                 |
|                        | shipping_middle_name            |                                 |
| shipping_kana01        | shipping_family_name_ja_kana_jp | shipping_family_name#ja-Kana-JP |
| shipping_kana02        | shipping_given_name_ja_kana_jp  | shipping_given_name#ja-Kana-JP  |
| shipping_company_name  |                                 |                                 |
| shipping_tel01         | shipping_phone_number           |                                 |
| shipping_tel02         | 廃止                            |                                 |
| shipping_tel03         | 廃止                            |                                 |
| shipping_fax01         | 廃止                            |                                 |
| shipping_fax02         | 廃止                            |                                 |
| shipping_fax03         | 廃止                            |                                 |
| shipping_zip01         | 廃止                            |                                 |
| shipping_zip02         | 廃止                            |                                 |
| shipping_zipcode       | shipping_postal_code            |                                 |
| shipping_addr01        | shipping_locality               |                                 |
| shipping_addr02        | shipping_street_address         |                                 |
| shipping_delivery_name |                                 |                                 |
| time_id                |                                 |                                 |
| fee_id                 |                                 |                                 |
| shipping_delivery_time |                                 |                                 |
| shipping_delivery_date |                                 |                                 |
| shipping_delivery_fee  |                                 |                                 |
| shipping_commit_date   |                                 |                                 |
| tracking_number        |                                 |                                 |
| commit_date            |                                 |                                 |
| note                   |                                 |                                 |
| rank                   |                                 |                                 |
| create_date            |                                 |                                 |
| update_date            |                                 |                                 |
| discriminator_type     |                                 |                                 |

## dtb_order 

| 変更前             | 変更後                       | JSON format                  |
|--------------------|------------------------------|------------------------------|
| order_id           |                              |                              |
| customer_id        |                              |                              |
| order_country_id   |                              |                              |
| order_pref         | order_region_id              |                              |
| order_sex          | order_gender_id              |                              |
| order_job          | order_job_id                 |                              |
| payment_id         |                              |                              |
| device_type_id     |                              |                              |
| pre_order_id       |                              |                              |
| message            |                              |                              |
| order_name01       | order_family_name            |                              |
| order_name02       | order_middle_name            |                              |
|                    | order_given_name             |                              |
| order_kana01       | order_family_name_ja_kana_jp | order_family_name#ja-Kana-JP |
| order_kana02       | order_given_name_ja_kana_jp  | order_given_name#ja-Kana-JP  |
| order_company_name |                              |                              |
| order_email        |                              |                              |
| order_tel01        | order_phone_number           |                              |
| order_tel02        | 廃止                         |                              |
| order_tel03        | 廃止                         |                              |
| order_fax01        | 廃止                         |                              |
| order_fax02        | 廃止                         |                              |
| order_fax03        | 廃止                         |                              |
| order_zip01        | 廃止                         |                              |
| order_zip02        | 廃止                         |                              |
| order_zipcode      | order_postal_code            |                              |
| order_addr01       | order_locality               |                              |
| order_addr02       | order_street_address         |                              |
| order_birth        | order_birthdate              |                              |
| subtotal           |                              |                              |
| discount           |                              |                              |
| delivery_fee_total |                              |                              |
| charge             |                              |                              |
| tax                |                              |                              |
| total              |                              |                              |
| payment_total      |                              |                              |
| payment_method     |                              |                              |
| note               |                              |                              |
| create_date        |                              |                              |
| update_date        |                              |                              |
| order_date         |                              |                              |
| commit_date        |                              |                              |
| payment_date       |                              |                              |
| currency_code      |                              |                              |
| status             |                              |                              |
| discriminator_type |                              |                              |

## 備考

- JSON format は参考です。 [OpenID Connect 5.2.  Claims Languages and Scripts](https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#ClaimsLanguagesAndScripts) に準拠しています。
- `shipping_family_name_ja_kana_jp` など、 30byte を越えてしまう。(Oracle の列名最大サイズを越えてしまう)
- マスタデータを参照しており、 id 表記のないものは `_id` を追加しました。

**Comment by tao-s** [comment]
@nanasess 電話番号についてですが、国番号コードのフィールドが欲しいです。
あと、名前に関しては、family nameとかじゃなくて、first name, last nameが一般的だと思います。
dtb_shippingやdtb_orderのカラム名のプレフィックスは無くしてはどうでしょうか？
name_ja_kana_JPも冗長な気がします。中国等でも越境で読み仮名をアルファベットで表記するケースもあると思うので、phonetic spell とか、pronunciationとかを使った方が良いのではないでしょうか？

**Comment by nanasess** [comment]
@tao-s 
名前やカナ, 電話番号に関しては、 OpenID Connect の Standard Claims と Claims Languages and Scripts に準拠するようにしています。これに準拠せずに、  first name, last name にした方がよい理由があれば教えてください。
http://openid.net/specs/openid-connect-core-1_0.html#Claims

> 中国等でも越境で読み仮名をアルファベットで表記するケース

name_ch_alphabet_CN といったようなカラムを増やしたらよいかなと。

プレフィクスを無くすことも考えたんですが、 旧バージョンからのデータ移行や、それぞれのテーブルを JOIN した時に扱いづらくなりそうなので、 カラム名はプレフィクスあり、 Entity のフィールドはプレフィクス無しで考えてます。
プレフィクスはあっても、 ORM 経由で使う分には意識しなくてもよいはず。

**Comment by okazy** [comment]
以下は4.0で対応済み

- zipcode: フォームを１個にまとめてpostalcodeへ変更
- Tel: フォームを１個にまとめた
- Fax: 削除

**Comment by eternalharvest** [comment]
あまり EC-Cube の開発の歴史的なことについて詳しくなくて恐縮ですが、電話番号の WEB 上での表記や帳票類でのハイフンなしのフォーマットはあまり美しくないなぁと思っていました。国際化対応に向けての布石で現状のような形になっているのかもしれませんが、Google の libphonenumber 等を使って表示するときだけでも整形した方がよいのではと思います。

**Comment by xuelian311** [comment]
住所や会員情報を国際標準へ対応 はすでに #3234 で実装されているため、本issueはクローズします。
郵便番号や電話番号表示のハイフン有りの実装については、 #5563 で引き続き、対応検討します。
