### ISSUE TITLE
EC-CUBE3 beta2 フロントの標準テンプレートについて

### ISSUE THREAD

**Issue by sakurasaku44** [EC-CUBE/ec-cube#260]
いつもお世話になっております。
EC-CUBE3 beta2 について質問があります。

Bootstrapをフロントの標準テンプレートに採用しているのは
何か理由があるのでしょうか？

管理画面等、あまりデザインやコーディングに動きが無いものに採用されているのでしたら、
問題ないのですが、フロントに採用されるとなると以下の点を心配しております。

・(jQuery+CSS)で動くものが入ってBootstrapが外せなくなると困る
・標準テンプレートベースで動くようにプラグインを作るとはいえ、
  なるべくマルチに動くように実装しようとするのにBootstrapが障害になってほしくない

ECサイトという性質上、独自でサイトデザインされたり、コーディングされたりすることが多く、
多くの場合で、Bootstrapが邪魔にならないか懸念しております。

**Comment by Yangsin** [comment]
@sakurasaku44 
仰るとおり、フロントは自由度が優先されるべきだとおもっており、フロントはBoostrapの中でも、使いやすいものだけをピックアップして使っている状態です。
jQueryのBootstrap依存に関していうと、bootstrapのjsを多用しているわけではないため、懸念されてるほど縛られないのではないかと思ってます
CSSのほうは、class命名ルールやグリッドレイアウトなどで参照している程度で、HeaderやFooterといった大枠のレイアウトでは全く使用していません。
そのため、基本的にはBootstrap部分のCSSを外しても問題ないと思っています。

**Comment by sakurasaku44** [comment]
方針を聞く事が出来安心いたしました。
ご回答頂きありがとうございました。

**Comment by Yangsin** [comment]
こちら方針確認のQということで、クローズさせていただきます。
