### ISSUE TITLE
ほぼ静的な特商法・おかいものガイド・会員規約はサンプルページにし管理機能は廃止する

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#2601]
## 概要(Overview)

ほぼ静的な特商法・買い物ガイド・会員規約は機能よりも静的なページ管理のサンプルとする
簡易な文言変更レベルはTwigを触ることもできると思われる。

## 期待する内容(Expect)  or 要望 (Requirement)

サンプルページ上はあまりコーディングに不慣れな人も触りやすいようにコメントなどを整える

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/1355

**Comment by okazy** [comment]
対応済
