### ISSUE TITLE
カート周りの再設計

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#2613]
### 同じ商品規格でも異なる明細にできるようにする
+ 標準の実装では現状通り、商品規格ごとに明細をわける
+ カスタマイズによって明細の分け方を変更できるようにする
    + 例) 商品規格 + 商品オプションで明細を分ける
+ 参考: https://github.com/EC-CUBE/ec-cube/pull/2486

### 支払方法が異なる商品をカートに入れられるようにする
例)  以下のような、配送方法A/B、商品A/Bがそれぞれあるとき

+ 配送方法
    + 配送方法A:  商品種別A/クレジットカード
    + 配送方法B:  商品種別A/代引き
+ 商品
    + 商品A: 商品種別A
    + 商品B: 商品種別B

現状は、商品Aをカートに先に入れると、商品Bをカートに入れることができない

+ 2系と同じように支払方法が異なる商品はカートを分けるようにする
+ 標準の実装では販売種別ごとにカートが分かれるようにする
    + 商品種別という名前は実態を表していないので、販売種別に名称を変更する
    + カスタマイズによってカートの分割方法を変更できるようにする
+ 販売種別/配送方法/支払方法で矛盾が生じる設定はできないようにする
    + 例) 同じ販売種別の配送方法は、必ず共通する支払方法を持つようにする
+ 受注/決済はカートごとに分けられる

## 実装案
次のような2つのインターフェイスを追加して、カスタマイズできるようにする

+ CartItemComparator
    + 明細の分け方を実装するインターフェイス
+ CartItemAllocator
    + カートの振り分け方法を実装するインターフェイス

#### シーケンス図
![シーケンス図](http://www.plantuml.com/plantuml/png/hLNBRjD05DtFLyoobUY6PHP8A18IEoI-m3XJ6idDLAuBB3js7owrQ6cRD4MYfEJPHab3sqK90Jvc6CUVmSpu6JiHgOGLHHwFxxddtdFcUgLOG70PO-CLVWS0o2kwaSSbGyUQXdIuz0IA9o-H_gQeeXnK2WMnVcwWrGMtCg3ab98jj_fXV3TO140LGQfHnALrICqkjKRKil_SRtgjDYXX0q6z-7h5W7WvimlvzNXy-uEI3ZjqAAbIqwPaXv8ktIJUpIMhtumxVMOtnxqzyL3irYbfoS08Z9f7pEP17wcvHqs7clin33dZIu1A1IYO-8K6POagKuHo2L1ombbHqlVBzFT5feCA-tKAKe5mATsoP5YgHPmJ-SwhI843LKSAxzRC_GpvcIzg6Az1z_GhwrMZFN5J7W3PkXHGg6qUhwufkc9WFGTLUO_ISZzAmoxwYB7ESYckJFwEUttYZIm9r_Br3hUuK5T2Dy9_brAwVMOtt4hF5v1kcX4ijNQfLQRc9RMwKgSs9TUilCEEYTSwS6kZKBbk01wxOm8dMpIdolfVlFgs26bmmzcIqh54QtD7Hh4--Scat1pcb8n1kCDsX-xdPe93x4cnKZG3Jcq9gzsnGnjCq9x30w41EHTgdGkhclSB4ueXRHt1SNdWf_blMIi3qH3vpBjmlDy_sVjQAd6f083yapQDJfBVpZbi-bJJiEgxLF5lKPGXgMpqNlPqHaczNfMF5zOxdEdYe361fxA1lCFkjo7hVyfQrUsSkSDAR2jfrUWq9kTRPhY9Y_VKtJg8D8ap4jvNpgSS3BkfXlhNe0ldxRHo7Av2OsAy-aClvTIvWWb_qvp3KMb-qVH8G7Mdsadu-864hlWyUp0XwUnv2CtmT-3iCDVav_R5XgwkAElecORVyk6hQEg69dozcFBbb2zKrxiTiUsc68fMJvxq8-6t2oV--Fq5)

**Comment by nanasess** [comment]
関連 #1348

**Comment by okazy** [comment]
対応済み
