### ISSUE TITLE
デバッグ用としてルーティング情報を表示するコマンドについて

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#262]
Symfony2でルーティング情報を表示する
php app/console router:debug
コマンドをsilex用として作成しました。 #261 
http://docs.symfony.gr.jp/symfony2/book/routing.html#index-10

php app/routing router:debug

として実行するとルーティング情報が一覧表示されますが、
詳細な表示をする機能までは実装していません。

**Comment by shinichi-takahashi** [comment]
本件、マージ済のためクローズいたします。
ご対応ありがとうございました。
