### ISSUE TITLE
eccube.entity.event.dispatcher が有効にならない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2625]
## 概要(Overview)

- experimental/3.1 ブランチにて実装されている `eccube.entity.event.dispatcher` が使用できない

## 期待する内容(Expect)  or 要望 (Requirement)

`ServiceProviderInterface::boot()` で、 ServiceProviderCache を生成しているためだと思われる。
以下のパッチで暫定的に回避可能

```patch
modified   src/Eccube/DI/DIServiceProvider.php
@@ -34,5 +34,6 @@ class DIServiceProvider implements ServiceProviderInterface, BootableProviderInt
     public function boot(Application $app)
     {
         $app['eccube.di']->build($app);
+        $e = $app['eccube.entity.event.dispatcher']; // XXX これ入れないと EntityEventDispatcher が登録されない
     }
 }
```

## 再現手順(Procedure)

簡単な EntityEventListener を作成し、 app/Entity に入れても実行されない。

### 環境 (environment)
+ EC-CUBE: experimental/3.1 ブランチ
+ PHP: 7.1.8
+ DB:
  - sqlite3

## 関連情報 (Ref)

- #2624

**Comment by okazy** [comment]
仕様変更となったためクローズします。
