### ISSUE TITLE
Console 系のコマンドをまとめる

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#265]
#261 などとも重複しますが、consoleが分散しそうなので、silexのconsole系のproviderを利用してコマンドを1つにまとめてはどうでしょうか。

**Comment by ttsuru** [comment]
https://github.com/KnpLabs/ConsoleServiceProvider
こちらあたりだと思います。

**Comment by k-yamamura** [comment]
routing機能を作成した後で思いましたが、
既にあるconsoleファイルに対して
php app/console router:debug
として利用出来た方が良かったですね。

symfony/consoleをcomposerに追加するだけでも出来そうですが、
silexだとConsoleServiceProviderの方が主流そうですね。

Symfony2でいうとこちらのurlの事になりますが、
http://docs.symfony.gr.jp/symfony2/cookbook/console/console_command.html
ConsoleServiceProviderの方が実装は簡単そうですね。
https://bradb.net/using-symfony-console-with-silex/


標準で用意するコマンド機能としては、

・ルーティングの表示機能
・キャッシュクリア機能
・swiftmailerでのspool送信機能
・DBのmigration機能

ぐらいでしょうか。

**Comment by ttsuru** [comment]
:+1:

**Comment by Yangsin** [comment]
:+1:
