### ISSUE TITLE
購入確認画面で、ProcessResult::error() を返した際に、カート画面に遷移してしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2660]
## 概要(Overview)

PurchaseFlow にて Processor が購入確認画面で、ProcessResult::error() を返した際に、カート画面に遷移してしまう。
エラーの内容によって、以下を分ける必要がある

- 購入を中止してカート画面に戻したいケース
- 購入確認画面でエラーメッセージを表示したいケース

## 期待する内容(Expect)  or 要望 (Requirement)

購入確認画面でエラーメッセージを表示したいケースでは、カートに遷移しないようにする。
ProcessResult に遷移先も含めるのが良い？

## 再現手順(Procedure)

購入確認画面で ProcessResult::error() を返す

## 関連情報 (Ref)

- #2624

**Comment by okazy** [comment]
修正済
