### ISSUE TITLE
Order::total と Order::payment_total の使い分け

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2662]
## 概要(Overview)

1系からの名残りで、購入時の合計金額を表わすフィールドとして dtb_order.total 及び、 dtb_order.payment_total が存在する。
2系までは、 以下のような扱いであった

- **dtb_order.total** : ポイント値引き前のお支払い金額合計
- **dtb_order.payment_total** : ポイント値引き後のお支払い金額合計

3.0 にてポイント機能がプラグインになり、EC-CUBE本体としては区別しなくなってしまった。
`experimental/3.1` ブランチでは、ポイントを含む、すべての値引を明細(OrderItem)で処理するため、  total と payment_total を使い分ける必要性が少ない

## 期待する内容(Expect)  or 要望 (Requirement)

total と payment_total を使い分ける必要性が少ないことから、 payment_total のみに統一する。
total にしないのは、データ移行などで予期せぬトラブルを防ぐため。

## 関連情報 (Ref)

#2624

**Comment by xuelian311** [comment]
#2624 にて実装済みの仕様であるため、クローズします。
