### ISSUE TITLE
決済プラグイン使用時の「戻る」「キャンセル」のエンドポイント実装

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2665]
## 概要(Overview)

決済プラグイン(特にリンク式)使用時に「戻る」「キャンセル」の処理が必要。

![default](https://user-images.githubusercontent.com/815715/33303897-0e2184b8-d449-11e7-9ee2-37bee162759b.png)

また、ポイント割引と手数料や他の割引が混在した場合不具合が発生しないか精査する

## 期待する内容(Expect)  or 要望 (Requirement)

「戻る」「キャンセル」のエンドポイントが必要。
処理は PurchaseFlow に実装する

## 関連情報 (Ref)

#2624

**Comment by okazy** [comment]
ステートマシンで実装済
