### ISSUE TITLE
スタイルガイドの統合

### ISSUE THREAD

**Issue by saiteisan** [EC-CUBE/ec-cube#2720]
## 概要(Overview)
minifiedされたcssのcommit内容を見てもよくわからないので
スタイルガイドを本体に取り込みたい。

・app、html、srcディレクトリの同階層状にstyleguideフォルダを新規作成。
・上記styleguideディレクトリ内に、github上の「Eccube-Styleguide」の中身を配置。
・styleguide内「sass.js」に記述されているsassをコンパイルするタスクに、minifiedされたstyle.min.cssファイルも出力するように追記。
・出力されたstyle.css及びstyle.min.cssを、html/template/default/assets/cssフォルダ内にコピーするnpm scriptsを、styleguide内「package.json」に、追記。

等で対応可能でしょうか。

## 相談（Discussion）
場所や名称は暫定で書いています。
他に、スマートな方法等あれば教えてください。

**Comment by Yangsin** [comment]
リポジトリ内に SCSS などのファイルが入ってくるとわかりづらいのと、手元でビルドさせないと行けないので npm が環境的に必須になってくるので必要ならスタイルガイドのリポジトリを見に行くという形にしては？という意見もありまして今のようになってます。
一緒にする場合そこら辺どう思います？

**Comment by saiteisan** [comment]
@Yangsin 
cssを
・大元から修正するのか
・別ファイルで上書きして修正するのか
どちらの更新方法にするか
だとは思うんですが

インストールして使うだけのユーザーには仰る通り必要がないですが
案件として使用する方たちには必ず必要になるものだと考えています。

なので、

npmはstyleguideを直接編集して元のcssを修正する方向けの推奨環境

として統合してしまっても良いのでは、と考えています

**Comment by mikakane** [comment]
@saiteisan 
スタイルガイド自体はユーザ側が編集することを想定していません。
bootstrap のような感じでパッケージ化された一つのもの…という
取扱をしてもらえるほうが良いかと思います。

**Comment by Yangsin** [comment]
@mikakane のいうようにスタイルガイド自体をユーザーが直接編集することはないと思いますが、 @saiteisan のいうように、大本のスタイルガイドをもとに自分たちのスタイルガイドをつくっていくという事は想像されます。
それぞれ長短あると思うのですが

+ 本体に取り込む）
  + メリット）本体開発している開発者にとって、機能開発や修正にともなうフロントの変更が把握しやすく扱いやすい
  + デメリット）本体開発しているがフロントまで気にしない人やフロントしか触らない人にとって、リポジトリがごちゃごちゃする

+ スタイルガイドとしてわける）
　+ メリット） スタイルガイドの開発者にとって、リポジトリがシンプルで保守メンテナンスがし易い
　+ デメリット）本体開発している開発者にとって、フロントのコードを修正する際に別なリポジトリを扱いながらさわらないといけない

みたいな感じでしょうか？

**Comment by pineray** [comment]
tests をレポジトリに含めていながら scss は分けるというのは、ダブルスタンダードではないかと思うのですが。
ダウンロードしたままでしか使わない方だけを対象とするなら tests も要らないはずです。
tests は開発の際に必要とおっしゃるのであれば、同様にscssも開発に必要です。
と横槍すみません。

**Comment by mikakane** [comment]
スタイルガイドを含めると、コンパイル済みのcssをリポジトリに含めることが難しくなり、
ユーザはダウンロードしてから手動でビルドする必要が出てきます。
スタイルガイドはそもそも触るものでもありませんので、添付する上での開発者側のメリットはなく、利用者側へのビルドの手間というデメリットが生じてきます。

テストに関しては存在自体が問題となることはありませんが、開発で必要となるケースは多いため同梱で問題ないと思います

**Comment by saiteisan** [comment]
色々ご意見頂きありがとうございます。

@mikakane 

> スタイルガイドを含めると、コンパイル済みのcssをリポジトリに含めることが難しくなり、

コンパイル済みのcssはリポジトリに含めた上で
スタイルガイドも同梱しておけば、開発者がcssの修正/上書きがしやすいのでは
という意味合いです。

その手法として、力技っぽいやり方ですが
こちらのissueに書いてある手法、もしくはもっとスマートな方法があればそれで
同梱した方が良いのでは、と考えています。

**Comment by ttsuru** [comment]
僕も同梱したほうが良いと思います。
Symfony であれば minify 用の Symfony Encore を含めて自分でもビルドできると非常にうれしいですね。

**Comment by tao-s** [comment]
同梱して欲しいです。
このバージョンの元のSCSSってどれ？ってなるので

**Comment by chihiro-adachi** [comment]
遅くなりましたが、以下の方針で進めようと考えています。

- scssファイルは本体のリポジトリに含める
- コンパイル済みのcssファイルも本体リポジトリに含める
- スタイルガイドのメンテナンスは基本的に開発チームで行う

新規画面を作成したり、CSS自体の不具合修正を行う場合の、EC-CUBE本体レポジトリへPull Requestする手順は以下になります。

- (コミッタ) scssファイル変更する
- (コミッタ) scssをコンパイルする
- (コミッタ) scssファイルおよびコンパイルしたcssファイルを含めてPRを送る
- (開発チーム) PRのレビュー・受け入れを行う
- (開発チーム) スタイルガイドに変更を反映する

scssのビルド環境の構築やコンパイル手順は、#2863 に記載していますので、こちらも合わせてご意見いただけますと幸いです。

**Comment by okazy** [comment]
統合済
