### ISSUE TITLE
.env ファイルの扱いについて

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2730]
## 概要(Overview)

Symfony 3.4 では、 **環境変数 APP_ENV が存在しない場合は、 .env ファイルを読み取る**
という[仕様になっています](https://github.com/symfony/demo/blob/0d3e58650bf72cf152cd6bfebe9594e8d792fac3/public/index.php#L20-L22)。
インストール時に、 環境変数 `DATABASE_URL` が設定されますが、標準では .env ファイルに書き込まれます。
また、 parameters で使用する、必要な環境変数(`ECCUBE_AUTH_MAGIC` 等)が設定されていないと、 Kernel を boot させることができません。

`APP_ENV=prod` 及び、 `APP_ENV=dev` では問題ないのですが、  **PHPUnit を使用したユニットテストでは、 phpunit.xml.dist ファイルによって、 `APP_ENV=test` が設定されます**。

Symfony 3.4 の  **環境変数 APP_ENV が存在しない場合は、 .env ファイルを読み取る** という仕様に準拠すると、以下のような課題があります。

- `phpunit.xml(.dist)` ファイルはインストーラで設定されない
- `phpunit.xml(.dist)` ファイルに、 `DATABASE_URL` 及び `ECCUBE_AUTH_MAGIC` を設定するのは、利便性が悪い
- ローカル環境のテストでは、利便性の関係上 .env ファイルの `DATABASE_URL` 及び `ECCUBE_AUTH_MAGIC`を使用したい

このような観点から、 #2714 では、 **PHPUnit を使用したユニットテストでは、 .env ファイルが存在する場合は、 .env ファイルから環境変数を取得する** という仕様に変更しています。

もっとより良い仕様案がありましたらご指摘お願い致します。

**Comment by chihiro-adachi** [comment]
http://doc4.ec-cube.net/quickstart_install
