### ISSUE TITLE
商品詳細画面で、数量に数字値以外を入力できます。(Front)

### ISSUE THREAD

**Issue by sanglephu** [EC-CUBE/ec-cube#2735]
## 概要(Overview)
●Chromeブラウザにて、「数量」を入力する時に、数量に「e」を入力できます。
●FirefoxとIEにて、何でも入力できます。

## 期待する内容(Expect)  or 要望 (Requirement)
●数量のデータ型は数字なので、数字だけを入力できると思います。

### 環境 (environment)
+ EC-CUBE: master(>3.0.15)

**Comment by okazy** [comment]
こちらはブラウザの仕様なので、こちらを解決するためにはjavascriptで実装する必要があります。
EC-CUBEとしてはここまでの対応は現時点では予定がありません。
