### ISSUE TITLE
twigキャッシュがアクセス毎に増加する

### ISSUE THREAD

**Issue by toshiaki-h** [EC-CUBE/ec-cube#2783]
## 概要(Overview)
3.0.15でアクセスするたびにキャッシュファイルが増える

## 期待する内容(Expect)  or 要望 (Requirement)
通常同じページへのアクセスはキャッシュファイルがあればそのファイルを使うはずだが、アクセスするたびにキャッシュファイルが増えている。

## 再現手順(Procedure)
app/cache/twig 内で "find . -type f | wc -l" を実行しページのアクセス毎にファイル数を取得したところ、増えていることを確認した。
確認環境は3.0.15を新規にインストールしたもので確認。
同様に、3.0.13, 3.0.14を確認したところ増加は見られなかった。

### 環境 (environment)
+ EC-CUBE: 3.0.15
+ PHP: 7.0.22
+ DB:
  - PostgreSQL 9.6.6

## 関連情報 (Ref)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=19944&forum=11

**Comment by kiy0taka** [comment]
Twigの不具合のようです。関連するIssueやコミットを見つけられなかったのですが、Twigのバージョンを`1.34.0`以降にするとキャッシュファイルが増えないことを確認しました。
最新のmasterでは`1.35.0`になっており、この問題が発生しないためクローズさせて頂きます。

**Comment by toshiaki-h** [comment]
@kiy0taka ご確認ありがとうございます。
3.0.15にバックポートする場合はどのように対処すればよろしいでしょうか？

**Comment by kiy0taka** [comment]
@toshiaki-h `composer require twig/twig "1.34.0"` を実行してバージョンを上げてもらえばいいかと思います。

**Comment by toshiaki-h** [comment]
@kiy0taka ありがとうございます。そのようにして対応いたします。

**Comment by nobuhiko** [comment]
https://www.ec-cube.net/download/index.php
ここのパッケージは更新したほうがよいのでは？

**Comment by Yangsin** [comment]
この件事態は比較的簡単に対応できそうなので、3.0.16のリリースを急ぎます。
