### ISSUE TITLE
PDF出力系ライブラリを何にするか

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#28]
必須条件
* 日本語対応している
* カスタマイズが容易

理想
* ミリ単位での指定ができる
* Packagistに登録されている

候補
* fpdf
* mPDF
* ThinReports
などを検討していますが、長い目で見てどれがいいか議論の上で決定したいと思います。

**Comment by shutta-** [comment]
FPDFは、ライセンス的に微妙なんじゃないでしょうか。(http://www.fpdf.org/en/FAQ.php#q1)
また、更新も止まっているようですので、「長い目で見て」ということであればそぐわないかと思います。

現状のFPDF+FPDIな実装を踏襲するのであれば、TCPDF(+FPDI)も候補に挙げてみても良いかもしれません。

**Comment by hrdaya** [comment]
横から失礼します。

私もTCPDF(+FPDI)が良いと思います。
ただ、MultiCellの引数などを見ると「なんだこの引数の数は...」といった感じなので、ラッパークラスを作成して簡易に使用できるようにしたほうが良いと思います。

**Comment by Yangsin** [comment]
@shutta- @hrdaya 
ご提案いただいているようなTCPDF(+FPDI)の実装イメージってもうすこし具体的にありますでしょうか。
3.0で対応するかどうかそろそろ決めたいと思います。

**Comment by amidaike** [comment]
pdf出力ライブラリの件ですが、
wkhtmltopdf
というのもあります。
http://wkhtmltopdf.org

EC-CUBEではどの機能でPDF出力するのか分かりませんが参考までにお伝えします。
ライセンスはLGPLv3です。

wkhtmltopdf のラッパーライブラリであるSnappyもあります。
https://github.com/KnpLabs/snappy

Silexでsnappyの使い方も下記urlが参考になります。
https://github.com/GromNaN/SilexServiceProvider/blob/master/doc/snappy.md

**Comment by nobuhiko** [comment]
Symfony2はなんでもありますねぇ
https://github.com/psliwa/PdfBundle

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
ここのComposer.json覗いてみましたがZendに依存してるみたいですねぇ。
もし使ってみた所感などあれば是非おきかせください！

**Comment by shutta-** [comment]
@Yangsin 

> ご提案いただいているようなTCPDF(+FPDI)の実装イメージってもうすこし具体的にありますでしょうか。

すみません、具体的な実装イメージとかは持っていません。
候補にFPDFが挙がっていたので、FPDFを挙げるぐらいならTCPDFを挙げた方が良いんじゃないかと思っただけです。
関数の体系もFPDFと似ているので、既存の方には馴染みやすいかな、と。
という感じなので、あまり積極的な提案を意図したもんじゃないんです。
どちらかと言えば、FPDFは3.0では採用して欲しくなくて、現状の実装と近いものにしたいというニーズがあるなら、TCPDFで代替できるんじゃないでしょうか、という意味合いが近いです。

**Comment by Yangsin** [comment]
Thinreports-PHPが発表されました。
https://github.com/thinreports-php/thinreports-php

PHPバージョンがPHP5.6に限られているため直接採用はできませんが、プラグイン等、検討できるかと思います。

**Comment by Yangsin** [comment]
帳票出力自体プラグイン化されていますので、一度クローズします。
引き続きなにかあれば、以下のリポジトリでお願いします。

https://github.com/EC-CUBE/order-pdf-plugin
