### ISSUE TITLE
web.config の修正

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2830]
## 概要(Overview)
3.0.x の web.config がそのままマージされているが、ディレクトリ構成が変更されているため修正する
https://github.com/EC-CUBE/ec-cube/pull/2823/files#diff-4ec11d3c3b35abfbc40faec85759a628

## 期待する内容(Expect)  or 要望 (Requirement)
IIS環境で正常に動作すること

### 環境 (environment)
+ EC-CUBE: experimental/sf branch

## 関連情報 (Ref)
#2823

**Comment by okazy** [comment]
対応済
