### ISSUE TITLE
ポイント管理のマージ

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2835]
## 概要(Overview)
twig が削除されてしまった

https://github.com/EC-CUBE/ec-cube/pull/2823/files?w=1#diff-b81e768bb95a3410df663bf17ac52991

## 期待する内容(Expect)  or 要望 (Requirement)
- ポイント管理が機能する

## 再現手順(Procedure)
- ポイント管理画面にアクセス

### 環境 (environment)
+ EC-CUBE: experimental/sf branch

## 関連情報 (Ref)
#2823

**Comment by okazy** [comment]
ポイント機能取り込み済
