### ISSUE TITLE
商品詳細画面の規格プルダウンのソート

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2837]
## 概要(Overview)
規格プルダウンがソートできない

以下のテストケースがエラーになってしまう
https://github.com/EC-CUBE/ec-cube/pull/2823/files?w=1#diff-cc19a45b4b765d17bd3ad549cf191150R108

ParamConverter を使うようになったが、 ProductClass の並び順が制御できていない
https://github.com/EC-CUBE/ec-cube/pull/2823/files?w=1#diff-6921efc47b9f1a489315736e1e1874afR300

## 期待する内容(Expect)  or 要望 (Requirement)
- Eccube\Tests\Web\ProductControllerTest::testProductClassSortByRank() が正常に通ること

## 再現手順(Procedure)
- Eccube\Tests\Web\ProductControllerTest::testProductClassSortByRank() がエラーになる

### 環境 (environment)
+ EC-CUBE: experimental/sf branch

## 関連情報 (Ref)
#2823 
#2158

**Comment by okazy** [comment]
修正済
