### ISSUE TITLE
Customer/Member に Serializable を実装する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#2874]
## 概要(Overview)
+ #2865 を移植する
+ 拡張性向上のため AdvancedUserInterface も実装した方が良いかも
+ UserLoaderInterface::loadUserByUsername() の実装も見直した方が良いかも

## 期待する内容(Expect)  or 要望 (Requirement)
+ Customer/Member が正常に serialize/unserialize できる

## 再現手順(Procedure)
+ 特に大きな問題は発生していないが、 Symfony のドキュメントに実装をあわせる

### 環境 (environment)
+ EC-CUBE: 3.n experimental/sf ブランチ

## 関連情報 (Ref)
+ https://symfony.com/doc/3.4/security/entity_provider.html

**Comment by okazy** [comment]
4.1で対応します。
以下のプルリクで対応済み
https://github.com/EC-CUBE/ec-cube/pull/4409
https://github.com/EC-CUBE/ec-cube/commit/9a84daf16d92a5129eb169ac14f9b219e81c5d90
https://github.com/EC-CUBE/ec-cube/commit/0824c7e7a3a776c9eb57e380316599fef105d3eb

**Comment by okazy** [comment]
会員ランクをカスタマイズしているプラグインに影響がある可能性があるので、マイグレーションガイドに記載する。

**Comment by chihiro-adachi** [comment]
4.1で対応済のためクローズします。
