### ISSUE TITLE
plugin dir not found.Error in \Eccube\Application::parsePluginConfigs

### ISSUE THREAD

**Issue by jaassoon** [EC-CUBE/ec-cube#2925]
## 概要(Overview)
plugin dir not found.Error in \Eccube\Application::parsePluginConfigs

## 再現手順(Procedure)
Page URL:http://127.0.0.1:8080/html/ (after fresh install)
Error in \Eccube\Application::parsePluginConfigs line:1253

value of $this['config']['plugin_realdir'] is unix-like format,
such as /d/project_dir/app/Plugin which project locate in d disk.
It cant be parsed by is_dir() function in php7
raise error:
  throw new \InvalidArgumentException(sprintf('The "%s" directory does not exist.', $dir));

### 環境 (environment)
Apache/2.4.26 (windows7)
PHP7.0.28
PostgreSQL 9.2.23
Browser：Google Chrome
Src version:commit af5711a9b

**Comment by ryo-endo** [comment]
@jaassoon 
Thank you for your report.
But, I can't reproduce your issue on my env.

Did you install ec-cube on same environment ?
If you installed on windows, the plugin_realdir value we expect is below.

app/config/eccube/path.yml 
`plugin_realdir: C:\xampp\htdocs\eccube3015/app/Plugin`

May I have more information ?

my env is XAMPP 3.2.2 (Win7,Apache/2.4.29, PHP 7.0.27)

**Comment by jaassoon** [comment]
@ryo-endo if you try installing by run below
```
$ sh eccube_install.sh mysql
```
Maybe you can reprodue the issue.
Because I cant install by eccube_install.php
You can run shell script in windows by git bash or busybox or whatever you like.

**Comment by ryo-endo** [comment]
We're not supposed using eccube_install.sh on windows.
We recommend `eccube_install.php` or `Web Installer`.

> I cant install by eccube_install.php
Which do you mean?
- can't install php on your environment.
- eccube_install.php throw error.
