### ISSUE TITLE
mysql環境における表示速度の改善について

### ISSUE THREAD

**Issue by i-like-sparc** [EC-CUBE/ec-cube#2933]
## 概要(Overview)
query_cacheを使わない状態で、10000件の商品を登録したECCUBEでトップページを表示させると、相当の時間がかかる（手元の環境では2分以上）

ProductRepository.php のコメントにある通り、
$qb->groupBy('p');
を
$qb->groupBy('p.id');
にすると普通に表示される。

ぜひ、この処理を標準のインストール方法でも適用されるようにしてほしい。

## 期待する内容(Expect)  or 要望 (Requirement)
mysql 5.5 or 5.6 の環境で、query_cache を使わない状態でも、トップ画面の表示速度が普通であること。（商品数10000,カテゴリ30）

## 再現手順(Procedure)
1) query_cache を使わないmysql 5.6.37 の環境（普通に mysql をインストールしただけの状態）に、ECCUBE 3.0.15 を標準インストール
2) createEcCubeData-v30.phpを使って、カテゴリ数30(大5、中2、小3）商品数 10000 の商品を登録
3) トップページを表示させる

### 環境 (environment)
+ EC-CUBE: 3.0.15
+ PHP: 5.6.33
+ DB:
  - PostgreSQL x.x.x 
  - MySQL 5.6.37, 5.5.x

## 関連情報 (Ref)
mysql 5.5 でも同様の結果である。

**Comment by okazy** [comment]
こちらの変更はPostgreSQL 9.1以上が必要なため、3.0系での対応はシステム要件的に難しいです。
現在開発中の3.n系でシステム要件が変更になりますので修正予定です。

参照
https://github.com/EC-CUBE/ec-cube/issues/1904

**Comment by okazy** [comment]
4.0で対応済です。
