### ISSUE TITLE
can't login to admin page 

### ISSUE THREAD

**Issue by jaassoon** [EC-CUBE/ec-cube#2945]
## 概要(Overview)
There is any limit in setting admin user? I set the admin user by access url/html/install.php,
and skip the step of db initialization. Then visit the admin page,input user name and password,
the page always redirect back to login page.After some researches,I found that it cause by 'Access Deny exception'
rasing by file of root\vendor\symfony\security\Http\Firewall\AccessListener.php in line 68.
How can I resoved this issue?

### 環境 (environment)
Apache/2.4.26 (windows7)
PHP7.0.28
PostgreSQL 9.2.23
Browser：Google Chrome
Src version:3.0.15

**Comment by kiy0taka** [comment]
Is there a error message at redirected login page?

**Comment by jaassoon** [comment]
message=Access Denied.
xdebug:
`<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Symfony\Component\Security\Core\Exception\AccessDeniedException: Access Denied. in /opt/apps/eccube3/vendor/symfony/security/Http/Firewall/AccessListener.php on line <i>68</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0094</td><td bgcolor='#eeeeec' align='right'>373736</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/opt/apps/eccube3/html/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.3006</td><td bgcolor='#eeeeec' align='right'>10298384</td><td bgcolor='#eeeeec'>Eccube\Application->run( ??? )</td><td title='/opt/apps/eccube3/html/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>57</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.3015</td><td bgcolor='#eeeeec' align='right'>10402680</td><td bgcolor='#eeeeec'>Eccube\Application->handle( ???, ???, ??? )</td><td title='/opt/apps/eccube3/vendor/silex/silex/src/Silex/Application.php' bgcolor='#eeeeec'>.../Application.php<b>:</b>563</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.3210</td><td bgcolor='#eeeeec' align='right'>11667936</td><td bgcolor='#eeeeec'>Symfony\Component\HttpKernel\HttpKernel->handle( ???, ???, ??? )</td><td title='/opt/apps/eccube3/vendor/silex/silex/src/Silex/Application.php' bgcolor='#eeeeec'>.../Application.php<b>:</b>586</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.3211</td><td bgcolor='#eeeeec' align='right'>11668352</td><td bgcolor='#eeeeec'>Symfony\Component\HttpKernel\HttpKernel->handleRaw( ???, ??? )</td><td title='/opt/apps/eccube3/vendor/symfony/http-kernel/HttpKernel.php' bgcolor='#eeeeec'>.../HttpKernel.php<b>:</b>57</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.3214</td><td bgcolor='#eeeeec' align='right'>11685392</td><td bgcolor='#eeeeec'>Symfony\Component\EventDispatcher\EventDispatcher->dispatch( ???, ??? )</td><td title='/opt/apps/eccube3/vendor/symfony/http-kernel/HttpKernel.php' bgcolor='#eeeeec'>.../HttpKernel.php<b>:</b>116</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.3214</td><td bgcolor='#eeeeec' align='right'>11686432</td><td bgcolor='#eeeeec'>Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( ???, ???, ??? )</td><td title='/opt/apps/eccube3/vendor/symfony/event-dispatcher/EventDispatcher.php' bgcolor='#eeeeec'>.../EventDispatcher.php<b>:</b>46</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.3284</td><td bgcolor='#eeeeec' align='right'>11948896</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func:{/opt/apps/eccube3/vendor/symfony/event-dispatcher/EventDispatcher.php:161}' target='_new'>call_user_func:{/opt/apps/eccube3/vendor/symfony/event-dispatcher/EventDispatcher.php:161}</a>
( ???, ???, ???, ??? )</td><td title='/opt/apps/eccube3/vendor/symfony/event-dispatcher/EventDispatcher.php' bgcolor='#eeeeec'>.../EventDispatcher.php<b>:</b>161</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.3284</td><td bgcolor='#eeeeec' align='right'>11948896</td><td bgcolor='#eeeeec'>Symfony\Component\Security\Http\Firewall->onKernelRequest( ???, ???, ??? )</td><td title='/opt/apps/eccube3/vendor/symfony/event-dispatcher/EventDispatcher.php' bgcolor='#eeeeec'>.../EventDispatcher.php<b>:</b>161</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.3302</td><td bgcolor='#eeeeec' align='right'>12082632</td><td bgcolor='#eeeeec'>Symfony\Component\Security\Http\Firewall\AccessListener->handle( ??? )</td><td title='/opt/apps/eccube3/vendor/symfony/security/Http/Firewall.php' bgcolor='#eeeeec'>.../Firewall.php<b>:</b>58</td></tr>
`

**Comment by jaassoon** [comment]
the reason maybe cause by that you first checkout the latest src and complete the installation (It can login normally at this time)
then checkout the 3_0_15 release version by 
`$ git checkout  8720e81`
After that,if you do login,you should reproduce the issue.

**Comment by jaassoon** [comment]
use the existed db and skip the db init

**Comment by ryo-endo** [comment]
If you would not like to init db, you need copy `auth_magic` from previous server.
`auth_magic` is included in `app/config/eccube/config.yml`.

You can see admin-page users in `dtb_members`.(Password is hashed by auth_magic)

**Comment by jaassoon** [comment]
OK. I think that's the point. Thank you @ryo-endo !
