### ISSUE TITLE
メールアドレスのDNSチェックが無効

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2948]
## 概要(Overview)

メールアドレスのバリデーションでDNSをチェックしていない。(想定内の仕様かどうかは不明)

## 再現手順(Procedure)

各種メールアドレス入力部に「test@example」と入力して送信するとvalidとなる。

## 環境 (environment)

+ EC-CUBE: 3.0.15

## 関連情報 (Ref)

- #1520

- https://github.com/symfony/validator/blob/2.7/Constraints/EmailValidator.php#L65

**Comment by nanasess** [comment]
checkHost や checkMX を有効にすれば対応できそうですが、厳密にしすぎると、テストの時などに困るかも
https://symfony.com/doc/2.7/reference/constraints/Email.html#options

**Comment by okazy** [comment]
厳密にチェックしすぎると弊害の方が多くなる可能性が高いので、標準のEC-CUBEとしてここまで厳密なチェックはする予定はありません。
必要な場合は個別の対応をお願いします。
