### ISSUE TITLE
ログファイルをローテーションできるようにする。

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#298]
site.logは現状だと延々と追記されていくため、
設定によりdailyやログファイル最大数を指定できるようにする。
http://silex-users-jp.phper.jp/doc/html/providers/monolog.html#id5

MonologのRotatingFileHandler等を使えば可能となるがsilexでの実装方法は未確認。

**Comment by k-yamamura** [comment]
#37 に記載されている通り、ログ出力仕様が定まってから検討する。

**Comment by Yangsin** [comment]
現状、日付でローテーションされるようになっておりますので、クローズします。
