### ISSUE TITLE
管理画面:商品管理＞商品規格登録 

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#306]
# 商品規格登録

## 仕様変更概要

+ option_class_regist による規格機能の有無は廃止  
+ UI変更に合わせたテイストの変更
+ 販売制限数の追加
+ DL商品の項目の削除

## 機能

+ 規格1と規格2のマトリクスから規格登録ができる
+ 規格1のみでも登録ができる
+ 規格登録のチェックボックスを外して規格の削除ができる

## 登録項目

|項目名|必須|変更内容・備考|
|------------|----------|-----------------|
| 登録 | -| チェック時登録、チェック解除時削除 |
| 規格1 | - | 規格1の分類をテキスト表示 |
| 規格2 | - | 規格2の分類をテキスト表示 |
| 商品コード | - |  |
| 在庫数 | 必須*| *無制限を選択すれば入力Disableにして必須ではなくなる |
| 販売制限数 |-| 販売を制限する数を入力。0=制限しない|
| 無制限 | - | 在庫数を無制限にできる |
| 販売価格 | 必須|-|
| 通常価格 | - | -|
| 商品税率 | -| 商品毎の税率有効時。軽減税率対応|
| 商品種別 | 必須| mtb_product_type、選択肢は通常商品のみ|

**Comment by shinichi-takahashi** [comment]
マージ済のため、クローズします。
