### ISSUE TITLE
config.yml のメール設定が反映されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#307]
config.yml で SMTP の設定をしても反映されません。

**Comment by k-yamamura** [comment]
#316 にてメール設定の修正を行っています。

**Comment by k-yamamura** [comment]
#316 の内容をこちらにも残しておきます。

メール送信の実装方法を修正しメール送信のトランスポートを
smtp、sendmail、mail
のいずれかで送信できるように修正しました。

トランスポートの設定は、
config.ymlの
```
mail:
    transport: smtp
```
というようにsmtp、sendmail、mailそれぞれを設定すると適用されます。
sendmail、mailが設定されたらtransport以外のhostやport等の設定は無視されます。
