### ISSUE TITLE
would you tell me what meaning of the logic_flg?please 

### ISSUE THREAD

**Issue by nvtag** [EC-CUBE/ec-cube#3091]
## 期待する内容(Expect)  or 要望 (Requirement)
would you tell me what meaning of the logic_flg?please ,thank you ^_^

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by t-nagahashi** [comment]
we re-design logic_flg now.
so please check this issue.
https://github.com/EC-CUBE/ec-cube/issues/2314

`logic_flg` meaning is Logical deletes / physical delete.

**Comment by t-nagahashi** [comment]
@nvtag 
If you have some questions,  please ask on developer forum.
https://xoops.ec-cube.net/

**Comment by kiy0taka** [comment]
@nvtag  Did you mean `dtb_block.logic_flg`?
If `dtb_block.logic_log` is `1`, render the fragment for the controller instead of include Twig file.
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Resource/template/default/block.twig

**Comment by nvtag** [comment]
Yes. I do understand now , thank you , so much.
