### ISSUE TITLE
Heroku のサポート範囲について

### ISSUE THREAD

**Issue by mikakane** [EC-CUBE/ec-cube#3093]
## 概要(Overview)

現状Heroku Button はサポートしているものの、以下の問題がある。

- 再起動orDyno並列化でセッション消える
- 再起動orDyno並列化で画像消える

どこまで Heroku での挙動をサポートするのかにもよるが、Cloudinary と Redis をサポートする必要あり。

## 期待する内容(Expect)  or 要望 (Requirement)

再機動やDyno並列化でもセッション、画像が維持されるよう修正

## 再現手順(Procedure)

Heroku の再機動やDynoの並列化設定

### 環境 (environment)

+ EC-CUBE: 3.n.x

**Comment by mikakane** [comment]
セッションの切り替え、Cloudinary 等のストレージスイッチ対応が本家取り込みOKであれば、PR出します。
プラグインでやったほうがよさそう…的な話であればその旨でCloseお願いします。

**Comment by Yangsin** [comment]
どこまで特定のサービス用のコードをいれるかという課題はありますが、他のSaaSやPaaSを利用する上でもベースとなる範囲であれば、本体に入れる事も可能です。
環境周りの設定は、そもそもプラグインでインスールすることも難しいはずなので・・・

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
