### ISSUE TITLE
index_dev.phpの作成

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#315]
#207 の中でも記述しましたがindex_dev.phpを作成し、
開発時はindex_dev.phpにアクセスして開発することにします。
http://localhost/index_dev.php/admin
や
http://localhost/index_dev.php/entry
というようにindex_dev.phpをつけてアクセスするとdebug環境で実行されます。

今までのようにindex.phpに
```
$app = new Eccube\Application(array(
    'env' => 'dev',
));
```
と記述してもdebug環境としては動作しません。

それに伴いApplication.phpファイルにあるdebug用のコードについては
index_dev.phpファイルへ移動させます。

index_dev.phpについてはsilexのskeletonに従って作成します。
https://github.com/silexphp/Silex-Skeleton

**Comment by k-yamamura** [comment]
#316 にて対応済みです。

**Comment by k-yamamura** [comment]
index_dev.phpの31行目に$arrowと許可するIPアドレスまたはドメインを定義していますので、
画面が表示されない方はそこにクライアントのIPアドレスまたはドメインを追加してください。

**Comment by ttsuru** [comment]
:+1:

**Comment by shinichi-takahashi** [comment]
インストーラにて管理画面への接続許可IPを設定したいのですが、同様の方法で可能でしょうか？

**Comment by shinichi-takahashi** [comment]
対応・マージ済のためクローズさせていただきます。
