### ISSUE TITLE
新規会員登録 確認画面に追加フィールドが表示されない

### ISSUE THREAD

**Issue by sw-takaya-murata** [EC-CUBE/ec-cube#3178]
## 概要(Overview)
新規登録確認画面のtwigに追加フィールド用の記述がないため、
新会員登録入力画面で入力した追加フィールドの内容を
登録することができません。

新規会員登録 確認画面
\src\Eccube\Resource\template\default\Entry\confirm.twig

## 期待する内容(Expect)  or 要望 (Requirement)
新規会員登録 確認画面にも入力画面同様の追加フィールド用の記述がほしい。

```
{% for f in form %}
    {% if f.vars.name matches '[^plg*]' %}
        <div class="extra-form dl_table">
            {{ form_row(f) }}
        </div>
    {% endif %}
{% endfor %}
```

## 再現手順(Procedure)
新規会員登録 入力画面で追加したフィールドの内容が、
確認画面ではレンダリングされないので
追加フィールドの内容を登録することができません。

### 環境 (environment)
+ EC-CUBE: 3.0.16

**Comment by chihiro-adachi** [comment]
@sw-takaya-murata 
ありがとうございます。PRも確認させていただきます。

**Comment by chihiro-adachi** [comment]
#3179 で修正済
