### ISSUE TITLE
DIコンテナの利用を検討

### ISSUE THREAD

**Issue by satoshi-m8a** [EC-CUBE/ec-cube#32]
以下の議論でも挙がっていますが、
https://github.com/EC-CUBE/ec-cube/issues/7#issuecomment-68120158
https://github.com/EC-CUBE/ec-cube/issues/7#issuecomment-68125306

DIコンテナを使えば、依存関係も上手く制御できると思います。（テストも書きやすくなります。インターフェースを考えなおす良い機会にもなるでしょう。）是非、検討して頂ければ幸いです。

**Comment by shinichi-takahashi** [comment]
ご意見ありがとうございます。

Silexベースで構築したものをαとしてリリースしております。
本リリースまで大きくブレることはないと予想されるため、本issueはcloseさせていただきます。
