### ISSUE TITLE
税率設定 : 適応日時が9時間ずれる問題

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#3274]
概要(Overview)
DBには00:00:00で入ってるが、グリニッジ標準時扱いされて、twigでdate関数かますと+9hされる

### 環境 (environment)
+ EC-CUBE: 3.n.x experimental/sf
+ PHP: 7.2
+ DB:
  - MySQL 5.6.x

## 関連情報 (Ref)
#3082

**Comment by tao-s** [comment]
確認したところ、商品情報の登録日時、更新日時も9hズレてた。たぶん全部ズレてる

**Comment by tao-s** [comment]
PHP.iniのdefault_timezoneをちゃんとAsia/Tokyoに設定したらズレなくなった。
さて、これどうしよう？EC-CUBE側でdefault_timezoneの設定持ちます？

**Comment by chihiro-adachi** [comment]
@tao-s 
macのロケールは英語にしてます？
あと、.envのECCUBE_TIMEZONEの値を教えてください。

.envのECCUBE_TIMEZONEがAsia/Tokyoで、PC/ブラウザのロケールがenやvnだと発生するようです。

**Comment by chihiro-adachi** [comment]
> DBには00:00:00で入ってるが、グリニッジ標準時扱いされて、twigでdate関数かますと+9hされる

あ、twigでdate関数使う場合は、date_day, date_min, date_secという国際化対応用のフィルタを作ってあるので、こちらを利用ください。

**Comment by tao-s** [comment]
@chihiro-adachi .envでは
`#ECCUBE_TIMEZONE=Asia/Tokyo`
となってますね。なので無視されてたのかな？
この状態で、PHP.INIのdefault timezoneの設定をしなくて+9hが発生しました

**Comment by chihiro-adachi** [comment]
@tao-s 
>#ECCUBE_TIMEZONE=Asia/Tokyo
となってますね。なので無視されてたのかな？

一応未定義の場合のデフォルト値は`Asia/Tokyo`にしているんですが、何かおかしいですね。
こっちでも挙動確認してみます。

以下らへんにtimezoneを設定するコードいれてみたら変わりますか？
https://github.com/EC-CUBE/ec-cube/blob/experimental/sf/src/Eccube/Kernel.php#L88

```
date_default_timezone_set($this->container->getParameter('timezone'));
```

**Comment by tao-s** [comment]
@chihiro-adachi ちょっとやってみますわ

**Comment by tao-s** [comment]
@chihiro-adachi 挙動としては、
`$this->container->getParameter('timezone')`
はPHP.iniのdefault timezoneの設定をコメントアウトして、.envの設定もコメントアウトされている状態でもAsia/Tokyoを返しています。ただ、PHP.iniの設定をコメントアウトすると+9hされてしまうので、そもそもdate_default_timezone_set()が効いていない感じです

**Comment by tao-s** [comment]
おおっとー
@chihiro-adachi 利用しているバージョンでどうかは調べてませんが、MySQLだとタイムゾーン使えないかもです。
http://labs.bucyou.net/Sf-2011-10/#datetimetz

**Comment by chihiro-adachi** [comment]
@tao-s 
> MySQLだとタイムゾーン使えないかもです

はい、それは認識していて、INSERT/SELECTの際にそれぞれ変換をかけて登録or取得するようにしています。
https://github.com/EC-CUBE/ec-cube/pull/2308

**Comment by tao-s** [comment]
@chihiro-adachi じゃあ、PHPのタイムゾーンが設定されていないと、そこの変換がうまく動かない感じですね。
とりあえず #3305 の修正で正常に動く様にはなってますが、環境次第（コードからタイムゾーンの設定がきょかされていない）では動かないかもです。どうしますか？

**Comment by chihiro-adachi** [comment]
@tao-s 

再現するコードもらえますか？
こっちでも事象確認してみます。

**Comment by tao-s** [comment]
@chihiro-adachi コードは experimental/sf のまんまです。
環境依存な現象だと思うので、環境の情報をslackのDMで送りました

**Comment by chihiro-adachi** [comment]
以下の環境を作って試してみたのですが、再現しなかったです。

- mysql: 5.6
- php: 7.2.2
- php.iniのタイムゾーン設定は空

他に要因があるのかもしれません。。

**Comment by chihiro-adachi** [comment]
取り急ぎ #3305 は取り込ませていただきました

**Comment by okazy** [comment]
対応済
