### ISSUE TITLE
フレームワークの利用の検討

### ISSUE THREAD

**Issue by satoshi-m8a** [EC-CUBE/ec-cube#33]
ルーティング機能やDBマイグレーション機能など、これだけの大幅な変更を加えるのであれば、いっそのことフレームワークの利用を検討してみては如何でしょうか。

**Comment by shinichi-takahashi** [comment]
@satoshi-m8a 
Issueたててくださってありがとうございます。
FW利用について、社内外含め検討しておりましたが、いまのところ利用しない方向で考えています。
理由として、昨今のFWの多くがSymfonyComponentsを利用しているため、

* EC-CUBEがFWに依存
* FWがSymfonyComponentsに依存

と、依存関係が多重になってしまい、外部要因でアップデートが引きずられることを懸念しているためです。
また、学習コストが高いことも理由のひとつになっております。

**Comment by shinichi-takahashi** [comment]
ご意見ありがとうございます。

Silexベースで構築したものをαとしてリリースしております。
本リリースまで大きくブレることはないと予想されるため、本issueはcloseさせていただきます。
