### ISSUE TITLE
InstallerCommand実行時にproxyファイルとキャッシュディレクトリを削除する処理を追加

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#3361]
## 概要(Overview)

bin/console e:i のコマンド
kernelがproxyをrequireする前に、proxyを削除する実装が必要。

## 期待する内容(Expect)  or 要望 (Requirement)

Entity拡張をした際にproxyファイルが上記ディレクトリにできますが、DBと不整合が起こるとエラーとなります。開発をしているとしばしば削除したい場面があるのですが、現在手動で削除するしかありません。。

## 再現手順(Procedure)

プラグイン「sample-payment-plugin-1.0.0alpha1」を app/Plugin 配下に「SamplePayment」にリネーム配置し、インストールコマンド（bin/console eccube:plugin:install --code=SamplePayment）、及び有効化コマンド（bin/console eccube:plugin:enable --code=SamplePayment）を実行。
ブラウザにて画面表示を行うと該当のエラーが画面に表示される。

### 環境 (environment)
環境：Windows 8.1 Pro、Xampp V7.2.7（Apache/2.4.33 (Win32)、PHP 7.2.7）

## 関連情報 (Ref)
3.n QA表
https://docs.google.com/spreadsheets/d/14cC6_CScYMP7ttaQlE8Wi_f1bR7SWFdRclRT2Nw8MlY/edit#gid=0

**Comment by okazy** [comment]
開発時は各自の環境でクリーンな状態にしてください。
