### ISSUE TITLE
未ログイン時にお気に入りリンクをクリックするとVariable "Page" does not exist.エラーとなる

### ISSUE THREAD

**Issue by kurozumi** [EC-CUBE/ec-cube#3372]
## 概要(Overview)
未ログイン時にお気に入りリンクをクリックするとVariable "Page" does not exist.エラーとなる

## 期待する内容(Expect)  or 要望 (Requirement)
ログインページに転送？するときのリクエストがサブリクエストのため、
TwigInitializeListener::onKernelRequestでPage変数が登録されないようです。
isMasterRequestの位置を変更するか、onKernelRequestのプライオリティを8以上にしたら動作したのですが。

## 再現手順(Procedure)
未ログイン時にお気に入りリンククリック

### 環境 (environment)
+ EC-CUBE: 3.n-alpha6
+ PHP: 7.1.9
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
修正済
