### ISSUE TITLE
不明な DEFAULT

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#35]
dtb_products_class.product_type_id
初期で使われていない0が初期値。データ移行で不正なデータが発生して発覚。とりあえず削除する。1でも良い気もする。

**Comment by seasoftjapan** [comment]
#36 にて @nobuhiko 様より、1の方が良い旨いただいており、PR削除しております。
その後、管理画面の初期値も確認しましたが、1で大丈夫そうです。

**Comment by nobuhiko** [comment]
PRを削除しなくても、修正コミットしてpushすればPRに反映されたのですが・・

**Comment by seasoftjapan** [comment]
おーー 便利！勉強になります。

**Comment by Yangsin** [comment]
DBまわりかなりかわってますので、こちらは一旦クローズさせていただきます。
