### ISSUE TITLE
CsvImportControllerを継承し、継承元のprotectedのメソッドを呼び出すとエラーになる

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#3512]
## 概要(Overview)

https://github.com/EC-CUBE/ec-cube/blob/555f15a714e900d80733737e6a434f3eaeeb64da/src/Eccube/Controller/Admin/Product/CsvImportController.php#L47-L55

protectedメソッド内から privateプロパティ(メンバ変数)を参照していますが、値が null になっているためエラーになります。

## 期待する内容(Expect)  or 要望 (Requirement)
private になっているプロパティを protected にしてエラーを回避したい。
なお、他のControllerも一通り確認しましたが、問題はなさそうでした。

### 環境 (environment)
+ EC-CUBE: 3.0.16

**Comment by chihiro-adachi** [comment]
#3513
