### ISSUE TITLE
プラグインジェネレータコマンドの修正

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#3516]
## 概要(Overview)

`bin/console eccube:plugin:generate`が一部古い実装のままになっている

### twigテンプレート

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Command/PluginGenerateCommand.php#L487

default_frame.twigに修正

### 設定画面のルーティング
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Command/PluginGenerateCommand.php#L311

[pluginコード(スネークケース)]_admin_configに修正

https://github.com/EC-CUBE/sample-payment-plugin/issues/6

**Comment by nobuhiko** [comment]
逆に未登録プラグインでは、eccube:plugin:generate で作成したままで設定画面へのリンクが出ています。これもバグじゃないでしょうか
`                // プラグイン用設定画面があれば表示(プラグイン用のサービスプロバイダーに定義されているか)
                $unregisterdPluginsConfigPages[$code] = $this->generateUrl('plugin_'.$code.'_config');
`

**Comment by chihiro-adachi** [comment]
,ありがとうございます。
インストール済かつ有効時のみ設定画面が表示される仕様だったはずなので、`eccube:plugin:generate`で作成した直後でリンク出ていればおかしいですね。

**Comment by chihiro-adachi** [comment]
#3731 で修正

**Comment by okazy** [comment]
修正済のためクローズします。
