### ISSUE TITLE
会員登録→購入遷移でシステムエラー

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#3524]
## 概要(Overview)
デフォルトのお届け先がないのが原因と思われる

An exception has been thrown during the rendering of a template ("Notice: Undefined variable: Shipping") in __string_template__18220681e9e1384505f10f187b75cdf939b1b4b227741fc8ab84b770e8f3e5dd at line 279.

## 再現手順(Procedure)
会員登録
カートに商品をいれる
レジに進む

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
お届け先 1件登録しても進めませんでした。別の理由？

**Comment by ryo-endo** [comment]
こちら確認しましたが、どこかのタイミングで対応済みとなっておりますのでCLOSEさせていただきます。
