### ISSUE TITLE
composer updateでsymfony/securityがv2.7.41以上にしてしまうと、管理画面でログインできなくなる。

### ISSUE THREAD

**Issue by sw-takaya-murata** [EC-CUBE/ec-cube#3525]
## 概要(Overview)
composer updateでsymfony/securityがv2.7.41以上にしてしまうと、管理画面でログインできなくなる。

## 期待する内容(Expect)  or 要望 (Requirement)
ECCUBEの本体でsymfony/securityがv2.7.41以上に対応する。
または、composer.jsonでv2.7.40以下に定義する。

## 再現手順(Procedure)
GitHubまたは公式サイトからEC-CUBE3.0.16をダウンロードし、
composer updateを行う。

### 環境 (environment)
+ EC-CUBE: 3.0.16

## 関連情報 (Ref)
https://github.com/symfony/security/blob/c6fc8fd5abe4b0452003720450571290e2f8b734/Http/Firewall/ContextListener.php#L79-L81

**Comment by nanasess** [comment]
この修正でいかがでしょう？
https://github.com/EC-CUBE/ec-cube/pull/2865
既に master ブランチには取り込まれていると思います

**Comment by sw-takaya-murata** [comment]
修正内容確認いたしました。
問題ございません。
