### ISSUE TITLE
画像ファイルをアップロードするUIの、ドラッグ&ドロップの範囲を全画面にしないで欲しい

### ISSUE THREAD

**Issue by nkenji09** [EC-CUBE/ec-cube#3577]
## 概要(Overview)

管理画面の商品詳細画面(new, edit)で
画像ファイルをアップロードするUIの、ドラッグ&ドロップの範囲が
全画面になっているため

商品情報を追加して、同じようなドラッグ&ドロップによって動作する
フィールドを作ろうとした時に、イベントが競合してしまう。

## 期待する内容(Expect)  or 要望 (Requirement)

画像ファイルをアップロードするUIの、ドラッグ&ドロップイベントが
発火する範囲を指定してほしい。

[dropZoneを指定する](http://t-umino-nit.hatenablog.com/entry/2016/10/11/111056)

(4.0では、Twigを正規表現で置き換える方法は非推奨とのことなので
 プラグインによる EC-CUBE本体ファイルへの dropZone の追加は行わない方針で考えています)

## 悩んでいるところ

単純にdropZoneを指定するだけだと
ユーザーが画像をドロップする箇所が、範囲外にずれた時に
ブラウザが画像を表示してしまい(意図せずページが遷移してしまい)
ユーザビリティを下げる可能性があるので、対応方法は考える必要はありそう。

### 環境 (environment)
+ EC-CUBE: 4.0

**Comment by chihiro-adachi** [comment]
@nkenji09 

> 商品情報を追加して、同じようなドラッグ&ドロップによって動作する
> フィールドを作ろうとした時に、イベントが競合してしまう。

こちら再現するコードをいただくことはできますか？
もしかしたら回避方法があるかもしれません。

**Comment by nkenji09** [comment]
@chihiro-adachi 

ご返信ありがとうございます。
ざっくり再現するための Twigを作ってみました。

元々の @admin/Product/product.twig に2点手を加えたものになります。
https://drive.google.com/file/d/1afet1feh1kapoA15eo5q7ulsQwTUGibU/view?usp=sharing

1. [681行目 ~ 761行目] 静的に画像アップロード用のHTMLを2つ配置
2. [258行目 ~ 324行目] アップロード範囲を指定して動作するスクリプト

例えば、追加したアップロード範囲に画像をドロップすると
EC-CUBEデフォルトのサムネイルと、追加したアップローダーの
両方に画像がアップロードされてしまいます。
(temp_image ディレクトリに2つの画像がアップロードされる)

これを、追加したアップローダーの範囲にドロップしたときには
EC-CUBEデフォルトのアップローダーにはアップロードされないようにしたいです。

こちら回避方法があれば、ぜひ教えていただけると嬉しいです。

**Comment by k-yamamura** [comment]
@nkenji09 様

現行のバージョンでは上記の内容を実現するのは不可能なため、
以下のように本体を修正するようにします。

https://github.com/EC-CUBE/ec-cube/pull/3607/commits/a7431f4747a2458ce846d758b966486c1b50aedb

こちらの修正で今までは全画面でアップロード出来たのが指定された範囲内でしかドラッグドロップ出来なくなりますが、
上記の内容が実現できるようになりますのでマージされるまでお待ちください。

**Comment by nkenji09** [comment]
@k-yamamura

ご対応ありがとうございます！
