### ISSUE TITLE
4系でdatetimepickerが使用できない

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#3693]
## 概要(Overview)
https://github.com/EC-CUBE/ec-cube/blob/294a8ec64af9bee2776a6d08af0232d2936e2a1a/html/template/admin/assets/css/bootstrap-datetimepicker.min.css#L2

bootstrap3用のため日付、時間のパネルが表示されず、動作しない。

## 期待する内容(Expect)  or 要望 (Requirement)
4系でもdatetimepickerを使いたい。

### 環境 (environment)
+ EC-CUBE: EC-CUBE 4.0 beta

## 関連情報 (Ref)
githubにいくつかbootstrap4に対応したdatetimepickerがありましたが、安定して利用できるプロダクトであるかの判断はできませんでした。

https://github.com/monim67/bootstrap-datetimepicker
https://github.com/pingcheng/bootstrap4-datetimepicker
https://github.com/tempusdominus/bootstrap-4
https://github.com/unifymonitor/date-time-selector

**Comment by k-yamamura** [comment]
@sw-satoshi-nakano 様
> 安定して利用できるプロダクトであるかの判断はできませんでした。
と記載されていますが何を気にされているのか教えてもらえないでしょうか。

**Comment by sw-satoshi-nakano** [comment]
@k-yamamura
頻繁に更新されるようなライブラリではないかもしれませんが、どれも最終コミットの日時が古かったこと、事例、使い方の説明があまりなかったことが理由になります。

**Comment by chihiro-adachi** [comment]
@sw-satoshi-nakano 
datetimepickerについては、以下のPRで対応を進めています。
https://github.com/EC-CUBE/ec-cube/pull/3589

ライブラリは https://github.com/tempusdominus/bootstrap-4 を使っています。
https://github.com/Eonasdan/bootstrap-datetimepicker の後継ですし、直近でも更新されているので問題はなさそうかと。

**Comment by sw-satoshi-nakano** [comment]
@chihiro-adachi @k-yamamura  
すでにPRがあったのですね。失礼しました。マージされるのを待ちます。
お手数ですがcloseしてください。

**Comment by chihiro-adachi** [comment]
#3589 を取り込みました
