### ISSUE TITLE
ログの処理を monolog で行う

### ISSUE THREAD

**Issue by pineray** [EC-CUBE/ec-cube#37]
ログの処理を monolog を用いて行いましょう。
https://github.com/Seldaek/monolog

**Comment by ttsuru** [comment]
:+1:

**Comment by Yangsin** [comment]
:+1:

**Comment by Yangsin** [comment]
βでは反映しきれていないので送ります。  
ログ出力仕様を別途まとめてFixとします。

**Comment by Yangsin** [comment]
@pineray  @ttsuru 
monolog 自体はすでに実装されていると思いますが、取り扱いがまだ定まっていません。
これまで、mtb_constansに帰さされていたようなログファイルの出力やらはすべてmonologの設定にまとめたいと思いますが、いかがでしょうか？

**Comment by ttsuru** [comment]
@Yangsin 
はい、その方がいいと思います。
いままでできなかった柔軟なログ取得が可能ですので、できるだけ設定でいけることが望ましいと思います。

特に、CRITICALエラーの際だけメールを出したいなどはよく聞いていた要件だと思います。

**Comment by Yangsin** [comment]
@ttsuru 
そろそろログ設計を完了しようと思うのですが、以下のようなログ設計の指針や実装イメージされているものってありますか？
http://qiita.com/nanasess/items/350e59b29cceb2f122b3

**Comment by ttsuru** [comment]
@Yangsin 
おそらくMonologに合わせて、あとは設定で柔軟に変更できればよいのではないでしょうか。

**Comment by Yangsin** [comment]
Monologに明るくなくどの程度の事ができるのかがなかなかわかっていないのですが
設定で変更できる範囲のイメージって
* ログに記録するエラーレベル
* メールを送信するエラーレベル
* メール送信先
* ログファイルのパス
くらいかなと思っていますが、他にも何かイメージございますか。

あとは、エラー以外で、ログを出力するタイミングをどこに仕込むか？
あまり細かなログ出力を埋め込むのは、どこのログかわかりづらいので、
現在のEC-CUBEと同等（管理画面ログインなど）で、よいかと思っています。

**Comment by ttsuru** [comment]
@Yangsin 
ログですが、Monologでは「何を」「どこに」記録するかの対を設定できます。

例えば、「Error以上を ログファイルに」「Critical以上を メールで送信」のように設定できます。

> あまり細かなログ出力を埋め込むのは、どこのログかわかりづらいので、
> 現在のEC-CUBEと同等（管理画面ログインなど）で、よいかと思っています。
こちらについてはdebug toolbarでもmonologのdebugレベルでログを出力しています。
debugはいくら仕込んでも「debugレベルをログファイルに記録」するような設定にしなければ全く出力されません。
debug や info などのレベルを設定するだけで、あとはどのようなタイミングで出力しても分かりづらくなることはないと思います。
ただ、ログを追加するのは大変ですので、現状では、現状のEC-CUBEと同様でいいと思います。

決済モジュールなどで、決済の通信などを詳細まで出力するのであればdebugレベルを設定、決済完了などであればinfoレベルが適切かと思います。

**Comment by Yangsin** [comment]
@ttsuru 
たしかに。デバッグで、ログ出力自体は随時増やしたいところに差し込むでもよさそうですね。
まずは、
既存のEC-CUBEと同等のログをinfoレベルで、ログ出力にする
ということでいきたいと思います。
その他、Debugレベルは開発者が随時設定可能とします。

ログファイルの分割は以下くらいでいかがでしょう？ほぼこれまで同様です。 
* 標準ログファイル
* 会員ログインファイル
* 管理機能ログファイル
* エラーログファイル
* DBログファイル
* プラグインログファイル（オーナーズストアのログ含む）

**Comment by ttsuru** [comment]
@Yangsin 
通常はloggerのログ出力先は1つでやるようです。
Apacheなども含め、1つのソフトウェアからは1つのログファイルという概念のようです。

エラー系のログについては一部errorなどがよいような気がします。

また、設定に関しては以下が参考になると思います。
http://blog.jicoman.info/2014/05/monolog/

**Comment by Yangsin** [comment]
ファイルは1つにまとめても、開発コミュニティやリテラシーの低い運用者から問い合わせ対応とかを想定すると、管理画面からログが絞り込めたほうがよいので、そういった実装がしやすい形ならいいなと思います。
なんやかんや分ける事象はでてくると思うので、エラーくらいは最低限わけておくほうがいいかも。

別途おしえていただいた、複数にわけるサンプル
http://silex-users-jp.phper.jp/doc/html/cookbook/multiple_loggers.html

**Comment by Yangsin** [comment]
ひとまず以下のように実装されております。
https://github.com/EC-CUBE/ec-cube/pull/380
http://qiita.com/shinichi-takahashi/items/f68590961d7bce886aa1
