### ISSUE TITLE
ProductClassControllerクラスへのフックポイント実装

### ISSUE THREAD

**Issue by naoki-shimo** [EC-CUBE/ec-cube#3700]
## 概要(Overview)
商品登録（規格設定）画面の処理に対してフックポイントが全く設置されていない

## 期待する内容(Expect)  or 要望 (Requirement)
EccubeEventsクラスには定義のみされている状態なので、これらを実装してもらいたい

### 環境 (environment)
+ EC-CUBE: 4.0beta

**Comment by ryo-endo** [comment]
@naoki-shimo ありがとうございます。検討させていただきます。

**Comment by naoki-shimo** [comment]
ご確認頂きありがとうございます。

現在プラグインを作成する中で規格ごとに項目を追加したいのですが
Entityの拡張では対応できない項目ですので少なくとも
ADMIN_PRODUCT_PRODUCT_CLASS_EDIT_COMPLETE
のフックポイントがないと処理できない状況です。

ProductClassContorollerクラスに

use Eccube\Event\EccubeEvents;
use Eccube\Event\EventArgs;

を追加した上で130行目付近と160行目付近の
saveProductClassesの処理の後に


                $event = new EventArgs(
                    [
                        'form' => $form,
                        'Product' => $Product,
                    ],
                    $request
                );
                $this->eventDispatcher->dispatch(EccubeEvents::ADMIN_PRODUCT_PRODUCT_CLASS_EDIT_COMPLETE, $event);


を追加して頂く事で使用出来る事は確認しております。
（もしくはsaveProductClassesの中に設置してもよいかもしれません）

すいませんが、リリースまでにご対応頂く事をご検討いただけないでしょうか。

**Comment by chihiro-adachi** [comment]
> Entityの拡張では対応できない項目ですので

こちら詳細お伺いさせていただくことはできますか？
具体的なコードでこれができなかった、とか教えていただければありがたいです。

**Comment by chihiro-adachi** [comment]
@naoki-shimo

**Comment by okazy** [comment]
解決済みのためクローズします。
