### ISSUE TITLE
.envファイルの記述に「%」を利用すると、プラグインのルーティングが追加されない

### ISSUE THREAD

**Issue by sw-takaya-murata** [EC-CUBE/ec-cube#3722]
## 概要(Overview)
.envファイルの記述に「%」を利用すると、プラグインのルーティングが追加されない

## 期待する内容(Expect)  or 要望 (Requirement)
DBのパスワードに記号を利用することがあるので、
正常に動作するようお願いします。

## 再現手順①(Procedure)
MySQLのパスワードに「%」を利用した場合

1. DBの接続の設定を行う
bin/console eccube:install
mysql://eccube:Pass%Word1234@localhost/eccube_db

2. プラグインインストールを行う
bin/console eccube:plugin:install --code=PluginDummy

## 再現手順②(Procedure)
SQLiteのファイル名に「%」を利用した場合

1. DBの接続の設定を行う
bin/console eccube:install
sqlite:///%kernel.project_dir%/var/eccube\%.db

2. プラグインインストールを行う
bin/console eccube:plugin:install --code=PluginDummy

### 環境 (environment)
+ EC-CUBE: 4.0
+ PHP: x.x.x
+ DB:
  - MySQL 5.x
  - SQLite

**Comment by okazy** [comment]
ご報告ありがとうございます。

.envファイルは開発環境での利用を想定しております。

本番環境では.envファイルは使わず、環境変数を設定してのご利用を推奨しております。

開発環境ではファイル名、パスワードの設定に「%」を利用しないようにしていただけますでしょうか。

よろしくお願いいたします。

**Comment by okazy** [comment]
%を二つでエスケープできるので参考にしてください。
https://stackoverflow.com/questions/27274230/how-to-escape-in-parameters-yml-symfony2
