### ISSUE TITLE
ファイル管理に保存した画像ファイルパスコピー機能がほしい

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#3727]
## 概要(Overview)
管理画面>ファイル管理>ファイル一覧の箇所に、
ファイル（画像）パスの表示もしくは、クリップボードへのコピー機能がほしい。

ページ管理などで画像を使用する際に、
ファイルパスが必要になり、どこに保存されているのかわかりづらかったので、
あると便利です。

![image](https://user-images.githubusercontent.com/13776434/44905735-f2a84080-ad4d-11e8-844a-24245c723342.png)

### 環境 (environment)
+ EC-CUBE: 4 β（2018/08/31時点）
+ PHP: 7

**Comment by ryo-endo** [comment]
@chihiro-adachi 対応済みっぽいです

**Comment by chihiro-adachi** [comment]
対応済のためクローズします。4.0.2で対応されたようす。
