### ISSUE TITLE
管理画面>ファイル管理のファイル削除時、TOPディレクトに戻ってしまう

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#3728]
## 概要(Overview)
 [前提]
1. 管理画面>ファイル管理にディレクトリを作成
2. ディレクトリへ移動
3. ファイル削除

管理画面>ファイル管理>ファイル一覧から、ファイル削除時、
TOPディレクトリに戻る。

## 期待する内容(Expect)  or 要望 (Requirement)
削除実行時の、カレントディレクトリを表示する

### 環境 (environment)
+ EC-CUBE: 4 β（2018/08/31時点）
+ PHP: 7

**Comment by ryo-endo** [comment]
@chihiro-adachi 対応済みのようです

**Comment by xuelian311** [comment]
#4148 対応済みですのでクローズします。
