### ISSUE TITLE
[商品詳細]カートに入れる実行時、のモーダルボタンの遷移先を変更したい

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#3729]
## 概要(Overview)
「お買い物を続ける」ボタンではなく、「商品一覧へ戻る」ボタンにしたいです。
商品一覧画面の場合、そのまま別商品を選ぶため「お買い物を続ける」ボタンが適切だと思いますが、
商品詳細の場合続けて商品を買う人は、商品一覧へ戻してあげたほうがいいと思います。

![image](https://user-images.githubusercontent.com/13776434/44906458-e91fd800-ad4f-11e8-8eaf-51c8cc63ce76.png)

**Comment by xuelian311** [comment]
しばらく議論が進んでないため、クローズします。また要望がある方は、issueを立てて番号を関連付けていただけると幸いです。
