### ISSUE TITLE
フロント側のエンティティ拡張の自動出力で、radio及びcheckboxが利用できない

### ISSUE THREAD

**Issue by sw-takaya-murata** [EC-CUBE/ec-cube#3768]
## 概要(Overview)
フロント側のエンティティ拡張の自動出力で、「ec-select」が定義されているため、
radio及びcheckboxが正常に動作しない。
`<div class="ec-select{{ has_errors(f) ? ' error' }}">`

https://github.com/EC-CUBE/ec-cube/blob/660993b12423e7d943bfb32e7950efe22ed5e2b4/src/Eccube/Resource/template/default/Entry/index.twig#L182-L200

## 期待する内容(Expect)  or 要望 (Requirement)
ec-radio、ec-checkboxを定義するように変更する。

### 環境 (environment)
+ EC-CUBE: 4.0

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/3224

**Comment by chihiro-adachi** [comment]
@sw-takaya-murata 
ご報告ありがとうございます。対応検討します。

**Comment by chihiro-adachi** [comment]
#3838 で対応
