### ISSUE TITLE
EC-CUBEイベント実装漏れ

### ISSUE THREAD

**Issue by sw-takaya-murata** [EC-CUBE/ec-cube#3784]
## 概要(Overview)
コントローラーにイベントが実装されていない。

実装されていないイベント（一部）
FRONT_SHOPPING_INDEX_INITIALIZE
FRONT_SHOPPING_CONFIRM_INITIALIZE
FRONT_SHOPPING_CONFIRM_COMPLETE

## 期待する内容(Expect)  or 要望 (Requirement)
リリース前にコントローラーへのイベントの実装する。

### 環境 (environment)
+ EC-CUBE: 4.0

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/3700

**Comment by sw-takaya-murata** [comment]
@chihiro-adachi
まず廃止なのかバグなのか教えていただけないですか？

3系と実装方法を変える場合、サポートや開発等の見通しが変わります。

**Comment by chihiro-adachi** [comment]
@sw-takaya-murata 
すみません、このあたり整理が追いついていないですが、基本的にはフックポイントは非推奨の扱いです。フォーム項目の追加であれば、FormExtensionでの拡張をお願いします。

現在定義されているものを削除するということはありませんが、単純なフォーム拡張のためにフックポイントを定義する、ということは無いかと思います。

**Comment by okazy** [comment]
どうしてもフックポイントが必要なユースケースがあればreopenしてください。
