### ISSUE TITLE
プラグインパッケージの中にResource/assetsが存在するとプラグインのインストールに失敗する

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#3796]
## 概要(Overview)
プラグインパッケージの中にResource/assetsが存在すると、エラーが発生し、プラグインのインストールに失敗する。

エラー
> Failed to create "/PATH/TO/WEB_ROOT/src/Eccube/Repository/Master/plugin/プラグインコード/assets": mkdir(): Permission denied.

エラー箇所
https://github.com/EC-CUBE/ec-cube/blob/ac7ec0ab023dada6ed17bb9a71cd08331bea843a/src/Eccube/Service/PluginService.php#L866-L884

## 期待する内容(Expect)  or 要望 (Requirement)
プラグインコード/Resource/assetsをミラーリングする仕様であればドキュメントに記載してほしい。
動作するようにしてほしい。

## 再現手順(Procedure)
管理画面からインストールした時に発生する。
コマンドラインでのインストールではPluginService::copyAssets()が実行されていないようでエラーが発生しない。

### 環境 (environment)
+ EC-CUBE: 4.0-beta

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/pull/2644
https://ec-cube.slack.com/archives/C03P2Q8QL/p1534386611000100

**Comment by okazy** [comment]
ご報告ありがとうございます。
手元の環境で同様のエラーが確認できました。

プラグインコード/Resource/assetsをミラーリングするのが正しい仕様となりますので、コマンド/画面の両方のインストール方法で正しくファイルを配置できるように修正する必要があります。

開発ドキュメントにも記載したほうがいいですね。

**Comment by okazy** [comment]
@sw-satoshi-nakano #3821 にて修正しましたのでそちらの環境でも確認していただけますか？

**Comment by kanako-kina** [comment]
@sw-satoshi-nakano 
確認いただきありがとうございます。
・管理画面のアンインストール
・コマンドのアンインストール
上記二点も消えるよう修正します。

**Comment by chihiro-adachi** [comment]
#4087 で対応しました。
