### ISSUE TITLE
plugin削除後、プラグイン一覧に表示されているプラグインにインストールボタンを表示したい

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#3811]
## 概要(Overview)
以下操作を行った際に、インストールボタンを表示したい（画像赤枠参照）。
プラグインを探す→プラグインインストール→削除

ここでプラグイン一覧に、プラグイン情報が表示され再インストール可能なはずなので、インストールボタンを表示したいです。

![image](https://user-images.githubusercontent.com/13776434/45296047-bb027b00-b53b-11e8-9d06-4ccf09baf791.png)

### 環境 (environment)
+ EC-CUBE: 4 β2（2018/09/10）

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
