### ISSUE TITLE
Entity拡張機能を利用したプラグインインストール時の問題

### ISSUE THREAD

**Issue by naoki-shimo** [EC-CUBE/ec-cube#3876]
## 概要(Overview)
slackに報告させて頂きましたが、念のためissueとしてあげさせて頂きます。
Entity拡張機能を利用してテーブルにカラムを追加した場合、
プラグインのインストール、もしくはアンインストールするタイミングで無効状態のプラグインが追加したカラムが削除されてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)
無効状態のプラグインが追加したカラムもそのまま保持する

## 再現手順(Procedure)
1.Entity拡張を行うプラグインを2つ用意
2.2つのプラグインをインストール　※この際有効化は行わない
3.2つ目のプラグインをインストールしたタイミングで1つ目のプラグインが追加したカラムが消えています

### 環境 (environment)
+ EC-CUBE: 4.0beta2

## 関連情報 (Ref)
有効化されていないプラグインは、 Doctrine Metadata 上は存在しないので、カラムが無いものとして SchemaTool が削除してしまうようですね。。。
無効化状態のものも含めて Metadata を生成するようにすれば解決できそうです

**Comment by nanasess** [comment]
ありがとうございます。
こちらの修正で解消されていると思います。
https://github.com/EC-CUBE/ec-cube/pull/3855
