### ISSUE TITLE
お問い合わせ番号URLについて

### ISSUE THREAD

**Issue by naoki-shimo** [EC-CUBE/ec-cube#3877]
## 概要(Overview)
現在の仕様では配送方法設定の"お問い合わせ番号URL"には"="を使用する事が出来ません。

## 期待する内容(Expect)  or 要望 (Requirement)
追跡URLについては各社直接詳細確認画面に遷移できるサービスを提供していますので"="は登録可能にした方がいいのではないでしょうか？

例えば
http://jizen.kuronekoyamato.co.jp/jizen/servlet/crjz.b.NQ0010?id=お問い合わせ番号
のようなURLにすれば直接追跡確認のページに飛べます

### 環境 (environment)
+ EC-CUBE: 4.0beta2

**Comment by ryo-endo** [comment]
ありがとうございます。
直近リリースの4.0.0には間に合わないのですが、マイナーバージョンアップで対応可能な内容だと思いますので検討させていただきます。

**Comment by kanako-kina** [comment]
最新バージョン(4.0.0)で確認したところ、"="が入力可能になっていました。
どこかのタイミングで修正されたようなので、クローズします。
