### ISSUE TITLE
管理画面ユーザを削除できない。

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#3907]
## 概要(Overview)
開発フォーラムから報告です。
一度でもログインすると、外部キー制約の問題で管理ユーザを削除できなくなります。
<img width="574" alt="2018-10-04 20 10 49" src="https://user-images.githubusercontent.com/485749/46470520-e5c9b180-c811-11e8-91f1-c51149f63671.png">

## 期待する内容(Expect)  or 要望 (Requirement)
論理削除を復活？

## 再現手順(Procedure)

1. 管理画面から管理ユーザ追加
2. 追加したユーザで管理画面にログイン
3. 別ユーザで管理画面に再度ログインし、メンバー管理で追加したユーザ削除

### 環境 (environment)
+ EC-CUBE: 4.0.0RC
+ PHP: 7.2.x
+ DB:
  - MySQL x.x.x

## 関連情報 (Ref)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=20940&forum=11&post_id=88667

**Comment by shutta-** [comment]
こちら、 #4120 とかと同様にSQLiteの外部キー制約等の問題とかってことはないですかね？

・EC-CUBE: 4.0.2
・PHP: 7.3.4
・DB: PostgreSQL 9.2.24
な環境では問題なく削除できました。

であれば、開発用途向けとされている？SQLiteの扱いと、SQLiteのために論理削除を復活？させるのかっていう話になる感じですかね？

**Comment by chihiro-adachi** [comment]
#5128 で対応
