### ISSUE TITLE
支払方法の上限下限金額設定と、ポイント利用を併用すると、購入が進めなくなる場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3916]
## 概要(Overview)

1 支払方法に以下を設定し、配送方法設定で選択しておく
  - 代引 金額上限50000円 金額下限30001円
  - 代引 金額上限30000円 金額下限0円
2. 45000円の商品を1個カートに入れ、注文手続に進む
3. ポイントを40000ポイント利用する
4. 画面がリロードし、支払方法の選択が外れる

5. 再度、代引を選択しても、4 が繰替えされてしまう

## 期待する内容(Expect)  or 要望 (Requirement)

ポイント利用時に支払い方法上限下限金額を跨いでも、購入を進めることができる

## 再現手順(Procedure)

上記の通り

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9
+ DB:
  - PostgreSQL 10.2

**Comment by okazy** [comment]
#3921 で修正済み
