### ISSUE TITLE
composer.json に require が無いプラグインがあるとプラグインのアンインストールに失敗する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3918]
## 概要(Overview)

プラグイン内包の composer.json に require が無いプラグインがあるとプラグインのアンインストールに失敗する

`ec-cube/plugin-installer` パッケージの不具合

## 期待する内容(Expect)  or 要望 (Requirement)

プラグインの composer.json に以下のようなエントリがあるのが正しいが、無い場合でも動作するようにする
```
  "require": {
    "ec-cube/plugin-installer": "~0.0.3"
  },
```

## 再現手順(Procedure)

1. require の無いプラグインをインストールする
2. require のあるプラグインをインストールする
3. require のあるプラグインをアンインストールする
4. 以下のようなエラーが発生する
```
In PluginInstaller.php line 107:
                            
  [ErrorException]          
  Undefined index: require  
```

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9
+ DB:
  - PostgreSQL 10.2

**Comment by okazy** [comment]
以下のプルリクで対応
https://github.com/EC-CUBE/eccube-plugin-installer/pull/12

**Comment by okazy** [comment]
本体のec-cube/plugin-installerのバージョンを0.0.8に上げる必要がある。

**Comment by chihiro-adachi** [comment]
#4074 で対応
