### ISSUE TITLE
dtb_page.file_name が重複しており、 管理画面から twig の編集ができない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3920]
## 概要(Overview)

- Mypage/delivery_edit
- Shopping/index

が該当する。
管理画面のページ管理から該当のページを編集しようとすると、ファイル重複のエラーになる

- 編集不可のページのみ重複を許すよう、エラーチェックを修正する

## 期待する内容(Expect)  or 要望 (Requirement)

正常にページ編集できる

## 再現手順(Procedure)

- Mypage/delivery_edit
- Shopping/index

上記いずれかを管理画面から編集する

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9
+ DB:
  - PostgreSQL 10.2

**Comment by chihiro-adachi** [comment]
使用していないレコードを参照している状態の様子。
4.0.1のマイグレーションで不要レコードの削除も合わせて必要と思われる。

**Comment by chihiro-adachi** [comment]
#3996 で対応しました。
