### ISSUE TITLE
DoctrineMigrationsBundle を動くようにする

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3925]
## 概要(Overview)

DoctrineMigrationsBundle を動くようにするため、設定を追加する

## 期待する内容(Expect)  or 要望 (Requirement)

`bin/console make:migration` でマイグレーションファイルが生成され、 `doctrine:migrations` コマンドが使用できるようになる

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9

**Comment by chihiro-adachi** [comment]
@nanasess 

`doctrine_migrations`は`parameters`配下ではなく、ルートに定義する必要があります。もしくはyamlファイルを別にしても可。

https://github.com/symfony/recipes/blob/master/doctrine/doctrine-migrations-bundle/1.2/config/packages/doctrine_migrations.yaml

あと、namespaceは`Eccube\`配下でないほうがよさそうです。
こんなコメントが書いてありました。
```
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
```

動作は見れてませんが、取り急ぎ。

**Comment by kanako-kina** [comment]
#3930 で対応済。
