### ISSUE TITLE
CustomizeとPluginでbuildFormの挙動が異なる

### ISSUE THREAD

**Issue by iplogic-kenpou** [EC-CUBE/ec-cube#3926]
## 概要(Overview)
マスターテーブルから情報を取得し、プルダウンやチェックボックスを生成する時、Pluginではvalue=マスターのid、表示内容=マスターのnameになっているが、Customizeの場合は取得時の並び順に関係なくvalue=0からの連番、表示内容=マスターのnameになっている。
また、Plugin側では追加できるパラメーターが追加できない場合がある（classなど）

## 期待する内容(Expect)  or 要望 (Requirement)
Customize側でもPlugin側同様にvalue=マスターのid、表示内容=マスターのnameになる

## 再現手順(Procedure)
buildFormメソッドで（$masterRepositoryはマスターデータのリポジトリ）
```
$builder->add(
    'hoge', ChoiceType::class, [
        'label' => 'hoge',
        'choices' => $masterRepository->findBy([], ['sort_no' => 'DESC']),
        'required' => false,
        'expanded' => false,
]);
```
とする

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP:  7.2.9
+ DB:
  - PostgreSQL 10.5

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
