### ISSUE TITLE
DBのパスワードに記号が入っているものを設定できない

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#3928]
## 概要(Overview)
インストール時にDBのパスワードに記号が入ってると

> 「Malformed parameter "url".」と出て先に進まない。doctrine.yamlのresolve:をとってもあかんし。誰か教えて～！

との事

## 期待する内容(Expect)  or 要望 (Requirement)
consoleでもwebインストーラでも安全に強力なパスワードが設定できるようにしたい。

### 環境 (environment)
+ EC-CUBE: 4.0.0

## 関連情報 (Ref)
https://twitter.com/kick_go/status/1052046233794097152
https://github.com/symfony/skeleton/issues/40

**Comment by sw-takaya-murata** [comment]
関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/3722

**Comment by chihiro-adachi** [comment]
#3928 で対応しました。
