### ISSUE TITLE
無効状態のプラグインのservices.yamlが読み込まれている

### ISSUE THREAD

**Issue by naoki-shimo** [EC-CUBE/ec-cube#3936]
## 概要(Overview)
プラグインにResource/config/services.yamlを配置している場合、無効状態にしても読み込まれている

## 期待する内容(Expect)  or 要望 (Requirement)
無効状態のプラグインのservices.yamlについては読み込まないようにしてほしい

## 再現手順(Procedure)
Resource/config/services.yamlを配置した状態のプラグインを無効化して確認。
例えばCartItemComparatorなどをservices.yamlに記述した状態にすると無効状態でも指定したものが動作している事が確認できる。

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2
prod設定

**Comment by sw-takaya-murata** [comment]
無効化しているプラグインでEntityも読み込まれています。

関連
https://github.com/EC-CUBE/ec-cube/issues/3712

**Comment by chihiro-adachi** [comment]
- services.yamlの読み込み -> Kernel::build()
- プラグインの有効無効の判定 -> EccubeExtension::configurePlugins()

の順に実行されているので、Kernel::build()で読み込みの制御を行うのは難しそうです。

PluginPassで無効なプラグインのコンテナ定義をクリアするのがよいかもしれません。
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/DependencyInjection/Compiler/PluginPass.php#L38

**Comment by chihiro-adachi** [comment]
@naoki-shimo 
https://github.com/EC-CUBE/ec-cube/pull/4088

CartItemAllocator/Comparatorは無効時に読まないようにしてみています。一度ご確認いただけないでしょうか。

**Comment by xuelian311** [comment]
時間がかなり立っていますのでクローズします。本件で困っている方はまたissueのオープンお願いします。
