### ISSUE TITLE
注文受付メールの文言が不適切

### ISSUE THREAD

**Issue by naoki-shimo** [EC-CUBE/ec-cube#3938]
## 概要(Overview)
注文受付メールの商品単価表示についてですが、単価に個数を掛け合わせた金額が表示されているようです。`単価`という表記であれば個数を掛け合わさない方がいいのではないでしょうか？

## 期待する内容(Expect)  or 要望 (Requirement)
{{ OrderItem.total_price|price }}を{{ OrderItem.price_inc_tax|price }}に変更
もしくは
`単価`表記を`小計`などに変更

### 環境 (environment)
+ EC-CUBE: 4.0.0

**Comment by chihiro-adachi** [comment]
`小計`のほうが自然かと思いますので、`小計`に変更する方針で進められればと思います。

**Comment by okazy** [comment]
現在のご注文商品明細

```
************************************************
　ご注文商品明細
************************************************

商品コード：dolore
商品名：じゃなかった紙きれい。 32mm × 32mm 
単価：￥893
数量：1


-------------------------------------------------
小　計：￥893(うち消費税 ￥140)
手数料：￥0
送　料：￥1,000
============================================
合　計：￥1,893
```
