### ISSUE TITLE
CSVの改行コードがLF

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#3945]
## 概要(Overview)
管理画面から出力されるCSVはエンコーディングがWin用になっているにも関わらず、改行コードがCRLFになっていない

## 期待する内容(Expect)  or 要望 (Requirement)
改行コードをCRLFで出力。もしくはUTF-8でLF

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
