### ISSUE TITLE
サイト設定でポイント無しに設定しても、マイページ内のユーザの所持ポイントが表示される

### ISSUE THREAD

**Issue by sw-takaya-murata-zz** [EC-CUBE/ec-cube#3958]
## 概要(Overview)
サイト設定でポイント無しに設定しても、マイページ内のユーザの所持ポイントが表示される

https://github.com/EC-CUBE/ec-cube/blob/01e1dfb396bb1d8ff70180fab3c971c1aa108249/src/Eccube/Resource/template/default/Mypage/navi.twig#L35

## 修正内容
`{% if BaseInfo.option_favorite_product %}`
↓
`{% if BaseInfo.option_point %}`

## 関連情報 (Ref)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=21043&forum=8&post_id=88997#forumpost88997

**Comment by chihiro-adachi** [comment]
ありがとうございます、再現確認しました。

**Comment by chihiro-adachi** [comment]
#4020 で対応
