### ISSUE TITLE
CartItemAllocator のカスタマイズを適用するとシステムエラーが発生する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3959]
## 概要(Overview)

以下 CartItemAllocator のカスタマイズを適用すると、システムエラーが発生する
http://doc4.ec-cube.net/customize_service#支払方法が異なる商品を同時にカートに入れられるようにする

CartItemAllocator::allocate の戻り値が `/cart/buystep/{cart_key}` のパターンにマッチしないため

## 期待する内容(Expect)  or 要望 (Requirement)

CartItemAllocator のサンプルコードが正常動作する

### 環境 (environment)
+ EC-CUBE: 4.0.0

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube.github.io/issues/209

**Comment by apple-x-co** [comment]
**補足**

そもそも以下の手順ではカスタマイズができませんでした。
http://doc4.ec-cube.net/customize_service#%E6%94%AF%E6%89%95%E6%96%B9%E6%B3%95%E3%81%8C%E7%95%B0%E3%81%AA%E3%82%8B%E5%95%86%E5%93%81%E3%82%92%E5%90%8C%E6%99%82%E3%81%AB%E3%82%AB%E3%83%BC%E3%83%88%E3%81%AB%E5%85%A5%E3%82%8C%E3%82%89%E3%82%8C%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B

Slack内で教えていただいてもらった方法が、 `app/config/eccube/packages/cart.yaml` ではなく
`app/config/eccube/services.yaml` に以下を書く方法でした。
こちらであれば、Allocatorが動いていることが確認できました。

```
Eccube\Service\Cart\CartItemAllocator: '@Customize\Service\Cart\CartItemAllocator'
```

そして、 `Customize\Service\Cart\CartItemAllocator` の `allocate` メソッドで文字列を返すとシステムエラーが起きるという流れになっております。
※ `allocate` メソッドの `@return` は、 `string` で定義されております。

**Comment by chihiro-adachi** [comment]
#3962, #4001 で対応しました
