### ISSUE TITLE
キャッシュの再生成中に MySQL がタイムアウトになる？

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3961]
## 概要(Overview)

X Server で **MySQL server has gone away** になる場合がある模様

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&order=ASC&topic_id=21049&forum=2

キャッシュの再生成中にDB接続がタイムアウトになっている可能性

## 期待する内容(Expect)  or 要望 (Requirement)

キャッシュの再生成中にDB接続がタイムアウトにならないようにする

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP:  7.1.18
+ DB:
  - MySQL 5.7

X Server にて発生する模様

**Comment by xuelian311** [comment]
@nanasess 本件現状困っている状況ではないと思いますのでクローズします。また困ることがありましたらissueをお願いいたします。
