### ISSUE TITLE
管理画面から受注登録した場合に pre_order_id が null になる(3系, 4系とも)

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3972]
## 概要(Overview)

管理画面で受注登録した場合、 pre_order_id が null になる。

```
$orderRepository->find(['pre_order_id' => $pre_order_id]);
```
上記のようなコードで、セッションが切れた時など、 `$pre_order_id` に null が渡ってしまうと、予期せぬ受注を取得してしまう可能性があるため、管理画面から受注登録した場合でも、 pre_order_id を設定する

## 期待する内容(Expect)  or 要望 (Requirement)

常にユニークな `pre_order_id` が設定されている

## 再現手順(Procedure)

管理画面から受注登録する

### 環境 (environment)
+ EC-CUBE: 3.x, 4.x

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/issues/1452

**Comment by kazumiiiiiiiiiii** [comment]
こちら、マージされましたので一旦クローズさせていただきます。
