### ISSUE TITLE
app/Customize 以下に services.yaml を置けるようにする

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3973]
## 概要(Overview)

今のところ、 プラグインの services.yaml が最優先されるが、プラグインの動作を個別に調整したい場合もありうるので、 app/Customize 以下にも services.yaml を設置できるようにする

## 期待する内容(Expect)  or 要望 (Requirement)

app/Customize/Resource/config 以下に `*.yaml` ファイルを置くと、自動的にロードされる

### 環境 (environment)
+ EC-CUBE: 4.0.0

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/pull/3962

**Comment by chihiro-adachi** [comment]
#4496 で対応しました
