### ISSUE TITLE
app/Customize 以下にmessages.yaml を置けるようにする

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#3975]
## 概要(Overview)

app/Customize 以下にも messages.yaml を設置できるようにする

## 期待する内容(Expect)  or 要望 (Requirement)

app/Customize/Resource/locale 以下に `*.yaml` ファイルを置くと、自動的にロードされる

### 環境 (environment)
+ EC-CUBE: 4.0.0

## 関連情報 (Ref)

- https://github.com/EC-CUBE/ec-cube/issues/3973
- https://github.com/EC-CUBE/ec-cube/pull/3962

**Comment by Yangsin** [comment]
参考）翻訳ファイル上書きプラグイン
https://github.com/kurozumi/eccube4-CustomizeTranslator4

**Comment by kurozumi** [comment]
本体で対応する場合は以下のpathsに追加するだけで良いんじゃないかと思います。

https://github.com/EC-CUBE/ec-cube/blob/4.0/app/config/eccube/packages/translation.yaml

**Comment by kurozumi** [comment]
下記ディレクトリを用意しておかないとエラーが発生するようです。

app/Customize/Resource/locale/

**Comment by nobuhiko** [comment]
@kurozumi 
`framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/src/Eccube/Resource/locale/'
            - '%kernel.project_dir%/app/Customize/Resource/locale/'
        fallbacks:
            - '%locale%'
`
こういうことではないです？

**Comment by chihiro-adachi** [comment]
#4518 で対応
