### ISSUE TITLE
プラグインのインストール時、システムエラーが発生するがログに何も表示されない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#3990]
## 概要(Overview)

プラグインのインストール時、モーダルで「システムエラーが発生しました」が表示される場合がある。
「＋ログを表示」で、ログを見ても、

```
************* プラグイン名 ***********
```

のみ表示され、デバッグの手がかりがない。

レンタルサーバなど、制限が強いサーバで発生しやすく、これまで経験したケースとしては、以下のいずれか(または複数)の要因で発生していました。

- xdebugが有効になっている  -> xdebugを無効にして解消
- memory_limitが128M  -> memory_limitを512Mにして解消
- max_execution_timeが30  -> max_execution_timeを180にして解消
- composer.json/composer.lockに書き込み権限がない -> 書き込み権限を与える

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
display_errors = on になっていれば、以下の PR にてエラーメッセージが表示されると思います
https://github.com/EC-CUBE/ec-cube/pull/4093

**Comment by okazy** [comment]
> memory_limitが128M -> memory_limitを512Mにして解消

インストール時のメモリの消費量があがっているので、可能なら 512M -> 1024M が無難かと思います。
インストール後に制限の値を戻しておくことをお勧めします。

**Comment by nanasess** [comment]
@okazy プラグインのインストール時は composer API によって memory_limit を自動的に 1.5GB まで伸張するので、 memory_limit の設定は意味無いです

**Comment by okazy** [comment]
訂正ありがとうございます。そうなんですね。

**Comment by chihiro-adachi** [comment]
4.1では、プラグインの数によって変わる可能性はあるものの、ロリポップ・herokuでのプラグインインストールが実行できることを確認できました。
https://github.com/EC-CUBE/ec-cube/issues/4142#issuecomment-913412045

**Comment by xuelian311** [comment]
本件はこちらの  https://github.com/EC-CUBE/ec-cube/pull/4093 で解決されましたので、クローズします。
