### ISSUE TITLE
テーブル命名規則の変更

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#4]
テーブルについているprefix「dtb\_」「 mtb\_」をはずす

**Comment by shinichi-takahashi** [comment]
prefixをとってみたんですが、dtb\_orderがorderとなりCREATE時に予約語エラーになってしまいました。
こちらはバッククォートで対応できるのですが、どうせなら、prefix定義してデフォルトは"ec\_"としてしまってもよいかと考えているのですが、いかがでしょうか？
※WordPressのようにインストール時に変更ができるようなイメージ

皆様のご意見を頂戴して判断したいです。

**Comment by nobuhiko** [comment]
order⇛orders ?

**Comment by nobuhiko** [comment]
> prefix定義してデフォルトは"ec_"

いいと思います！

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
ご意見ありがとうございます！
ordersで解決ですね。。失礼しました。

**Comment by Yangsin** [comment]
改めて要件をまとめます。
*  dtb\_, mtb\_はつけない、複数形に統一
　 dtb_orderはorders
　dtb_products_classはproduct_classesに変更
* table名、column名はsnake_caseとする
* flag系統はXXX_flgに綴りを統一する
* IDカラムを持つ場合は{TABLE_NAME:単数形}_idの形式とする
```
table name: products
ID: product_id
```

* mtb\_系統をひとつのテーブルで取り扱う[issue](https://github.com/EC-CUBE/ec-cube/issues/5)
  ただし、id, name, rank以外の構造のmtb\_（mtb\_constants / mtb\_zipなど）は別table（constants / zip）とする

**Comment by Yangsin** [comment]
Silexへの置き換えを決め、Doctrineを採用したことから以下に訂正します。

*  dtb\_, mtb\_はつける。単数形に統一
* table名、column名はsnake_caseとする
* flag系統はXXX_flgに綴りを統一する
* dtb系でIDカラムを持つ場合は{TABLE_NAME}_idの形式とする
```
table name: dtb_product
ID: product_id
```

* mtb\_系統をひとつのテーブルで取り扱う[issue](https://github.com/EC-CUBE/ec-cube/issues/5) は見送り

**Comment by Yangsin** [comment]
#210 に議論がうつってますので、クローズします。
