### ISSUE TITLE
インストール方法

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#40]
しばらくインストーラーも動作しない感じで、実際の動作を試せていないのですが、どんな感じで環境構築するのでしょうか?

**Comment by shinichi-takahashi** [comment]
掲載できておらず、すみません。
本日中にはREADME.mdに掲載できるように準備しております。

ざっくりですが、現状では下記のような形になる想定です。

+ `git clone http://github.com/EC-CUBE/ec-cube.git`
+ `php composer.phar install`
+ `app/config/eccube/`以下に`config.php`を移動

※Composerが必須になります。

**Comment by seasoftjapan** [comment]
情報ありがとうございます。
> app/config/eccube/以下にconfig.phpを移動

インストール済みの EC-CUBE データベースが必要な感じですか?

**Comment by shinichi-takahashi** [comment]
そうなります。
一度、2.13系を通常通りインストールした後に、その定義ファイルを移動してください。
今のところ/html/install/が正常に動作しない為です。

**Comment by seasoftjapan** [comment]
メイン部が表示されなかったり、404となったりするようですが、現状そういった状況でしょうか?
それとも、異常ですか?
https://www.uploady.com/#!/download/IPRHKtYjq4h/Uz81izfLasnDJziu
https://www.uploady.com/#!/download/P4793Caa4Cm/ueGua~QWhoK8m7Rt

EC-CUBE	2.13.3
サーバーOS	Windows NT 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
DBサーバー	PostgreSQL 9.3.5
WEBサーバー	Apache/2.4.6 (Win32) OpenSSL/0.9.8y PHP/5.5.5
PHP	5.5.5 (Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, Phar, SimpleXML, wddx, xml, xmlreader, xmlwriter, apache2handler, gd, mbstring, mysql, pgsql, mhash)
GD	有効 (GD Version => bundled (2.1.0 compatible), FreeType Support => 1, FreeType Linkage => with freetype, T1Lib Support => , GIF Read Support => 1, GIF Create Support => 1, JPEG Support => 1, PNG Support => 1, WBMP Support => 1, XPM Support => 1, XBM Support => 1, JIS-mapped Japanese Font Support => )

**Comment by tattin** [comment]
html/がDocumentRootになるようにした状態で、eccube_insatall.sh叩いてみていただけますか。
繰り返しになりますが、Composerがインストールされていることが前提となります。

また、α版のため、制約や不具合が多くあります。
お手数をかけ恐縮ですが、ご了承願います。

**Comment by seasoftjapan** [comment]
情報ありがとうございます。
> html/がDocumentRootになるようにした状態で、eccube_insatall.sh叩いてみていただけますか。

試してみます。

> 繰り返しになりますが、Composerがインストールされていることが前提となります。

既に ライブラリーのダウンロードまで終えています。

**Comment by tattin** [comment]
composer.pharも必要ですのでおわすれなきようお願いします。

**Comment by seasoftjapan** [comment]
> composer.pharも必要ですのでおわすれなきようお願いします。

ライブラリーのダウンロード時に使ったものは、composer.json と同じ場所に放置してありますが、他に対応必要でしょうか?

**Comment by tattin** [comment]
composer.jsonの置いてあるディレクトリ(このリポジトリですね)で
`curl -sS https://getcomposer.org/installer | php`
で、composer.pharが落とせるので、そのあとにインストールスクリプト叩けばインストールされると思います。

**Comment by seasoftjapan** [comment]
> html/がDocumentRootになるようにした状態で、eccube_insatall.sh叩いてみていただけますか。

残念ながら、Windows + Cygwin bash だと難しそうな感じですね。

**Comment by seasoftjapan** [comment]
とりあえず、このまま Issue 残させていただいて、通常のルートでセットアップ通るようになった頃に、アナウンスいただけましたら幸いです。

README.md も待ってます！

**Comment by tattin** [comment]
現時点ではWindows環境のことを考慮できてないですね。。すみません。
※正式リリースでは対応予定です。

@nanasessさんがVagrant環境をGitHubに公開してますので、そちらで確認してみていただけますか？？
LAMP環境のvagrantがあると開発が楽になると思います。

**Comment by nobuhiko** [comment]
Windows環境の問題なのか、インストールが上手く言っていないことが問題なのか、それ以外なのか
そこを検証したほうがいいんじゃないでしょうか？

Windows + Cygwin bashならeccube_insatall.shは動きます (Appveyorで確認済み)

**Comment by seasoftjapan** [comment]
>メイン部が表示されなかったり、404となったりするようですが、現状そういった状況でしょうか?
それとも、異常ですか?
https://www.uploady.com/#!/download/IPRHKtYjq4h/Uz81izfLasnDJziu

どうやらインストールの問題ではなく、アプリケーション側だったようです。#44
お騒がせいたしました。

**Comment by yuitsubasapapa** [comment]
2015/02/19 16:20:33 [/index.php] Fatal error(E_COMPILE_ERROR): Cannot redeclare class MDB2_Error on [/usr/share/pear/MDB2.php(977)]

とエラーログに出力され、トップページが開けませんでした。
こんな現象が出ているのは、僕だけか？

**Comment by ttsuru** [comment]
/usr/share/pear/ のMDB2を見ていますね。
conposerは実行されてますか？

**Comment by yuitsubasapapa** [comment]
TSURU

> /usr/share/pear/ のMDB2を見ていますね。

はい。/usr/share/pear/を見ています。

> conposerは実行されてますか？

実行し、正常に終了した状態で、トップページにアクセスした結果現在の状況に陥っています。

**Comment by ttsuru** [comment]
本来であればcomposerで入れればvendor以下のpearを見ると思います。

**Comment by yuitsubasapapa** [comment]
> 本来であればcomposerで入れればvendor以下のpearを見ると思います。
>

あるには、ありますが、pear-pear.php.netとなっていますね。
pearにディレクトリ名変更した方がよいでしょうか？

**Comment by ttsuru** [comment]
Composerは依存関係を自動的に解決してくれるはずです。
vendor以下はcomposerが勝手に作成するので、変更は不要です。

autoloadが正しく動作していないようですね。

**Comment by yuitsubasapapa** [comment]
なるほど。autoloadですか。

 

チェックしてみます。
