### ISSUE TITLE
FAXのバリデーション処理が正しく行われない

### ISSUE THREAD

**Issue by 5ym** [EC-CUBE/ec-cube#4026]
## 概要(Overview)
Entry/index.twigからfaxのフォームテンプレートを削除した際faxが必須項目ではないにもかかわらずバリデーションが動作し確認画面に進めなくなる。

## 期待する内容(Expect)  or 要望 (Requirement)
大変お手数ですがこちらでは技術不足なため再現、調査をお願いいたします。

## 再現手順(Procedure)
1. Entry/index.twigからfaxのフォームテンプレートのみを削除
2. 送信テスト
3. 確認画面に進まない

### 環境 (environment)
+ EC-CUBE: 3.0.16
+ PHP: 7.1.24
+ DB: MySQL 5.7.24

**Comment by chihiro-adachi** [comment]
@16dyui 
カスタマイズの際のご質問などは、開発コミュニティでお願いします。
検索したところ、以下が同様の内容かなと思いました。

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=18839&forum=10

**Comment by 5ym** [comment]
@chihiro-adachi 
ご返信ありがとうございます。バグの可能性があるためこちらに立てさせていただきました。faxに使用しているtelのフォームテンプレートのバリデーションが空欄だった際に引っかかるようになっておりそちらの確認をお願いいたします。  
補足  
faxのフォームテンプレートが呼び出されている状態で確認画面に進み入力画面に戻ると正しい値を入力してください等のエラーメッセージが出ております。意図しないバリデーションが行われている可能性があります
