### ISSUE TITLE
注文受付メールなどに記載されている消費税の表示位置がおかしい

### ISSUE THREAD

**Issue by e2haining** [EC-CUBE/ec-cube#4027]
## 概要(Overview)

デフォルトの注文関連のメールテンプレートでは下記のようになっています。

```
ーーーーーーーーーーーーーーーーーーー
小　計：￥25(うち消費税 ￥3)
　
手数料：￥20
送　料：￥5
ーーーーーーーーーーーーーーーーーーー
合　計：￥50

```

(うち消費税 ￥XXXX) は、商品+手数料+送料を合計した料金の消費税のようで、小計のところに表示されるのはおかしいです

## 期待する内容(Expect)  or 要望 (Requirement)

下記のような表示が正しいと思います

```
ーーーーーーーーーーーーーーーーーーー
小　計：￥25
　
手数料：￥20
送　料：￥5
ーーーーーーーーーーーーーーーーーーー
合　計：￥50
　(うち消費税 ￥3)
```

### 環境 (environment)
+ EC-CUBE: 4.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
**うち消費税** の Order::tax は `@deprecated` となっており、正常な値を表示できませんので、削除する方向で検討したいです。
https://github.com/EC-CUBE/ec-cube/pull/3900
