### ISSUE TITLE
現在設定している支払方法が使用できない配送方法に変更したとき、ヘッダ/フッタが非表示となる

### ISSUE THREAD

**Issue by e2haining** [EC-CUBE/ec-cube#4028]
## 概要(Overview)
　現在設定している支払方法が使用できない配送方法に変更したとき、ヘッダ/フッタが非表示となる

## 期待する内容(Expect)  or 要望 (Requirement)
  現在設定している支払方法がリセットされて、ヘッダ/フッタが表示される

## 再現手順(Procedure)
①管理画面の配送方法設定で
　　　配送方法A：郵便振替、現金書留
　　　配送方法B：現金書留
　　と設定する
②フロントのご注文手続き画面で、
　　　配送方法：配送方法A
　　　支払方法：郵便振替
　　に設定する
③配送方法を「配送方法B」に設定する

### 環境 (environment)
+ EC-CUBE: 4.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by kanako-kina** [comment]
https://github.com/EC-CUBE/ec-cube/pull/3940
上記で修正されているかと思いますので、最新版でご確認ください。

Issueとしては閉じさせていただきます。
何か他問題があれば、再度Issueのご登録をお願いします。
