### ISSUE TITLE
フロントの注文履歴画面で、お問い合わせ欄の改行が「<br />」で表示される

### ISSUE THREAD

**Issue by e2haining** [EC-CUBE/ec-cube#4030]
## 概要(Overview)
/mypage/history/nnn
フロント　注文履歴画面　お問い合わせ欄

お問い合わせの入力テキストの改行がタグ「`<br>`」で表示されてしまう

EC-CUBE管理画面の受注詳細の画面では改行はそのまま表示されています
注文履歴画面でメール配信履歴一覧から該当注文受付メールを開くと、改行はそのまま表示されています
Gmailで受信した注文受付メールでは、改行が半角スペースとなって一行に表示されていました（こちらも対応できればお願いします）

## 期待する内容(Expect)  or 要望 (Requirement)
タグが表示されず、入力した通りの改行となる

### 環境 (environment)
+ EC-CUBE: 4.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by kanako-kina** [comment]
再現しました。テンプレートのエスケープ処理の見直しが必要そうです。

**Comment by okazy** [comment]
修正済みのためクローズします。
