### ISSUE TITLE
フロント ご注文手続き ／ 在庫があるのに在庫不足のエラーメッセージが表示される

### ISSUE THREAD

**Issue by e2haining** [EC-CUBE/ec-cube#4031]
## 概要(Overview)
フロント　ご注文手続き

在庫が０になった商品を在庫ありにして登録後に購入しようとすると、在庫不足のエラーメッセージが表示される。
”「フルーツパフェ」の在庫が不足しております。該当商品をカートから削除しました。”

## 期待する内容(Expect)  or 要望 (Requirement)
表示すべきではないエラーメッセージを非表示

## 再現手順(Procedure)
①在庫がある商品を選択して、ショッピングカードの画面を表示する。
②管理画面で在庫を０にする。
③ショッピングカート画面でレジに進むボタンを押す。
④購入エラー” ご注文手続きが正常に完了しませんでした。大変お手数ですが、再度ご注文手続きをお願いします。”が表示される。
⑤管理画面で在庫ありにする。
⑥1で選択した商品を選択し、レジに進むボタンを押す。
⑦在庫不足のエラーメッセージが表示されるが、購入はできる。

### 環境 (environment)
+ EC-CUBE: 4.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by kanako-kina** [comment]
ありがとうございます、再現することを確認しました。
修正方法を検討します。

**Comment by KenTanaka** [comment]
@xuelian311 @kanako-kina 

■ 原因：
対象のエラーメッセージ（「フルーツパフェ」の在庫が不足しております。該当商品をカートから削除しました。）は
`eccube.front.warning`で設定されているが、本来エラーメッセージを表示すべき④shopping_error.twigではeccube.front.warningを表示させていない為、セッション内にフラッシュメッセージが滞留している。

shopping_error.twig(error_only = trueの為、warning表示せず）
```
<!-- アラートメッセージ -->
{{ include('Shopping/alert.twig', { 'error_only': true }) }}
```

改修案としては以下の2パターン考えられます。

■改修案①
・shopping_error.twigでwarningレベルのメッセージを表示する。

■改修案②
・当該メッセージをeccube.front.warningではなく、eccube.front.errorとしてフラッシュメッセージに登録する。


※いずれの改修パターンでも遷移した/shopping/error/で以下の表示となります。

![Issue4031-EC-CUBE-SHOP-商品購入-購入エラー](https://github.com/EC-CUBE/ec-cube/assets/586502/f3781161-16b8-4d56-b404-b138d664f25b)

**Comment by kiy0taka** [comment]
@KenTanaka このIssueの期待する内容としては「表示すべきではないエラーメッセージを非表示」となっているのでエラーなく購入できることが期待されているのですが、エラーで処理するしかないということでしょうか？

**Comment by KenTanaka** [comment]
@kiy0taka 
④のタイミングでエラーにはなりますが、フラッシュメッセージに登録されている「警告レベル」のメッセージが表示されていません。

⑦のタイミングでは「正常」な状態ですので「購入」はできるのですが、④で設定されている「警告レベル」のメッセージが【後追いで＝正しいタイミングでなく】表示されている事が問題の諸元となります。

表示すべきではないエラーメッセージを非表示とすべきは⑦のタイミングですが、
④のタイミングでフラッシュメッセージを正しく表示しておけば⑦で表示される事はなくなります。

**Comment by kiy0taka** [comment]
@KenTanaka 理解しました、勘違いしていたようです。ありがとうございます。
改修案はどちらも警告をエラーと同等に扱うということになると思います。今回のケースはレアな方でこの方法で解消できると思いますが、警告をエラーとすることで他への影響はないでしょうか？

**Comment by KenTanaka** [comment]
@kiy0taka @xuelian311 
今回、改修案②で臨みたいと思います。（View側のみの修正）

改修案①とした場合、指摘頂いたように「警告」→「エラー」とする事でコントローラ側の判定条件変更など
改修範囲が拡大する可能性があります。

■今回の在庫切れパターン
購入時点の在庫切れパターンは以下の3パターンとなります。
　①カート内に1商品のみ投入 + 購入時点で在庫切れ = **shopping_error**へ遷移
　②カート内に複数商品投入 + 購入時点で全部在庫切れ = **shopping_error**へ遷移
　③カート内に複数商品投入 + 一部商品のみ在庫切れ = **shopping**へ遷移

①②でshopping_errorに遷移している直接的原因は **在庫切れ商品をカートから削除した結果、
カートが空になった**事によります。

③については「購入可能」な商品がカート内に存在する事から、shoppingへ遷移し、warningレベルのメッセージは
購入画面内で正しく表示されます。

■その他パターン
shopping_errorへ遷移する実装は、明確にコントローラ側で「購入不能」が判定された場合のみとなっています。

今回のケースは購入不能エラー判定の過程において、warning と error が同時に発生したパターンとなり、
他に同様のパターンがあったとしても、View側変更のみであれば、エラー判定そのものへの影響はありません。

**Comment by kiy0taka** [comment]
購入フローでの警告とエラーのパターンは以下になると思います。

1. 警告のみ
2. エラーのみ
3. 警告とエラー(関連性なし)
4. 警告とエラー(関連性あり)

おそらく現状は3.を考慮して作られていて、購入フローで警告とエラーが発生したときには、エラーだけ優先して表示しておけば問題ないということだと思います。逆に関連性のない警告を同時に表示すると混乱をまねくだけなのでこの場合はエラーだけで良いと思います。

しかし、今回のようにカートに調整が入って警告が発生した結果エラーになるという4.のパターンをどうするか。
関連性があるのでエラーと警告を同時に表示するのが一番いいですが、関連性の有無を判断できないので3.のパターンとの衝突してしまいます。

不親切ではありますが、エラーさえ表示していれば購入処理をやり直す必要があることはわかるので、購入エラー画面で警告は表示しないでいいのではないでしょうか？
今回の問題である「在庫があるのに在庫不足のエラーメッセージが表示される」については購入エラー画面表示時に警告があれば消しておくとすれば解消されると思います。

**Comment by nkajiwara** [comment]
@KenTanaka 
これまでの流れを確認し、以下でいきたいのですが実装お願いできますか？

■改修案③
・「在庫があるのに在庫不足のエラーメッセージが表示される」については購入エラー画面表示時に警告があれば消しておく

修正後の確認
・引き続き在庫不足の場合は、在庫不足メッセージが出る(もしくは購入フローがどこかで止まる)
・在庫不足が解消されている場合は、警告メッセージが表示されず購入完了する。
