### ISSUE TITLE
メンテナンスモード有効時に、デバッグツールバーが動作しない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4032]
## 概要(Overview)

メンテナンスモードを有効にすると、 `/_profile` もメンテナンスモードとなってしまい、デバッグツールバーが動作しない

## 期待する内容(Expect)  or 要望 (Requirement)

メンテナンスモードでもデバッグツールバーが利用できる

## 再現手順(Procedure)

環境変数を以下のように設定し、メンテナンスモードを有効にする

```
APP_ENV=dev
APP_DEBUG=1
```

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.2.9
+ DB:
  - PostgreSQL 11

**Comment by chihiro-adachi** [comment]
4.1.2で修正されました。
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/8196725/164372177-ff1b3007-4694-47f9-b581-dc68e4cdf878.png">
