### ISSUE TITLE
メンテナンスモード有効にした場合に、管理者はフロント画面の確認ができるようにする

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/ec-cube#4034]
## 概要(Overview)
4.0.1で実装したメンテナンス管理機能で、メンテナンスモード有効にした場合に、フロント画面が表示されなくなるが、管理者はフロント画面の確認ができるようにする

## 再現手順(Procedure)
管理画面よりメンテナンスモードを有効にし、フロント画面へアクセスする。

### 環境 (environment)
+ EC-CUBE: 4.0.1

**Comment by chihiro-adachi** [comment]
#5233
