### ISSUE TITLE
マスターデータ管理でmtb_order_statusを追加できない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4035]
## 概要(Overview)

マスターデータ管理でmtb_order_statusを追加できない。
内部的には以下のエラーが発生している

```
   An exception occurred while executing 'INSERT INTO mtb_order_status (display_order_count, id, name, sort_no, discriminator_type) VALUES (?, ?, ?, ?, ?)' with pa ▶
    \n
    SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: mtb_order_status.display_order_count
```

## 期待する内容(Expect)  or 要望 (Requirement)

- mtb_order_statusで値を追加できること

## 再現手順(Procedure)

- 管理画面＞マスターデータ管理を開く
- mtb_order_statusを選択
- 任意の値を追加し、保存
- 「保存に失敗しました」のエラーが表示される

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by tamagoya** [comment]
こちらの問題ですが、マスターデータテーブルの中でmtb_order_statusにのみ、display_order_countといいう独自パラメータがある事に起因しております。

修正案ですが、以下の2つの対応で悩んでいます。ご意見をいただけないでしょうか。
(1) mtb_order_statusから、display_order_countを別エンティティ(テーブル)に切り出す
(2) AbstractMasterEntityに、getExtendParameterInterfaceという、独自パラメータがあったときに、名前とGet,Setメソッドを取得するための口を用意して、ControllerとFormで利用する

今後のマスターデータテーブルが、独自のパラメータが追加されることがあるのかで、対応方法を決めたいたと考えております。
ご意見を頂ければ幸いです。

**Comment by chihiro-adachi** [comment]
@tamagoya 
独自パラメータはdefault値を定義しているつもりでしたが、現状の実装では効いていないようです。
以下のようにプロパティにも値を設定する必要がありそうです。
https://stackoverflow.com/questions/43195874/doctrine-default-value-vs-null-insert/43200609

ただこれだと、全てのデータの独自パラメータがdefault値に更新されてしまうので、下記のコードのようにコントローラ側での制御が必要になります。

```diff
@@ -141,12 +141,18 @@ class MasterdataController extends AbstractController
                     $data['data']
                 ));
 
+                $repository = $this->entityManager->getRepository($entityName);
+
                 foreach ($data['data'] as $key => $value) {
                     if ($value['id'] !== null && $value['name'] !== null) {
+                        $entity = $repository->find($key);
+                        if ($entity === null) {
+                            $entity = new $entityName();
+                        }
                         $entity->setId($value['id']);
                         $entity->setName($value['name']);
                         $entity->setSortNo($sortNo++);
-                        $this->entityManager->merge($entity);
+                        $this->entityManager->persist($entity);
                     } elseif (!in_array($key, $ids)) {

```

**Comment by kazumiiiiiiiiiii** [comment]
@tamagoya @chihiro-adachi 
マージされましたので、クローズいたします。ありがとうございました。
