### ISSUE TITLE
ECCube 3.0.16 allows admins to upload unrestricted file.

### ISSUE THREAD

**Issue by Hexife** [EC-CUBE/ec-cube#4038]
## 概要(Overview)
In administrator panel, EC-Cube allows someone who has the admin authority to upload unrestricted file. 
It 

## 期待する内容(Expect)  or 要望 (Requirement)
Upload feature should filter the dangerous file type
(reference : [CWE-434](https://cwe.mitre.org/data/definitions/434.html) )

## 再現手順(Procedure)
1. Login the administrator.

2. move to コンテンツ管理 > ファイル管理

3. Just upload the vulnerable files.
php
```
<?php system('id');?>
```

html
```
<html><head><title>test</title></head><body><script>alert(1);</script></body></html>
```

js
```
alert(1);
```

.htaccess
```
AddType application/x-httpd-php .jpg
```
(This file handle the .jpg extension files to execute as php scripts)

4. Access uploaded file directly.
http://[ip]/eccube/html/user_data/[uploaded file]

### 環境 (environment)
+ EC-CUBE: 3.0.16
+ PHP: 5.6.38
+ DB:
  - MySQL 5.7.24

I use the default repo of Ubuntu 17.10 except php5.6 and libapache2-mod-php5.6.

## 関連情報 (Ref)
In the file management feature (Original text : コンテンツ管理 > ファイル管理), ECCube didn't restrict the uploaded file type. 
The list that tested file type is below. 
`PHP, HTML, JS, .htaccess `

Even the administrator only accessible features, they should have the upload file filter because anyone who stole the admin authority (e.g. XSS) can misuse this vulnerability.

PS. I can read the japanese. Sorry about that.

**Comment by okazy** [comment]
@Hexife 
Thank you for reporting.

It's in the specifications.
In EC-CUBE, someone who has the admin authority can customize the source code.

Please contact us from the following link form for security reports.
https://www.ec-cube.net/contact/

**Comment by Hexife** [comment]
OK, I got it. Thank you.
