### ISSUE TITLE
有効化したプラグインが無効と判定されてしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4043]
## 概要(Overview)

データベース上では、 **有効** となっているプラグインが、 Symfony Container 上では **無効** と判定され、動作しない。
有効表示になっているが、プラグインの設定ボタンが表示されない等の問題が発生する。

EccubeExtension にて、 Doctrine ORM が有効化される前に PDO を使用して DB 接続しにいくが、ここで接続に失敗するのが原因。
https://github.com/EC-CUBE/ec-cube/blob/1f68cbaf3a62bf185856d7abefa5612786bcb050/src/Eccube/DependencyInjection/EccubeExtension.php#L109-L114

#3929 にて、パスワードが URL エンコードされるようになったが、エンコードされたパスワードだと接続に失敗する模様

## 期待する内容(Expect)  or 要望 (Requirement)

有効化されたプラグインの設定ボタンが表示される

## 再現手順(Procedure)

データベースのパスワードに `#` や `%` などの記号を使用する

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.2.9
+ DB:
  - PostgreSQL x.x.x 
  - MySQL 5.7.23

**Comment by chihiro-adachi** [comment]
#4047 で対応
