### ISSUE TITLE
EC-CUBE以外のプログラムもパーミッションチェックの対象となっている

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4053]
## 概要(Overview)

レンタルサーバーのプログラムもパーミッションチェックの対象となっている模様

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=thread&topic_id=21361&forum=11&post_id=89737#forumpost89737

## 期待する内容(Expect)  or 要望 (Requirement)
- EC-CUBE の保持するプログラムのみパーミッションチェックの対象とする

## 再現手順(Procedure)
- EC-CUBE以外のプログラムを配置し、Read Only でインストールを実行する

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
#4085 で対応
