### ISSUE TITLE
システム設定>セキュリティ管理で設定した管理画面URLが.htaccessに反映されない

### ISSUE THREAD

**Issue by DaiMotoh** [EC-CUBE/ec-cube#4055]
## 概要(Overview)
システム設定>セキュリティ管理で設定した管理画面URLが反映されない

## 期待する内容(Expect)  or 要望 (Requirement)
マニュアルにて[.envは非推奨](http://doc4.ec-cube.net/quickstart_install)と記載されている為、
APP_ENVにprodが設定されている場合、htaccessに自動で反映してほしい。

## 再現手順(Procedure)
* .envファイルを消す
* .htaccessに下記を手動で設定
```
SetEnv APP_ENV prod
SetEnv APP_DEBUG 0
SetEnv DATABASE_URL mysql://eccube:eccube@localhost/eccube
SetEnv DATABASE_SERVER_VERSION 5
SetEnv MAILER_URL null://localhost
SetEnv ECCUBE_AUTH_MAGIC pQdbavrPPZvJds9J
SetEnv ECCUBE_ADMIN_ALLOW_HOSTS '[]'
SetEnv ECCUBE_FORCE_SSL false
SetEnv ECCUBE_ADMIN_ROUTE admin
```
* システム設定>セキュリティ管理で管理画面URLを"admin2"に設定
* ログアウトされる
* "/admin2"にアクセスすると404が返る

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.1

**Comment by okazy** [comment]
ご報告ありがとうございます。

.htaccessでの環境変数の設定は、よりセキュアに利用いただくための設定方法としてドキュメントに記載しています。
環境変数で設定した場合は[こちら](http://doc4.ec-cube.net/quickstart_install#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%97%E3%81%9F%E5%A0%B4%E5%90%88%E3%81%AE%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A0%85)のマニュアルに記載しております通り、一部機能が制限されてしまいます。
セキュリティと利便性はトレードオフの関係にあり、マニュアルでは利便性を一定落としてでもセキュリティリスクを下げることを推奨しています。

管理画面から.htaccessで設定されている環境変数を変更可能にすることはセキュリティリスクを上げてしまうことになりますので、いただいた方針での対応は難しいかと思います。

それぞれの設定方法のセキュリティリスクと制限事項をご理解いただいた上で、環境にあった方法を洗濯してご利用いただければと思います。

別の問題として、.envが存在しない場合にも登録が完了してログアウトされてしまう問題があります。
こちらは.envの存在をチェックしてエラーとするような処理が必要かと思いますので、エラー処理を追加する方針で対応を検討できればと思います。

[こちら](https://github.com/EC-CUBE/ec-cube/issues/4061)に別途issueを作成させていただきました。

本issueはクローズとさせていただきます。
