### ISSUE TITLE
プラグインが無効の状態だと Doctrine SchemaTool でエンティティ拡張が認識されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4056]
## 概要(Overview)

プラグインが無効の状態になっていると、`@EntityExtension` で拡張したカラムを Doctrine SchemaTool が認識しない。

`@EntityExtension` で拡張したカラムは、プラグインが無効の状態でも、 DB には追加された状態となっているのが正しいが、 `bin/console doctrine:schema:update` コマンドなど、 Doctrine SchemaTool はこれを認識することができないため、そのまま `doctrine:schema:update` を実行すると、追加されたカラムが削除されてしまう場合がある。

## 期待する内容(Expect)  or 要望 (Requirement)

`bin/console doctrine:schema:update`  コマンドで、無効状態のプラグインのエンティティ拡張を正しく認識する

## 再現手順(Procedure)

1. `@EntityExtension` を使用したプラグインを無効にする
2. `bin/console doctrine:schema:update` を実行する
3. カラムを削除する SQL が表示される

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.2.9
+ DB:
  - PostgreSQL 11.1
  - MySQL 5.7.16

**Comment by chihiro-adachi** [comment]
#4058 で対応しました
