### ISSUE TITLE
受注編集時に不必要なデータが更新される

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#4059]
## 概要(Overview)
受注編集時に不必要なデータが更新される

### 環境 (environment)
+ EC-CUBE: 4.x.x

## 関連情報 (Ref)
src/Eccube/Form/Type/Admin/OrderType.php

        // 会員受注の場合、会員の性別/職業/誕生日をエンティティにコピーする
        if ($Customer = $Order->getCustomer()) {
            $Order->setSex($Customer->getSex());
            $Order->setJob($Customer->getJob());
            $Order->setBirth($Customer->getBirth());
        }

**Comment by nobuhiko** [comment]
$Customer->getSex() など値がない時に、システムエラーが発生する

**Comment by kazumiiiiiiiiiii** [comment]
@nobuhiko さん、いつもありがとうございます。
こちら、以下の再現方法で検証してみましたが、システムエラーは確認できませんでした。

1. 会員登録時に「生年月日」「性別」「職業」を未設定のまま登録を行う。
　（dtb_customerを確認。sex_id, job_id, birthがそれぞれNULLの状態）
2. 商品を登録した会員で購入。
3. 「管理画面/受注管理」から、2で登録された注文情報を編集し、保存。

こちらのシステムエラーの問題は、すでに解決済みでしょうか？
@nobuhiko さんが確認されている、発生する環境や再現手順などあれば、教えていただけないでしょうか？

または、「受注編集時に不必要なデータが更新される」という仕様の変更してほしいということでしょうか？

**Comment by nobuhiko** [comment]
@kazumiiiiiiiiiii debugモードだとエラーが出ないでしょうか？なにぶんこれを書いたのが2018年だったので、記憶がありません。

**Comment by kazumiiiiiiiiiii** [comment]
@nobuhiko ご確認ありがとうございます。

> なにぶんこれを書いたのが2018年だったので、記憶がありません。

回答が遅くなり、申し訳ありません。

.envでAPP_ENV=devで実行してみましたが、システムエラーは発生しませんでした。

「受注編集時に不必要なデータが更新される」状態に関しては、仕様として問題があると思うので、4.0.x以降となりますが、修正を行なっていきたいと考えております。

**Comment by okazy** [comment]
~~新規受注の場合には必要な処理なので、「受注の性別/職業/誕生日が設定されていなければ情報を更新」にするのがいいかと思います。~~
認識が間違っていました。一つ下のコメントを参照 (2021/03.24 追記)


https://github.com/EC-CUBE/ec-cube/blob/f5dd1c85efde38e1344dff8a93b4885fb580ff7f/src/Eccube/Form/Type/Admin/OrderType.php#L381-L386

**Comment by okazy** [comment]
Issue 検討会より

`$Order->getCustomer()` が null の場合は非会員購入を表す。
初回受注作成時の判定は `$Order->getId()` のチェックで行える。

https://github.com/EC-CUBE/ec-cube/blob/f5dd1c85efde38e1344dff8a93b4885fb580ff7f/src/Eccube/Form/Type/Admin/OrderType.php#L382

**Comment by chihiro-adachi** [comment]
Sex/Job/Birthは、受注の新規登録時かつ会員購入時のみ更新する

**Comment by chihiro-adachi** [comment]
#4997 で修正しました。
