### ISSUE TITLE
セキュリティ管理において、.envが存在しない場合でも登録が完了してしまう

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4061]
## 概要(Overview)
[マニュアルの方法](http://doc4.ec-cube.net/quickstart_install)に従い.envではなく.htaccessで環境変数で設定した場合、.envファイルがないにもかかわらずセキュリティ管理で登録が完了してしまう。

## 期待する内容(Expect)  or 要望 (Requirement)
.envが存在しない場合は管理画面から変更ができない旨のエラーを画面に表示させる

## 再現手順(Procedure)
* .envファイルを消す
* .htaccessに下記を手動で設定
```
SetEnv APP_ENV prod
SetEnv APP_DEBUG 0
SetEnv DATABASE_URL mysql://eccube:eccube@localhost/eccube
SetEnv DATABASE_SERVER_VERSION 5
SetEnv MAILER_URL null://localhost
SetEnv ECCUBE_ADMIN_ALLOW_HOSTS '[]'
SetEnv ECCUBE_FORCE_SSL false
SetEnv ECCUBE_ADMIN_ROUTE admin
```
* システム設定>セキュリティ管理で管理画面URLを"admin2"に設定
* ログアウトされる
* "/admin2"にアクセスすると404が返る

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.1

## 関連情報 (Ref)

#4055

**Comment by chihiro-adachi** [comment]
#4064 で対応
