### ISSUE TITLE
CategoryTypeExtension でフォームを追加しても編集画面にはフォームが出ない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#4063]
## 概要(Overview)
新規作成のフォームは追加されるが、編集ボタンを押したときに出てくる場所にはフォームが追加されない

### 環境 (environment)
+ EC-CUBE: 4.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
対象画面：管理画面 -> 商品管理 -> カテゴリ管理
カテゴリのテンプレートの編集フォームにもエンティティ拡張の自動出力処理を追加する必要がある。

https://github.com/EC-CUBE/ec-cube/blob/66937034780fda3dd8aa9354ee6bfeb62b8ac787/src/Eccube/Resource/template/admin/Product/category.twig#L268-L280
