### ISSUE TITLE
eccube:plugin:update でスキーマ更新されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4065]
## 概要(Overview)
eccube:plugin:update でスキーマ更新の実装が漏れている

## 期待する内容(Expect)  or 要望 (Requirement)
eccube:plugin:update でスキーマ更新が実行される

## 再現手順(Procedure)
eccube:plugin:update コマンドを実行する

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by KenTanaka** [comment]
@xuelian311 
4.2.1では発生しません。

**Comment by xuelian311** [comment]
ありがとうございます。解消されているようですので、クローズします。
