### ISSUE TITLE
descriptionがタイポしている

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/ec-cube#4069]
## 概要(Overview)
以下ファイルで**descriptionがdescriptiron**になっている。
```
/html/template/default/assets/css/style.css
/src/Eccube/Resource/template/default/Block/eyecatch.twig
/src/Eccube/Resource/locale/messages.ja.yaml
```

## 期待する内容(Expect)  or 要望 (Requirement)
タイポが修正されている。

### 環境 (environment)
+ EC-CUBE: 4.0.1

**Comment by okazy** [comment]
eyecatchのブロック内でタイポしています。
テンプレートに影響はありますが、動的な処理はありませんのでマイナーバージョンで修正しても問題ないかと思います。

**Comment by nanasess** [comment]
メッセージキーは古いものも残しておく必要があるかと。

**Comment by okazy** [comment]
こちらで修正されましたのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4220
