### ISSUE TITLE
お問い合わせ完了・購入完了でシステムエラー

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#407]
myapp.CRITICAL: Swift_RfcComplianceException: Address in mailbox given [] does not comply with RFC 2822, 3.6.2

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
RFC規約に沿っていないメールアドレスが入力されているのでしょうか？

以下のプルリクで、インストール時にメールアドレス整合のチェックをかけるようにしました。
https://github.com/EC-CUBE/ec-cube/pull/415

**Comment by nobuhiko** [comment]
よくわからないですが、インストール時に最初の画面で入力した内容がDBに登録されなかった為に起きた現象な気がします
インストールしなおしたら直りました

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
beta4時に環境によってDB接続が正常に動作しない場合があり、beta4以降に修正したのでその影響かもしれません。
ご確認、ご回答ありがとうございます。

**Comment by shinichi-takahashi** [comment]
現状起きないということでクローズいたします。

**Comment by nobuhiko** [comment]
いやいやいや、データが入ってないと落ちる部分は修正すべきでは？

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
あ、ごめんなさい。インストール時に入らない問題だって勝手に脳みそですり替えてました。
メール送信時の確認は必要ですね。
再オープンいたします。

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
あれ？でも、メールアドレスが入っていない状態というのがそもそも異常で、
その際は、システムエラーが起きていい（＝管理者にエラー通知がいってほしい）ものになりませんか？

メールアドレスが入ってない場合は、メールを送らない、という仕様にしてしまうと、
管理者側が問い合わせがあったかどうかをキャッチするすべがなくなってしまう懸念があります。

**Comment by k-yamamura** [comment]
@nobuhiko 
そもそもメールアドレスが入っていないというのはFrom、Toどちらを指している状態でしょうか。
Fromに関してはメールアドレスチェックを#415で対応した事で解消されており、
Toに関しては会員登録時や非会員購入時に入力チェックをかけている事で防いでいます。

メールアドレスに異常な値が入っている時は上記の指摘通りシステムエラーで良いと思います。

**Comment by nobuhiko** [comment]
@shinichi-takahashi 
購入完了時にメールが飛ばない程度で、システムエラーになってしまうほうが困る気がします
エラー通知と言ってもエラーログに履かれるだけでは・・・
もしこの状態になったらお問い合せからお問い合せしようとしても送れませんよ？

**Comment by nobuhiko** [comment]
@k-yamamura 
たぶんFromだと思いますが、どちらでも関係ないとは思います。
100％起きないのであれば、修正の必要はないです

**Comment by Yangsin** [comment]
現在は再現性がないためクローズします。
