### ISSUE TITLE
faviconパスの変更

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4070]
## 概要(Overview)
faviconの変更を容易に出来るようにするために、パスをuser_data以下に変更。

▼現在のパス
html/template/default/assets/img/favicon.ico

## 対応方法
・faviconをuser_dataに移動させる。
・default_frame.twigに記載されているfaviconのパスを変更。

**Comment by nanasess** [comment]
インストーラで favicon を user_data 以下にコピーするようにしたい
 - ショップ独自の favicon に変更後は、 Git のバージョン管理から外したい(EC-CUBEのソースに含めない)
 - 既存のデザインテンプレートに極力影響を与えないようにしたい

**Comment by chihiro-adachi** [comment]
#4075 で対応
