### ISSUE TITLE
ファイル管理にてアップロードしたファイルパスの表示

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4072]
## 概要(Overview)
ページ編集などで画像の差し替えがしやすい様に、ファイル管理にてアップロードしたファイルパスを表示する。

## 方針
現在、ファイル管理でファイルアップロードした際にファイルパスが表示されないため、ページ編集などでパスの変更に手間がかかる(EC-CUBEのルールがわかっていないと、そもそもパスもわからない)状態となってしまっている。
ファイルパスの表示が出来れば上記問題は解決出来るが、運用の手間を省くための工夫は検討したい。

## 期待する内容(Expect)
・ファイル管理にてアップロードした画像のファイルパスがわかる。
・よく使われると想定される機能のため、クリップボード貼り付けなど、簡単にコピーできる機能があればなお良い。

## 対象画面
http://XXXX/admin/content/file_manager
![image](https://user-images.githubusercontent.com/13776434/52252374-80173e80-2945-11e9-861e-db7be2de7480.png)

**Comment by chihiro-adachi** [comment]
#4080 で対応
