### ISSUE TITLE
商品画像に大文字のJPG画像がアップロードできない

### ISSUE THREAD

**Issue by yosshieee** [EC-CUBE/ec-cube#4077]
## 概要(Overview)
aaa.jpgはアップロードできるが、aaa.JPGはアップロードできない

### 環境 (environment)
+ EC-CUBE: 4.0.1

**Comment by nanasess** [comment]
EC-CUBE3系でしょうか？🤔

**Comment by yosshieee** [comment]
@nanasess 
環境情報、テンプレートのまま登録したので3.x.xになってました。。
４系の事象です。

**Comment by chihiro-adachi** [comment]
#4139 で対応
