### ISSUE TITLE
EC-CUBE 4系 - プラグイン有効化・無効化ボタンが重なって表示される

### ISSUE THREAD

**Issue by koyamaps** [EC-CUBE/ec-cube#4078]
## 概要(Overview)
EC-CUBE 4.0.1 のプラグイン有効化、無効化、削除をする際に表示されるアイコンが低解像度のブラウザーで表示すると押したアイコンの隣のアイコンを押したと条件判定されるため、有効化を試みた際に削除が開始される恐れがある。

## 期待する内容(Expect)  or 要望 (Requirement)
HTMLで書かれているグリッドデザインを修正することでアイコンが重なる問題を回避が可能。

## 再現手順(Procedure)
`インストール先ディレクトリー/store/plugin`

### 環境 (environment)
+ EC-CUBE: 4.0.1

**Comment by chihiro-adachi** [comment]
関連：#3979

**Comment by chihiro-adachi** [comment]
#4081 で対応
