### ISSUE TITLE
お問い合せページのカナがひらがなを許容しない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#408]
![__ _ _](https://cloud.githubusercontent.com/assets/604492/8389428/2d363996-1cab-11e5-8bb1-a2d7b976371b.png)

購入遷移は大丈夫だった

**Comment by nobuhiko** [comment]
![_-_ec-cube](https://cloud.githubusercontent.com/assets/604492/8499970/ec4d94ce-21d2-11e5-8e1d-b6a4ad137f65.png)

**Comment by Yangsin** [comment]
本来は変換を自動で入れてあげたいですね。。。

**Comment by tamagoya** [comment]
以下に紹介されているjquery.autoKana.jsを使うのは妥当でしょうか?
▼jquery.autoKana.jsで自動カナ入力する
http://qiita.com/u-chida/items/6c07d558b3f06c9ed8d8

**Comment by ttsuru** [comment]
フロントエンドで入力補助ができればベストですね。

最低限、Form側で行える仕組み(2のKVaなどの設定)ができると必要があるのではと思いますがいかがえしょうか。

**Comment by nanasess** [comment]
@tamagoya たしか、そのままでは満足に動かなくて、某案件でカスタマイズしたやつ使ってますよ

**Comment by nobuhiko** [comment]
入力補助はあると親切だと思います
それとは別にカナがカタカナじゃないとダメな理由がよくわからないです
「有効な値ではありません」も意味不明だし
