### ISSUE TITLE
オーナーズストアから独自プラグイン以外を有効化する時にボタンが重なる問題が解決していない

### ISSUE THREAD

**Issue by koyamaps** [EC-CUBE/ec-cube#4092]
## 概要(Overview)
EC-CUBE 4.0.1 のプラグイン有効化、無効化、削除をする際に表示されるアイコンが低解像度のブラウザーで表示すると押したアイコンの隣のアイコンを押したと条件判定されるため、有効化を試みた際に削除が開始される恐れがある。既に独自プラグインのインストール時に起きる事象は #4078 で解決しているものの、認証キーを入力してインストールする場合は解決していない。

## 期待する内容(Expect) or 要望 (Requirement)
オーナーズストア（ec-cube.net）側を修正する必要がある可能性が高いのではないかと予測。コード自体は本体で既に修正済みですので、同様のコードを置き換えるだけで解決が可能と考えています。

## 再現手順(Procedure)
`インストール先ディレクトリー/store/plugin`

### 環境 (environment)
* EC-CUBE: 4.0.1

**Comment by chihiro-adachi** [comment]
@koyamaps 
こちらのテンプレートで処理してませんか？
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Resource/template/admin/Store/plugin_table_official.twig

**Comment by koyamaps** [comment]
@chihiro-adachi : 失礼しました、こちらのファイルを見逃していました。

**Comment by chihiro-adachi** [comment]
@koyamaps 
ご確認ありがとうございます。
#4081 と同様の対応で修正できそうですね。

**Comment by okazy** [comment]
以下でこちらの問題も解決しているかもしれません。
確認してクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4800

**Comment by chihiro-adachi** [comment]
#4988 で修正済のためクローズします
