### ISSUE TITLE
appディレクトリにあるmigrationファイルが必要なものか分からない

### ISSUE THREAD

**Issue by yoshiaki-natsume** [EC-CUBE/ec-cube#4094]
## 概要(Overview)

`app/DoctrineMigrations/Version20181017090225.php`
`app/DoctrineMigrations/Version20181109101907.php`

の2ファイルがEC-CUBEを動かす上で必要なのか不要なのかわかりません

## 期待する内容(Expect)  or 要望 (Requirement)

不要であれば削除したいし、必要であれば初期データに含めるようにしたいです。
いずれにしろappディレクトリ以下のDoctrineMigrationsには含めるべきファイルではないと思います。

## 再現手順(Procedure)

自分でマイグレーションファイルを作成していないのに上記2ファイルがあるために
`./bin/console doctrine:migrations:status`
を打つと
`    >> Available Migrations:                               2`
と表示されてしまう

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.2.14
+ DB:
  - MySQL 5.7.25

**Comment by chihiro-adachi** [comment]
ありがとうございます。

EC~CUBEをバージョンアップする際の手順として、ファイルの更新後、マイグレーションを実行しDBの変更分を適用する流れになります。その際にマイグレーションファイルが必要になります。

http://doc4.ec-cube.net/quickstart_update

初期データにはマイグレーションのデータは含まれているため、最新版をインストールした場合は、確かにご指摘の表示になりますね。

**Comment by chihiro-adachi** [comment]
@yoshiaki-natsume 
コメントの通り、バージョンアップ時には必要になります。
また未実行のマイグレーションが実行されても特に問題は発生しないと考えていますので、こちらはクローズさせていただきます。

もしご意見等ありましたらReOpenしてください。
