### ISSUE TITLE
プラグインをアンインストールしたらテーブルが削除されてしまう場合がある

### ISSUE THREAD

**Issue by kurozumi** [EC-CUBE/ec-cube#4097]
## 概要(Overview)
BlockTraitを実装しているプラグインAと、Blockというクラス名のエンティティを実装しているプラグインBがインストールされている場合、プラグインBをアンイストールするとdtb_blockテーブルが削除されました。

## 再現手順(Procedure)
1.  BlockAプラグインをbin/console eccube:plugin:generateで作成
2. BlockAプラグインに以下のようなBlockTraitを作成

```
namespace Plugin\BlockA\Entity;

use Doctrine\ORM\Mapping as ORM;
use Eccube\Annotation as Eccube;

/**
 * @Eccube\EntityExtension("Eccube\Entity\Block")
 */
trait BlockTrait {
    
    /**
     * @ORM\Column(name="sample", type="boolean", options={"default":false})
     */
    private $sample;
}
```
3.  BlockBプラグインをbin/console eccube:plugin:generateで作成
4.  BlockBプラグインに以下のようなBlockエンティティを作成

```
namespace Plugin\BlockB\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Block
 *
 * @ORM\Table(name="plg_block_b_block")
 * @ORM\Entity(repositoryClass="Plugin\BlockB\Repository\BlockRepository")
 */
class Block
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", options={"unsigned":true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}
```

5.  bin/console eccube:plugin:install --code BlockAでBlockAプラグインをインストール
6. bin/console eccube:plugin:install --code BlockBでBlockBプラグインをインストール
7. bin/console eccube:plugin:uninstall --code BlockBでBlockBプラグインをアンインストール

これでdtb_blockテーブルが削除されました。

BlockAプラグインなしでBlockBプラグインのインストール・アンインストールした場合はdtb_blockテーブル削除されませんでした。

上記、bin/console eccube:installで初期化を行ったあとも同様の現象が起こりました。

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.2.9
+ DB:
  - PostgreSQL x.x.x 
  - MySQL 5.7.23

**Comment by chihiro-adachi** [comment]
@kurozumi 
ありがとうございます、再現確認しました。
原因箇所の調査すすめていきます。

**Comment by nanasess** [comment]
通常、ここでは `Plugin\BlockB\Entity` の namespace が取得されるはずだが `Eccube\Entity` を取得してしまっているのが原因ぽい

https://github.com/EC-CUBE/ec-cube/blob/0da26a9bd0d63683281c3bcced085af4e2f163a5/src/Eccube/Doctrine/ORM/Mapping/Driver/ReloadSafeAnnotationDriver.php#L129-L131

**Comment by nanasess** [comment]
ここで namespace を考慮せずにパスを置換しているため、 既存のエンティティと同名のエンティティは上書きされてしまう

https://github.com/EC-CUBE/ec-cube/blob/0da26a9bd0d63683281c3bcced085af4e2f163a5/src/Eccube/Doctrine/ORM/Mapping/Driver/ReloadSafeAnnotationDriver.php#L98

**Comment by kazumiiiiiiiiiii** [comment]
マージいたしましたので、クローズします。
