### ISSUE TITLE
商品管理画面で販売価格を変更しても更新日が変わらない

### ISSUE THREAD

**Issue by moritahiroo** [EC-CUBE/ec-cube#4098]
## 再現手順(Procedure)
商品登録画面で、販売価格を変更して登録。
右カラムの更新日が変わっていない。

### 環境 (environment)
+ EC-CUBE: 4.0.2

## 関連情報 (Ref)
#1671

**Comment by moritahiroo** [comment]
勘違いでした

**Comment by okazy** [comment]
規格なし商品の場合は商品情報の更新で更新日が更新されるが、規格あり商品の規格を更新しても商品自体の更新日は更新されない状況。

**Comment by kurozumi** [comment]
規格なし商品の場合でも価格のみ変更して更新すると更新日は更新されないようです。
商品名とかProductエンティティの項目を更新しないと更新日は更新されませんでした。

SaveEventSubscriber::preUpdateの見直しが必要そうです。

**Comment by chihiro-adachi** [comment]
#3639 での実装統一時に、誤って商品の更新日時の部分も削除されたようです。
3.0での実装に戻すように修正します。
