### ISSUE TITLE
納品書に表示されているロゴの変更をファイル管理から出来るようにする

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4105]
## 概要(Overview)
納品書ロゴの変更をファイル管理から出来るようにするために、画像パスをuser_data以下に変更。

▼現在のパス
html/template/admin/assets/pdf/logo.png

## 対応方法
・logoファイルをuser_dataに移動させる。
・納品書のロゴの読み込みパスを変更する。

## 対応参考
https://github.com/EC-CUBE/ec-cube/issues/4070

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by kazumiiiiiiiiiii** [comment]
こちら、対応いたしましたのでクローズいたします。
