### ISSUE TITLE
コンテンツ管理＞ページ管理＞のmeta記載例をそのまま利用できるようにする

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4108]
## 概要(Overview)
コンテンツ管理＞ページ管理＞のmeta記載例をそのまま利用できるようにする。
※現在はフォーム入力しようとプレースホルダーが消えてしまい活用が出来ない。

## 要望 (Requirement)
どこかにコピーボタンがあり、プレースホルダーの内容を使用して編集できる。

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
以下のプルリクにて商品詳細画面にあらかじめOGPタグが埋め込まれるようになりましたのでこちらクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4352
