### ISSUE TITLE
ファイル管理でアップした画像ファイルをサムネイルでわかる様にしたい

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4109]
## 概要(Overview)
現在、ファイル管理ではアップした画像ファイルのサムネイル画像が表示されないため、
アップファイル数が多くなった時に、画像の把握が難しくなる。

## 期待する内容(Expect)  or 要望 (Requirement)
拡張子が画像のものに関してはサムネイル画像を表示する。

**Comment by Yangsin** [comment]
Twitterでも同様に御意見をいただいておりました。添付画像がわかりやすかったのでこちらにも。
![image](https://user-images.githubusercontent.com/8196511/54814270-b7159980-4cd2-11e9-956e-ecb82f17141c.png)

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">eccube coのコンテンツ管理＞ファイル管理でサムネイルによる画像管理ができず、全て文字で判断しなければいけないのが少し手間で数日後に確認すると、この画像はなんだたっけ…ってことになりそう。商品一覧の画面ではサムネイルがしっかりの出るのでファイル管理部分もそうなれば嬉しいな… <a href="https://t.co/rrpurBqpD8">pic.twitter.com/rrpurBqpD8</a></p>&mdash; 農業法人 紀州梅香/Japan (@kishubaiko) <a href="https://twitter.com/kishubaiko/status/1109027034997506048?ref_src=twsrc%5Etfw">2019年3月22日</a></blockquote>

**Comment by chihiro-adachi** [comment]
#4122 で対応
