### ISSUE TITLE
ファイル管理でフォルダごと、または画像ファイルを一括でアップロードしたい

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4112]
## 解決したい課題
現在、ファイル管理ではフォルダを一つずつ作成したり、画像を一つずつアップしたりする必要があり、手間が発生している。

## 期待する内容(Expect)  or 要望 (Requirement)
フォルダ丸ごとアップや、複数画像をまとめてアップ出来るようにしたい。

**Comment by kazumiiiiiiiiiii** [comment]
#4235 をマージいたしました。
