### ISSUE TITLE
Composer 2.0 will error というエラーが出るケースが有る

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#4133]
## 概要(Overview)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&topic_id=21691&forum=11

これが原因？
https://github.com/mikey179/vfsStream/pull/174

**Comment by chihiro-adachi** [comment]
@nobuhiko 
はい、composer 2.0から大文字は使えなくなっているので、それでdeperecatedのワーニングがでるようになっています。
https://github.com/EC-CUBE/ec-cube/issues/4106

**Comment by nobuhiko** [comment]
@chihiro-adachi なるほど。プラグインインストールが失敗するケースとは関係なさそうですね
