### ISSUE TITLE
Entry/confirm.twigのフックポイント(TemplateEvent)が利用できない

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4136]
## 概要(Overview)
Entry/confirm.twigのフックポイント(TemplateEvent)をプラグインでgetSubscribedEventsに登録しても実行されない

@Templateアノテーションの場合はEccube\DependencyInjection\Compiler\TemplateListenerPassでEnvironmentが差し替えられているが、EntryController::index内のようにコードで$this->renderされている場合はTemplateEventが発火しない

```
 return $this->render(
                        'Entry/confirm.twig',
                        [
                            'form' => $form->createView(),
                        ]
                    );
```

## 期待する内容(Expect)  or 要望 (Requirement)
フックポイントが実行される

## 再現手順(Procedure)
プラグインでgetSubscribedEventsに登録
```    
/**
     * @return array
     */
    public static function getSubscribedEvents()
    {
        return [
            'Entry/confirm.twig' => 'onRenderEntryConfirm',
        ];
    }
```

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@dk-umebius 
$this->renderだとオリジナルのTwigEnvironmentが呼ばれるので、TemplateEventが聞いていないということですね。ありがとうございます。

**Comment by okazy** [comment]
以下のプルリクで修正されましたのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4362
