### ISSUE TITLE
出荷登録画面で商品を追加しても受注の合計金額が更新されない

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4137]
## 概要(Overview)
出荷登録画面で商品を追加しても合計金額が更新されない

## 再現手順(Procedure)
1. 受注登録（チェリーアイスサンドのみ）　合計金額は4,024円

2. 出荷登録画面で商品を追加して保存（彩のジェラートCUBE cube-06 / ( フレーバー： 抹茶 / サイズ： 16mm × 16mm )）　この時点で受注一覧などの合計金額は4,024円

3. 受注を開いて何も変更せずに保存　この時点で合計金額は41,284円に更新される

## 期待する内容(Expect)  or 要望 (Requirement)

「2. 出荷登録画面で商品を追加して保存」の時点で合計金額が更新される

### 環境 (environment)
EC-CUBE4 デモサイト

**Comment by chihiro-adachi** [comment]
@dk-umebius 
ありがとうございます、再現確認しました。

**Comment by chihiro-adachi** [comment]
#4283 で修正済のためクローズします。
