### ISSUE TITLE
管理画面の受注管理からお届け時間の指定を「指定なし」に変更できない

### ISSUE THREAD

**Issue by kifr** [EC-CUBE/ec-cube#4143]
## 概要(Overview)
管理画面の受注管理からお届け時間の指定を「指定なし」に変更できない

## 具体例(Example)
お届け時間に「指定なし」,「10-12」,「12-14」があると仮定。

「10-12」で受注し、その後管理画面から「指定なし」にして登録しても値が「NULL」にかわらず「10-12」のままとなってしまう。
「12-14」に切り替えた場合は正常に切り替わる(「指定なし」以外の値には正常に切り替わる)。

## 期待する内容(Expect)  or 要望 (Requirement)
受注管理にて「指定なし」で登録した場合DBの値がNULLに切り替わって欲しい。

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.2.17
+ DB: MySQL 5.7.23

**Comment by okazy** [comment]
#4145 で修正済みのためクローズします。
