### ISSUE TITLE
コアクラスのカスタマイズ、使い方、拡張の指針について

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#4151]
開発する時の指針としたいので、コアクラスはどのようカスタマイズ、使われることを
想定、推奨されているのか、お教えいただけないでしょうか？
私は以下のパターンを考えましたが、どれになりますでしょうか？他にもあればお願いします。

1. カスタマイズしたい場合は、コアクラスを直接修正することを推奨している。
2. Customize ディレクトリにクラスを設置し、処理を差し替える(継承ではなく)ことを推奨している。
3. Customize ディレクトリにクラスを設置し、継承して使われることを推奨している。
4. Event をフックして処理に介入する方法を推奨している。
5. new または forward(dispatch) で利用することを推奨している。(継承して利用されることは考慮していない)

**Comment by okazy** [comment]
頂いた意見のメモ程度ですが、一旦投稿します。

## 前提
上の項目から検討していく
1. プラグインで対応可能であればプラグインで対応
2. 拡張機構で対応可能であれば拡張機構で対応
3. 本体のコードを直接変更。ただしバージョン管理を強く推奨
ただし、1,2では時間がかかるが3では簡単に対応できる場合には3での対応も検討できる

## 出た意見

- しっかりバージョン管理して最新に追従していけるなら、本体のコードを直接編集される方法（1）の方がメリットが多い
- Customizeディレクトリでの処理の差し替え(2)、継承(3)は利用しやすい方を使うのがよい

**Comment by chihiro-adachi** [comment]
private methodに関する方針
https://github.com/EC-CUBE/ec-cube/pull/4141#issuecomment-507936692

**Comment by xuelian311** [comment]
本体の改善要望などではありませんので、一旦クローズいたします。
ご質問などはぜひ開発コミュニティをご利用くださいませ。
