### ISSUE TITLE
商品一覧画面、詳細画面でのURLkeyとcanonical URLの設定機能が欲しい

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#4162]
## 概要(Overview)
現状、標準では商品一覧画面と詳細画面ではそれぞれIDがURLに利用されているが、任意の文字列を指定できる様にしたい

### 例
```/products/detail/1``` -> ```/products/fork-01```
```/products/list?category_id=3``` -> ```/products/gelato/```

## 期待する内容(Expect)  or 要望 (Requirement)
従来のURLでもアクセスできるが、管理画面からcanonicalは指定できる様にしたい

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by kazumiiiiiiiiiii** [comment]
以下でも議論されています。
#2569

**Comment by tao-s** [comment]
@kazumiiiiiiiiiii おお！まだ生きてたんですね。懐かしい。
では、コレは重複してるのでクローズします。
