### ISSUE TITLE
商品用の画像を一括アップロードしたい

### ISSUE THREAD

**Issue by yosshieee** [EC-CUBE/ec-cube#4172]
## 概要(Overview)
商品一括登録時、 `①：/html/upload/save_image/` 上の画像を参照はできるが、
その画像を管理画面から、一括でアップロードできない。

### 実施したいこと
- 商品一括登録時、画像もまとめてアップロードしたい。
　（現状①の箇所の画像のみしか参照できないため、ファイル管理は使用できない
- （運用開始後含めて）同じ画像を複数商品で適用させたい
- 上記を行うために、ファイル名と画像が確認したい

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by shutta-** [comment]
関連しそうなIssueがあったので付けておきます。
#4110 #4112

**Comment by Yangsin** [comment]
重複するためクローズします。
