### ISSUE TITLE
Entityの拡張を伴うプラグインのアップデート実行時、システムエラーが発生する。

### ISSUE THREAD

**Issue by hiro-t59** [EC-CUBE/ec-cube#4173]
## 概要(Overview)
Entityの拡張を伴うプラグインのアップデート実行時、システムエラーが発生する。
ただし、アップデート自体は問題なく完了している。

## 期待する内容(Expect)  or 要望 (Requirement)
Entityの拡張を伴うプラグインのアップデート実行時、システムエラーが発生せず、
正常にアップデート完了する。

## 再現手順(Procedure)
1.Entityの拡張を伴うプラグインをアップデートする

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.1.21
+ DB:
  - MySQL 5.5.60-MariaDB

**Comment by hiro-t59** [comment]
再現時のログになります。

> [php7:error] [pid 22690] [client 203.167.42.19:52619] PHP Fatal error:  Cannot declare class Eccube\\Entity\\ProductClass, because the name is already in use in /home/web/eccube-4.0.2-mysql/app/proxy/entity/ProductClass.php on line 28, referer: https://eccube-4.0.2-mysql/test/store/plugin/api/upgrade/1/confirm

**Comment by nanasess** [comment]
`PHP Fatal error: Cannot declare class` は、プラグインのアップデートに係わらず、通常の有効/無効でも発生しています。
参考) https://github.com/EC-CUBE/ec-cube/pull/3412

通常の有効/無効では、ブラウザのリダイレクト後に該当の Fatal error が発生しているので、システムエラー画面になることはありません。
アップデート時の有効化では、 Ajax で随時レスポンスを受け取るため、 Fatal error を捕捉してしまい、システムエラー表示となってしまう模様です

**Comment by nanasess** [comment]
案としては、プラグインアップデート時、有効化まで自動で行わずに、以下のようにすることで回避可能と思われます。

1. 無効化→プラグインアップグレード→スキーマアップデート→プラグインアップデートを自動で行う
2. 有効化のリンク or ボタンを表示する
3. 2 をクリックして、通常の有効化と同様のプロセスで有効化する

**Comment by hiro-t59** [comment]
Fatalが出る原因として、
app/proxy/entity/　以下の読み込みと　src/Eccube/Entity/　の読み込みが同時に発生し、
同namespaceのクラスの重複が発生することによりエラーとなっている。

処理としては、プラグインを有効化（アップデート時の有効化を含む）する場合かつ、app/proxy/entity/以下のファイルが生成されていない場合、プロキシを生成して、キャッシュを削除する。

キャッシュが削除されたことにより、クラスローダの対象になるため、プロキシが読み込まれ、クラスの重複が発生し、Fatalが発生している。

なお、アップデートではない有効化を実行した場合、admin_store_pluginへリダイレクトを行った後にキャッシュの削除が実行されるため、ブラウザ側では検知しないが、Fatalは発生している。

**Comment by hiro-t59** [comment]
Fatalに対する根治対応が難しいことから、上記PRにて回避処理を実装しました。
操作性の変化としては以下となります。

・現状
　1.無効化→アップデート→有効化
　プラグインのアップデートボタン押下にて以下の処理が自動実行

・#4270での動作
　1.アップデートボタン押下 (無効化→アップデート)
　2.有効化ボタン押下 (有効化)
　プラグインのアップデートボタンでは有効化はされない為、プラグイン一覧から
有効化ボタン押下が必要

**Comment by hiro-t59** [comment]
また、回避案の懸念点としては以下となります。

・アップデートの一連の処理から有効化部分のみ切り出したので、プラグインの有効化忘れが発生する可能性がある。

その他懸念点やアイデア等あればご意見お願いします。

**Comment by okazy** [comment]
こちらの問題は #4728 にて修正されたかと思います。
#4270 で行っていただいた対応は不要になったかと思いますので Revert のプルリクを作成しました。
