### ISSUE TITLE
プラグインのインストールに失敗する

### ISSUE THREAD

**Issue by InoueYoshihisa** [EC-CUBE/ec-cube#4174]
## 概要(Overview)
    
　オーナーズストアから導入できるプラグイン全てでプラグイン導入時
   システムエラーが発生しましたエラー出て導入が止まる。
　
　ファイルアップロード機能からの手動インストールでは導入が可能。
    エラーログは下記に記載

![image](https://user-images.githubusercontent.com/12758470/58685815-e5d97b80-83b7-11e9-9b48-8147a03d6303.png)
`

admin.ERROR [mgsocqq9a33g23ub5omblun2hv] [0a84fca] [1] [Eccube\Log\Logger:log:64] - In JsonFile.php line 300: "https://package-api.ec-cube.net/packages.json" does not contain valid JSON   Parse error on line 1:  ^ Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [--ignore IGNORE] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]  [] [GET, /ecadmin/store/plugin/api/install/1723/confirm, 
admin.INFO [mgsocqq9a33g23ub5omblun2hv] [0a84fca] [1] [Eccube\Log\Logger:log:64] - {"command":"config","setting-key":"repositories.eccube","setting-value":["{\"type\":\"composer\",\"url\":\"https:\\/\\/package-api.ec-cube.net\",\"options\":{\"http\":{\"header\":[\"X-ECCUBE-KEY: ************************\"]}}}"],"--working-dir":"************/html","--no-ansi":true} [GET, /ecadmin/store/plugin/api/install/1723/confirm,
admin.INFO [mgsocqq9a33g23ub5omblun2hv] [0a84fca] [1] [Eccube\Log\Logger:log:64] - http get_info {"url":"https://package-api.ec-cube.net/plugin/1723","content_type":"application/json;charset=UTF-8","http_code":200,"header_size":413,"request_size":192,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":0.43831699999999996,"namelookup_time":0.001292,"connect_time":0.002124,"pretransfer_time":0.082419,"size_upload":0,"size_download":989,"speed_download":2256,"speed_upload":0,"download_content_length":-1,"upload_content_length":0,"starttransfer_time":0.438229,"redirect_time":0,"redirect_url":"","primary_ip":"133.242.233.183","certinfo":[],"message":""} [GET, /ecadmin/store/plugin/api/install/1723/confirm,

`

## 期待する内容(Expect)  or 要望 (Requirement)
　プラグインが導入できるようにしたい。

## 再現手順(Procedure)
 オーナーズストアからプラグインを導入しようとすると複数回繰り返しても再現
 新規インストールした別環境でも再現

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ サーバーOS:Linux ik1-403-33773.vs.sakura.ne.jp 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 14:52:26 UTC 2019 x86_64
+ PHP: 7.2.18 
　-  (Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gettext, iconv, intl, json, exif, mysqlnd, PDO, apcu, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, zip, Phar)
+ DB:
  - MySQL 5.5.64-MariaDB

**Comment by chihiro-adachi** [comment]
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22109&forum=16&post_id=92619#forumpost92619

**Comment by tao-s** [comment]
これ、xserverでも発生する様です。

**Comment by nanasess** [comment]
OOM Killer で PHP のプロセスが強制終了する問題だと思われますので、 Linux を使用している場合は該当してくると思います #4142

**Comment by tao-s** [comment]
@nanasess xserverで起きたのはsymfony/flexの問題でした。

>  "https://package-api.ec-cube.net/packages.json" does not contain valid JSON Parse error on line 1:

コレです。

**Comment by nanasess** [comment]
@tao-s なるほど、勘違いでした🙏

**Comment by xuelian311** [comment]
一部の環境起因の問題だったようですので、クローズいたします。
またお困りのことがございましたらぜひ開発コミュニティをご利用ください。
