### ISSUE TITLE
区分記載請求書等への対応

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#4182]
## 概要(Overview)

軽減税率の施行にあわせて、軽減税率対象の商品は画面上から把握可能なようにする

## 期待する内容(Expect)  or 要望 (Requirement)

区分記載請求書等として、請求書の代替として利用されそうな画面で軽減税率対象であることが明示される
• フロント:購入手続・確認画面、注文完了メール、注文履歴
• 管理画面:納品書

商品一覧・詳細・カート は区分記載請求書としては不要と判断

## 関連情報 (Ref)
フォーラムでの参考
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22020&forum=15
消費税・軽減税率情報Cafe
https://www.keigenzeiritsu.info/article/18455
https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/0018006-112.pdf

**Comment by chihiro-adachi** [comment]
区分請求書に対応した注文内容の表示です。
https://www.gov-online.go.jp/tokusyu/keigen_zeiritsu/jigyosya/kubunkisai.html

明細項目 |   |   |  
-- | -- | -- | --
  | 税込価格 | 個数 | 小計
チェリーアイス(※) | ¥3,024 | 2 | ¥6,048
おなべ | ¥1,000 | 1 | ¥1,000
※は軽減税率対象品目 |   |   |  


サマリ項目 |   |  
-- | -- | --
送料 | ¥1,000 |  
手数料 | 0 | ※値引き項目については、EC-CUBE標準では金券として扱うため合計配下に移動
合計 | ¥8,048 |  
8% | ¥6,048 | ※チェリーアイス税込み価格
10% | ¥2,000 | ※おなべ＋送料＋手数料
  |   |  
ポイント利用 | ¥-100 | ※従来値引きで扱っていた項目は金券として処理
クーポン利用 | ¥-500 | ※従来値引きで扱っていた項目は金券として処理
  |   |  
お支払い金額 | ¥7,448 |  

4.0.2からの変更点は以下の通り

- 総額表示に関する変更はなし
- 軽減税率対象品目については、※を商品名の後ろにつける
- 値引き項目
  - EC-CUBEのポイント・クーポンの標準機能では値引きとしては扱わない方針
  - 明示的に支払手段の代替として扱う #4274
- 合計金額は8%と10%で内訳を表示
  - 上記サンプルの場合、8%はチェリーアイスサンドの税込金額を表示
  - 10%はおなべ+送料＋手数料を表示
- ポイント・クーポンの金額
  - 従来では値引きであったが、金券として処理するため、支払い手段の代替として、合計金額から差し引く #4274

**Comment by chihiro-adachi** [comment]
以下のような画面イメージになります。
![image](https://user-images.githubusercontent.com/8196725/63558473-06b10780-c588-11e9-8c03-f49a8c9283d7.png)
