### ISSUE TITLE
軽減税率に合わせた対応のまとめ

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#4183]
## 概要(Overview)

軽減税率にあわせて対応すべき内容や強化したい点についての内容のまとめ

## 期待する内容(Expect) 

4.0.2の対応状況：
　1. 商品別に税率（％）、税区分（外税・内税）が設定可能、受注データとしても保持。
　2. カート・購入確認画面・マイページ購入履歴で明細毎の税率が確認可能
　3. 管理画面受注詳細で明細毎の税率が確認可能・編集はできない
　4. 税率を変更後に以前の受注明細を再計算すると、新しい税率で税額を再計算

4.0.3で対応を予定しているもの
　受注管理での税率・税額を受注時点のデータを元とし編集可能にする #4269  (対応状況の4を見直し）
　税率設定：商品CSVの入出力で、税率を登録できるようにする #1741
　区分記載請求書等への対応 #4182　

追加で期待されるもの
　外税での表示 #1067
　適格請求書(インボイス)の要件にそった税率計算の変更  #4268 

4.0.x では対応を見送るもの
　税率マスターによる管理： #2587

**Comment by nanasess** [comment]
外税表示の要望もよくあがるので貼っておきます
https://github.com/EC-CUBE/ec-cube/issues/1067

**Comment by chihiro-adachi** [comment]
軽減税率の対応方針・対応範囲についてドラフトを作成しました。
[軽減税率対応.pdf](https://github.com/EC-CUBE/ec-cube/files/3486460/default.pdf)

上記資料の前提としては、マイナーバージョンで対応できる範囲での改修となります。
対応範囲としては、
- #3732 での課題である、受注更新時に税額が登録されている税率で再計算されてしまう問題の解消
- 商品管理・受注管理での税関連項目の登録・出力
- 区分記載請求書・適格請求書(インボイス)への対応

を検討しています。

ご意見うかがえるとありがたいです。
こういう運用の際にどうなるの？等の質問でもかまいませんので、コメントよろしくおねがいします。

**Comment by nobuhiko** [comment]
- 商品CSVでの出力・登録
- 発送日時点での税率計算

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます。
商品csvは出力、登録共に対応予定です。

発送時点での税計算は今のところ考えてないですね。
基本的には以下のようなオペレーションになるかなと思っています。
https://www.keigenzeiritsu.info/article/18744

受注編集画面で税率変更はできたほうがよさそうです。

**Comment by nanasess** [comment]
区分記載請求書や適格請求書は仕入税額控除を受けるために必要な書類となります。
BtoCの場合など、課税業者ではない一般消費者に対して交付義務はありませんし、確認画面やメールを仕入税額控除を受けるために必要な書類の代替とするケースは少なそうな気がしています。(通常は別途正式な請求書を発行する)

厳密に制度に追従するより、基本は BtoC で利便性の高い仕様とし、必要に応じて柔軟にカスタマイズ可能なデータ構造としておくのが良いと思います

**Comment by xuelian311** [comment]
軽減税率対応は完了しているため、クローズいたします。
