### ISSUE TITLE
商品CSVアップロード時、商品説明(詳細)の値が約3000文字を超えるとシステムエラーになる

### ISSUE THREAD

**Issue by yosshieee** [EC-CUBE/ec-cube#4187]
## 概要(Overview)
商品CSV登録時、「商品説明(詳細)」に3000文字以上入れると、システムエラーが発生します。
3000文字前後なので、文字数でなくビット数によってエラーが発生している模様。

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.2.19 
+ DB:
  - PostgreSQL 10.6

**Comment by ryo-endo** [comment]
#4218 で対応済みのためIssueをCLOSEします。
フィードバックありがとうございました。
