### ISSUE TITLE
複数配送設定で商品追加時に消費税が設定されていない

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#4193]
## 概要(Overview)
管理画面の受注登録 -> 出荷情報の追加 -> 商品追加
で、操作した時に消費税が設定されていない。
なお、この状態で受注登録画面の「登録」ボタンを押すと、消費税が設定されました。
おそらく、出荷情報の商品追加・更新処理時に消費税計算のロジックが抜けているのだと思います。

## 期待する内容(Expect)  or 要望 (Requirement)
消費税が設定されるようにして欲しい。

### 環境 (environment)
+ EC-CUBE: 4.0.2

![eccube_bug](https://user-images.githubusercontent.com/22627978/59998175-bd346100-9699-11e9-89f3-293ca8589dbb.png)

**Comment by Yangsin** [comment]
修正PRがマージされましたので、4.0.3リリースにむけてIssueクローズします。
