### ISSUE TITLE
セキュリティ向上のための機能改善提案

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#4195]
# 概要(Overview)
昨今のカード情報漏洩事件の多発から、EC-CUBEももうちょっとセキュアな状態を強制した方が良いと思います。
EC-CUBEを使っているユーザは、必ずしもリテラシーが高いとは限らず、どちらかというと「無料だから使ってみよう」というWebアプリケーションのセキュリティとかあまり知らない人が多いと思います。
どれだけ注意喚起したとしても、そういった人たちには届かない事が多いので、危険な設定をシステム側でできなくしちゃった方が良いと思います。

## 期待する内容(Expect)  or 要望 (Requirement)

- SSL通信の強制（インストール時からSSL必須）
- デフォルトで管理画面URLをランダムな文字列に（ admin等良くある単語を含ませない ）
- デフォルトで管理画面のログインIDをランダムな文字列に（ admin等良くある単語を含ませない ）
- デフォルトで管理画面のログインパスワードをランダムな文字列に（password等簡単な文字列を許可しない）

**Comment by Yangsin** [comment]
ご意見ありがとうございます。
SSL通信を完全に強制すると、開発環境とかで面倒だったりしませんか。

**Comment by tao-s** [comment]
@Yangsin コマンドラインからインストールする際はhttpでもOKにするとかありますが、ローカルなら自己証明とか、フリーのssl証明書とかもありますし、それくらい準備できない人がいじるのは危ないんじゃないかな？と思います。

**Comment by xuelian311** [comment]
リリース時のセキュリティ面の注意事項に関しましては、セキュリティチェックリストを用いて確認可能となっているため、本issueはクローズいたします。またセキュリティチェックリストで対応しきれない注意事項などありましたら再度issueを立てていただけると幸いです。
