### ISSUE TITLE
Dockerfileを作成したい

### ISSUE THREAD

**Issue by kmurata08** [EC-CUBE/ec-cube#4200]
## 概要(Overview)
現在、PHP環境にEC-CUBEが動く環境構築を行なった上で開発をする流れだが、Dockerfileを作成することにより、dockerコマンド1発で開発環境が整うようにしたい。

## 期待する内容(Expect)  or 要望 (Requirement)
dockerコマンド、もしくはdocker-composeコマンドで環境が構築でき、EC-CUBEが乗っているローカル開発サーバーが立ち上がることにより、開発者がスムーズに環境構築を行うことができる。

### 環境 (environment)
+ EC-CUBE: 4
+ PHP: 7.2
+ DB:
  - PostgreSQLもしくはMySQL

**Comment by nanasess** [comment]
var 以下を VOLUME にマウントすると強烈に遅くなる問題がありますのでご注意ください。
(EC-CUBE に限らず Symfony の問題)
http://blog.michaelperrin.fr/2017/04/14/docker-for-mac-on-a-symfony-app/

個人的には、 DB は Docker で立ち上げて、ビルトインウェブサーバーで開発するのに落ち着いてます。

**Comment by nanasess** [comment]
@Canon11 #4204 で作成してみましたので、よろしければお試しください

**Comment by chihiro-adachi** [comment]
@Canon11 
#4204 マージしました。
試していただいて、何かあればまたissueかpr上げていただければ助かります。
