### ISSUE TITLE
カテゴリー編集フォームのイベントに渡す変数がおかしい

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4201]
## 概要(Overview)

カテゴリー編集フォームの登録完了時イベントにおいて、イベントに渡しているformが編集用フォームではなく、新規登録用フォームになっている
EccubeEvents::ADMIN_PRODUCT_CATEGORY_INDEX_COMPLETE

## 期待する内容(Expect)  or 要望 (Requirement)
プラグインなどから操作できるよう、イベントには該当の編集フォームが渡って来るべき

## 再現手順(Procedure)
カテゴリー編集フォーム

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by kazumiiiiiiiiiii** [comment]
こちら、マージされましたのでクローズします。
#4202
