### ISSUE TITLE
お気に入り画面の表示件数をデフォルトで12件にする

### ISSUE THREAD

**Issue by 60dage** [EC-CUBE/ec-cube#4206]
## 概要(Overview)

現状10件となっているが、デフォルトのPCテンプレート（デザイン）は４列表示のため、右下に空欄ができてしまい見た目が惜しい。

## 要望 (Requirement)

お気に入りページの表示件数をデフォルトで12件にしてはどうか？
16件、20件でも良い。

## 再現手順(Procedure)

お気に入り商品を10件以上登録。

<img width="596" alt="ScreenShot 2019-07-02 10 16 17" src="https://user-images.githubusercontent.com/14285777/60476041-fc276f80-9cb4-11e9-9ec1-42e2311cccef.png">

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by 3tiles** [comment]
ここの表示件数はeccube_search_pmaxで定義されていて、この設定値を使っているのは、マイページのお気に入り一覧とご注文履歴だけのようです。

ご注文履歴のデフォルト表示件数も変えてしまって問題ないのであれば、この設定値を10->12とかに変更するだけで済むんですが、別途お気に入り画面用の表示件数を定義して追加した方が良いんでしょうか。

このあたりってどう考えるのが良いんでしょうか。

**Comment by 60dage** [comment]
> ここの表示件数はeccube_search_pmaxで定義されていて、この設定値を使っているのは、マイページのお気に入り一覧とご注文履歴だけ

> ご注文履歴のデフォルト表示件数も変えてしまって問題ないのであれば、この設定値を10->12とかに変更するだけで済むんですが、別途お気に入り画面用の表示件数を定義して追加した方が良いんでしょうか。

なるほど、ご説明ありがとうございます。
いち利用者としては、現状のご注文履歴レイアウトは常に１カラム表示であり、お気に入りと違って件数による見栄え上の不都合が生じないため、気にしなくて良さそうに思っています。

**Comment by kazumiiiiiiiiiii** [comment]
@rokuzeudon さん、
いただいたご意見で問題ないため、マージさせていただきました。
ありがとうございました！
