### ISSUE TITLE
タグを追加した場合、登録商品が削除できない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4227]
## 概要(Overview)

開発コミュニティより
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22382&forum=9&post_id=93546#forumpost93546

## 期待する内容(Expect)  or 要望 (Requirement)

タグが登録されている商品を削除できるようにする。
商品画像の場合は、商品削除時にdtb_product_imageを削除するようになっており、挙動をあわせてもよいと思われる。

## 再現手順(Procedure)

1. 商品登録時、任意のタグを設定
1. 上記で登録した商品を削除する
1. 商品が削除できない

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
#4241 にて修正済み
