### ISSUE TITLE
[配送方法設定] お届け時間を並び替えることができない

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4228]
## 概要(Overview)
登録済みの配送方法で、お届け時間の順番を替えて保存しても、並び順が保持されず、並び替えることができない。
ドラッグ&ドロップも矢印での並び替えも同じ。

デモサイトでも「午後」と「午前」を並び替えられない。
https://site4.ec-cube.net/admin/setting/shop/delivery/1/edit

## 期待する内容(Expect)  or 要望 (Requirement)
お届け時間の順番を並びかえられ、注文画面や管理画面ではその並び順で表示される。

**Comment by chihiro-adachi** [comment]
#4229 で対応しました。
