### ISSUE TITLE
標準テンプレート カテゴリー名２行で縦位置が下寄り、３行目は表示されない

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4232]
## 概要(Overview)

カテゴリーブロック
標準テンプレート カテゴリー名２行で縦位置がおかしく３行目は表示されない

## 期待する内容(Expect)  or 要望 (Requirement)
標準テンプレートからあまりデザインを変えない場合も多いので
できればある程度の長さのカテゴリー名にも対応して欲しい。

現在は１０文字程度を超えると縦位置が真ん中ではなくなり、クライアントからは見た目の不具合とされてしまう。

![スクリーンショット 0031-07-20 11 57 37](https://user-images.githubusercontent.com/4304985/61573227-071c3580-aae6-11e9-8169-282018448bde.png)

**Comment by kazumiiiiiiiiiii** [comment]
@dk-umebius いつもありがとうございます。マージされましたので、クローズいたします。
