### ISSUE TITLE
ログインアタック対策機能(アカウントロック、ログイン回数制限、ログイン試行回数制限、スロットリング)

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4249]
## 概要(Overview)
ログイン画面にて、指定回数以上パスワードを間違えた場合はサイト全体に対してアクセス制限を実施する。

## 期待する内容(Expect)  or 要望 (Requirement)
管理画面より、指定回数・ロック時間の指定が可能とし、その値を設定する。
設定上限に引っかかった場合は、ロック状態になった画像を表示する。
※IPで制御を想定するが、それ以外に何か良い案あれば。
　IPに関してはホワイトリスト、ブラックリスト登録が出来ればより便利かも知れない。

**Comment by nanasess** [comment]
自前で頑張るより Google reCAPTCHA などと連携強化したほうが得策と思います

**Comment by Yangsin** [comment]
管理画面ログインへのセキュリティ強化が話題になることが増えており、4.2での対応を検討したいです。

**Comment by pineray** [comment]
私が公開しているプラグイン「連続○○で□□制限」の機能を移植するのはどうでしょうか？
https://www.ec-cube.net/products/detail.php?product_id=2342

- ログインフォーム送信時点から指定時間前までの間に、設定した回数以上ログインに失敗していると、アカウントをロックします。
- アカウントがロックされていると、正しいパスワードを入力していてもログインできません。
- 時間が経過し、時間内の失敗回数が設定値未満になれば自動的にロックが解除され、ログインできるようになります。
- ログインに成功することで失敗履歴はクリアされます。

閲覧制限ではなく、あくまでログインできなくするだけです。

**Comment by taguchimasahiro** [comment]
@pineray ご提案ありがとうございます。
IPアドレスは複数使い分けてくるbotもあるので、ご提案の仕様がよさそうに感じました。
プラグインはフロントのログインや問い合わせのようですが、管理画面にも同様に可能であればぜひ移植をお願いしたいです。本体へのPullRequestをいただけないでしょうか？4.2.0βリリース後ではありますが、セキュリティとして重要度も高く考えておりますので、4.2.0へ実装をしたいです。
ご検討よろしくお願いします。

**Comment by pineray** [comment]
私のプラグインではイベントで制限をかけているのですが、コアに移植する場合は firewall を使用する必要があるようです。
そこで実装方法を調べていたら、5.2以降の Symfony にはデフォルトでログイン試行回数を制限する機能が存在するようです。
https://symfony.com/doc/5.4/security.html#limiting-login-attempts
こちらを使用すれば、少なくともアクセス試行回数に関しては独自の実装を追加せずとも実現可能ではないでしょうか。

**Comment by chihiro-adachi** [comment]
@pineray 
ありがとうございます。こちらで確認しました。
手元で試してみたところ動作しました。修正も軽微に見えるのでこちらをSymfonyの機能を利用するでよいかと思います。
https://github.com/chihiro-adachi/ec-cube/commit/fceec2be783525db667dad1b6bfc14f203cabdb7

こちら利用した場合の影響範囲としては`AuthenticationEvents::AUTHENTICATION_FAILURE`が動作しなくなるようなので、そこだけ修正が必要そうです。
https://github.com/chihiro-adachi/ec-cube/commit/d573b3226b9a954d04511bd7cea814e6a2ceb356

**Comment by chihiro-adachi** [comment]
@pineray 
まずは以下の仕様で実装できればと思いますがいかがでしょうか。

- フロント・管理画面の両方で適用する(adminおよびcustomerのfirewallに適用)
- デフォルト値は以下の通り
  - max_attempts: 5
  - interval: '30 minutes'
- 設定値は~環境変数で~パラメータで変更可能なようにeccube.yamlに切り出し

**Comment by chihiro-adachi** [comment]
#5473 にて対応。
@pineray さんありがとうございます。

**Comment by chihiro-adachi** [comment]
仕様として補足です。

制限をかける仕様としては、Symfonyの機能に準じています。
デフォルト設定の場合、

- 同一のユーザIDでログインを試行する場合、5回失敗するとロック
- 異なるユーザIDでログインを試行する場合、25回失敗するとロック

のようにロックがかかります。 

詳細は以下をご確認ください。
https://symfony.com/doc/5.4/security.html#limiting-login-attempts
> By default, login attempts are limited on max_attempts (default: 5) failed requests for IP address + username and 5 * max_attempts failed requests for IP address. The second limit protects against an attacker using multiple usernames from bypassing the first limit, without disrupting normal users on big networks (such as offices).
