### ISSUE TITLE
商品CSV登録：必須項目のみのCSVを登録すると、任意項目がnullで更新される

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4250]
## 概要(Overview)

カテゴリ列がないCSVを登録するとカテゴリの紐付けが消える

カテゴリ以外では、以下がnullで更新される

- 商品説明(一覧)
- 商品説明(詳細)
- 検索ワード
- ショップ用メモ欄
- フリーエリア
- 商品コード

## 期待する内容(Expect)  or 要望 (Requirement)

任意項目で列がない場合は更新せず、スキップしてほしい。
2系からのデータ移行時に、必須列のみのCSVを作成しアップロードすると今回の事象に当たりました。

## 再現手順(Procedure)

- 商品CSVをダウンロード
- CSVのカテゴリ列を削除
- 商品CSV登録からCSVをアップロード
- カテゴリの紐付けが消える

### 環境 (environment)

+ EC-CUBE: 4.0.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by hiro-t59** [comment]
マージされたのでクローズします。
