### ISSUE TITLE
EC-CUBEインストール後の初期で税率10%に設定しておく

### ISSUE THREAD

**Issue by kazumiiiiiiiiiii** [EC-CUBE/ec-cube#4251]
## 概要(Overview)
EC-CUBE初期状態で2019/10/01から、税率10%に適用されるよう設定しておく必要があるかを決定したい。

## 期待する内容(Expect)  or 要望 (Requirement)
現状では、新規でインストールした際に10月以降も8%となるので対応を検討したい。
食品を扱っているサイトは基本税率8%で運用するところも多いと思うので、8%のままが良いかもしれない。

**Comment by nanasess** [comment]
2019/10/01 から自動的に適用されるのは、設定されていることがわかりづらく、不用意に税率変更される懸念もあるため反対です。

**Comment by chihiro-adachi** [comment]
> 食品を扱っているサイトは基本税率8%で運用するところも多いと思うので

送料や手数料の税額は基本税率で計算されるので、10%を追加しておかないと税額がちゃんと計算されないですね。

アップデート時にマイグレーションで自動適用するのは @nanasess さんの仰る通り避けたほうがよいかもしれないなと思いました。

**Comment by Yangsin** [comment]
10%になる2019年10月以前に初期値を変更することは余計な混乱になるため、4.0.3（2019年10月以前のリリース予定）では見送ります。

**Comment by okazy** [comment]
以下で修正されました。
https://github.com/EC-CUBE/ec-cube/pull/4479
4.0.4でリリース予定です。
