### ISSUE TITLE
管理画面からのマイグレーション機能について

### ISSUE THREAD

**Issue by asano-shinichi** [EC-CUBE/ec-cube#4256]
## 概要(Overview)
EC-CUBE3では、下記URLでマイグレーションが実施可能だったが、EC-CUBE4では実装されていない
```
http://インストール先/install.php/migration
```

## 期待する内容(Expect)  or 要望 (Requirement)
- EC-CUBE3と同様にブラウザアクセスでマイグレーションできること
- 下記、スキーマ更新も行えること
```
bin/console doctrine:schema:update --force --dump-sql
```

### 背景
クラウド環境やVPSであればコマンドでの反映が可能ですが、一般的なレンタルサーバではコマンド実行が不可なケースが多く、ブラウザからのマイグレーションが有用なため

## 再現手順(Procedure)
なし

### 環境 (environment)
+ EC-CUBE: 4.0.2

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
@asano-shinichi 
4.0からアップデートプラグインを提供するようになりました。プラグイン内でマイグレーションも実行されます。

https://github.com/EC-CUBE/eccube-update-plugin

こちらを利用するのは難しいでしょうか？

**Comment by asano-shinichi** [comment]
@chihiro-adachi 
プラグインの存在は認識していたのですが、内容を確認しておりませんでした...
まさにこちらのプラグイン機能で解決出来る内容でした！

ご教授頂きありがとうございました。
