### ISSUE TITLE
適格請求書(インボイス)の要件にそった税率計算の変更

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#4268]
## 概要(Overview)

適格請求書(インボイス)の要件である、税額の丸め計算は「税率毎に1回」に対応する

## 期待する内容(Expect)  or 要望 (Requirement)

4.0.2では、
「商品ｘ税率」で丸めて、税額計算が行われているため、厳密には適格請求書（インボイス）への対応が不十分となる
送料など税込みで計算されている明細についても、検討が必要。

### 環境 (environment)
+ EC-CUBE: 4.0.2

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/4183
https://www.nta.go.jp/publication/pamph/koho/kurashi/html/01_5.htm

**Comment by chihiro-adachi** [comment]
消費税の端数処理は、従来より1取引あたりで行うのが原則。また、積み上げ計算はあくまで経過措置であり、いくつかの要件が必要となる。
https://www.nta.go.jp/taxes/shiraberu/taxanswer/shohi/6391.htm

消費税の計算方式としては以下の2種

- 積み上げ計算：1取引あたりの税額を積み上げて集計
- 割戻し計算：課税売上(税込)から割り戻す

EC-CUBEの端数処理は商品単位で行っているため、現状でも積み上げ計算は採用できない。
税処理の上では、実際には、割戻し計算で行っている運用が多いのではないかと思われます。

適格請求書施行後も、割戻し方式が原則となり、EC-CUBEの端数処理を無理に変更する必要はなく、税率ごとに課税売上を集計できればよさそうです。

https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/qa/01-16.pdf

dtb_order_itemでは、税率および税込価格を保持しており、税率ごとの売上の集計は可能です。

| 名称           | 価格 | 税率 | 税額 | 税込価格 |
|----------------|------|------|------|----------|
| チェリーアイス | 1000 | 8%   | 80   | 1080     |
| ケーキ         | 100  | 8%   | 8    | 108      |
| おなべ         | 1000 | 10%  | 100  | 1100     |

合計：2,288
8%：1,188(税88)     `※税は1188*8/108で割戻して算出`
10%：1,100(税100)  `※税は1100*10/110で割り戻して算出`

※逆に割戻しが前提となるため、dtb_order_itemで保持している税額は税処理では使えないことになります。

**Comment by Yangsin** [comment]
4.0.3などマイナーで急ぎ対応する必要性はなく、4.1での割戻し計算について再検討するものとします。

**Comment by Yangsin** [comment]
適格請求書の運用が2023年に迫ってきているので4.2で再検討するためにマイルストーンを変更しました。

**Comment by nanasess** [comment]
記載事項及び端数処理の留意点(https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/0020006-027.pdf)
EC-CUBE4.1の納品書の記載事項に加え、登録番号及び **消費税額** の記載が必要
![image](https://user-images.githubusercontent.com/815715/171557921-ce3edd50-fce1-4a55-ba58-ffc017f1a99b.png)

![image](https://user-images.githubusercontent.com/815715/171557381-02c0c1c3-e016-4a87-9f33-8c1caf530c90.png)

値引の計算方法(https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/qa/01-09.pdf)
EC-CUBE4.1では、税込合計金額から値引きをしていた(税率ごとの合計金額は値引き前の価格)
適格請求書の要件では、**値引き後の合計金額から税率ごとの消費税額を算出する必要がある**
(ポイントやクーポン値引きに係る消費税額は税率ごとの価格の割合で按分する)
![image](https://user-images.githubusercontent.com/815715/171560002-41926c2b-38a3-48dd-b809-68186d17749f.png)

**Comment by nanasess** [comment]
適格請求書に対応した納品書の例です。赤字で記載した箇所が変更箇所となります。
![image](https://user-images.githubusercontent.com/815715/171573244-906903bc-16da-437f-9af5-5f3a226c9b6c.png)

- (追加)登録番号
- (変更)値引きは消費税額集計前に値引きする
- (変更)値引き後の税率ごとの小計、消費税額を記載する
- お客様が支払う金額に変更はありません
- 値引きの仕様変更があることから納品書の他、注文確認画面(フロント)、注文確認メール、注文編集画面も変更が必要

上記納品書の計算式の詳細は以下のようになります([Excel シートはこちら](https://skirnir-my.sharepoint.com/:x:/g/personal/ohkouchi_skirnir_dev/EaXsuVopveBDhN6V0TIcNAkBFHUFaSSuLjITmm4hHoWVjA?e=yxj4aN))
|商品|税率|数量|単価|税込単価(四捨五入)|金額(税込)|計算式|
|:----|:----|:----|:----|:----|:----|:----|
|チョコ|10%|4|71141|78255|313020| |
|抹茶|10%|4|92778|102056|408224| |
|バニラ|8%|4|15221|16439|65756| |
| | | | | | | |
| | | | |商品合計|787000| |
| | | | |送料(10%)|1000| |
| | | | |手数料(10%)|2187| |
| | | | | | | |
| | | | |合計|790187| |
| | | | |値引き|-7159| |
| | | | |請求金額|783028| |
| | | | | | | |
| | | | |10%対象小計|724431| |
| | | | |8%対象小計|65756| |
| | | | | | | |
| | | | |10%対象値引額|6563.258481|7159*724431/790187(値引額x10%対象小計÷合計)|
| | | | |8%対象値引額|595.7415194|7159*65756/790187(値引額x8%対象小計÷合計)|
| | | | | | | |
| | | | |10%対象値引後合計|¥717,868|724431-6563.258481(10%対象小計-10%対象値引額で四捨五入)|
| | | | |8%対象値引後合計|¥65,160|65756-595.7415194(8%対象小計-10%対象値引額で四捨五入)|
| | | | | | | |
| | | | |10%対象消費税(四捨五入)|¥65,261|724431-6563.258481*(10/110)(10%対象小計-10%対象値引額x(10/110)で四捨五入)|
| | | | |8%対象消費税(四捨五入)|¥4,827|65756-595.7415194*(8/108)(8%対象小計-8%対象値引額x(8/108)で四捨五入)|

**Comment by yt1969** [comment]
最後の消費税計算の割返しですけど、税率ごと値引き後の税込み金額から税額を求めるんですよね。それぞれ*(10/110), *(8/108)では？
(上の方はそうなってますね、Excelシートのあたりで)

**Comment by nanasess** [comment]
@yt1969 ご指摘ありがとうございます。おっしゃる通りでございました。修正しました。お恥ずかしい🙇‍♂️

**Comment by chihiro-adachi** [comment]
#5382 で対応しました。
