### ISSUE TITLE
削除済の商品規格をCSVで新規登録できない

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4282]
## 概要(Overview)

削除済の商品規格をCSVで新規登録できない
他のCSV登録については未確認

## 期待する内容(Expect)  or 要望 (Requirement)

商品CSV登録で `visible` の制御をできるようにする

## 再現手順(Procedure)

1. `チョコ / 16mm × 16mm` の商品規格を登録
2. 管理画面から `チョコ / 16mm × 16mm` の商品規格を削除
3. CSVにて `チョコ / 16mm × 16mm` の商品規格を新規登録

2の操作で `dtb_product_class` の `visible` が `false` となる（論理削除）
3の商品CSVでの登録ではレコードは更新されるが、 `visible` が `true` とならず、実質登録ができない

### 環境 (environment)
+ EC-CUBE: 4.0.4

## 関連情報 (Ref)

#4190

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5875 で対応しました
