### ISSUE TITLE
受注登録で利用ポイントを空欄にして登録した場合、システムエラーとなる

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/ec-cube#4289]
## 概要(Overview)

管理画面で受注登録時に、利用ポイントを空白で登録するとシステムエラーとなる。

## 期待する内容(Expect)  or 要望 (Requirement)

空欄で登録した場合、エラーメッセージを返却する。
または、0で登録する。

## 再現手順(Procedure)

1. 受注登録画面で必須の項目を入力する。
1. 商品情報の利用ポイント欄を空白にする（デフォルトは0）
1. 登録ボタンを押下する

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.2.9
+ DB:
  - MySQL 5.7.27

**Comment by okazy** [comment]
以下のプルリクで解決したのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4423
