### ISSUE TITLE
商品の個別税率が効かない

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4292]
## 概要(Overview)
「彩のジェラートCUBE」商品の個別税率が効かない

## 期待する内容(Expect)  or 要望 (Requirement)
dtb_product_class.id = 0 のレコードが存在している。

product_class_id が 0　の場合に個別税率の判定で弾かれてしまう。
src/Eccube/Repository/TaxRuleRepository.php（188行目）
if ($ProductClass && $productClassId > 0) {

デフォルトの商品を上書き更新して実際に販売する商品を登録している場合があるため、対応は必要。

## 再現手順(Procedure)
「彩のジェラートCUBE」に個別税率を設定する。

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by chihiro-adachi** [comment]
@hironori-tanaka ありがとうございます。
すみません、`個別税率が効かない`というのはどんな事象が発生していますでしょうか？

**Comment by chihiro-adachi** [comment]
#4294 で対応しました。

**Comment by hironori-tanaka** [comment]
ご対応ありがとうございます。
