### ISSUE TITLE
複数の販売種別がある場合、複数配送時に商品が変わってしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4293]
## 概要(Overview)

デモサイト (https://site4.ec-cube.net/admin/) でも確認したのですが、複数配送を行う箇所でバグを発見いたしました。

【現象】
カートページにて「複数の販売種別商品がある状態」で下にあるものを先に購入しようとした場合、
お届け先の編集を行った後にページに戻ると、上にあった販売種別商品に変わっています。

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22674&forum=8&post_id=94363#forumpost94363

## 期待する内容(Expect)  or 要望 (Requirement)

お届け先の編集後、下の販売種別の商品が購入できる

## 再現手順(Procedure)

（例：販売種別Aと販売種別B）
01：「販売種別A」と「販売種別B」があり、カートに入れたときの状況は下記になります。
　　-----
　　「販売種別B」の商品×2個
　　「販売種別A」の商品×2個
　　-----

　　同時に購入ができないので、「販売種別A」を先に購入するために購入フローへ進む
02：配送情報で、お届け先を追加する
03：お届け先を複数指定して、カートへと戻る
04：配送情報にて、「販売種別B」の商品が選択されている。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
4.0.4時点でこちらの問題は解決されていませんでした。

**Comment by dk-umebius** [comment]
4.0.5 でも再現するようです。
関連：https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=25036&forum=8

複数配送のカートの個数を更新する処理で、getPersistedCartsで取得したカートの順番そのままセッションにカートキーが保存されるためのようですね。
https://github.com/EC-CUBE/ec-cube/blob/4.0.5/src/Eccube/Service/CartService.php#L172

**Comment by okazy** [comment]
ありがとうございます！
#4906 で修正していただきましたのでクローズします。
