### ISSUE TITLE
ご注文内容のご確認画面で課税対象の値引き項目が消えてしまう

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/ec-cube#4303]
## 概要(Overview)

クーポンプラグイン等で課税対象の値引きを商品購入時に適用し、
ご注文手続き画面からご注文内容のご確認画面に遷移した時、
ご注文手続き画面で表示されていた値引きの項目が
ご注文内容のご確認画面では消えてしまう。

<img width="370" alt="スクリーンショット 2019-08-30 11 43 42" src="https://user-images.githubusercontent.com/26207848/63989497-7b052100-cb1b-11e9-9a14-d5954c0bb664.png">

## 期待する内容(Expect)  or 要望 (Requirement)

ご注文内容のご確認画面の購入金額詳細表示が、ご注文手続き画面と同様の表示となること

## 再現手順(Procedure)

1. クーポンプラグインで1000円引きのクーポンを登録
1. 適当な商品をカートに入れ、購入手続き画面に遷移
1. 登録したクーポンを適用
1. 購入手続き画面で値引き額が-￥1,000となっていることを確認
1. ご注文内容のご確認画面に遷移
1. 値引きの項目が消えていることを確認

### 環境 (environment)
+ EC-CUBE: dev/reduced_tax_rate　ブランチ
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/4302/commits/2718fe3723e62d6e8a149ff4acc4d5b1733e4ed7 で修正しました。
