### ISSUE TITLE
軽減税率対象でない商品の購入時でも「※ は軽減税率対象商品です。」と表示される

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/ec-cube#4304]
## 概要(Overview)

軽減税率対応で軽減税率対象商品に※印が表示されるようになるが、
対象商品を購入しない場合にも「※ は軽減税率対象商品です。」と表示されてしまう。
※印の注記はあるが、対象の※がない状態となっている。

### 対象範囲

- ご注文手続き画面
- ご注文内容のご確認画面
- マイページの注文履歴画面
- 購入完了時のメール

## 期待する内容(Expect)  or 要望 (Requirement)

軽減税率対象の商品を購入する時のみ、「※ は軽減税率対象商品です。」
と表記するようにする

## 再現手順(Procedure)

軽減税率対象ではない商品を購入する

### 環境 (environment)
+ EC-CUBE: dev/reduced_tax_rate　ブランチ
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
以下のプルリクで修正されましたのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4438
