### ISSUE TITLE
対応状況(受注ステータス)を追加すると、会員編集画面でエラーになる

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#4306]
## 概要(Overview)

対応状況(受注ステータス)を追加すると、管理画面の会員編集画面でエラーになる。
原因は、対応状況の表示の色分けがハードコーディングされているため。

## 期待する内容(Expect)  or 要望 (Requirement)

表示の色分けは mtb_order_status_color を使用するように変更する。

### 環境 (environment)
+ EC-CUBE: 4.0.2

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/blob/d5d6e105457b62c301a8993c7d9b1ed8b4390488/src/Eccube/Resource/template/admin/Customer/edit.twig#L422

エラーが発生する該当行を以下のように修正し、エラーを回避することはできた。
{{ attribute(cssClassStatus, Order.OrderStatus.id) is defined ? attribute(cssClassStatus, Order.OrderStatus.id) : 'badge-ec-glay' }}

**Comment by okazy** [comment]
以下で修正されました。
https://github.com/EC-CUBE/ec-cube/pull/4437
