### ISSUE TITLE
マスタデータ管理でmtb_order_statusの追加・更新ができない

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#4307]
## 概要(Overview)

マスタデータ管理でmtb_order_statusへデータの追加・更新ができず、画面に「保存に失敗しました」と表示される。

## 期待する内容(Expect)  or 要望 (Requirement)

追加・更新できるようにしてほしい。

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by chihiro-adachi** [comment]
@sw-satoshi-nakano 
以下のPRで修正していますので、よろしければご確認お願いいたします。
https://github.com/EC-CUBE/ec-cube/pull/4221

ただ、ステータスは追加できますが、受注画面で利用するには設定ファイルでステータス遷移を定義する必要があります。

#4299

**Comment by sw-satoshi-nakano** [comment]
4.0.3 パッケージ版で追加・更新・削除ができることを確認しました。
ありがとうございます。

**Comment by chihiro-adachi** [comment]
ご確認ありがとうございます。
こちらのissueはクローズさせていただきます。
