### ISSUE TITLE
4.0.4リリース計画

### ISSUE THREAD

**Issue by hiro-t59** [EC-CUBE/ec-cube#4312]
## 基本方針
マイナーバージョンとして以下の方針で開発を行います。

- 不具合改修および機能改善を行う。
- 既存プラグイン/デザインテンプレートとの互換性を最大限考慮する。

## 開発スケジュール

- 2020/6/10 RC版パッケージ公開
- 2020/6/17 4.0.4リリース

## 主要な対応内容

- PHP7.4への対応
- Google Chrome の SameSiteCookie ポリシー変更対応

※EC-CUBE4.0.4で取り込む予定の改修一覧
https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+milestone%3A4.0.4+is%3Aclosed+base%3A4.0+is%3Amerged

### その他 

 Issueのマイルストーンの設定は現時点での予定であり、変更となる可能性があります。
- 積極的に対応を予定しているものを [4.0.4](https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.4) としてマイルストーン設定しています。
 - ソース凍結以前にPull Request があれば取り込みたいものを [4.0.x](https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.x)としてマイルストーン設定しています。

- Pull Request 未経験の方もぜひ開発にご協力ください。修正が容易と思われるものや、仕様が明確なものには、<a class="d-inline-block IssueLabel v-align-text-top" style="background-color: #5ae833; color: #000000" title="簡単に修正できそうなもの" href="/EC-CUBE/ec-cube/issues?q=is%3Aissue+is%3Aopen+label%3AEasy">🏷 Easyラベル</a>をつけています。

## 互換性についての情報

マイナーバージョンの開発では互換性を維持するために、以下の観点でPullRequestをレビューしています。

#### 既存機能の仕様変更
[`affected:外部仕様` ラベル](https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Aaffected%3A%E5%A4%96%E9%83%A8%E4%BB%95%E6%A7%98+is%3Aclosed+milestone%3A4.0.4+is%3Amerged)をご確認ください

#### フックポイントの呼び出しタイミングの変更
変更はありません

#### フックポイントのパラメータの削除・データ型の変更
変更はありません

#### twigファイルに渡しているパラメータの削除・データ型の変更
変更はありません

#### Serviceクラスの公開関数の、引数の削除・データ型の変更
変更はありません

#### 入出力ファイル(CSVなど)のフォーマット変更
変更はありません

**Comment by okazy** [comment]
4.0.4リリースに向けた残課題を洗い出しました。

## 4.0.4リリースに向けた課題

- [x] SameSite Cookie対応
- [x] PHP7.4のサポート
- [x] 不具合修正
- [x] 自動テスト
- [x] 結合テスト
- [x] セキュリティテスト
- [x] アップデートテスト

### SameSite Cookie対応

Google ChromeのSameSiteについての仕様変更で、決済でエラーとなる場合がある。
https://github.com/EC-CUBE/ec-cube/issues/4457

#### 残課題

- [x] [SameSite cookie 対応](https://github.com/EC-CUBE/ec-cube/pull/4519)
- [x] ドキュメントの整備

### PHP7.4のサポート

EC-CUBE 4.0.3 では PHP7.1 ~ 7.3 をサポートしている。
最新版のPHP7.4を新規サポートをする。
PHP7.1のセキュリティサポートが 2019/12 に終了しているが、4.0.4では引き続きサポートする。
https://www.php.net/supported-versions.php

開発中のAPIのシステム要件は7.2以上となる。

#### 残課題

- [x] [PHP7.4のサポート](https://github.com/EC-CUBE/ec-cube/pull/4414)

### 不具合修正

High, Critical およびそれに準ずるの不具合の対応

#### 残課題

- [x] [デバッグツールの不具合](https://github.com/EC-CUBE/ec-cube/pull/4530)
- [x] [eccube:composer:require-already-installedコマンドで404エラーが発生するのを修正](https://github.com/EC-CUBE/ec-cube/pull/4483)
- [x] 対象の洗い出し

### 自動テスト

UnitテストとE2Eテストを全て通す必要がある。
TravisCIでUnitテストは実行しているが、E2Eテストは実行できていない。
UnitテストとE2Eテストの両方実行できているGitHub Actionsが通れば要件は満たせる。

#### 残課題

- [x] Unitテスト(GitHub Actions)
- [x] E2Eテスト(GitHub Actions)
- [x] 公式プラグインのUnitテスト(TravisCI)

### 結合テスト

パッケージ版にて正常系と今回の主要な変更箇所のテストを実施する。

#### 残課題

- [x] 正常系の手動テスト（商品登録、購入、出荷手続き）
- [x] 公式プラグインの手動テスト
- [x] 決済プラグインの手動テスト（リンク型、トークン型）
- [x] SameSite Cookie対応
- [x] Template Eventテスト
- [x] 試験内容は精査が必要

### セキュリティテスト

セキュリティ診断ソフトでのテストを実施

#### 残課題

- [x] AppScanの実施

### アップデートテスト

4.0.3から4.0.4へのアップデートのテストを実施

#### 残課題

- [x] バージョンアップドキュメントの作成・テスト
- [x] アップデートプラグインの作成・テスト

**Comment by okazy** [comment]
4.0.4がリリースされましたのでこちらのIssueはクローズします。
https://github.com/EC-CUBE/ec-cube/releases/tag/4.0.4
ご協力ありがとうございました。
