### ISSUE TITLE
納品書PDFに店舗の都道府県がない

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4313]
## 概要(Overview)
納品書PDFの店舗情報に都道府県が出力されない

## 期待する内容(Expect)  or 要望 (Requirement)
受注管理で納品書PDFを出力したときに、店舗情報の住所1,2の前に都道府県を出力してほしい。

## 再現手順(Procedure)
受注管理で納品書を出力する。

### 環境 (environment)
+ EC-CUBE: 4.0.3

**Comment by chihiro-adachi** [comment]
#4322 で対応しました。
