### ISSUE TITLE
「保存して移動する」ボタンを複数回クリックで多重登録される

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4315]
## 概要(Overview)

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22748&forum=9&post_id=94547#forumpost94547

管理画面の登録更新系画面で別ページに遷移するボタンを押下した際に表示される「保存して移動する」ボタンですが、複数回クリックするとクリックした回数分処理がはしってしまう。

その影響でシステムエラーとなることがあります。
商品登録画面にて下記事象は確認しました。

・既存商品の編集時、商品画像を変更した後「保存して移動する」をダブルクリックするとシステムエラーとなり、商品カテゴリとの紐付けが外れる

・商品新規登録時に「保存して移動する」をダブルクリックするとシステムエラーとなり、中途半端な重複データが作成される

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
#4472 で修正されましたのでクローズします。
