### ISSUE TITLE
環境構築後CLIから環境を再構築すると管理画面URLがadminに固定される

### ISSUE THREAD

**Issue by tokidrill** [EC-CUBE/ec-cube#4316]
## 概要(Overview)
現在、ブラウザからのインストールでは管理画面のURLにadminを利用することができない仕様になっているようですが、
構築後に `bin/console eccube:install` のコマンドから再構築すると管理画面のURLが一律でadminに設定されます。

bagかenhancementか微妙なところですが、一瞬戸惑ったので報告です。

## 期待する内容(Expect)  or 要望 (Requirement)
上記コマンドでは初回構築時の各種設定が.envに排出され対話シェルのdefault値として読み取られるようですので、ブラウザ版インストール処理で設定できる管理画面のURL設定もCLIから設定およびdefault値の読み取りが可能となるのがあるべき姿かと考えています。

## 再現手順(Procedure)
1. ブラウザ版から管理画面URLを `admin` 以外の文字列で構築(ex: "hogepiyo")
2. CLI `bin/console eccube:install` コマンドから環境を再構築

もともと `https://example.com/hogepiyo` でアクセスできていた管理画面のURLが`https://example.com/admin` になることを確認。

**Comment by tokidrill** [comment]
追記：あくまで個人的な意見ですが、開発用途では管理画面URLをadminに設定できるようにしておいた方が便利かなとは思っています。

**Comment by chihiro-adachi** [comment]
CLIはあくまで開発用途で作成したツールなので、Webインストーラの挙動を完全に追従できているわけではないです。

envの値を読んで、設定されていればその値を利用するのはよいかもしれないですね。

**Comment by okazy** [comment]
以下で修正されました。
https://github.com/EC-CUBE/ec-cube/pull/4439
