### ISSUE TITLE
コンテンツ管理 > ページ管理 から追加したtwigへのTemplateEventについて

### ISSUE THREAD

**Issue by aaa70** [EC-CUBE/ec-cube#4329]
## 概要(Overview)

コンテンツ管理 > ページ管理 から追加したtwigに対してTemplateEventを発生させたい

## 要望 (Requirement)

たとえば user_data/test.twig にもプラグインからイベントを発生させたい。またなぜイベントが発生しないのかを知りたい。

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.2.22
+ DB:
  - sqlite 3.11.0

## 関連情報 (Ref)

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22658&forum=17

**Comment by chihiro-adachi** [comment]
@aaa707 
現状では、$this->render()でtwigテンプレートを出力している箇所では動作しなかったかと思います。
コントローラで、`@Template('xxx/xxx.twig')`のように、`@Template`アノテーションで指定されているtwigファイルのみが対象になります。

ちなみに、どんな処理を追加したい感じでしょうか？
代替案があるかもしれないので、教えてもらえるとありがたいです。

**Comment by aaa70** [comment]
@chihiro-adachi 
回答ありがとうございます。

私は現在、プラグインを開発しております。
そのプラグインはページの遷移などをトラッキングする目的で作成しているため、全ページを対象に javascript を出力する必要があります。

ユーザーが作成した画面(twig)でなければ src/Eccube/Resource/template/default 以下にある twig を対象に getSubscribedEvents しておいて
render 時に一度だけ $event->addAsset が呼ばれるようにすればいいかと思っていたのですが、ユーザーの追加したページでは、そもそも TemplateEvent が発生せずお手上げ状態でした。

ユーザーが追加した twig でも javascript を挿入するいい方法はありますでしょうか。
よろしくお願いいたします。

**Comment by chihiro-adachi** [comment]
@aaa707 
ありがとうございます。
全ページ対象であれば、ブロックを追加するほうが楽かもしれません。

ブロックを追加しているサンプルとしては、おすすめ商品ブロックがありますのでご参考まで。
https://github.com/EC-CUBE/Recommend-plugin/blob/4.0/PluginManager.php

**Comment by aaa70** [comment]
@chihiro-adachi 
ありがとうございます。
ブロック見てみたいと思います。

ちなみに、全ページ共通のタグではないのですが、ブロックはページによって動的に値を変更するような仕組みはあるのでしょうか。

**Comment by chihiro-adachi** [comment]
@aaa707 

> ちなみに、全ページ共通のタグではないのですが、ブロックはページによって動的に値を変更するような仕組みはあるのでしょうか。

特に用意はしていないので、ルーティングやURLで判断することになるかと思います。

**Comment by aaa70** [comment]
@chihiro-adachi 
回答ありがとうございました。
ブロック使ってみたいと思います。
