### ISSUE TITLE
商品別税率が適用されないケースがある(4系/3系)

### ISSUE THREAD

**Issue by apple-x-co** [EC-CUBE/ec-cube#4330]
## 概要(Overview)

TaxRule を 適用日降順 で取得し、1件目を採用（ `source/src/Eccube/Repository/TaxRuleRepository.php` ）しているので
税率設定の適用時期 と 商品別の消費税 を登録するタイミングによっては
商品別の消費税が適用されなくなる。

## 期待する内容(Expect)  or 要望 (Requirement)

商品別の消費税があれば、優先する。

## 再現手順(Procedure)

1. `設定 > 店舗設定 > 税率設定` に新しいレコードを追加する。（適用日を明日、税率を10%）
2. `設定 > 店舗設定 > 基本` の 「設定商品別税率機能」を有効にする
3. 商品の「税率」に「8」を設定する

**翌日**

* 上記3番で設定した商品が「税率10%の価格」で表示されている
* 上記3番とは別の商品の「税率」に「8」を設定すると、「税率8%の価格」で表示されている

**dtb_tax_rule**

| id | product_class_id | creator_id | country_id | pref_id | product_id | rounding_type_id | tax_rate | tax_adjust | apply_date          | create_date         | update_date         | discriminator_type |
|----|------------------|------------|------------|---------|------------|------------------|----------|------------|---------------------|---------------------|---------------------|--------------------|
|  1 |                  |            |            |         |            |                1 |        8 |          0 | 2017-03-07 10:14:52 | 2017-03-07 10:14:52 | 2017-03-07 10:14:52 | taxrule            |
|  2 |                  |          2 |            |         |            |                1 |       10 |          0 | 2019-09-17 15:00:00 | 2019-09-16 23:35:23 | 2019-09-16 23:37:37 | taxrule            |
|  3 |               30 |          2 |            |         |         22 |                1 |        8 |          0 | 2019-09-17 01:30:02 | 2019-09-17 01:30:02 | 2019-09-17 01:30:02 | taxrule            |
|  4 |               29 |          2 |            |         |         21 |                1 |        8 |          0 | 2019-09-17 01:30:02 | 2019-09-17 01:30:02 | 2019-09-17 01:30:02 | taxrule            |

### 環境 (environment)

+ EC-CUBE: 4.0.1
+ PHP: 7.2

**Comment by chihiro-adachi** [comment]
@apple-x-co 
ありがとうございます。こちらでも再現確認しました。

**Comment by apple-x-co** [comment]
@chihiro-adachi  ご確認ありがとうございます。

これはつまり、10月1日の10%対応を事前に行う場合に、遭遇してしまう問題かと思います。

暫定対応はどうしたらよろしいでしょうか。

私の方で考えているのは、商品別の消費税の `apply_date` が 登録日時で登録されてしまうのが問題なので、暫定対応としては、管理画面で商品別の消費税を登録した後に、 `apply_date` を 10月1日1秒 とかで、データベースを更新すれば取得できると考えたのですが、他にありましたら教えてください。

**Comment by chihiro-adachi** [comment]
@apple-x-co 
暫定対応としては、おっしゃる通りで、apply_dateを標準税率より先の日付にしてもらうしかないですね。

不具合の修正は、ある程度あたりはついたので、可能なかぎり早急に対応できればとおもっています。

**Comment by apple-x-co** [comment]
@chihiro-adachi 
かしこまりました。
ただ、この方法は、技術者でないと厳しいですね…

**Comment by chihiro-adachi** [comment]
TaxProcessor.phpで、$taxRuleRepository経由でTaxRuleを取得している箇所を、https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php#L96

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Service/TaxRuleService.php#L60

のように、ProductClassから直接取得するようにすれば解消できそうです。

**Comment by ryo-endo** [comment]
3系でも同様の問題があることを確認しました。

## 3系の場合の回避方法
3系の場合は以下2つの対応を行うことで回避可能。
- #4310 の修正を適用。
- apply_dateを標準税率より先の日付にする。

**Comment by okazy** [comment]
#4331 で修正されましたのでクローズします。
