### ISSUE TITLE
プラグインを探す画面で価格が低い順にソートすると価格が高い順で表示される

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/ec-cube#4335]
## 概要(Overview)
管理画面 > オーナーズストア > プラグインを探す
画面に遷移し、画面右上のプルダウンで価格が低い順でソートした場合、価格が高い順にソートされて表示されてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)
価格が低い順で表示されること。

## 再現手順(Procedure)
1. プラグインを探す画面に遷移。
1. プルダウンで価格が低い順を設定。
1. 下記画像の様になる。

<img width="1582" alt="スクリーンショット_2019-09-27_9_13_17" src="https://user-images.githubusercontent.com/26207848/65733114-1b913580-e108-11e9-976f-3a77371ca3b0.png">

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.2.8
+ DB:
  - MySQL 5.7.27

**Comment by m-pyon23** [comment]
本体ではなく、EC-CUBE Package API サーバ  `package-api.ec-cube.net` 側の実装に誤りがあると思わます。

オーナーズストアの検索結果は、以下のようなクエリを発行して取得した結果をそのまま表示していることを確認しました。

```
https://package-api.ec-cube.net/plugins?price_type=all&sort=price&page=1&per_page=10
```

APIサーバ側の対応が必要と思われます。

**Comment by m-pyon23** [comment]
一応、 https://www.ec-cube.net/ のストアでも価格が高い順になる挙動となっていることを確認しました。(そもそもストア側も表記が"価格順" なので、高い順/低い順のどちらか明記されてもいませんが…)

![image](https://user-images.githubusercontent.com/13373597/72665303-671a7700-3a4a-11ea-95f6-c83ecd1e8904.png)

**Comment by kiy0taka** [comment]
Package APIは管理画面に「価格の低い順」とあるので表示通り低い順で表示されるように対応しました。
ストアの方は現状のままとしています。
