### ISSUE TITLE
CSVのダウンロードで一定以上のレコード数を越えるとダウンロードされない

### ISSUE THREAD

**Issue by kazumiiiiiiiiiii** [EC-CUBE/ec-cube#4336]
## 概要(Overview)
CSVのダウンロードで一定以上のレコード数を越えるとダウンロードされない

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22794&forum=9&post_id=94683#forumpost94683

## 期待する内容(Expect)  or 要望 (Requirement)
CSVのダウンロードで一定以上のレコード数を越えてもダウンロードされるようにしたい

### 環境 (environment)
+ EC-CUBE: 4

**Comment by chihiro-adachi** [comment]
#4815 で対応しました
