### ISSUE TITLE
カートに追加した商品の数量をマイナスにできてしまう

### ISSUE THREAD

**Issue by yoshiaki-natsume** [EC-CUBE/ec-cube#4338]
## 概要(Overview)
サーバーサイドでの個数のup/downがバリデーションがないので、UIで防いでる個数変更処理をいじることで、マイナスの個数を指定できてしまう。
また複数商品をカートに入れている場合、マイナス分の価格が合計値から引かれて購入できてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)
UIだけでなくサーバー側でも個数のバリデーションをマイナスも想定して行うようにしたい。

## 再現手順(Procedure)
- 独自で実装したカート画面で増減ボタンクリック時のUIブロッキング処理を入れてない場合
- カートページでconsoleを開きマイナスボタンをclick連打するjsを実行する

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9
+ DB:
  - MySQL 5.7.x

## 関連情報 (Ref)

- [実際のup/downの処理](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Controller/CartController.php#L212-L222)
    - ここでは単純な増減しかしてないので数量がマイナスになりうる
- [PurchaseFlowのバリデーション処理](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Service/PurchaseFlow/Processor/EmptyItemsValidator.php#L49)
    - ここでは0個のときにしかバリデーションが走らないのでマイナスになった場合正常に購入処理が継続されてしまう

**Comment by chihiro-adachi** [comment]
@yoshiaki-natsume 
ありがとうございます。

PurchaseFlowのバリデーションはカート投入のタイミングでも走るので、ここの判定条件を修正すればよさそうですね。

**Comment by chihiro-adachi** [comment]
#4341 で対応
