### ISSUE TITLE
メールアドレスに255文字より長いものを入れるとエラーになる

### ISSUE THREAD

**Issue by yoshiaki-natsume** [EC-CUBE/ec-cube#4340]
## 概要(Overview)

Entityの定義ではメールアドレスの長さは255文字となっているが、Formのバリデーションでメールアドレスの長さをチェックしていないので、確認用メールアドレス入力欄を含む各フォームでメールアドレスが255文字を越えた場合にデータの登録・更新でエラーが発生する。

## 期待する内容(Expect)  or 要望 (Requirement)

メールアドレスのバリデーションで文字列長もチェックするようにする

## 再現手順(Procedure)

メールアドレスの入力が求められるフォームで255を超えた文字列を入れる

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9
+ DB:
  - MySQL 5.7.x

## 関連情報 (Ref)

- [dtb_customerのemailの定義](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Entity/Customer.php#L101)
- [実際のemailのバリデーション](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Form/Type/RepeatedEmailType.php#L46-L73)
- 実際に利用されている箇所
  - [EntryType](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Form/Type/Front/EntryType.php#L77)
  - [NonMemberType](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Form/Type/Front/NonMemberType.php#L74)

**Comment by kazumiiiiiiiiiii** [comment]
こちら、マージされましたのでクローズいたします。
