### ISSUE TITLE
4xx系のエラーログの出力レベルを見直し検討してもらいたい

### ISSUE THREAD

**Issue by yoshiaki-natsume** [EC-CUBE/ec-cube#4361]
## 概要(Overview)

現状4xx系含めてエラーを全てログレベルERRORとして出力していると認識しています([該当コード](https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/EventListener/ExceptionListener.php#L76))
本番環境の監視などを想定した場合、ログレベルのERRORというのは500エラーのように何かしら対応を求められるものという認識なので、404などのユーザー起因のエラーはログレベルを下げたほうが良いのではないでしょうか？

## 期待する内容(Expect)  or 要望 (Requirement)

4xx系のエラーログのレベルをWARNING等に下げる

## 再現手順(Procedure)

なし

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.x
+ DB:
  - MySQL 5.7.x

**Comment by chihiro-adachi** [comment]
@yoshiaki-natsume 
ありがとうございます。
確かに400番台でERRORになるのはおかしいですね。
WARNINGか、404等は対応する必要もないですし、INFOレベルでもよいのかな、という気がします。

出力レベルの考え方は以下の指針に沿って作っていたかと。
https://qiita.com/nanasess/items/350e59b29cceb2f122b3

**Comment by yoshiaki-natsume** [comment]
そうですね、自分もINFOレベルで良いと思います。

**Comment by genzouw** [comment]
プルリクエストを取り込みました。
