### ISSUE TITLE
全てのリクエストで一様にトランザクションを貼るのを止めたい

### ISSUE THREAD

**Issue by yoshiaki-natsume** [EC-CUBE/ec-cube#4366]
## 概要(Overview)

onKernelRequestでbeginTransactionを行っているため、トランザクションが不要なDBへの処理も全てトランザクションが貼られるため、DBのパフォーマンスが落ちてしまいます。
必要なときだけ必要なトランザクションを貼ったほうが良いのではないでしょうか？

ちなみにEC-CUBE4系でのトランザクション管理について把握してないのでお聞きしたいのですが、現時点のソースコードでは必要箇所にbeginTransactionを明記せず、onKernelRequestで全てカバーするような実装になっているのでしょうか？

## 期待する内容(Expect)  or 要望 (Requirement)

- onKernelRequestでの一律のトランザクション処理を廃止する
- beginTransactionは必要な処理のみに記述する(決済や在庫数の変更処理等)

### 環境 (environment)
+ EC-CUBE: 4.0.1
+ PHP: 7.2.x
+ DB:
  - MySQL 5.7.x

## 関連情報 (Ref)

- [該当コード](https://github.com/EC-CUBE/ec-cube/blob/4.0.3/src/Eccube/EventListener/TransactionListener.php#L66-L87)

**Comment by nanasess** [comment]
プラグインなど拡張した箇所で、何らかの処理に失敗した場合、できる限りすべてロールバックできるようにするためですね。
個別に記述できるようにした場合、プラグイン側でも個別にトランザクションブロック記述する必要がでてきます。
1リクエストで複数のプラグインが処理を行う場合、個別にトランザクションブロックを記述してしまうと、処理が失敗した場合にコミット済みの処理を考慮してエラーハンドリングする必要があると思います。
これを簡便にするため、1リクエスト1トランザクションになるようにしています。

ちなみに不勉強で申し訳ございませんが、トランザクションによるボトルネックはどの程度出るものなのでしょうか？

**Comment by nanasess** [comment]
経緯についてはこのあたりです
https://github.com/EC-CUBE/ec-cube/issues/1518#issuecomment-234825735

**Comment by yoshiaki-natsume** [comment]
本体と複数プラグイン間でのトランザクション管理は考えていませんでした。確かに安全側に倒すとリクエスト内でトランザクション全体を管理するのが良いですね。

>ちなみに不勉強で申し訳ございませんが、トランザクションによるボトルネックはどの程度出るものなのでしょうか？

不勉強なんてとんでもないです…

ボトルネックとしましては単一商品規格に対する購入処理が集中した場合MySQLの `innodb_lock_wait_timeout` を超えてタイムアウトが発生しやすくなるため、なるべくtransactionを貼る処理を最小単位にしたいと考えています。

また、他サービスと連携してバッチ処理などを行う場合httpでトリガーされる場合が多く、その場合バッチ処理の間ずっとトランザクションが貼られるため、通常リクエストでのDB更新処理がタイムアウトエラーになりやすいという問題があります。

どちらもEC-CUBEの用途とユースケースが違いそうなのでなんとも言えませんが、設定等でリクエストに対するトランザクション管理の方法も選べたら良いかなと思いました。例えばcontrollerのannotationでオン・オフできるようなインタフェースだと汎用性が増すかと思います。

**Comment by nanasess** [comment]
@yoshiaki-natsume ありがとうございます。そこまでミッションクリティカルな状況を考えると、トランザクションよりも Doctrine ORM の方がボトルネックになってきそうですね🤔
デッドロックによる不具合発生を懸念されているのだと思いますが、トランザクションの範囲を限定して回避するよりも、デッドロックが発生しにくい処理に改修していく方が正しいのかなと思いました。

**Comment by yoshiaki-natsume** [comment]
対象のリクエストでauto-commitを有効化することでデッドロックを防げそうだったので、そちらで対応することにしました。ありがとうございます！
