### ISSUE TITLE
ルート以下のディレクトリにインストールした場合”お気に入りに追加”ができない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4369]
## 概要(Overview)

開発コミュニティより
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22931&forum=8&post_id=95087#forumpost95087

> ルート直下のディレクトリ"shop"にインストールしました。商品アイテムの”お気に入りに追加 → ログイン画面 → ”ページが見つかりません”となります。
> "-https://xxxx.com/shop/shop/products/add_favorite/1-"にかえされてしまいます。
> また、ルート直下に展開したところ問題はありませんでしたが、ルート直下のディレクトリに展開したいのです。
> 何卒、どうかよろしくお願いいたします。
> 
> また余談ですが、ルート直下に展開しても商品アイテムの”お気に入りに追加”からログイン時に入力ミスをすると”お気に入りに追加”されず再入力後、トップページにかえされます。

## 期待する内容(Expect)  or 要望 (Requirement)
ルート以下のディレクトリにインストールした場合でも正常にお気に入りに追加できる

## 再現手順(Procedure)

1. `example.com/path/to/ec-cube` にEC-CUBE をインストールする
2. 会員登録する
3. ログアウト状態で商品をお気に入りに追加
4. ログインすると、 404 Not found になる

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.3.10

**Comment by chihiro-adachi** [comment]
#4373 で修正
