### ISSUE TITLE
さくらレンタルサーバー向けの.htaccess記述を削除する

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#4381]
## 概要(Overview)
さくらレンタルサーバー向けに、回避用の記述を.htaccessにコメントとして記載していた。
さくらレンタルサーバーのFreeBSDのアップデートに伴い、不要になったので削除する。
(削除するだけで良い)

### 該当箇所
https://github.com/EC-CUBE/ec-cube/blob/4.0/.htaccess#L39

## 関連情報 (Ref)
https://help.sakura.ad.jp/notification/360000190121/

**Comment by okazy** [comment]
#4501 で修正されたかと思います。

**Comment by okazy** [comment]
クローズします。ありがとうございました。
