### ISSUE TITLE
masterブランチを作成し、defaultブランチとして設定してほしい。

### ISSUE THREAD

**Issue by genzouw** [EC-CUBE/ec-cube#4390]
## 概要(Overview)
masterブランチを作成し、defaultブランチとして設定してほしい。

## 期待する内容(Expect)  or 要望 (Requirement)
最新ブランチがわかりやすくなりますね。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
現状バージョンごとにブランチを作成する形で運用しているためクローズします。
