### ISSUE TITLE
GitHub Actionsが軒並み失敗する

### ISSUE THREAD

**Issue by m-pyon23** [EC-CUBE/ec-cube#4392]
## 概要(Overview)
プルリクの際のCIが軒並み失敗しているが、コード類の問題ではなくGitHub Actions自体が契約類の問題により正常に動いていないと思われる

```
### ERRORED 09:12:07Z

- Workflows can't be executed on this repository. Please check your payment method or billing status.
```

## 期待する内容(Expect)  or 要望 (Requirement)
- GitHub Actionsのワークフローが正常に実行されること

### 環境 (environment)
GitHub

## 関連情報 (Ref)
#4391 
#4386 
#4383

**Comment by Rights1995** [comment]
こちらでも同様の現象が起きています。

github-actions で Build Failed となっています。

### ERRORED 08:48:38Z

- Workflows can't be executed on this repository. Please check your payment method or billing status.

#4349 
この場合、処理が失敗しているので、完了した旨の通知も届かないでしょうか？

**Comment by chihiro-adachi** [comment]
@m-pyon23 @Rights1995 

契約しているプランの関係上、GitHub Actionsが利用できないみたいです。
いったん無効化したので、今後のPRではGitHub Actionsは走りません。

既にいただいているPull Requestについては、他のCIが通っているかどうかで判断する予定です。
すみませんがよろしくおねがいします。

**Comment by m-pyon23** [comment]
了解しました
一旦クローズします！
