### ISSUE TITLE
プラグイン検索機能が大文字小文字を無視してくれない

### ISSUE THREAD

**Issue by genzouw** [EC-CUBE/ec-cube#4393]
## 概要(Overview)

4.0.xの管理画面から、プラグイン検索を行う場合、大文字小文字を無視してくれない。

## 期待する内容(Expect)  or 要望 (Requirement)

大文字小文字を無視してくれたほうが使いやすいのでは？と思いました。

## 再現手順(Procedure)

* 管理画面の「プラグインを探す」ページから、キーワードでプラグインを検索する。
    * `facebook` で検索した場合、 `Facebook` が検索結果として表示されない。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by kiy0taka** [comment]
Package API側で対応しました。
