### ISSUE TITLE
Safariで管理画面から認証キーを発行できない

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4416]
## 概要(Overview)

Safariにおいて、認証キー新規発行で「エラー 入力された文字列が正しくありません。」と表示されて発行ができない。

<img width="1077" alt="スクリーンショット 2019-12-16 10 24 39" src="https://user-images.githubusercontent.com/16895409/70872974-b0604c80-1fee-11ea-964d-91dc0e51e52b.png">

他に条件があるか、いつから発生したかも不明。

## 期待する内容(Expect)  or 要望 (Requirement)

Safariで認証キーの発行ができる

## 再現手順(Procedure)

Safariにて認証キーの発行を行う。

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.2.9
+ DB:
  - PostgreSQL 10.5
+ Safari（エラー）
  - バージョン13.0.4 (13608.4.9.1.4)
+ Chrome（正常）
  - バージョン: 79.0.3945.79（Official Build） （64 ビット）
+ FireFox（正常）
  - 71.0 (64 ビット)

**Comment by nanasess** [comment]
ブラウザのコンソールから、以下のように fetch をコールして API キーの取得を確認
- ⭕️ Chrome
- ⭕️ Firefox
- ❌ Safari(13.0.3)

```javascript
fetch("https://package-api.ec-cube.net/api_key",
      {
          "credentials": "include",
          "headers":
          {
              "accept": "application/json, text/javascript, */*; q=0.01",
              "accept-language": "ja,en-US;q=0.9,en;q=0.8",
              "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
              "eccube-csrf-token": "tCpu1cJLaNuYLmb2Ny62zGXRmAXlM8tZRCa8QvkCFUQ",
              "sec-fetch-mode": "cors",
              "sec-fetch-site": "cross-site"
          },
          "referrer": "http://127.0.0.1:8000/admin/store/plugin/authentication_setting",
          "referrerPolicy": "no-referrer-when-downgrade",
          "body": "captcha=s0DhY8&eccube_url=http%3A%2F%2F127.0.0.1%3A8000%2F&eccube_version=4.0.3&eccube_shop_name=EC-CUBE+SHOP",
          "method": "POST",
          "mode": "cors"
      }
     )
    .then((response) => response.text())
    .then((text) => console.log(text))
    .catch((error) => console.log(error));

```

eccube-csrf-token 及び、 captcha は EC-CUBE 管理画面から発行されたものに置きかえる

**Comment by nanasess** [comment]
[eccube/mock-package-api](https://hub.docker.com/r/eccube/mock-package-api) では再現せず

**Comment by nanasess** [comment]
Safari 12.1.2 では再現せず。正常に動作する

**Comment by chihiro-adachi** [comment]
おそらく3rd party cookieの制限によるものと思われる。
キャプチャ文字列の保持・照合をpackage-apiのセッションで行っているが、セッションクッキーが3rd party cookieとなる。
safari 13から3rd party cookieはデフォルトでブロックされるようになった模様。
safari だけでなく、chromeも2023年末には3rd party cookieが廃止されるため、cookieに依存しない仕組みへの変更が必要そう。


```mermaid
sequenceDiagram
    ブラウザ ->> EC-CUBE: 認証キー画面を表示
    EC-CUBE ->> ブラウザ: 認証キー画面を返却
		ブラウザ ->> ブラウザ: 認証キー発行モーダルを表示
		ブラウザ ->> package-api: キャプチャ画像リクエスト(/capcha)
		package-api ->> package-api: キャプチャ文字列をセッションへ保存
		package-api ->> ブラウザ: キャプチャ画像、セッションクッキー(※3rd party)を返却
		ブラウザ ->> ブラウザ: 文字列を入力し、新規発行ボタン押下
		ブラウザ ->> package-api: 認証キー発行リクエスト(/api_key)
		package-api ->> package-api: セッション内の文字列と照合。同一であれば認証キー発行
		package-api ->> ブラウザ: 認証キーを返却
		ブラウザ ->> EC-CUBE: 認証キーを登録
```

**Comment by nanasess** [comment]
@chihiro-adachi あー、それで Safari だけ動かなくなってたんですね

**Comment by chihiro-adachi** [comment]
はい、そのようです。

**Comment by chihiro-adachi** [comment]
#5388 で対応
