### ISSUE TITLE
在庫なしの状態で規格初期化すると在庫「なし」の絞り込み結果に出続ける

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4421]
## 概要(Overview)
在庫なしの組み合わせを含む状態で規格初期化すると
その後在庫があったとしても商品マスタで在庫「なし」の絞り込み結果に出続ける

(開発環境の場合はProduct::getPrice02MinでWarning発生する)

理由：管理画面商品マスタでvisible = falseのProductClassを検索に含んでいるため。

## 期待する内容(Expect)  or 要望 (Requirement)
検索時点で在庫なしの規格が存在しないのであれば、絞り込み条件在庫なしではヒットしない

## 再現手順(Procedure)
1. 規格を登録した商品のいずれか１つ以上の規格を在庫０にする
2. 1の商品の規格を初期化する
3. 在庫を無制限または数値を設定する
4. 商品マスタの絞り込み条件在庫なしで検索する

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=thread&order=ASC&topic_id=23140&forum=11

**Comment by okazy** [comment]
以下で修正されたのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4422
