### ISSUE TITLE
Basic認証をかけた場合、Google Chromeでアクセスすると真っ白の画面となる

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4424]
## 概要(Overview)

Basic認証をかけた場合、特定ページにGoogle Chromeでアクセスすると真っ白の画面となる。

### Basic認証の設定

Basic認証の記述は `.htaccess` に記載されているBasic認証サンプルを利用

https://github.com/EC-CUBE/ec-cube/blob/54dab5f603220ed9fa039c4df6242c090e57fa7c/.htaccess#L59

### アクセスができなくなるページ

- 管理画面
- マイページ

※TOPページは表示可能なため、おそらくSymfonyで認証の設定をしているページかと予想できるが詳細は不明

### ブラウザ

- アクセス不可
  - Google Chrome (バージョン: 79.0.3945.88（Official Build） （64 ビット）)
- 正常にアクセス可能
  - Safari (バージョン13.0.4 (13608.4.9.1.4))
  - Firefox (71.0 (64 ビット))

Google Chromeの以前のバージョンではアクセス可能だったため、アップデートでアクセスできなくなったと思われるが、いつからアクセスできなくなったかは不明

## 期待する内容(Expect)  or 要望 (Requirement)

Basic認証をかけた管理画面にGoogle Chromeの最新版でアクセスができる

## 再現手順(Procedure)

1. `.htaccess` のサンプルを元にBasic認証の設定をする
2. 管理画面のURLにアクセスする
3. Basic認証のIDとPassを入力する
4. 画面が真っ白になる

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP:  7.2.25
+ DB:
  - PostgreSQL: 9.2.24
+ CentOS Linux release 7.7.1908
+ Server version: Apache/2.4.6 (CentOS)

**Comment by kiy0taka** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1034468
このバグっぽいです。

Google Chrome Version 80.0.3987.16 (Official Build) beta (64-bit) で試したところ動作していたので次のアップデートで解消されると思います。

**Comment by genzouw** [comment]
## 原因

### 検証による状況証拠

`HTTP RESPONSE CODE = 401` が返却されると、ResponseBodyが捨てられ、Basic認証の認証済みステータスがリセットされる。

```
 +-Chrome-+             +-Apache------------------+
 |        | ----------> |                         |
 |        | <-401------ | BasicAuth               |
 |        | ----------------+                     |
 |        |             |   |       +-EC-CUBE----+|
 |        |             |   +-----> | AppAuth    ||
 |        | <-401------------------ +------------+|
 +--------+             +-------------------------+
```

## 暫定的な対処

### 1.Chrome以外のブラウザを利用する

Safari / Firefoxなどを利用。

### 2.URLを一部変更する

*（検証やサイト公開前の準備のためにBasic認証をかけているのであれば）*
管理画面アクセス時に `/login` のリクエストパスを付与することで一時的に問題を解除できる

* **x** : `http://localhost:8080/admin` ( response_code = *401* )
* **o** : `http://localhost:8080/admin/login` ( response_code = *200* )

## 根本的な対処

**対処方法**

* `./app/config/eccube/packages/security.yaml` の `use_forward` を `false` に変更

```diff
$ gitdi ./app/config/eccube/packages/security.yaml
diff --git app/config/eccube/packages/security.yaml app/config/eccube/packages/security.yaml
index efb8df1e3c..2ad4e1a608 100644
--- app/config/eccube/packages/security.yaml
+++ app/config/eccube/packages/security.yaml
@@ -31,7 +31,7 @@ security:
                 default_target_path: admin_homepage
                 username_parameter: 'login_id'
                 password_parameter: 'password'
-                use_forward: true
+                use_forward: false
                 success_handler: eccube.security.success_handler
                 failure_handler: eccube.security.failure_handler
             logout:
@@ -53,7 +53,7 @@ security:
                 default_target_path: homepage
                 username_parameter: 'login_email'
                 password_parameter: 'login_pass'
-                use_forward: true
+                use_forward: false
                 success_handler: eccube.security.success_handler
                 failure_handler: eccube.security.failure_handler
             logout:
...
```

**Comment by okazy** [comment]
以下で修正されました。
https://github.com/EC-CUBE/ec-cube/pull/4431
