### ISSUE TITLE
売上状況が9時間ずれる問題

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4426]
## 概要(Overview)
売上状況のグラフは正しいが、今月・今日・昨日の売上金額が9時間ずれて集計されている。

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.1.32
+ DB:
  - MySQL 5.7.27

**Comment by okazy** [comment]
#4465 で修正されましたのでクローズします。
