### ISSUE TITLE
不要な？FormTypeクラスが存在しているため、見直し検討してもらいたい

### ISSUE THREAD

**Issue by watarukashii** [EC-CUBE/ec-cube#4443]
## 概要(Overview)
./src/Eccube/Form/Type/ShoppingType.php というファイルですがレジ関連のファイルかと思い調べているのですが、使われている形跡が見当たりませんでした。

## 期待する内容(Expect)  or 要望 (Requirement)

もし使っていなさそうでしたらこちらのファイルを削除するなどご検討お願いします。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)

コミット情報
https://github.com/EC-CUBE/ec-cube/commit/67ff2c372e101141e429305cc2aae1eb77f555dd　にて
src/Eccube/ServiceProvider/EccubeServiceProvider.php　から削除
https://github.com/EC-CUBE/ec-cube/commit/134bb8d6f22d78664fe10bbf30f83cde9f73da6a　にて
tests/Eccube/Tests/Service/PaymentServiceTest.php　から削除されているようでした。

**Comment by okazy** [comment]
以下で修正されたのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4471
