### ISSUE TITLE
管理画面受注一覧 入金日(終了)のラベル間違い

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4450]
## 概要(Overview)

入金日(終了)で検索すると、入金日(開始)と表示される

![スクリーンショット 0032-01-25 14 38 21](https://user-images.githubusercontent.com/4304985/73116830-5dc86780-3f80-11ea-9c31-6461a9984dbd.png)

## 期待する内容(Expect)  or 要望 (Requirement)
入金日(終了)と表示される

## 再現手順(Procedure)
入金日(終了)に日付を入力して検索

### 環境 (environment)
+ EC-CUBE: 4.0.3

**Comment by okazy** [comment]
以下のプルリクで修正されましたのでクローズします。
https://github.com/EC-CUBE/ec-cube/pull/4451
