### ISSUE TITLE
カートに追加できなくてもブラウザバック時に「カートに追加しました」とメッセージが表示される

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4466]
## 概要(Overview)
商品詳細や一覧でカートに追加する際に
カートに追加できていなくてもブラウザバックすると「カートに追加しました」とメッセージが表示される

## 期待する内容(Expect)  or 要望 (Requirement)
ブラウザバック時は何もメッセージが表示されない、または、元のメッセージが表示される

## 再現手順(Procedure)
1. 販売制限でカートに追加できない状態でカートに追加を行う
2. 「チェリーアイスサンド」は販売制限しております。一度に販売制限数を超える購入はできません。」とモーダルメッセージが表示される
3. モーダル内のカートへ進むをクリックしカートへ移動
4. ブラウザバックで戻る
5. 「カートに追加しました」とモーダルメッセージが表示される

販売制限以外の在庫などの制約に引っかかった場合も再現すると考えられる

### 環境 (environment)
+ EC-CUBE: 4.0.3

**Comment by okazy** [comment]
ありがとうございます！
#4468 で修正されました。
