### ISSUE TITLE
税率設定の適用日時エラーメッセージが設定されていない。

### ISSUE THREAD

**Issue by belltzel** [EC-CUBE/ec-cube#4475]
## 概要(Overview)
税率設定で同じ適用日時を登録しようとすると表示されるエラーメッセージが「taxrule.text.error.date_not_available」になっている。

## 期待する内容(Expect)  or 要望 (Requirement)
taxrule.text.error.date_not_availableのエラーメッセージ設定。

/src/Eccube/Form/Type/Admin/TaxRuleType.phpの92行目

## 再現手順(Procedure)
登録されている適用日時と同じ適用日時で税率を登録する

### 環境 (environment)
+ EC-CUBE: 4.0.3

## 関連情報 (Ref)

**Comment by okazy** [comment]
Issueの作成とクローズありがとうございます。
以下のプルリクで修正されました。
https://github.com/EC-CUBE/ec-cube/pull/4526
