### ISSUE TITLE
商品購入/ご注文確認に「閉じspan」だけ残っている

### ISSUE THREAD

**Issue by hmatsuba** [EC-CUBE/ec-cube#4487]
## 概要(Overview)

「商品購入/ご注文確認」のテンプレートの「お客様情報」欄

https://github.com/EC-CUBE/ec-cube/blob/70483058b0f7f486dab0dad0eaa9ee1077846a7f/src/Eccube/Resource/template/default/Shopping/confirm.twig#L71-L79

閉じる `</span>` だけ残っています。

## 期待する内容(Expect)  or 要望 (Requirement)

何かのスタイルつける `<span>` が必要であれば追加を、
`<span>` 自体が不要であれば削除するとよいと思います。
※判断がつかなかったのでプルリクしませんでした

## 再現手順(Procedure)

商品を追加し、レジに進み、注文内容を確認する画面で表示されます。
※特段の表示崩れなどは発生してないようです

### 環境 (environment)

+ EC-CUBE: 4.0.3
+ PHP: 7.2.27
+ DB:
  - MySQL 5.7.29

**Comment by chihiro-adachi** [comment]
#5228 で修正されました。
