### ISSUE TITLE
プラグインからのPurchaseFlowカスタマイズについての質問

### ISSUE THREAD

**Issue by watarukashii** [EC-CUBE/ec-cube#4491]
## 概要(Overview)

プラグインからレジ周りのカスタマイズにあたって、PurchaseFlow にプロセッサを追加するとのことですが、やり方がいくつかあるかと思います。2つ質問したいです。

1) 実装のアプローチ
a) https://doc4.ec-cube.net/customize_service#processor-%E3%81%AE%E5%AE%9F%E8%A3%85%E4%BE%8B
では app/config/eccube/packages/purchaseflow.yaml の定義する

メリット：どのタイミングで実行されるのか、yamlでわかる。
デメリット：プラグイン有効にしても実行されない。yaml追記が必須。

b) https://github.com/EC-CUBE/ec-cube/pull/3289
では アノテーションを追加

メリット：プラグイン有効後のyaml追記は要らない。バージョンアップに伴うファイルが上書きされることはなくなる。
デメリット：そのプロセスのどのタイミングで実行されるのかが不明（ただ、プロセッサは、基本細分化された単位なので気にする必要ナシ？）

それぞれメリットデメリットをまとめてみましたが、多視点でご意見をいただきたいです。

2)namespace の指定

a) https://doc4.ec-cube.net/customize_service#processor-%E3%81%AE%E5%AE%9F%E8%A3%85%E4%BE%8B
では `./app/Plugin/プラグインコード/Processor`

b) https://github.com/EC-CUBE/ec-cube/pull/3289
では `./app/Plugin/プラグインコード/Service/PurchaseFlow/Processor`

下記の2ページでは、構造的に差分があったため、本来どちらがいいのか？どちらでもよいのか？
見解をお聞きしたいです。私としては、srcフォルダで a) の構造となっているので合わせたほうが良いのではと考えております。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
> 1. 実装のアプローチ

メリット、デメリットはご認識の通りです。
単純なカスタマイズでしたらアノテーションの追加をおすすめしますが、何個も Processor を追加するような場合は Yaml での定義をおすすめします。
Yaml で定義してあった方が、後任者に引き継ぎしたりする場合に把握しやすいです。

> 2. namespace の指定

b が正しいと思います

**Comment by watarukashii** [comment]
@nanasess 遅くなりましたが、ご回答いただきありがとうございました。issue クローズとします。
