### ISSUE TITLE
管理画面のテンプレートのアップロードページのツールチップが表示されない

### ISSUE THREAD

**Issue by yKazihara** [EC-CUBE/ec-cube#4492]
## 概要(Overview)
管理画面→オーナーズストア→テンプレート→アップロードのツールチップ(？マーク)にカーソルを当ててもヒントが表示されない。
 - テンプレートコード
 - テンプレート名
 - テンプレートファイル

## 期待する内容(Expect)  or 要望 (Requirement)
上記？マークにカーソルを当てたらヒントが表示される。

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
#4944 で修正していただきましたのでクローズします。
