### ISSUE TITLE
管理画面同様、フロント画面もIP制限をしたい

### ISSUE THREAD

**Issue by yosshieee** [EC-CUBE/ec-cube#4507]
## 概要(Overview)
サイトリリース前、メンテナンス中などを考慮して、
管理画面のセキュリティ機能と同様の機能を、フロント画面も使えるようにしたいです。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
特定のユーザーのみフロントにアクセスしたいという要件でしたら、現在のメンテナンス画面でも十分要件を満たしていると思いますがいかがでしょう？

ブラウザ以外でフロント画面にアクセスすることを想定していますか？？

**Comment by ryo-endo** [comment]
@nanasess いまのメンテナンス機能の仕様だと、管理画面にログインしている・いない関わらず、フロントにはアクセスができなくなる仕様だったと思います。

ref 取り込まれなかったPR https://github.com/EC-CUBE/ec-cube/pull/4057

**Comment by nanasess** [comment]
@ryo-endo なるほど、取り込まれてなかったんですね。失念してました。失礼しました。

**Comment by nanasess** [comment]
IPに依存しているのは、あまりよろしくない気がするので、フロント画面へのアクセス許可をブラウザに限定して良いのであれば、 **管理画面ログインしているユーザーのみアクセス許可** の方が良いと思います

**Comment by chihiro-adachi** [comment]
@t-nagahashi 
こちらのプラグインで、管理者のフロント閲覧機能があるようですが要件みたせそうでしょうか？
https://www.ec-cube.net/products/detail.php?product_id=1716

**Comment by yosshieee** [comment]
ありがとうございます！
こちらで対応できそうです。
