### ISSUE TITLE
FatalThrowableError Cannot instantiate abstract class Eccube\Twig\Template

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4520]
## 概要(Overview)

APP_ENV=devの際に、表題のデバッグ画面が表示される

#4502 を参照

### 環境 (environment)

+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
Issueが重複して作成されていたのでこちらにまとめます。
https://github.com/EC-CUBE/ec-cube/issues/4529

## 概要(Overview)

キャッシュ削除後の初回アクセス時にデバッグツールバーで以下のようなエラーが発生する。

![image](https://user-images.githubusercontent.com/16895409/80831978-c6ca1600-8c26-11ea-9d2f-1f3b11edc08a.png)

以下のPRが原因と思われる。
https://github.com/EC-CUBE/ec-cube/pull/4362

プロダクトモードでは発生しないもよう。

## 期待する内容(Expect)  or 要望 (Requirement)

エラーが発生しない。

## 再現手順(Procedure)

1. 環境変数を `APP_ENV=dev, APP_DEBUG=1` を設定
1. 管理画面からキャッシュを削除
1. どこかのページにアクセス

デバッグツールバーでエラーが発生

### 環境 (environment)
+ EC-CUBE: 4.0.x (最新ブランチ)
+ PHP: 7.3

## 関連情報 (Ref)
