### ISSUE TITLE
プラグインのtemplteもapp/templateで上書きしたい

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#4521]
## 概要(Overview)
コア((src配下))の管理画面のテンプレートなどは```app/template```に同名のファイルを置く事で拡張できるが、プラグインのview(テンプレート)を拡張する手段が無い。

## 期待する内容(Expect)  or 要望 (Requirement)
```app/templte/plugin/[plugin_code]```配下とかに同名のファイル置いたらそっちが優先されて利用される様にしたい。
もしくは、```app/Customize/Resource/Plugin/[plugin_code]```とかでも

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.2.x

**Comment by okazy** [comment]
#4527 にて機能追加されましたのでこちらはクローズさせていただきます。
