### ISSUE TITLE
MySQL での charset の初期値を utf8mb4 にする

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4525]
## 概要(Overview)
最近は、お問い合わせ覧などに絵文字を入力されるユーザーが増えており、 utf8 のままだとシステムエラーになってしまい、機会損失につながりやすい。
MySQL での charset の初期値を utf8mb4 にし、絵文字を使用できるようにする。

## 期待する内容(Expect)  or 要望 (Requirement)
- `dbal: charset` の初期値を utf8mb4 にする
- `dbal: default_table_options: collate` は `utf8mb4_bin` に変更した方が良いかもしれない
   - 参考 https://pando.life/qwintet/article/833

## 再現手順(Procedure)

お問い合わせ覧に絵文字を入力する

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.4.5
+ DB:
  - MySQL 5.7.29

**Comment by chihiro-adachi** [comment]
#4796 で対応
