### ISSUE TITLE
How to add a column when exporting a csv file

### ISSUE THREAD

**Issue by socloccoc** [EC-CUBE/ec-cube#4537]
### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
You can select output items on the management page.

![image](https://user-images.githubusercontent.com/16895409/82170638-fe5fe000-98ff-11ea-9059-39fa4e288a90.png)

If you add a new column, you need to add a setting record to "dtb_csv".

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
