### ISSUE TITLE
非公開の商品がSEO検索でヒットしてしまう

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4543]
## 概要(Overview)
非公開の商品がSEO検索でヒットしてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)
非公開の商品の商品詳細ページは noindex を出力して検索インデックスが貼られないようにすべき。

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by okazy** [comment]
確かに非公開の商品が検索結果に出てきたら困りますね。

商品を非公開にすると「ページがみつかりません。」の画面が表示されると思うので、こちらの画面に `noindex` を入れるのが良いのでしょうか。

**Comment by hironori-tanaka** [comment]
そうですね。
運用では公開していた商品を非公開にすることもありますので、非公開にして検索結果に残り続けるのは良くないと思われます。
ただ、404 ページに遷移するのでしたらいずれ検索結果に表示されなくなると思いますので、対応なしでも良いのかもしれません。

**Comment by okazy** [comment]
管理画面にログインした状態ですと非表示の商品の詳細画面がみれますが、ログアウトした状態でアクセスすると404のページが表示されるかと思います。
すぐに更新したいときはサーチエンジンのクローラに更新を依頼するのが良いかと思います。

エラーページにnoindexが入っていませんでしたので、入れるプルリクを作成して置きました。
#4544

**Comment by okazy** [comment]
https://github.com/EC-CUBE/ec-cube/pull/4544#issuecomment-649153603
404を返しているのでnoindexも不要とのことでした。

こちらのIssueはクローズさせていただきます。
