### ISSUE TITLE
受注編集にて複数商品の時、商品削除→追加時に正しく追加されない場合がある。

### ISSUE THREAD

**Issue by DAICHI-Otani** [EC-CUBE/ec-cube#4545]
## 概要(Overview)
受注編集にて複数商品の時に、商品削除→追加時に、
・商品の情報が上書きされてしまう。
・削除した商品の商品コード、商品規格1/商品規格2が追加した商品やその他明細に適応されてしまう。
という場合があります。

## 期待する内容(Expect)  or 要望 (Requirement)
商品の削除→追加時に、正しく商品が追加される。

## 再現手順(Procedure)
1.受注明細（商品または、その他明細）が、3つ以上の受注を作成する。
2.受注明細の上２つを削除する。
3.受注明細を新たに追加する（商品・その他明細問わず）。

上記手順で新たな商品・明細が追加されず、既存明細項目に上書きされてしまう。

また、以下の手順を踏むと
商品・明細は追加されるが、商品コード・商品規格1/商品規格2が削除した商品の情報で適応されてしまう。

1.受注明細（商品または、その他明細）が、3つ以上の受注を作成する。
2.受注明細の下２つを削除する。
3.受注明細を新たに追加する（商品・その他明細問わず）。

### 環境 (environment)
+ EC-CUBE: 4.0.2

## 関連情報 (Ref)

**Comment by okazy** [comment]
同様の問題かわかりませんが、以下の手順で `HTTP 500 Internal Server Error` となりました。

1.受注明細が3つ以上の受注を作成する。（eccube:fixture:generatコマンドで作成）
2.受注明細の上２つを削除する。
3.割引（課税）明細を新たに追加する。

![image](https://user-images.githubusercontent.com/16895409/83228168-c3dc2a00-a1c0-11ea-9b2a-2870cf65ed48.png)

ブラウザからの送信時には `OrderItemType` が設定されていましたが、エラー個所では設定されていませんでした。サーバサードの処理に問題があるのではないかと思います。

**Comment by ryo-endo** [comment]
@kiy0taka 先日不具合修正されてたと思うので、なにかわかったことあれば補足お願いしますー。

**Comment by ryo-endo** [comment]
@kiy0taka さーん。

**Comment by hironori-tanaka** [comment]
EC-CUBE 4.0.4 で同様の問題が発生いたしました。
次の手順でシステムエラーが発生いたします。

■再現手順
1. フロントからの注文で受注登録を作成する
2. 受注の編集で「商品を追加」する
3. 既存の商品明細を削除する
4. 「その他の明細を追加」する

<img width="1155" alt="受注登録" src="https://user-images.githubusercontent.com/26919767/92206436-79a2cd00-eec2-11ea-97c5-530f29f05477.png">

**Comment by ryo-endo** [comment]
4.2-beta2でも引き続き発生することを確認しました。

https://user-images.githubusercontent.com/16891862/184468732-37939289-7a85-4459-b897-e452954c3295.mov

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5540 で対応
