### ISSUE TITLE
samesite設定有効時に、Webインストーラで画面遷移できない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4546]
## 概要(Overview)

samesite設定有効時に、Webインストーラで画面遷移できない

## 期待する内容(Expect)  or 要望 (Requirement)

画面遷移できること

## 再現手順(Procedure)

以下の設定を参考に、chromeのsamesite設定を有効にする

https://qiita.com/ahera/items/0c8276da6b0bed2b580c#%E3%83%86%E3%82%B9%E3%83%88%E6%96%B9%E6%B3%95

- SameSite by default cookies：enabled
- Cookies without SameSite must be secure：enabled

Webインストーラを表示し、「次へ進む」をクリックしても同一画面でリロードする

### 環境 (environment)
+ EC-CUBE: 4.0.4 試験用パッケージ
+ PHP: 7.2.19
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
古い cookie が残存していると似たような事象になりますが、 cookie を削除しても再現しますでしょうか？
参考) https://github.com/EC-CUBE/ec-cube/issues/3917

**Comment by chihiro-adachi** [comment]
はい、再現します。

**Comment by nanasess** [comment]
Cookie の Secure 属性がなぜか勝手に無効になってしまうため、 Cookie が拒否されるようです🤔

**Comment by nanasess** [comment]
framework.yaml で `cookie_secure: true` にすることで回避可能なのを確認。

```patch
diff --git a/app/config/eccube/packages/framework.yaml b/app/config/eccube/packages/framework.yaml
index 6145711bcc..ffe8b47391 100644
--- a/app/config/eccube/packages/framework.yaml
+++ b/app/config/eccube/packages/framework.yaml
@@ -11,6 +11,7 @@ framework:
         handler_id: 'Eccube\Session\Storage\Handler\SameSiteNoneCompatSessionHandler'
         save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
         name: '%env(ECCUBE_COOKIE_NAME)%'
+        cookie_secure: true
         cookie_lifetime: '%env(ECCUBE_COOKIE_LIFETIME)%'
         gc_maxlifetime: '%env(ECCUBE_GC_MAXLIFETIME)%'
         cookie_httponly: true
```

**Comment by chihiro-adachi** [comment]
ありがとうございます。

以下の箇所を削除したら動作するようになりました。
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/DependencyInjection/EccubeExtension.php#L61

インストール時にはECCUBE_FORCE_SSLは定義されてないので、cookie_secureの値がfalseに固定されているのかなと推測してますが。

**Comment by nanasess** [comment]
@chihiro-adachi なるほど、ここも `session.cookie_secure` の値を見るようにしたら良さそうですね

**Comment by chihiro-adachi** [comment]
cookie_secureは、SameSiteNoneCompatSessionHandlerで動的に判定してるようなので、EccubeExtensionでの設定はもう不要なのかな、と思いましたがいかがでしょう？？

**Comment by nanasess** [comment]
@chihiro-adachi そうですね、削除しても大丈夫そうですね
