### ISSUE TITLE
WhereClauseを省略形で書くとエラーが発生

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#4547]
## 概要(Overview)
(bool)$yがfalseとして評価される値を使用するとエラー

## 再現手順(Procedure)

``` php
// OK
[WhereClause::eq('p.hoge', ':hoge', ['hoge' => 0])];

// OK
[WhereClause::eq('p.hoge', ':hoge', 1)];

// Too few parameters: the query defines X parameters but you only bound X-1
[WhereClause::eq('p.hoge', ':hoge', 0)];
```

### 環境 (environment)
+ EC-CUBE: 4.0.3

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/blob/8aa1e38f042f7427d6f8f28b56887ef0082bc6fb/src/Eccube/Doctrine/Query/WhereClause.php#L48

**Comment by okazy** [comment]
クローズありがとうございます！
