### ISSUE TITLE
不要なコメントを削除する

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4553]
## 概要(Overview)

以下のコメントを削除する

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/DependencyInjection/EccubeExtension.php#L49

#4548 にて、上記の箇所でcookie_secureの設定は行わないようになったため、コメントも合わせて削除しておく

### 環境 (environment)
+ EC-CUBE: 4.0.4 テスト用パッケージ
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
#4566 で修正されましたのでクローズします。
