### ISSUE TITLE
ページ管理：商品詳細のmetaタグの記述誤り

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4556]
## 概要(Overview)

`<meta property="product:retailer_title" content="{{ Product.name }}"/>`

product:retailer_titleに商品名が入っているが、ショップ名の方が適切

## 期待する内容(Expect)  or 要望 (Requirement)

ショップ名が出力されること

## 再現手順(Procedure)

noteに商品詳細ページのURLを投稿時、購入ボタンに商品名が表示されています。

![image](https://user-images.githubusercontent.com/8196725/83999850-905a8600-a99e-11ea-8d9a-81673c65a6d7.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
#4597 にプルリクを出しました。
