### ISSUE TITLE
レイアウト削除失敗時のメッセージが不適切

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4558]
## 概要(Overview)

レイアウト削除失敗時のメッセージが不適切です。
ページに紐づいた状態で削除しようとしたところ、「すでに削除されています」になっています。
「このレイアウトは利用されています。ページとの紐づけを解除してから削除してください。」くらいが適切かと思います。

![image](https://user-images.githubusercontent.com/16895409/84000758-3c50a100-a9a0-11ea-9ce7-1d08b2b5d376.png)

## 期待する内容(Expect)  or 要望 (Requirement)

適切なエラーメッセージへ修正

## 再現手順(Procedure)

ページに紐づいた状態でレイアウトを削除

### 環境 (environment)
+ EC-CUBE: 4.0.4
+ PHP: 7.4
+ DB:
  - MySQL 5.7

**Comment by okazy** [comment]
#4599 にプルリクを出しています。

**Comment by yKazihara** [comment]
#4599 で修正されました。
ありがとうございました。
