### ISSUE TITLE
user_data 直下の .gitkeep は不要

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4559]
## 概要(Overview)

以下の .gitkeep は不要かと思います。
https://github.com/EC-CUBE/ec-cube/tree/4.0/html/user_data
管理画面から見えてしまっているので削除したいです。

## 期待する内容(Expect)  or 要望 (Requirement)

不要な .gitkeep の削除

### 環境 (environment)
+ EC-CUBE: 4.0.4

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/issues/4149

**Comment by Yangsin** [comment]
そもそも user_data のしたに asset が追加されたので user_dataの .gitkeepは不要ですね。

**Comment by chihiro-adachi** [comment]
#4593 で対応しました。
