### ISSUE TITLE
管理画面をIP制限した際に表示される画面のリンク先が 'localhost' になる

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4561]
## 概要(Overview)

設定>システム設定>セキュリティ管理 からIP制限をかけ、許可されていないIPからアクセスすると「アクセスできません。」の画面が表示される。
そこに表示されている「ログイン画面へ」のリンクが 'localhost' になってしまっている。

![image](https://user-images.githubusercontent.com/16895409/84011197-bee15c80-a9b0-11ea-9f5b-3ec69cc79a2e.png)

## 期待する内容(Expect)  or 要望 (Requirement)

対応は３ケースほど考えられる。
- 「ログイン画面へ」のリンクを管理画面のログイン画面のリンクにする
- 「ログイン画面へ」のリンクをフロント画面トップページのリンクにする
- 管理画面が外部からわからないようにそもそもフロント画面の404等にする。

## 再現手順(Procedure)

設定>システム設定>セキュリティ管理 からIP制限をかける。
許可されていないIPから管理画面へアクセスする。

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.4
+ DB:
  - MySQL 5.7

**Comment by okazy** [comment]
原因を調べて見ましたがわかりませんでした。
こちらのエラー画面は403以外にも管理画面のHttpException系は全てこのテンプレートを利用してるようです。
404では問題なく動いていますので、403のためにリンク先を切り替えるのは冗長な気がしますね。。。

**Comment by dk-umebius** [comment]
リンクがlocalhostになるのはIpAddrListenerのリスナーのpriorityが512のためで、31以下でしたら正しいドメインになるのではないかと思います。
https://github.com/EC-CUBE/ec-cube/blob/4.0.4/src/Eccube/EventListener/IpAddrListener.php#L62

ただpriority変えるのはプラグイン等に影響出そうですし、twigのurlをpathに変えることで対応可能かと思いましたので一応プルリクさせていただきました。
どんな修正方法でも良いのですが、アクセス制限画面でリンク切れがあまり印象良くないので何かしら対応いただけるとありがたいです。

**Comment by kiy0taka** [comment]
#4637 で対応いただいたのでクローズします。
