### ISSUE TITLE
ブラウザでインストール時のSSL制限機能をデフォルトにしたい

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4568]
## 概要(Overview)

ブラウザでインストール時のSSL制限機能はオプトインとなっており、わざわざチェックして有効にする必要がある。

## 期待する内容(Expect)  or 要望 (Requirement)

このご時世SSLは必須なので、すでにSSLでアクセスしている場合はデフォルトで有効にしたい。

## 再現手順(Procedure)

SSL環境でブライザでインストール

### 環境 (environment)
+ EC-CUBE: 4.0.4

**Comment by okazy** [comment]
#4598 でプルリクを出しました。

**Comment by chihiro-adachi** [comment]
#4598 で修正されました。
