### ISSUE TITLE
自動ログイン状態からのログイン時にもカートがマージされてしまう不具合

### ISSUE THREAD

**Issue by hinto-Yamashita** [EC-CUBE/ec-cube#4574]
## 概要(Overview)
オートログイン機能及びカート情報保持機能を利用した際
カートの商品数量が2倍になる事象が発生する。

## 期待する内容(Expect)  or 要望 (Requirement)
数量2倍の事象を解消して欲しい。

## 再現手順(Procedure)

1. 管理画面より自動ログインをON。
2. 登録済み会員IDにてログインする
3. カートに商品を1個入れる
4. ブラウザを閉じる
5. ブラウザを立ち上げる（2のユーザでログイン）
6. カート内には「3」の商品を確認。
7. 「レジに進む」のボタンを押下。
8. ログインを要求されるので、ログインを行う。
9. 内容確認画面に入ると、「3」の商品が2個になっている

### 環境 (environment)
EC-CUBE: 4.0.3

**Comment by okazy** [comment]
ローカル環境で試して見たところ再現しました。
EC-CUBE 4.0.0 からログイン時に以前のカート情報を復元する機能が加わりました。
購入ログインにて「現在のカート内」と「ログアウト前のカート内」がマージされるのは正しい挙動ですが、自動ログイン状態でもマージされてしまうのは直感と反する挙動かと思います。

とはいえどういった挙動にするのが良いかはなかなかイメージできません。
どのように扱うのがいいでしょうか？

**Comment by hinto-Yamashita** [comment]
マージ内容が正しい挙動である事は理解いたしました。
しかしながら、直感ではカートに入っているものは、ユーザが意図した操作なく（ログインの意識があっても）
増減すべきではないと考えております。
そのような動作を行った際、ログインしたら同一商品はマージされず、差分は反映する挙動が良いと考えております。

**Comment by okazy** [comment]
ご意見ありがとうございます。

> ログインしたら同一商品はマージされず、差分は反映する挙動が良いと考えております。

例えば

- 現在のカート内：商品A 1個、商品B 1個
- ログアウト前のカート内：商品A 1個、商品C 1個

の場合に
「商品A 1個、商品B 1個、商品C 1個」
となるイメージであっていますでしょうか？

商品Aの個数がそれぞれ異なった場合にどちらを優先するのかなど仕様が複雑になってしまうかと思いました。

**Comment by okazy** [comment]
Issue のタイトルを変更させていただきました。

**Comment by hinto-Yamashita** [comment]
>例えば
>現在のカート内：商品A 1個、商品B 1個
>ログアウト前のカート内：商品A 1個、商品C 1個
>の場合に
>「商品A 1個、商品B 1個、商品C 1個」
>となるイメージであっていますでしょうか？
→その内容で直感的な認識には相違ございません。

**Comment by okazy** [comment]
関連 https://github.com/EC-CUBE/ec-cube/pull/3170

**Comment by okazy** [comment]
そもそも、 `IS_AUTHENTICATED_REMEMBERED` ログイン状態でもカートをDBと連動させた方がいいと思いました。

**Comment by okazy** [comment]
すみません、こちら間違いでした。。。
https://github.com/EC-CUBE/ec-cube/issues/4574#issuecomment-647378806

`IS_AUTHENTICATED_REMEMBERED` ログイン状態でもDBのカート情報と同期されています。
なので `IS_AUTHENTICATED_REMEMBERED` ログイン状態からのログイン時にはカートをマージする必要はありません。
なので自動ログイン状態でもマージされてしまうのは「直感と反する挙動」ではなく不具合ですね。。。

`SecurityEvents::INTERACTIVE_LOGIN` でカートをマージする処理があり、ここで `IS_AUTHENTICATED_REMEMBERED` ログイン状態からのログイン時にはマージしないようにできれば解決するかと思いますが、ここの処理で以前のログイン状態を判定するのは難しい気もします。
https://github.com/EC-CUBE/ec-cube/blob/321ed0849ce8d23a41ba9956a343d8efdf4ee29f/src/Eccube/EventListener/SecurityListener.php#L66
どう実装するのがいいのか・・・

**Comment by okazy** [comment]
@hinto-Yamashita 報告ありがとうございました。
#4756 で修正されましたのでクローズします。
