### ISSUE TITLE
複数配送時に在庫数が減らない

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4578]
## 概要(Overview)
配送先が2つで注文すると、1つの配送先分の在庫は減るが、もう1つの配送先分の在庫が減らない

## 期待する内容(Expect)  or 要望 (Requirement)
注文個数分の在庫が減る

## 再現手順(Procedure)
1. 管理画面の商品登録ページで在庫数5の商品を用意する
2. 用意した商品を5個カートに入れる
3. ご注文手続きで配送先を追加する
4. 配送先Aに3個、配送先Bに2個を振り分ける
5. 注文する
6. 管理画面の商品登録ページを確認すると、在庫数が3個になっている
　※合計5個注文しているので在庫数は0になるべき

### 環境 (environment)
+ EC-CUBE: 4.0.3

**Comment by okazy** [comment]
手元の環境で再現しました。こんな不具合が残っていたとは・・・

**Comment by chihiro-adachi** [comment]
#4588 で対応しました。
