### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4579]
## 概要(Overview)
PHP8 への対応

## 期待する内容(Expect)  or 要望 (Requirement)
PHP8 で問題なく運用できること

## 再現手順(Procedure)
- PHP8(nightly)で動作検証
  - https://travis-ci.org/github/nanasess/ec-cube/jobs/699940895

#### Doctrine DBAL にてシステムエラーが発生する
```
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $statement) in /home/travis/build/nanasess/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 70
```
DBAL 2.10.x では修正されていない
https://github.com/doctrine/dbal/blob/78de4498e4ff726bef21f5eb00781f39c0ffbc75/lib/Doctrine/DBAL/Driver/PDOConnection.php#L78

DBAL3.x では修正されている
https://github.com/doctrine/dbal/issues/4042
https://github.com/doctrine/dbal/pull/3803

### 環境 (environment)
+ EC-CUBE: 4.0.4
+ PHP: 8.0.0(nightly)
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
DBAL 2.x -> 3.x は結構影響ありそうですね。
EC-CUBE 4.x と一緒に検討が必要かと思います。

**Comment by nanasess** [comment]
PHP7.4 の EOL は 2022年11月末ですので、それまでに対応が必要そうです

**Comment by okazy** [comment]
Doctrine DBAL 2.12.x でPHP8に対応見込み。
Doctrine ORMは対応中(?)
https://github.com/EC-CUBE/ec-cube/issues/4603#issuecomment-720231282

4.1β時点では対応できない見込みのため、マイルストンをいったん `4.x` とさせていただきます。

**Comment by okazy** [comment]
DoctrineのPHP8対応ができたとしても、プラグイン側をPHP8対応する必要があり、単純には導入が難しい可能性がある。
利用している全てのライブラリがPHP8対応してくれないといけないので、すぐには難しい。

**Comment by chihiro-adachi** [comment]
#5353 で対応。
