### ISSUE TITLE
composer install時にDeprecation Notice

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4607]
## 概要(Overview)

composer install時に以下のnoticeがでてます。
ファイル名とクラス名が異なってるため。CustomerSortNoTrait.phpに変更するのが妥当かと思います。

```
Deprecation Notice: Class Plugin\EntityExtension\Entity\CustomerSortNoTrait located in ./app/Plugin/EntityExtension/Entity/CustomerRankTrait.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///Users/chihiro_adachi/.anyenv/envs/phpenv/versions/7.3.15/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

## 期待する内容(Expect)  or 要望 (Requirement)

上記Noticeがでなくなること。

## 再現手順(Procedure)

compser install もしくはcomposer dump-autoloadを実行

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
DBの予約後の関係でrankからsort_noへカラム名を変更した時のファイル名の修正漏れかと思います。
ファイル名の変更になるので、4.1のタイミングで修正できれば良いかと思いました。

**Comment by chihiro-adachi** [comment]
@okazy 

- サンプルプラグインなのでプロダクトコードには影響しない
- ファイル名とクラス名の不一致により現状動作していない

↑なので、4.1待たず直して良いかと思います。

**Comment by okazy** [comment]
同封されてるサンプルプラグインだったんですね、確認不足でした。確かに影響なさそうです。

**Comment by okazy** [comment]
4.1 に関しては以下のプルリクで解決しています。

https://github.com/EC-CUBE/ec-cube/pull/4963

4.0 も git cherry-pick などで対応しておきたい。

**Comment by chihiro-adachi** [comment]
#4963 で修正済のためクローズします。
