### ISSUE TITLE
OrderItemForShippingRegistrationType.php は使われていないので削除

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4609]
## 概要(Overview)

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Form/Type/Admin/OrderItemForShippingRegistrationType.php

`OrderItemForShippingRegistrationType.php` は使われていないように見えます。

## 期待する内容(Expect)  or 要望 (Requirement)

使われていない場合は削除
使われている場合は利用箇所が知りたい。

### 環境 (environment)
+ EC-CUBE: 4.0.4

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5681
