### ISSUE TITLE
検索エンジン用（xml）サイトマップ生成

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#4610]
## 概要(Overview)

SEO対策的にｍ検索エンジン用（xml）サイトマップを標準提供したい

## 期待する内容(Expect)  or 要望 (Requirement)

2系のsitemap.phpのように、サイトマップを生成したい
たぶん個別にやっている人も多そう

### 環境 (environment)
+ EC-CUBE: 4.0.x

## 関連情報 (Ref)

https://www.sitemaps.org/protocol.html

**Comment by okazy** [comment]
サイトマップ作成のプラグインが公開されています。
https://www.ec-cube.net/products/detail.php?product_id=1778

**Comment by matsuoshi** [comment]
こちらで対応されたためクローズします
https://github.com/EC-CUBE/ec-cube/issues/4610
