### ISSUE TITLE
複数配送時に在庫の処理が1件分しかされない不具合

### ISSUE THREAD

**Issue by kamotetu** [EC-CUBE/ec-cube#4612]
## 概要(Overview)
同じproductClassを複数配送すると在庫の減算処理に不具合がでる

## 期待する内容(Expect)  or 要望 (Requirement)
同じproductClassが回ってきたときに、stockを更新して正規の減算処理をしてほしい

## 再現手順(Procedure)
例えばチェリーアイスサンドを５個カートに追加->注文画面で配送先を追加、それぞれの配送先に2個3個と分割->注文確定->在庫の数がマイナス2か3されている

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - MySQL x.x.x

**Comment by Yangsin** [comment]
ご報告ありがとうございます。タイトルを修正させていただきました。
また、以下のPull Requestもありがとうございます。確認させていただきます。
https://github.com/EC-CUBE/ec-cube/pull/4611

**Comment by kamotetu** [comment]
よろしくお願いします！

iPhoneから送信

**Comment by chihiro-adachi** [comment]
#4588 で修正済のため、こちらはクローズさせていただきます。

@kamotetu 
ご確認ありがとうございました！
