### ISSUE TITLE
Twigで動的にしたブロックの追加

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#4623]
## 概要(Overview)

フロントエンドをメインに担当されているエンジニアを中心に
テンプレートだけであれこれしたいという要望をいただく
実際にある程度、Twigでできるが、サンプルとなるようなものが少ない

ドキュメントよりも、実際のデフォルトではいっているほうが助けになるだろうという点で
新着商品など、静的になっているブロックを
TwigだけでRepositoryからデータを出してきて動的にしたブロックを用意したい

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by nanasess** [comment]
#4698 の話題もあり、管理画面の権限奪取から可能な不正アクセスを広げてしまう懸念があるので、 Twig でできることは慎重に取捨選択した方がよいと思います

**Comment by chihiro-adachi** [comment]
コメントいただいたとおり、セキュリティ上の懸念から本Issueの採用は見送ります。
https://github.com/EC-CUBE/ec-cube/issues/4623#issuecomment-695522241
