### ISSUE TITLE
PHP-CS-FixerのCI化の検討

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4624]
## 概要(Overview)

PHPのコードの自動整形の仕組みとしてPHP-CS-Fixerが導入されているが、現在は手動で実行するしかなく、運用に乗っておらず長期間適応できていない状況です。

差分は以下のプルリクのように膨れ上がっています。
https://github.com/EC-CUBE/ec-cube/pull/4616

GitHub Actions を利用すれば自動でチェックやプルリクなども可能なので、人間の手間がかからない形で運用に乗せたいと思っています。

## 期待する内容(Expect)  or 要望 (Requirement)

以下のような対応が考えられます。
- 定期的にPHP-CS-Fixerを実行してプルリク or プッシュ
- プルリクのマージ時にPHP-CS-Fixerを実行してプルリク or プッシュ
- プルリクの作成時にPHP-CS-Fixerを実行してプルリクに対してプルリク

プルリクを作成する場合、不要なブランチが増えてしまいそうという懸念もあります。
一方でプロダクトブランチに自動pushするのはよくないと思います。

良い方法があれば教えてください。

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by nanasess** [comment]
php-cs-fixer の `--diff` でパッチを作れるので、 upload-artifact でパッチをアップロードしたら良さげですね

**Comment by okazy** [comment]
upload-artifact でファイルアップロードして、それを手動で適用する感じでしょうか？
人間がする作業増えたらまた滞るなと思いまして、プルリクまでしてしまいたいなと。。。

**Comment by nanasess** [comment]
> プルリクを作成する場合、不要なブランチが増えてしまいそうという懸念もあります。

ということなので、パッチをアップロードするだけなら Pull Request 増えない方法を考えましたが、 Pull Request で問題なければそれで良いと思います

**Comment by okazy** [comment]
ありがとうございます:pray:

**Comment by KentarouTakeda** [comment]
#4649 でエディタ（VSCode）上での自動化を提案させて頂きましたが、
それとは別で（VSCode + Remote Containers以外の環境も考慮し）

Git で commit 前に 自動でコマンドを実行する #Node.js #husky | Developers.IO
https://dev.classmethod.jp/articles/pre-commit/

この辺りの方法でcommit時に強制適用するのはいかがでしょうか。
node.jsは一部で既に使われているようなので、導入のハードルはそんな高くない気がします。

* 【メリット】[husky](https://www.npmjs.com/package/husky)であればフック `.git/hooks/` もpackage.json内で一元管理できます。
* 【メリット】npm install が行われた環境であればcommit時に強制的に適用されます。
* 【デメリット】commitする環境でphpが動作する必要がある（動作しない場合はフックを迂回する対応が必要となる）ため、絶対のものではありません。
* 【デメリット】ごく稀に php-cs-fixer では自動修正を行えないケースがあります。commit不可状態となってしまうためこの場合は次の何れかの対応が必要になります。
  * php-cs-fixerが対応できるようコードを修正する
  * `git commit --no-verify` で明示的にフックを迂回する

**Comment by okazy** [comment]
提案ありがとうございます！
commit 時に fixer が実行されるとすごく便利そうですね！

心配な点は２個あります。
- php/nodeが実行できない環境でcommitのハードルが上がってしまう。
特にnodeはCSSの生成でしか利用していないので、実行できない場合が結構あるかと思います。
実行に失敗した時に commit わざわざオプションをつけていただくのは難易度が高いと思いますので、実行できなければスキップしてcommitできるようにしたいです。

- cs-fixerの初回実行にはかなり時間がかかります。
今まで開発されていた方だと驚かれるのではないかと思いました。
実行中の表示を工夫すれば解決できるかもしれません。

**Comment by KentarouTakeda** [comment]
@okazy 
確認ありがとうございます！ご懸念の点は了解しました。
おそらく結論大丈夫だと思うので、一旦私の方でPR作ってみようと思います。

* node が実行できない環境  
    [husky](https://www.npmjs.com/package/husky) の時点でnode.jsが必要なので、ない場合はpre-commit-hook自体が呼ばれない。（何も起こらない）
* php が実行できない環境  
    フックの書き方で対応。（無い場合は何もせず成功を返すようにする）
* cs-fixer速度  
    commit対象のファイルに対してのみ適用するようにします。これで多分大丈夫だと思います。（一旦試してみます）
* 実行失敗のケース  
    了解です。どこまで厳密にやりたいか（ポリシー）の話だと思うので、それはそれでアリですね。

という感じで作ってみようと思うので少々お待ち下さい。（スレ違いぽい内容ですみませんでした！）

**Comment by okazy** [comment]
ご確認ありがとうございます！
いただいている内容で解決できそうですね！

**Comment by okazy** [comment]
#4661 にて commit 時に fixer を実行するようにしていただき、本 Issue の題意は満たされたかと思いますので、クローズします。
改善されないようであればまた Issue を立てて検討しましょう。
現在残っているソースコードの差分は 4.1 での開発の中で fixer をかけられたらと思います。
ご意見をいただきありがとうございました。
