### ISSUE TITLE
dtb_delivery_duration.duration の判定方法がおかしい

### ISSUE THREAD

**Issue by Uzurachan** [EC-CUBE/ec-cube#4644]
## 概要(Overview)
src/Eccube/Form/Type/Shopping/ShippingType.php の142行目辺りで

```ShippingType.php
...
                    if ($deliveryDuration->getDuration() < 0) {
                        // 配送日数がマイナスの場合はお取り寄せなのでスキップする
                        $deliveryDurationFlag = false;
                        break;
                    }
...
```

の条件があるが
そもそも `dtb_delivery_duration.duration` はマイナスの値を取らないので、判定方法としておかしい。

Eccube3で `dtb_delivery_duration.duration` に対応する `dtb_delivery_date.value` はマイナスの値を取るので
おそらくEccube3時代のロジックが残ってしまっている。

Eccube3からEccube4にデータ移行した場合
お取り寄せの `dtb_delivery_duration` を判定できなくなるので修正が必要。

## 期待する内容(Expect)  or 要望 (Requirement)
以下のように直す？

```ShippingType.php
...
                    if (preg_match('/^お取り寄せ*+/', $deliveryDuration->getName())) {
                        $deliveryDurationFlag = false;
                        break;
                    }
...
```

## 再現手順(Procedure)
\-

### 環境 (environment)
+ EC-CUBE: 4.0.3
+ PHP: 7.2.24
+ DB:
  - MySQL 5.7.30

**Comment by kiy0taka** [comment]
MySQLで発生する問題で #4405 により対応済みです。
4.0.4以上ではこの問題は発生しません。

**Comment by Uzurachan** [comment]
@kiy0taka ご教示ありがとうございます。
大変失礼致しました。。 助かりましたm(_ _)m
