### ISSUE TITLE
商品CSV登録時に商品説明等の改行が消える

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4647]
## 概要(Overview)
商品CSV登録時に商品説明等のCSVフィールド内改行が消える（項目内の最初の方のみ)

フロント表示時にはテンプレート内で改行をbrタグに変換しているので、
CSVエクスポート→再インポートすると表示が変わってしまう可能性あり。

CsvImportService.phpで \SplFileObject::DROP_NEW_LINEのオプションを外せば良いのかと思いますが、未確認です。

＜コミュニティより＞
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=24413&forum=11&post_id=99322

＜PHPのバグ報告＞
https://bugs.php.net/bug.php?id=69181

## 期待する内容(Expect)  or 要望 (Requirement)

改行が維持されたままデータベースに登録される

## 再現手順(Procedure)
CSV上で商品説明(詳細)の項目を"AAAA\nBBBB"として商品CSV登録を行う
→　改行コードが消えている

### 環境 (environment)
+ EC-CUBE: 4.0.4
+ PHP: 7.2

**Comment by chihiro-adachi** [comment]
#4942 で対応
