### ISSUE TITLE
VSCode Remote Containersを用いた開発

### ISSUE THREAD

**Issue by KentarouTakeda** [EC-CUBE/ec-cube#4649]
## 概要(Overview)

* 本リポジトリでは docker-compose.yml が配布されている（コンテナ開発環境が提供されている）が、これに対応する形で VSCode拡張機能 [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) との統合環境も提供したい。

又は

* VSCode上での環境構築は、プロジェクト毎の事情や開発者の好みにもされる可能性があるため上記設定は本リポジトリでは関知しない。この場合、設定ファイルを設置するディレクトリを丸ごと `.gitignore` で管理除外する対応が望ましい。

Remote Containers 拡張機能をセットアップするとプロジェクトのルートディレクトリに .devcontaner というディレクトリが自動的に作成されますが、このディレクトリが常に、gitからuntrackedとマークされた状態になります。これを解消したいです。

上記何れの方法を採るか（環境を提供するか、関知しないか）はプロジェクトによってマチマチのようですが、今回は前者の方法（環境を提供する）のが良いのではと個人的には思います。理由は下記のとおりです。

* docker-compose.yml が提供されている時点で、方針として前者寄り。
* VSCodeが自動的に生成する.devcontainers設定 （デフォルト設定）ではほぼ何も動作しない。  
    ディレクトリ設定やユーザー設定に関しては、全員がほぼ同じカスタマイズを行うことになる。
* .devcontainers を通じて利用する拡張機能やそのデフォルト設定も配布できる。  
    例えば [PHP-CS-Fixerの自動適用](https://qiita.com/yujiroarai/items/e3e41785f5037e825414#%E4%BF%9D%E5%AD%98%E3%81%97%E3%81%9F%E3%82%BF%E3%82%A4%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%A7%E6%95%B4%E5%BD%A2%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E8%A8%AD%E5%AE%9A) なども環境ごと配布できるので #4624 などは（Remote Containers上の開発に限っては）CIの時点でなくcommitの時点で解消できる。

## 期待する内容(Expect)  or 要望 (Requirement)

* VSCode Remote Container の設定ファイルをdocker-compose.ymlと共に配布する  
    （又は）
* VSCode Remote Container の設定ファイルは .gitignore でgit管理から除外しておく

### 環境 (environment)
* EC-CUBE: 4.0
* docker-compose
* Visual Studio Code

## 関連情報 (Ref)

#4624 PHP-CS-FixerのCI化の検討

Developing inside a Container using Visual Studio Code Remote Development
https://code.visualstudio.com/docs/remote/containers

VSCode Remote Containerが良い - Qiita
https://qiita.com/d0ne1s/items/d2649801c6f804019db7

**Comment by KentarouTakeda** [comment]
差し支えなければPRもこちらで作成します。
（方針や仕様の相談が必要かと思いまずはIssueにしました）

**Comment by kiy0taka** [comment]
@KentarouTakeda VSCode Remote Containerの設定があるPRを作っていただけると試せるのでぜひ設定ありの方を用意していただけるとありがたいです。

**Comment by KentarouTakeda** [comment]
レビュー＆マージありがとうございました！
