### ISSUE TITLE
HTMLの属性maxlengthがところどころ間違ってmax_lengthになっている

### ISSUE THREAD

**Issue by kazuyoshikakihara** [EC-CUBE/ec-cube#4657]
## 概要(Overview)

たとえば
src/Eccube/Form/Type/Front/CustomerLoginType.php の50行目近くなどで、

```
$builder->add('login_email', EmailType::class, [
    'attr' => [
        'max_length' => $this->eccubeConfig['eccube_stext_len'],
    ],
```

のようなtypoがあります。

## 期待する内容(Expect)  or 要望 (Requirement)

正しくは 'maxlength' ですね。

ざっと検索したところ、

- src/Eccube/Form/Type/Admin/LoginType.php
- src/Eccube/Form/Type/Front/CustomerLoginType.php
- src/Eccube/Form/Type/Front/ForgotType.php
- src/Eccube/Form/Type/Front/PasswordResetType.php

にあるようです。

**Comment by okazy** [comment]
確認しました。確かに該当のフォームの文字数制限が正しくできていないですね。

**Comment by Okkun555** [comment]
上記ファイルのtypo修正対応させていただきます！
OSS初参加のため至らぬ点ございましたら、ご指摘いただけますと幸いに存じます。

**Comment by okazy** [comment]
#4770 にて修正していただきましたのでこちらはクローズさせていただきました。ありがとうございました。
