### ISSUE TITLE
コンテンツ管理＞ページ管理の編集対象にお問い合わせ(確認ページ)を加える

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4662]
## 概要(Overview)
コンテンツ管理＞ページ管理にて、確認ページが編集対象となっていないため、
デザインを調整する際や、テンプレート調整が必要なプラグインの場合、
管理画面から適用出来ない状態となっている。

## 期待する内容(Expect)  or 要望 (Requirement)
コンテンツ管理＞ページ管理から、お問い合わせ(確認ページ)のテンプレートの変更が出来る。

## 関連
【EC-CUBE4】コンテンツ管理＞ページ管理の編集対象に会員登録(確認ページ)を加える
https://github.com/EC-CUBE/ec-cube/issues/4318

**Comment by chihiro-adachi** [comment]
#4433
