### ISSUE TITLE
リリースした 4.0.4 の ログレベルは DEBUG

### ISSUE THREAD

**Issue by havill** [EC-CUBE/ec-cube#4668]
## 概要(Overview)
4.0.4 ダウンロード版のでログレベルは、DEBUG に設定されているから、毎日の site-YYYY-MM-DD.log　ファイルがアイドル状態のサーバーでも非常に大きくなってしまっています。

あまり忙しくないサーバーでも毎日１００MB以上になっています。

「システム設定」の「ログ表示」でも表示できないほど（PHPの規定最大メモリ設定のために処理を完了しないでエラー）。

## 期待する内容(Expect)  or 要望 (Requirement)

DEBUGよりERRORレベルまたはWARNINGレベルに設定すれば良いです。

### 環境 (environment)
+ EC-CUBE: 4.0.4
+ 7.4.9 (Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, apcu, curl, intl, zip, mysqlnd, PDO, xml, calendar, ctype, dom, mbstring, FFI, fileinfo, ftp, gettext, iconv, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, Phar, Zend OPcache)
+ DB:
  - MySQL 5.7.25-google-log

## 関連情報 (Ref)

app/config/eccube/packages/prod/monolog.yml

```monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: main_rotating_file
        main_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/site.log'
            formatter: eccube.log.formatter.line
            level: debug
        front:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: front_rotating_file
            channels: ['front', 'app', 'php']
        front_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/front.log'
            formatter: eccube.log.formatter.line
            level: debug
        admin:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: admin_rotating_file
            channels: ['admin', 'app', 'php']
        admin_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/admin.log'
            formatter: eccube.log.formatter.line
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']```

**Comment by watarukashii** [comment]
@havill  こんにちは、本件、下記にてプルリクエストの承認をいただきました。
問題なさそうであればissue クローズの程よろしくおねがいします。
https://github.com/EC-CUBE/ec-cube/pull/5322
