### ISSUE TITLE
管理ツールの受注詳細ページで商品追加時に商品コードを入れるとエラーになる

### ISSUE THREAD

**Issue by yoshiaki-natsume** [EC-CUBE/ec-cube#4678]
## 概要(Overview)

管理ツールの受注詳細ページで商品追加時に商品コードを入れると
`search product failed.`
というアラートが出てきて商品の追加が出来ません

## 期待する内容(Expect)  or 要望 (Requirement)

商品コードを入力した場合も正常に追加対象の商品が登録できるようになる

## 再現手順(Procedure)

管理ツールより
受注一覧→受注データを選択→商品を追加→検索boxに存在する商品コードを入力して検索すると
`search product failed.`
というアラートが出てくる

### 環境 (environment)
+ EC-CUBE: 4.0.0
+ PHP: 7.2.9
+ DB:
  - MySQL 5.7.x

**Comment by okazy** [comment]
@yoshiaki-natsume 

以下の環境でテストをして見ましたが再現しませんでした。

- EC-CUBE: 4.0.5-rc
- PHP: 7.4
- DB:
  - MySQL 5.7

問題の箇所は以下の画像の箇所であっていますか？

![image](https://user-images.githubusercontent.com/16895409/91683304-34636000-eb8f-11ea-8dcc-219a10d7dd16.png)

**Comment by yoshiaki-natsume** [comment]
すいません、問題の箇所はあっていますが前提条件で商品規格の用意に条件がありました。

1. 商品規格の「規格１」のみ設定された商品があり、かつ商品規格に異なる商品コードが設定されている。
（例：商品コード=AAA111, AAA123, AAA999) [1]
2. 受注データ編集画面の「商品を追加」で上記の商品規格の中の一部の商品コードと部分一致する検索文字列を入力して検索する。
（例： 検索文字列=AAA9） [2]
（例： 検索文字列=AAA1） [3]
なお、全ての商品規格の商品コードと部分一致する場合はエラーにならない。
（例：検索文字列=AAA）[4]

[1]
![product_class](https://user-images.githubusercontent.com/30715900/91807076-1d903c80-ec67-11ea-8b95-5236e0ce47ed.png)
[2]
![fail1](https://user-images.githubusercontent.com/30715900/91807118-1ff29680-ec67-11ea-9fee-d2f1e884cb18.png)
[3]
![fail2](https://user-images.githubusercontent.com/30715900/91807139-21bc5a00-ec67-11ea-9d84-c71e121d0d65.png)
[4]
![success](https://user-images.githubusercontent.com/30715900/91807159-22ed8700-ec67-11ea-9682-5b1e19560a3d.png)

**Comment by izayoi256** [comment]
4.0.4にて再現しました。 [refs](https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22869&forum=9)

@okazy
Doctrineの動作を詳細に追った訳ではありませんが、商品規格に関する条件をEXISTSで指定する必要がありそうです。
https://github.com/EC-CUBE/ec-cube/blob/925e1f69572031cf7e461ecac2a743c908a53112/src/Eccube/Repository/ProductRepository.php#L228-L237

``` php
// 正常に動作したコード
        if (isset($searchData['id']) && StringUtil::isNotBlank($searchData['id'])) {
            $id = preg_match('/^\d{0,10}$/', $searchData['id']) ? $searchData['id'] : null;
            $expr = $qb->expr();
            $orX = $expr->orX();
            $subQuery = $this->getEntityManager()->createQueryBuilder();
            $subQuery
                ->select('pc2')
                ->from(ProductClass::class, 'pc2')
                ->andWhere('p.id = pc2.Product')
                ->andWhere('pc2.code LIKE :likeid');
            $orX->add('p.id = :id');
            $orX->add('p.name LIKE :likeid');
            $orX->add($expr->exists($subQuery));
            $qb
                ->andWhere($orX)
                ->setParameter('id', $id)
                ->setParameter('likeid', '%'.str_replace(['%', '_'], ['\\%', '\\_'], $searchData['id']).'%');
        }
```

**Comment by izayoi256** [comment]
解決策は見当もつかないのですが、原因となる箇所はおよそ把握できたので報告します。

https://github.com/EC-CUBE/ec-cube/blob/dc27cb56697f2a02a7950d0a12cdc9983aa0d6a3/src/Eccube/Repository/ProductRepository.php#L219

上記にて商品規格(pc)がSELECTに追加されていて、コミットログを見るとこれはN+1問題への対応のようです。
この状態で`WHERE pc.code = 'hoge'`と指定して検索すると、結果の`Product::$ProductClasses`には、商品コードがhogeの商品規格のみがセットされます。

https://github.com/EC-CUBE/ec-cube/blob/dc27cb56697f2a02a7950d0a12cdc9983aa0d6a3/src/Eccube/Repository/ProductRepository.php#L69

その後、上記にて再度商品規格(pc)をSELECTに追加して検索することで、商品コードがhoge以外の商品規格を検索する際に、DoctrineのObjectHydratorがうまく値を取れずエラーが発生する…みたいです。

単純にエラーが発生しないようにするだけなら、下記のいずれかの方法で対応が可能です。
- `ProductRepository::findWithSortedClassCategories()`内の`->addSelect(...)`を削除する。
- `ProductRepository::getQueryBuilderBySearchDataForAdmin()`内の`->addSelect(...)`を削除する。
- `ProductRepository::getQueryBuilderBySearchDataForAdmin()`内の商品規格に関する条件をEXISTS句に変更する。

ちなみに商品管理画面で商品コードを指定して検索すると、

> この状態で`WHERE pc.code = 'hoge'`と指定して検索すると、結果の`Product::$ProductClasses`には、商品コードがhogeの商品規格のみがセットされます。

この現象が確認できたので併せて画像にて報告しておきます。(上はaddSelectあり、下はaddSelectなし)

![addSelectあり](https://user-images.githubusercontent.com/1329505/93310771-288ac580-f840-11ea-9244-e179adff2165.png)
![addSelectなし](https://user-images.githubusercontent.com/1329505/93310773-29bbf280-f840-11ea-93a7-0953fbfc565f.png)

**Comment by okazy** [comment]
#4695 で修正されましたのでクローズします。
ご報告、調査、ご意見ありがとうございました。
