### ISSUE TITLE
Class LocaleNotFoundException not defined

### ISSUE THREAD

**Issue by l2dy** [EC-CUBE/ec-cube#4683]
## 概要(Overview)
LocaleNotFoundException is not imported.

https://github.com/EC-CUBE/ec-cube/blob/0d6b6e80b677beb79d0e6ce66f14335995a9793c/src/Eccube/DataCollector/EccubeDataCollector.php#L116

## 期待する内容(Expect)  or 要望 (Requirement)
e.g.

```php
use Sylius\Component\Locale\Context\LocaleNotFoundException;
[...]
```

### 環境 (environment)
+ EC-CUBE: 4.0.4
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
Thanks for your report!
Certainly no `LocaleNotFoundException` has been imported.
I think it's a remnant of the Sylius process that was used as a reference.
I don't think it's enough to implement `LocaleNotFoundException`, so I think it should be changed to `Exception`.

**Comment by okazy** [comment]
It is fixed in # 4714 and closed. Thank you.
