### ISSUE TITLE
log_error argument mismatch

### ISSUE THREAD

**Issue by l2dy** [EC-CUBE/ec-cube#4684]
## 概要(Overview)
`log_error` expects 2 arguments.

https://github.com/EC-CUBE/ec-cube/blob/0d6b6e80b677beb79d0e6ce66f14335995a9793c/src/Eccube/Resource/functions/log.php#L38-L44

But the following calls pass 3 arguments to it.

https://github.com/EC-CUBE/ec-cube/blob/0d6b6e80b677beb79d0e6ce66f14335995a9793c/src/Eccube/Controller/Admin/Customer/CustomerDeliveryEditController.php#L147
https://github.com/EC-CUBE/ec-cube/blob/0d6b6e80b677beb79d0e6ce66f14335995a9793c/src/Eccube/Controller/Admin/Customer/CustomerController.php#L248

## 期待する内容(Expect)  or 要望 (Requirement)
Remove the extra argument.

### 環境 (environment)
+ EC-CUBE: 4.0.4
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
Thanks for your report!
It would certainly be a correct to remove the third argument.

**Comment by okazy** [comment]
It is fixed in # 4715 and closed.
