### ISSUE TITLE
システム要件

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#47]
取り急ぎ把握したいのは、PostgreSQL のバージョンなのですが、諸々どこかにまとまっていましたっけ?

**Comment by Yangsin** [comment]
まだまとめれてはいません。
現在、ホスティングなどにも実態をヒアリングしており、近日中に決定させていただきます。
PHPについては、5.4～、Postgresqlについては、8.3～程度で想定しております。

**Comment by seasoftjapan** [comment]
了解です。ありがとうございます。
