### ISSUE TITLE
画像アップロード可能な拡張子に WebP を追加する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4700]
## 概要(Overview)

商品画像などで使用可能な拡張子は 'gif', 'jpg', 'jpeg', 'png' に限定されているが、これに **WebP** を追加する

## 期待する内容(Expect)  or 要望 (Requirement)

WebP の画像をアップロードできる

## 再現手順(Procedure)

WebP の画像をアップロードする

### 環境 (environment)
+ EC-CUBE: 4.0.5
+ PHP: 7.4.10

**Comment by xuelian311** [comment]
WebP対応済みであるため、クローズいたします。
