### ISSUE TITLE
受注登録画面で商品追加時、規格が登録されすべての規格の在個がゼロの時、+ボタンを押すとjavascriptエラー

### ISSUE THREAD

**Issue by belltzel** [EC-CUBE/ec-cube#4702]
## 概要(Overview)
特定の条件で商品追加時にjavascriptエラーが出る。

原因としては、すべての在庫がゼロの時は、規格のselectboxを作成しない為、規格が無い商品と判定され、[ここ](https://github.com/EC-CUBE/ec-cube/blob/3bf980027d32b336c33f38aef3f4f1f57f9cacd7/src/Eccube/Resource/template/admin/Order/search_product.twig#L60)でエラーとなる。

## 期待する内容(Expect)  or 要望 (Requirement)
在個がゼロの場合は+ボタンの表示を「品切れ中」と表示する。

## 再現手順(Procedure)
**規格を登録して、無制限のチェックを外し、在庫数をゼロで登録する。**
![01](https://user-images.githubusercontent.com/48919150/94226815-85b70300-ff33-11ea-85c4-864b5a37858e.png)

**管理画面の受注登録で商品追加ボタンを押す。**
**商品を検索し、+ボタンを押す。**
![02](https://user-images.githubusercontent.com/48919150/94226889-b6973800-ff33-11ea-92cd-cf660849c15a.png)

**javascriptエラーがでる。**
![03](https://user-images.githubusercontent.com/48919150/94226928-d0d11600-ff33-11ea-8472-4e97615f8939.png)

### 環境 (environment)
+ EC-CUBE: 4.0.5
+ PHP: 7.4.9
+ DB:
  - MySQL 5.7.28

**Comment by okazy** [comment]
報告ありがとうございます。
#4704 で修正されましたのでクローズします。
