### ISSUE TITLE
受注管理＞受注検索のお名前、注文者名検索のロジック修正

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4716]
## 概要(Overview)
■受注一覧
検索窓から氏名で検索すると、スペースの有り無しに関わらずヒットしない。
「詳細検索」から同じ名前を入力するとヒットする。（スペースありではヒットしない）

■会員一覧
スペースあり（半角、全角）、なしいずれでも検索ヒットする。

## 期待する内容(Expect)  or 要望 (Requirement)
受注検索も、会員検索と同様の検索ロジックとする。

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
検索して見ました。ロジックは見てません。

|ラベル|form|パターン|可否|
|----|----|----|----|
|注文番号・お名前・会社名・メールアドレス・電話番号|admin_search_order[multi]|姓|可|
|注文番号・お名前・会社名・メールアドレス・電話番号|admin_search_order[multi]|名|可|
|注文番号・お名前・会社名・メールアドレス・電話番号|admin_search_order[multi]|姓名|不可|
|注文番号・お名前・会社名・メールアドレス・電話番号|admin_search_order[multi]|姓 名|不可|
|注文者名|admin_search_order[name]|姓|可|
|注文者名|admin_search_order[name]|名|可|
|注文者名|admin_search_order[name]|姓名|可|
|注文者名|admin_search_order[name]|姓 名|不可|
|会員ID・メールアドレス・お名前|admin_search_customer[multi]|姓|可|
|会員ID・メールアドレス・お名前|admin_search_customer[multi]|名|可|
|会員ID・メールアドレス・お名前|admin_search_customer[multi]|姓名|可|
|会員ID・メールアドレス・お名前|admin_search_customer[multi]|姓 名|可|

不可のところも検索可能とするのが親切かと思いました。

**Comment by morry48** [comment]
上記、当方で対応可能ですので、修正対応させていただきます。

**Comment by okazy** [comment]
#4766 にて修正していただきましたのでこちらはクローズします。ありがとうございました。
