### ISSUE TITLE
Member Entity拡張後に特定の操作をすると管理画面にログインできなくなる

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/ec-cube#4725]
## 概要(Overview)
Member Entity拡張後に特定の操作をすると管理画面にログインできなくなりました。

## 期待する内容(Expect)  or 要望 (Requirement)

ログインできるようにしたい。

## 再現手順(Procedure)

1. Entity拡張する
2. 管理画面 -> メンバー管理 -> ユーザーの修正をする
3. その後、他のページを表示しようとするとエラーが発生する

> "There is no user provider for user \"Proxies\\__CG__\\Eccube\\Entity\\Member\". Shouldn't the \"supportsClass()\" method of your user provider return true for this classname?"

おそらく、以下の箇所でセットしたMemberオブジェクトが「Eccube\Entity\Member」ではなくProxyで生成されたオブジェクトになっているからでは？

https://github.com/EC-CUBE/ec-cube/blob/62f730f4a64c8a1aacbc1cda36dd530a520c665d/src/Eccube/Controller/Admin/Setting/System/MemberController.php#L207

以下の箇所をMemberのサブクラスであればtrueを返すように修正したら、エラーは解消した。
> return Member::class === $class || is_subclass_of($class,Member::class);

https://github.com/EC-CUBE/ec-cube/blob/62f730f4a64c8a1aacbc1cda36dd530a520c665d/src/Eccube/Security/Core/User/MemberProvider.php#L89

### 環境 (environment)
+ EC-CUBE: 4.0.4 , 4.0.5
+ PHP: 7.3.22
+ DB:
  - MySQL 5.7

## 関連情報 (Ref)

https://github.com/symfony/symfony/issues/35435

**Comment by okazy** [comment]
@sw-satoshi-nakano 

以下の手順で動作確認してみましたが、ログインできなくなる事象は確認できませんでした。
どこか手順が間違っていますでしょうか？

> 1. Entity拡張する

`app/Customize/Entity/MemberTrait.php` ファイルを作成

```php
<?php

namespace Customize\Entity;

use Eccube\Annotation\EntityExtension;

/**
 * Trait MemberTrait
 * @package Customize\Entity
 *
 * @EntityExtension("Eccube\Entity\Member")
 */
trait MemberTrait
{
    public $role;
}
```

proxy作成

```
bin/console e:g:p
gen -> /Users/hideki_okajima/temp/20201007/ec-cube-doc/app/proxy/entity/src/Eccube/Entity/Member.php
```

> 2. 管理画面 -> メンバー管理 -> ユーザーの修正をする

メンバー管理にてログイン中のメンバーの「名前」と「ログインID」を変更

> 3. その後、他のページを表示しようとするとエラーが発生する

管理画面ログアウト、ログイン

**Comment by sw-satoshi-nakano** [comment]
@okazy 
ご確認ありがとうございます。
再度、再現方法を詳細に確認しご提示いたします。
少しお時間をいただけないでしょうか。

**Comment by okazy** [comment]
ありがとうございます。

**Comment by sw-satoshi-nakano** [comment]
@okazy 

どうやらtraitで拡張したことが直接の原因では無いようでした。
以下のdoctrineのキャッシュファイルが出来た時に問題が発生することはわかりましたが、このファイルが出来るタイミングとメカニズムがよくわらず、原因の特定ができておりません。
このファイルはどういったことをすると出来るのか、ご存じでしたら教えてください。

var/cache/[dev or prod]/doctrine/orm/Proxies/__CG__EccubeEntityMember.php

**Comment by okazy** [comment]
@sw-satoshi-nakano 
すみません、私もまだ理解できていないのですが、一旦わかったことを共有です。
#2546 にてproxyの生成についての調整が入っています。
インストール時に「Traitは利用されないがカラムは追加される」という状態になっており、この際に内部的に利用されているキャッシュではないかと思います。

処理 | Plugin | Trait | カラム |  
-- | -- | -- | -- | --
インストール | 無効 | 利用されない | 追加 | Proxyは再生成されないスキーマは更新される

**Comment by okazy** [comment]
上記、動作を検証しましたが、EC-CUBEの独自実装のProxyはシステムの一時ファイル( `/var/folders/ハッシュ/proxy_ハッシュ/src/Eccube/Entity/Product.php` )に生成されていました。
`var/cache/[dev or prod]/doctrine/orm/Proxies/__CG__EccubeEntityMember.php` はDoctrine自体のProxy機構およびキャッシュではないかと思います。

**Comment by sw-satoshi-nakano** [comment]
いただいた情報をもとに探ってみます。
ありがとうございます。

**Comment by okazy** [comment]
@sw-satoshi-nakano 
こちらの問題のようですね。
https://github.com/symfony/maker-bundle/pull/532

Doctrineを利用している場合にマイナーバージョンアップでも問題が発生しているようでした。
プルリクでいただいている変更内容で問題ないようです。

ドキュメントも修正されていますね。
https://github.com/symfony/symfony-docs/pull/14304

**Comment by sw-satoshi-nakano** [comment]
意図的に同じ状況を作ってエラーを発生させることが出来ずモヤモヤしておりますが、Symfonyの仕様に対応した。ということで納得することにします。ご対応ありがとうございました。
