### ISSUE TITLE
プラグインの composer.json から require ec-cube/plugin-installer: "~0.0.6" を削除

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4734]
本来は ec-cube/plugin-installer の issues かもしれませんが、プラグイン開発者などにも影響があるため、EC-CUBE本体の issues としておきます

## 概要(Overview)
現在、 EC-CUBE 本体とプラグインの composer.json に `require ec-cube/plugin-installer: "~0.0.6"` が設定されており、二重定義となっている。

公式ドキュメントにはプラグインの composer.json に必ず記述が必要とある
https://doc4.ec-cube.net/plugin_spec#composerjson

require が存在しないプラグインがエラーとなる issues は解決している模様
https://github.com/EC-CUBE/ec-cube/issues/3918

本体が依存している plugin-installer が 0.0.8 未満(EC-CUBE4.0.2以下)だと問題があるが、0.0.8 以降であれば無くても問題ない？
https://github.com/EC-CUBE/eccube-plugin-installer/releases/tag/0.0.8

プラグイン側で記述が必要なケースは、**本体側が 0.0.6 の時に、プラグイン側は 0.0.8 を利用したい場合など** に限られると思われる

## 期待する内容(Expect)  or 要望 (Requirement)

composer2.0 に対応するにあたり、各プラグインに 以下のような記述をしてもらうのはつらいなということで、可能であれば無くても大丈夫な状態にしたい
```json
  "require": {
    "ec-cube/plugin-installer": "~0.0.6 || ^2.0@dev"
   }
```

## 再現手順(Procedure)

プラグインの composer.json から `require ec-cube/plugin-installer` を削除する

### 環境 (environment)
+ EC-CUBE: 4.0.5
+ PHP: 7.4.10

## 関連情報 (Ref)

- #3918 
- #4712

**Comment by chihiro-adachi** [comment]
プラグイン側に require ec-cube/plugin-installer の設定をしてもらった方が安全と思われるため、本issueはクローズします。
