### ISSUE TITLE
会員管理＞会員一覧 「購入商品名」での検索が購入に至っていない会員も対象になっている

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#4735]
## 概要(Overview)
会員管理＞会員一覧 「購入商品名」での検索が購入に至っていないデータも対象になっている
対応状況で判断していないため、購入処理中のまま残っている会員も対象になっている。

## 期待する内容(Expect)  or 要望 (Requirement)

少なくとも会員の受注が下記の対応状況の場合は検索対象になるべきではないのではないかと思います。
- 購入処理中
- 決済処理中

下記は賛否両論あると思いますが、個人的には対象で良いのかなと思います。
- 注文取消し
- 返品

## 再現手順(Procedure)
1. 新規会員登録
2. ログインした状態でカートに商品Aを入れ注文画面まで進む(実際に注文はしない)
3. 会員管理＞会員一覧で購入商品名＝商品Aで検索する
→ 登録した会員が検索にヒット

## 関連情報 (Ref)

メルマガプラグインがCustomerRepository::getQueryBuilderBySearchDataを使用しています
そのため同様に「購入商品名」で絞り込んでも購入していない会員へメルマガを送ってしまうという問題が発生しています。

**Comment by okazy** [comment]
確かに購入が完了していない受注が対象になるのは仕様として違和感がありますね。
検索の対象とする受注ステータスは提案いただいているもので問題ないかと思います。

**Comment by okazy** [comment]
#4751 で修正していただきましたのでクローズします。ご提案ありがとうございました！
