### ISSUE TITLE
オーナーズストア→プラグイン→プラグインを探す、プラグイン一覧では 4.0.x 対応と 4.1.x 対応を混在させない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4738]
## 概要(Overview)

Composer2.0 及び、 Symfony4.4 の対応に伴い、プラグインに若干の改修が必要になるため、
- EC-CUBE4.0.x では **4.1.x 以降対応のプラグインは動作しなくなる**
- EC-CUBE4.1.x では **4.0.x のみ対応のプラグインは動作しなくなる**

現状、混在して表示してしまうため、エラーが発生し、インストールできないプラグインが表示されてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)

- EC-CUBE4.0.x では **4.1.x 以降対応のプラグインは表示しない**
- EC-CUBE4.1.x では **4.0.x のみ対応のプラグインは表示しない**
- EC-CUBE4.1.x では **4.0.x と 4.1.x 両方に対応するプラグインは表示する**

## 再現手順(Procedure)

#4724 を取り込んで、オーナーズストア→プラグイン→プラグインを探す、プラグイン一覧を表示する

### 環境 (environment)
+ EC-CUBE: experimental/symfony4.4 branch
+ PHP: 7.4.10
+ mock-package-api:composer2

## 関連情報 (Ref)

- https://github.com/EC-CUBE/ec-cube/issues/4603
- https://github.com/EC-CUBE/ec-cube/issues/4737

**Comment by okazy** [comment]
4.0.x(Composer1) 対応と 4.1.x(Composer2) 対応で package-api のエンドポイントを分けることで対応しました。
明示的に設定変更をされる場合は環境変数で変更可能です。

4.0.x(Composer1) 対応
```
ECCUBE_PACKAGE_API_URL=https://package-api.ec-cube.net
```

4.1.x(Composer2) 対応
```
ECCUBE_PACKAGE_API_URL=https://package-api-c2.ec-cube.net
```

**Comment by okazy** [comment]
解決済みのためクローズします。
