### ISSUE TITLE
docker-compose環境の標準DBをSQLiteにし、MySQL/Postgresはオプションにする

### ISSUE THREAD

**Issue by m-pyon23** [EC-CUBE/ec-cube#4757]
## 概要(Overview)
docker-composeで環境を構築するとmysqlとpostgresの2つのDBが立ち上がるようになっているが、特に両方立ち上げる意味がなく、開発環境への無駄な負荷になる。

~~一方は記述を削除してもよいのではないか？~~

開発環境はsqliteでも十分なため、mysql/postgresはオプションにする（コメント欄参照）

## 期待する内容(Expect)  or 要望 (Requirement)

- docker-compose.ymlのservicesから、mysql/postgresのブロックを削除する

- mysql/postgres向けはオプションとしてdocker-compose-xxxx.ymlのような形の環境を用意する

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
#4391

**Comment by nanasess** [comment]
標準は SQLite にして、両方オプションでよいかなと思います

**Comment by m-pyon23** [comment]
#4391 時点では、なんとなくmysqlとpostgres両方の手順がドキュメントにあったので両方盛り込んでしまっていたのですが、使えば使うほど両方立ち上げる意味がないと感じました…

開発環境としてはsqliteでも充分ですし、mysqlやpostgresを使いたい方向けにはdocker-compose-mysql.yml、docker-compose-postgres.ymlのようなオプションを用意する形で提供するのはどうでしょうか

**Comment by m-pyon23** [comment]
> 標準は SQLite にして、両方オプションでよいかなと思います

コメント作成中にリプライいただいておりました…！

また、本体開発だと仕様の変更などはメジャーバージョンリリースにあわせるなど必要ですが、本件のように開発環境を立てる手順が少し変わる、というような内容については多少カジュアルに考えてしまってもよいでしょうか？
（もちろんその辺の最終的なジャッジは各種影響を考えた上でメンテナーの方にしていただけるとは思うのですが）

**Comment by kiy0taka** [comment]
今回のような内容であれば、カジュアルに考えて頂いて大丈夫です。

docker-compose-(mysql| postgres).yml に +1 です。

**Comment by kiy0taka** [comment]
@m-pyon23 今回のような内容であれば、カジュアルに考えて頂いて大丈夫です。

docker-compose-(mysql| postgres).yml に +1 です。

**Comment by nanasess** [comment]
#4955 で対応してみました
