### ISSUE TITLE
ファイル管理で既に存在しているフォルダを作成した際の挙動

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4758]
## 概要(Overview)

既に存在しているディレクトリと重複するディレクトリを作成した際、エラーにはならずに成功のメッセージが表示される
既存のディレクトリが上書き、削除はされない。

エラーメッセージが表示されるほうがわかりやすいかも。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
#4889 で修正されましたのでクローズします。
