### ISSUE TITLE
レイアウトファイルに対しTemplateEventで介入を行った際の動作

### ISSUE THREAD

**Issue by KentarouTakeda** [EC-CUBE/ec-cube#4760]
## 概要(Overview)

`@admin/default_frame.twig` 及びそれを参照している管理画面配下の各画面、双方に対し
`TemplateEvent::addAsset()` を用いた介入を行った場合 `default_frame.twig` への介入のみが有効となり
個別画面への `addAsset()` が無効になります。こちらは想定された動作でしょうか？

* 管理画面配下の全画面に対して共通のSnippet/Assetを追加する
  `@admin/default_frame.twig` へ介入
* とは別で、個別の画面に対しても追加する。
  `@Template` で指定されている各画面の個別のテンプレートへ介入

という実装を行おうとしています。

## 期待する内容(Expect)  or 要望 (Requirement)

現在実装しようとしている要件において *双方の介入が有効となる* という動作を期待したのですが
レイアウトファイルに対する介入という実装がそもそもイレギュラーな気がするので
この辺りの仕様について確認させてください。

## 再現手順(Procedure)

```php
class DefaultFrameEvent implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            '@admin/default_frame.twig' => 'defaultFrame',
        ];
    }

    public function defaultFrame(TemplateEvent $event)
    {
        $event->addAsset('@admin/_event/default_frame.twig'); // 有効
    }
}
```

```php
class CustomerEditEvent implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            '@admin/Customer/edit.twig' => 'edit',
        ];
    }

    public function edit(TemplateEvent $event)
    {
        $event->addAsset('@admin/_event/Customer/edit.twig'); // 無効（DefaultFrameEventを無効化すると有効になる）
    }
}
```

### 環境 (environment)
+ EC-CUBE: EC-CUBE/ec-cube/tree/4.0
+ PHP: 7.4.12
+ DB:
  - PostgreSQL 13.0

**Comment by nanasess** [comment]
`default_frame.twig` への介入のほうがイレギュラーな気がするのですが、いかがでしょうか。
画面全体へ EventHandler を適用するのであれば、Symfony の Kernel Events を使用する方が適切な気がします。
https://symfony.com/doc/current/reference/events.html

**Comment by KentarouTakeda** [comment]
了解です。ありがとうございます。
「extendsを経由して複数のテンプレートに介入するのは不可」にて正しい動作、と理解しました。
（仰るとおり少々イレギュラーな実装をしようとしている自覚は確かにありました…）
Symfonyのリファレンスも感謝です。ありがとうございました！
