### ISSUE TITLE
【Symfony4.4対応】Eccube\Form\Extension の仕様変更への対応

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4763]
## 概要(Overview)

refs https://github.com/EC-CUBE/ec-cube/issues/4399

`getExtendedType()` が廃止されたため `getExtendedTypes()` を実装する必要がある。
4.1ブランチでは対応済み。
プラグインで利用されている場合には、 `getExtendedType()` は残しておいても問題ないので、 `getExtendedTypes()` を新しく追加していただく必要がある。

## 期待する内容(Expect)  or 要望 (Requirement)

4.1へのマイグレーションガイドに記載

### 環境 (environment)
+ EC-CUBE: 4.1

**Comment by chihiro-adachi** [comment]
マイグレーションガイドに記載済
https://doc4.ec-cube.net/update-40-41
