### ISSUE TITLE
ログインページで _failure_path を変更するとシステムエラーになる

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4772]
## 概要(Overview)
通常の操作では発生しないエラーですが、セキュリティ会社による脆弱性診断で指摘されました。

## 期待する内容(Expect)  or 要望 (Requirement)
条件分岐による処理を行うことで 500 Internal Server Error が発生しないようにする。

## 再現手順(Procedure)
デモサイトでも再現確認しました。

■再現手順
1. 未ログイン状態でカートに商品を入れて「次に進む」
2. /shopping/login ページでブラウザの開発者ツール等で _failure_path の値を適当な値 %00 などに変更する
3. 誤ったパスワード情報でログインを試みる
4. URLは /mypage/login に遷移するが、システムエラーが発生する

### 環境 (environment)
+ EC-CUBE 4.0.3〜5
+ PHP: 7.1.33
+ DB:
  - MySQL 5.7.28-log

**Comment by okazy** [comment]
#4917 で解決していただきましたのでクローズします。
