### ISSUE TITLE
Google Chromeの最新版（Mac)でpost時のページ遷移ができない。

### ISSUE THREAD

**Issue by aonuma-mori** [EC-CUBE/ec-cube#4785]
## 概要(Overview)

Google Chromeの最新版（Mac)でpost時のページ遷移ができない。Windowsなどの他のOSの検証はできていません。
動作を確認するとPOSTのリクエストができないようです。GETのリクエストは問題なく動作しています。Chromeを利用しているユーザーは多いと思うで解決策を模索しております。
FirefoxやOperaなどの他のブラウザーでは問題なく動作します。
類似した問題として、Webインストーラで画面遷移できないというものがありましたが、Webインストーラ以外のページ遷移でも問題がありました。
https://github.com/EC-CUBE/ec-cube/issues/4546
- SameSite by default cookies
- Cookies without SameSite must be secure
上記をEnableにすることでは解決できませんでした。

## 期待する内容(Expect)  or 要望 (Requirement)

(http(80)のアクセスで）
- 商品のカート追加ができる　
- WEBインストーラーが機能する
- 新規会員登録ができる
- ログインができる
- お問い合わせ送信ができる
- パスワードリセットができる
- カートに商品が入る

## 再現手順(Procedure)

Google Chromeの最新版 ver 87.0.4280.67でサブミイットの動作をすると、ページ遷移しない。（リクエストがおそらくできていない）

### 環境 (environment)

+ EC-CUBE: 4.0.5
+ PHP: 7.3.19-1~deb10u1
+ DB:
  - MySQL Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

## 関連情報 (Ref)

Google Chrome
バージョン: 87.0.4280.67（Official Build） （x86_64）
2020/12/03時点

**Comment by kiy0taka** [comment]
@aonuma-mori こちら確認しましたが、同じバージョンのChromeで問題なくPOSTできました。
何かPOSTを制御するChrome拡張等は入っていないでしょうか？
可能であれば拡張がない状態で動作確認していただけますか？

**Comment by aonuma-mori** [comment]
add-onをすべて削除してみましたが、状況は同じでした。引き続き調査してみます。

**Comment by aonuma-mori** [comment]
@kiy0taka
いろいろ試した中でSSL証明書をつけてみるとPOSTが可能になりました。(すべてのsubmit動作で問題なく動作しているようです。)　ちなみに開発用のDocker環境（localhost内）では問題がないようです。上記の現象は外のホスト（Google Cloud)に立てたVMインスタンスでGIPをもたせているものでhttpアクセスしているものになります。

**Comment by kiy0taka** [comment]
@aonuma-mori httpアクセスしたときのCookieに `secure` 属性がついていたりしないでしょうか？

**Comment by aonuma-mori** [comment]
@kiy0taka HttpOnlyは付いていましたが`secure`属性はついておりませんでした。この事象はChromeだけで起こるらしくFirefoxやOperaなどの他のブラウザーは現在のところ問題ありません。またApacheの動作するOSをDebian10とUbuntu16で試してみましたが同じ現象になったのでOSは無関係のようです。
ブラウザーに起因することのように見えます。
