### ISSUE TITLE
納品書に郵便番号が出力されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4792]
## 概要(Overview)

- 店舗所在地、お客様情報共に、郵便番号は出力されない
- 2系の納品書には出力されていた

## 期待する内容(Expect)  or 要望 (Requirement)

店舗所在地、お客様情報に郵便番号が出力される

## 再現手順(Procedure)

納品書出力する

### 環境 (environment)
+ EC-CUBE: 4.0.5
+ PHP: 7.4.5

## 関連情報 (Ref)

- #4652

**Comment by chihiro-adachi** [comment]
#5887 で対応
