### ISSUE TITLE
インターフェースのメッセージはハードコーディングです。

### ISSUE THREAD

**Issue by camilovietnam** [EC-CUBE/ec-cube#4798]
## 概要(Overview)
So many of the strings in ECCUBE are hard-coded (ハードコーディング), meaning you have to go manually one by one changing them if you want to use the translation feature. 

![2020-12-11-1607660463](https://user-images.githubusercontent.com/49581907/101861937-ceca3b00-3ba3-11eb-8ee7-39dcd3c354d2.jpg)

This means any attempt at internalization becomes way more taxing than simply changing the `messages.en.yaml` file, you have to actually go string by string, finding the hard-coded versions in the files and changing them to use the translations in the YAML file. 

## 期待する内容(Expect)  or 要望 (Requirement)
Template files should be using the strings from the translation files, not hard-coded values. 

### 環境 (environment)
+ EC-CUBE: 4.0.5

**Comment by tao-s** [comment]
@camilovietnam Maybe, You use packed zip file. Those Japanese texts in the package are converted when it packed.
Please checkout directly from github repository.

**Comment by okazy** [comment]
Thank you for your answer, tao-s.

This issue is now closed.
If you have additional questions, please reopen the issue with your comments or create another issue.
