### ISSUE TITLE
テーブル定義書・ER図

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#48]
2.13 では、2つありましたが、まとめた方が良いのかなと。

* docs\テーブル定義書(EC-CUBE2.13dev).xlsx
* docs\table_definition.xls

個人的には、前者は Excel 方眼紙で勝手が悪かったので、最近は後者を重宝しています。

今後の保守方針に関して、Excel 直書きなのか、ツール生成なのかといった当たりも明確にしたほうが良いように感じます。(docs\ER-D\README.md みたいに、なっていると分かりやすいですね。)

EC-CUBE 上の用語との差異も散見するので、統一していくのも必要かと考えます。

合わせて、html\install\sql\comment_set_pgsql_2.13.sql の保守も課題でしょうか。

#22 あたりとも関わりますかね。

**Comment by Yangsin** [comment]
#10 で行われているER図についてもこちらに移させていただきます。

**Comment by chihiro-adachi** [comment]
ER図については以下で管理しています。
https://github.com/EC-CUBE/eccube3-doc/tree/master/ER-D

※ERマスターで作成→エクセルは閲覧用として保存しています。
