### ISSUE TITLE
商品画像を削除すると、他の商品で使ってても画像が消える

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#4812]
## 概要(Overview)
例えば、hoge.jpgのを商品AとBで使用していて、Bでは表示させたくなくなった時にBからhoge.jpgを消すと、Aからもhoge.jpgが消えてリンクが切れた様になる。

## 期待する内容(Expect)  or 要望 (Requirement)
他の商品で使っている画像は消さない様に、削除する際にチェックして欲しい。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - MySQL x.x.x

**Comment by nanasess** [comment]
こちらを適用しても再現しますでしょうか？　https://github.com/EC-CUBE/ec-cube/pull/4767

**Comment by tao-s** [comment]
@nanasess お、ありがとうございます！
