### ISSUE TITLE
PDFのロゴ画像は空画像で良いのでは

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#4824]
## 概要(Overview)
わざわざ毎回変えないとEC-CUBEのロゴが表示されてしまって煩わしいという意見もあるので、デフォルトは空画像で良いのではと思います。

## 期待する内容(Expect)  or 要望 (Requirement)
ロゴ画像を空画像に置き換え。faviconもそうしたい。favicon変えるの忘れて公開してエライ目にあった。

### 環境 (environment)
+ EC-CUBE: 4.0.x

## 関連情報 (Ref)
https://twitter.com/ShinzoWithLinko/status/1346378837399990274?s=20

**Comment by Yangsin** [comment]
ファビコンもそうですが、空画像もあれなんでちょっと汎用的なカートっぽいロゴ作りましょうか
個人的にはEC-CUBEのロゴで納品書とどいたらちょっとうれし気持ちになります。
