### ISSUE TITLE
Google アナリティクスを使用できるようにしたい

### ISSUE THREAD

**Issue by yKazihara** [EC-CUBE/ec-cube#4837]
## 概要(Overview)
- 現状はコードを入力しブロックを配置する必要がある
- 管理画面でトラッキングIDを設定するだけで、GAを使えるようにしたい

## 期待する内容(Expect)  or 要望 (Requirement)
- 管理画面でトラッキングIDを設定し、GAで計測ができる

**Comment by dotani1111** [comment]
merge済みのため、クローズします。
