### ISSUE TITLE
メンテナンスモードで、管理者はショップを閲覧できるようにしたい

### ISSUE THREAD

**Issue by matsuoshi** [EC-CUBE/ec-cube#4839]
## 概要(Overview)
メンテナンス目的に、ストアを一般向けには非公開とし、管理者はページを閲覧できるようなモードがほしい
(現状もメンテナンスモードはあるが、管理者からもショップの閲覧ができない)

## 期待する内容(Expect)  or 要望 (Requirement)
以下のようなモードを用意する

- 一般ユーザはショップを閲覧できない (メンテナンス中などの画面が表示される)
- 管理者はショップを閲覧できる

## 関連情報 (Ref)
#4507

**Comment by yKazihara** [comment]
現在のメンテナンスモードとは別に、管理者のみがショップ閲覧を出来るモードについてIssueを立てました。
こちらは一旦クローズとさせていただきます。
#4954
