### ISSUE TITLE
管理画面のログイン履歴

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#4847]
## 概要(Overview)

管理画面へのログイン履歴が記録されるようにしたい

## 期待する内容(Expect)  or 要望 (Requirement)

アカウントの乗っ取りなどで、管理画面への不正なアクセスがあったかを知れるように
日時、IPアドレス、ブラウザーくらいを履歴としてのこしたい

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
ログイン履歴の保存先はログファイルとDBの２種類考えられる。
ログファイルでよければ今のログ管理機能を活用できるので比較的簡単に実装でそうです。
冗長化して利用されることを考えるとDBが無難かと思います。

**Comment by okazy** [comment]
議論の余地があること

### ユースケース

1.  不正アクセスの際に行動を追うために
2.  複数のアカウントを発行しているサイトで、管理ユーザが行動を調べるため
3. 複数のユーザの行動の競合を回避したい

(2), (3) は別のIssue #4946 として対応する

### ログイン失敗の履歴も必要か？

### ログを消す機能は必要か？

**Comment by okazy** [comment]
#4978 で対応いただきましたのでこちらはクローズします。
ご対応ありがとうございました。
