### ISSUE TITLE
商品登録ページの画像削除でtemp画像を削除していない

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/ec-cube#4848]
## 概要(Overview)
商品登録ページの画像の登録では複数の画像を登録できる機能を持っているが、
画像をアップロード後、登録ボタンを押さないままアップロードした画像を削除すると、
登録ボタンを押しても、eccube_save_image_dir内のファイルを削除しようとする。

## 期待する内容(Expect)  or 要望 (Requirement)
temp画像を削除する場合は、eccube_temp_image_dir内を削除し、
DB登録済み画像を削除する場合は、eccube_save_image_dir内を削除するように条件分岐処理を追加する。

## 再現手順(Procedure)
1. 画像ファイルを選択
2. アップロードされた画像ファイルをXを押して削除
3. 登録ボタンを押下

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
#4935 にて修正していただきましたのでクローズします。
ご協力ありがとうございました。
