### ISSUE TITLE
管理画面へのログインで二要素認証を導入したい

### ISSUE THREAD

**Issue by matsuoshi** [EC-CUBE/ec-cube#4850]
## 概要(Overview)

セキュリティの観点から、管理画面へのログインは、ID/パスワード方式だけでなく、二段階認証も導入できるようにしたい

## 期待する内容(Expect)  or 要望 (Requirement)

管理画面へのログイン時に、

- メールによるワンタイムパスワード
- Google Authenticator などのスマホアプリ

などを用いた、2段階認証を利用できるようにする

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by sw-satoshi-nakano** [comment]
弊社で開発したプラグインのソースコードを提供することが可能です。
4.1で実装されるようであれば、プルリクでコードを提供しますので、お知らせください。

taba secure 2段階認証 プラグイン for EC-CUBE 4
https://www.ec-cube.net/products/detail.php?product_id=1750

**Comment by yKazihara** [comment]
@sw-satoshi-nakano さま
お返事が大変遅くなり申し訳ありません。4.1説明会でブレイクアウトセッションで弊社足立とご一緒させていただきましたかじはらです。
プルリクでのコード提供のお申し出、大変ありがたいです！
何卒よろしくお願いいたします。

**Comment by sw-satoshi-nakano** [comment]
@yKazihara さま

先日はありがとうございました。
承知いたしました。
4月中を目途にプルリクを出させていただきます。
よろしくお願いいたします。

**Comment by yKazihara** [comment]
@sw-satoshi-nakano さま
ありがとうございます！
よろしくお願いいたします。

**Comment by sw-satoshi-nakano** [comment]
@okazy 

質問がございます。
PRを4.1-featureブランチに対して行おうと思いましたが、4.1-featureが4.1の最新ソースコードが反映されていないようです。どのブランチで機能追加開発してPRを出すのが良いのでしょうか？

**Comment by okazy** [comment]
@sw-satoshi-nakano 
ご対応ありがとうございます。
EC-CUBE 4.1のフレームワークの開発ブランチ (4.1-core) と機能開発のブランチ (4.1-feature) を分けて開発を行なっています。
EC-CUBE 4.0 で稼働中のサイトも EC-CUBE 4.1 へバージョンアップをしやすくするため、4.1-feature ブランチは 4.0 ブランチから派生させ、4.1 リリース前に 4.1 ブランチにマージするような手順で進めています。
詳細は #4901 の開発ブランチについてをご確認ください。

ですので、まずは 4.0 へ機能を組み込み 4.1-feature ブランチにプルリクをいただければと思います。

**Comment by okazy** [comment]
#5017 で対応いただきましたのでこちらはクローズします。
ご対応ありがとうございました。
