### ISSUE TITLE
新着商品やニュースのRSSフィードがほしい

### ISSUE THREAD

**Issue by matsuoshi** [EC-CUBE/ec-cube#4863]
## 概要(Overview)
新着商品と、新着情報(ニュース) のRSSフィードを出力したい。

(外部サービス連携などでの利用を想定、たとえば新着ニュースをTwitterに自動で流すなど)

## 期待する内容(Expect)  or 要望 (Requirement)
以下のRSSフィードが出力される

- 新着商品
- 新着情報 (ニュース)

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
#4908 で機能追加されましたのでこちらはクローズします。ありがとうございました。

**Comment by okazy** [comment]
RSSは悪用される可能性があるので、管理画面でオン/オフを切り替えられるようにするほうがいいとのことでした。
