### ISSUE TITLE
支払方法で、手数料・利用条件を設定した際に、購入フローで選択できない場合がある

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4881]
## 概要(Overview)

以下のような仕払方法を作成した際に、注文画面で支払方法を選択できないケースがある。
- 代引有料(手数料300円、利用条件1〜3000円)
- 代引無料(手数料0円利用条件3001円〜)

利用条件の判定が、総計で行われているため。
再現手順に記載した条件だけではなく、送料や値引きも影響するかもしれない(未確認)

## 再現手順(Procedure)

- 配送方法設定から送料を0円で設定しておく
- 以下2点の支払い方法を追加
  - 代引(手数料：300円、利用条件：1〜1,399円)
  - 代引(手数料：0円、利用条件：1,400円〜)
- 販売価格：1,000円(税込1,100円)の商品を作成
- 上記の商品をカートにいれ、レジに進む
- 注文画面では、以下のように表示される
```
小計：￥1,100
手数料：￥0
送料：￥0
合計：￥1,100

支払方法：「代引有料」が未選択状態で表示される(内部的には「代引無料」が選択されている)
```

- 代引を選択すると、以下のように表示される

```
小計：￥1,100
手数料：￥300
送料：￥0
合計￥1,400

支払方法：「代引無料」が未選択状態で表示される(内部的には代引有料が選択されている)
```

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
1)注文画面遷移時に、カート情報から受注情報が生成されるタイミング

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Service/OrderHelper.php#L468

初期の支払方法が設定されるが、ここでは利用条件や金額は見ていない。
配送方法から支払方法のリストを生成し、ソート順が最上位の支払方法が設定される。

2)注文画面での支払方法のプルダウン生成

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Form/Type/Shopping/OrderType.php#L136

利用条件の判定を行い、利用可能な支払方法のプルダウンリストを生成している。
ただし、利用条件の判定が支払総額で行われているため、手数料や値引き等の影響を受ける。


そのため、1)で設定された支払方法が、2)で生成される支払方法のプルダウンリストと合致しないケースが発生する
1)2)ともに、支払総額ではなく商品明細の小計で利用可能な支払方法を抽出するのがよさそう。

**Comment by chihiro-adachi** [comment]
商品明細の小計で利用条件を判定する場合、以下の懸念がある

・決済手段により、支払総額で利用上限がある場合
例えばペイジーでは10万円まで決済可など。このとき、小計での判定だと決済が通らない可能性がある

・代引手数料を段階的に設定している場合
代引手数料は実際には支払総額での料金テーブルとなるため、小計での判定だと店舗側が多く負担するケースが発生する
https://www.yamatofinancial.jp/service/payment/daibiki.html

**Comment by chihiro-adachi** [comment]
無料化する支払方法の利用条件の下限を、手数料分を減算して設定しておくことで回避が可能(もしくはその逆でも可)

```
支払方法設定
①代引(手数料：300円、利用条件：1〜999円)
②代引(手数料：0円、利用条件：700円〜) ※①の手数料分を減算して下限設定

小計が700円の場合
①→支払総計1,000円(700+300)：利用不可
②→支払総計700円(700+0)：利用可
```

```
支払方法設定
①代引(手数料：300円、利用条件：1〜1299円)※①の手数料分を加算して上限設定
②代引(手数料：0円、利用条件：1000円〜) 

小計が700円の場合
①→支払総計1,000円(700+300)：利用可
②→支払総計700円(700+0)：利用不可
```

**Comment by chihiro-adachi** [comment]
上記の回避方法を使う場合、以下1)2)共に修正は必要になる

1)注文画面遷移時に、カート情報から受注情報が生成されるタイミング
このタイミングでは支払総額は決定していないため、利用条件が設定されているものは初期設定から除外

2)注文画面での支払方法のプルダウン生成
選択中の支払方法の手数料を除外し、各支払方法の手数料を加味した上で利用できる支払方法を抽出

**Comment by okazy** [comment]
支払方法が選択できない問題は解決しましたのでこのIssueはクローズします。
設定がややこしい問題は引き続き残りますので、ドキュメントの方にIssueを作成させていただきました。
https://github.com/EC-CUBE/doc4.ec-cube.net/issues/172
