### ISSUE TITLE
商品管理＞タグ管理のIDを変更可能とする

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4882]
## 概要(Overview)
現在、管理画面にて商品管理＞タグ管理のIDが自動採番となっている。
3系ではマスターデータ管理に位置していたため、IDを自身で採番出来ることが可能だったため、その状態に戻す。

聞いている話として、3系の際にタグIDを利用して商品検索の柔軟性を高めていたが、
4系では自動採番されることにより、アップデートに踏み切れない。という状況。
※広告周りなどで既にタグIDつきのURLにて登録が完了しているため、変更が難しいとのこと。

## 期待する内容(Expect)  or 要望 (Requirement)
管理画面：商品管理＞タグ管理にて、タグIDを編集出来る状態とする。

**Comment by chihiro-adachi** [comment]
顧客のユースケースとしては以下のようなものでした。
- 社内システムで採番されたIDとタグIDを合わせる必要がある
- IDは商材ごとに振られ、商材A=1000番台、商材B=2000番台など、IDで商材を連想できるように管理している
- 一度に大量登録することはなく、商材がリリースされたタイミングで順次登録していく

顧客の業務固有の利用方法となるため、EC-CUBE標準としてはこちらの修正は行いません。
