### ISSUE TITLE
インストール時のお支払い方法

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#489]
現在、インストール時に以下のお支払い方法が設定されます。

- 郵便振替
- 現金書留
- 銀行振込
- 代金引換

今時、現金書留を使用されるショップは皆無だと思いますし、

- 現金書留 → 削除
- 郵便振替 → ゆうちょ銀行送金

としてはいかがでしょうか？

**Comment by Yangsin** [comment]
* 銀行振込
* 代金引換  

だけでもよいかと。
