### ISSUE TITLE
CSV登録処理に対してフックポイントを用意する

### ISSUE THREAD

**Issue by jumemoto** [EC-CUBE/ec-cube#4893]
## 概要(Overview)
CSV登録処理に対してフックポイントがないことでプラグインの動きが制限される。

## 期待する内容(Expect)  or 要望 (Requirement)
レビューにてやりとりされている下記実現のため。
https://www.ec-cube.net/products/detail.php?product_id=1731

`現状EC-CUBE側のCSV登録処理に対してフックポイントが用意されておらずプラグイン側で対応を行う事が出来ない状態です。
そのため弊社では別の商品にはなりますが”商品CSV登録拡張プラグイン for EC-CUBE4”と連携させる事で商品登録出来る仕組みを提供させて頂いております。
今後EC-CUBE本体の方で該当箇所にフックポイントが追加される事があれば対応を予定しております。`

**Comment by nanasess** [comment]
こちらと重複でしょうか https://github.com/EC-CUBE/ec-cube/issues/3575
性能を考慮しなければ実現できそうですが、悩ましいですね

**Comment by jumemoto** [comment]
内容確認させていただきました。
確かに重複ですね。紐づけありがとうございます。

**Comment by xuelian311** [comment]
https://github.com/EC-CUBE/ec-cube/issues/3575 との重複であるため、こちらのissueはクローズします。
引き続き、 #3575 で対応検討していきます。
