### ISSUE TITLE
カートにアイテムを追加・数量変更・削除を行った時、カート・アイテムの順番が逆になる。

### ISSUE THREAD

**Issue by belltzel** [EC-CUBE/ec-cube#4895]
## 概要(Overview)
■一覧・商品詳細から、カートへアイテムを追加した時、右上に表示されるアイテムの順番が逆になる。

・アイテム１
・アイテム２

上記に新しくアイテムを追加した場合、

・アイテム３（新規）
・アイテム２
・アイテム１

の並び順になる。

さらにアイテムを追加した場合、

・アイテム４
・アイテム１
・アイテム２
・アイテム３

の並び順になる

![01](https://user-images.githubusercontent.com/48919150/106555583-34fa8b00-6561-11eb-9933-0f98414187c3.png)

![02](https://user-images.githubusercontent.com/48919150/106555589-375ce500-6561-11eb-9734-de2bdf3fd932.png)

■カートページも同様

アイテムの数量変更・削除を行った場合も並び順が逆になる。

販売種別が別々の商品が入って、複数のカートがある場合、カートの並び順も逆になる。

![03](https://user-images.githubusercontent.com/48919150/106555598-3af06c00-6561-11eb-9a68-141c1e5afe60.png)

![04](https://user-images.githubusercontent.com/48919150/106555602-3c219900-6561-11eb-9535-abd9f212eb64.png)

## 期待する内容(Expect)  or 要望 (Requirement)

カートにアイテムを追加・数量変更・削除を行っても並び順を変化させない。

## 再現手順(Procedure)

カートにアイテムを追加。

カートページでアイテムの数量を変更・削除。

### 環境 (environment)
+ EC-CUBE: 4.0.5

## 関連情報 (Ref)

開発コミュニティの質問
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=25281&forum=1

**Comment by belltzel** [comment]
イシュー立てる時は、デモサイトを使って確認しました。

4.0.5で環境を作り、再度確認したところ、同一販売種別の入れ替わりの動きはありませんでした。（順番変わらず）

販売種別が違う場合（カートが複数ある場合）はカートの順番が入れ替わります。

**Comment by okazy** [comment]
カートの順番が入れ替わる問題は #4439 にて修正いただきました。
賞品の順番が入れ替わる問題はまだ残っています。

**Comment by izayoi256** [comment]
@okazy
`4.0`だと商品の順番が変わる問題は確認できないのですが、再現手順などありますか？
(先の投稿にて`4.0.5`だと同一販売種別での入れ替わりはないとの報告あり)

**Comment by okazy** [comment]
@izayoi256 
私も詳しい条件はわかっていません。

PostgreSQLでEC-CUBEをインストール直後だと商品が入れ替わるのを確認しました。
SQLiteでは入れ替わりは確認できませんでした。
4.0ブランチで確認しています。

+ EC-CUBE: 4.0
+ PHP: 7.4.8
+ DB:
  - PostgreSQL 10.4
  - SQLite 3.24.0

**Comment by izayoi256** [comment]
@okazy 
#4953 リレーションで`ORDER BY`を指定してなかったため、RDBMSの種類によって再現性が違ったようです。

**Comment by okazy** [comment]
#4953 にて商品が入れ替わってしまう問題も対応いただきましたのでこちらはクローズさせていただきます。
ご対応ありがとうございました！
