### ISSUE TITLE
EC-CUBEのデフォルトの画像をWebP形式に変更

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#4896]
## 概要(Overview)

PageSpeed Insights でカスタマイズをしていないEC-CUBEを診断すると、画像関連のスコアが低く、Issue作成時点でモバイルで64点程度となっています。

![image](https://user-images.githubusercontent.com/16895409/106709600-1fa46000-6638-11eb-8e2f-1ea08e2ad1ce.png)

iOS 14/macOS 11 Big Sur からWebPが正式にサポートされましたので、主要なブラウザはWebPをサポートするようになりました。
どこかのタイミングでデフォルトの画像をWebPに変更したいです。

とは言え、Big Surより古いmacOSではサポートをしていないため、差し替えのタイミングは難しいと思っています。
2021年にリリース予定の4.1では対応が難しいかもしれませんが、その次のバージョンアップでは対応したいと思いましたのでIssueを作成しました。

## 期待する内容(Expect)  or 要望 (Requirement)

デフォルトの画像をWebPに変更して PageSpeed Insights のスコアアップ。

## 再現手順(Procedure)

 PageSpeed Insights で診断
https://developers.google.com/speed/pagespeed/insights/

### 環境 (environment)
+ EC-CUBE: 4.0

## 関連情報 (Ref)

https://github.com/EC-CUBE/ec-cube/issues/4700

**Comment by nanasess** [comment]
packagist に登録して2〜4系で使えるようにしたいです

https://github.com/EC-CUBE/ec-cube2/issues/358#issuecomment-567317539

**Comment by tao-s** [comment]
@okazy webpを標準とするなら、対応していないクライアント（IEとか）の場合にどうすか？を検討するべきだと思います。
個人的には、標準はjpgやpngなどアップロードされた画像を使って、リクエストヘッダ見てwebp対応してたらwebp返す感じにするのが良いと思います。

**Comment by chihiro-adachi** [comment]
#4900 で対応
