### ISSUE TITLE
お問い合わせの確認画面のメールアドレス

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#490]
メールアドレスの項目が2つあります
![default](https://cloud.githubusercontent.com/assets/815715/8429714/49c44f28-1f65-11e5-87ff-5965efb472d5.PNG)

**Comment by Yangsin** [comment]
ありがとうございます。
こちらいただいた https://github.com/EC-CUBE/ec-cube/issues/490 で修正されておりましたので、完了といたします。
