### ISSUE TITLE
EC-CUBE 4.1 機能開発方針

### ISSUE THREAD

**Issue by taguchimasahiro** [EC-CUBE/ec-cube#4901]
## EC-CUBE 4.1 機能開発方針

今後のEC-CUBEが店舗主と開発者の双方にとってより使いやすく魅力的なプラットフォームに成長させるために、以下のように考えています。

## 機能開発について

[EC-CUBE 4.1 Roadmap](https://github.com/EC-CUBE/ec-cube/issues/4603) の通り、EC-CUBE 4.1 で機能追加や改善を進めるにあたって、どのような機能が必要かを検討しています。カスタマイズ性や、既存プラグイン/デザインテンプレートとの互換性を最大限に考慮しながらも、誰もが利用しやすい機能から開発していきます。
そのために広く多くの方のご意見を集めたいので EC-CUBE の標準機能として必要だと思われる機能の Issue にご意見のコメントか 👍スタンプをお願いします。
「enhance」ラベルと「4.1」マイルストンが付いている Issue が EC-CUBE 4.1 で追加を検討中の機能です。
EC-CUBE 4.1で追加を検討している機能のIssueは以下で検索可能です。

[EC-CUBE 4.1 で追加を検討中の機能](https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement+milestone%3A4.1+sort%3Areactions-%2B1-desc)

コメントとスタンプを参考に実装していきます。

## バージョンについての方針

EC-CUBE 4.0に関しては積極的な機能追加は行いません。新しい機能の取り込む先として、EC-CUBE 4.1以降を想定しています。

## 互換性について

[EC-CUBE 4.1 Roadmap](https://github.com/EC-CUBE/ec-cube/issues/4603) の通り、プラグインの互換性に関しては最大限考慮します。

## 開発ブランチについて

2021/08/13 追記
EC-CUBE 4.1 開発時には役割別に `4.0` / `4.1-core` / `4.1-feature` に分けて開発をしていましたが、 EC-CUBE 4.1 の仕様確定に伴い 今後は `4.1` ブランチに統一します。
今後新しくプルリクをいただく際には `4.1` へいただきますようによろしくお願いいたします。
すでに `4.0` / `4.1-core` / `4.1-feature` へいただいていますプルリクはマージ後に `4.1` ブランチにマージさせていただきます。
`4.1` ブランチへのマージが完了しましたら `4.1-core` / `4.1-feature` は削除させていただきます。

![image](https://user-images.githubusercontent.com/16895409/129304726-45826314-4b6b-4c6b-b3bb-2aa61cfd900b.png)

<details>
<summary>EC-CUBE 4.1 開発時の運用</summary>

EC-CUBE 4.1のフレームワークの開発ブランチと機能開発のブランチを分けて開発を行います。EC-CUBE 4.1リリース時には両方のブランチをマージしてリリースします。

[4.1-core](https://github.com/EC-CUBE/ec-cube/tree/4.1-core) ： Symfony4.4/Composer2.0のアップデートの開発を行います。
[4.1-feature](https://github.com/EC-CUBE/ec-cube/tree/4.1-feature) ： 新機能開発を行います。

![4 1-feature](https://user-images.githubusercontent.com/4678370/106995720-d0d70180-67c2-11eb-9453-6ef3d47b799b.png)
</details>

## Feedback

機能開発に関する進め方へのご意見もお待ちしております。
本Issueにぜひコメントください。

**Comment by nanasess** [comment]
フレームワークとしての開発と、 CMS としての開発(feature)を分けていくのは賛成です。
今回のバージョンアップでは難しいかもしれませんが、 機能開発効率を高めるためのフレームワーク開発や、バージョンアップしやすくする仕組み作りの必要性を感じています。

現状では、 core は Symfony や Doctrine の新バージョンを追いかけるブランチという認識ですが、それのみではなく、 eCommerce に特化した、開発効率の良いフレームワークに育てていけたら良いなと思っています。
将来的には、 core は分離して vendor 以下で動かせるようになれば嬉しいです。

また、バージョンアップのしやすさについては、どうしても Synfony や Doctrine のバージョンアップによる破壊的な変更の影響を受けるので、 EC-CUBE 側の Interface で wrap して影響を吸収できたら良いと思います。(EC-CUBE2系や Concrete5 がそういった構成になっています)

あとは、プラグインやカスタマイズディレクトリの開発効率も悪すぎるので、もっと洗練させて簡単に書けるようにしたいですね。

**Comment by kurozumi** [comment]
@nanasess 

「プラグインやカスタマイズディレクトリの開発効率も悪すぎる」

自分は現状それほど苦に思っていないのですが、開発効率の悪さを具体的に教えていただけると助かります。

**Comment by dk-umebius** [comment]
EC-CUBE本体では、プラグインで実装すると他プラグインと競合しやすい機能を優先して欲しい気がします。

イメージでは #4600 #4873 #4577 #4627 あたりです。

**Comment by nanasess** [comment]
@kurozumi 
もっと簡潔に書けるようになったらいいと思っています。
具体的なイメージはまだ見出せていませんが、 Java の SpringBoot などは参考になりそうです。
特に、FormType は記述性が悪く、毎回苦しんでます。
SpringBoot はとても簡潔に書けるようになっています。
https://qiita.com/ryo2132/items/bbef095c87cab3720c70
究極は、 Twig の中にフォーム定義の Yaml とか、アノテーションコメントを埋め込んだら、自動的にフォームが生成されるようになったりすると、デザイナーさんにも優しそうです。

あと、できるかどうかわかりませんが Twig に式言語みたいな仕組みを導入できたらいいなと思っています。
(例なので Twig の構文と乖離してますがご容赦ください)
例えば、以下のように書くだけで、商品ID:10 をカートに入れられるフォームが生成されるとか。
```xml
<form:cart type="product" id="10" />
```

管理画面の検索フォームもパターンは決まっていますし、もっと簡単に書けたらいいですね。
今は、受注番号検索は単一でしかできませんが、1000〜1010 まで検索したいという要望もあるかもしれません。そんな時に、
```xml
<input:order type="id" attr="between" />
```
と書けば、
```xml
<input type="text" name="order[id][]" />〜<input type="text" name="order[id][]" />
```
のようなフォームが自動生成されるとか。

具体的なイメージがすぐに湧きませんが、フォームのみでなく、 PHPのプログラム側ももっと簡潔に書けるようにしたいです。 4系で導入された、 PurchaseFlow はその先駆けと言えます。


20年近く前に、 Java のフレームワーク開発をしていたのですが、当時すでに上記のような仕組みを導入して、業務に特化したコンポーネントをたくさん作り、機能開発効率を上げていました。
当時のフレームワークと比べると、 EC-CUBE は20年遅れているといっても過言ではないと思います。
が、14年間開発に携わって、なかなかその境地まで辿りつけていないのが現実です。
ただ、現代のスクリプト言語はフレームワークのカスタマイズはあまりせずに、そのまま使うのが主流なようなので、時代錯誤なのかもしれません。

**Comment by chihiro-adachi** [comment]
PRの送り先について補足です。

方針発表前に既に投稿いただいているPRについては、投稿されたブランチで受け入れを行う予定です。
ただし、4.1ブランチにPRを投げていただいている場合は、修正依頼をお願いする場合があります。

今後は、不具合修正：4.0ブランチ、機能追加・機能改善：4.1-featureにPRをお願いします。

**Comment by okazy** [comment]
現時点の 👍  数上位

### 3個以上

#4600 
#4807
#4852

### 2個

#4875
#4879
#4873
#4867

### 実装を検討中

#4840
#4859
#4847
#4874
#4862
#4878

**Comment by okazy** [comment]
毎週水曜日の14時からオンラインで EC-CUBE Issue 検討会を実施しています。
GitHub の Issue の内容がわかりにくいのでリファインメントしようという会です。
GitHub 共有会から続きで開催し、会場も GitHub 共有会と同じです。
一緒にEC-CUBEを改善していきましょう！

▼参加用URL（GitHub 共有会と同じ）
meet.google.com/rqq-jtpi-jha

▼公式サイトのイベントページ
https://www.ec-cube.net/event/detail.php?event_id=280

<details>

## 概要

EC-CUBE のリポジトリには多くの Issue が作成されていますが、内容が不明確で開発に着手しにくい Issue が多いかと思います。
EC-CUBE の機能向上に向け、開発者が開発に着手できるように、またプルリク後の手戻りが少ないように Issue を整理（リファインメント）していきます。

Issue の整理には EC-CUBE のコア開発者が数名参加予定です。
EC-CUBE を改善したいと思われている方はぜひご参加いただきご意見をいただければと思います。
全体としては開発者向けの内容とはなりますが、開発者は運用面が苦手なため、運用経験者の参加も大歓迎です。
これから EC-CUBE の開発に参加しようと思われているエンジニアの方は考え方など勉強になるかと思います。

Issue 検討会は週１回程度を目標に開催していきたいと思っています。
アジェンダや開催日程は参加者のご意見をいただきながら改善していきますので、お気軽にご参加よろしくお願いいたします。

## 日時

2021/3/3 14:00~15:00 (EC-CUBE GitHub 共有会の後)

## 参加方法

Google Meet で開催します。
時間になりましたら以下の URL からご参加ください。

meet.google.com/rqq-jtpi-jha

## アジェンダ

1. 趣旨説明（3分）
2. 更新 Issue/PR の確認（10分程度）
3. 開発 ready ではない Issue のリファインメント（40分程度）
  - Issue の要件・仕様の決定、できれば実装方針まで決めて開発できる状態とする

## 第1回のリファインメント対象の Issue

参加者から要望があれば優先してリファインメントしていきたいと思います。
特に希望がなければ第1回は以下の Issue の中からリファインメントをしていこうと思います。

- 商品の掲載期間を設定したい #4852
- 商品購入時にギフト・ラッピングを選べるようにしたい #4875
- カテゴリページにコンテンツを追加する機能の追加 #4840
- 管理画面のログイン履歴 #4847
- ダウンロードコンテンツを販売できるようにしたい #4874
- 検索ボックスでタグ検索を出来るようにしたい #4862


</details>

**Comment by okazy** [comment]
毎週木曜日に EC-CUBE Issue 検討会を実施していますが、実施内容を記録しておくところがありませんでしたので、こちらの Issue に投稿していこうと思います。
EC-CUBE Issue 検討会の記録の撮り方でもっといい方法があればコメントいただければと思います。

[dev-readyのIssue](https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aopen+is%3Aissue+label%3A%22Status%3A+dev-ready%22)

## 検討したい Issue メモ

- HTML, Javascriptもminifyして欲しい #5025
- カテゴリの商品一覧か画面に関連カテゴリのリンクを付与したい #5015
  - 実現方法がいくつかあるので検討する
- SEO強化 #4807
  - 対応しておくべきSEO施策をまとめたい
- 予約販売機能 #4883
- 抽選販売の設定が欲しい #4994
- 検索のサジェスト機能を追加したい #4949
- カテゴリページにコンテンツを追加する機能の追加 #4840
- その他直近で更新があった Issue

## 検討した Issue

> しるし
> :rocket:開発 Ready
> :new:新規
> :checkered_flag:クローズ
> :up:更新
> :soon:次回に持ち越し

### 2021/04/28

商品にオプション項目を追加できるようにする https://github.com/EC-CUBE/ec-cube/issues/4873#issuecomment-828149756 https://github.com/EC-CUBE/ec-cube/issues/4873#issuecomment-828164807 :up:

次回は管理画面と DB の設計をできればと思います。

### 2021/04/21

商品購入時にギフト・ラッピングを選べるようにしたい https://github.com/EC-CUBE/ec-cube/issues/4875#issuecomment-823787318 https://github.com/EC-CUBE/ec-cube/issues/4875#issuecomment-823797015 :up:
商品にオプション項目を追加できるようにする https://github.com/EC-CUBE/ec-cube/issues/4873#issuecomment-823789021 :up:

商品単位のオプション機能があれば（使いにくいケースはあれど）多くの場合網羅できるという結論になりましたので、商品単位のオプション（ラッピング）機能の検討をしたいと思います。

### 2021/04/14

Doctrine Filterで拡張機構を実装してみる https://github.com/EC-CUBE/ec-cube/issues/5005#issuecomment-819235809 :up:
商品購入時にギフト・ラッピングを選べるようにしたい #4875 :up::soon:

### 2021/04/07

【商品の公開状況の制御機能のベース】商品の掲載期間を設定したい #4852 :up:
フロント側での商品情報表示を制御する拡張機構 #4995 :up:
フロント画面に管理者権限でログインしているかを判断できる表示が欲しい #5006 :new::rocket:

### 2021/03/31

商品の掲載期間を設定したい https://github.com/EC-CUBE/ec-cube/issues/4852#issuecomment-810771903 :up::soon:
抽選販売の設定が欲しい #4994 :new:

### 2021/03/24

タグ管理の項目追加の自動表示位置が誤り #4981 :rocket:
受注登録でお届け先に氏名が表示されない #4980 :rocket:
composer install時にDeprecation Notice #4607 :rocket:
受注管理＞出荷CSVのラベルで"出荷ID"ではなく、"配送ID"となっている #4180 :rocket:
受注編集時に不必要なデータが更新される #4059 :rocket:
複数台構成で稼働時に、データ更新後のリダイレクトでデータが反映されない場合がある #4985 :new:
マイページのお届け先追加/削除の完了メッセージの追加 #4762 :checkered_flag:
画像の lazy load 対応 #4816 :checkered_flag:

### 2021/03/17

https://github.com/EC-CUBE/ec-cube/issues/4972 :rocket:
https://github.com/EC-CUBE/ec-cube/issues/4969 :rocket:
https://github.com/EC-CUBE/ec-cube/issues/4952

### 2021/03/10

https://github.com/EC-CUBE/ec-cube/issues/4948
https://github.com/EC-CUBE/ec-cube/issues/4947 :rocket:
https://github.com/EC-CUBE/ec-cube/issues/4946

### 2021/03/03

https://github.com/EC-CUBE/ec-cube/issues/4847
https://github.com/EC-CUBE/ec-cube/issues/4946
https://github.com/EC-CUBE/ec-cube/issues/4947
https://github.com/EC-CUBE/ec-cube/issues/4948

**Comment by okazy** [comment]
EC-CUBE 4.1 に追加予定の機能

## A: 4.1β2に向けて積極的に取り込みたいプルリクエスト
 
https://github.com/EC-CUBE/ec-cube/pull/4987
https://github.com/EC-CUBE/ec-cube/pull/4986
https://github.com/EC-CUBE/ec-cube/pull/4975 
https://github.com/EC-CUBE/ec-cube/pull/4976
https://github.com/EC-CUBE/ec-cube/pull/4966
https://github.com/EC-CUBE/ec-cube/pull/4808
https://github.com/EC-CUBE/ec-cube/pull/5017

- 4.1はβの段階ですので、多少の課題があってもテストに問題がなければ上記を 4.1-beta2 ブランチに取り込みたいと思います。
- 4.1 RC までに課題の解決を目指します。
- 新機能については既存のプラグインとの競合調査も実施し、エラーが発生しない状態を目指します。
- また、プラグインから本体へ取り込まれた機能についてはマイグレーションの提供も検討します。
- β版ですので、課題が解決できない場合には切り戻す可能性もあります。
- 個別に判断もしたいので、β2のリリースは4月中旬となる見込み

## B: 4.1.1 以降での取り込みとなりそうなプルリク

https://github.com/EC-CUBE/ec-cube/pull/4642
https://github.com/EC-CUBE/ec-cube/pull/4974
https://github.com/EC-CUBE/ec-cube/pull/4928
https://github.com/EC-CUBE/ec-cube/pull/4920
https://github.com/EC-CUBE/ec-cube/pull/4916
https://github.com/EC-CUBE/ec-cube/pull/4912
https://github.com/EC-CUBE/ec-cube/pull/4697

### 4.1に入れたいが、現時点で課題があり入れる判断ができないもの

https://github.com/EC-CUBE/ec-cube/pull/4898

- 最低限GDが入っていない場合も動作するように対応が必要

https://github.com/EC-CUBE/ec-cube/pull/4796

- 照合順序 `default_table_options`
- カラムの定義変更がスキーマアップデートでアップデート可能かの確認が必要
- カスタマイズでバイト数で文字列処理をしている場合にずれる可能性がある？

https://github.com/EC-CUBE/ec-cube/pull/4687

- 4.1ではシリアライズの課題あり

## C: 4.1では実現できないもの

**Comment by okazy** [comment]
`4.0.6` / `4.1-beta2` / `4.1RC` のリリースまでのブランチの運用を整理しました。
直近の `4.1-beta2` リリースに向けて、 ① ② ③ ④ を実施します。

- [x] 1: https://github.com/EC-CUBE/ec-cube/tree/4.1-beta2
- [x] 2: https://github.com/EC-CUBE/ec-cube/pull/4999
- [x] 3: https://github.com/EC-CUBE/ec-cube/pull/5000 
- [x] 4: https://github.com/EC-CUBE/ec-cube/pull/5002

![image](https://user-images.githubusercontent.com/16895409/113385934-0fa0c680-93c4-11eb-9ebd-f5285bcd7ba2.png)

- https://github.com/EC-CUBE/ec-cube/pull/5001
  - Symfony Update で課題あり 
  - Symfonyに問題があれば、Symfony 4.4.18 で beta2 はリリース
  - 課題解決自体は 4.1-core にプルリク

**Comment by okazy** [comment]
ブランチの今後の運用について追記させていただきました。

EC-CUBE 4.1 開発時には役割別に `4.0` / `4.1-core` / `4.1-feature` に分けて開発をしていましたが、 EC-CUBE 4.1 の仕様確定に伴い 今後は `4.1` ブランチに統一します。
今後新しくプルリクをいただく際には `4.1` へいただきますようによろしくお願いいたします。
すでに `4.0` / `4.1-core` / `4.1-feature` へいただいていますプルリクはマージ後に `4.1` ブランチにマージさせていただきます。
`4.1` ブランチへのマージが完了しましたら `4.1-core` / `4.1-feature` は削除させていただきます。

![image](https://user-images.githubusercontent.com/16895409/129304662-da1db318-dbdd-477b-9b20-e4cae24944e2.png)

**Comment by chihiro-adachi** [comment]
4.1へのマージは完了したため、4.1-core/4.1-featureブランチを削除しました。
