### ISSUE TITLE
管理者のみがショップを閲覧できるモードが欲しい

### ISSUE THREAD

**Issue by yKazihara** [EC-CUBE/ec-cube#4954]
## 概要(Overview)
現状メンテナンスモードはあるが、管理者であってもショップの閲覧ができない。
このメンテナンスモードとは別に、管理者のみがショップを閲覧出来るモードが欲しい。

## 期待する内容(Expect)  or 要望 (Requirement)
メンテナンスモードを改修するのではなく、新たに管理者のみがショップを閲覧出来る機能を追加したい。

### 環境 (environment)
+ EC-CUBE: 4.0.x

## 関連情報 (Ref)
#4839

**Comment by okazy** [comment]
> メンテナンスモードを改修するのではなく、新たに管理者のみがショップを閲覧出来る機能を追加したい。

こちら補足します。

既存のメンテナンス機能はアップデートやプラグインインストール時のトラブルを防ぐため、フロント画面アクセスでキャッシュが生成されないように作られた機能です。
そのため最初にアクセスされる index.php 内で Symfony のカーネルが呼び出されるよりも先にメンテナンスモードか判定してアクセスを遮断するようにできています。

https://github.com/EC-CUBE/ec-cube/blob/8934130ddea39075a563f2c5d057fa2282b4d671/index.php#L58-L73

既存機能のメンテナンス機能と本 Issue の主題となっているメンテナンス機能は両立できない問題があります。
「管理画面にログインしていたらフロント画面にアクセスできる」機能を実現するためには Symfony が提供している機能を使ってログイン状態かを判定する必要があります。
なのでログイン状態の判定には Symfony のキャッシュの生成が必要になり、既存のメンテナンス機能の要件が満たされなくなります。

こちらの問題の良い解決策が見つからないため、既存のメンテナンス機能とは別で、管理者だけがフロントを確認できるメンテナンス機能を実装するのがいいと思います。

**Comment by kiy0taka** [comment]
#4961 現状のメンテナンスモードと共存する方法を考えてみました。

**Comment by chihiro-adachi** [comment]
#5233
