### ISSUE TITLE
管理画面 受注一覧の一括操作で受注ステータスを「発送済」に変更すると加算ポイントが正しく反映されない

### ISSUE THREAD

**Issue by kuniiskywalker** [EC-CUBE/ec-cube#4958]
## 概要(Overview)

同一顧客の複数受注（新規受付）が存在する状態で、管理画面 受注一覧の一括操作で受注ステータスを「発送済」に変更すると、正しくポイント加算がされない

## 期待する内容(Expect)  or 要望 (Requirement)

受注数分の加算ポイントの合計が顧客に付与される

### 前提
- 本登録顧客が存在する状態
- ポイント設定 > ポイント機能を有効化

### 手順

1. 該当顧客で受注1の作成: 新規受付 加算ポイント有り
2. 該当顧客で受注2の作成: 新規受付 加算ポイント有り
3. 管理画面の受注一覧で↑1,2で作成した受注を選択
4. 対応状況の変更プルダウンから「発送済」を選択
5. 決定ボタンをおす

### 環境 (environment)
+ EC-CUBE: 4.0.5
+ PHP: 7.3.26
+ DB:
  - MySQL 5.7
+ ローカルDocker環境

### 調査内容
以下ポイント付与処理実行前にlog_infoを追加してユーザーの保有ポイント（$Customer->getPoint()）を出力

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Service/OrderStateMachine.php#L192

### 結果
各受注のログ出力時点ででユーザーの保有ポイントが同一（2回目の出力で1回目の加算ポイントが付与されてない状態）

### 調査仮説
各受注のステータス変更をAjaxで並列に行っているため、1回目の加算ポイントが付与される前に、2回目の加算ポイント処理が動いているものと思われる

**Comment by okazy** [comment]
記載いただいている仮説は十分考えられると思います。
在庫の増減処理と同様にテーブルの書き込みをロックする処理を追加する必要があるかと思います。
https://github.com/EC-CUBE/ec-cube/blob/b0bc5efa47b48c4207c270b422745557f0903cb6/src/Eccube/Service/PurchaseFlow/Processor/StockReduceProcessor.php#L89

**Comment by chihiro-adachi** [comment]
#5132 で修正
