### ISSUE TITLE
キャッシュ生成を制御するメンテナンスモードで管理者だけがフロント画面にアクセスできるようにする

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#4961]
## 概要(Overview)

メンテナンスモード開始時にランダムな文字列を生成し、それを `.maintenance` ファイルの内容とCookieに設定し、Cookieによって管理者らしいことを確認してメンテナンスモードでもフロントにアクセスできるようにする。
Cookieの比較であれば、`index.php` だけで検証できるので、キャッシュが生成されることもない。
管理画面へのアクセスには上記のCookieではなく、これまでどおりの認証が必要。
万が一管理者でないユーザーが適当な値をCookieに設定して一致するかもしれないが、管理画面にはアクセスできないので問題ない。

### [シーケンス図](http://www.plantuml.com/plantuml/umla/nLNFJnD15BxFNp7X12580_72GM49yQ09Hk3cPTcECB7TQPOfmHip4sgra114Y0P5Y8OVfENWHK8DVynZstBoNt1sDcljignxyzBEzhttlU_x-lRD-1AtFLuk5j0YpHFyWZ4-prOGiXtEFDpNRXoqDokTrRM9FcmlOJjVfEx4hQ3L3LfH4EGPo0kGLw0-WsgQ3AUyn5cHUAYaUrA7bcoNupxgvidAlT9YoUIOfzw4gScXoJbhoeI9uvJd2K9emMFb4kxo0x4EwW3KTr0LK6-3Wswl3dLlK6zkTch-KGs5_F7GWx0D7Xp4O_ZfzCmi7dQOoudBXuis3Gwswv102bssEObqXqMwEcIXor5uwlwcyK2T61gheBw0E6tjlFRhktvr5yGHo7h0Hswrj_TRrSt4wYXbah6Nb83GDbw2Kg2g_RS5Xaa3gK3-fePOJJBdFSW3a5z1dLt_t0luU8INFJVwGiJD9nkjArNTm5KDmKEGvvgc1aN97Z-QqXPt_JE7CNoNdg25a21h86g_clknEWsNBWP4mw-i-OqB4CTtjf1RhVFjJbCb_AczDk2HN0vFFxxJZF2XlNrvy-amPaQA5oOoV5lPtsXppvw0q1wSWAZemyECyzSvtUWSDri_gY2kUkiJTUL9VCoDqhXKgx-rTnf23sHHRQMexcre_LSNHdCZ4Qy2Mw0kIgSVfMKTcsGuitEouyM9PW3Dw5BAwz4vhlkDZyXbd62FBYnodItUWLo_llnsys43n7btDa3AvsxALWXMdzW0MSisWXRgcS7OLVAl1HJTCeahw4-ZA2i-V9ctKgJXVcuKpn1lcJe4pv9YYNcsHmkly9nhBzkqOCyNY14OxsiaZkiFVVd-1W00)

説明をわかりやすくするために、`index.php` を分けて記述しています。

![image](http://www.plantuml.com/plantuml/png/nLNFJnD15BxFNp7X12580_72GM49yQ09Hk3cPTcECB7TQPOfmHip4sgra114Y0P5Y8OVfENWHK8DVynZstBoNt1sDcljignxyzBEzhttlU_x-lRD-1AtFLuk5j0YpHFyWZ4-prOGiXtEFDpNRXoqDokTrRM9FcmlOJjVfEx4hQ3L3LfH4EGPo0kGLw0-WsgQ3AUyn5cHUAYaUrA7bcoNupxgvidAlT9YoUIOfzw4gScXoJbhoeI9uvJd2K9emMFb4kxo0x4EwW3KTr0LK6-3Wswl3dLlK6zkTch-KGs5_F7GWx0D7Xp4O_ZfzCmi7dQOoudBXuis3Gwswv102bssEObqXqMwEcIXor5uwlwcyK2T61gheBw0E6tjlFRhktvr5yGHo7h0Hswrj_TRrSt4wYXbah6Nb83GDbw2Kg2g_RS5Xaa3gK3-fePOJJBdFSW3a5z1dLt_t0luU8INFJVwGiJD9nkjArNTm5KDmKEGvvgc1aN97Z-QqXPt_JE7CNoNdg25a21h86g_clknEWsNBWP4mw-i-OqB4CTtjf1RhVFjJbCb_AczDk2HN0vFFxxJZF2XlNrvy-amPaQA5oOoV5lPtsXppvw0q1wSWAZemyECyzSvtUWSDri_gY2kUkiJTUL9VCoDqhXKgx-rTnf23sHHRQMexcre_LSNHdCZ4Qy2Mw0kIgSVfMKTcsGuitEouyM9PW3Dw5BAwz4vhlkDZyXbd62FBYnodItUWLo_llnsys43n7btDa3AvsxALWXMdzW0MSisWXRgcS7OLVAl1HJTCeahw4-ZA2i-V9ctKgJXVcuKpn1lcJe4pv9YYNcsHmkly9nhBzkqOCyNY14OxsiaZkiFVVd-1W00)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by kiy0taka** [comment]
`.maintenance` ファイルには `auto_maintenance` や `auto_maintenance_update` といった文字列が書かれているようなので、`<ランダムな文字列>:auto_maintenance` のような形式にする必要がある。
https://github.com/EC-CUBE/ec-cube/blob/dc27cb56697f2a02a7950d0a12cdc9983aa0d6a3/src/Eccube/Service/SystemService.php#L144-L157

**Comment by izayoi256** [comment]
Cookie管理にしてしまうと、複数人で作業するときや、別ブラウザ表示確認の際に支障があるように思います。

**Comment by kiy0taka** [comment]
@izayoi256 メンテナンス中に一度管理画面にログインしてもらえば、Cookieが発行されるので支障はでないと考えてます。上記のシーケンス図では管理者Bのパターンになります。

**Comment by izayoi256** [comment]
@kiy0taka あ、すいません。しっかり書いてありましたね…。それなら他に懸念事項はないんじゃないでしょうか。

**Comment by izayoi256** [comment]
#4966 にて試しに実装した際の懸念を下記。

- メンテナンスモード有効時に管理者ログアウトした際のCookieの取り扱い
- `4.0でメンテナンスモード有効化` → `4.1にアップデート`とした際にトークン未発行で回避できない
- 回避中にその旨が分かるようにしたほうがよいか (解除忘れ防止)
- 無効化処理の中には `KernelEvents::TERMINATE`にて行われているものがある。Cookie側のトークン削除処理が次のリクエストの `KernelEvents::RESPONSE`になってしまう。ただ、これが起こるのはAjax通信時か、POST後にリダイレクトを挟むことになるので、実質的に問題はないはず…。

**Comment by okazy** [comment]
> メンテナンスモード有効時に管理者ログアウトした際のCookieの取り扱い

セッションと同様に破棄で良いかと思います。

> 4.0でメンテナンスモード有効化 → 4.1にアップデートとした際にトークン未発行で回避できない

こちらはアップデート時だけなのでアップデート手順に注意書きがあれば許容できるかと思いました。

> 回避中にその旨が分かるようにしたほうがよいか (解除忘れ防止)

確かに、「現在メンテナンスモードです」のようなアラートが表示されるのが良いかと思いました。

> 無効化処理の中には KernelEvents::TERMINATEにて行われているものがある。Cookie側のトークン削除処理が次のリクエストの KernelEvents::RESPONSEになってしまう。ただ、これが起こるのはAjax通信時か、POST後にリダイレクトを挟むことになるので、実質的に問題はないはず…。

実質的には問題ないはず。。。

**Comment by izayoi256** [comment]
@okazy 
> セッションと同様に破棄で良いかと思います。

破棄するよう変更しました。

> 確かに、「現在メンテナンスモードです」のようなアラートが表示されるのが良いかと思いました。

画面上部に`position: fixed;`で表示するよう変更しましたが、テンプレートの修正に不慣れなため、もし直したほうが良ければPR等お願いします。

**Comment by chihiro-adachi** [comment]
#5123 で対応
