### ISSUE TITLE
受注登録でお届け先に氏名が表示されない

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/ec-cube#4980]
## 概要(Overview)
受注登録でお届け先に氏名が表示されない

## 再現手順(Procedure)
受注登録ページで、複数配送のときにお届け先が複数表示されるが、会社名が空だと各お届け先に氏名が表示されない

### 環境 (environment)
+ EC-CUBE: 4.0.5

**Comment by okazy** [comment]
@hironori-tanaka 
問題の箇所はこちらでしょうか？

![image](https://user-images.githubusercontent.com/16895409/111959441-d0f04e00-8b31-11eb-8030-4f71a8023832.png)

デモ環境で試してみましたが、会社名を設定しても氏名が表示されませんでした。。。

**Comment by hironori-tanaka** [comment]
はい、そちらの箇所になります。

app/template/admin/Order/edit.twig
の三項演算子の処理順序がおかしいのかなと思います。

■現行
{% set shipping_name = shipping.full_name ~ '(' ~ shipping.full_name_kana ~ ')' ~ shipping.company_name is not null ? shipping.company_name : '' %}

■修正案
{% set shipping_name = shipping.full_name ~ '(' ~ shipping.full_name_kana ~ ')' ~ (shipping.company_name is not null ? shipping.company_name : '') %}

**Comment by okazy** [comment]
確かに書き方がよくなさそうですね。

`shipping_name` と `shipping_company_name` は変数を分けた方が良さそうです。

https://github.com/EC-CUBE/ec-cube/blob/ce9503051244bbb6f9ebb5390ecc0fc04548372d/src/Eccube/Resource/template/admin/Order/edit.twig#L511-L519

**Comment by chihiro-adachi** [comment]
#5213 で修正のためクローズします。
