### ISSUE TITLE
タグ管理の項目追加の自動表示位置が誤り

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#4981]
## 概要(Overview)

プラグインやカスタマイズ領域でタグ管理に項目を追加すると、新規作成ボタンの右側に項目が表示されます。
![image](https://user-images.githubusercontent.com/8196725/112101311-c2656d80-8be9-11eb-96ad-1d2203c068f5.png)

## 期待する内容(Expect)  or 要望 (Requirement)

以下のように表示されるのが望ましいかと思います。
![image](https://user-images.githubusercontent.com/8196725/112101500-15d7bb80-8bea-11eb-9d38-e92ca3633135.png)

## 再現手順(Procedure)

以下のフォーム拡張をカスタマイズ領域に追加

```php
<?php

namespace Customize\Form\Extension;

use Eccube\Form\Type\Admin\ProductTag;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class TagTypeExtention extends AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('hoge', TextType::class, [
            'mapped' => false,
            'eccube_form_options' => [
                'auto_render' => true,
            ]
        ]);
    }

    public function getExtendedType()
    {
        return ProductTag::class;
    }

    public function getExtendedTypes()
    {
        return [ProductTag::class];
    }
}
```

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by okazy** [comment]
似た UI の他の画面も修正が必要かもしれません。
必要であれば同時に修正したいです。

- タグ管理
- 規格管理
- カテゴリ管理

**Comment by okazy** [comment]
該当箇所はこちらです。順番を入れ替えるだけで良いかと思います。

https://github.com/EC-CUBE/ec-cube/blob/3e492f7975e8a34d6139746037e10b437edb978c/src/Eccube/Resource/template/admin/Product/tag.twig#L149-L169

**Comment by chihiro-adachi** [comment]
#5209 で修正されました。
