### ISSUE TITLE
mtb_系統をひとつのテーブルで取り扱う

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#5]
* 構造の違うmtb\_系テーブルを除き、ひとつのテーブルとする。
* 既存の各テーブルを分けるために、「type」カラムを用意する。

ただし、id, name, rank以外の構造のmtb\_（mtb\_constants / mtb\_zipなど）は別table（constants / zip）とする

**Comment by shinichi-takahashi** [comment]
ひとつのテーブルにまとめる際の、テーブル名はどうしましょうか？

master_dataとか？

**Comment by Yangsin** [comment]
こちらβ版の開発を進めるなかで、現状のmtb構造で問題なしと判断し、見送る方針です。

**Comment by Yangsin** [comment]
こちらmtbは現構造のままとします（不要なテーブルは削除しますが）
