### ISSUE TITLE
ブルートフォース対策について

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#500]
ブルートフォース対策について方向性を確認
・IPアドレスをブラックリスト管理する。

**Comment by aminotsukasa** [comment]
銀行ATMのカード飲み込み仕様のようにユーザ単位でカウントする方法もあります。
IPアドレスとユーザのどちらの単位が良いか悩み所…

**Comment by xuelian311** [comment]
ブルートフォース対策としてスロットリングが実装されたためクローズします。

https://github.com/EC-CUBE/ec-cube/pull/5881
https://github.com/EC-CUBE/ec-cube/pull/5473されているため、本issueはクローズします。

**Comment by chihiro-adachi** [comment]
@xuelian311 
こちらの要望ですが、内容的には以下のようなログインの試行回数制限を指しているかと思います。
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=thread&order=DESC&topic_id=10441&forum=12

IPアドレス制限や退会処理ではなく、スロットリングが実装されたためクローズ、が正確かなと思いました。

- https://github.com/EC-CUBE/ec-cube/pull/5881
- https://github.com/EC-CUBE/ec-cube/pull/5473

**Comment by xuelian311** [comment]
@chihiro-adachi ありがとうございます。コメント編集しました。
