### ISSUE TITLE
受注の一括送信メールでシステムエラーが発生する

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5004]
## 概要(Overview)

一括全選択→メール送信で発生しました。
必ず発生するわけではなく、表示件数によって発生の有無があります。

![image](https://user-images.githubusercontent.com/8196725/113788897-01162e80-9779-11eb-9c40-200ef8b27385.png)

## 再現手順(Procedure)

- デモサイトにて確認
- 受注一覧を表示
- 受注の表示件数を100件に変更
- 一括全選択し、メール送信

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by kiy0taka** [comment]
`503` が帰ってきてるようなので、Webサーバーのパラメータを調整するか、メール送信の並列度を下げてやる必要がありそうです。

**Comment by chihiro-adachi** [comment]
対応状況の変更でもシステムエラーが発生しました。
一括処理の問題のような感じです
![image](https://user-images.githubusercontent.com/8196725/113813008-0770ce80-97aa-11eb-9460-c01b555767ae.png)

**Comment by xuelian311** [comment]
現状発生しなくなりましたので、クローズします。
改めて発生した場合は、新たにissueを立てます。
