### ISSUE TITLE
PostgreSQL11.x, 12.x, 13.x をシステム要件に追加する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5007]
## 概要(Overview)
現在、システム要件として PostgreSQL10.x となっているが、GitHub Actions では 11 でテストしている。
最新は 13.2 になっているため、システム要件を追加したい

## 期待する内容(Expect)  or 要望 (Requirement)
PostgreSQL のシステム要件を 9.x / 10.x / 11.x / 12.x / 13.x に変更する

## 再現手順(Procedure)
以下、GitHub Actions にて PostgreSQL13で動作確認(一部エラーになっているのは MySQL なので問題ない)
- https://github.com/nanasess/ec-cube/actions/runs/725177607
- https://github.com/nanasess/ec-cube/actions/runs/725177608
- https://github.com/nanasess/ec-cube/actions/runs/725177609

### 環境 (environment)
+ EC-CUBE: 4.1-core
+ PHP: 7.x
+ DB:
  - PostgreSQL 13.2

**Comment by okazy** [comment]
ありがとうございます。
UnitTest/E2Eテストが通っていますので、Postgres 13 までサポートバージョンに加えたいと思います。

**Comment by matsuoshi** [comment]
こちら、EC-CUBE 4.1.0 にて PostgreSQL13までがシステム要件対象に加わりましたので、クローズします
