### ISSUE TITLE
検索結果0件のページと在庫切れのページは noindex としたい

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#5014]
## 概要(Overview)

SEOの観点から、不要なページをサイト内から減らしたい。
検索結果0件のページと在庫切れのページは noindex としたい。

## 期待する内容(Expect)  or 要望 (Requirement)

検索結果0件のページと在庫切れのページは noindex 付与

### 環境 (environment)
+ EC-CUBE: 4.0.x

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/4807#issuecomment-768654133

**Comment by chihiro-adachi** [comment]
#5019 で対応
