### ISSUE TITLE
composer 2がインストールされるためdocker-compose up できない

### ISSUE THREAD

**Issue by Ippey** [EC-CUBE/ec-cube#5021]
## 概要(Overview)
ローカル環境構築用にDockerが用意されており、backendのDockerfileに以下の記述がありますが
現在、getcomposer.org/installerからダウンロードされるcomposerのバージョンが2になるため、
以降のcomposer requireコマンドがエラーとなります。

```
RUN curl -sS https://getcomposer.org/installer \
  | php \
  && mv composer.phar /usr/bin/composer \
  && composer config -g repos.packagist composer https://packagist.jp \
  && composer global require hirak/prestissimo \
  && chown www-data:www-data /var/www \
  && mkdir -p ${APACHE_DOCUMENT_ROOT}/var \
  && chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT} \
  && find ${APACHE_DOCUMENT_ROOT} -type d -print0 \
  | xargs -0 chmod g+s \
  ;
```

## 期待する内容(Expect)  or 要望 (Requirement)
docker-compose upしてもエラーにならずに環境構築できる。
解決手段としては、self-update --1でcomposer 1に下げる方法が一番楽ですが、
ec-cube 4.1リリース時にself-update --1の記述を削除する必要があります。

```
RUN curl -sS https://getcomposer.org/installer \
  | php \
  && mv composer.phar /usr/bin/composer \
  && composer self-update --1 \  --> ここ
  && composer config -g repos.packagist composer https://packagist.jp \
  && composer global require hirak/prestissimo \
  && chown www-data:www-data /var/www \
  && mkdir -p ${APACHE_DOCUMENT_ROOT}/var \
  && chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT} \
  && find ${APACHE_DOCUMENT_ROOT} -type d -print0 \
  | xargs -0 chmod g+s \
  ;
```

## 再現手順(Procedure)
1. ec-cubeのサイトから最新版をダウンロード
2. プロジェクト直下で`docker-compose up -d`

### 環境 (environment)
+ EC-CUBE: 4.0.5

## 関連情報 (Ref)
https://getcomposer.org/download/

**Comment by Ippey** [comment]
すいません。4.0のブランチはselfupdateしてますね。。
ec-cubeのサイトからダウンロードしたときだけの現象でした。
後日のリリースでダウンロードファイルも対応される予定でしたら、こちらクローズでお願いします。

**Comment by okazy** [comment]
@Ippey 
ご報告ありがとうございます。
4.0の最新ブランチでは対応できていました。

ダウンロード版も次のバージョンから対応予定ですのでこちらはクローズさせていただきます。
