### ISSUE TITLE
ファイルアップロードが可能な機能を無効化するオプション

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5059]
## 概要(Overview)
- 悪意のあるユーザーがプラグインのアップロードを悪用して攻撃するケースがあるため、プラグインのアップロードを無効化して防御する
- プラグインのアップロードは常時利用する機能ではないため、必要な時のみ有効化することで、ある程度の対策になると思われる
- このオプションは環境変数で指定する。(管理画面から設定可能とすると、攻撃者が有効化できてしまう可能性があるため)
- #4698 も併わせて検討が必要

## 期待する内容(Expect)  or 要望 (Requirement)
- 必要な場合のみ、プラグインのアップロードを有効化できる

### 環境 (environment)
+ EC-CUBE: 4.0.x

**Comment by okazy** [comment]
2021/6/17 セキュリティ対策検討会より

ファイル管理やテンプレートの編集なども制限も考えられる
4.1.x のマイナーバージョンでの対応も可能

**Comment by chihiro-adachi** [comment]
#5402 で対応
