### ISSUE TITLE
CSPヘッダーでの外部スクリプト制御

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#5061]
## 概要(Overview)

[CSPとは](https://developer.mozilla.org/ja/docs/Web/HTTP/CSP)

実行を許可するスクリプトの正しいドメインをブラウザーに向けて指定することにより、 XSS の発生する箇所を削減・根絶することができます。

## 期待する内容(Expect)  or 要望 (Requirement)

CSPヘッダーの指定。
ただし、デフォルトでCDNなどドメイン外のスクリプトも利用しているので考慮が必要。
また、カスタマイズも考慮し、許可ドメインを追加できる拡張機構も必要。
既存サイトのバージョンアップを考え、無効化できる機能も検討。

## 実現可能性

現時点で不明、調査から。

## 対応できるバージョン

4.1 以降で検討。
マイナーバージョンで実現できるかは現時点で不明。

**Comment by okazy** [comment]
4.1 で CSP ヘッダーの導入も検討しましたが、カスタマイズの難易度が高くなってしまうため、4.1 での対応を見送りました。

デフォルトでの対応は難しいですが、カスタマイズなどで対応したい需要はあるかもしれませんので、サンプルの実装はあってもいいかもしれません。

**Comment by shinya** [comment]
現状実現が難しいため、本Issueはクローズします。
