### ISSUE TITLE
フロント入力項目のサニタイズを追加/強化

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#5063]
## 概要(Overview)

現状の仕様だと、例えば `<script>` のような文字列を、フロント画面から名前や住所として登録できる。
名前や住所として明らかに不適切で、攻撃の可能性のある入力はそもそも入力できないようにしたい。

## 期待する内容(Expect)  or 要望 (Requirement)

特定文字、文字列に対してバリデーションか、サニタイズの処理を追加。
できればデフォルトで有効な機能とし、必要な場合に明示的に外せるようにする。

## 実現可能性

色々なレイヤー/影響範囲での対策が考えられるため、どの方針が良いかから検討が必要。

## 対応できるバージョン

4.1 以降で検討。
マイナーバージョンで実現できるかは現時点で不明。

**Comment by chihiro-adachi** [comment]
サンプルレベルですが、以前こんなものを作りました。
フロントへのrequest bodyをチェックし、問題あればエラーにします。
https://gist.github.com/chihiro-adachi/2959de58f4028adada7db70527153def

これが必ずしも正とは考えていないので、議論のたたきとしていただければ幸いです。

**Comment by okazy** [comment]
上記サンプルについて
Symfony Event を利用するため、プラグインでも提供可能
パフォーマンスへの影響は確認する必要がある
検知条件は編集可能なようにすると良さそう。（管理画面で編集できるようにするかは要検討）

**Comment by kurozumi** [comment]
こちらのSymfony Bundleはいかがですか？
https://github.com/Exercise/HTMLPurifierBundle

こちらのSymfony Bundleです。
http://htmlpurifier.org/


試してみましたけど、<script>や<script、<imgなどを入力してサブミットしたら削除されました。
設定はかんたんで、バンドルをインストールしてFormTypeに専用のオプションを追加するだけでした。

**Comment by kurozumi** [comment]
> できればデフォルトで有効な機能とし、必要な場合に明示的に外せるようにする。

こちらの件もAbstractTypeExtensionでかんたんに対応できそうです。

**Comment by kurozumi** [comment]
プラグイン化してみました。

https://github.com/kurozumi/HTMLPurifier

**Comment by okazy** [comment]
ありがとうございます！
プラグインの内容確認しました。
実装もシンプルで有効な対応だと思います。
チェック部分をメンテナンスされているライブラリに任せられるのも良いと思いました。

~~管理画面でもデフォルトで入力不可となると思いますので、 `<img>` 等のHTMLタグを許可するところは明示的にオプションを指定してやる必要がありますね。
また既存のプラグインにも影響が予想されますので、マイグレーションガイドとリリースノートでの説明は必須かと思います。~~
フロントのみにしていただいていました。見逃していました。
https://github.com/kurozumi/HTMLPurifier/blob/2128941156b08b25c45ac2a09aa203b71f154847/Form/Extension/TextTypeExtension.php#L35

**Comment by kurozumi** [comment]
@okazy 

もし問題なければ、無料でこのプラグインを譲渡するのでEC-CUBE公式プラグインとして公開してもらえませんか？
公式プラグインのほうがより多くのユーザーに利用されると思うので。

**Comment by okazy** [comment]
@kurozumi 
プラグインのご提供感謝します 🙏 

（まだ社内で検討できていないため個人の意見となります。）
セキュリティ強化のため公式プラグインとして提供ができれば嬉しいので、社内調整したいと思います。

EC-CUBE 4.0 に対しては互換性の観点からプラグインの提供が良いかと思っています。
（どの程度影響があるか調査してからにはなりますが、）こちらの機能は EC-CUBE 4.1 では標準の機能として搭載したいと思っています。
EC-CUBE 4.1 の本体機能として取り込ませていただくことも可能でしょうか？

**Comment by kurozumi** [comment]
@okazy 

本体に取り込んでいただいて問題ないです。

**Comment by okazy** [comment]
#5081 で対応いただきましたのでクローズします。
ありがとうございました。
