### ISSUE TITLE
管理ページ>ファイル管理ページが開けない

### ISSUE THREAD

**Issue by genzouw** [EC-CUBE/ec-cube#507]
デモサイトで再現しました。

![bug003](https://cloud.githubusercontent.com/assets/29957/8448175/14105eae-1fff-11e5-945c-31d1c369af04.gif)

**Comment by chihiro-adachi** [comment]
@genzouw
ありがとうございます。デモサイト管理画面は、一部機能を制限しています(ファイルのアップロードやメンバ管理など)。たいへん恐縮なのですが、ご自身の開発環境でお試しいただけるとありがたいです。
