### ISSUE TITLE
管理ページ>セキュリティ管理ページが開けない

### ISSUE THREAD

**Issue by genzouw** [EC-CUBE/ec-cube#508]
デモサイトで再現しました。

![bug002](https://cloud.githubusercontent.com/assets/29957/8448180/26e51614-1fff-11e5-820d-3038221fc790.gif)

**Comment by chihiro-adachi** [comment]
@genzouw
ありがとうございます。デモサイト管理画面は、一部機能を制限しています(ファイルのアップロードやメンバ管理など)。たいへん恐縮なのですが、ご自身の開発環境でお試しいただけるとありがたいです。
