### ISSUE TITLE
無駄なログ出力の抑制

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#5082]
## 概要(Overview)
現在のデフォルトの設定では、site, admin, frontでログが出力されるが、```prod```環境であったとしてもそれぞれほぼ同じ様な内容が出力される。また、symfonyやcomposerのライブラリに関する``` Deprecated```や、 ```security.INFO``` ```ront.INFO``` など本番環境では必要無さそうなapacheのアクセスログみたいなものが大量に出力されて見辛いしログファイルがディスクを圧迫したりする。

## 期待する内容(Expect)  or 要望 (Requirement)
prod環境ではERRORなどクリティカルなエラーが発生した場合にのみ詳細を出力する様にしたい
参考:  https://symfony.com/doc/3.4/logging.html

### 環境 (environment)
+ EC-CUBE: 4.0.5

## 関連情報 (Ref)
ref #4668

**Comment by watarukashii** [comment]
本件、私も気になって調べて改善策をご提案させていただきますので、ご検討頂くことは可能ですか。

検討内容

1. `Deprecated` エラー
2. https://github.com/EC-CUBE/ec-cube/blob/4.1/src/Eccube/EventListener/LogListener.php にて出力される「INIT」「PROCESS START」「LOGIC START」「LOGIC END」「PROCESS END」

修正内容

1. `Deprecated` エラー

symfony4.1 系からは、error_reporting から除外対象はログに出力されなくなったということです。
ただ、symfony3.4 系では、monolog の修正が必要とのことで合わせて画像添付しております。

・./index.php にて `error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);` 
・./app/config/eccube/packages/prod/monolog.yml の調整

<img width="802" alt="SS-screenshot- 2022-02-25 12 52 08" src="https://user-images.githubusercontent.com/2732196/155650476-02ef5fd0-014e-4828-be1c-b0b1bb546c0d.png">

<img width="576" alt="SS-screenshot- 2022-02-25 12 52 24" src="https://user-images.githubusercontent.com/2732196/155650486-2b254a0f-73c6-48e4-88b8-4bb2d1bfca3a.png">

参考URL
https://github.com/symfony/symfony/issues/26267#issuecomment-820408988

2. https://github.com/EC-CUBE/ec-cube/blob/4.1/src/Eccube/EventListener/LogListener.php にて出力される「INIT」「PROCESS START」「LOGIC START」「LOGIC END」「PROCESS END」

ログレベルがinfo だったのと、本番モードは不要かと考えており info -> debug に変えるというのはいかがでしょうか？
あわせて、./app/config/eccube/packages/prod/monolog.yml の調整を行っております。

<img width="666" alt="SS-screenshot- 2022-02-25 13 21 05" src="https://user-images.githubusercontent.com/2732196/155653155-769a18cd-fbcb-400b-a1b6-35b5d1e6f434.png">


まとめ

上記の対応で、一番多かったDeprecatedエラーは本番モードでなくなり、スッキリとしたログが閲覧が可能となりました。

関連課題

https://github.com/EC-CUBE/ec-cube/issues/5082
https://github.com/EC-CUBE/ec-cube/issues/4668
https://github.com/EC-CUBE/ec-cube/issues/4775

**Comment by watarukashii** [comment]
@tao-s こんにちは、本件、下記にてプルリクエストの承認をいただきました。
問題なさそうであればissue クローズの程よろしくおねがいします。
https://github.com/EC-CUBE/ec-cube/pull/5322

**Comment by chihiro-adachi** [comment]
#5322 で対応のためクローズします
