### ISSUE TITLE
管理ページ>メンバー管理ページが開けない

### ISSUE THREAD

**Issue by genzouw** [EC-CUBE/ec-cube#509]
デモサイトで再現しました。

![bug001](https://cloud.githubusercontent.com/assets/29957/8448185/37465f18-1fff-11e5-82ac-19f179a00ea8.gif)

**Comment by chihiro-adachi** [comment]
@genzouw
ありがとうございます。デモサイト管理画面は、一部機能を制限しています(ファイルのアップロードやメンバ管理など)。申し訳ないのですが、ご自身の開発環境でお試しくださいませ。
