### ISSUE TITLE
コーディング規約についてのご意見箱

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#51]
Wikiに、[EC-CUBE3　機能要件]と[開発要件]の２つのページを作成いたしました。
[EC-CUBE3 機能要件]は変更が入ることはほとんどありません。

[開発要件]について、意見をいただきたく本Issueを作成いたしました。
[開発要件]は本リリースまで適宜ブラッシュアップをしていきたく、皆様のご意見をこちらで集約させていただきたいと思います。

**Comment by seasoftjapan** [comment]
> GETメソッドについてはFormを利用しない

これは、どういった意図からですか? キーワード検索あたりは、GET の方が都合良い気がして。

> 各種ログインサービス対応

プラグインで提供して、同様のプラグインを実装するのに不便がないように整備しておくのが良いような気がします。(なんとなく。)

**Comment by Yangsin** [comment]
[コーディング規約](https://github.com/EC-CUBE/ec-cube/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84)としてWikiをすこし整理しましたので、本チケットの役割を上記ページへのツッコミとさせていただきます。

**Comment by masahiko220** [comment]
この質問がここでは間違いでしたらすみません。
2系で利用されていた定数はどのような扱いになるのでしょうか？

**Comment by shinichi-takahashi** [comment]
`app/config/eccube/config.yml` に記載し、DICで使えるようにしたいと思っています。

**Comment by Yangsin** [comment]
議論から大分経過して状況もことなっていますので、一度クローズします。
