### ISSUE TITLE
ご注文内容のご確認の「お問い合わせ欄」に入力した文字数が多すぎるとエラー

### ISSUE THREAD

**Issue by genzouw** [EC-CUBE/ec-cube#510]
デモサイトで再現しました。

![bug005](https://cloud.githubusercontent.com/assets/29957/8448202/7dfae622-1fff-11e5-8a6b-681e5fd000e1.gif)

**Comment by chihiro-adachi** [comment]
@genzouw 
#510 で修正しました。

**Comment by Yangsin** [comment]
ご報告ありがとうございます。
