### ISSUE TITLE
新規ページの表示でシステムエラー

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#511]
ページ管理 > 新規入力 で新しくページを作成後、作成したページを表示するとエラーが表示されます。

ログを見たところ、UserDataController::index の $PageLayout 取得時の引数が「device_type_id」になっていますが、「DeviceType」だと思います。

また、テンプレートファイルの取得処理で getTemplatePath メソッドを使用していますが存在しません。

Resource/sql の初期SQLで dtb_page_layout_page_id_seq のシーケンス値が間違っています。「31」にしないと2回ほどエラーが表示されます。

**Comment by chihiro-adachi** [comment]
@shhirose 
ありがとうございます.
#515 で修正しました.

**Comment by basseyboost** [comment]
こちら更新後に新規ページは見れるようになったのですが、以下の不具合が出ています。

コンテンツ管理＞ページ管理
TOPページと新規ページ以外のページを更新しようとすると、
URL部分に「有効な値ではありません。」と表示されて更新できません。

「MYページ/お届け先変更」に関しては。
「※ 同じURLのデータが存在しています。別のURLを入力してください。」という表示も発生します。

3.0.0をインストーラー版から以下のファイルのみを上書きして検証しました。
src/Eccube/Controller/UserDataController.php
src/Eccube/ControllerProvider/FrontControllerProvider.php
src/Eccube/Form/Type/MainEditType.php
src/Eccube/Resource/sql/insert_data_pgsql.sql
（やり方あってるのかよくわからないのですが…）

[PHP]   5.5.3
[データベース]    MySQL 5.5.33
[WEBサーバ]  MAMP
[ブラウザ]  safari
