### ISSUE TITLE
Web API プラグインの初期インストール時に生成される鍵がパッケージに入る

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube#5117]
## 概要(Overview)

Web API プラグインを初期インストールにした際に入る問題なので、Web API プラグイン側ではなくこちらのリポジトリに Issue を作成しています。

Web API プラグインのインストール時に秘密鍵と公開鍵が生成され、 `app/PluginData/Api/oauth/` 配下に保存される。
その状態でパッケージングをするとパッケージに鍵が入ってしまう。

```
ll eccube-4.1-beta3/app/PluginData/Api/oauth/
total 16
-rw-rw-rw-@ 1 hideki_okajima  staff   3.2K  8 16 00:47 private.key
-rw-rw-rw-@ 1 hideki_okajima  staff   800B  8 16 00:47 public.key
```

## 期待する内容(Expect)  or 要望 (Requirement)

パッケージに秘密鍵/公開鍵が含まれない OR EC-CUBE のインストール時に確実に変更される。

## 再現手順(Procedure)

EC-CUBE 4.1-beta3 のパッケージをダウンロードして解答。
`app/PluginData/Api/oauth/` 配下に鍵が保存されている

### 環境 (environment)
+ EC-CUBE: 4.1-beta3

**Comment by chihiro-adachi** [comment]
@okazy 
ApiCompilerPassで鍵の再生が行わるため、空の鍵をパッケージ内においておけば、インストール画面にアクセスしたタイミング もしくはキャッシュクリアのタイミングで再生成されます。
https://github.com/EC-CUBE/eccube-api4/blob/master/DependencyInjection/Compiler/ApiCompilerPass.php#L90

ただ再生成の判定に不具合があるため、API側の修正も必要になります。
https://github.com/EC-CUBE/eccube-api4/issues/117

**Comment by okazy** [comment]
調査ありがとうございます！大きな影響なく対応できそうで良かったです 🙏

**Comment by chihiro-adachi** [comment]
#5126 で対応
