### ISSUE TITLE
4.1-beta3：2段階認証プラグインをインストールした状態でのバージョンアップでエラー

### ISSUE THREAD

**Issue by matsuoshi** [EC-CUBE/ec-cube#5121]
## 概要(Overview)
4.0.6-p1 に二段階認証プラグインをインストールした状態で、4.1 へのアップデートを行うと、
管理画面ログイン時に 500エラーが発生する

## 再現手順(Procedure)

- EC-CUBE 4.0.6-p1 に対し、[2段階認証プラグイン](https://www.ec-cube.net/products/detail.php?product_id=1750)をインストール → 有効化 → 無効化
- 4.0.1-beta3 へのバージョンアップ実施 ([バージョンアップ手順](https://github.com/EC-CUBE/doc4.ec-cube.net/pull/215))

実施後、管理画面ログイン画面にて、以下のエラー発生

```
HTTP 500 Internal Server Error
Attempted to call an undefined method named "isTwoFactorAuthEnabled" of class "Eccube\Entity\Member".

Symfony\Component\Debug\Exception
UndefinedMethodException
in src/Eccube/EventListener/TwoFactorAuthListener.php (line 96)
```

```
if (
    ($Member = $this->requestContext->getCurrentUser())
    && $Member instanceof Member
    && $Member->isTwoFactorAuthEnabled()
    && !$this->twoFactorAuthService->isAuth($Member)
) {
    // トークン入力
```

なお、2段階認証プラグインをインストールしていない EC-CUBE のバージョンアップでは、この問題は発生しませんでした。

### 環境 (environment)
+ EC-CUBE: 4.1-beta3
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@matsuoshi 
app/proxy/entity/src/Eccube/Entity/Member.phpが古いままでした。

[proxyの再生成](https://github.com/EC-CUBE/doc4.ec-cube.net/pull/215/files#diff-fef4cbe15ac80014b4f840d2ac79b8e974d83edd95b87e64d0f4cc1e4e84ab1aR190)は行っているものの、プラグインが無効化されているので更新されなかったようです。

プラグインは有効化のままでアップデート実施でよいかもしれません。(テーブル名などは重複なかったと思うので、システムエラーになることはないはず)

**Comment by matsuoshi** [comment]
@chihiro-adachi ありがとうございます、プラグイン有効化のままでバージョンアップを試したところ、以下のエラーになりました

```
+ bin/console cache:clear --no-warmup

In DefinitionErrorExceptionPass.php line 54:

  Cannot autowire service "Plugin\Taba2FA\Controller\Taba2FAController": argument "$memberRepository" of
method "__construct()" references class "Eccube\Repository\memberRepository" but no such service exists.
Did you mean "Eccube\Repository\MemberRepository"?
```

`MemberRepository` の大文字小文字の違いのようで、そこを修正して再実施してみたところ、続いて以下のエラーとなりました

```
% bin/console cache:clear --no-warmup

In DefinitionErrorExceptionPass.php line 54:

  Cannot autowire service "Plugin\Taba2FA\Taba2FAEvent": argument "$tokenStorage" of method "__construct()"
references class "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage" but no such
service exists. Try changing the type-hint to "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface"
instead.
```

`TokenStorage` → `TokenStorageInterface` ?
ひとまずご報告まで

**Comment by matsuoshi** [comment]
@chihiro-adachi 
2段階認証プラグインを4.1に対応させたうえで、プラグインを有効化したまま本体を4.1にバージョンアップすることで、エラーは解消されました

なお、プラグインを無効化して本体をバージョンアップした場合も、プラグインを有効化 → proxyの再生成、という手順でエラーが解消することを確認できました

**Comment by chihiro-adachi** [comment]
@matsuoshi 
ありがとうございます。
アップデート手順側にも記載しました。
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/215#issuecomment-912406922

手順側で検討できればと思いますので本issueはクローズします。
