### ISSUE TITLE
JSライブラリはすべて npm で管理したい

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5185]
## 概要(Overview)
現在、 JSライブラリは以下の方法で参照している
- script タグで CDN を参照
- `html/template/<template name>/assets` 以下に同梱

利用している JS ライブラリのバージョンは管理されておらず、とても古いバージョンを使用していたり、ページによってバージョンが異なったりする場合がある。

| パッケージ名                         | 利用中バージョン                   | 最新バージョン                            |
|--------------------------------------|------------------------------------|-------------------------------------------|
| IE10 viewport hack                   | 不明                               |                                           |
| html5shiv                            | 3.7.2                              | 3.7.3                                     |
| respond                              | 1.4.2                              | 1.4.2                                     |
| jquery                               | 3.3.1                              | 3.6.0                                     |
| jquery                               | 3.5.1                              | 3.6.0                                     |
| bootstrap                            | 3.3.4                              | 3.4.1                                     |
| bootstrap                            | 4.3.1                              | 4.4.1                                     |
| yubinbango                           | 不明                               |                                           |
| moment                               | どのバージョンを同梱しているか不明 | 2.29.1                                    |
| tempusdominus-bootstrap-4            | 5.0.1                              | 5.39.0                                    |
| spin.js                              | 不明                               |                                           |
| ace                                  | 1.2.8                              | 1.4.12                                    |
| popper.js                            | 1.14.7                             | 2.10.1                                    |
| jquery.qrcode                        | 1                                  |                                           |
| jquery-ui                            | 1.12.1                             | 1.12.1(もうすぐ1.13.0 がリリースされそう) |
| jquery-ui                            | 1.10.4                             |                                           |
| jquery-ui                            | 1.11.1                             |                                           |
| jQuery File Upload Plugin            | 5.42.3                             | 10.31.0                                   |
| jQuery Iframe Transport Plugin       | 1.8.3                              |                                           |
| jQuery File Upload Processing Plugin | 1.3.1                              |                                           |
| jQuery File Upload Validation Plugin | 1.1.3                              |                                           |
| chart.js                             | 2.7.2                              | 3.5.1                                     |
| chart.js                             | 2.3.0                              |                                           |
| loader.js( sitekit で使用)                            | 不明                               |                                           |
| Ladda                                | 1.0.6                              |                                           |
| slick.js                             | 1.6.0                              | 1.8.0                                     |
| bootstrap-colorpicker                | 3.2.0                              |                                           |
| bootstrap-datetimepicker             | リンク切れのバグ                   |                                           |

## 期待する内容(Expect)  or 要望 (Requirement)
JSライブラリはすべて npm で一元管理し、セキュリティアドバイザリが発表された場合は迅速に対応できるようにしたい。
npm で管理することにより、 dependabot による通知を受け取ることができる

### 環境 (environment)
+ EC-CUBE: 4.1.0

## 関連情報 (Ref)
- #5184 
- #5025
- #4279

**Comment by tao-s** [comment]
jQuery関連がひどいな

**Comment by tao-s** [comment]
#4828 
#4829

**Comment by chihiro-adachi** [comment]
npm管理する(package.jsonで管理)することで、dependabotのアラートを受け取ることができる

**Comment by chihiro-adachi** [comment]
#5383 で対応
