### ISSUE TITLE
基本設定画面のgood_tradedとmessageの文字数制限の修正

### ISSUE THREAD

**Issue by joolenkoyama** [EC-CUBE/ec-cube#5193]
## 概要(Overview)
Eccube\Form\Type\Admin\ShopMasterType.php
の
good_traded
と
message
の文字数制限がEntityの文字数を超えている

## 期待する内容(Expect)  or 要望 (Requirement)
Eccube\Form\Type\Admin\ShopMasterType.php
の
good_traded
と
message
の
'constraints' の Assert\Length
を
'eccube_lltext_len'
から
'eccube_ltext_len'
へ変更

## 再現手順(Procedure)
管理画面-[店舗設定]-[基本設定]画面の
取り扱い商品説明文、店舗からのメッセージ それぞれに
4001文字以上を登録する

### 環境 (environment)
+ EC-CUBE: 4.1

**Comment by chihiro-adachi** [comment]
#5205 で修正しました。
