### ISSUE TITLE
プラグインのアップロード時にファイルが選択されたかわからない

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#520]
プラグインをアップロードする際に、tarファイルを選択した後に選択されたファイル名が表示されないため、どうなっている状態かわかりません。

また、登録ボタンを押下した後に正常に終了したメッセージが表示されませんでした。

**Comment by Yangsin** [comment]
3.0.3でファイル名が表示されるようになりましたので、クローズいたします。
