### ISSUE TITLE
商品で使用中の規格分類を削除できてしまう

### ISSUE THREAD

**Issue by ykato** [EC-CUBE/ec-cube#5203]
## 概要(Overview)

商品で使用中の規格分類を削除できてしまうため、商品一覧画面でシステムエラーが発生する。

## 期待する内容(Expect)  or 要望 (Requirement)

商品で使用中の規格分類は削除不可とする。

## 再現手順(Procedure)

- 商品で使用中の規格分類を削除する。
初期状態のデータであれば、「フレーバー」の中の「チョコ」等。
- 商品一覧画面を表示するとシステムエラー

### 環境 (environment)
+ EC-CUBE: 4.0.6
+ PHP: 7.3.31
+ DB:
  - SQLite

## 関連情報 (Ref)

EC-CUBE3の時の #796 の再発のようです。

**Comment by chihiro-adachi** [comment]
@ykato 
ありがとうございます。

以下環境で試してみましたが、 `関連するデータがあるため「XXX」を削除できませんでした`と外部キー制約違反で削除はできませんでした。

- EC-CUBE: 4.0.6-p1
- DB:PostgreSQL

SQLiteのみ発生する事象でしょうか？
MySQLでも再現するかご確認いただくことはできますか？

**Comment by chihiro-adachi** [comment]
再現状況が不明なのでクローズします。
