### ISSUE TITLE
無効にした商品規格がマイページ再注文から購入されてしまう

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#5210]
## 概要(Overview)
マイページの注文履歴 - 再注文ボタンから無効または削除されている商品規格の注文が可能になっている

## 期待する内容(Expect)  or 要望 (Requirement)
無効または削除されている商品規格は注文できない

## 再現手順(Procedure)
1. 規格を設定した商品でフロントから1度目の購入を行う
2. 1で購入した商品を管理画面の商品規格登録から無効にする
3. マイページの注文履歴から再注文ボタンを押下しカートに追加する
4. 購入手続きを進め購入完了する(→注文完了してしまう)

### 環境 (environment)
+ EC-CUBE: 4.1

**Comment by chihiro-adachi** [comment]
@dk-umebius 
ありがとうございます。
再現確認しました。

PurchaseFlowでのチェック漏れですね。

**Comment by dk-umebius** [comment]
@chihiro-adachi 
ご確認ありがとうございます。一応PRさせていただきました。
実際の案件でProductStatusValidatorに追記したのでそのままPRしたのですが、新規クラスの方が良いでしょうか？

**Comment by chihiro-adachi** [comment]
@dk-umebius 
ありがとうございます！
そうですね、修正範囲増えるので迷ったんですが、役割が異なるので新規クラスのほうが望ましいかと思いました。

**Comment by chihiro-adachi** [comment]
@dk-umebius 
> そうですね、修正範囲増えるので迷ったんですが、役割が異なるので新規クラスのほうが望ましいかと思いました。

といってましたが、ProductStatusValidatorでもそれほど違和感はないので、ProductStatusValidatorでの修正でも問題ないかと思います。

**Comment by chihiro-adachi** [comment]
#5211 で修正しました。
