### ISSUE TITLE
デバックモード有効時に警告を画面出力する

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#5212]
## 概要(Overview)

デバックモード有効時に警告を画面出力したい

## 期待する内容(Expect)  or 要望 (Requirement)

Web公開された状態でデバックモードを有効化しているケースの報告がある
当然ながら、デバックモードを利用した攻撃も可能なので
あやまってデバックモードのまま公開が続けられるようなことがないよう
画面に警告を出力するようにしたい

**Comment by xuelian311** [comment]
https://github.com/EC-CUBE/ec-cube/issues/4271 と合わせて実装を検討してみます。

**Comment by dotani1111** [comment]
マージされたためクローズします。
