### ISSUE TITLE
パッケージング時に composer.json の PHPバージョンが更新されてしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5214]
## 概要(Overview)
- refs #5194 
- refs https://github.com/EC-CUBE/ec-cube/pull/4634
パッケージング時にプラグインをインストールするため、 composer.json の `config.platform.php` のバージョンが更新されてしまう

## 期待する内容(Expect)  or 要望 (Requirement)
GitHub の composer.json と相違ない状態とする

## 再現手順(Procedure)
https://github.com/EC-CUBE/ec-cube/releases/tag/4.1.0 からパッケージ済みのファイルをダウンロードして composer.json を確認

### 環境 (environment)
+ EC-CUBE: 4.1.0

**Comment by chihiro-adachi** [comment]
以下対応が必要かと思われます。
- 7.3のパッチバージョンをどのバージョンにするかを定義 
- package.shで、プラグインインストール後に`config.platform.php`の値を再更新

**Comment by matsuoshi** [comment]
パッチバージョンは特に依存関係がないようであれば、7.3.0 として進めたいと考えています

**Comment by carkn** [comment]
#5219にてマージしていますので、こちらはクローズさせていただきます。
