### ISSUE TITLE
キャッシュをクリアすると一部プラグインが無効になる

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#5215]
## 概要(Overview)
4.1 キャッシュをクリアすると、一部のプラグインが無効になってしまう。
無効化、有効化をすると正常に戻る。共通することはオーナーズストアで購入、管理画面からインストールしたプラグインということ。

問題が発生したプラグイン

- OrderPlus

## 期待する内容(Expect)  or 要望 (Requirement)
キャッシュクリアしても正常に無効にならない。

## 再現手順(Procedure)

オーナーズストアから該当プラグインを購入、管理画面からインストール、キャッシュをクリア

### 環境 (environment)
+ EC-CUBE: 4.1.0
+ PHP: 7.4.3
+ DB:
  - PostgreSQL 13.4
+ GCE+Linux web 5.11.0-1018-gcp 20~20.04.2-Ubuntu SMP Fri Sep 3 01:01:37 UTC 2021 x86_64

**Comment by chihiro-adachi** [comment]
@tao-s 
ありがとうございます、確認してみます。
キャッシュクリアは、管理画面のコンテンツ管理＞キャッシュ管理でされてます？

**Comment by tao-s** [comment]
@chihiro-adachi 管理画面、コンソールから、両方で同じになります。管理画面のプラグイン一覧ではキャッシュクリアした状態でもプラグインは有効と表示されています

**Comment by chihiro-adachi** [comment]
@tao-s 
ありがとうございます。
こちらでも事象確認してみます。

**Comment by tao-s** [comment]
プラグインをバージョンアップしたら解消されました
