### ISSUE TITLE
4.1.1 リリース計画

### ISSUE THREAD

**Issue by matsuoshi** [EC-CUBE/ec-cube#5221]
## 基本方針
マイナーバージョンとして以下の方針で開発を行います。

- 不具合改修および機能改善を行う。
- 既存プラグイン/デザインテンプレートとの互換性を最大限考慮する。

## 開発スケジュール

- 2021/11/30 ソースコード凍結
- 2021/12/21 4.1.1 リリース

## 主要な対応内容

- 無効にした商品規格がマイページ再注文から購入されてしまう問題の対応 #5211 #5210
- 受注編集時にすでに受注にセットされている顧客情報を書き換えない #4997
- 受注登録でお届け先に氏名を表示する #4980 #5213
- 定休日カレンダー #4974

※ EC-CUBE4.1.1で取り込む予定の改修一覧
https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+milestone%3A4.1.1+is%3Aclosed+base%3A4.1+is%3Amerged

### その他 

Issueのマイルストーンの設定は現時点での予定であり、変更となる可能性があります。
- 積極的に対応を予定しているものを [4.1.1](https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.1.1) としてマイルストーン設定しています。
- Pull Request 未経験の方もぜひ開発にご協力ください。修正が容易と思われるものや、仕様が明確なものには、<a class="d-inline-block IssueLabel v-align-text-top" style="background-color: #5ae833; color: #000000" title="簡単に修正できそうなもの" href="/EC-CUBE/ec-cube/issues?q=is%3Aissue+is%3Aopen+label%3AEasy">🏷 Easyラベル</a>をつけています。

## 互換性についての情報

4.1.0 からシステム要件が PHP 7.3以降となったことにあわせ、PHPのバージョンのチェックを追加しています。これにより、PHP 7.3.0 未満の環境では動作しなくなりますのでご注意ください。
https://github.com/EC-CUBE/ec-cube/pull/5219

マイナーバージョンの開発では互換性を維持するために、以下の観点でPullRequestをレビューしています。

#### 既存機能の仕様変更
[`affected:外部仕様` ラベル](https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Aaffected%3A%E5%A4%96%E9%83%A8%E4%BB%95%E6%A7%98+is%3Aclosed+milestone%3A4.1.1+is%3Amerged)をご確認ください

#### フックポイントの呼び出しタイミングの変更
変更はありません

#### フックポイントのパラメータの削除・データ型の変更
変更はありません

#### twigファイルに渡しているパラメータの削除・データ型の変更
変更はありません

#### Serviceクラスの公開関数の、引数の削除・データ型の変更
変更はありません

#### 入出力ファイル(CSVなど)のフォーマット変更
変更はありません

**Comment by chihiro-adachi** [comment]
#5230 の取り込みをもって、4.1.1のソースコード凍結とさせていただきます。
PRいただいた皆様、誠にありがとうございました 👍

**Comment by tao-s** [comment]
@chihiro-adachi 4.1.0の時みたいにパフォーマンスもチェックして欲しいです

**Comment by chihiro-adachi** [comment]
@tao-s 

> 4.1.0の時みたいにパフォーマンスもチェックして欲しいです

はい、その予定です。
今検証準備すすめてるので、結果でたらissueたてますー

**Comment by matsuoshi** [comment]
パフォーマンス関連の issue はこちらでした！
https://github.com/EC-CUBE/ec-cube/issues/5247

4.1.1 はリリースされましたため、こちらはクローズいたします
