### ISSUE TITLE
Let's EncryptのルートCA期限切れでプラグインのインストールが出来ない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5224]
## 概要(Overview)
オーナーズストアからプラグインのインストールに失敗する

## 期待する内容(Expect)  or 要望 (Requirement)
ルート証明書方が期限切れが原因だが、サーバー環境をいじれないことも多いので、EC-CUBE側で対応出来るのであれば対応したい
オーナーズストアの証明書をLet's Encryptじゃないものにしてくれればそれで解決する問題ではある

## 再現手順(Procedure)
オーナーズストアからプラグインのインストールをしようとする

### 環境 (environment)
+ EC-CUBE: 4.1.0
+ PHP: 7.3.29
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=26341&forum=16&post_id=104994#forumpost104994

**Comment by nobuhiko** [comment]
src/Eccube/Service/Composer/ComposerApiService.php で
secure-http false
verify_peer false
disable-tls true
など試してみたが、うまく行かず、なにかいい方法ないですかね？
https://stackoverflow.com/questions/20921486/composer-to-disable-https-completely

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます。
package-apiの証明書を別のものに変更する方向で検討しています。

**Comment by kiy0taka** [comment]
`package-api.ec-cube.net`(4.0系)、`package-api-c2.ec-cube.net`(4.1系) の証明書をそれぞれLet's EncryptからAlphaSSLに変更しました。
