### ISSUE TITLE
非会員の Eccube\Entity\Cart::getCustomer() をコールするとシステムエラーになる

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5226]
## 概要(Overview)
非会員の Eccube\Entity\Cart::getCustomer() をコールすると以下のシステムエラーになる

```
Return value of Eccube\Entity\Cart::getCustomer() must be an instance of Eccube\Entity\Customer, null returned
```

## 期待する内容(Expect)  or 要望 (Requirement)
null を返却する

## 再現手順(Procedure)
非会員状態でカートに商品を入れて以下のプログラムを実行する
```php
// 1 は該当のカートID 
$Cart = $this->entityManager->getRepository(\Eccube\Entity\Cart::class)->find(1);
$Cart->getCustomer();
```

### 環境 (environment)
+ EC-CUBE: 4.1.0
+ PHP: 7.4

**Comment by chihiro-adachi** [comment]
#5227 で修正されました。
