### ISSUE TITLE
ゲスト購入時、「ご注文手続き」の「お届け先を追加する」押下時にシステムエラーが発生する

### ISSUE THREAD

**Issue by oywc410** [EC-CUBE/ec-cube#5229]
## 概要(Overview)
ゲストで購入の場合「ご注文手続き」ページの「お届け先を追加する」を押すとシステムエラー

## 再現手順(Procedure)
1. ゲストで任意商品を購入し「ご注文手続き」までに進みます
2. お客様情報の「変更」ボタンをクリックしたあと「ＯＫ」ボタンをクリックする
3. 「お届け先を追加する」ボタンをクリックする

## バージョン

ECCUBE4.1

## 関連情報 (Ref)

![screencapture-eccube4-design-4-1-0-cos-sundaysys-shopping-shipping-multiple-2021-11-24-17_09_51](https://user-images.githubusercontent.com/14345299/143254135-0cacd0f4-1a1e-4ab1-8ad9-2bfb32907db3.png)

**Comment by chihiro-adachi** [comment]
#5230 で修正しました。
