### ISSUE TITLE
お問い合わせ画面の「お問い合わせ内容」ラベルを押下すると異なるフォームがフォーカスされる

### ISSUE THREAD

**Issue by tatsuishi** [EC-CUBE/ec-cube#5232]
## 概要(Overview)
お問い合わせ画面の「お問い合わせ内容」ラベルを押下すると異なるフォームがフォーカスされる

## 期待する内容(Expect)  or 要望 (Requirement)
「お問い合わせ内容」ラベルを押下した際に「お問い合わせ」フォームをフォーカスさせる

## 再現手順(Procedure)

1. フロントのお問い合わせ画面で「お問い合わせ内容」ラベルを押下する
2. 「メールアドレス」フォームがフォーカスされてしまう

### 環境 (environment)
+ EC-CUBE: 4.1

## 関連情報 (Ref)
![issue_image](https://user-images.githubusercontent.com/36718825/143364656-c18df9fa-d0ab-4d5d-b250-9860c4aa5734.png)

**Comment by chihiro-adachi** [comment]
#5234 で修正しました。
