### ISSUE TITLE
商品一覧やお気に入りページの商品画像の高さ固定を無くしたい

### ISSUE THREAD

**Issue by tatsuishi** [EC-CUBE/ec-cube#5248]
## 概要(Overview)
商品一覧やお気に入りページに表示される商品画像を包むタグの高さが、以下の数値で固定されてしまっている
・PC時250px
・スマホ時150px

画面幅を狭くしてレスポンシブさせた際に、高さが変わらず画像だけは小さくなるためかなり余白ができてしまう
(何度かクライアント様からも修正要望を頂いている)

## 期待する内容(Expect)  or 要望 (Requirement)
高さ固定をなくす

## 再現手順(Procedure)
ブラウザ横幅768pxにしたときの余白再現スクリーンショット

![商品一覧_768px](https://user-images.githubusercontent.com/36718825/144973750-2a339f7f-654b-4b2a-b367-4a824ebb13fe.png)

### 環境 (environment)
+ EC-CUBE: 4.1.0

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
#5249 で対応
