### ISSUE TITLE
403エラー報告 -シンボリックリンク-

### ISSUE THREAD

**Issue by fors2** [EC-CUBE/ec-cube#526]
シンボリックリンクが有効になっていないサーバで稼働させると下記エラーが発生します。
「Options FollowSymLinks or SymLinksIfOwnerMatch is off which implies that RewriteRule directive is forbidden」

htaccessにこのように記述しておいておくと親切かと思うのですがいかがでしょうか。

```
order deny,allow
allow from all
<IfModule mod_rewrite.c>
#    Options FollowSymLinks Includes
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```

※「Options FollowSymLinks Includes」に関する記述を追加

**Comment by Yangsin** [comment]
よいと思います。

**Comment by aminotsukasa** [comment]
Options IncludesってSSIだったと思うのですが、どこかで使ってます?

特になければ
Options +FollowSymLinks 
を追加するのが適当かと思いますが…
