### ISSUE TITLE
4.1.2 リリース計画

### ISSUE THREAD

**Issue by matsuoshi** [EC-CUBE/ec-cube#5269]
## 基本方針
マイナーバージョンとして以下の方針で開発を行います。

- 不具合改修および機能改善、セキュリティ改善を行う。
- 既存プラグイン/デザインテンプレートとの互換性を最大限考慮する。

## 予定スケジュール

- 2022/1/28 ソースコード凍結
- 2022/2/21 4.1.2 リリース

## 対応内容

EC-CUBE4.1.2にて取り込む予定の改修一覧
https://github.com/EC-CUBE/ec-cube/milestone/45

マージ済みプルリクエスト一覧
https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+milestone%3A4.1.2+is%3Aclosed+is%3Amerged+base%3A4.1

### その他 

- Issue および Pull requests のマイルストーンの設定は現時点での予定であり、変更となる可能性があります。
- Pull Request 未経験の方もぜひ開発にご協力ください。修正が容易と思われるものや、仕様が明確なものには、<a class="d-inline-block IssueLabel v-align-text-top" style="background-color: #5ae833; color: #000000" title="簡単に修正できそうなもの" href="/EC-CUBE/ec-cube/issues?q=is%3Aissue+is%3Aopen+label%3AEasy">🏷 Easyラベル</a>をつけています。

## 互換性についての情報

マイナーバージョンの開発では互換性を維持するために、以下の観点でPullRequestをレビューしています。

#### 既存機能の仕様変更
[`affected:外部仕様` ラベル](https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Aaffected%3A%E5%A4%96%E9%83%A8%E4%BB%95%E6%A7%98+is%3Aclosed+milestone%3A4.1.1+is%3Amerged)をご確認ください

#### フックポイントの呼び出しタイミングの変更
変更はありません

#### フックポイントのパラメータの削除・データ型の変更
変更はありません

#### twigファイルに渡しているパラメータの削除・データ型の変更
変更はありません

#### Serviceクラスの公開関数の、引数の削除・データ型の変更
変更はありません

#### 入出力ファイル(CSVなど)のフォーマット変更
変更はありません

**Comment by chihiro-adachi** [comment]
#5282 の取り込みをもってコード凍結とさせていただきます。
PRいただいた皆様、誠にありがとうございました。

試験用のパッケージを以下で作成しています。
https://github.com/EC-CUBE/ec-cube/releases/tag/4.1.2-20220128
