### ISSUE TITLE
TemplateEvent::addSnippet()が失敗する

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/ec-cube#5273]
## 概要(Overview)
AmazonPayプラグインを利用している場合だけかもですが、``default_framte.twig``に対して``addSnippet()``すると、AmazonPayのsnippetがカート画面で消えて出力されない。

## 期待する内容(Expect)  or 要望 (Requirement)
全てのsnippetが正常に出力される。

## 再現手順(Procedure)

1. AmazonPayV2プラグインのインストール、有効化
2. テンプレートイベントで``default_framte.twig``に対して``addSnippet()``
3. カート画面に遷移、AmazonPayのスニペットが出力されていない。

### 環境 (environment)
+ EC-CUBE: 4.1.1
+ PHP: 7.4.3
+ DB:
  - PostgreSQL 13.5

**Comment by chihiro-adachi** [comment]
@tao-s 
ありがとうございます。確認してみます。

**Comment by tao-s** [comment]
プラグインをアップデートしたら解消しました。
直接的な原因はわかりませんが、一応解決済みということで
