### ISSUE TITLE
インストール時 -Step4で不適切なエラー表示-

### ISSUE THREAD

**Issue by 2stars** [EC-CUBE/ec-cube#528]
表題の件です。
正しい接続情報を入力してもデータベース接続エラーが発生しました。
ソースを追ってみると「正しい理由はPDOのDriverが組み込まれてない」ということがわかりました。
つまり画面上のエラー内容とプログラム上のエラーの内容が合致していません。

利用者は「正しく入力してるのに接続できない！」
非常によろしくないと感じました。

src/Eccube/Form/Type/Install/Step4Type.php 
buildFormメソッド内

```
try {
	$dsn = $data['database']
		. ':host=' . $data['database_host']
		. ';dbname=' . $data['database_name'];
	if (!empty($data['port'])) {
		$dsn .= ';port=' . $data['database_port'];
	}
	new \PDO(
		$dsn,
		$data['database_user'],
		$data['database_password']
	);
} catch (\PDOException $e) {
	$form['database_name']->addError(new FormError('データベースに接続できませんでした。'));
}
```

「\PDOException $e」で受け取ったメッセージを利用してないことに起因しているようです。
ちなみにPDO Driverが組み込まれてない場合のメッセージは「could not find driver」になります。

PDO Driverを組み込んでおけばそれで済むのですが…
このエラーメッセージは改善できないでしょうか。

**Comment by shinichi-takahashi** [comment]
本件、以下のシステム要件にPDOドライバは必須として表示しているため、
アプリケーションのレイヤーでエラー表示まで担保する必要はないと考えております。
もし、修正するのであれば、 `$e->message()` をそのまま出力し、Translatorで変換かますとかになるかと思います。

[システム要件](http://www.ec-cube.net/product/system.php)

**Comment by nobuhiko** [comment]
EC-CUBE2でも度々話題になっていましたが、システム要件を満たしていないことをインストール画面でアラート表示するほうがよくないですか？

**Comment by 2stars** [comment]
ご回答ありがとうございます。
トラブル防止のための処置として考えていました。

確かにシステム要件に記述があり満たしていないユーザに非があるのも理解できます。
先ほど上述のように発言したものの、
導入を支援する意味でインストーラにシステム要件へのリンクを設置するだけでも改善できると感じます。
（どちらかと言えばnobuhikoさんの発言に賛成です。）

要件を満たしているか画面表示してあげることがベストと思いますが、
優先度は低いように見受けられますのでマストではないと思います。

**Comment by Yangsin** [comment]
@2stars @nobuhiko 
インストーラーでのミスは余計なトラブルに繋がりやすいものなので、なにかしらアシストできるとよいですね。
できるなら、インストーラーのアラートで対応したいところですが、システム要件をインストーラーの画面に書いてしまうでもよさそうですね。
（リンクだとPage切れもあるので。。。）

まだまだ、細かなところにまで手がいきとどかず、よろしければプルリクエストなどでもご協力いただけますと幸いです。

**Comment by k-yamamura** [comment]
@2stars 
PDOのDriverが組み込まれていないという事ですがどのような動作環境で試されたのでしょうか。

https://github.com/EC-CUBE/ec-cube/wiki/Issuesの利用方法
こちらを参考に動作環境を記載して頂けないでしょうか。

**Comment by k-yamamura** [comment]
@2stars @nobuhiko 

システム要件を満たしているかどうかを画面表示するということについてですが、
WordpressやDrupal等のCMSのインストーラーはデータベース情報だけで事足りると思いますので、
それ以外で参考になったインストーラーが付いているWebアプリをご存知でしょうか。

また、システム要件が満たしていなかった時はインストーラー時に解決方法まで記載されているものなのでしょうか。

**Comment by nobuhiko** [comment]
Drupalのinstall.phpはこんなん書いてありますね
```
if (version_compare(PHP_VERSION, '5.2.4') < 0) {
  print 'Your PHP installation is too old. Drupal requires at least PHP 5.2.4. See the <a href="http://drupal.org/requirements">system requirements</a> page for more information.';
  exit;
}
```

**Comment by nobuhiko** [comment]
baserCMSはドライバーをチェックしてあるものだけ表示されるようになってそう？
```
	protected function _getDbSource() {
		/* DBソース取得 */
		$dbsource = array();
		$folder = new Folder();
		$pdoDrivers = PDO::getAvailableDrivers();

		/* MySQL利用可否 */
		if (in_array('mysql', $pdoDrivers)) {
			$dbsource['mysql'] = 'MySQL';
		}

		/* PostgreSQL利用可否 */
		if (in_array('pgsql', $pdoDrivers)) {
			$dbsource['postgres'] = 'PostgreSQL';
		}

		/* SQLite利用可否チェック */
		// windowsは一旦非サポート
		if (version_compare(preg_replace('/[a-z-]/', '', phpversion()), '5', '>=') && (DS != '\\')) {
			if (in_array('sqlite', $pdoDrivers)) {
				$dbFolderPath = APP . 'db' . DS . 'sqlite';
				if (is_writable(dirname($dbFolderPath)) && $folder->create($dbFolderPath, 0777)) {
					$dbsource['sqlite'] = 'SQLite';
				}
			}
		}

		/* CSV利用可否 */
		/* $dbFolderPath = APP.'db'.DS.'csv';
		  if(is_writable(dirname($dbFolderPath)) && $folder->create($dbFolderPath, 0777)){
		  $dbsource['csv'] = 'CSV';
		  } */

		return $dbsource;
	}

```

**Comment by nanasess** [comment]
> それ以外で参考になったインストーラーが付いているWebアプリをご存知でしょうか。

MovableType とか、とても親切です。

![default](https://cloud.githubusercontent.com/assets/815715/8491059/9fc34810-216e-11e5-98e6-f94ff263d8c7.PNG)

**Comment by k-yamamura** [comment]
最近はMovableTypeなんて触っていませんでしたので色々と参考になりました。ありがとうございます。

エラーが発生すればテキストエリアにエラー内容を表示すれば良いだけではないかと浅はかな考えでいました。

今回、EC-CUBE3としてはエラーが発生した際にどこまで考慮するつもりなのか疑問なのですが、
エラーを詳細に表示したから後は自分たちで解決してくださいというようにするのか、
MovableTypeのようにエラーが発生した時の解決方法まで指し示した方が良いのか、
EC-CUBE3としてはどのような方向性でいくつもりでしょうか。

インフラに詳しくない方もいるため、どこまで対処すれば良いのか難しい話だとは思いますが。

**Comment by seasoftjapan** [comment]
私も、まさか PDO を使用していると思わず、引っかかりました。他で気になる動作があり、ソースを見ながらだったので、幸い直ぐに分かりましたが。

あと、IPアドレス誤りでも、DB名にエラーが出るのも気になりました。(3.0.1)

**Comment by Yangsin** [comment]
インストーラーの初めに環境チェックとその結果のアラートが表示されるようになりましたので、クローズといたします。
