### ISSUE TITLE
eccube:composer 系のコマンドや eccube:plugin 系のコマンドが動作しない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5283]
## 概要(Overview)
Composer API v2.2 の環境で eccube:composer 系のコマンドや eccube:plugin 系のコマンドが動作しない。
エラーも出ずに黙ったままとなってしまう

<img width="697" alt="スクリーンショット 2022-01-28 16 48 30" src="https://user-images.githubusercontent.com/815715/151515214-c66addf5-fb74-4490-8b1c-6ff4690c1477.png">

- https://github.com/EC-CUBE/ec-cube/pull/5265 にて composer/composer 2.2.4 へ更新された影響と思われる
- `composer require composer/composer "~2.1.0"` で、 Composer API 2.1 に更新すると解消される

## 期待する内容(Expect)  or 要望 (Requirement)
Composer API 2.2 で eccube:composer 系のコマンドや eccube:plugin 系のコマンドが正常に実行できる

## 再現手順(Procedure)
1. `composer selfupdate` で composer 2.2.x 以降へ更新する
2. EC-CUBE4.1.2 をセットアップ(おすすめ商品プラグインがプレインストールされた状態にする)
3. `bin/console eccube:plugin:enable --code=recommend4` で、おすすめ商品プラグインを有効化する

### 環境 (environment)
+ EC-CUBE: 4.1.2(pre release)
+ PHP: 7.4.x

**Comment by kiy0taka** [comment]
Composer 2.2から変更された仕様で、Composer API利用時に `allow-plugins` を設定するかのインタラクションが発生して処理が止まってしまってました。
https://getcomposer.org/doc/06-config.md#allow-plugins

- #5290 でインタラクションを発生させないようにしました。
- 2022年7月まで `allow-plugins`を設定しなくても利用することが可能ですが、以降はプラグインがロードされなくなるので、#5291 でデフォルトで利用するプラグインは許可するようにしました。

**Comment by nanasess** [comment]
@kiy0taka #5290 を適用して動作するようになりました。ありがとうございます！

**Comment by chihiro-adachi** [comment]
#5290 #5291 取り込ませていただきました。
ご確認、ご対応ありがとうございました。
@nanasess @kiy0taka
