### ISSUE TITLE
改正商取引法の施行に伴うECカート「最終確認画面」表示項目の変更

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube#5304]
## 概要(Overview)

改正商取引法の施行に伴うECカート「最終確認画面」表示項目の変更への対応

**ディスカッションPoint**
どこまで特商法の内容を使いまししやすくするか
前提）
　* 特商法の内容なので、各サイト毎に修正する必要がある
　* 定期購入などデフォルトで提供のない機能にあわせた対応が必要

Lv1） デフォルトの特商法サンプルページの内容を、注文確認画面のテンプレートにも記載する（静的、テンプレート編集）
Lv２）2系のようにDBに入れて、注文確認画面でもDBから読み出す形にする

## 期待する内容(Expect)  or 要望 (Requirement)

購入確認画面で次の6項目を表示させる必要がある
ーーーー
1.  分量
2. 販売価格・対価
3. 支払の時期・方法
4. 引渡・提供時期
5. 申込みの撤回、解除に関すること
6. 申し込み期間（期限のある場合）
ーーーー

## 関連情報 (Ref)
［全EC対象］改正商取引法の施行に伴うECカート「最終確認画面」表示項目の変更についてのまとめ
https://eczine.jp/article/detail/11020

**Comment by chihiro-adachi** [comment]
現状の本体の表示がどこまで対応できているか一度まとめてみます

**Comment by chihiro-adachi** [comment]
4.1の確認画面です。
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/8196725/156297638-3ef28bf0-a963-4213-a616-88863544e606.png">

`3.支払の時期・方法 /  4.引渡・提供時期`に関しても、検討が必要かと思われます。

**Comment by Yangsin** [comment]
各サイト毎に異なる内容のため、個別にテンプレートを修正いただくしかなさそう

基本的に、3.0〜4.1.2の利用者は、特商法ページのテンプレートに記載されている支払い方法や引き渡し時期などを個別に転載してもらうか、特商法へのリンクをいれてもらう形になるでしょうね

4.1.xでやるなら、デフォルトのテンプレートで特商法のサンプルテキストを注文確認画面にもコピーしておいておくくらいしかできないですね

4.2以降では、2系のように、特商法の各項目をDBにいれて、確認ページで読み出すような実装も検討するか？

**Comment by Yangsin** [comment]
4.1以前では、個別に修正するものとして、4.2へマイルストーンを移しました。
4.1以前での対応方法の参考
https://www.ec-cube.net/know_how/tokuteishoutorihikihou_kaisei.php

**Comment by chihiro-adachi** [comment]
特商法設定のCMS化に伴う仕様案です。

### 画面イメージ
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/8196725/172990532-2728d3e1-c293-4eb7-af1e-0590d444c97e.png">

### 入力項目
- 名称
- 説明：テキストエリア
- 注文画面に表示：Onの場合、注文画面へ表示する
- 登録行は15行まで表示(デフォルトでは10行だが余裕をもたせておく)
  
### アクション
- 登録時はdelete/insert
- 名称・説明が未入力の場合は登録しない

### 注文画面の表示
注文画面および確認画面で以下のように出力(お問い合わせの下部)
説明はhtml許可(ただしpurifyフィルタはかけること)

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/8196725/172990979-b615afc9-d108-44be-a97c-fcf377931018.png">

### テーブル定義

dtb_tradelaw |   |   |   |  
-- | -- | -- | -- | --
id | int | primary key | not null |  
name | varchar(255) |   | nullable |  
description | varchar(4000) |   | nullable |  
sort_no | smallint |   | not null |  
display_order_screen | boolean |   | not null | default false


### 初期値

id | name | description | sort_no | display_order_screen
-- | -- | -- | -- | --
1 | 販売業者 | NULL | 1 | FALSE
2 | 代表責任者 | NULL | 2 | FALSE
3 | 所在地 | NULL | 3 | FALSE
4 | 電話番号 | NULL | 4 | FALSE
5 | メールアドレス | NULL | 5 | FALSE
6 | URL | NULL | 6 | FALSE
7 | 商品代金以外の必要料金 | NULL | 7 | TRUE
8 | 引き渡し時期 | NULL | 8 | TRUE
9 | お支払方法 | NULL | 9 | TRUE
10 | 返品・交換について | NULL | 10 | TRUE

**Comment by chihiro-adachi** [comment]
#5399 で対応
