### ISSUE TITLE
ページ編集で編集してもキャッシュが更新されず、古い情報が表示される。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#531]
ページ編集画面で既存のページを編集した際にキャッシュが更新されておらず、キャッシュを消さないと新しい情報が表示されません。

ページ編集を行った際に、該当のキャッシュファイルを削除するようにした方がいいのではと思います。

**Comment by Yangsin** [comment]
こちら3.0.3で対応済みですのでクローズします。
