### ISSUE TITLE
ページ編集のURL表記について

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#532]
ページ編集画面のURL表記が、リクエストするURLではなく、ファイルのURLになってしまっていますが、このままだとルーティングに引っかからなくなってしまします。

URLにはルーティングに引っかかるURLにし、ファイル名は別のラベルにした方がURLの貼り間違いがないかと思います。
※技術者以外はまず間違えるかと思います。

http://localhost/user_data/test.twig
↓
http://localhost/user_data/test

**Comment by Yangsin** [comment]
ご意見ありがとうございます。
#603 にてURLとフィアル名をそれぞれ登録できるようにさせていただきました。
