### ISSUE TITLE
管理画面受注登録でprototypeの__name__に指定するindexの指定の仕方について

### ISSUE THREAD

**Issue by kamotetu** [EC-CUBE/ec-cube#5320]
## 概要(Overview)
現在管理画面の受注登録画面、または出荷登録画面での商品またはその他の明細を追加するアクションで、prototypeの__name__に、商品の明細の数プラス1したindexを指定していますが、この方法だと以下再現手順の操作を行なった際、不具合がでる可能性があります。

## 期待する内容(Expect)  or 要望 (Requirement)
商品明細の行の数からindexを求めると、すでに登録されている商品明細のidと重複する可能性があるので、idが重複しない処理を追加、もしくは修正をして欲しいです。

## 再現手順(Procedure)
- 受注登録画面または出荷登録画面
> 1. 商品を2個追加(明細行が2行となるように)
> 1. 商品の明細から、一つ目に登録した商品(上の明細行)を削除
> 1. 商品またはその他の明細を追加
>    - 商品追加の場合、すでに登録済みの商品が追加した商品に上書きされる
>    - その他の明細の場合、エラーとなる

### 環境 (environment)
+ EC-CUBE: 4.1.0
+ PHP: 7.4.27
+ DB:
  - MySQL 5.7.34

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5540 で対応
