### ISSUE TITLE
納品書PDFで複数行になる商品明細がページをまたぐとレイアウトが崩れる

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#5326]
## 概要(Overview)

納品書PDFで、複数行になる商品名の明細行がページをまたいで表示されたときにレイアウトが崩れる。
<img width="651" alt="image" src="https://user-images.githubusercontent.com/57504/158725278-3cf51699-9eff-4365-9385-79380d7536f2.png">

### 環境 (environment)
+ EC-CUBE: 4.1.2
+ PHP: 7.4.15
+ DB:
  - PostgreSQL 10.17

**Comment by chihiro-adachi** [comment]
#5349 で対応
