### ISSUE TITLE
EF0101-UC01-T02 TOPページ 新着情報 で www.ec-cube.net の画面が表示され、エラーになる場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5344]
## 概要(Overview)

EF01TopCest: EF0101-UC01-T02 TOPページ 新着情報 がエラーになる場合がある
https://github.com/EC-CUBE/ec-cube/runs/5809030779?check_suite_focus=true#step:13:45

エラー発生時のスクリーンショットを確認すると、 www.ec-cube.net の画面が表示されている模様

![EF01TopCest topページ 新着情報 chrome github action fail](https://user-images.githubusercontent.com/815715/161510853-47688c77-3f9b-411a-83d3-d386e9a3f3fa.png)

## 期待する内容(Expect)  or 要望 (Requirement)
EF0101-UC01-T02 TOPページ 新着情報 が正常に終了する

## 再現手順(Procedure)
GitHub Actions の Backward compatibility testing EF01TopCest: EF0101-UC01-T02 TOPページ 新着情報 を実行する

### 環境 (environment)
+ EC-CUBE: 4.1.x
+ PHP: 7.4
+ DB:
  - PostgreSQL

**Comment by chihiro-adachi** [comment]
@nanasess 
BCテストだけでなく、通常のE2Eテストでも同様の事象が発生していました。

発生しているエラーと類似の事象だと、CIのスペックに起因するみたいな情報もありました。
https://qiita.com/oieioi/items/0e9468c1d2ad2da1a94c

クリック時のアクセス先をwww.ec-cube.netから軽そうなページに変更したら解消するかもしれません。

**Comment by nanasess** [comment]
@chihiro-adachi なるほど、タイトル変更しておきました

**Comment by chihiro-adachi** [comment]
#5352 で修正しました。
今の所落ち着いてそうです。
