### ISSUE TITLE
カテゴリ編集フォームでエラーがあっても気づかない

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#5346]
## 概要(Overview)
カテゴリ編集フォームでエラーがあり保存できなくても、編集ボタンをクリックしないと見えず気づかない

## 期待する内容(Expect)  or 要望 (Requirement)
保存できなかった場合は画面上部アラートとフォームのエラーメッセージで最初から分かるようにする

## 再現手順(Procedure)
1. 登録済みのカテゴリ編集ボタンを押して名称欄に256文字以上の文字を入力する
2. 決定ボタンを押す
3. 名称は255文字制限なので登録できないが再度編集ボタンを押さないとエラーが表示されないため気づかない
※プラグインでの追加項目などがエラーになる場合も同様

動画キャプチャ
https://umebius.gyazo.com/46d70b29ebaa61b1f466f5f640201dbf

**Comment by chihiro-adachi** [comment]
@dk-umebius 
ありがとうございます、動画の再現キャプチャわかりやすかったです。

**Comment by chihiro-adachi** [comment]
#5350 でカテゴリ名のエラーに関しては修正済
プラグインで拡張した項目については未対応

**Comment by chihiro-adachi** [comment]
#5360 で対応
