### ISSUE TITLE
Cant login to admin page (No error)

### ISSUE THREAD

**Issue by kaistudios** [EC-CUBE/ec-cube#5347]
## 概要(Overview)
Cant login to administration after moving site to new host no error just refresh back to login again

## 期待する内容(Expect)  or 要望 (Requirement)

I moved ec-cube 4 site to new host AWS LightSail instance [LAMP_PHP_7-1] 
Front end looks good but when I go to administration back end I cant login and there is no error just refresh back to login again.
I copied all files from old server including .env same auth magic similar
Do I need to chmod any specific folder with special permissions?
Do I need to clear cache somewhere?
Where is the admin login error log will this give a clue?
any ideas?

## 再現手順(Procedure)
Go to admin
feed login and password
back to login

### 環境 (environment)
+ EC-CUBE: 4.1.0
+ PHP: 7.1
+ DB: mysql 5.7.37
  - MySQL 5.7.37

**Comment by chihiro-adachi** [comment]
@kaistudios 
Please post your operational questions in the forum.
https://xoops.ec-cube.net/
