### ISSUE TITLE
管理画面にログインしようとすると、フロントページトップが表示される

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#536]
#516 と関連しているかどうか、わかりませんが、[Vagrant で作成した CentOS の仮想マシン](https://github.com/EC-CUBE/eccube-vagrant) に EC-CUBE3 をインストールし、管理画面へログインしようとすると、フロントページトップへリダイレクトされ、管理画面へログインできません。

環境依存の問題かもしれませんが、念のためご報告です。

**Comment by shinichi-takahashi** [comment]
私も同様の現象になやみ、以下の記事でかいけつしました。
環境依存問題ですね。。
http://gongo.hatenablog.com/entry/2014/12/17/204831

**Comment by shinichi-takahashi** [comment]
@nanasess の環境でも解決したらクローズをお願いします。

**Comment by nanasess** [comment]
確認してみます。ありがとうございます。

**Comment by Yangsin** [comment]
@nanasess その後確認いかがでしょうか？

**Comment by nanasess** [comment]
#1361 と重複していると思われますのでクローズします
