### ISSUE TITLE
インストール　ドキュメントの間違い

### ISSUE THREAD

**Issue by entrycoderfox** [EC-CUBE/ec-cube#5365]
## 概要(Overview)
[各種インストール方法](https://doc4.ec-cube.net/quickstart/install)にで、
「bin/console *」なとコマンドは欠失がある

例：
[ComposerからWebインストーラでインストールする](https://doc4.ec-cube.net/quickstart/composer_web_installer)
```
bin/console server:run
```
正しい方
```
php bin/console server:run
```

## 期待する内容(Expect)  or 要望 (Requirement)
以下のコマンド修正
[ComposerからWebインストーラでインストールする](https://doc4.ec-cube.net/quickstart/composer_web_installer)
```
bin/console server:run
```

[コマンドラインからインストールする](https://doc4.ec-cube.net/quickstart/command_install)
> 4.ec-cube ディレクトリが生成されますので、...
```
bin/console server:run --env=dev
```
> ### Windows 環境を使用する場合
```
# (optional) データベース削除
bin/console doctrine:database:drop --force
# データベース作成
bin/console doctrine:database:create
# (optional) スキーマ削除
bin/console doctrine:schema:drop --force
# スキーマ生成
bin/console doctrine:schema:create
# 初期データ生成
bin/console eccube:fixtures:load
```

### 環境 (environment)
+ EC-CUBE: 4.1.2
+ PHP: php-7.4.28-nts-Win32-vc15-x64
+ OS: Windows11 x64

**Comment by entrycoderfox** [comment]
[こち](https://github.com/entrycoderfox/doc4.ec-cube.net)で修正しました。

**Comment by chihiro-adachi** [comment]
@entrycoderfox 
ありがとうございます、こちらのPullRequestも確認していきます。
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/268
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/267
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/266

ドキュメントに関するissueはdoc4のレポジトリに作成してもらえると助かります。
https://github.com/EC-CUBE/doc4.ec-cube.net/issues

**Comment by chihiro-adachi** [comment]
上記マージしました。
ありがとうございます。
