### ISSUE TITLE
コマンドラインからインストールのエラー

### ISSUE THREAD

**Issue by entrycoderfox** [EC-CUBE/ec-cube#5366]
## 概要(Overview)
[コマンドラインからインストールする](https://doc4.ec-cube.net/quickstart/command_install)による、EC-CUBEをインストールする、エラーがある
```
 Run doctrine:database:create...


 [ERROR] The command "bin/console doctrine:database:create" failed.

Exit Code: 1(General error)

Working directory:
         D:\compare_tmp\ec-cube_composer

Output:
================


Error Output:
================
'bin' is not
         recognized as an internal or external command,
         operable program or batch file.

```

## 期待する内容(Expect)  or 要望 (Requirement)
ソースの内容修正（この場合、「Script」でのエラーの可能性が高い)

## 再現手順(Procedure)
1.EC-CUBEをインストールしたいディレクトリへ移動
```
cd D:\compare_tmp
```

2.[Composer のインストール](https://getcomposer.org/download/)から、composer.phar をdownloadする
downloadしたcomposer.pharをD:\compare_tmpに置く

3.composer.phar のバージョンを「1.x」 に変更する
```
php composer.phar selfupdate --1
```

4.以下のコマンドを実行する
```
php composer.phar create-project ec-cube/ec-cube ec-cube_composer "4.1.x-dev" --keep-vcs
```

5.以下のコマンドを実行する
```
cd ec-cube_composer
php bin/console eccube:install
```

6.host、database、authの設定はディフォルトで、インストールする

7.エラーがある

### 環境 (environment)
+ OS: Windows11 x64
+ EC-CUBE: 4.1.2
+ PHP: php-7.4.28-nts-Win32-vc15-x64

## 関連情報 (Ref)
[インストール　ドキュメントの間違い #5365](https://github.com/EC-CUBE/ec-cube/issues/5365)

**Comment by chihiro-adachi** [comment]
@entrycoderfox 
doc4のレポジトリにissueを作成お願いできますでしょうか。
https://github.com/EC-CUBE/doc4.ec-cube.net/issues
