### ISSUE TITLE
bin/consle でコマンド実行時に.envをロードしないケースがある

### ISSUE THREAD

**Issue by y-natsume-d** [EC-CUBE/ec-cube#5367]
## 概要(Overview)

`bin/console`でコマンドを実行する時、個人的には常に `.env` ファイルをロードして欲しいのですが、コードを見る限り `APP_ENV` 環境変数が設定されていない時のみに限定されているので理由を知りたいです。

実際の処理 https://github.com/EC-CUBE/ec-cube/blob/4.1/bin/console#L19

## 期待する内容(Expect)  or 要望 (Requirement)

個人的には `.env` ファイルが存在するなら常にロードして貰いたいです

## 再現手順(Procedure)

- ロードする (`APP_ENV` 未定義)

```shellscript
env -i bin/console debug:container --env-vars
```

- ロードしない (`APP_ENV` 定義済み)

```shellscript
env -i APP_ENV=prod bin/console debug:container --env-vars
```
### 環境 (environment)
+ EC-CUBE: 4.1.1
+ PHP: 7.4.26
+ DB:
  - MySQL 5.7.x

**Comment by nanasess** [comment]
> コードを見る限り APP_ENV 環境変数が設定されていない時のみに限定されているので理由を知りたいです。

この箇所を実装した人ですが、 Symfony Demo Application のコードを真似しただけ...というのが正直な理由です。
https://github.com/symfony/demo/blob/0142c89a3b336eb1cae69938ce7cd678279a4cf3/bin/console#L18-L20

**Comment by nanasess** [comment]
Symfony 4.2 あたりから、常に .env を読み込む方針に変更されたようですので、この仕様に合わせることを検討しても良いかもしれません。
https://github.com/symfony/recipes/pull/501
https://github.com/symfony/symfony-docs/pull/10846

**Comment by y-natsume-d** [comment]
なるほど、ありがとうございます。
理由がわかったので一旦issueはクローズさせて頂きます。
