### ISSUE TITLE
「安全なwebサイトの作り方」に沿った実装の見直しの検討

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5371]
## 概要(Overview)

[安全なウェブサイトの作り方](https://www.ipa.go.jp/security/vuln/websecurity.html)を参考に、現状のEC-CUBEの実装を確認する。
方針に沿わないものがある場合、実装の見直しを検討する

以下の脆弱性について、内容を確認する
- [] XSS
- [] CSRF
- [] SQLインジェクション
- [] ディレクトリトラバーサル
- [] 認証/認可

### 環境 (environment)
+ EC-CUBE: 4.1.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by shinya** [comment]
対応する。
何から着手していくか、などの検討を別途詳細に進める必要あり。

**Comment by xuelian311** [comment]
重要操作時のメール通知機能を実装するのみ残っているため、本issueはクローズし、重要操作時のメール通知#5373で対応続けます。
