### ISSUE TITLE
重要操作時のメール通知

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5373]
## 概要(Overview)

#5371

CSRFの保険的対策として

```
保険的対策	重要な操作を行った際に、その旨を登録済みのメールアドレスに自動送信する。
```

## 期待する内容(Expect)  or 要望 (Requirement)

マイページの各更新操作時に実施
- 会員情報変更
- お届け先情報変更
- 退会

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by shinya** [comment]
実装するのであれば、管理画面側を優先的にしたい。
が、その場合ユーザーごとにメールアドレスを保持していないので宛先をどのアドレスにするのか？という課題が残る。

**Comment by chihiro-adachi** [comment]
フロント側は、パスワード再設定も対象と思われる (/forgot/reset)

**Comment by xuelian311** [comment]
重要操作時の再認証機能ができてもこの機能は別途必要？

**Comment by nanasess** [comment]
フロント側のパスワード再設定、退会は既存のメール送信機能があるため、あえてメール通知を送信する必要ないと思われます

**Comment by xuelian311** [comment]
以下の方針でpull request 作ります。

フロント画面：
会員情報変更　実装予定
お届け先情報変更　実装予定
ログイン成功/失敗　必要以上の機能と判断し、実装しない

管理画面：
管理画面からの変更に関しては、有効性が曖昧で今回は実装しない
別途必要と感じたら、issueを新規作成する

メールアドレス変更前と変更後両方に通知を送信する

**Comment by xuelian311** [comment]
仕様について再度整理しました。
・on/off機能を付ける
　管理画面＞店舗設定＞基本設定にてON/OFFできるようにする

・デフォルト設定
　新規インストールではデフォルトON、既存インストールではデフォルトOFFとする

・通知メールの内容
　自分がログインしたかどうかの確認：日時、ブラウザ種類、ショップURL
　管理者への問い合わせのため：IPアドレス

**Comment by Yangsin** [comment]
メールテンプレートの追加があるため
カスタマイズやプラグインでおこなっているような環境でバージョンアップする際に
テンプレートIDの重複などが発生しないか気になりました
最低限、アップデート時の注意点としては記載しておきたいですね

**Comment by ji-eunsoo** [comment]
こちらPR取り込みしたため、closedします。
