### ISSUE TITLE
RememberMeトークンでログインするとパスワードの再発行画面がエラーになる

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/ec-cube#5379]
## 概要(Overview)
RememberMeトークンでログイン状態になった場合、
会員情報編集などを開くには再ログインが必要になるが、
パスワードが分からず再発行しようとすると404エラーになる

この場合一度ログアウトしてからパスワード再発行を行う必要があるが、気付きにくい。

## 期待する内容(Expect)  or 要望 (Requirement)
パスワード再発行ができる
IS_AUTHENTICATED_REMEMBEREDの状態ではパスワード再発行機能が使えて良いのでは？

## 再現手順(Procedure)

1. RememberMeトークンでログインした状況をつくる
2. 会員情報編集ページ(/mypage/change)へアクセスしログイン画面を表示する
3. ログイン画面上のログイン情報をお忘れですか？リンクをクリックする

<動画>
https://umebius.gyazo.com/4009d71de8912e57276fbb340b0acd1f

### 環境 (environment)
+ EC-CUBE: 4.1.x, 4.2-α

**Comment by chihiro-adachi** [comment]
#5380 で対応
