### ISSUE TITLE
開発終了となった JavaScript ライブラリの更新

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5385]
## 概要(Overview)
開発終了となった JavaScript ライブラリを更新、または別のライブラリにリプレイスする
- #5383 
- #5185

## 期待する内容(Expect)  or 要望 (Requirement)

- bootstrap4 → bootstrap5
- tempusdominus-bootstrap-4 → bootstrap-datepicker
- bootstrap-colorpicker → React color?
- jQuery File Upload → https://github.com/pqina/filepond 

### 環境 (environment)
+ EC-CUBE: 4.1

**Comment by chihiro-adachi** [comment]
#5395 #5397 #5398 で対応
