### ISSUE TITLE
ユニットテストのgenerateUrlがプラグインに対応していない？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5396]
## 概要(Overview)

ユニットテストのgenerateUrlがプラグインに対応していないように思う

1) Plugin\DataMigration4\Tests\Web\Admin\ConfigControllerTest::testgenerateUrl
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "data_migration4_admin_config" as such route does not exist.

/www/ec-cube42/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50
/www/ec-cube42/vendor/symfony/routing/Router.php:235
/www/ec-cube42/tests/Eccube/Tests/EccubeTestCase.php:291
/www/ec-cube42/app/Plugin/DataMigration4/Tests/Web/Admin/ConfigControllerTest.php:33
/www/ec-cube42/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
/www/ec-cube42/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/www/ec-cube42/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/www/ec-cube42/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673

## 期待する内容(Expect)  or 要望 (Requirement)
generateUrlが正常に動作する

## 再現手順(Procedure)
$url =$this->generateUrl('data_migration4_admin_config');
dump($url);

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ちゃんと原因わかってないのですが、キャッシュ消してあげるとうまくいったりします。

```
rm -rf var/cache
bin/console --env=test
bin/console debug:router --env=test
```

**Comment by nobuhiko** [comment]
@chihiro-adachi 
ありがとうございます、ホントですね
これで動くってことはgit actions で動かないのはまた別の理由か。。

**Comment by nobuhiko** [comment]
vendor/bin/phpunit tests/Eccube/Tests/Web/CartControllerTest.php  も動かないので client->request の仕様が変わったんですかね

**Comment by chihiro-adachi** [comment]
actionsはこちらで動作するようになりました。
https://github.com/EC-CUBE/data-migration-plugin/pull/99
