### ISSUE TITLE
[4.2] 商品編集画面で、商品画像のローディングに失敗する

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5414]
## 概要(Overview)

インストール直後の状態で、商品編集画面を表示すると商品画像のローディングに失敗する

<img width="774" alt="image" src="https://user-images.githubusercontent.com/8196725/176597155-efb8a806-4900-40dd-a1d1-5dc4e873dec0.png">

以下のように画像を取得しているが、404を返している状態
```
http://xxx.xxx.xxx.xxx/ec-cube/admin2/product/product/image/load?source=%2Fec-cube%2Fhtml%2Fupload%2Fsave_image%2Fcube-1.png
```

## 期待する内容(Expect)  or 要望 (Requirement)

画像が表示される

## 再現手順(Procedure)

- ec-cubeをサブディレクトリに配置してインストール
- 管理画面から、商品編集画面を表示

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
#5417 で対応してます
