### ISSUE TITLE
[管理画面]カテゴリの数が削除済商品もカウントしている

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#542]
管理画面から商品を削除しても、カテゴリ内の商品数が減らないため、カテゴリを削除することができない。
del_flgが1のものはカウントしない＋FKの対応をする必要がある。

**Comment by chihiro-adachi** [comment]
こちら再現不可のため(商品削除後、カテゴリの削除が可能であることを確認)、クローズさせていただきます。
