### ISSUE TITLE
メンバー編集エラー

### ISSUE THREAD

**Issue by TPS-NghiaLe** [EC-CUBE/ec-cube#5420]
## 概要(Overview)
**Expected argument of type "string", "null" given at property path "plain_password".**

![edit_member](https://user-images.githubusercontent.com/105767287/177488429-a5b862fb-58a6-403c-b9a5-40d170d33d95.png)
![edit_member_2](https://user-images.githubusercontent.com/105767287/177488448-3c3fdbc5-f5d4-4596-b37f-d7dbcfee5968.png)

## 再現手順(Procedure)

1.設定→システム設定→メンバー管理
2.「編集」ボタンを押下する
3メンバー編集画面に遷移する
4.登録済の情報が、メンバー入力フォームに表示される
5.メンバー入力フォームの値をクリアする
6.「登録」ボタンを押下する

### 環境 (environment)
+ EC-CUBE: 4.2.0 alpha
+ PHP: 8.0.20
+ DB: 
  - MySQL 5.7.26

**Comment by nanasess** [comment]
手元の環境では再現しませんでした。正常にメンバー登録できました
![image](https://user-images.githubusercontent.com/815715/177919428-f304eec6-0cb4-4a0b-9a66-c64513b23715.png)
以下の環境で確認しました
- PHP7.4.30
- PHP8.1.6

**Comment by TPS-NghiaLe** [comment]
> 手元の環境では再現しませんでした。正常にメンバー登録できました ![image](https://user-images.githubusercontent.com/815715/177919428-f304eec6-0cb4-4a0b-9a66-c64513b23715.png) 以下の環境で確認しました
> 
> * PHP7.4.30
> * PHP8.1.6

@nanasess 
下記にステップに従ってご実施ください。
ステップ１：　存在しているメンバーの編集ボタンをクリックする。
ステップ２：　パスワード と パスワード(確認) など２つのフィルードのデータを削除する。
ステップ３：　登録ボタンをクリックする。
![delete_pass](https://user-images.githubusercontent.com/105767287/177967602-80471d17-f6d1-42ed-baa0-add4b9e3b07b.png)

**Comment by nanasess** [comment]
@tpsnghiale ありがとうございます。再現確認できました

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5431 で対応
