### ISSUE TITLE
[4.2] httpでのアクセス時にメンテナンスモード時に、管理者がフロント画面を閲覧できない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5424]
## 概要(Overview)

メンテナンスモード時に、管理者がフロント画面を閲覧できない
管理画面ログイン済であっても、フロント画面を表示すると「メンテナンス中です」の画面が表示される。

httpでのアクセスで発生。httpsでは未確認。

## 期待する内容(Expect)  or 要望 (Requirement)

通常画面が表示される

## 再現手順(Procedure)

- httpでアクセス
- コンテンツ管理＞メンテナンス管理で、メンテナンスモードを有効にする
- フロント画面を閲覧する

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
@chihiro-adachi 
手元の環境では、 http:// 及び https:// であっても再現しませんでした
![image](https://user-images.githubusercontent.com/815715/177922239-3526c038-7bfa-42ef-ab5e-512cef92ab56.png)


![image](https://user-images.githubusercontent.com/815715/177922160-61c72a7e-5967-4831-97e7-b1d3f8139c5a.png)

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます。

localhostではsecure属性は無視されるようなので、それで再現しないのかもしれません。
https://teratail.com/questions/368825

localhostでない環境で試してもらうことはできますでしょうか？

**Comment by nanasess** [comment]
@chihiro-adachi リモート環境であっても再現しませんでした
![image](https://user-images.githubusercontent.com/815715/178381405-fc60b1a4-1383-49fe-be33-3d9f981e6798.png)
![image](https://user-images.githubusercontent.com/815715/178381774-c0282195-19f0-4214-ab3d-18ecd3cc2305.png)

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます。お手数おかけしました。
いったんこちらは再現せずでクローズします。
