### ISSUE TITLE
慎重にコーディングしてください。

### ISSUE THREAD

**Issue by ukeloop01** [EC-CUBE/ec-cube#5429]
慎重にコーディングしてください。 ソースを閉じることはダンプと同じだと思います。 私は日本のプログラマーについて別の見方をしています

**Comment by kiy0taka** [comment]
@ukeloop01 ご意見ありがとうございます。
このIssueは具体的に何に対するものかが不明なので、Issue作成については以下の利用方法を一読願います。
https://github.com/EC-CUBE/ec-cube/wiki/Issues%E3%81%AE%E5%88%A9%E7%94%A8%E6%96%B9%E6%B3%95

もう一つのIssueは不適切な内容が含まれるため、削除させていだきます。

**Comment by ukeloop01** [comment]
あなたは子供のようにコーディングします。 コントローラにすべての処理を書き込みます。 リポジトリパターンを適用する場合は、よくお読みください。 このようなコアを作成すると、外部委託されたプログラマーが惨めになるだけです。(You code like children. Write all the processing in the controller. If you apply the repository pattern, please read it carefully. If you create cores like this, it will only make outsourced programmers miserable.)

**Comment by ukeloop01** [comment]
私がそのコードを書いた人だったら、私はとても恥ずかしいでしょう  (If I were the one who wrote that code, I'd be so embarrassed)
