### ISSUE TITLE
render イベントがフックできない。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#543]
プラグインで render イベントを使用したところ、うまくいくページと、いかないページがありました。
ソースを確認したところ、うまくいくページは「$app['view']::render」を使用しており、いかないページは「$app::renderView」（内部で $app['twig']::render）でレンダリングされておりました。

$app['view'] は ViewSource クラスでフックポイントを dispatch されていましたが、$app['twig'] は Twig_Environment のため、「eccube.event.render.{route}.before」の dispatch がありません。

レンダリング方法が複数あるのはどのような意図があるのでしょうか。
また、今後はどちらか（$app['view']？）に統一されるのでしょうか。

**Comment by shinichi-takahashi** [comment]
@shhirose 
ver3.0.1では、renderイベントが変更となり、`FilterResponseEvent` を使うようになります。

https://github.com/shinichi-takahashi/eccube3-sample-plugin/blob/CategoryContent/CategoryContent/CategoryContent.php
こちらを参考にしてみてください。

また、 `$app['view']` で統一する方向で考えています。
（現状すでに難しい状態ですが）twigではなく、smartyに置き換える余地を残すためです。

**Comment by shhirose** [comment]
3.0.1 で Application で dispatch されていることを確認しました。
ご回答ありがとうございました。
