### ISSUE TITLE
インストール完了も dtb_member に管理者が追加されない

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube#544]
再インストールでは、再現しなかった。

初回は、PDO ドライバーが導入されていないなどで、何度か入力し直すなど行ったので、そういった操作が影響したか。

システム情報
EC-CUBE
3.0.1 (リリース版)
サーバーOS
Windows NT X230 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
DBサーバー
PostgreSQL 9.3.5, compiled by Visual C++ build 1600, 32-bit
WEBサーバー
Apache/2.4.6 (Win32) OpenSSL/0.9.8y PHP/5.5.24
PHP
5.5.24 (Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, Phar, SimpleXML, wddx, xml, xmlreader, xmlwriter, apache2handler, gd, mbstring, mysql, pdo_mysql, pdo_pgsql, pgsql, xsl, mhash)
GD
有効 (GD Version => bundled (2.1.0 compatible), FreeType Support => 1, FreeType Linkage => with freetype, T1Lib Support => , GIF Read Support => 1, GIF Create Support => 1, JPEG Support => 1, PNG Support => 1, WBMP Support => 1, XPM Support => 1, XBM Support => 1, JIS-mapped Japanese Font Support => )
HTTPユーザーエージェント
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by nobuhiko** [comment]
dtb_base_info も空じゃないですか？

**Comment by chihiro-adachi** [comment]
どうもsessionの値がうまく渡ってこないようです。
configのファイルを削除/ブラウザ再起動、してからインストールすると再現すると思います。

明示的にsessionを開始するようにすれば一応回避はできました。

#549

**Comment by nobuhiko** [comment]
@chihiro-adachi 
うーん、ダウンロードしてFTPであげてインストール画面からインストールしてもおきたので、再現の仕方は様々ありそうな気がします
仮に直ってたとしても、sessionにデータがない状態でインストールが完了できちゃうのはバリデーション不足な気もします

**Comment by chihiro-adachi** [comment]
> 仮に直ってたとしても、sessionにデータがない状態でインストールが完了できちゃうのはバリデーション不足な気もします
ここは確かにそうですね。
pdoでのinsert処理が失敗しているはずなので、エラーハンドリング必要ですね。

**Comment by seasoftjapan** [comment]
再び発現しました。(6c82dceff4eee1d25372b3971d321c9fcbfec3a1)

> dtb_base_info も空じゃないですか？

レコードは存在して、値が反映されていませんでした。

**Comment by nobuhiko** [comment]
ってことはこの問題も直ってないってことなんですよね
#407

**Comment by Yangsin** [comment]
#576 とあわせてクローズさせていただきます。
