### ISSUE TITLE
[4.2] 管理画面メッセージ表示「閉じる」押下しない場合の挙動

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5448]
## 概要(Overview)
管理画面から出荷お知らせメール後、「送信しました」メッセージポップアップの「閉じる」ボタンを押さずに、
別場所でクリックすると、画面がグレーで操作できなくなる （画面をリフレッシュで操作可能になる）
![#5448](https://user-images.githubusercontent.com/109564827/179666937-a0878203-e859-4e5c-a3a3-966955559008.PNG)

## 期待する内容(Expect)  or 要望 (Requirement)
メッセージポップアップを無視した場合は「閉じる」ボタン押下と同様の挙動となる

## 再現手順(Procedure)
①管理画面から出荷お知らせメールを送付
②ポップアップメッセージを無視して、他場所でクリック

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.4.30
+ DB: PostgreSQL 10.21 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
バグバウンティExcel#10

**Comment by nanasess** [comment]
こちらは再現しませんでした。
#5446 で修正された可能性があります。
以下の環境で確認しました。
Windows11
Chrome  103.0.5060.114
Edge 103.0.1264.62
Firefox 102.0

**Comment by chihiro-adachi** [comment]
@nanasess 
確認ありがとうございます。
再現不可ということでクローズします。
