### ISSUE TITLE
[4.2] 画像表示について

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5449]
## 概要(Overview)
SP表示画像はOKだが、PC表示はブラウザ幅によっては画像が伸びる
※トライアル4.1.2ではブレイクポイントで画像サイズが変わります。
![#5449](https://user-images.githubusercontent.com/109564827/179667121-2106b8c7-461b-48f6-bd7b-814b5f351a99.PNG)

## 期待する内容(Expect)  or 要望 (Requirement)
トライアルと同様に画像縦横サイズが変わらないようにして欲しい

## 再現手順(Procedure)
画像が表示されているページでブラウザサイズ幅を縮める

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.4.30
+ DB: PostgreSQL 10.21 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
バグバウンティExcel#12

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5456 で対応
