### ISSUE TITLE
[4.2] プラグイン「クーポン」の表示位置

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5450]
## 概要(Overview)
プラグイン有効化後のクーポン利用のお買い物で、表示位置が「特定商取引法に基づく表記」の間になっている
![＃5450](https://user-images.githubusercontent.com/109564827/179667240-ab67ac4c-bff0-4495-a271-b40c97708aeb.PNG)

## 期待する内容(Expect)  or 要望 (Requirement)
「特定商取引法に基づく表記」の上に表示？
どこか良い場所に…

## 再現手順(Procedure)
①プラグイン「クーポン」を有効化
②お買い物

### 環境 (environment)
EC-CUBE: 4.2.0-beta
PHP: 7.4.30
DB: PostgreSQL 10.21 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
PostgreSQL x.x.x
MySQL x.x.x

## 関連情報 (Ref)
バグバウンティExcel#14

**Comment by nanasess** [comment]
以下で対応しました
https://github.com/EC-CUBE/coupon-plugin/pull/151

**Comment by chihiro-adachi** [comment]
@nanasess 
ご対応ありがとうございます。

https://github.com/EC-CUBE/coupon-plugin/pull/151 の修正を取り込みました。
