### ISSUE TITLE
連想配列とオブジェクトの値の受け渡し

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#546]
[こちら](http://svn.ec-cube.net/open_trac/wiki/EC-CUBE%E6%A8%99%E6%BA%96%E8%A6%8F%E7%B4%84/%E9%96%8B%E7%99%BA%E5%8A%B9%E7%8E%87%E5%90%91%E4%B8%8A%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AETips#%E3%82%A8%E3%83%B3%E3%83%86%E3%82%A3%E3%83%86%E3%82%A3%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B) のサンプルコードにある、 `AbstractEntity::setPropertiesFromArray()` と `AbstractEntity::toArray()` を移植したいです。

どうしても nativeQuery を書かなきゃいけない場合、連想配列からオブジェクトに値をコピーするのがとても大変なので。

ちなみに、これらのメソッドの応用で `AbstractEntity::copyProperty(Entity entity)` とか作れば、とても便利になります。(フレームワークがサポートするようなメソッドになるので、 EC-CUBE3 のポリシーには少々抵触するかもしれません)

**Comment by ttsuru** [comment]
http://stackoverflow.com/questions/20254144/doctrine-convert-array-to-doctirne-entity
http://stackoverflow.com/questions/8270151/convert-the-result-of-a-query-to-an-array-of-arrays
それっぽいことやられてるかたいますね・・・

**Comment by nanasess** [comment]
Java のフレームワークだと、こういうリフレクション使って値を渡すのは常套手段なんですけどね。

**Comment by ttsuru** [comment]
Dotrine 1の頃はデフォであったんですけどね・・・笑

**Comment by aminotsukasa** [comment]
これはないと不便ですね
誰かが車輪の再発明してしまう前に入れてしまっていいと思います

**Comment by nanasess** [comment]
> Dotrine 1の頃はデフォであったんですけどね・・・笑

おお、そうなのですねぇ。 ただ、これを使い始めると、 O/R Mapper でクエリを組みたくなくなって、 nativeQuery ばかり気軽に書くようになるので、無くしたくなる気持もわかります。
(本当はどうかわかりませんが)

**Comment by nanasess** [comment]
時間みつけて早いとこテスト書きますねー

**Comment by k-yamamura** [comment]
Seasar2のBeans.copyみたいなものが欲しいのですが、Doctrineとかで似たようなものご存知ないですか。

**Comment by ttsuru** [comment]
@k-yamamura 
http://stackoverflow.com/questions/9071094/how-to-re-save-the-entity-as-another-row-in-doctrine-2
こういうことではないですよね・・・？

**Comment by k-yamamura** [comment]
@ttsuru 
基本はそんな感じなのですが今回求めているのがeccubeの例の場合、
dtb_order_detailとdtb_shipment_item
がほぼ同じ内容なので2つに対してsetterを記述するのではなく、
どちらかにセットすれば、
copy(fromEntity, toEntity)
みたいな感じでentityの同一名のプロパティに値をセットしてくれる便利なものが無いか探していました。

**Comment by nanasess** [comment]
@k-yamamura 8340370 のリフレクションを応用してやればできると思いますが、自作するしかないのですかね。
PHPer の方たちは、こういう時どうしているのでしょうか...

**Comment by k-yamamura** [comment]
@nanasess 
欲しているのはまさしくそれです。BeanUtilsみたいなものがあれば万事解決します。
今はもう自作するしかないかと半ば諦めています。

**Comment by nanasess** [comment]
すぐでなくても良ければ、 `AbstractEntity::copyProperty(Entity entity)` みたいなの作りますよ

**Comment by k-yamamura** [comment]
@nanasess 
作成してもらえるのであれば是非おねがいします。

**Comment by nanasess** [comment]
@k-yamamura それでは、時間見つけて作成してみますね。
8340370 のテストも書かないといけませんし...

**Comment by k-yamamura** [comment]
@nanasess 
ありがとうございます。非常に助かります。

**Comment by nobuhiko** [comment]
ほぼ重複しているのに dtb_order_detail って必要なんですか？

**Comment by nanasess** [comment]
@nobuhiko 互換性を考えなければ、不要だと思います。

**Comment by nanasess** [comment]
315715bb461f7ee89b3f4399e26834d3ae38e157 で、 copyProperties() にも対応して、テストケースも書きました。

**Comment by nanasess** [comment]
7769b75cf1a0ccb74f9bbb2deb752d3112857b83 にて、 null のフィールドのコピーにも対応しました。

**Comment by nanasess** [comment]
#833 #547 でマージされましたのでクローズします。

**Comment by nanasess** [comment]
> 昔、 Java の Jakarta Commons にあった BeanUtils みたいなのがあれば万事解決ですよね.

似たようなのがあるみたいです。 現在の copyProperties は、フィールドのコピーにしか対応していないので、 プロパティのコピーをしたい場合は、こちらを使用すると良さそうです。

http://symfony.com/doc/current/components/property_access/index.html
