### ISSUE TITLE
[4.2]消費税額の計算について

### ISSUE THREAD

**Issue by FujiiToshio** [EC-CUBE/ec-cube#5478]
## 概要(Overview)
4.2よりインボイス対応とのことですが、商品購入時の商品ごとの消費税額の計算が、以前同様の
(商品単価×税率)=税込価格(端数処理込) × 購入個数となっているようです。

## 期待する内容(Expect)  or 要望 (Requirement)
インボイス対応であれば、商品価格(税抜)×購入個数＝税抜価格 × 税率 = 税込価格(端数処理込)が正解なのではないでしょうか？※私の認識が間違っていれば、申し訳ございません。
例）
商品名　　単価　　税率　購入個数
商品A　　114円　　8%　　4個
商品B　　102円　　8%　　2個
商品C　　222円　　10％　2個
商品D　　300円　　10%　1個
※小数点以下、切り捨て。

税率8%分計算
114円×4個=456円
102円×2個=204円
税率8%税抜計　456円+204円＝660円
8%消費税額　660円×8％=52.8円=52円(端数処理適応)
8%税込合計　660円+52円 = 712円

税率10%分計算
222円×2個=444円
300円×1個=300円
税率10%税抜計　444円+300円＝744円
10%消費税額　774円×10％=77.4円=77円(端数処理適応)
10%税込合計　774円+77円=851円

お支払い合計　712円+851円＝1,563円
![171557381-02c0c1c3-e016-4a87-9f33-8c1caf530c90](https://user-images.githubusercontent.com/14307966/181472091-38acf7da-3c52-448f-8819-90fd06aa4a8a.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4
+ DB:
  - MySQL 5.7

**Comment by nanasess** [comment]
一般消費者に対する販売には総額表示が義務づけられているのに対して、インボイスの対象となる[請求書は総額表示義務の対象外](https://www.mof.go.jp/tax_policy/summary/consumption/a_001.htm#1)となっているため、ややこしいことになっていそうです。

総額表示義務の観点からすると、**(商品単価×税率)=税込価格(端数処理込) × 購入個数** という EC-CUBE4.1 まで採用していた、**「税込価格」を基にする計算方法** が、消費者にとってわかりやすいと思われます。

また、財務省の[総額表示に関する主な質問](https://www.mof.go.jp/tax_policy/summary/consumption/a_001.htm#16) にも 

> 総額表示への移行後も従来の「税抜レジシステム」を用いた場合には消費者との間でトラブルが生じるケースがあるため、「税込価格」を基に計算するレジシステムに移行されていくことが望ましいと考えます。

と、記載がありますので、 **「税込価格」を基にする計算方法** で差し支えないという認識です。

一方、インボイスの要件となる消費税額は、お支払いの合計額から割戻して表示しています。

このような認識なのですが、いかがでしょうか？
もし税理士さんなどの専門家の方からの指摘などありましたら、ぜひお知らせいただけると助かります。

**Comment by FujiiToshio** [comment]
ご回答ありがとうございます。

現EC-CUBEの計算方式だと、1円未満の金額に対して端数処理を商品ごとに実施している形となります。
つまり、カートの中に4アイテム入っていれば、4回端数処理(端数が出るか出ないかは別として)をしていることになります。

このことが、国税庁が指摘している、”**適格請求書の記載事項である「税率ごとに区分した消費税額等」に1円未満の端数が生じる場合には、一つの適格請求書につき、税率ごとに1回の端数処理を行います。**”
に反していると、思われますが、、、

![181472091-38acf7da-3c52-448f-8819-90fd06aa4a8a](https://user-images.githubusercontent.com/14307966/181732341-6abc4580-2d0f-4556-869f-b5965cfac12b.png)

端数が発生しないような価格設定の店舗さんでは、問題ないのかもしれませんが
端数が発生してしまう価格設定の店舗さんだと、1取引で最大2円の差異が生じるはずですが、、、

とりあえず、一度、何人か税理士に聞いてみます。

**Comment by nanasess** [comment]
@FujiiToshio ご確認ありがとうございます。
国税庁の資料([適格請求書等保存方式の概要ーインボイス制度の理解のために](https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/0020006-027.pdf))の 9Pにわかりやすい例がありました。
<img width="411" alt="スクリーンショット 2022-07-29 21 10 13" src="https://user-images.githubusercontent.com/815715/181755636-7afade67-b93b-4b62-806a-409debbff263.png">

上記【例3:認められる例】が、EC-CUBE4.2の計算方法と一致すると思われますが、いかがでしょうか。

**Comment by FujiiToshio** [comment]
ご回答ありがとうございます。

確かに、商品ごとに税率計算をして端数処理することは、問題ないようです。

例3と同条件でEC-CUBE4.2で試してみました。
※小数点以下は切り捨て。
![テストショップ 商品購入(3)](https://user-images.githubusercontent.com/14307966/182075837-b0114cd1-3a57-49c4-bff9-2dd61fb33920.png)
上記の通り、合計で177円マイナスになっています。

これにある問題は、単価計算で税込(＋端数処理)の通り端数処理を単価で行なっている為に発生しております。
つまり、単価を計算した時点で、1円づれる可能性があります。
ご提示いただいた資料の3は、(税抜×個数)×税率(＋端数処理)となっており、端数処理のタイミングが違う為
個数が増えるとその分価格がづれます。

ちなみに、弊社にてEC-CUBEで作成させて頂いたいくつかの会社(サイト)さんは、ほとんどの場合、税抜き合計を合算した後
それぞれの税率で消費税を計算する予定だそうです。

**Comment by nanasess** [comment]
@FujiiToshio 具体例のご提示ありがとうございます！
なるほど、これはインボイス対応に限らず、1系の頃からの課題ですね。

[何度か話題](https://indigo-design.org/2009/07/calculate-consumption-tax/)にあがっていますが、財務省の[総額表示に関する主な質問](https://www.mof.go.jp/tax_policy/summary/consumption/a_001.htm#15)には、以下のような記載があります。

> 「総額表示義務」は、値札や広告などにおいて「消費税相当額を含む支払総額」の表示を義務付けるものであってレジシステムの変更を義務付けるものではありません。しかし、「総額表示」の下で、「税抜価格」を基に計算するレジシステムを用いている場合には、下の例のような問題が生じ、消費者との間でトラブルが発生する場合があります。
したがって、このような場合には、「税込価格」を基に計算するレジシステムへの変更することが考えられます。また、システム変更が困難な場合には、「消費税の計算上、レジでの精算の際に合計額が異なる場合がある」旨の周知を行うなどの対応が必要になると考えます。

税込(＋端数処理) x 個数で計算するか、(税抜×個数)×税率(＋端数処理)で計算するかは事業者に委ねられており、どちらでも差し支えないという認識です。
(税抜×個数)×税率(＋端数処理)で計算する場合は、「消費税の計算上、レジでの精算の際に合計額が異なる場合がある」旨の周知が必要ということもあり、 EC-CUBE では従来より「税込価格」を基に計算しております。
B2Bサイトの場合は総額表示義務から外れますので、税抜価格を基に計算するようカスタマイズされるケースが多いです。

もし、総額表示や実際の運用に際して認識が間違っておりましたら、ぜひご指摘いただければ助かります。

**Comment by FujiiToshio** [comment]
ご回答ありがとうございます。

結局、どちらでも良いと言うことなのですね。
大変勉強になりました。

(税抜×個数)×税率(＋端数処理)で運用を考えていらっしゃるクライアント様には
カスタマイズする方向で考えたいと思います。
