### ISSUE TITLE
受注情報に関する不具合報告

### ISSUE THREAD

**Issue by 2stars** [EC-CUBE/ec-cube#548]
受注情報に関連つく配送業者を管理画面上から削除後に対象の受注情報を閲覧するとエラーが発生します。

再現手順
1. 「admin > 設定 > 基本情報設定 > 配送方法設定」より配送業者を登録
2. フロントより商品を購入。No.1の配送業者を指定
3. No.2の受注を「admin > 受注管理 > 受注マスタ > 一覧」より閲覧（確認のため）
3. No.1の配送業者を「配送方法設定」より削除
4. No.3と同様の手順で受注情報を確認（ここでエラー）

https://github.com/EC-CUBE/eccube3-doc/blob/eccube-3.0.0-beta/ER-D/ER-order.xls

エンティティを確認しますと下記のようにデータが関連づいており、
削除されているdtb_delivery.delivery_idを参照するためエラーが発生してるのではないかと思われます。

dtb_order.order_id =  dtb_shipping.order_id
dtb_shipping.delivery_id = dtb_delivery.delivery_id

> 動作環境
EC-CUBE:3.0.1
DBサーバー:PostgreSQL 8.4.11
WEBサーバー:Apache/2.2.3 (CentOS)
PHP:5.3.10

**Comment by 2stars** [comment]
dtb_deliveryから論理削除した配送業者を有効化することでエラーが解決できました。
　→update dtb_delivery set del_flg = 0

一応報告まで。

**Comment by aminotsukasa** [comment]
単純に参照整合性制約のように注文から参照されている支払い方法は削除できないようにしてしまうと不都合があるように思います
EC-CUBE2系だとこの部分はどう動くんでしたっけ?

**Comment by nanasess** [comment]
>  EC-CUBE2系だとこの部分はどう動くんでしたっけ?

dtb_order.payment_method に支払方法の文字列が入っているので、受注履歴の支払方法名は、そのまま残ります。
そのまま受注を更新しようとすると、支払方法を選択してくださいとエラーが出るはずです。

**Comment by aminotsukasa** [comment]
@nanasess 
ありがとうございます。

フロントも合わせて考えると、支払い方法を削除した場合DB上では該当レコードに削除フラグが立っているので
フロント側では新規注文時の支払い方法として使用できない
管理者側では削除フラグが立っていても注文時の支払い方法が表示される(更新は不可)
でしょうか?

**Comment by Yangsin** [comment]
購入時点ので支払方法や配送業者のIDと名称（表示用として）を受注情報に合わせてもつようになっていますので
受注データと支払方法や配送業者が紐づく必要はなく。
新たに支払い方法や配送業者を変更する場合にのみ、現在有効な支払方法、配送業者と紐づくようにできればよいのではないでしょうか。
