### ISSUE TITLE
[4.2] 0.1の電話番号を入力して、登録が成功する

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5483]
## 概要(Overview)
電話番号を入力フィールドにて、数字を入力する必要があります、少数を入力しても、データチェックを行っていないため、登録が成功になってしまいます。

## 期待する内容(Expect)  or 要望 (Requirement)
10 進数データをチェックする必要があります

## 再現手順(Procedure)
Step 1. 会員ログインして、 /mypage/deliveryへ遷移する
![1](https://user-images.githubusercontent.com/105194449/182062130-35581269-9be6-441c-ab32-47e06e558a7f.png)

Step 2. 新規お届け先を追加するボタンを押し下げする
電話番号に0.1を入力して、ほかの必須項目も入力する
登録するボタンを押し下げする
![2](https://user-images.githubusercontent.com/105194449/182062037-2fe3fdf9-a914-4cc2-b6d2-704a6e859734.png)

Step 3. お届け先の登録が成功した画面
![3](https://user-images.githubusercontent.com/105194449/182062045-3c7d2fd6-e537-4c91-bfb6-39c1b7802280.png)

チェック必要があるケースは以下になります：
- 0.1の少数を入力
実際: 登録が成功
期待: 通知表示 「数字で入力してください。」

- 123.123.123を入力
実際: 通知表示 「数字で入力してください。」
期待: 123123123

- 123 123 123を入力
実際: 通知表示 「数字で入力してください。」
期待: 123123123

- 123-123-123を入力
実際: 123123123 (OK)

- 1e1を入力
実際: 登録が成功
期待: 通知表示 「数字で入力してください。」

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
Monkey Test

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5482 で対応
