### ISSUE TITLE
How can I generate an entity file from an exist database or exist table?

### ISSUE THREAD

**Issue by bocanhcam** [EC-CUBE/ec-cube#5484]
This question may not relate to ec-cube but I still want to ask:

How can I generate an entity file from an exist database or exist table?

example:
- I already have a table name:` xxx_clients `and want to generate an entity file name `Client` at `Customize/Entity`

+ EC-CUBE: 4.1
+ PHP: 7.4
+ MySQL 5.7

**Comment by chihiro-adachi** [comment]
@bocanhcam 

Try the following command.
```
bin/console doctrine:mapping:import --path=app/Customize/Entity --filter=Client Customize\\Entity annotation
```
The generated file may need some rework.

**Comment by bocanhcam** [comment]
Thanks @chihiro-adachi !
