### ISSUE TITLE
[4.2] 注文中に規格を非表示に変更しても購入を完了できる

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5491]
## 概要(Overview)
- カートの商品ページにて、ユーザーが注文中に、もし管理者が商品の規格を非表示すると数量の上下ができなくなる
- 注文ページにて、お届け先を追加するへアクセスして、数量の上下ができる
- 商品の規格を非表示しても、注文が成功になる

## 期待する内容(Expect)  or 要望 (Requirement)
標準の非表示の製品を確認し、ユーザーにメッセージを表示します

## 再現手順(Procedure)
Step 1. 注文ページにて、規格がある商品をカートに追加する
![1](https://user-images.githubusercontent.com/105194449/182514551-4840f75b-414b-4825-9cb0-8f854cf320d3.png)
Step 2. 企画管理ページへアクセスする
![2](https://user-images.githubusercontent.com/105194449/182514582-bab31e6f-1490-4eb8-abf9-90cfe5f3a503.png)
Step 3. 製品規格を非表示にして購読ボタンを押す
![3](https://user-images.githubusercontent.com/105194449/182514595-758fb331-183b-4466-8417-090d634fc85f.png)
Step 4. 注文ページへ戻る,
規格が非表示された商品はまだ残る
![4](https://user-images.githubusercontent.com/105194449/182516473-1008a188-b631-4168-b5f5-4a2bfc8eb701.png)

Step 5. 商品の詳細ページへアクセスして、商品の規格がちゃんと日表示されること確認する
![5](https://user-images.githubusercontent.com/105194449/182516470-4b2a3f3e-5e57-4584-83da-e4981fe49dda.png)

Step 6. カートへアクセスする
規格が非表示された商品がまだ残ることを確認する
![6](https://user-images.githubusercontent.com/105194449/182516458-78cb6cce-6f49-44d7-9055-82060010c2a2.png)

Step 7.  規格が非表示された商品の数量上下ボタンを押し下げする
でも量は変わらない
![7](https://user-images.githubusercontent.com/105194449/182516438-1d84086d-925f-457b-9103-590ba63adcfc.png)

Step 8. レジに進む ボタンを押し下げする, ログイン画面が表示する
![8](https://user-images.githubusercontent.com/105194449/182516416-91546f6c-73c7-4c42-a366-b47d46754db6.png)

Step 9. 会員でログインする
注文手続きページへ遷移する
![9](https://user-images.githubusercontent.com/105194449/182516412-1df06cc9-56d8-4373-a11c-ec50a8c05b0f.png)

Step 10. お届け先を追加するボタンを押して、お届け先追加ページへ遷移する
![10](https://user-images.githubusercontent.com/105194449/182516362-e3e6c992-ba93-406f-84ad-51036906e2dd.png)

Step 11. お届け先追加ボタンをおして、住所を追加して、また数量も増やす
![11](https://user-images.githubusercontent.com/105194449/182516305-7c0046ad-c84e-43ff-a703-1903cc5682ec.png)

Step 12. 登録ボタンを押すと注文手続き画面が表示されます,
商品の数量が変更される
![13](https://user-images.githubusercontent.com/105194449/182516243-58bdbc4d-48d0-4034-99e9-06409216d956.png)

Step 13.
確認するボタンを押して、注文確認ページへ遷移する
注文するボタンを押して、支払い成功ページが表示される
![15](https://user-images.githubusercontent.com/105194449/182516209-2d5177cf-0980-4fff-8816-ce24c90b8d6a.png)

Step 14. 管理画面で、受注管理ページへアクセスする
![842e6466-8824-4963-8731-b06985a8699c](https://user-images.githubusercontent.com/105194449/182515933-1222eaf8-d4d7-4972-977d-255bf865e0ce.png)

Step 15. 成功した請求書の詳細を見る
![17](https://user-images.githubusercontent.com/105194449/182515925-90a0dbc4-4176-4a1d-9fd1-b169d5ca341b.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
Monkey Test

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5515 で対応
