### ISSUE TITLE
定休日カレンダーの編集時にキャンセルすると編集中のタイトル/日付のままになる

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5492]
## 概要(Overview)
定休日カレンダー設定の編集時に、日付の重複などでエラーが表示された場合
その後キャンセルすると、定休日の一覧には、(見た目上)変更したタイトル/日付が表示されたままになる。

## 期待する内容(Expect)  or 要望 (Requirement)
エラーが表示された場合も、決定せずに単にキャンセルした場合と同様に、編集前の値に戻ってほしい。

## 再現手順(Procedure)
STEP1.
![image](https://user-images.githubusercontent.com/8424850/182606789-205d75ee-b237-41dd-ad79-dc74fca07060.png)
既存の定休日に対して、他と被る日付を入力し、決定ボタンクリック
STEP2.
![image](https://user-images.githubusercontent.com/8424850/182606958-f925169e-9962-492d-9afc-a83677039646.png)
エラーになるので、キャンセルボタンをクリックすると、編集時の値が表示される
(決定ボタンを押さずに、一時的に編集→キャンセルすると、元の値に戻るので、キャンセルボタンの動作が異なることになる)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.4.x
+ DB:
  - PostgreSQL 14.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5517 で対応
