### ISSUE TITLE
お届け先の複数指定画面でボタンのボーダーが表示されない

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5493]
## 概要(Overview)
お届け先の複数指定画面で、「新規お届け先を追加する」「削除」ボタンにボーダーが表示されない

## 期待する内容(Expect)  or 要望 (Requirement)
ボタンとして表示されるようになるとよいです

## 再現手順(Procedure)
![image](https://user-images.githubusercontent.com/8424850/182623854-68bfee31-3bcb-4ad9-af5b-7a9bde1e4f48.png)
Chrome、FireFoxで確認しました

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5494 で対応
