### ISSUE TITLE
[4.2] 範囲外の日時値を検索する

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5499]
## 概要(Overview)
 範囲外の日時値を検索する

## 再現手順(Procedure)

Step 1. ログイン履歴ページにて
![image](https://user-images.githubusercontent.com/104967957/182787963-8c07b616-51a6-444e-8823-094c096e0e40.png)

Step 2. 詳細検索で「01/01/0001 12:00 AM」を検索する
検索ボタンを押し下げする
![image](https://user-images.githubusercontent.com/104967957/182788513-77bf36c6-6068-4555-81d5-fc0a64e8d12d.png)

Step 3. エラー画面 (APP_ENV=prod, APP_DEBUG=0)が表示される
![image](https://user-images.githubusercontent.com/104967957/182788337-797a78fb-ab91-4bed-9507-662635c52c87.png)

Step 4. エラー画面(APP_ENV=dev, APP_DEBUG=1)が表示される
![image](https://user-images.githubusercontent.com/104967957/182788411-c5055238-b0d9-4435-b52b-f8268db10d10.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 

## 関連情報 (Ref)
Monkey Test

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5576 で対応
