### ISSUE TITLE
インストーラーの「DBサーバーのIP」という記載がわかりにくい

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#550]
フォーラムより
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16206&forum=2&post_id=71941#forumpost71941

**Comment by seasoftjapan** [comment]
:+1:

ついでに、入力必須も止めて欲しい。初期値 localhost でも良いかもしれないけど。

何れにしても、実際にIPアドレスを入力する必要があるケースは稀だと感じる。

**Comment by erizou1492** [comment]
入力必須でなくてもインストールできるなら、是非必須を外してほしいです。

**Comment by Yangsin** [comment]
2.13までと同様に、ラベル「DBサーバー」 として、初期値 localhost ではいかがでしょうか？

**Comment by seasoftjapan** [comment]
無理なくできるならば、ビジュアル的に必須項目は減って欲しいというのはありますけど。1回限りの画面なので、あまり気にしなくて良いのかもしれませんね。

技術的には、PDO の dsn の仕様を把握できていないのですが、localhost でソケットへ行きますよね？以前、127.0.0.1 に繋ぐ実装があった記憶があって。

**Comment by erizou1492** [comment]
借りているGMOクラウドのiClustaでは2.13のときから「localhost」ではインストールできませんでした。今回もlocalhostとしても「データベースに接続できませんでした。」となり、進みません。
必須ライブラリの不足かと懸念もしていました。

**Comment by seasoftjapan** [comment]
> 「localhost」ではインストールできませんでした。
2.13 ですと、何を入力すると (若しくは空欄だと) インストールできましたか?

**Comment by k-yamamura** [comment]
記載するラベルですがWordPressに合わせておけば良いんじゃないでしょうか。

![wordpress](https://cloud.githubusercontent.com/assets/12592005/8692159/7865e75e-2b06-11e5-9dc3-4b0bb68f8389.png)

**Comment by erizou1492** [comment]
今から2.13をアップして改めて試そうとしているところですが、今までは図の赤丸を入力していました。
![db-name](https://cloud.githubusercontent.com/assets/4628802/8692249/8a633956-2b07-11e5-8b1e-4ceaaeb2f45d.jpg)

**Comment by seasoftjapan** [comment]
共用サーバーですと、一般的にこの値の入力は必要です。入力を省略できる可能性が高いのは、VPS・クラウド・専用サーバーなどの汎用環境ですね。

添付いただきましたコントロールパネルでは「データベースサーバー」と読んでいますが、これを EC-CUBE ではどう記載するのが分かりやすいかというのが本題の部分ですね。

@erizou1492 さんの書かれている「データベースのホスト名」というのは、個人的には分かりやすいですね。ただ、「ホスト名」を良く理解していない人も多いようで、悩ましいですが・・・

**Comment by erizou1492** [comment]
2.13の場合、未入力はエラーでダメでした。seasoftjapanさんがおっしゃるとおりです。
エラー画面添付します。

![2-13-eccube](https://cloud.githubusercontent.com/assets/4628802/8692602/d08bd41c-2b0a-11e5-977b-6cf183b24c28.jpg)

**Comment by nobuhiko** [comment]
3の場合も、2.13と同じものをいれれば普通は動くはずです
動かないということは、問題は別にありますね

**Comment by erizou1492** [comment]
インストール時にライブラリ等の不足があれば、チェックがかかるとありがたいですね。
インストールログに出るのでもいいですが。今のログではそこまで分からないので。

**Comment by nobuhiko** [comment]
src/Eccube/Form/Type/Install/Step4Type.php の 90行目で var_dump($e); をすると、何が原因なのかわかるかもしれません。

**Comment by ttsuru** [comment]
@erizou1492 
GMO CloudのiCLUSTA+であれば、MySQLのポートが違うと思います。

**Comment by erizou1492** [comment]
@nobuhiko 
dump吐かせたらブラウザ画面何スクロールも出て、マシンのメモリが一気に食われて、どこがどこか検証できずにマシン再起動になってしまいました…。スペック高くないので…。
ログファイルへ書き出させる方向でやってみます。

@ttsuru 
ポートが違うとは…？　
PLAN MANAGERのデーターベース設定のポート番号とは違うという意味ですか？

**Comment by nobuhiko** [comment]
@erizou1492 
var_dump($e->getMessage()); だと大丈夫だと思います

**Comment by erizou1492** [comment]
@nobuhiko 
試したところ、下記エラーでした。127.0.0.1でやってみても同じエラー。
"SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'mysql529.in.shared-server.net' (111)" 

localhostの場合は、
"SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)" 

適当なIP入れた場合
"SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 104"

**Comment by nobuhiko** [comment]
@erizou1492 
あー、わかりました。
ポートが違うDBに接続できないバグが有ります

if (!empty($data['port'])) {
を
if (!empty($data['database_port'])) {
になおすとつながると思います

**Comment by ttsuru** [comment]
やはりポート関連でしたね！

**Comment by erizou1492** [comment]
@nobuhiko 
@ttsuru 
いきましたーーーー！！
バグで良かったです。
ありがとうございました。

**Comment by erizou1492** [comment]
しかし、dtb_memberにユーザーが出来ておらず、管理画面にログインできずです。
#544

**Comment by nobuhiko** [comment]
もう1回インストールし直すか、EC-CUBE 3 Weekly Buildを試すといいと思います
http://www.ec-cube.net/download/index.php

**Comment by erizou1492** [comment]
Weekly Buildを入れなおしたら上手く行きました。
先ほどはショップ情報も入ってなかったのですが、今回は上手くいきました。

**Comment by Yangsin** [comment]
こちら修正済みですので、クローズとします、
