### ISSUE TITLE
[4.2] 認証キー設定

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5500]
## 概要(Overview)
アクセス オーナーズストア -> 認証キー設定
認証キーは大文字と小文字を区別せずに入力できます

## 再現手順(Procedure)
Step 1. 認証キー設定へアクセスする
![image](https://user-images.githubusercontent.com/105194449/182792263-f3894fd7-f0c9-474b-b0c9-17cd5385885b.png)

Step 2. 認証キー新規発行 ボタンを押し下げする
![image](https://user-images.githubusercontent.com/105194449/182792284-662d82b2-fbcd-489e-838f-7ba97a0a7b55.png)

Step 3. すべて文字を大文字若しくは小文字で入力する
認証キー新規発行ボタンを押し下げする
![image](https://user-images.githubusercontent.com/105194449/182792319-989302c6-44f2-4dc6-b861-4ca59e3c5ca5.png)

Step 4. 登録成功の通知が表示される
![image](https://user-images.githubusercontent.com/105194449/182792343-2c9e919f-7d15-422d-9081-bf934fcb3220.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
Monkey Test

**Comment by chihiro-adachi** [comment]
特に明示していないですが、大文字小文字の区別なしは許容しています。
