### ISSUE TITLE
[4.2] CSV (アップロード)

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5501]
## 概要(Overview)
２つ規格のCSV商品を更新して、規格１と規格２の位置を差し替えする

## 再現手順(Procedure)
Step1.  商品管理 → 商品登録
公開状態の新規商品を登録する
![image](https://user-images.githubusercontent.com/105194449/182816311-de4d6e32-1082-4e15-9802-df9617a50ab3.png)

Step 2. この商品の規格を確認ボタンを押し下げする
新規作成した商品の規格を登録する
![image](https://user-images.githubusercontent.com/105194449/182816374-06ee20ca-b89e-4e9d-8296-036f82e6ef2f.png)
![image](https://user-images.githubusercontent.com/105194449/182816394-214a91fe-0cef-4b51-a69e-39d96770654b.png)
Step 3. フレーバー (CUBE用味)の規格を選択する
サイズ (CUBE用サイズ)も選択する
![image](https://user-images.githubusercontent.com/105194449/182816424-8c4df7bb-3e9a-441c-81f7-09052bc1515e.png)
Step 4. 商品企画の情報を登録する
登録成功の通知が出てくる
![image](https://user-images.githubusercontent.com/105194449/182816476-a7a8f9f7-ae36-437d-acd6-d85ec693a6a6.png)
Step 5. 商品編集ページへ戻して、作成した商品規格の表示を確認する
![image](https://user-images.githubusercontent.com/105194449/182816503-741d4c89-8658-4041-b3f6-74a10d96a505.png)
Step 6. UIで、各規格を確認する
![image](https://user-images.githubusercontent.com/105194449/182816537-119a091b-fc50-4350-bde3-ca81cd4b64f3.png)
Step 7. 商品管理 → 商品CSV登録
![image](https://user-images.githubusercontent.com/105194449/182816579-f324da65-226b-4630-9d6f-fb8c00df1872.png)
Step 8. CSVにアップルされる内容は以下のように用意する
(File 1)に対して以下通り
商品ID,公開ステータス(ID),商品名,ショップ用メモ欄,商品説明(一覧),商品説明(詳細),検索ワード,フリーエリア,商品削除フラグ,商品画像,商品カテゴリ(ID),タグ(ID),販売種別(ID),規格分類1(ID),規格分類2(ID),発送日目安(ID),商品コード,在庫数,在庫数無制限フラグ,販売制限数,通常価格,販売価格,送料,税率
4,1,パンケーキ,,,,,,,,,,1,1,4,,,,1,,4000,3000,,

(File 2)に対して以下通りですがそのうちに規格が差し替えされた
商品ID,公開ステータス(ID),商品名,ショップ用メモ欄,商品説明(一覧),商品説明(詳細),検索ワード,フリーエリア,商品削除フラグ,商品画像,商品カテゴリ(ID),タグ(ID),販売種別(ID),規格分類1(ID),規格分類2(ID),発送日目安(ID),商品コード,在庫数,在庫数無制限フラグ,販売制限数,通常価格,販売価格,送料,税率
4,1,パンケーキ,,,,,,,,,,1,4,1,,,,1,,4000,3000,,
![image](https://user-images.githubusercontent.com/105194449/182816806-f3020dae-d6f3-4e36-847d-70c643c16dde.png)

Step 9: csv (File 2)にアップして、一括登録を実行ボタンを押し下げする
アップロード成功の通知が出てくる
![image](https://user-images.githubusercontent.com/105194449/182816848-9d8652f0-e980-46b2-81ad-d06882e5f052.png)

Step 10. 商品一覧ページにて
商品の規格確認を選択する
更新した規格が表示される
![image](https://user-images.githubusercontent.com/105194449/182816906-fc43dd41-3b2a-475e-a85e-802ad857cb74.png)

Step 11. 商品詳細ページにて、更新した規格が表示される
![image](https://user-images.githubusercontent.com/105194449/182816970-8e8519fe-7b08-4b28-b907-5373bd5a513e.png)

Step 12. 商品の規格編集ページへアクセスする
ここで、更新した規格が表示されない
![image](https://user-images.githubusercontent.com/105194449/182817014-d79309b9-d2b1-4f54-a0d0-297443ffed90.png)

Step 13. 商品詳細のUIにて
余裕になってしまっている商品規格ががまだUIに表示される
![image](https://user-images.githubusercontent.com/105194449/182817047-3ebb655f-98e5-4db8-b9db-cffc3dddc401.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
Monkey Test

**Comment by chihiro-adachi** [comment]
報告ありがとうございます。
指定したID通りに更新されており、挙動としては正しいかと思います。
厳密には適切な規格かどうかのチェックがあればよいかとは思いますが、頻繁に発生するとは考えずらいです。
