### ISSUE TITLE
コピーライトの記載について

### ISSUE THREAD

**Issue by masamoto3** [EC-CUBE/ec-cube#5507]
## 概要(Overview)
Cipyright(c)について

## 期待する内容(Expect)  or 要望 (Requirement)
できればコピーライトはマルシーでお願いしたい。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
GPLライセンスの著作権表示の記載だと

> 常に英語の言葉の“Copyright”を国際的慣習として使ってください。これは国際的に、ほかの言語のものでも使います。望みならば(そして文字セットがそれをサポートしていれば)、著作権マーク“©”を含めることも可能ですが、必須ではありません。3文字の列、“(C)”、を使うことは法律上なんの意味もありませんが、まったく害はありません。

https://www.gnu.org/licenses/gpl-howto.ja.html

とのこと。

**Comment by xuelian311** [comment]
現状のままで問題ないという判断でクローズいたします。また今後対応の必要があると判断した場合は再オープンさせていただきます。
