### ISSUE TITLE
[4.2] ラジオボタンのエラー時の表示

### ISSUE THREAD

**Issue by Yuu1188** [EC-CUBE/ec-cube#5508]
## 概要(Overview)
新規会員登録のメールマガジン送付についてのバリデーションエラーメッセージ等がほかの要素のように赤く表示されない

## 期待する内容(Expect)  or 要望 (Requirement)
ほかの要素と同じようなエラー表示に変える

## 再現手順(Procedure)
新規会員登録のメールマガジン送付についてを選択せずに同意するボタンを押下する

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
メルマガの追加項目だけでなく、radioボタン形式のエラーメッセージにstyleがあたってないようですね。

<img width="710" alt="image" src="https://user-images.githubusercontent.com/8196725/183325976-4268f5fa-2f7e-4a30-a059-9361a8b3a60c.png">

**Comment by chihiro-adachi** [comment]
#5541
