### ISSUE TITLE
vendor以下がないとFatal error: require() になる

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#551]
installerで Composer is not installed.  的なエラーを出してくれると、画面真っ白にならなくていい気がします

http://coelacanth.jp.net/fuelphp1-6%E3%81%A7composer-is-not-installed%E3%82%A8%E3%83%A9%E3%83%BC/

**Comment by Yangsin** [comment]
ご意見、ご対応ありがとうございます。3.0.2にて取り込ませていただきます。
