### ISSUE TITLE
性別の選択項目について見直しが必要

### ISSUE THREAD

**Issue by masamoto3** [EC-CUBE/ec-cube#5511]
## 概要(Overview)
性別を選ぶのに
男・女しか選べないのは今時ではないと思う。
デフォルトで「答えたくない」も入れてほしい。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
yahooだと男性・女性・その他・回答しないの4択ですね。
https://about.yahoo.co.jp/info/blog/20180613/diversity.html

上記は2018年の発表内容ですが、現時点でも以下の4択のようです。 

アカウント編集画面
<img width="665" alt="image" src="https://user-images.githubusercontent.com/8196725/183326435-975f1740-ebc6-4bf9-8ec4-86cc9ab3fe11.png">

**Comment by nanasess** [comment]
ISO は以下のとおり

https://ja.m.wikipedia.org/wiki/ISO_5218

**Comment by chihiro-adachi** [comment]
現状ではマスターデータのmtb_sexで、データを追加いただく形でご対応いただければ修正は可能です。
今後標準でどのような形がよいか検討できればと思います。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5651
