### ISSUE TITLE
会員登録時のメールアドレスで、ドメイン部分が不十分でも登録できる

### ISSUE THREAD

**Issue by masamoto3** [EC-CUBE/ec-cube#5512]
## 概要(Overview)
会員登録でのメールアドレスを入力

## 期待する内容(Expect)  or 要望 (Requirement)

会員登録でメールアドレスを入力するとき、
ドメイン（.com）などのチェックをしていないようですが仕様ですか？
ドメイン（.com）とかが無くても登録できてしまう。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@nanasess 
こちらわかりますでしょうか？
事象としては再現するのですが、rfcではドメイン部分のフォーマット定義されてましたっけ。

**Comment by nanasess** [comment]
@chihiro-adachi ドメイン部は **FQDN のみが許可されます** くらいしか定義されてないですね。
https://www.rfc-editor.org/rfc/rfc5321.html#section-2.3.5

出現する文字チェックは必要ですが、必ずしも .com などのトップレベルドメインが必要なわけではないと思われます

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます、了解です。

**Comment by chihiro-adachi** [comment]
@masamoto3 
メールアドレスの書式のチェックとしては、仕様通りということで扱わせていただければと思います。

厳密にチェックするにはDNSチェック等の手法もありますが、弊害の方も多いということで標準では採用していません。
ご参考まで。
https://github.com/EC-CUBE/ec-cube/issues/2948#issuecomment-392995999
