### ISSUE TITLE
規格分類をすべて非表示にしたときの価格の表示について

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5522]
## 概要(Overview)
規格を持つ商品で、"チョコ""抹茶""バニラ"などの規格分類をすべて非表示にすると
価格が0円で、在庫切れ表示になる
また、JSON-LDでは価格が空で、構文エラーになっている

## 期待する内容(Expect)  or 要望 (Requirement)
”0円”と表示してしまうと、お客様に良からぬ期待を抱かせてしまうので、価格を消すか別の適切な表現がいいです
JSON-LDはpriceの項目をなくすか、TEXT型での適切な表現が必要そうです

## 再現手順(Procedure)
STEP1.規格分類をすべて非表示にします
![image](https://user-images.githubusercontent.com/8424850/184155165-e264f4f8-649b-4bf5-9327-5176b9bad043.png)
STEP2.その規格を利用している商品を表示します
![image](https://user-images.githubusercontent.com/8424850/183822168-9333c6e9-5e63-43eb-b354-2d6b50f70b75.png)
![image](https://user-images.githubusercontent.com/8424850/183822607-d8e324cc-c2db-428a-9d01-9579e32e27ac.png)

商品は０円、JSONは値が空で出力されます

### 環境 (environment)
+ EC-CUBE: 4.1.x/4.2β
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@takeuji 
0円表記については、適切な表現があればご提案いただけると助かります。
json-ldの構文エラーに関しては、不具合として修正できればと思います。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5775 で対応
