### ISSUE TITLE
CookieのSecure Flagが有効になっていない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5525]
## 概要(Overview)
SSLが有効な環境では強制的にSecure Flagも有効になったほうがよいのではないでしょうか

## 期待する内容(Expect)  or 要望 (Requirement)
CookieのSecure Flagが有効になる

## 再現手順(Procedure)
初期インストールをしてCookieを確認

### 環境 (environment)
+ EC-CUBE: 4.2.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@nobuhiko 
どのcookieでしょうか？

**Comment by nobuhiko** [comment]
@chihiro-adachi 
eccube という session.cookie です

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます。
httpsでのアクセスであればセキュア属性は有効になるかと思うんですが、有効になってないですか？

https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Session/Storage/Handler/SameSiteNoneCompatSessionHandler.php#L45

**Comment by nobuhiko** [comment]
@chihiro-adachi cloudflareが原因でしたーー

**Comment by chihiro-adachi** [comment]
@nobuhiko 
了解です、ご確認ありがとうございます。
