### ISSUE TITLE
[4.2] ラジオボタンのエラー時の表

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5526]
## 概要(Overview)
ラジオボタンのエラーメッセージ形式

## 再現手順(Procedure)
Step 1. アクセス /entry
![image](https://user-images.githubusercontent.com/105194449/184117160-51c73489-d70a-4f39-a55f-8ba142dc29af.png)

Step 2. ラジオボタンのエラーを表示するように値を変更します
![image](https://user-images.githubusercontent.com/105194449/184117197-43218860-0790-47d5-8204-13694bb7d5af.png)

Step 3. 値を 0 に変更します
![image](https://user-images.githubusercontent.com/105194449/184117235-1eea10e3-bc84-4165-9384-9dbf1c3e99a1.png)

Step 4. 値を編​​集したラジオボタンを選択します, 購読ボタンを押す
![image](https://user-images.githubusercontent.com/105194449/184117284-e7b2db6f-d93c-4e1a-975e-e246fcb0fe1e.png)

Step 5. radioボタン形式のエラーメッセージにstyleがあたってないようですね。
同じことが /mypage/change でも起こります
![image](https://user-images.githubusercontent.com/105194449/184117347-77c7e31d-8d49-4dec-835e-f4050d281ba7.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta v2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/5508

**Comment by chihiro-adachi** [comment]
#5508 と同一内容のため、こちらはクローズします。
