### ISSUE TITLE
[4.2] 郵便番号の誤差表のフォーマット

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5527]
## 概要(Overview)
間違った形式で表示される郵便番号エラー テーブル

## 再現手順(Procedure)
Step 1. アクセス /contact
![image](https://user-images.githubusercontent.com/105194449/184118554-9b7b0c2d-0249-437d-8369-495c7b4c820c.png)

Step 2. [1e1]の郵便番号で入力して、登録する
間違った場所と形式で表示される郵便番号エラー メッセージ
![image](https://user-images.githubusercontent.com/105194449/184118622-314e212d-ede6-4b63-b7a2-4e9d7f3bfe20.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta v2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5546 で修正
