### ISSUE TITLE
購入後のポイント付与率変更によるポイント進呈問題

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5529]
## 概要(Overview)
お客様からのお問い合わせで、ポイント付与率を購入後に変更した場合、変更が反映されてしまう現象が発覚。
（100pt進呈キャンペーン中に購入があったのに、10ptの期間に出荷したら10ptになってしまった。）

## 期待する内容(Expect)  or 要望 (Requirement)
購入時のポイントを維持して欲しい

## 再現手順(Procedure)
藤崎トライアル環境でテストしたところ、下記現象が確認できました。
①管理画面でポイント付与率を10%に変更
②ユーザー1000円購入→100pt加算予定表示
③管理画面で受注内容を確認→100ptと記載あり
④管理画面でポイント付与率を1%に変更
　　→この時点では受注内容は100ptのまま
⑤管理画面の受注で「対応状況」を変更すると10ptに変化（出荷でなくても変更するだけで変わる模様）
※ちなみに、受注一覧から出荷した場合は、100ptで出荷されました。
藤崎管理画面のIDなどが必要でしたら、お申し付けくださいませ。

### 環境 (environment)
EC-CUBE：4.1.2
サーバーOS：Linux eccube-5bc98dcfc-kmzsc 5.4.188+ #1 SMP Sun Apr 24 10:03:06 PDT 2022 x86_64
DBサーバー：PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
WEBサーバー：Apache
PHP：7.4.30 (Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, exif, gd, intl, pdo_pgsql, sodium, zip, Zend OPcache)

**Comment by nobuhiko** [comment]
4.2 でも発生すること確認しました

10%で購入
<img width="1229" alt="受注管理_受注登録_-_テスト店舗42" src="https://user-images.githubusercontent.com/604492/185521117-aeea7a99-326d-4a1d-ba59-0cac6cb06423.png">

1%に変更して、更新
<img width="1221" alt="受注管理_受注登録_-_テスト店舗42" src="https://user-images.githubusercontent.com/604492/185521199-4f0c521d-0805-4715-a707-125aba3c1b4c.png">

受注編集画面に、ポイント付与率が表示されておらず、編集不可な点が根本的な原因に感じる

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5571 で対応
