### ISSUE TITLE
[4.1.x, 4.2.x] 2段階認証(ログイン)

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5530]
## 概要(Overview)
2 要素認証のログインに失敗しました

## 再現手順(Procedure)
Step 1. 設定→システム設定→メンバー管理
![image](https://user-images.githubusercontent.com/104967957/184312961-76fc49ec-943e-4ec2-8fcb-7ba6ec3fcf8e.png)

Step 2. 「新規登録」ボタンを押下する
2段階認証を有効化し、登録する
![image](https://user-images.githubusercontent.com/104967957/184313015-df8d4683-4f14-4deb-8ba4-83899fe74198.png)

Step 3. 一覧画面を確認し、2段階認証が有効かつ設定未完了の状態であることを確認する
![image](https://user-images.githubusercontent.com/104967957/184313073-b0458bff-84cb-4c4e-b7fc-d2fa66da5cb0.png)

Step 4. ログアウト
![image](https://user-images.githubusercontent.com/104967957/184313113-4fd14bab-fe67-4ff1-87ac-2309c73c8bf2.png)

Step 5. 作成したメンバーでログインする
2段階認証の登録画面が表示される
![image](https://user-images.githubusercontent.com/104967957/184313183-c632cdde-8e36-45d3-846e-74f1ad5c73c5.png)

Step 6. Google Authenticatorアプリ等でQRコードをスキャンし、数値を入力する
トークンに誤りがあります。再度入力してください。
![image](https://user-images.githubusercontent.com/104967957/184313236-8dd408cf-4cde-44cd-9cad-499651f54ee3.png)

### 環境 (environment)
+ EC-CUBE: 4.1.2, 4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
@nguyen-tien-dat-10022000 
サーバもしくはスマートフォンの時刻が同期がとれてないのかもしれません。
サーバとスマートフォンの時刻が一致しているか確認できますか？
https://github.com/scheb/two-factor-bundle/issues/56

**Comment by LeTanNghia** [comment]
@chihiro-adachi 
こちらの現象を再度確認しましたが、こちら側のサーバーと電話の間の時間が正しく同期されていません。 その後、時刻を同期して再確認しました。 すべてが正常に動作しています。
ありがとうございました。

**Comment by chihiro-adachi** [comment]
@nguyen-tien-dat-10022000 
ご確認ありがとうございます！
