### ISSUE TITLE
[4.2] リダイレクトURLが不正

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5531]
## 概要(Overview)
管理画面にて、おすすめのプラグインのリダイレクトリンクが不正

## 期待する内容(Expect)  or 要望 (Requirement)
現在: https://test/news/detail.php?news_id=349
期待する内容: https://www.ec-cube.net/news/detail.php?news_id=349
## 再現手順(Procedure)
Step 1. 管理画面で [おすすめのプラグイン → EC-CUBEセキュリティチェック プラグイン(4.2系)] を選択
![image](https://user-images.githubusercontent.com/104967957/184315005-fb89dc88-4139-445c-a5f8-e055f4372c59.png)

Step 2. リンクをクリック「EC-CUBE バージョン別運用環境セキュリティチェックリスト」
![image](https://user-images.githubusercontent.com/104967957/184315437-043c3e7b-669e-499b-80fd-cf47694d169b.png)

Step 3. ページがみつかりません。
現在: https://localhost/news/detail.php?news_id=349
期待する内容: https://www.ec-cube.net/news/detail.php?news_id=349
![image](https://user-images.githubusercontent.com/104967957/184315653-469a4212-9e64-4528-b5eb-4253b51869fb.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
オーナーズストアの登録情報を修正しました。
