### ISSUE TITLE
[4.2] 税金計算エラーを 0 で割った値を表示

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5533]
## 概要(Overview)
管理ページで新しい注文を作成するときに、注文に詳細を追加すると、注文の合計がゼロの場合に税率の計算に関するエラーが発生しました (Division by zero)
これは 8.0 および 8.1 環境で簡単に発生します。

## 再現手順(Procedure)
Step 1. 受注管理 → 受注登録
【商品情報】欄の【その他の明細を追加】ボタンを押してください。
![image](https://user-images.githubusercontent.com/104967957/184319562-cb89251e-8888-43cb-956a-56de62591d3c.png)

Step 2. 注文に詳細を追加する
![image](https://user-images.githubusercontent.com/104967957/184319598-d9abdcc5-67cb-482b-82b0-ce8e33514172.png)

Step 3. システムエラーが発生しました。 (APP_ENV=prod,  APP_DEBUG=0)
![image](https://user-images.githubusercontent.com/104967957/184319644-d3014e53-7a1b-40d0-bdff-ba95db0ec301.png)

(APP_ENV=dev, APP_DEBUG=1)
![image](https://user-images.githubusercontent.com/104967957/184319680-322e99e3-9670-4e25-8da5-e460766ecae1.png)

### 環境 (environment)
+ EC-CUBE:  4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5537 で修正
