### ISSUE TITLE
出荷お知らせメールに「配送方法」の記載が無い

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5536]
## 概要(Overview)
出荷お知らせメールに「配送方法」の記載が無い。

<img width="756" alt="スクリーンショット 2022-08-13 15 13 40" src="https://user-images.githubusercontent.com/16891862/184471342-2af1397f-01a6-4c17-8741-d465c3d25bb3.png">

※補足：「注文受付メール」「マイページの注文履歴」には配送方法の記載があります。

## 期待する内容(Expect)  or 要望 (Requirement)
出荷お知らせメールに「配送方法」が記載されている。

#### お気持ち
購入者としては、出荷通知のメールで出荷されたことと同時に配達業者を知りたい。

## 再現手順(Procedure)
通常の受注と発送手続きを行う

### 環境 (environment)
+ EC-CUBE: 4.2-beta2

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5551 で対応
