### ISSUE TITLE
受注登録画面で商品の削除→追加を行うとエラー

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5539]
## 概要(Overview)
管理画面の受注編集画面で、商品の削除→追加を行うとエラーになる
(既存のidと被る形で商品を登録しようとする場合）

## 期待する内容(Expect)  or 要望 (Requirement)
エラーにならず、登録できるとよいです

## 再現手順(Procedure)
STEP1.　フロントから以下の注文がある状態をスタートとします
商品A
商品B
送料
手数料
![image](https://user-images.githubusercontent.com/8424850/184497768-1ac9b24a-a443-4fe5-b0fc-f00dfbffe87d.png)

STEP2.　商品Bと送料を×ボタンで削除します

STEP3.　この状態で割引を追加します
![image](https://user-images.githubusercontent.com/8424850/184497811-c35ef246-4e93-4e95-959e-4cef2db473bd.png)

そうすると、エラー画面になります
![image](https://user-images.githubusercontent.com/8424850/184497850-e423177e-f4d8-4756-a4fa-ec0d80a37f9d.png)

さらにこの際に、割引ではなく商品を追加すると、追加ではなく既存の行が置き換えられます
![image](https://user-images.githubusercontent.com/8424850/184497869-87d86550-029b-4b07-94b3-b5994254ecdb.png)

### 環境 (environment)
+ EC-CUBE: 4.2.β
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by ryo-endo** [comment]
ref https://github.com/EC-CUBE/ec-cube/issues/4545

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/issues/4545
https://github.com/EC-CUBE/ec-cube/issues/5320

**Comment by chihiro-adachi** [comment]
@takeuji 
ご報告ありがとうございます。
過去に同様のissueがありましたので、こちらはクローズさせていただきます。
