### ISSUE TITLE
[4.1.0, 4.2 beta2] 注文の作成に失敗しました

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5543]
## 概要(Overview)
新規注文作成ページで、商品を2つ追加して最初の商品を削除し、削除した商品を再度追加すると、商品が1つしか表示されず、
次に、請求書の詳細を注文に追加すると、エラー ページが表示されました

## 再現手順(Procedure)
Step 1. 受注管理 → 受注登録
![image](https://user-images.githubusercontent.com/104967957/184569523-1014b2b3-f053-4c16-9c3d-696b58e973bc.png)

Step 2. 必要な情報を入力し、2 つの商品を注文に追加します
![image](https://user-images.githubusercontent.com/104967957/184569542-4c3dbd52-81f0-43e1-808e-c5f8178c844a.png)

Step 3. 注文から最初の商品を削除する
![image](https://user-images.githubusercontent.com/104967957/184569568-3045bab6-d579-4eec-943b-ca029534c5d2.png)

Step 4. 「商品情報」ボタンを押して他の商品を追加
注文画面を確認したところ、商品が消えていて商品が1つしか表示されていない、こちらに問題があると思います
次に「その他の明細を追加」ボタンを押します
![image](https://user-images.githubusercontent.com/104967957/184569597-b210edff-bbdc-48e8-9ac0-221175caf441.png)

Step 5. を表示の一覧が表示されます
![image](https://user-images.githubusercontent.com/104967957/184569607-138176c8-b6d0-43f6-8185-d669cc830dc2.png)

Step 6. 任意のアイテムを追加
![image](https://user-images.githubusercontent.com/104967957/184569620-c32c3ce8-5308-4bc4-a481-f3aaa7cef439.png)

Step 7. システムエラーが発生しました。(APP_ENV=prod, APP_DEBUG=0)
![image](https://user-images.githubusercontent.com/104967957/184569664-64d13262-2fdf-437e-960a-1f4efde68aa3.png)

Step 8: エラーメッセージが表示される (APP_ENV=dev, APP_DEBUG=1)
![image](https://user-images.githubusercontent.com/104967957/184569804-a11d8e4f-ec1e-43be-b7c3-daafec5dbe90.png)

### 環境 (environment)
+ EC-CUBE:  4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/5320

**Comment by chihiro-adachi** [comment]
以下と同一内容のためクローズします。
https://github.com/EC-CUBE/ec-cube/issues/5320
https://github.com/EC-CUBE/ec-cube/issues/4545
https://github.com/EC-CUBE/ec-cube/issues/5539
