### ISSUE TITLE
[4.2] 新着情報を追加するが失敗する

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5544]
## 概要(Overview)
新着情報を作成する際に、もし選択する秒が最初の秒と違っていると作成できない

## 再現手順(Procedure)
Step 1. コンテンツ管理 -> 新着情報管理 -> 新規作成
![image](https://user-images.githubusercontent.com/104967957/184614327-344f805b-9806-4b7c-a358-bea1b6f63ab5.png)

Step 2. 新規作成ページを表示
![image](https://user-images.githubusercontent.com/104967957/184614404-eea94943-cea0-4cf2-9503-43fecdf1aa1e.png)

Step 3. 元の数値と異なる秒数を変更する
![image](https://user-images.githubusercontent.com/104967957/184614453-691053a1-8ba1-48e1-adfc-09aee37f2b9a.png)

![image](https://user-images.githubusercontent.com/104967957/184614475-426c5a3e-3dbc-4ec5-998e-b23037bcad3f.png)

Step 4. 購読ボタンを押す
最初に正しい秒数 (04) を入力するように求めるブラウザー エラー メッセージが表示されます。
[Please enter a valid value . The two nearest valid values are  08/11/2022 4:38:04 PM and 08/11/2022 4:39:04 PM.]
[有効な値を入れてください 。最も近い 2 つの有効な値は、08/11/2022 4:38:04 PM と 08/11/2022 4:39:04 PM です。]
![image](https://user-images.githubusercontent.com/104967957/184614592-91073b93-c670-4ec7-bd4c-1232400b6150.png)

### 環境 (environment)
+ EC-CUBE:  4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5564 で修正
