### ISSUE TITLE
[4.2] モーダルダイアログの終了ボタンの型が不正

### ISSUE THREAD

**Issue by LeTanNghia** [EC-CUBE/ec-cube#5545]
## 概要(Overview)
通知表示が表示される際に、モーダルの終了ボタンが黒枠で囲まれる

## 再現手順(Procedure)
Step 1 新着情報管理ページにて
![image](https://user-images.githubusercontent.com/104967957/184619475-bee9e215-8e47-4ea1-98b6-18da04f5a40e.png)

Step 2. 一つの情報を削除する
確認ダイアログが表示される
ダイアログの終了ボタンの型が不正
![image](https://user-images.githubusercontent.com/104967957/184619270-0b5773fb-2816-4266-ab58-1dcebf7539ae.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5547 で修正
