### ISSUE TITLE
[4.2] 注文時に支払い方法を非表示に変更しても購入完了

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5549]
## 概要(Overview)
注文時に支払い方法を非表示に変更しても購入完了

## 再現手順(Procedure)
Step 1. ユーザー インターフェースで、メンバー アカウントでログインします。
![image](https://user-images.githubusercontent.com/105194449/184841731-c9e06c3f-50ce-43b7-9fe8-779b0c2f7bb0.png)
Step 2. カートに商品を追加してカートに移動
![image](https://user-images.githubusercontent.com/105194449/184841765-a99c6963-d1cb-487b-821f-bf36eb8e00ff.png)
Step 3. [レジに進む]を押して[ご注文手続き]ページへ
![image](https://user-images.githubusercontent.com/105194449/184841798-ca11de05-e168-4b9b-9476-17464de79cfa.png)
Step 4. 発送方法、お支払い方法を選択
![image](https://user-images.githubusercontent.com/105194449/184841830-2b739fa8-49fb-4025-864e-973cf1120f4b.png)
Step 5. [確認する] を押して [ご注文内容確認] ページへ
![image](https://user-images.githubusercontent.com/105194449/184841869-c2b94b32-cd65-44ab-8a14-b428ac50ed3b.png)
Step 6. 管理画面の「支払方法設定」へ
![image](https://user-images.githubusercontent.com/105194449/184841907-62b09ec9-915d-4bc1-a87b-2f83f5ec1b7d.png)
Step 7. ステップ 4 で選択した支払い方法を非表示にします
![image](https://user-images.githubusercontent.com/105194449/184841935-b7bbd39a-6d19-420d-9c55-327f9197f0a6.png)
Step 8. [ご注文内容のご確認]ページで[注文する]ボタンを押してください。
![image](https://user-images.githubusercontent.com/105194449/184841966-6fe24686-1bf8-4eba-8237-ee41cc897a4f.png)
Step 9. お支払い方法を非表示にしても注文は成功です
![image](https://user-images.githubusercontent.com/105194449/184842011-5c660540-a4f0-4d8f-b0c4-aedb6dc2233e.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0 beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5558 で修正
