### ISSUE TITLE
基本設定の郵便番号がハイフン付きで設定できない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5554]
## 概要(Overview)
基本設定で設定できる「郵便番号」が、ハイフン付きで設定できない。
ハイフンを付けて入力しても、保存時にハイフンが取り除かれてしまう。

「当サイトについて」でもハイフンの無い郵便番号が表示されるので、ちょっとかっこ悪い。

<img width="486" alt="image" src="https://user-images.githubusercontent.com/16891862/184911325-152a019d-ee73-4e59-b5a2-7c971555b1f9.png">

## 期待する内容(Expect)  or 要望 (Requirement)
ハイフン付きでも保存できること
(欲を言えばハイフン無しで入力した場合は自動的にハイフンが付与される)

## 再現手順(Procedure)
基本設定で郵便番号をハイフン付きで入力して登録。

### 環境 (environment)
+ EC-CUBE: 4.2-beta2
+ Chrome 104.0.5112.79

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
郵便番号は4.0から、postalcodeとして数値のみの形式に仕様変更されました。
https://github.com/EC-CUBE/ec-cube/issues/2598

現状ではカスタマイズ等でご対応いただく形になるかと思います。
