### ISSUE TITLE
ログイン履歴のステータにの上にマウスオーバすると、ステータスの表示が消える

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5560]
## 概要(Overview)
![画面収録 2022-08-17 23 32 32](https://user-images.githubusercontent.com/16891862/185168495-52dc1a51-2101-47ff-abd2-079350963205.gif)

## 期待する内容(Expect)  or 要望 (Requirement)
表示が消えないこと

## 再現手順(Procedure)
概要の動画の通り

### 環境 (environment)
+ EC-CUBE: 4.2-beta2
+ Chrome 104.0.5112.79
+ Safari 15.4 (17613.1.17.1.13)

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
@ryo-endo 
ありがとうございます。
以下と同じ事象かと思いますので、クローズさせていただきますね。
https://github.com/EC-CUBE/ec-cube/issues/5520

**Comment by ryo-endo** [comment]
うおおおお。見逃してました。CLOSE了解です。お手数おかけしました。
