### ISSUE TITLE
ファイル管理：すでにあるフォルダと同じ名前のファイルをアップロードしたときのエラーメッセージが不正

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5561]
## 概要(Overview)
ファイル管理画面にて。
すでにあるフォルダと同じ名前のファイルをアップロードすると、サーバー内のパスが露出したエラーメッセージが表示されます。

<img width="500" alt="image" src="https://user-images.githubusercontent.com/16891862/185172342-c0c70057-e9a6-4efc-9c1d-2d705ab7ee0e.png">

## 期待する内容(Expect)  or 要望 (Requirement)
・すでに同じ名前が使われているのでアップロードできない旨のメッセージが表示される。
・サーバー内部のパスが含まれるエラーメッセージは表示されないこと。

## 再現手順(Procedure)
1. ファイル管理画面を開く
2. 「ddd」という名前のフォルダを作成する
3. 「ddd」という名前のファイルをアップロードする →指摘のエラーメッセージが表示される(NG)

### 環境 (environment)
EC-CUBE: 4.2-beta2
サーバー: OSLinux 013db5d450b4 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64
DBサーバー: SQLite version 3.34.1
WEBサーバー: Apache/2.4.54 (Debian)
PHP: 7.4.30
※公式のdocker環境

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
@ryo-endo 
ありがとうございます！事象確認しました。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5565 で修正
