### ISSUE TITLE
インストール時にsmtp情報の入力内容を確認していないため、実際にメールを送るシーンでシステムエラーになる

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5569]
## 概要(Overview)
インストール時にsmtp情報の入力を確認していないため、実際にメールを送るシーンでシステムエラーになる

## 期待する内容(Expect)  or 要望 (Requirement)
smtp情報の入力でその入力内容でメールが送信できるのかチェックする

## 再現手順(Procedure)
smtp情報の入力を初期状態のままで登録し、インストール後会員登録などするとシステムエラーになる

### 環境 (environment)
+ EC-CUBE: 4.2.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by xuelian311** [comment]
インストール時のメール設定の有効性確認はユーザビリティが低いと判断し、本件はクローズします。
