### ISSUE TITLE
Web公開ディレクトリ以下へインストールした場合に html を無くしたい

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#558]
Microsoft Azure など、 公開ディレクトリ以下へしかインストールできない場合もあるので、公式に何とかする方法を公表した方が良いと思います。
### 参考
- http://xoops.ec-cube.net/modules/newbb/viewtopic.php?forum=10&post_id=71959&topic_id=16212#forumpost71959
- http://gihyo.jp/design/serial/01/azure_eccube/0005

**Comment by seasoftjapan** [comment]
:+1:

とりあえず、インストーラー内での html/ 決め打ちは回避して欲しいです。html/*.php で __DIR__ を退避するなり、遣り様はあるのではないかと思います。

**Comment by nobuhiko** [comment]
:+1:

**Comment by chihiro-adachi** [comment]
未検証ですが、docroot(=eccube root)直下にindex.phpと.htaccessを配置で出来ませんか。

**Comment by nobuhiko** [comment]
@chihiro-adachi 
やってみましたが、
このウェブページにはリダイレクト ループが含まれています
ERR_TOO_MANY_REDIRECTS
となりました

**Comment by nobuhiko** [comment]
index.php を
$location = str_replace('index.php', 'html/install.php', $_SERVER['SCRIPT_NAME']);
に書き換えたらインストールは進みまして、完了しましたけど管理画面に移動する時に、 html/admin/というURLになりページがみつかりません
また、htmlをぬいて、adminにアクセスすると画面は表示されますがログインできませんしエラーメッセージも出ないですね
フロントも一見動いてますが、POSTとかはダメっぽいです

**Comment by k-yamamura** [comment]
ブログにも書きましたが、こちらの方法で実現可能です。


EC-CUBEをインストールしたディレクトリ先は
```
/home/hoge/EC-CUBEROOT
```
とします。


1.インストール  
```
http://ドメイン名/html/install.php
```
から普通にインストールを行ってください。

2.ファイルの配置場所変更  
 ```
/home/hoge/EC-CUBEROOT/html
```
にある以下の3つのファイル  
index.php  
.htaccess  
robot.txt  
を
```
/home/hoge/EC-CUBEROOT
```
直下へ移動させるかコピーしてください。

3.index.phpの書き換え  
```
require __DIR__ . '/../autoload.php';
```
と記述されている箇所を
```
require __DIR__ . '/autoload.php';
```
に変更します。

4.path.ymlの書き換え  
```
/home/hoge/EC-CUBEROOT/app/config/eccube/path.yml
```
にある
```
root_urlpath: /html
```
を
```
root_urlpath: 
```

に変更してください。


上記の設定を行う事で、
```
http://ドメイン名/
```
で接続できるようになります。


こちらの方法についてはスクリプトを作成して簡単に対応できるようにします。

**Comment by ryo-endo** [comment]
3.0.11では、 #1709 で、新規インストール時に限って無くす手順を公開しました。
http://ec-cube.github.io/remove_html

**Comment by Yangsin** [comment]
3.0.11の対応をもってクローズとします。
