### ISSUE TITLE
インストール画面の表示崩れ

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5581]
## 概要(Overview)
 [推奨] apc拡張モジュールが有効になっていません。
という表示の☓マークの位置が変

<img width="942" alt="ようこそ___EC-CUBEインストール" src="https://user-images.githubusercontent.com/604492/185723658-cf8a4fbe-488e-46e5-abda-2ddf9168b7e4.png">

## 期待する内容(Expect)  or 要望 (Requirement)
4.1と同様の表示

<img width="926" alt="ようこそ___EC-CUBEインストール" src="https://user-images.githubusercontent.com/604492/185723675-53cab06d-09f0-44b1-916f-e7ca5f0a09d5.png">

## 再現手順(Procedure)
インストール画面を表示させる

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5582 で修正
