### ISSUE TITLE
インストール画面のSVGアイコンが表示されていない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5583]
## 概要(Overview)
これが再発している
https://github.com/EC-CUBE/ec-cube/issues/2052

## 期待する内容(Expect)  or 要望 (Requirement)
表示される、か不要なら消す
4.1でも表示されていない

## 再現手順(Procedure)
インストール画面を表示

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5585 で対応
