### ISSUE TITLE
インストール画面のロゴが表示されていない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5584]
## 概要(Overview)
<img width="1362" alt="ようこそ___EC-CUBEインストール" src="https://user-images.githubusercontent.com/604492/185724619-d207d63e-bf9c-416c-befc-58fd18498b21.png">
左上にロゴがあるらしい

## 期待する内容(Expect)  or 要望 (Requirement)
ロゴが表示される、なお4.1も表示されていない

## 再現手順(Procedure)
インストール画面を表示する

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
#5583

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます。修正確認しました

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5585 で対応
