### ISSUE TITLE
インストール画面で[データベースの初期化を行わない]を選択するとシステムエラー

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5586]
## 概要(Overview)
<img width="1056" alt="Attempted_to_call_an_undefined_method_named__fetch__of_class__Doctrine_DBAL_Statement____500_Internal_Server_Error_" src="https://user-images.githubusercontent.com/604492/185725087-c4196906-be0a-4013-95d6-02df1e83f386.png">

## 期待する内容(Expect)  or 要望 (Requirement)
システムエラーにならない

## 再現手順(Procedure)
インストール画面のstep5でデータベースの初期化を行わないにチェックを入れる

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5587 で対応
