### ISSUE TITLE
3.0.1で発見した不具合

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#559]
プラグインの作成や、カスタマイズを行っていく上で発見した不具合を記載します。

■プラグインのアンインストール、有効化、無効化などでバインドのエラーが発生する。
対象関数： PluginController::update、PluginController::enable、PluginController::disable、PluginController::uninstall
原因： $app->redicret() 時の文字列が間違っている。
対処： 「admin_setting_store_plugin_index」から「admin_setting_store_plugin」へ変更したところうまくいきました。

■プラグインの code と name が異なる場合、アンインストール等でエラーとなる。
対象関数： PluginService::enable、PluginService::uninstall
原因： $pluginDir 変数に値をセットする際に $plugin->getName() を使用している。
対処： $plugin->getCode() を使用するようにしたところうまくいきました。

■受注管理のキーワードを入れて検索するとエラーが発生。
対象関数： OrderRepository::getQueryBuilderBySearchDataForAdmin
原因： $searchData 変数に存在しないキーを使用している。存在しない変数を使用している。
対処： multi の if 文内にて preg_match 関数の第二引数の三項演算子の正しい時の $searchData のキーが「multi」ではなく「mutli」となっている。
また、その下の setParameter の第二引数に「$id」ではなく「$multi」に変更。

**Comment by shinichi-takahashi** [comment]
@shhirose ご報告ありがとうございます。
こちらお手数ですが、ひとつひとつわけて掲載いただけますでしょうか？
PR対応時にCloseしづらいため、ご協力お願い致します。

**Comment by shhirose** [comment]
分けましたので、こちらは Close します。

**Comment by shinichi-takahashi** [comment]
@shhirose ご対応いただきありがとうございます。
手数をおかけいたしました。
