### ISSUE TITLE
Coupon Plugin for EC-CUBE42　管理画面でレイアウトが崩れている

### ISSUE THREAD

**Issue by C-Inada** [EC-CUBE/ec-cube#5595]
## 概要(Overview)
Coupon Plugin for EC-CUBE42　で 新規登録時のレイアウトが崩れている
![image](https://user-images.githubusercontent.com/107402966/186070255-931b5114-56ca-41c0-a6a4-d00efb399ce6.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 8.1.6
+ DB:MySQL 5.7.38

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/coupon-plugin/pull/155 で対応
