### ISSUE TITLE
会員登録しようとするとシステムエラーが発生する

### ISSUE THREAD

**Issue by kings10-hiroki** [EC-CUBE/ec-cube#5596]
## 概要(Overview)
![エラー画面](https://user-images.githubusercontent.com/59495696/186089279-be94a683-08e9-4315-a356-a19c48ed41da.png)

## 期待する内容(Expect)  or 要望 (Requirement)
会員登録が実施できる

## 再現手順(Procedure)
「新規会員登録」から会員登録する

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.4.19
+ DB:
  - MySQL 5.7.37

## 関連情報 (Ref)
.envファイルを下記に修正することでエラー解消される
MAILER_DSN=smtp://localhost:25?verify_peer=false

**Comment by nanasess** [comment]
以下の PR で解消予定です
https://github.com/EC-CUBE/ec-cube/pull/5578
