### ISSUE TITLE
公開日時のUIレイアウトが崩れている

### ISSUE THREAD

**Issue by kings10-hiroki** [EC-CUBE/ec-cube#5597]
## 概要(Overview)
コンテンツ管理>新着情報管理 の公開日時のレイアウトが崩れている

![エラー画面_2](https://user-images.githubusercontent.com/59495696/186090982-e4240033-0564-4b7c-acee-cdd166eb6221.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.4.19
+ DB:
  - MySQL MySQL 5.7.37

**Comment by nobuhiko** [comment]
@kings10-hiroki 4.1とさほどかわらないですが、何が崩れていますか？

**Comment by kings10-hiroki** [comment]
@nobuhiko 

添付が誤っておりました。
下記が該当の画像です。

##期待する内容
公開日時のプルダウンの列が縦ではなく横に並ぶ

EC-CUBE: 4.1
![エラー画面_5](https://user-images.githubusercontent.com/59495696/186109034-8bff4938-e5fd-4d08-81c3-91b484b9674a.png)

EC-CUBE: 4.2.0-beta
![エラー画面_6](https://user-images.githubusercontent.com/59495696/186109642-85a416f1-537f-4515-a4d4-ae5caaeaf532.png)

**Comment by chihiro-adachi** [comment]
@kings10-hiroki 
現時点では以下のように修正されているかと思います。
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/8196725/186335112-b6ad7778-fa03-4f72-b693-428586d344ec.png">

**Comment by chihiro-adachi** [comment]
パッケージは随時更新していますので、最新でご確認いただければと。
https://github.com/EC-CUBE/ec-cube/releases
