### ISSUE TITLE
プラグイン一覧画面でプラグイン名の左に「_」アンダースコアが付与されている

### ISSUE THREAD

**Issue by kings10-hiroki** [EC-CUBE/ec-cube#5598]
## 概要(Overview)
![エラー画面_3](https://user-images.githubusercontent.com/59495696/186091533-f381b4bb-af2f-449d-a4d9-e3e5088f9e28.png)

## 期待する内容(Expect)  or 要望 (Requirement)
プラグイン名の左に「_」アンダースコアが表示されない

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.4.19
+ DB:
  - MySQL MySQL 5.7.37

**Comment by nobuhiko** [comment]
mac chromeで見る限りはアンダースコアは表示されていない
ブラウザ依存？？

**Comment by kings10-hiroki** [comment]
環境はwindows chromeになります。

**Comment by maianhtu010596** [comment]
@nobuhiko 

これを Eccube 4.1.2 beta2 でテストしましたが、リンクにカーソルを合わせるとエラーが表示されるようです。
環境はwindows chromeになります。
![image](https://user-images.githubusercontent.com/105194449/186125844-0f09bee5-8be7-4f34-872e-ec98b1d87875.png)
