### ISSUE TITLE
プラグインのアンインストール、有効化、無効化などでバインドのエラーが発生する。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#560]
対象関数： PluginController::update、PluginController::enable、PluginController::disable、PluginController::uninstall
原因： $app->redicret() 時の文字列が間違っている。
対処： 「admin_setting_store_plugin_index」から「admin_setting_store_plugin」へ変更したところうまくいきました。

**Comment by aminotsukasa** [comment]
連絡ありがとうございます。こちら現在対応中です。

**Comment by aminotsukasa** [comment]
#564
にて対応しました
