### ISSUE TITLE
商品登録画面で縦サイズが600以下の画像を登録するとレイアウトが崩れる

### ISSUE THREAD

**Issue by kings10-hiroki** [EC-CUBE/ec-cube#5602]
## 概要(Overview)
縦サイズが600px以下の画像を登録して、画像の位置を移動すると
商品説明の箇所に画像がはみ出してしまう
![エラー画面_7](https://user-images.githubusercontent.com/59495696/186111129-69b7c0bb-4999-434b-a69b-378e7a7284b1.png)

## 期待する内容(Expect)  or 要望 (Requirement)
商品説明の箇所に画像がはみ出ない

## 再現手順(Procedure)
縦サイズが600px以下の画像と600px以上の画像を登録する
縦サイズが600px以下の画像を最左から右に移動させる

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 7.4.19
+ DB:
  - MySQL MySQL 5.7.37

**Comment by chihiro-adachi** [comment]
ありがとうございます。事象確認しました

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5626 で修正
