### ISSUE TITLE
クーポンプラグイン　ラジオボタンの位置がおかしい

### ISSUE THREAD

**Issue by C-Inada** [EC-CUBE/ec-cube#5605]
## 概要(Overview)
クーポンプラグイン　ラジオボタンの位置がおかしい
![image](https://user-images.githubusercontent.com/107402966/186173294-5226ba84-37e5-4bdb-8bb4-be2d2ee0abef.png)

## 期待する内容(Expect)  or 要望 (Requirement)
位置を揃える

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 8.1.6

**Comment by nobuhiko** [comment]
[#1680](https://github.com/EC-CUBE/coupon-plugin/pull/160) にて修正ずみ

**Comment by chihiro-adachi** [comment]
以下で報告・修正済のため、クローズさせていただきます。
https://github.com/EC-CUBE/coupon-plugin/pull/159
https://github.com/EC-CUBE/coupon-plugin/pull/160
