### ISSUE TITLE
［4.2］Site Kit プラグイン　設定の最後でエラーになる

### ISSUE THREAD

**Issue by C-Inada** [EC-CUBE/ec-cube#5606]
## 概要(Overview)
Site Kit プラグインのGoogle連携の設定の最後でエラーになる。

**Warning: Undefined array key "rows"**
HTTP 500 Internal Server Error

![image](https://user-images.githubusercontent.com/107402966/186188909-cb1b1d48-7e7c-4e33-95ad-d3828afe55e9.png)

## 再現手順(Procedure)
プラグイン一覧から有効にしたあと、管理画面から連携作業をすすめると
「Search Console で設定されました。これで完了です。」のあとに「ダッシュボードへ移動」で上記エラーが出る。
このあと管理画面からSite Kit の設定などに移動しても同じエラーが出る。

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 8.1.6
+ DB:MySQL 5.7.38

**Comment by nobuhiko** [comment]
これかな？
https://github.com/EC-CUBE/sitekit-plugin/pull/13

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/sitekit-plugin/pull/13 で対応済
