### ISSUE TITLE
プラグインの code と name が異なる場合、アンインストール等でエラーとなる。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#561]
対象関数： PluginService::enable、PluginService::uninstall
原因： $pluginDir 変数に値をセットする際に $plugin->getName() を使用している。
対処： $plugin->getCode() を使用するようにしたところうまくいきました。

**Comment by aminotsukasa** [comment]
連絡ありがとうございます。こちら現在対応中です。

**Comment by aminotsukasa** [comment]
#564
にて対応しました
