### ISSUE TITLE
［4.2］クーポンプラグイン　一覧の枚数が更新されない。使えてしまう。

### ISSUE THREAD

**Issue by C-Inada** [EC-CUBE/ec-cube#5617]
## 概要(Overview)
Coupon Plugin for EC-CUBE42 でクーポンを作り、編集から枚数を更新すると、はじめに登録された枚数が有効になったままで使えてしまう。
表示も変更されない。

▼999,999枚で新規作成し、編集から1枚に変更したのに一覧では変わっていない
発行枚数1枚に変更、更新後に別の人が２回使用できている。
![image](https://user-images.githubusercontent.com/107402966/186357286-ec8f6df0-4f5d-47e3-9c7c-3af5a7df84aa.png)

▼こちらでは発行枚数が1枚のまま
![image](https://user-images.githubusercontent.com/107402966/186357900-eced150a-d913-4451-afa6-89e946ad9abd.png)
## 再現手順(Procedure)
変更したら反映されるようにしたい。
枚数変更ができないのであればエラーを出すようにする。

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta
+ PHP: 8.1.6
+ DB:  -MySQL 5.7.38

Coupon Plugin for EC-CUBE42  Var. 4.2.2

**Comment by chihiro-adachi** [comment]
@C-Inada 
こちら再現しませんでした。
最新のパッケージでも事象発生するかご確認いただけますでしょうか？

**Comment by ryo-endo** [comment]
追試成功しました。
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/16891862/187033275-43534b26-5c81-4a37-8f17-1cededc169ab.png">

## 再現手順
一度、保存時エラーを発生させるのが発生条件でした。

1. 発行枚数 999,999 枚のクーポンを作成する。(パラメータなどは適当で良い)
2. 上記クーポンの編集画面に入り、発行枚数を1枚にしたあと、**意図的に保存時エラー**を発生させる。(例えば割引率を300%にするなど)
3. 手順(2)のエラーを修正して正常保存する。
4. リストを確認する　→ 999,999/1枚になっている (NG)

## 原因っぽいコード
変更前の値を `$request->get('coupon_release_old')` から変更前の発行枚数を取得しようとしているが、一度エラーになった場合はここに変更前の値ではなく変更後の値が入ってくる。
その結果 `if ($Coupon->getCouponRelease() != $oldReleaseNumber) {` が同値なのでFalseとなって、`$Coupon->setCouponUseTime` が実行されないため、999,999が残り続ける。


https://github.com/EC-CUBE/coupon-plugin/blob/6b717c8fc76e390857d63167e961d500975763e3/Controller/Admin/CouponController.php#L130-L137

**Comment by chihiro-adachi** [comment]
クーポンプラグインのレポジトリにIssueを移動しました。
こちらはクローズします。
