### ISSUE TITLE
[4.2] 空白のパスワードで管理者アカウントを登録してもエラーが表示されない

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5627]
## 概要(Overview)
管理者アカウントのサインアップ時にパスワードを空白のままにするとエラーが発生しました

## 再現手順(Procedure)
Step 1. 設定 → システム設定 → メンバー管理 → 新規登録
![image](https://user-images.githubusercontent.com/105194449/186567516-f7965a3c-3f6c-4032-abe0-23ae56f33799.png)
Step 2. [会員登録]ページが表示されます
![image](https://user-images.githubusercontent.com/105194449/186567531-bff1087b-0e3e-4f66-928a-b8295e9aea7c.png)
Step 3: パスワード欄は空欄のまま登録ボタンを押してください
![image](https://user-images.githubusercontent.com/105194449/186567549-562370fb-bca0-45c8-97fd-0784d397480b.png)
Step 4. エラーメッセージは表示されません
![image](https://user-images.githubusercontent.com/105194449/186567570-3ef94846-f4fb-44ea-8ffe-e48caf34a6ed.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x 
+ DB:
  - PostgreSQL 10.x.x 
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/5420

モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220824）

**Comment by maianhtu010596** [comment]
@chihiro-adachi 

この問題の原因を調査したところ、別の関連する問題が見つかりました。
パスワード入力フィールドのプレースホルダーが表示されないエラー。

ファイル内のコードを変更すると、本当の問題は解決しました
ec-cube/src/Eccube/Form/Type/Admin/MemberType.php

コードから
`->add('plain_password', RepeatedPasswordType::class, [
                'first_options' => [
                    'label' => 'admin.setting.system.member.password',
                ],
                'second_options' => [
                    'label' => 'admin.setting.system.member.password',
                ],
            ])`
コードに
`->add('plain_password', RepeatedPasswordType::class)`

原因は次のように特定されます。
- (MemberType) の first_options と second_options は、(RepeatedPasswordType) の first_options と second_options を直接上書きしました


**-実装前後の結果。**
**4.1.x の場合**

問題を解決する前に:
![image](https://user-images.githubusercontent.com/105194449/186869359-09b7d8d3-44b7-4877-aa88-d4ec156ffd19.png)
問題を修正した後:
![image](https://user-images.githubusercontent.com/105194449/186869762-4b3c7a29-52fd-40f9-abbb-38901da3aa3f.png)

**4.2.x の場合**
問題を解決する前に:
![image](https://user-images.githubusercontent.com/105194449/186870309-02fe2322-3ac8-442e-a84f-10acc955994e.png)

問題を修正した後:
![image](https://user-images.githubusercontent.com/105194449/186870694-25fd9a1c-c483-44f2-8924-2eb992afcd87.png)

同じケースは次の場合にも発生します。
- 新規会員登録
ec-cube\src\Eccube\Form\Type\Admin\CustomerType.php

この問題を確認して確認してください。ありがとうございました。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5643
