### ISSUE TITLE
お問い合わせ完了画面で英語のタイポ

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5632]
## 概要(Overview)
inquiryのスペリングが違う

## 期待する内容(Expect)  or 要望 (Requirement)
inquiryにする

## 再現手順(Procedure)
言語を英語として、お問い合わせ完了画面を表示します
![image](https://user-images.githubusercontent.com/8424850/186675338-ca28ed77-dee9-4191-b874-f1942a68f164.png)

### 環境 (environment)
+ EC-CUBE: 4.2.β
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5633 で対応
