### ISSUE TITLE
マスタデータ管理画面で「？」にマウスオーバーしてもツールチップが表示されない

### ISSUE THREAD

**Issue by sf-habu** [EC-CUBE/ec-cube#5635]
## 概要(Overview)

「マスタデータ管理」画面の「マスタデータ管理」の右側の「？」アイコンの上にマウスカーソルをあてても、ツールチップが表示されない。
（「マスタデータ管理」の文字の上にマウスオーバーすると、ツールチップが表示される）

## 期待する内容(Expect)  or 要望 (Requirement)

「マスタデータ管理」の右側の「？」アイコンにマウスオーバーした際にツールチップが表示されるべき。

## 再現手順(Procedure)

EC-CUBE管理画面 左メニューの「設定」→「システム設定」→「マスタデータ管理」画面を開き、
「マスタデータ管理」の右側の「？」アイコンの上にマウスカーソルをあてる。

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 8.0.20
+ DB:
  - PostgreSQL 12.12

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5636 で修正
