### ISSUE TITLE
インストール画面で未入力で登録を押してもエラーメッセージが表示されない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5640]
## 概要(Overview)
htmlのrequiredのメッセージなどが表示されない

## 期待する内容(Expect)  or 要望 (Requirement)
メッセージなどが表示される
もしくはhtmlのメッセージでバリデートしない

## 再現手順(Procedure)
未入力で登録を押す

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/issues/5656 と内容は同じかとおもいますので、こちらはクローズさせていただきます。
