### ISSUE TITLE
インストール画面にエラーアイコンが表示されていない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5641]
## 概要(Overview)

<img width="907" alt="ようこそ___EC-CUBEインストール" src="https://user-images.githubusercontent.com/604492/186873292-c6e35124-b89a-4d2f-9153-2e4fdd4a45d1.png">

## 期待する内容(Expect)  or 要望 (Requirement)
<img width="866" alt="ようこそ___EC-CUBEインストール" src="https://user-images.githubusercontent.com/604492/186873776-74ddb881-38b5-4524-b85f-2581fce19fb1.png">

## 再現手順(Procedure)
インストール画面でエラーを出す

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5642 で対応
