### ISSUE TITLE
APP_ENV=dev でログをダウンロードするとシステムエラー

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5658]
## 概要(Overview)
システム設定ログ表示のダウンロードボタンを押すと500エラーになる

Warning: filesize(): stat failed for /ec-cube42/var/log/dev/site_2022-08-27.log

## 期待する内容(Expect)  or 要望 (Requirement)
エラーにならない

## 再現手順(Procedure)
システム設定 > ログ表示のダウンロードボタンを押す

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@nobuhiko 
手元の環境では再現しませんでした。
設定等、再現条件わかるようでしたられば記載おねがいします。

**Comment by nobuhiko** [comment]
@chihiro-adachi 
<img width="936" alt="システム設定_ログ表示_-_テスト店舗" src="https://user-images.githubusercontent.com/604492/187107950-d3596316-7dbb-4f53-bb7e-9e20ff039ea7.png">
こうでした

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます。再現しました。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5733
