### ISSUE TITLE
商品詳細のサムネイルが崩れる

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#5659]
## 概要(Overview)
2カラムにした場合にサムネイルが崩れる
<img width="1186" alt="テスト店舗___彩のジェラートCUBE" src="https://user-images.githubusercontent.com/604492/187021079-61327191-0072-4f38-af14-b446fc0711dc.png">

## 期待する内容(Expect)  or 要望 (Requirement)
画像のアスペクト比を維持する

## 再現手順(Procedure)
下層にブロックを設置し、2カラム以上にして商品詳細を見る

### 環境 (environment)
+ EC-CUBE: 4.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5662
