### ISSUE TITLE
Cookie が設定できない？

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#566]
3.0.1 では Cookie の設定ができないようにも思えるのですが、対応しているのでしょうか。
対応しているようであればどのように記載すれば良いかご教授いただけますでしょうか。
もし対応していないようであれば、どのような対応を検討されているのでしょうか。

通常のページ、ブロック、プラグイン（eccube.event.controller.xxx.after など）それぞれあるとありがたく思います。

**Comment by shinichi-takahashi** [comment]
@shhirose 

Requestオブジェクトを持っている箇所(Controllerなど)では、
`$request->cookies->set('key', $val)`
`$cookie = $request->cookies->get('key')`
などの方法で取得・設定できます。

`$app` をもっているところでは、 `$pp['request']->cookies->set()` で設定できます。

setする場合は、Responseが返却されたタイミングでブラウザに送信されるので、扱いに注意が必要です。

**Comment by shhirose** [comment]
やはりうまくできませんでした。（github から 現在の master を clone して試しました。）
以下に試した方法を記載します。

TopController.php
class TopController
{
    public function index(Application $app)
    {
        $value = 'no-cookie';
        if ($app['request']->cookies->has('aaa')) {
            $value = $app['request']->cookies->get('aaa');
        } else {
            $app['request']->cookies->set('aaa', 'find cookie');
        }
        return $app['view']->render('index.twig', array('cookie_value' => $value));
    }
}


index.twig
～ 省略 ～
{% block main %}
    <p>Cookie Value: [{{ cookie_value }}]</p>
    <div class="row">
       <div class="col-sm-12">
            <div class="main_visual">
                <div class="item">
                  <img src="{{ app.config.front_urlpath }}/img/top/mv01.jpg">
                </div>
                <div class="item">
                  <img src="{{ app.config.front_urlpath }}/img/top/mv02.jpg">
                </div>
                <div class="item">
                  <img src="{{ app.config.front_urlpath }}/img/top/mv03.jpg">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

以上の処理でトップページを表示し、1回目および2回目ともに「no-cookie」と表示されてしまします。
認識違いや間違いがあればご指摘いただけますでしょうか。

**Comment by aminotsukasa** [comment]
@shhirose 
こちらでもやってみたら、
$app['request']->cookies->set('aaa', 'find cookie');
だとレスポンスに出力されませんね

Symfonyの標準的な方法
$response = new Symfony\Component\HttpFoundation\Response();
$response->headers->setCookie(new Symfony\Component\HttpFoundation\Cookie('key','val'));
$app->render('xxx.twig',array(),$response)
なら設定できました。
getするときより長くなるのが難点ではありますが…

プラグインの場合もFilterResponseEvent からResponseが取得できれば同様の方法で設定可能だと思います。

**Comment by shhirose** [comment]
@aminotsukasa 
プラグインで FilterResponseEvent を使用して試したところ、うまくいきました。
<pre>
public function renderBefore(
        \Symfony\Component\HttpKernel\Event\FilterResponseEvent $event)
{
    $cookie = new \Symfony\Component\HttpFoundation\Cookie('cookie_value', 'find cookie');
    $response = $event->getResponse();
    $response->headers->setCookie($cookie);
    $event->setResponse($response);
}
</pre>


> getするときより長くなるのが難点ではありますが…

get と set で対応方法がだいぶ違うので開発する上では大変な気がします。
改善できる余地があるのであればこの isssue は残しますが、なければ Close しようと思いますが、いかがでしょうか。

**Comment by Yangsin** [comment]
まずは仕様として本Issueは、Closeでよいかと思います。
今後改善できる余地があるなら別途Issueを起こしていただけますと幸いです。
