### ISSUE TITLE
仮会員メールを再送する場合には認証URLを再生成する提案

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5667]
*セキュリティ向上の提案です。EC-CUBE運営チームからIssue起案で問題ない旨をご連絡いただきました。*

## 概要(Overview)
- いまの仕様では、管理画面から仮会員メールを再送した場合に、**毎回同じURL**を送信しています。
- 送信されるごとに、前回のURLは無効になって新しいURLが発行される方が、システムとしてよりセキュアだと考えています。

## 期待する内容(Expect)  or 要望 (Requirement)
- 再送するたびに認証URLを再生成する。

## 再現手順(Procedure)
1. 会員登録をして、仮会員メールを受信する。
2. 管理画面から仮会員メールを再送する。
3. 仮会員メールを再度受信する。→URLが同じことを確認

### 環境 (environment)
+ EC-CUBE: 4.2-beta2

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5835 で対応
