### ISSUE TITLE
出荷CSV登録で「お問い合わせ番号」に利用できない文字が登録できる

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5668]
## 概要(Overview)
出荷CSV登録では「お問い合わせ番号」に利用できない文字が登録できてしまいます。
<img width="308" alt="image" src="https://user-images.githubusercontent.com/16891862/187023596-b45cf703-5527-4330-a8d8-add4ae143533.png">

画面から「お問い合わせ番号」に登録できる文字は「半角英数字かハイフン」です。
<img width="714" alt="image" src="https://user-images.githubusercontent.com/16891862/187023504-8daed9ae-4c25-421a-87d2-13b6d4efd17a.png">

## 期待する内容(Expect)  or 要望 (Requirement)
出荷CSV登録でも、画面と同じ入力制限がかかっていること。

## 再現手順(Procedure)
1. 出荷CSVファイルを作成し、このとき「お問い合わせ番号」に「半角英数字かハイフン」**以外**を入力する。
2. 出荷CSV登録ページから、出荷CSVファイルを登録する。
3. 受注情報を確認すると、手順(1)で入力した文字列が「お問い合わせ番号」に登録されている(NG)

### 環境 (environment)
+ EC-CUBE: 4.2-beta2

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5671

**Comment by ryo-endo** [comment]
うぉー。PRまでは検索してなかった。失礼しました。

**Comment by ryo-endo** [comment]
違う。速攻でPRが作られたのか。早い。
