### ISSUE TITLE
メールテンプレート編集画面でブラウザバックをすると、テンプレート名と本文が食い違った表示になる

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube#5670]
## 概要(Overview)
メールのテンプレート編集画面でブラウザの「戻る」を行うと、以下再現手順の画像の通り「テンプレート名」と「件名/本文」が食い違った表示になります。

### 同様の不具合が発生するページ
- CSV出力項目設定

## 期待する内容(Expect)  or 要望 (Requirement)
「テンプレート名」と「件名/本文」が常に一致していること。

## 再現手順(Procedure)
1. メールのテンプレート編集画面を開く。
2. 「受注受付メール」を選択する。
3. 「会員仮登録メール」を選択する。
4. ブラウザの「戻る」を押す
→ テンプレート名は「会員仮登録メール」ですが件名/本文は「受注受付メール」が表示されている（NG）

※ 補足：この状態で保存すると「受注受付メール」の内容が更新される
<img width="630" alt="image" src="https://user-images.githubusercontent.com/16891862/187024553-88901575-5a59-47b9-8614-834d4df51e38.png">

### 環境 (environment)
+ EC-CUBE: 4.2-beta2
+ Chrome バージョン: 104.0.5112.79（Official Build） （arm64）

## 関連情報 (Ref)
なし

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5700
