### ISSUE TITLE
[4.2] 製品規格は製品に関連付けられているため削除できません

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5698]
## 概要(Overview)
製品規格は製品に関連付けられているため削除できません
## 再現手順(Procedure)
Step 1. 創建新規範
![image](https://user-images.githubusercontent.com/105194449/187343932-24b17262-2e37-42c9-afd0-bb8b433614cc.png)

Step 2. 創建新的分類規範
![image](https://user-images.githubusercontent.com/105194449/187343960-eb8c95a9-92c5-4562-8c8f-d2fa57332d45.png)

Step 3. 商品管理->商品登録
![image](https://user-images.githubusercontent.com/105194449/187343985-e9f79205-81ec-46f6-bcbd-188aca2fcf42.png)

Step 4. 新しい製品を作成し、購読ボタンを押してください
![image](https://user-images.githubusercontent.com/105194449/187344000-c472f36a-0c00-49ff-8fec-7c933fe0431d.png)

Step 5. 製品に新しい基準を追加
![image](https://user-images.githubusercontent.com/105194449/187344011-98fea242-2c7c-4b59-98fa-6d6bc023dc59.png)

Step 6. 製品の規格を選択し、購読ボタンを押してください
![image](https://user-images.githubusercontent.com/105194449/187344025-168045a3-36ee-46ff-927c-8fd91fedc764.png)

Step 7. 成功製品の新規格登録のお知らせ
![image](https://user-images.githubusercontent.com/105194449/187344045-35ffb155-9efa-4fb7-be04-0dce058ab04a.png)

Step 8. [商品規格の初期化]ボタンを押して[規格を初期化]を選択
![image](https://user-images.githubusercontent.com/105194449/187344057-7934c68d-3755-4d1b-bf36-36a997331832.png)

![image](https://user-images.githubusercontent.com/105194449/187344076-ca39a6a0-5dbe-4899-bde1-d3925984f67e.png)

Step 9. 商品管理 -> 規格管理
![image](https://user-images.githubusercontent.com/105194449/187344092-07c36016-627d-4a40-a4f9-b30811c0f0ec.png)

Step 10. 刪除我們剛剛在步驟 7 中從產品中刪除的標準
![image](https://user-images.githubusercontent.com/105194449/187344106-c6c11ae4-2868-4522-bb16-eb19cedac051.png)

Step 11. 製品に関連付けられているため、標準を削除できません。これは、手順 8 で標準の削除を実行したときにジャンク データが隠されているためです。
![image](https://user-images.githubusercontent.com/105194449/187344127-561b3dd1-3d86-437d-a155-108b935ae5e1.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220829）

**Comment by longtq0711** [comment]
すみません、製品規格を直接削除して、製品のそれらの製品規格を null に設定したいのですが、どうすればよいですか?

**Comment by chihiro-adachi** [comment]
関連：https://github.com/EC-CUBE/ec-cube/issues/5766
