### ISSUE TITLE
[4.2] インストーラのDBのプルダウンの表示くずれ

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5701]
## 概要(Overview)

<img width="773" alt="image" src="https://user-images.githubusercontent.com/8196725/187379905-677a709c-f3c8-4f08-8835-7c6204d12039.png">

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5639/commits/c2d655bf889628d93e023bfae38d13473f6605cc
これで直ってるのかな？

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます、確認してみます！

**Comment by chihiro-adachi** [comment]
#5639
