### ISSUE TITLE
商品登録画面の商品画像アップロードのファイル容量の記載について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5706]
## 概要(Overview)
PNGファイルアップロード時、ほとんどは２MBを超えている画像に対して「Error during upload」になりますが、
9MB超えているファイルでもErrorにならず「Upload Complete」になる場合があります。

ただし[登録]ボタン押下した場合に、「SizError during load」のエラーになりますが、
項目下に表示されるエラーメッセージが「 画像のパスが不正です。」が表示され、
エラー内容と表示内容が合っておりませんでした。

## 期待する内容(Expect)  or 要望 (Requirement)
下記などの対応を行った方がユーザにわかりやすいのではないかと思いました
・画面に「最大画像容量：{容量}MB以内」などの注意事項を表示
・容量でエラーの場合、「{容量}MB以内の画像をアップロードしてください」などのメッセージを表示

## 再現手順(Procedure)
1. 商品登録画面を開く
2. 画像をアップロードする

![画像サイズチェック](https://user-images.githubusercontent.com/13821027/187578316-85392910-32e4-4033-8a37-37c6badc82cb.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
おそらく、 `post_max_size` と `upload_max_filesize` の設定に起因しているものと思われます。
#5763 で10MBまでアップロードできるよう修正してみました

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5763で対応
