### ISSUE TITLE
商品登録画面の商品画像アップロードの拡張子の記載について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5707]
## 概要(Overview)
拡張子についての制限ですが、画像以外(PNG、JPEG、GIF）以外の画像をアップした場合「Files of invalid type」のエラーになります。
文字が小さいのと色が薄いためわかりずらいように思います。

## 期待する内容(Expect)  or 要望 (Requirement)
・画面に「PNG、JPEG、GIFの拡張子のファイルのみ」などの注意事項を表示
・拡張子ででエラーの場合、「「PNG、JPEG、GIF」の拡張子の画像をアップロードしてください」などのメッセージを表示

## 再現手順(Procedure)
1. 商品登録画面を開く
2. 画像をアップロードする

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5882 で対応
