### ISSUE TITLE
商品登録画面の販売種別について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5708]
## 概要(Overview)
デベロッパーツールのElementsより、「販売種別」のvalueの値をを19桁以上、数値以外、選択肢以外、絵文字などに変更し登録しようとした場合、商品登録画面にリダイレクトされ、販売種別の項目が赤枠にはなりますがエラーメッセージが表示されませんでした

## 期待する内容(Expect)  or 要望 (Requirement)
エラーメッセージが表示された方がよいと思いました

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
4.2 最新版ではエラーメッセージが表示されました

**Comment by chihiro-adachi** [comment]
4.2のHEADでは以下のようになりました。
`form_errors `の記述漏れかと思います。

<img width="928" alt="image" src="https://user-images.githubusercontent.com/8196725/187874352-eb5f4182-048d-40ae-8d83-96feb47ebd86.png">

**Comment by dotani1111** [comment]
merge済み
