### ISSUE TITLE
商品登録画面のフリーエリアについて

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5709]
## 概要(Overview)
・「フリーエリア」ですが、maxlengthの指定がなく、入力制限がありませんでした。
　文字数が多いすぎる場合、システムエラーになりました。

その他
・「フリーエリア」はjavascriptのコードが有効になっておりますが、問題ありませんでしょうか。
・「フリーエリア」は<input>: 入力欄 (フォーム入力) 要素が有効になっておりますが、問題ありませんでしょうか。

## 期待する内容(Expect)  or 要望 (Requirement)
システムエラーにならず、エラーメッセージが表示された方がよいと思いました。

## 再現手順(Procedure)
1. 商品登録画面のフリーエリアに文字を入力

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
4.2 最新版で20万文字いれてみましたが、mysqlではシステムエラーにはなりませんでした。
ですが、フロントの商品一覧画面が Allowed memory size of  エラーになりました

**Comment by chihiro-adachi** [comment]
あまりにも大きい文字列だと機能的に動作しなくなるので、妥当な範囲で上限チェックをいれられればと思います。

**Comment by nanasess** [comment]
65535文字くらいが妥当でしょうか。

**Comment by xuelian311** [comment]
@nanasess ありがとうございます！根拠について少しだけ補足お願いできますか？

**Comment by nanasess** [comment]
@xuelian311 特に根拠は無いのですが、符号無し2バイト整数値の上限にしてみました。

**Comment by chihiro-adachi** [comment]
@xuelian311 
精査はしてないですが、定数`eccube_lltext_len`(99999文字)あたり使えばよいかかな？と当時は思ってました。
https://github.com/EC-CUBE/ec-cube/blob/4.2/app/config/eccube/packages/eccube.yaml#LL63C5-L63C22

**Comment by dotani1111** [comment]
修正済みなのでCloseします。
