### ISSUE TITLE
商品登録画面の必須マークについて

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5710]
## 概要(Overview)
商品登録、商品編集画面で項目名右横に表示される「必須」の文言が白文字で表示されているため見えない状態です。

## 期待する内容(Expect)  or 要望 (Requirement)
必須の文言が見えた方がよいと思いました。

## 再現手順(Procedure)
1. 商品登録画面を開く
![image](https://user-images.githubusercontent.com/13821027/187577554-00e59f70-46f9-4456-9314-106a024cb9c0.png)

![image](https://user-images.githubusercontent.com/13821027/187577518-fc05bdbe-2fa1-4dea-b6f6-44cc1a73abe3.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
4.2 最新では修正済み

**Comment by chihiro-adachi** [comment]
修正済のためクローズします。
