### ISSUE TITLE
商品登録画面の関連商品について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5711]
## 概要(Overview)
関連商品の入力についてですが、関連商品で商品を選択しないで、説明文のみ入力し登録した場合エラーにならずに保存されます。
この時、商品登録画面がリダイレクトされますが、入力した説明文がクリアされ表示されております。

## 期待する内容(Expect)  or 要望 (Requirement)
商品を選択し忘れて、説明文のみ入力して登録してしまった場合は「関連商品が選択されていません」などのエラーメッセージを表示した方が使い勝手が良いのではないでしょうか。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
プラグインのIssueのため、以下に移動させていただきました。
https://github.com/EC-CUBE/related-product-plugin/issues/88
