### ISSUE TITLE
[4.2] 注文時に会員ポイントの使用をオフにしても、購入を完了することができます

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5713]
## 概要(Overview)
注文時に会員ポイントの使用をオフにしても、購入を完了することができます

## 再現手順(Procedure)
Step 1. 注文を作成し、注文にポイントを使用する\
![image](https://user-images.githubusercontent.com/105194449/187579363-608fcf3b-d6c4-4496-818e-3cd91246039e.png)

Step 2. 管理者ページでポイントの使用をオフにします
![image](https://user-images.githubusercontent.com/105194449/187579376-97ea8445-006d-421c-923e-c3fdd5eed90c.png)

Step 3. 注文画面に戻り、続行をクリックしてカートを完了します
![image](https://user-images.githubusercontent.com/105194449/187579394-fa0618c9-e1fe-499a-869f-89e4e684903e.png)

Step 4. 会員のポイント利用機能がオフになったという通知がない
![image](https://user-images.githubusercontent.com/105194449/187579416-d0a3aa74-d9a2-4f82-b667-4a96119a7a7e.png)

Step 5. 注文完了画面が表示される
![image](https://user-images.githubusercontent.com/105194449/187579428-8f8e9487-23e8-40f6-a11c-fa01d207f147.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220829）

**Comment by xuelian311** [comment]
こちらは、実運用としては購入者にとって優しくないパターンになりますので、バグではなく仕様として判断し、クローズします。
