### ISSUE TITLE
フロント/画面：商品一覧　商品規格分類にjavascriptやinputを入力した場合の挙動

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5717]
## 概要(Overview)
商品一覧画面で下記ようなの商品規格分類をプルダウンメニューより選択し、[カートに入れる]ボタンを押下すると、javascriptやinput要素が有効の状態で表示されます。

```
例）
<input type="text" value="">
<script>alert('Test!!!');</script><br>
<p><input type="button" class="chk1" value="アラート" onclick="alert('これはテストです')"></p>
```

## 期待する内容(Expect)  or 要望 (Requirement)
javascriptやinputはエスケープされた方がよいと思いました

## 再現手順(Procedure)
1. 商品規格分類にjavascriptやinput要素を入力
2. 商品規格分類をプルダウンメニューより選択し、[カートに入れる]ボタンを押下

![4 1 商品一覧](https://user-images.githubusercontent.com/13821027/187580456-ae3d9fef-d98c-4cda-94a6-7d738e0b7722.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
4.2 最新版では再現しませんでした

**Comment by chihiro-adachi** [comment]
未再現ということでクローズします。
