### ISSUE TITLE
新規会員登録　メールアドレスに254文字のアドレスを入力して登録したところ、システムエラーを示す画面に遷移した。

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5720]
## 概要(Overview)
新規会員登録でメールアドレスに254文字のアドレス(abcdefghij123456789@abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij.com])を入力して登録したところ、システムエラーを示す画面に遷移した。

## 期待する内容(Expect)  or 要望 (Requirement)
エラーメッセージが表示された方がよいと思いました

## 再現手順(Procedure)
新規会員登録でメールアドレスに254文字のアドレスを入力

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
@tiger-nakaya 
システムエラーのログ及び、利用しているDBのバージョンなども記載いただけると大変助かります。

**Comment by C-Inada** [comment]
有効なメールアドレスを取得時、通常は30文字前後に設定されてることが多いので254文字のメールアドレス自体を取得ができないことがほとんどです。
様々なサービスのメールアドレスの入力欄の文字数は32-64文字程度に制限をかけているところが多いようです。

**Comment by nobuhiko** [comment]
4.2最新版、mysqlではエラーになりませんでした。
varchar(255)に収まってるらしい

**Comment by nobuhiko** [comment]
一応仕様的には最大254文字までOKらしい
https://qiita.com/yoshitake_1201/items/40268332cd23f67c504c

**Comment by nobuhiko** [comment]
ちなみに256文字入れてもエラーにならず、255字で登録される
mysql

**Comment by chihiro-adachi** [comment]
pgsql10でも再現せずでした。

**Comment by chihiro-adachi** [comment]
未再現ということでクローズさせていただきます。
