### ISSUE TITLE
電話番号のバリデーションチェック

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5721]
## 概要(Overview)
電話番号が14文字以内の数字が入力OKとなっていますが問題ないでしょうか。
「87911112222」「97911112222123」のような番号が登録できますが問題ないでしょうか。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
現状では最大長のチェックのみ行っています。
特に大きな問題は発生していないかと思います。要望等多ければ今後改善できればと。
