### ISSUE TITLE
メールアドレスのバリデーションチェック

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5722]
## 概要(Overview)
メールアドレスに以下のアドレスが登録可能だが問題ないでしょうか。
aabcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcd@aaa.com（ローカル部が65文字）

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
デフォルトだとrfcでのチェックは行われないため、このメールアドレスは通るかと思います。
eccube_rfc_email_checkパラメータをtrueで実行すると、エラーとなりました。

**Comment by chihiro-adachi** [comment]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/8196725/188372170-36ea0144-28a1-42cc-88c2-3d8a4aafc25a.png">
