### ISSUE TITLE
フロント　ご注文手続き画面の登録された発送日目安とお届け日指定の関係性について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5724]
## 概要(Overview)
下記の状態になっていましたが問題ございませんでしょうか。

　1)商品登録で発送日目安を「即日」に設定した場合、お届け日に当日の午前が指定できる。
 　　例）8/19 13:00に注文するのに、お届け日指定に8/19午前、8/19午後が指定できる。
　2)商品登録で発送日目安を「1~2日後」に設定した場合、お届け日に翌日の午前が指定できる。
　　例）8/19 14:00に8/20午前が指定できる。

## 再現手順(Procedure)
概要の通りです

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
こちらのissueで議論できればと思います。
https://github.com/EC-CUBE/ec-cube/issues/5555
