### ISSUE TITLE
管理／フロント　レビューのタイトルに50文字を超える文字列を入力したところ、システムエラーを示す画面に遷移しました

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5726]
## 概要(Overview)
管理画面とフロント画面の両方で、
タイトルに50文字を超える文字列を入力したところ、システムエラーを示す画面に遷移しました

## 期待する内容(Expect)  or 要望 (Requirement)
エラーメッセージが表示された方がよいと思いました

## 再現手順(Procedure)
![レビューを投稿_タイトル_システムエラー1](https://user-images.githubusercontent.com/13821027/187582776-76cc1e3d-0411-47c2-9f62-bab7ee768aa9.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
4.2 最新版ではシステムエラーにならず、入力文字が途中できれました
mysqlです

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ProductReview-plugin/pull/90 で修正
