### ISSUE TITLE
管理　レビュー管理の「検索条件をクリア」ボタンをクリックしても検索条件がクリアされませんでした

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5727]
## 概要(Overview)
管理画面の
レビュー管理の「検索条件をクリア」ボタンをクリックしても検索条件がクリアされませんでした

## 期待する内容(Expect)  or 要望 (Requirement)
検索条件がクリアされた方がよいと思いました

## 再現手順(Procedure)
概要の通りです

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
https://github.com/EC-CUBE/ProductReview-plugin/pull/89

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ProductReview-plugin/pull/89 で修正
