### ISSUE TITLE
フロント　「ご注文内容のご確認」と「マイページ/ご注文履歴詳細」のお届け日の日付の表示形式について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5728]
## 概要(Overview)
お届け日の日付の表示形式が下記のように表示されます
お届け日 2022/08/27 0:00:00(土) お届け時間 午前

## 期待する内容(Expect)  or 要望 (Requirement)
「0:00:00」は不要だと思いました。

## 再現手順(Procedure)
![ご注文内容のご確認_お届け日の日付の表示形式不正](https://user-images.githubusercontent.com/13821027/187583272-58f8154f-9784-42ac-a273-3db97071b5fe.png)
![ご注文履歴詳細_お届け日の日付の表示形式不正](https://user-images.githubusercontent.com/13821027/187583278-f79309b5-433a-41b7-85cc-da1b921e5e7f.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@tiger-nakaya 
ありがとうございます。事象確認しました。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5734 で修正
