### ISSUE TITLE
フロント　マイページ/ご注文履歴詳細のご注文日時について

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5729]
## 概要(Overview)
ご注文履歴詳細に表示されるご注文日時(2022/08/25 13:34:43)が、
「マイページ/ご注文履歴」「管理画面の注文日」「メールに記載されているご注文日時」(2022/08/25 13:39:22)
と異なる

## 期待する内容(Expect)  or 要望 (Requirement)
同一の日時が表示された方がよいと思いました

## 再現手順(Procedure)
![ご注文履歴詳細_ご注文日時不正1](https://user-images.githubusercontent.com/13821027/187583663-d0ae58fd-3028-43e1-bb16-aada4457a6ce.png)
![ご注文履歴詳細_ご注文日時不正2](https://user-images.githubusercontent.com/13821027/187583676-522806f5-0eb2-4c41-a33c-4b690800aa0f.png)
![ご注文履歴詳細_ご注文日時不正3](https://user-images.githubusercontent.com/13821027/187583682-1888e017-6a96-4040-af43-734daedf3bec.png)
![ご注文履歴詳細_ご注文日時不正4](https://user-images.githubusercontent.com/13821027/187583688-ada08609-26a6-4dad-9f30-2a651ece576f.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5736 で対応
