### ISSUE TITLE
管理　受注登録の対応状況で「返品」を行った時の会員のポイント数にマイナスの数値が登録されることがあります

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5730]
## 概要(Overview)
管理　受注登録の対応状況で「返品」を行った時の会員のポイント数にマイナスの数値が登録されることがありますが、
想定通りの挙動でしょうか
そのまま操作を続けると、エラー文言が表示されたり、システムエラーを示す画面に遷移したりする挙動が見られます

## 再現手順(Procedure)
操作例）
　お買い物をして1091ポイント加算→次のお買い物で1091ポイント使用
　→先のお買い物を返品→会員データに-1091ポイントが登録される。
　フロント側からマイページを確認すると-1091ポイントが表示される。
　→ご注文手続きで利用ポイントに「100」を入力し確認するボタンをクリックするとシステムエラーを示す画面に遷移する。
　→受注登録でデータを更新しようとすると「利用ポイントが所有ポイントを上回っています。」のエラー文言が表示される。

![受注登録_返品した場合にポイント数にマイナスの数値が登録されることがある1](https://user-images.githubusercontent.com/13821027/187584089-286b2a10-59b1-4ccf-b1c0-1a2f0572037e.png)
![受注登録_返品した場合にポイント数にマイナスの数値が登録されることがある2](https://user-images.githubusercontent.com/13821027/187584182-82b98a65-8bc9-4eef-9084-93cdbb10463f.png)
![受注登録_返品した場合にポイント数にマイナスの数値が登録されることがある3](https://user-images.githubusercontent.com/13821027/187584187-16941bc2-cf6d-45dc-96fd-d2c7667b6e2a.png)
![受注登録_返品した場合にポイント数にマイナスの数値が登録されることがある4](https://user-images.githubusercontent.com/13821027/187584189-5b2f0b01-043e-414c-bd8a-9c47d9155fb0.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
> 　→ご注文手続きで利用ポイントに「100」を入力し確認するボタンをクリックするとシステムエラーを示す画面に遷移する。

これは発生しませんでした。

**Comment by chihiro-adachi** [comment]
> ご注文手続きで利用ポイントに「100」を入力し確認するボタンをクリックするとシステムエラーを示す画面に遷移する。

システムエラーは発生しませんでした(PgSQLで確認)。
「利用ポイントが所有ポイントを上回っています。」のエラー文言が表示されます。

> 管理　受注登録の対応状況で「返品」を行った時の会員のポイント数にマイナスの数値が登録されることがありますが、
想定通りの挙動でしょうか

ポイントに関しては返品等のタイミングでどうしてもマイナスポイントが発生することはあります。
その場合、購入フローや受注編集では「利用ポイントが所有ポイントを上回っています。」のエラー文言が表示されます。
