### ISSUE TITLE
管理　受注一覧 　注文者で並べ替えを行うと、注文者名ではなく注文番号で並べ替えが行われます

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5731]
## 概要(Overview)
管理　受注一覧 　「注文者」で並べ替えを行うと、注文者名ではなく「注文番号」で並べ替えが行われます
想定通りの挙動でしょうか

## 再現手順(Procedure)
概要の通りです

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5744
