### ISSUE TITLE
管理　受注登録 　電話番号に数字以外の文字列が登録できます

### ISSUE THREAD

**Issue by tiger-nakaya** [EC-CUBE/ec-cube#5732]
## 概要(Overview)
管理
受注登録
電話番号に数字以外の文字列が登録できます

補足
・会員登録フォームでは数字以外不可でした

## 期待する内容(Expect)  or 要望 (Requirement)
エラーチェックを行ったがよいと思いました。

## 再現手順(Procedure)
概要の通りです

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nobuhiko** [comment]
4.2 最新版では 出荷情報>電話番号は数字しか登録できないようでした。
@tiger-nakaya どのバージョンで動作確認をされていますか？

**Comment by tiger-nakaya** [comment]
@nobuhiko 
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta
から2022/8/16に取得して動作確認をしていました。
これまでに確認したものを本日登録したのですでに対応されているものも含まれているかもしれません。
お手数をおかけして申し訳ございません。

**Comment by chihiro-adachi** [comment]
@tiger-nakaya 
投稿いただいたIssueについて、お手数ですが最新のパッケージで再度ご確認いただけないでしょうか。

現時点の最新パッケージは以下になります。
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta2-20220829

もし修正済のIssueあればクローズいただけるとありがたいです。

**Comment by chihiro-adachi** [comment]
注文者・出荷情報ともにバリデーションはかかってそうです。
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/8196725/188028804-bcbc61b4-d40c-44b2-9947-34bacff37af9.png">
