### ISSUE TITLE
商品を廃止状態にしても管理者の場合URLで直接アクセスすると閲覧可能

### ISSUE THREAD

**Issue by kurozumi** [EC-CUBE/ec-cube#5737]
## 概要(Overview)
商品を廃止状態にしても管理者の場合URLで直接アクセスすると閲覧可能です。

## 期待する内容(Expect)  or 要望 (Requirement)
廃止した商品を管理者のみですが閲覧できるのは正常でしょうか？
改善してほしいというお問い合わせがあったので確認です。

## 再現手順(Procedure)
・チェリーアイスサンドを廃止
・管理画面ログイン
・https://domain/products/detail/2
・チェリーアイスサンドが閲覧可能

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@kurozumi 

同様の改善要望Issueはあがってますね。
https://github.com/EC-CUBE/ec-cube/issues/5006

**Comment by kurozumi** [comment]
@chihiro-adachi 

非表示の場合は商品一覧で表示され、廃止の場合は商品一覧で表示されないので、
非表示はメンテナンスモードのように表示させて、
廃止の場合は表示させないようにするのはどうでしょうか？

**Comment by chihiro-adachi** [comment]
@kurozumi 
> 非表示の場合は商品一覧で表示され、廃止の場合は商品一覧で表示されないので、

あれ、一覧はどちらも表示されないような気もします。。

非表示と廃止で実装分けるの面倒ではないですか？
商品のステータスが判別つかないのが課題だと思うので、管理者アクセスのメッセージ＋商品のステータスを表示とかでもよいのかなと思いました。

※そこまでこだわりがあるわけではないので、実装が複雑にならなければご提案いただいた挙動でもよいかと思います。

**Comment by kurozumi** [comment]
@chihiro-adachi 

あ、ごめんなさい。
商品一覧とは管理画面の商品一覧のことです。
言葉足らずでした。

こだわりがないのでしたらどうするか考えてPRします。
