### ISSUE TITLE
割引の名称が長い場合、納品書の高さが崩れる

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5741]
## 概要(Overview)
割引の名称が長いと、商品名の行の高さが揃いません

## 期待する内容(Expect)  or 要望 (Requirement)
高さが揃うとよいです

## 再現手順(Procedure)
長い名称の割引を登録した注文の納品書を表示させます

![image](https://user-images.githubusercontent.com/8424850/187624327-52868a51-7f4f-4ae0-86ec-92bd4e8c38a5.png)

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5742 で修正
