### ISSUE TITLE
納品書のメッセージを消しにくい

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5745]
## 概要(Overview)
納品書のタイトルおよびメッセージの1行目から3行目は
入力を空にすると、デフォルトの値が納品書として出力されるようになっています
そのため、例えば3行目の”ご確認くださいますよう、お願いいたします。”は不要と考え、店舗管理者が消そうとする場合は
3行目を空にするのではなく、スペースをあえて入力する必要があります。

本来の意図と違う入力を行わせることになります。

## 期待する内容(Expect)  or 要望 (Requirement)
タイトルは必須とする
メッセージの1行目から3行目は入力の通り(空であれば空のまま)出力がよいです

## 再現手順(Procedure)
受注登録画面から、登録済みの受注を開きます
納品書を出力ボタンをクリックし、納品書出力ウィンドウを表示します

たとえば、メッセージの3行目を空にして、作成ボタンをクリックします

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5746 で対応
