### ISSUE TITLE
HOST書き換えアクセス時のエラーページのトップへ戻るリンクはlocalhostになる

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5747]
## 概要(Overview)
HOSTを書き換えてアクセスした場合
エラーページのトップへ戻るリンクはlocalhostになります

## 期待する内容(Expect)  or 要望 (Requirement)
localhostを踏ませないよう、トップへ戻るボタンを表示させない？

## 再現手順(Procedure)
TRUSTED_HOSTSを設定したうえで、HOSTSを書き換えてサイトにアクセスします

![image](https://user-images.githubusercontent.com/8424850/187651676-b1ffa9f1-d98b-4e9e-a5ad-24f7182284df.png)

そうすると、共通のエラーページが出ますが
トップページへのリンクはlocalhostになります

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
こちらに記載の通り、trusted hostのチェック以外でも同様の事象が発生します。
url関数ではなくpath関数で対応するくらいでよさそうです。
https://github.com/EC-CUBE/ec-cube/pull/5748#issuecomment-1273932111

**Comment by chihiro-adachi** [comment]
#5883 で対応
