### ISSUE TITLE
割引の表示が登録順にならない

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5749]
## 概要(Overview)
管理画面から割引を複数登録し、削除→登録を繰り返すと表示順が登録の順番にならなくなります

![image](https://user-images.githubusercontent.com/8424850/187673459-759ce2cb-471a-4086-b2f5-c1d1b9d697f4.png)

D→E→Fと登録しているのに、表示はF→D→Eとなっています

![image](https://user-images.githubusercontent.com/8424850/187673599-a5937e94-ca6a-43a2-9c87-3f634f8e19df.png)

## 期待する内容(Expect)  or 要望 (Requirement)
登録順に表示されてほしい

## 再現手順(Procedure)
![image](https://user-images.githubusercontent.com/8424850/187673677-0a255dd5-56eb-4220-905f-ac148da0cbb2.png)

まず上図の登録からスタートします
次に、Aを消しDを追加します→登録
次に、Cを消しEを追加します→登録
次に、Bを消しFを追加します→登録

※登録ボタンを押した直後の表示は正しい順に見えても、更新すると順番が崩れます

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@takeuji 
ありがとうございます。事象確認しました

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/issues/5749 で対応
