### ISSUE TITLE
スピナーがボタン内に見えない

### ISSUE THREAD

**Issue by takeuji** [EC-CUBE/ec-cube#5757]
## 概要(Overview)
白地ボタンの場合、くるくる回る表示が見えない状態です

## 期待する内容(Expect)  or 要望 (Requirement)
スピナーが黒系で表示されるとよいです

## 再現手順(Procedure)
![btn](https://user-images.githubusercontent.com/8424850/187709047-34d556a5-3771-44ac-8876-59887f808a64.gif)

白地のボタンをクリックします

するとボタンが膨らんで、本当はスピナーが表示されていますが、見えません

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5762　で対応
