### ISSUE TITLE
Proposal: 画像やcssのTwigでの表記方法について

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#577]
現状、テンプレート内での画像のファイルの

```
<img src="{{ app.config.front_urlpath }}/img/top/mv01.jpg">
<script src="{{ app.config.front_urlpath }}/js/vendor/bootstrap.custom.min.js"></script>
<img src="{{ app.config.admin_tpl }}img/contents/logo_resize.jpg" width="99" height="15" alt="EC-CUBE" />
```

などと表記をしていますが、CDNへの対応や `app.config` 以下に設定として多くの画像をもっておく必要があります。
こういったことを解決するために、Symfony デフォルトの Asset component  をデフォルトで利用するのはどうでしょうか。

Fabpotのログでの紹介も以下にあります。
http://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component

導入することで、以下のように表記することができます。

```
<img src="{{ asset('img/top/mv01.jpg') }}">
<script src="{{ asset('js/vendor/bootstrap.custom.min.js') }}"></script>
<img src="{{ asset('img/contents/logo_resize.jpg') }}" width="99" height="15" alt="EC-CUBE" />
```

adminかどうかの判断部分もassetの設定側にもっていくことで、テンプレートの表記がわかりやすくシンプルになるかと思います。
こちら、問題がなさそうでしたら実際にコードを書いてプルリクを投げたいと思います。

**Comment by ttsuru** [comment]
こちら、同時に多くのパスを設定している変数を削除し、環境変数から取得することで、環境に依存せず、インストールや設定変更なども容易にしたいと思います。
``${ROOT_DIR}`` などは不要になると思います。
現状のSymfony FWでも同様の内容になっています。

**Comment by Yangsin** [comment]
こちらぜひPRとして確認できればと。
デザインテンプレートやプラグインのインストールにも考慮が必要そうですね。

**Comment by ttsuru** [comment]
こちら、現状の ``path.yml`` がほぼ要らなくなるため、設定やサーバの移動などを含めて極めて有効だと思います。
ぜひ実装したいのですが、いかがでしょうか。

https://github.com/MatTheCat/silex-asset-provider

**Comment by ttsuru** [comment]
refs #916

**Comment by nanasess** [comment]
> 環境変数から取得することで

環境変数は、どこかに設定されているものを取得する感じでしょうか？

**Comment by shhirose** [comment]
本件だいぶ時間が経っていますが、私の方でサンプルを作ってみました。（フロントのみです。）
https://github.com/shhirose/ec-cube/tree/asset_sample

@ttsuru 
`path.yml`も量を減らそうと調べてみたのですが、やり方がよくわかりませんでした・・・。
アドバイスがあればおねがいします。

**Comment by ttsuru** [comment]
@shhirose 
https://github.com/EC-CUBE/ec-cube/pull/1543
こちらである程度対応しました。
