### ISSUE TITLE
[4.2] 商品詳細画面で画像ファイルのドラッグ、ドロップで枠内に収まらないと画像がブラウザに表示される

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#5777]
## 概要(Overview)
商品詳細画面で枠内に収めずに画像をドラッグ、ドロップするとブラウザに画像が表示されてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)
4、4.1と同じように枠内に収まらずにドラック、ドロップされても無視されるようにすること。
支払方法設定では正常に動作している。

### 環境 (environment)
+ EC-CUBE: 4.2

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5788 で対応
