### ISSUE TITLE
[4.2] 問題のあるブロックのコード プレビュー

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5782]
## 概要(Overview)
管理ページで /content/layout/new に移動し、ブロック コード プレビューを選択し、ポップアップの外側をクリックして非表示にすると、画面が機能しなくなります。

## 再現手順(Procedure)
Step 1. コンテンツ管理 -> レイアウト管理 -> 新規作成
未使用ブロックを右クリック
![image](https://user-images.githubusercontent.com/105194449/189322837-754c83b5-6635-4ef4-8bae-350a301c23b9.png)

Step 2. ポップアップが表示され、外側を押してこのポップアップを非表示にします
![image](https://user-images.githubusercontent.com/105194449/189325320-f6447097-9f14-46e3-ba0a-7b540d76dd7b.png)

Step 3. ポップアップ ウィンドウを閉じて開く操作を繰り返していると、インプレッション数が何度も繰り返されていることに気付きました。
![image](https://user-images.githubusercontent.com/105194449/189326903-35d1062f-86a0-453d-a752-183f8e7a8312.png)

Step 4. 画面が私のすべてのアクションをブロックしました
![image](https://user-images.githubusercontent.com/105194449/189327039-2849210f-7238-4263-a2b4-c54ec7ab1a74.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220905）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5783 で対応
