### ISSUE TITLE
[4.2] LOCK_DSN=semaphore は不要？

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5786]
## 概要(Overview)
#5473 に伴い、 .env に `LOCK_DSN=semaphore` が追加されているが、無くてもログインスロットリングは動作する模様。
ログインスロットリングの制御には var/cache 以下のファイルが使用されており、セマフォは使用されていない模様。
また、 docker-compose.yml の environment には `LOCK_DSN=semaphore` が設定されていないがログインスロットリングの機能は動作している

## 期待する内容(Expect)  or 要望 (Requirement)
`LOCK_DSN=semaphore` を削除する

## 再現手順(Procedure)
環境変数 LOCK_DSN を使用せず、同一IDによるログインを5回以上失敗させる

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4.30
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
#5473

**Comment by chihiro-adachi** [comment]
@nanasess 
`symfony/rate-limiter`をcomposer requireした際に、自動で追加されてました。
設定なしでも動作するのであれば削除しても問題ないかなと思います。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5809 で対応
