### ISSUE TITLE
[4.2]  二要素認証の編集時に画面にエラーが表示されない

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5789]
## 概要(Overview)
二要素認証の編集時に画面にエラーが表示されない

## 再現手順(Procedure)
Step 1. 二段階認証で管理者アカウントでログイン
2 要素認証の編集ボタンを選択します
![image](https://user-images.githubusercontent.com/105194449/190047576-ab8912e5-fff2-46f3-8a5e-8cf6c66f36ec.png)

Step 2. 任意の数字を入力して登録ボタンを押す
![image](https://user-images.githubusercontent.com/105194449/190047613-af882ff6-a4bd-4015-8b11-99c92b7e50c9.png)

Step 3. 画面にエラー メッセージが表示されない
![image](https://user-images.githubusercontent.com/105194449/190047628-2feb7abd-27e4-4897-abf2-a64e4d0f11ff.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220905）

**Comment by chihiro-adachi** [comment]
@maianhtu010596 
ありがとうございます。事象確認しました。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5794 で対応
