### ISSUE TITLE
空ディレクトリに置くファイルの統一

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#579]
現状、 ``dummy`` と ``.gitkeep`` があり統一されていません。
こちら、``.gitkeep`` に統一してはいかがでしょうか。
Symfonyでは空ディレクトリは基本的にありませんが、以下の部分で ``.gitkeep`` が利用されています。

```
vendor/symfony/intl/Tests/Data/Bundle/Reader/Fixtures/NotAFile/en.php/.gitkeep
```

**Comment by Yangsin** [comment]
.gitkeep 統一で問題ありません。dummyについては、SVN時代の名残だとおもっていただければ・・・
