### ISSUE TITLE
[4.2] モーダルの閉じるボタンのマークアップ

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5791]
## 概要(Overview)

モーダルの閉じるボタンのマークアップがbootstrap5に対応できていない

## 再現手順(Procedure)

管理画面>ホームから、おすすめのプラグインを選択することで確認可能です。
![image](https://user-images.githubusercontent.com/105194449/190048545-c4348f40-6502-4ea1-b9e4-1e6e181ae351.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220905）

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5802 で対応
