### ISSUE TITLE
[4.1.x, 4.2.x] 値をスペースで更新してから更新をキャンセルすると、元の値が消えます

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5792]
## 概要(Overview)
インターフェースのクイックエディットでカテゴリとかタグとかそういうのを更新したら、入力値がスペースだったりエラー画面が出て更新キャンセルを押したら初期値頭がなくなったり、これは表示エラー。

## 再現手順(Procedure)
Step 1.  商品管理 ↦ カテゴリ管理
![image](https://user-images.githubusercontent.com/105194449/190053428-f0254186-c9f2-4197-9b35-c615990986ba.png)

Step 2. ボタンを押すと、カテゴリをすばやく編集できます
![image](https://user-images.githubusercontent.com/105194449/190053445-0034b762-618d-42c3-9cb1-9a5ca05d1884.png)

Step 3. 値をスペースとして入力し、登録ボタンを押すと、エラー行が表示されます。
![image](https://user-images.githubusercontent.com/105194449/190053455-2fcac23f-b998-416a-9910-f50734bec701.png)

Step 4. 次に、更新のキャンセル ボタンを押すと、画面に元の値が再び表示されなくなります。
![image](https://user-images.githubusercontent.com/105194449/190053474-40904152-238b-435a-9e15-09e1a0669739.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220905）

**Comment by chihiro-adachi** [comment]
@maianhtu010596 
ありがとうございます。事象確認しました。
タグ管理の機能でも同様の事象があるようです。

**Comment by maianhtu010596** [comment]
@chihiro-adachi はい、確認ありがとうございます
で同様の現象が発生
/product/class_name (規格管理)
/product/category (カテゴリ管理)
/product/tag (タグ管理)

**Comment by maianhtu010596** [comment]
@chihiro-adachi 
で同様の現象が発生
/setting/shop/delivery/{id}/edit (配送方法設定)
