### ISSUE TITLE
[4.2] ポイントがマイナスの場合、受注を更新できない

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5795]
## 概要(Overview)
管理ページでは、メンバーシップ スコアがマイナスの場合、請求書を更新できません。

## 再現手順(Procedure)
Step 1. メンバーのスコアを負の数に変更します
![image](https://user-images.githubusercontent.com/105194449/190149577-d866beba-82e1-4a36-9552-d2131129024e.png)

Step 2. 請求書管理ページで、スコアがマイナスの会員の請求書を更新する
エラーメッセージ画面が表示される
[利用ポイントが所有ポイントを上回っています。]
![image](https://user-images.githubusercontent.com/105194449/190149699-33a1080b-f24e-43f7-8d98-499c8b001dc7.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.x, 8.0.x, 8.1.x
+ DB:
  - PostgreSQL 10.x.x
  - MySQL 5.7.x, 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-beta2-20220905）

**Comment by chihiro-adachi** [comment]
@maianhtu010596 
ありがとうございます。事象確認しました。

**Comment by chihiro-adachi** [comment]
diffが0ならエラーにしなくてよい気がしますね。
https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Service/PurchaseFlow/Processor/PointDiffProcessor.php#L69

**Comment by toshiaki-h** [comment]
@chihiro-adachi 横から失礼します。こちら4.1.2でも同様の問題が発生しております。
