### ISSUE TITLE
app/console をインストール前から実行できるようにしたい

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#580]
`app/console` がインストール前には利用できません。
せっかくですので、 `eccube_install.sh` を廃止し、 `./app/console eccube:install` や `./app/console eccube:fix-perms` 的なことができるとよいのではないでしょうか。

**Comment by nanasess** [comment]
#1798 で、 eccube_install.sh を PHP スクリプトにしてみました。
Composer のセットアップや、 CREATE DATABASE を `app/console` で実行するのが難しそうだったので、とりあえずは単体の PHP スクリプトにしましたが、 スキーマ生成や、マイグレーションの処理は `app/console` に移植した方がいいかもしれません。

**Comment by ttsuru** [comment]
:+1: 
せっかくなので他のコマンドと同様に Symfony Console にしてしまいたいですね。

**Comment by xuelian311** [comment]
長期間にわたって議論が停止していますので、一度クローズいたします。
引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
