### ISSUE TITLE
[4.2] お届け日を制限を超える過去の日付を入力するとエラーが発生しました

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5816]
## 概要(Overview)
お届け日を一定の制限を超える日付を入力するとエラーが表示されます。

## 再現手順(Procedure)
Step 1. 制限を超えた配達日を入力してください。
![image_2022_09_23T10_18_21_366Z](https://user-images.githubusercontent.com/105194449/191941065-61e343b6-50ad-4487-ab84-5c76397e8f6e.png)
Step 2. 表示システムエラー
![image_2022_09_23T10_18_34_576Z](https://user-images.githubusercontent.com/105194449/191941095-e32f6e92-4165-4d2f-83ba-faa7123aced5.png)
Step 3.  開発環境で表示されます
![image_2022_09_23T10_21_13_282Z](https://user-images.githubusercontent.com/105194449/191941088-60ec471e-a55d-4635-bc01-f017ebaef692.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-rc
+ PHP: 7.4.x, 8.1.x
+ DB:
  - PostgreSQL 14.x.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-rc）

**Comment by dotani1111** [comment]
修正済みなのでクローズします。
