### ISSUE TITLE
[4.2] 支払い方法の画像の表示が大きすぎる

### ISSUE THREAD

**Issue by maianhtu010596** [EC-CUBE/ec-cube#5817]
## 概要(Overview)
支払い方法の画像の表示が大きすぎる

## 再現手順(Procedure)
Step 1. お支払い方法の編集ページへ
![image_2022_09_23T10_27_05_064Z](https://user-images.githubusercontent.com/105194449/191944558-3549eb5c-6dcb-4851-bd2e-c135594b5cf5.png)
Step 2. 支払い方法の画像を追加し、登録を押します。
![image_2022_09_23T10_27_45_092Z](https://user-images.githubusercontent.com/105194449/191944568-fb9fcba8-e925-4637-8704-445e4df6e853.png)
Step 3. ショッピングカートページへ
![image_2022_09_23T10_28_45_417Z](https://user-images.githubusercontent.com/105194449/191944573-1aadd585-2874-4f9b-85d2-666348eb9e33.png)
Step 4. お支払い方法の画像表示が大きすぎます。
![image_2022_09_23T10_29_17_884Z](https://user-images.githubusercontent.com/105194449/191944582-0917e891-9aa2-41bb-9d9a-879b495d66d5.png)

### 環境 (environment)
+ EC-CUBE: 4.2.0-rc
+ PHP: 8.1.x
+ DB:
  - MySQL 8.0.x

## 関連情報 (Ref)
モンキーテスト（β2 - EC-CUBE 4.2.0-rc）

**Comment by chihiro-adachi** [comment]
支払方法画像は任意の画像を登録してもらえればと思いますので、こちらの修正は行いません。
