### ISSUE TITLE
/install.php/step5 にて Session の Warning が発生する

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#582]
以下のエラーが発生します。
```
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 56
```

**Comment by geany-y** [comment]
@chihiro-adachi の要望で以下設定でチェックしてみました。
--------------------------------xampp(php.ini)-------------------------------------
~
~
 display_errors
   Default Value: On
   Development Value: On
   Production Value: Off
~
~
error_reporting = E_ALL | E_STRICT
~
~
display_errors=On
~
--------------------------------xampp(php.ini)-------------------------------------

現状再現せずでした。
再現ケースをご教授いただけるとありがたいです。

**Comment by chihiro-adachi** [comment]
現masterで再現しないため、クローズします。

**Comment by nobuhiko** [comment]
このエラーは出なくなってましたが下記エラーが出るようになってました
PHP Notice:  ob_flush() [<a href='ref.outcontrol'>ref.outcontrol</a>]: failed to flush buffer. No buffer to flush in /Users//eccube/src/Eccube/Controller/Install/InstallController.php on line 254
