### ISSUE TITLE
商品CSV登録する際に、改行を含んだ特定の文字が末尾にある文章を登録するとエラーが発生する

### ISSUE THREAD

**Issue by xx4Z** [EC-CUBE/ec-cube#5838]
## 概要(Overview)
商品CSV登録する際に、改行を含んだ特定の文字が末尾にある文章を登録するとエラーが発生します。
下記のような文章を『商品説明(詳細)』に入力し、商品CSV登録を行うとエラーになります。
`ここに文章が入ります。`
`可能`

『商品説明(詳細)』だけでなく、『商品説明(一覧)』や『ショップ用メモ欄』でも同様のエラーが発生します。
全ての文字を試したわけではないですが、改行した文章の末尾が下記のような文字だとエラーが起こるようです。
https://www.psl.ne.jp/references/0x5c.html

インストールしたデフォルト状態で再現出来ています。

## 期待する内容(Expect)  or 要望 (Requirement)
改行を含んだ特定の文字が末尾にある文章があっても商品登録が行える。

## 再現手順(Procedure)
1. 商品登録の際に、『商品説明(詳細)』に文章を入力し改行して最後に『能』の文字を入力して商品登録を行う。
2. 登録した商品を含んだCSVをダウンロードする。
3. ダウンロードしたCSVファイルで商品CSV登録を行う。
4. エラーが発生し商品登録が行えない。

### 環境 (environment)
+ Xserver
+ EC-CUBE: 4.1.2
+ PHP7.4.28
+ DB:
  - MariaDB10.5

## 関連情報 (Ref)

**Comment by chihiro-adachi** [comment]
@xx4Z 
エラーが発生するCSVを共有いただくことはできますでしょうか？

**Comment by xx4Z** [comment]
@chihiro-adachi 
ファイルをお送りいたします。
お手数ですが、確認よろしくお願いいたします。
[product_20221014111802.csv](https://github.com/EC-CUBE/ec-cube/files/9781939/product_20221014111802.csv)

**Comment by nanasess** [comment]
4.2 で直ってると思います
https://github.com/EC-CUBE/ec-cube/pull/5407

**Comment by chihiro-adachi** [comment]
@xx4Z @nanasess 
ご確認ありがとうございます。
4.2 ではエラーは発生せず、正常に取り込むことができました。

**Comment by chihiro-adachi** [comment]
4.2では修正済のため、こちらはクローズさせていただきます。
