### ISSUE TITLE
How to add more order steps?

### ISSUE THREAD

**Issue by bocanhcam** [EC-CUBE/ec-cube#5840]
I read the docs and haven't seen a way to customize the order steps.
Now we have 4 steps:
1. ```items in shopping cart```
2. ``` Order procedure```
3. ``` Order confirmation```
4. ```Complete```

What if I want to add one more step before step 2 (```Order procedure```) and one more step after it?
What is the best practice for doing that?
Both steps I'm planning to add require inserting information into new tables with ```order_id```. So it requires order information

### 環境 (environment)
+ EC-CUBE: 4.2.x
+ PHP: 7.4.30
+ DB:
  - MySQL 5.7

**Comment by nanasess** [comment]
If you are familiar with Git, you may want to customize src/Eccube/Controller/ShoppingController.php directly.
Otherwise, create a new ShoppingController in the app/Customize directory.

**Comment by bocanhcam** [comment]
@nanasess Thanks. What I mean is more detail on how to customize it with at least changes. Anyway, I going to close this topic. If you have any ideas feel free to comment on it.
