### ISSUE TITLE
Twigのrender関数に渡した変数のタイムゾーンが変わる

### ISSUE THREAD

**Issue by hayato07** [EC-CUBE/ec-cube#5842]
## 概要(Overview)
sendOrderMail関数内のrenderメソッド前後で$Orderのタイムゾーンが変わっている。

## 要望 (Requirement)

renderメソッドに利用した変数のタイムゾーンがECCUBE_TIMEZONEで設定したものになっていること。

## 再現手順(Procedure)

1. インストールしたデフォルト状態で、.envのタイムゾーンをAsia/Tokyoに設定する。
2. sendOrderMail関数内のtwigのrenderメソッドの使用前後に下記コードを追加する。
3. ゲストユーザーで購入処理を進め、注文するボタンを押下すると、前後でタイムゾーンに変化が見られる。

(EccubeEvents::MAIL_ORDERイベントに渡される$Orderの日時もUTCになっている。)

```diff
+ var_dump($Order->getCreateDate()->format('e')); // Asia/Tokyo
        
$body = $this->twig->render($MailTemplate->getFileName(), [
    'Order' => $Order,
]);

+ var_dump($Order->getCreateDate()->format('e')); // UTC
+ exit;
```

### 環境 (environment)
+ EC-CUBE: 4.2, 4.1.2
+ PHP: 8.0.21, 7.4.29
+ DB:
  - Sqlite

**Comment by chihiro-adachi** [comment]
@hayato07 
たぶんですが、UTCへの変換処理がどこかのタイミングで走っているのかなと思います。
https://github.com/EC-CUBE/ec-cube/pull/2308

何か実害は発生してますか？

**Comment by hayato07** [comment]
@chihiro-adachi 

実害はないのですが、気づくまでにハマっていました。
情報を調べてみましたが、どこにも見つけられなかったので、issue作成させていただきました。


EccubeEvents::MAIL_ORDERイベントを利用するプラグインを作成する際に、時間がどうしてもUTCになってしまっており、今回の現象を発見した形になります。

現在の対応としては、イベントに追加する処理内で、EccubeConfigを利用して再度envで設定した内容に変換を行うようにしております。

**Comment by hayato07** [comment]
@chihiro-adachi 

こちら仕様ということであればissue閉じようと思います。
