### ISSUE TITLE
Form submit redirect http instead of https

### ISSUE THREAD

**Issue by bocanhcam** [EC-CUBE/ec-cube#5846]
I'm using EC-CUBE 4.2 with docker-compose

I deployed EC on a domain with HTTPS.

Every form in EC redirects to HTTP instead of HTTPS which creates an error "The information you’re about to submit is not secure"

I tried to use ECCUBE_FORCE_SSL=1 but it got another error "This page isn’t working...redirected you too many times"

I know this place is not supposed to answer questions but I tried to use the forum https://xoops.ec-cube.net/ but seems like no help 

+ EC-CUBE: 4.2
+ PHP: 7.4
+ MySQL 5.7

**Comment by nanasess** [comment]
Is the following URL helpful?
https://stackoverflow.com/a/34119372

**Comment by chihiro-adachi** [comment]
@bocanhcam 
Someone answered.
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27108&forum=2&post_id=107175#forumpost107175
