### ISSUE TITLE
M1 Macでdocker-compose upが立ち上がらない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5847]
## 概要(Overview)

4.2ブランチのHEADでdocker-compose upを実行すると以下のようなエラーが発生します。
https://github.com/EC-CUBE/ec-cube/pull/5801 が影響しているようです。

```
ec-cube42-ec-cube-1      | > bin/console eccube:fixtures:load
ec-cube42-ec-cube-1      |   > Finished Successful!
ec-cube42-ec-cube-1      | Executing script cache:clear --no-warmup [OK]
ec-cube42-ec-cube-1      | Executing script cache:warmup --no-optional-warmers [OK]
ec-cube42-ec-cube-1      | Executing script assets:install --symlink --relative html
ec-cube42-ec-cube-1      |  [OK]
ec-cube42-ec-cube-1      | [Tue Oct 25 02:38:11.694696 2022] [env:warn] [pid 1] AH01506: PassEnv variable TRUSTED_PROXIES was undefined
ec-cube42-ec-cube-1      | [Tue Oct 25 02:38:11.696328 2022] [env:warn] [pid 1] AH01506: PassEnv variable TRUSTED_HOSTS was undefined
ec-cube42-ec-cube-1      | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.2. Set the 'ServerName' directive globally to suppress this message
ec-cube42-ec-cube-1      | [Tue Oct 25 02:38:11.705847 2022] [core:emerg] [pid 1] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex 
ec-cube42-ec-cube-1      | (95)Operation not supported: could not create accept mutex
ec-cube42-ec-cube-1      | AH00015: Unable to open logs
```

## 再現手順(Procedure)

```
gh repo clone EC-CUBE/ec-cube
cd ec-cube
docker-compose up
```

### 環境 (environment)
+ Mac Monteray (M1)
+ EC-CUBE: 4.2.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nanasess** [comment]
arm64 のイメージをビルドすると、多大な時間がかかるので今のところ対応してないです。
以下 docker-compose.yml のコメントにあるように、自前でビルドしてもらえると良いかと
https://github.com/EC-CUBE/ec-cube/blob/1815e6ab57a6bf495d80f64d0b12f4cc722847a7/docker-compose.yml#L23-L24

**Comment by nanasess** [comment]
もし対応したい場合は、以下2箇所のコメントをはずすと arm64 のイメージも作れます(時間がかかります)
https://github.com/EC-CUBE/ec-cube/blob/1815e6ab57a6bf495d80f64d0b12f4cc722847a7/.github/workflows/dockerbuild.yml#L44-L48
https://github.com/EC-CUBE/ec-cube/blob/1815e6ab57a6bf495d80f64d0b12f4cc722847a7/.github/workflows/dockerbuild.yml#L129

**Comment by nanasess** [comment]
以下でいけるかも。手元に M1 の環境がないのでお試しください🙇‍♂️
```shell
RUN echo "Mutex posixsem" >> /etc/apache2/apache2.conf
```
https://stackoverflow.com/a/73303983

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます、無事起動しました！
以下PullRequest投げてます。
https://github.com/EC-CUBE/ec-cube/pull/5848

**Comment by nanasess** [comment]
@chihiro-adachi よかったです！ありがとうございます！

**Comment by shinya** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5848
こちらにて解決済みなのを確認できましたので、クローズいたします。
