### ISSUE TITLE
サイト管理画面＞情報に管理・運用マニュアルリンクが欲しい

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5852]
## 概要(Overview)
周知が低いようなので、サイト管理画面の情報項目に、[管理・運用マニュアル](https://www.ec-cube.net/manual/ec-cube4/)のリンクを追加いただきたいです。

## 期待する内容(Expect)  or 要望 (Requirement)
リンクを追加することで、お問い合わせ件数の削減を期待しております。

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
#5878 で対応
