### ISSUE TITLE
CSVのカラム名が重複していた場合でも列の順番を保持する

### ISSUE THREAD

**Issue by valbeat** [EC-CUBE/ec-cube#5854]
## 概要(Overview)

`\Eccube\Service\CsvImportService`でheader名が重複するCSVを読み込む際に`DUPLICATE_HEADERS_INCREMENT`オプションを選択できるようにしたい。
また、重複するカラムが隣接していない場合、順番が変わってしまう。

## 期待する内容(Expect)  or 要望 (Requirement)

pull requestを作成しましたので、よろしければmergeをお願いします。 #5855

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
@valbeat 
カラム名が重複するのって実際どんなケースなんでしょう。
すみませんが、あまり聞いたことがないなと思いまして。

**Comment by valbeat** [comment]
@chihiro-adachi 
外部の企業様とのデータの受け取りで発生することがあります。
APIでjson等でデータを受け渡す場合と違い、csvデータにはカラム名の重複が起きうる仕様なので。

**Comment by chihiro-adachi** [comment]
@valbeat 
ありがとうございます。
重複が自動的に解消されるよりは、重複しているのであればエラーとなるのが利用側からするとイメージしやすい挙動かと思いました。誤ってカラムが複数あり、エラーに気づかず登録されてしまう、というケースも考えられます。

**Comment by chihiro-adachi** [comment]
こちらについては一旦クローズさせていただきます。
ご意見等あればReOpenいただければとおもいます。

**Comment by hironori-tanaka** [comment]
DUPLICATE_HEADERS_INCREMENT オプションを使用したいケースが発生しました。
販売システムの出荷データから出力されるCSVに重複カラムがあり、このCSVを取り込むときに使用したいと思っています。
出荷データCSVは次のような列になっています。

出荷ID 会員ID 配送先（名、住所、TELなど） 出荷日 商品ID 商品名 単価 個数 小計 商品ID 商品名 単価 個数 小計 商品ID 商品名 単価 個数 小計
