### ISSUE TITLE
商品CSVにおける商品規格の扱いの改善

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5856]
## 概要(Overview)
 - https://github.com/EC-CUBE/ec-cube/issues/4190
   - https://github.com/EC-CUBE/ec-cube/pull/4199
- https://github.com/EC-CUBE/ec-cube/issues/4282
- https://github.com/EC-CUBE/ec-cube/issues/5766
    - https://github.com/EC-CUBE/ec-cube/pull/5853

商品規格が論理削除(visible = true/false)となっている関係で、以下のような問題が発生している
- 商品コピー、初期化を繰替えすと visible = false のデータが増え続ける
- 商品CSVダウンロードに visible = false のデータが含まれるが、 visible = true に更新することはできない
- 規格有り商品をコピー→規格無し商品を登録した場合に visible = false の商品規格が残ってしまう
- 商品CSVアップロードで visible = false に更新することができない

## 期待する内容(Expect)  or 要望 (Requirement)
- [x] 商品初期化時は物理削除する
- [x] 商品CSVダウンロードボタンを「商品CSV」と「商品CSV(非表示の商品規格を含む)」に分ける
- [x] 商品CSVアップロードに「商品規格非表示フラグ」を追加し、商品規格をCSVで非表示にできるようにする
- [x] 商品CSVアップロード時、visible = false の行が存在する場合は visible = true に更新する

## 再現手順(Procedure)
概要のリンク先 issues を参照

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4

**Comment by nanasess** [comment]
管理画面側の visible の動きを要確認
→ チェックボックスの ON/OFF で visible = true/false が切り替わるようになっていました。また、dtb_product_class の行を物理削除した状態で、チェックボックスを ON にした場合、 visible = true の行が追加されます
![image](https://user-images.githubusercontent.com/815715/203724293-f4646421-4e25-4540-bfa0-a27d4791a9ca.png)

**Comment by nanasess** [comment]
#5875 に別の解決方法を PR しました

**Comment by chihiro-adachi** [comment]
以下2点を取り込みました。
- https://github.com/EC-CUBE/ec-cube/pull/5853
- https://github.com/EC-CUBE/ec-cube/pull/5875
