### ISSUE TITLE
下層ディレクトリにec-cubeを設置した場合、カート→レジに進むにてログインした場合にエラーになる

### ISSUE THREAD

**Issue by Mi-Hiroki** [EC-CUBE/ec-cube#5863]
## 概要(Overview)
https://example.com/ec-cube のように下層ディレクトリにec-cubeを設置すると、
未ログイン会員がカート→レジに進むからログインを行うと
「ページがみつかりません。」のエラー表示になる

## 期待する内容(Expect)  or 要望 (Requirement)
https://example.com/ec-cube のように下層ディレクトリにec-cubeを設置した場合も、
「ページがみつかりません。」の表示ではなく通常通りログインでき、
「ご注文手続き」画面が表示される。

## 再現手順(Procedure)
1. 未ログイン会員が商品をカートに追加
2. カート画面へ遷移
3. レジに進むボタンを押下してログイン画面へ遷移
4. ログイン情報を入力してログインボタンを押下
5. 「ページがみつかりません。」のエラー表示される

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4.27
+ DB:
  - PostgreSQL 9.2.24

## 関連情報 (Ref)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27148&forum=10&post_id=107368

**Comment by chihiro-adachi** [comment]
@Mi-Hiroki 
ご報告ありがとうございます。再現確認しました。
path関数ではなくurl関数使えば解消できそうです。
https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Resource/template/default/Shopping/login.twig#L28

**Comment by chihiro-adachi** [comment]
下層ディレクトリに配置した場合のテストは不足しがちなので、E2Eで自動化できるとよいですね。

**Comment by Mi-Hiroki** [comment]
@chihiro-adachi 
修正してPRをしておきました。

**Comment by chihiro-adachi** [comment]
#5890 で対応
