### ISSUE TITLE
特定のメールアドレスを会員登録拒否したい

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5868]
## 概要(Overview)
特定のメールアドレスを会員登録拒否させる方法が知りたいという問い合わせがありました。

## 期待する内容(Expect)  or 要望 (Requirement)
スパムアカウントが登録するのを止められる方法があれば幸いです。

**Comment by nanasess** [comment]
該当のメールアドレスを使用して、管理画面からダミーの会員登録をしておけば、同じメールアドレスで登録できなくなりますね。
ドメインごと拒否するとか、拡張メールアドレスも拒否対象とする場合は機能開発が必要です

**Comment by chihiro-adachi** [comment]
こちらはクローズさせていただきます。
機能要望ありましたらReOpenお願いします。

**Comment by Mi-Hiroki** [comment]
@fujisaki55 
@chihiro-adachi 
特定のメールアドレスの会員登録を拒否するプラグインをリリースさせて頂きました。
https://www.ec-cube.net/products/detail.php?product_id=2684
https://www.ec-cube.net/products/detail.php?product_id=2685
