### ISSUE TITLE
Formの拡張を行いやすいようにする

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#587]
現状のFrom関係のPluginではViewを書き換える必要があります。
``Form/form_layout.twig`` やForm関連をリファクタリングすることで、Templateを変更せずにFormへの入力欄追加が可能になります。

```twig
{{ form_rest(form) }}
```

**Comment by nobuhiko** [comment]
これって結局どうなったんでしょうか？
特に管理画面はこれで統一してくれるといいんですが・・

**Comment by Yangsin** [comment]
既存のプラグインへの影響もなさそうですし、管理画面は全フォームにいれていきたいですね。
 プラグインによるフォームの拡張はこれを利用するなどにするとできるだけシンプルになりそうな気がしますね。

**Comment by nanasess** [comment]
#1381 で対応済み
