### ISSUE TITLE
Install 用の phar を用意する

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#588]
現状、 `tar.gz` もしくは `zip` をダウンロードしてインストールする必要がありますが、pharにすることで、以下のフローでインストールできます。
1. `ec-cube.phar` をダウンロード
2. インストールしたいディレクトリにアップロード
3. ブラウザから `ec-cube.phar` にアクセス

**Comment by ttsuru** [comment]
参考ソース

PHP - pharでWebアプリを作ってみた - Qiita
http://qiita.com/rana_kualu/items/e437fff6f558c053cc41

**Comment by Yangsin** [comment]
FTPしか使えないレンタルサーバーなどでは、多くのファイルをアップロードするのが大変だったりしますが、これによりかなり楽になりますでしょうか？

**Comment by ttsuru** [comment]
現状、テストをしている感じでは楽になると思います。解凍やPermissionの設定も初めにする必要がなく、pharを拡張子phpにしてブラウザからアクセスすればよさそうです。

**Comment by ttsuru** [comment]
#591

**Comment by ttsuru** [comment]
@Yangsin 
こちら、 #591 にコメントさせていただきましたが、対応してみました。
ファイルのアップが相当簡単になるかと思います。
