### ISSUE TITLE
メール文面の多言語対応

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#5884]
## 概要(Overview)
- メールの文面が日本語にしか対応していない

## 期待する内容(Expect)  or 要望 (Requirement)
- `ECCUBE_LOCALE=en` を使用した場合は、メール文面も英語で表示される

## 再現手順(Procedure)
1. 環境変数 `ECCUBE_LOCALE=en`  を設定する
2. 商品購入や、お問い合わせフォームの送信をしてメールの送信をする

### 環境 (environment)
+ EC-CUBE: 4.20

## 関連情報 (Ref)
- #4600

**Comment by chihiro-adachi** [comment]
- 言語ファイルへ切り出す場合、メールの文面の保守性が大きくさがる
- テンプレート自体を切り替えるほうが望ましいかもしれない
..etc 検討事項や改修範囲は大きくなりそうで、結局直接ベタで文面を編集いただくほうが簡単そうです。

いったんクローズさせていただきます。
要望ありましたらReOpenいただければと思います。
