### ISSUE TITLE
symfony/password-hasherでの互換性に関する問題

### ISSUE THREAD

**Issue by luolongfei** [EC-CUBE/ec-cube#5891]
## 概要(Overview)

私のphpのバージョンは8.1.13です。composer update を実行すると、ec-cube が依存する symfony/password-hasher パッケージのバージョンが 6.2 に更新されました。そして、symfony/password-hasher パッケージは symfony 6.2 をベースに開発されていることがわかりました。しかし、現在の ec-cube は symfony5.4 をベースに開発されているため、互換性がありません。

## 期待する内容(Expect)  or 要望 (Requirement)

「composer update」を実行した後、symfony/password-hasherパッケージのバージョンが6.2にアップデートされました。これにより、現在のec-cubeに対応していないため、管理側にログインできなくなりました。これは、パスワード処理に関連するライブラリとの互換性の問題です。symfony/password-hasherパッケージのバージョンを現在のec-cubeと互換性があるように制限することを楽しみにしています。

## 再現手順(Procedure)

1. 最新の ec-cube 4.2.0 コードを入手します。
2. composer.json が配置されているディレクトリで、「composer update」を実行します。
3. 管理ページにアクセスしてログインを試みると、エラーが直接表示され、ログに「No password hasher has been configured for account \"管理者\"」と表示されます。
4. 次に、デバッグを行い、symfony/password-hasher パッケージに問題があることが判明しました。

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 8.1.13
+ DB:
  - MySQL 5.7.40

## 関連情報 (Ref)

いいえ

**Comment by chihiro-adachi** [comment]
@luolongfei 
ご報告ありがとうございます！

**Comment by chihiro-adachi** [comment]
@luolongfei 
手元で試しましたが再現しませんでした。
ec-cubeはダウンロード版のパッケージを使ってますでしょうか？

**Comment by luolongfei** [comment]
@chihiro-adachi 

お返事が大変遅くなり申し訳ありません。 

私は Composer を使って ec-cube 4.2.0 をインストールしました。実行したインストールコマンドは「composer create-project --no-scripts ec-cube/ec-cube ec-cube "4.2.0" --keep-vcs」です。インストールが完了した後、プロジェクトのルートディレクトリ下の composer.json の config.platform.php の値を 7.4.0 から 8.1.13 に変更しました。その後、「composer update」を実行しました。その結果、symfony/password-hasher のバージョンが 6.x に変わり、現在の ec-cube と互換性がなくなりました。

今日も何度も試行錯誤を繰り返し、ようやく問題を100％再現できるステップにたどり着きました。 時間を節約し、問題の再現を容易にするために、私はすべてのコードと環境を1つのファイルにパッケージしました。 ダウンロードアドレスは、https://drive.google.com/file/d/1mty81Ye8BZ7TTFDVUiDX799-yNwWH3ll/view?usp=sharing。

ダウンロードして解凍すると、ルートディレクトリにdocker-compose.ymlファイルがあるので、このファイルと同じディレクトリで「docker compose up --build -d」を実行すると、私の環境と全く同じ環境が起動します。 そして、このURLにアクセスします。http://localhost:9081/admin/login 、ランダムなアカウントとパスワードを入力し、ログインをクリックすると、エラーが表示されます。 すると、site-2022-12-15.log ファイルに、「No password hasher has been configured for account」関連のエラーメッセージが表示されます。

お手数をおかけしますが、この問題をもう一度調査していただけますか？

**Comment by luolongfei** [comment]
![image](https://user-images.githubusercontent.com/34597923/207833208-6e007862-bc0b-4fe2-8b54-06547e6ea2b4.png)

**Comment by nanasess** [comment]
config.platform.php の値を `8.1` 以上にして `composer update` を実行すると、 composer.json に記載されていない依存する `symfony/*` のパッケージが 6.0 以上に更新されてしまうようです。
composer.json に記載されていない依存する symfony のパッケージも composer.json に記載し、 `^5.4` を指定しておくことで防止できると思います

**Comment by luolongfei** [comment]
@nanasess ご返信ありがとうございます。再度確認させていただきます。

**Comment by luolongfei** [comment]
@nanasess @chihiro-adachi 

`symfony/security-bundle`コンポーネントと`symfony/security-core`コンポーネントが`symfony/password-hasher`コンポーネントに依存しているようです。現在の`composer.json`ファイルでは、`symfony/security-bundle`のバージョンは`^5.4`です。`composer why symfony/password-hasher`コマンドを実行すると、`symfony/password-hasher`のバージョンが`^5.3|^6.0`であることが分かります。PHPバージョンを8.1以上に設定し、`composer update`を実行すると、composerが自動的に`symfony/password-hasher`コンポーネントを`6.x`バージョンに更新します。

`composer.json`ファイルで`symfony/password-hasher`のバージョンを`^5.3`に指定し、`composer update`を実行すると、`symfony/password-hasher`のバージョンが再び`5.4.x`に戻ることが分かります。

そのため、結論として、`composer.json` ファイルで `symfony/password-hasher` コンポーネントのバージョンを手動で指定することで問題を解決できます。問題の原因は、`symfony` 内部である程度広いバージョンの要件がある一部のコンポーネントがあり、`ec-cube` 側では、より高いバージョンのいくつかのコンポーネントをサポートすることができていないようです。おそらく `ec-cube` の `composer.json` ファイルでは、`symfony/password-hasher` などのようなコンポーネントのバージョン制限をもっと行う必要があるでしょうか？

![image](https://user-images.githubusercontent.com/34597923/208016688-335d8cf0-af93-4caa-ba0f-6ed2f535982a.png)

**Comment by chihiro-adachi** [comment]
#5899 で対応しました。

**Comment by luolongfei** [comment]
ありがとうございます。
