### ISSUE TITLE
Plugin uninstall successfully but still show error

### ISSUE THREAD

**Issue by bocanhcam** [EC-CUBE/ec-cube#5893]
I try to uninstall my own plugin on the admin dashboard.

it shows an error but it still deleted that plugin successfully.

the error in the log file shows: 

```
 ["File mapping drivers must have a valid directory path, however the given path [/var/www/html/app/MyPlugin/Entity] seems to be incorrect!","/var/www/html/vendor/doctrine/persistence/src/Persistence/Mapping/MappingException.php",63
```

Before deleting my plugin I checked the folder Entity and the entity file and it still exists. I don't know why it shows the error of an invalid path. Does anybody know why and how to fix it?

By the way. This only happens on my production server. in my localhost, everything seems to be ok.

I had tried to ```clear:cache --no-warmup ``` or even delete the var/cache folder but still nothing changed

+ EC-CUBE: 4.2
+ PHP: 7.4.30
+ DB:
  - MySQL 5.7

**Comment by chihiro-adachi** [comment]
@bocanhcam 
Please ask the issue on this site. 
https://xoops.ec-cube.net/
