### ISSUE TITLE
Unknown　integer　エラー

### ISSUE THREAD

**Issue by 1000x** [EC-CUBE/ec-cube#5894]
## 概要(Overview)
商品一覧ボタンを押すと、システムエラーになりました。
エラーログを一部抜粋。

search_items.twig該当ソースに、is integer の条件がありました。直接原因か

    [2022-12-15T15:48:06.467299+09:00] admin.ERROR [64a540ac] [14556c8] [1] [Eccube\Log\Logger:log:64] - システムエラーが発生しました。
     ["Unknown \"integer\" test.","src/Eccube/Resource/template/admin/search_items.twig",41,"#0
      vendor/twig/twig/src/ExpressionParser.php(694): Twig\\ExpressionParser->getTest(41)\n#1 
      vendor/twig/twig/src/ExpressionParser.php(79): 

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4.33
+ DB:
  - MySQL 5.7

**Comment by takeuji** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5752/commits/6cde478c128b6ba19312d619cf6720a297fbfb29 こちらを取り込んでみてください

**Comment by chihiro-adachi** [comment]
@takeuji
フォローありがとうございます。

@1000x 
> https://github.com/EC-CUBE/ec-cube/commit/6cde478c128b6ba19312d619cf6720a297fbfb29 こちらを取り込んでみてください

こちらお試しください。
