### ISSUE TITLE
プラグイン雛形コマンドを実行すると存在しない名前空間を読み込んでいる。

### ISSUE THREAD

**Issue by teratai3** [EC-CUBE/ec-cube#5895]
## 概要(Overview)
プラグイン雛形コマンドを実行すると存在しない名前空間を読み込んでいる。

## 再現手順(Procedure)
「bin/console eccube:plugin:generate」する

ConfigRepository.php
use Symfony\Bridge\Doctrine\RegistryInterface;

### 環境 (environment)
EC-CUBE: 4.2.0

## 関連情報 (Ref)
4.2から内部のsymfonyのバージョンが上がったため、そのままだと使えない気がします。
なので毎回別名をつけてやってます。
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

**Comment by chihiro-adachi** [comment]
@Tera112300 
こちらのPRで修正されていますので、4.2.1で修正されます。
https://github.com/EC-CUBE/ec-cube/pull/5839
