### ISSUE TITLE
初期状態だとオーナーズストアから他のプラグインをインストールできない

### ISSUE THREAD

**Issue by teratai3** [EC-CUBE/ec-cube#5896]
## 概要(Overview)
初期状態だとオーナーズストアから他のプラグインをインストールできない
エラーが起きる

## 再現手順(Procedure)
githubからでなく公式サイトからダウンロードしてきたeccubeをインストールすると、
EC-CUBE Web API プラグインがComposerエラーを起こして、オーナーズストアから他のプラグインをインストールできないバグが存在する気がします。

### 環境 (environment)
EC-CUBE: 4.2.0

## 関連情報 (Ref)
圧縮したプラグインをアップロードする分には正常にインストールできる。
EC-CUBE Web API プラグインを削除するとオーナーズストアからインストールできました。
EC-CUBEは最近触り始めたので、もしかしたら違うかもしれません。

**Comment by chihiro-adachi** [comment]
@Tera112300 
エラーの詳細や環境情報などいただくことはできますでしょうか？

こちらの事象と同じかどうかも見ていただけると幸いです。
https://github.com/EC-CUBE/ec-cube/issues/5851

**Comment by teratai3** [comment]
@chihiro-adachi 
すでに問題として上がっていたんですね...失礼しました。
こちらと同じ事象になります。

**Comment by chihiro-adachi** [comment]
ご確認ありがとうございます。
こちらはクローズさせていただきます。
