### ISSUE TITLE
テストの対象範囲について

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#59]
βリリースまでは、開発スピードを重視し、以下をテスト基準にしようと思いますが、いかがでしょうか？

特に、src\Eccube\Service\は、ビジネスロジックがほぼすべて集約されるため、最重要と考えています。
そのため、src\Eccube\Service\以下は、カバレッジ100%にしていきたいです。

* 疎通確認（Routing）テスト
  + 全正常系/異常系を網羅
* src\Eccube\Service\に属するClassの単体・機能テスト
  + 単体テスト100%
  + 機能テスト100%
* src\Eccube\Form\Type\に属するClassの機能テスト
  + Validationチェック
* src\Eccube\Plugin\に属するClassの単体・機能テスト
  + Plugin詳細が決まり次第

上記に含まれていない、
* src\Eccube\Controller\
  + ビジネスロジックを持たせないように作成していくため
* src\Eccube\View\
  + カスタマイズ前提で、テストされている意味が薄いため
以上を理由に、テストをマストにしていません。

βリリース以降では、上で挙げたもの以外も対象にしていきたいと思います。

:+1: や :-1:  だけでもコメントいただけると判断しやすいです。

**Comment by Yangsin** [comment]
Wikiに[テストポリシー](https://github.com/EC-CUBE/ec-cube/wiki/%E3%83%86%E3%82%B9%E3%83%88%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC)としてまとめましたのでクローズします。
