### ISSUE TITLE
apc環境下で同一サーバにEC-CUBEを複数インストールした場合に別の環境を見てしまう。

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#590]
ApcClassLoader の引数が ``'autoloader.'`` に固定されているため。
今後サポートが必要になる可能性が大きい。

Symfony などではデフォルトではコメントアウトされています。

**Comment by aminotsukasa** [comment]
一度リアルにはまったことがあります。

手元にあったのでDrupalの該当箇所を見てみると
new ApcClassLoader(sha1(__FILE__),$loader);
になってました。

ファイル名が同じでディレクトリが違うケースに対応するなら、
new ApcClassLoader(sha1(__DIR__.__FILE__),$loader);
とかでしょうか?

**Comment by nanasess** [comment]
#1326 で対応いただきましたのでクローズします。
