### ISSUE TITLE
拡張したエンティティの項目に標準のスタイルが当たらない

### ISSUE THREAD

**Issue by sf-kataoka** [EC-CUBE/ec-cube#5904]
## 概要(Overview)
エンティティの拡張を行って、フロントに自動で表示させると、標準の項目のスタイルが当たりません。
![image](https://user-images.githubusercontent.com/119290083/210909236-cbb3abb8-4236-4a1c-b876-de361aed2236.png)

## 期待する内容(Expect)  or 要望 (Requirement)
EntityやFormTypeでスタイルを定義せずとも、標準のスタイルがtwig側で定義済みで適用されるとよいです。

## 再現手順(Procedure)
Entityを拡張して(スタイルをアノテーションに記載せず)、フロントの新規会員登録等を表示させます。

### 環境 (environment)
+ EC-CUBE: 4.2

**Comment by chihiro-adachi** [comment]
@sf-kataoka 
ありがとうございます。修正確認しました。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5905 で対応
