### ISSUE TITLE
管理画面：受注一覧の一括操作の「対応状況の変更」の挙動が一部おかしい（システムエラー発生）

### ISSUE THREAD

**Issue by sf-kataoka** [EC-CUBE/ec-cube#5906]
## 概要(Overview)
受注一覧の一括操作の「対応状況の変更」を選択せずにそのまま決定ボタンを押して表示された「対応状況を選択してください」のポップアップでOKを押すとメール文面が空のメール送信のポップアップが表示される。
![image](https://user-images.githubusercontent.com/119290083/210915495-05c61445-6875-4ff4-a353-98c9e219252f.png)

右下の青ボタンをクリックするとシステムエラーが発生する。
![image](https://user-images.githubusercontent.com/119290083/210915606-9b4e661d-add5-4a60-a290-739fb28effae.png)

## 期待する内容(Expect)  or 要望 (Requirement)
「対応状況を選択してください」でOKを押すとメール送信のポップアップが立ち上がることなく
そのまま受注一覧に戻るのが望ましいかと思います。

## 再現手順(Procedure)
受注一覧で注文を選択して、一括操作部分を表示させ、「対応状況の変更」を選択せずそのまま「決定」ボタンを押す
![image](https://user-images.githubusercontent.com/119290083/210916069-96ea73d2-32ee-495d-a919-b3369aae54de.png)

「対応状況を選択してください」のポップアップでOKをクリックするとメール送信のポップアップが表示される。
![image](https://user-images.githubusercontent.com/119290083/210916300-17324a2d-ad98-4f1f-bb46-5fe948eeb86d.png)

メール送信のポップアップの青ボタン部分をクリックする。
![image](https://user-images.githubusercontent.com/119290083/210916408-a4616d3e-635b-4bed-b2ff-a7d8fdaabb0e.png)

### 環境 (environment)
+ EC-CUBE: 4.2

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5911 で対応
