### ISSUE TITLE
管理画面：受注対応状況設定の左右に余白がある

### ISSUE THREAD

**Issue by sf-kataoka** [EC-CUBE/ec-cube#5907]
## 概要(Overview)
対応状況表の左右に余白がある
![image](https://user-images.githubusercontent.com/119290083/210920479-27aae9e7-d062-4584-b4fa-ce4db67651ac.png)

## 期待する内容(Expect)  or 要望 (Requirement)
税率設定に合わせたい。
![image](https://user-images.githubusercontent.com/119290083/210920571-9e3cc62a-0440-427a-a3e6-a41ecf3d3b71.png)

## 再現手順(Procedure)
設定＞店舗設定＞受注対応状況設定を表示する。

### 環境 (environment)
+ EC-CUBE: 4.2

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5908 で対応
