### ISSUE TITLE
管理画面：定休日カレンダー設定の表のthが足りないため、一部白くなっている

### ISSUE THREAD

**Issue by sf-kataoka** [EC-CUBE/ec-cube#5909]
## 概要(Overview)
管理画面の定休日カレンダー設定表の見出し項目の一部が白くなっている。
![image](https://user-images.githubusercontent.com/119290083/210945404-995e75d8-5018-4d98-94e8-f64e0a97986e.png)

## 期待する内容(Expect)  or 要望 (Requirement)
thタグが1行足りないため、追加して他と同じ色になるようにするのが望ましい。

## 再現手順(Procedure)
設定＞店舗設定＞定休日カレンダー設定を開く

### 環境 (environment)
+ EC-CUBE: 4.2

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5910 で対応
