### ISSUE TITLE
Composer でインストール

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#591]
開発者が直接サーバにEC-CUBEをインストール / バージョンアップする場合にもっと簡単にしたいと思います。

インストールであれば以下を実行

```
$ composer create-project ec-cube/install __DIR__ --prefer-dist
```

プラグインのインストールであれば以下を実行

```
$ composer require example/plugin_name:*
```

これだけで終わりにしたいですよね。僕はしたいです。

プラグインのインストールについてはもちろん、株式会社ロックオンさんのプラグインストアへの対応はすぐには難しいと思いますが、将来的には擦り合わせて実装できればと思います。
このインストール方法は技術者向けのオプションとして実装したいと思いますが、いかがでしょうか。

**Comment by ttsuru** [comment]
プラグインは https://getcomposer.org/doc/articles/custom-installers.md このドキュメントをベースに実装できると思います。

**Comment by ttsuru** [comment]
プラグインの composer 経由でのインストールに対応してみました。
#589 が取り込まれたら使えると思います。
サンプルプラグインが以下のコマンドでインストールできます。
```
$ composer require ec-cube-plugin/sample_entity:@dev
$ composer require ec-cube-plugin/sample_event:@dev
$ composer require ec-cube-plugin/sample_form:@dev
$ composer require ec-cube-plugin/sample_service:@dev
```

**Comment by ttsuru** [comment]
こちら、現状まだ実装はできていませんが、EC-CUBE本体は以下でforkして、Composer経由での導入に対応中です。
https://github.com/ttsuru/ec-cube/tree/composer_install

また、EC-CUBEのインストールは以下で可能になります。
```
$ composer create-project ec-cube/installer <DIRECOTRY> --prefer-dist
```

**Comment by ttsuru** [comment]
Packagist はこちらです。
https://packagist.org/packages/ec-cube/installer

エンジニアにとって一番簡単なEC-CUBEのインストール方法になると思います。
こちらをもとに phar 版もつくっていきたいと思っています。


## phar 版のイメージ

1. ec-cube.phar をダウンロード
2. インストールしたいディレクトリにアップ
3. ブラウザから http://example.com/ec-cube.phar にアクセス
4. インストーラが起動
5. インストール完了

アップデートは ec-cube.phar の差し替えだけでいけます。

こちらもロックオンさんに導入をぜひ促して行きたいです。
こんな感じで皆様いかがでしょうか。

**Comment by nanasess** [comment]
素晴しいと思います。

ただ、 EC-CUBE をダウンロードして、アーカイブを展開すること自体は大して難易度は高くありませんが、動作させるための Webサーバーとデータベースを構築するのが、そこそこ大変です。
(デザイナーさんや初心者の方は特に)

Windows 環境でしたら、 WebMatrix を使えば簡単に環境構築できますが、 Mac では VirtualBox + Vagrant や、 MAMP 等の選択肢しかなく、初心者の方にはかなり敷居が高いです。

PHPの ビルトインウェブサーバーで動くようになれば、完璧ですよねぇ。。。

**Comment by ttsuru** [comment]
@nanasess 
とりあえず、むちゃくちゃ簡単ですが、vendor以下に ec-cube/ec-cube を移動して、vendor.phar に固めることに対応してみました。

**Comment by ttsuru** [comment]
本件、 #588 の phar化とほぼ同等です。
まずは EC-CUBE を vendor/ec-cube/ec-cube 以下に入れても動作するようにロジックを改修します。
その後、 vendor 以下を pharとして固めることで、対応しました。

本件、採用ができれば、バージョンアップ作業が、vendor.phar を差し替えるだけで完了するようになると思います。

以下で動作するようにロジックを変更します。
```
{
    "require": {
        "ec-cube/ec-cube": "~3"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

ディレクトリイメージ
```
+ app
+ + app以下は通常
+ html
+ + html以下は通常
+ vendor.phar
```

**Comment by ttsuru** [comment]
こちら、 path.yml から不要な設定を削除するだけでほぼ完成しそうです。

**Comment by ttsuru** [comment]
以下のリポジトリにpushしました。
ぜひご意見をいただけますでしょうか。
https://github.com/ttsuru/ec-cube-composer

**Comment by ttsuru** [comment]
Pharを試してみた感じをまとめました。

デメリット
・メモリを食う
・若干遅い

メリット
・ファイルアップロードが簡単
・アップデートが簡単

**Comment by nanasess** [comment]
とても素晴しいと思います。
ただ、現状のプラグインの自由度や、(本体に触らない)カスタマイズの自由度の低さを考えると、時期早々ではないかなというのが個人的な感触です。

**Comment by ttsuru** [comment]
@nanasess 
内容をご覧いただいていますでしょうか。
プラグインの自由度とはなにをさしていますでしょうか。
app以下とhtml以下はそのままですし、プラグインやテンプレートの挙動は今までと一切変わらず動作します。
また、本体に触らないカスタマイズとありますが、何を指しているかがわかりません・・・

現状の挙動を変えずに vendor 以下に src を移動してpharに固めただけのものです。

**Comment by nanasess** [comment]
@ttsuru 別のチケットでも書きましたが、現在の Service クラス(Repository も含む)は、単一のプラグインから継承して DI のインスタンスを入れ替える、といったことしかできない認識です。
Service クラスや Repository クラスで複数のプラグインを扱おうとすると、src 以下に手をいれなくてはいけないような現状なので、 Phar にするメリットが少なくなってしまう(逆に工数が増えかねない)のではないかと思っています。
(認識が間違っておりましたらご指摘ください)

ちなみに Phar にするのに反対しているわけではありません。むしろ、将来的には正しい方向だと思います。

**Comment by ttsuru** [comment]
@nanasess 
そもそもPHARはそういった開発をされない方向けなのではないでしょうか。
エンジニアであればcomposerでインストールすればいいと思います。

また、EC-CUBE3は本体に手を入れることなく、運用していくポリシーになっているかと思います。
そういった意味からもエンジニア向けのcomposerでの導入と、一般ユーザー向けに簡単に導入ができるpharの二本立てがわかりやすいと思います。

特にバージョンアップに関してはpharであれば非常に大きいメリットがあると思います。

**Comment by ttsuru** [comment]
DIのインスタンスを入れ替えるのは別の問題で、pharだからかといったこととは関係ないかと思います。
本体に手を入れたいのであればcomposerでの導入でよいのではないでしょうか。

**Comment by nobuhiko** [comment]
vendorだけpharになっているととても便利だと思います

**Comment by ttsuru** [comment]
ちなみに、 Composer 版のメリットですが、技術者にとってバージョンアップがしやすいことです。

```
{
    "require": {
        "ec-cube/ec-cube": "3.0.4"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

としてインストールしたEC-CUBE 3.0.4 を 3.0.5 にあげる場合には

```
{
    "require": {
        "ec-cube/ec-cube": "3.0.5"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

として、

```
$ composer update
```

これだけになります。

**Comment by ttsuru** [comment]
こちら、もう一つ Composer のメリットとして、複数バージョンのEC-CUBEでのプラグインのテストが容易になることだと思います。

**Comment by Yangsin** [comment]
こちらありがとうございます。
大きな方向性、可能性としては継続して検討できればと思いますが
現在、EC-CUBE3.0として、品質や安定性というところを最もプライオリティー高く置いています。
その中で、まだ、アップデートの手順やポリシーが定めきれていない、EC-CUBEのユーザー層として多くをしめるレンタルサーバーでの挙動における課題などが残っています。

その中でインストールの手法などの多様化や、ディレクトリ構造を大きく変更するようなものやソフトウェアとしての根幹の設計に関するものを取り入れることは難しいと判断します。

大きな方向性、可能性としては、開発者以外の方にいかに安心して利用してもらえるのか、Composerなどとても触れないような方も、支障なく利用していける、対応できるアプローチで、引き続き検討し、3.x で対応というくらいで考えてます。

**Comment by ttsuru** [comment]
@Yangsin 
品質という面からも、Composerでのインストールはぜひ対応すべきではないでしょうか。
現状、各バージョンのインストールをするためには、バッチでの対応は難しくなっています。

Composerでの導入ができれば、簡単にプラグインのテストができます。
また、phpunitとの互換性も非常によくなると思います。

実際に、ソースコードの差分は30行程度ですし、今後、Composerに対応できなくなる前に、今のうちに対応すべきかと思います。
今、対応しておかないと、今後どんどん互換性を保つことが難しくなると思います。

**Comment by nanasess** [comment]
せめて、以下を対応してからでも遅くないと思います。

#558
#864

**Comment by ttsuru** [comment]
@nanasess
こちら、関係はあると思いますがcomposerに対応する際にも一部、 #864 を修正しました。
composer を後工程として考える必要はなく、並行して、対応していく課題かと思います。

とくに path.yml はcomposer対応とも強く関連しておりますが、それ以外でもデプロイの際に無駄に難易度を上げている項目かと思います。

**Comment by ttsuru** [comment]
#1543 にて対応してみました。
