### ISSUE TITLE
EC-CUBE4.2.0のソフトウェア要件（必須PHPライブラリ）などのドキュメントの修正

### ISSUE THREAD

**Issue by Mi-Hiroki** [EC-CUBE/ec-cube#5912]
## 概要(Overview)
EC-CUBE4.2.0からweb APIプラグインにより、PHP-sodium 拡張の影響によりオーナーズストア等からのプラグインインストールが出来ないという報告が多数挙がっている

## 期待する内容(Expect)  or 要望 (Requirement)
EC-CUBE4.2.0からweb APIプラグインにより、
PHP-sodium 拡張の影響によりオーナーズストア等からのプラグインインストールが出来ないという報告が多数挙がっているため、

- 開発情報サイト
https://www.ec-cube.net/developers/
へのソフトウェア要件（必須PHPライブラリ）へのPHP-sodium 拡張の追加
- EC-CUBE 4 開発者向けドキュメント
https://doc4.ec-cube.net/?_gl=1*1u00be6*_ga*OTY1OTk5MjA5LjE2NjIyNTM1MDI.*_ga_PBKHJT0C0B*MTY3MzE2MTQ0NC40OTkuMS4xNjczMTYyMTM3LjYwLjAuMA..
へのEC-CUBE4.2.x系ではPHP-sodium 拡張が必要の追加

※EC-CUBE4.2.1系以降からweb APIプラグインが影響がなくなるのであれば、注意事項として記載するなど

## 再現手順(Procedure)
EC-CUBE4.2.0をインストール後に、オーナーズストア等からのプラグインインストール時に発生

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/5851
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27093&forum=2&post_id=107086#forumpost107086
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27143&forum=1&post_id=107317#forumpost107317
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27189&forum=16&post_id=107573#forumpost107573
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27237&forum=16&post_id=107996#forumpost107996
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=27272&forum=10&post_id=108186#forumpost108186
など

**Comment by chihiro-adachi** [comment]
@nanasess 
Web-APIプラグインのsodium拡張の問題ですが、プラグイン側で対処することは可能でしょうか？
難しいようならシステム要件として追加する方向で検討できればと考えています。

**Comment by nanasess** [comment]
@chihiro-adachi APIプラグインが使用している Bundle が依存するライブラリですので、 Bundle 自体を使用しないようにすれば対処できると思いますが、現実的ではないと思います。

そもそも、PHP7.2以降で標準のPHPライブラリなので、それくらい入れてほしいんですけどね

**Comment by chihiro-adachi** [comment]
@nanasess 
ご確認ありがとうございます、承知しました。
システム要件に追加するよう対応進めたいと思います。

**Comment by chihiro-adachi** [comment]
@Mi-Hiroki 
もし可能でしたら doc4.ec-cube.netへpull requestいただけると大変ありがたいです。

**Comment by Mi-Hiroki** [comment]
@chihiro-adachi 
下記にて修正プルリクを作成致しました。
ご確認のほど、よろしくお願いいたします。
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/299

**Comment by naoki-shimo** [comment]
お話が進んでいる中恐縮ではありますが、システム要件の変更を行うよりはWebAPIプラグインを初期インストールのリストから外し、必要な方は別途任意にインストールするように変更を行った方がよいのではないでしょうか？
理由としましては
・sodiumに対応していないレンタルサーバで構築を行われている方が多数存在する事
システム要件を厳しくしてしまうと動作させることができるサーバにもより制約がかかってしまうのではないかと思います。
・所感としてWebAPI機能を利用されるケースが多くない事
WebAPI機能については必須機能という訳ではないと思いますので以前と同様に必要な方が任意にインストールできるようになっていれば問題ないのではないでしょうか？
・システム要件に記載したとしても今後も同様のトラブルが発生しそうな事
システム要件をあまり確認せず利用されている方も多いので同様のトラブルが今後も発生するのではないかという懸念があります。

仮にこの対応方法で進めるとなった場合は
システム要件としましては本体側の要件は現状のままとし、WebAPIプラグインの要件に追加するという事になろうかと思います。

よろしくお願いいたします。

**Comment by Mi-Hiroki** [comment]
@naoki-shimo 
EC-CUBE4.2.0およびEC-CUBE4.2.1（開発中）にて、
WebAPIプラグインが初期インストールから入っているのは変わらないので、
以降バージョンで初期インストールされていないことによるドキュメント上の相違もおかしいと思うので、
しっかりsodium拡張が必要と告知した方がよいと思います。

また、sodium拡張が入っていない入っているかは、EC-CUBEインストール画面で判定すれば良いと思います。

**Comment by chihiro-adachi** [comment]
@naoki-shimo 
ご提案ありがとうございます。

4.2.0および4.2.1では、WebAPIプラグインは初期インストールプラグインとして同梱されます。
@Mi-Hiroki のおっしゃるとおり、現時点では必須ライブラリとしてドキュメントには記載の方向で進めたいと思います。

初期インストールプラグインの対象から外すかどうかについては、次のバージョンで検討させていただきます。

**Comment by chihiro-adachi** [comment]
@naoki-shimo @Mi-Hiroki 

少し考え方整理しました。

sodium拡張は標準モジュールなので、本来であればレンタルサーバ側で対応していただくのが望ましいと考えてます(なかなか難しいだろうなとは思いつつ)。また、WebAPIプラグインを初期インストールの対象から外すことは現時点では考えていません。

根本の問題としては、システム要件外の環境にWebAPIプラグインがインストールされてしまうことではないかと思います。

Webインストーラで、システム要件を満たしていない場合APIにプラグインを除外するといったことは実装可能かと思いますので、後ほどPRあげられればと。

こちらは可能なかぎり4.2.1で取り込めるよう対応進めます。

**Comment by Mi-Hiroki** [comment]
@chihiro-adachi 
承知しました。
> Webインストーラで、システム要件を満たしていない場合APIにプラグインを除外するといったことは実装可能かと思いますので、後ほどPRあげられればと。

こちらになったら、以前アップしたドキュメントの内容を少し修正致しますのでよろしくお願いいたします。
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/299

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5934 にて、インストーラでの制御を行うように対応しました
