### ISSUE TITLE
管理画面：認証キーの新規発行時、captchaキーを入力後Enterでも新規発行できるようにしたい

### ISSUE THREAD

**Issue by cajiya-nakamura** [EC-CUBE/ec-cube#5913]
## 概要(Overview)

オーナーズストアの認証キー新規発行の画面で、captchaキーを入力した後に「認証キー新規発行」を押下すると、検証後に認証キーが取得＆保存される。
この認証キー取得時に、画像に表示されている文字を入力する手順がありますが、このテキストフィールドの段階で入力後にEnterを押すと、検証されず画面が再ロードされてしまいます。

## 期待する内容(Expect)  or 要望 (Requirement)

captchaキーを入力後Enterでも新規発行できるようにしたい

## 再現手順(Procedure)

認証キーの新規発行時、画像に表示されている文字を入力する段階で、
テキストフィールドがアクティブの状態でEnterを押す。

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4.33
+ DB:
  - MySQL 5.7.27

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5914 で対応
