### ISSUE TITLE
Dockerfile内のphp8.x対応

### ISSUE THREAD

**Issue by kawaway** [EC-CUBE/ec-cube#5919]
## 概要(Overview)
php 7.4がEOLを迎え、利用しているdocker image [php:7.4-apache-bullseye](https://github.com/EC-CUBE/ec-cube/blob/4.2/Dockerfile#L1-L2) の本家 https://github.com/docker-library/php からも7.4は既になくなっております。
github actons等ではphp 8系にてテストされているようですが、Dockefileを更新する予定はありますでしょうか?

## 期待する内容(Expect)  or 要望 (Requirement)
Dockerfile内で使用するphpのバージョンがEOFでないでないこと

### 環境 (environment)
+ EC-CUBE: 4.2.0
+ PHP: 7.4.33

**Comment by nanasess** [comment]
一応、 `docker pull php:7.4-apache-bullseye` は実行可能ですね

**Comment by kawaway** [comment]
確認ありがとうございます。
現在のところ docker pullは可能です。ただディストリビューションによるパッチバックポートもないため確認させていただきました。

**Comment by nanasess** [comment]
@kawaway 
あと、最新の 4.2 ブランチでよろしければ、以下にビルド済みのイメージがあります。
https://github.com/EC-CUBE/ec-cube/pkgs/container/ec-cube-php/63870242?tag=8.1-apache-4.2
https://github.com/EC-CUBE/ec-cube/pkgs/container/ec-cube-php/63870114?tag=8.0-apache-4.2

docker-compose.yml のデフォルト値が `8.1-apache` ですので、通常のユーザーは上記のイメージを使用されると思います。
https://github.com/EC-CUBE/ec-cube/blob/da5cf35155240fccf24e32f5910ea537f0ed7a74/docker-compose.yml#L25

EC-CUBE4.2.x の下限のサポートが PHP7.4 なので、個人的には Dockerfile のデフォルト値は現在のままで良いかなと思っています。
 `--build-arg TAG=8.1-apache` を指定して docker build すれば `php:8.1-apache` をベースイメージにしてビルドすることも可能です。
Dockerfile のデフォルト値を php:8.0-apache 以降にするかどうかは議論が必要そうです。

**Comment by kawaway** [comment]
@nanasess 

回答ありがとうございます。
docker-compose.yml を見落としておりました。
おっしゃる通り通常のユーザーが `8.1-apache` ためDockerfileは現状のままで良いと思い直しました。
ありがとうございました。
