### ISSUE TITLE
EC-CUBE3.0.1 標準テンプレートのbootstrapについて

### ISSUE THREAD

**Issue by TakaYasu1984** [EC-CUBE/ec-cube#592]
いつもお世話になっております。

EC-CUBE3.0.1の標準テンプレートで使用しているbootstrapについて
画面サイズを変更しているとグリッドが崩れてしまうようです。

[EC-CUBE3.0.1 標準テンプレートのbootstrap.custom.min.cssを使用]
![bug](https://cloud.githubusercontent.com/assets/13491552/8887487/c19b35e0-32be-11e5-807e-45d2b77a1db6.jpg)

[Bootstrap3.3.5 のbootstrap.min.cssを使用]
![ok](https://cloud.githubusercontent.com/assets/13491552/8887488/d16161e8-32be-11e5-8339-cf8560eee506.jpg)

**Comment by Yangsin** [comment]
EC-CUBEのBootstrapはv3.3.4 を利用しているのでもしかしたらその差かもしれません。

フロント自体はBootstrapによりすぎないようにしており、独自のコーディングですすめているので、標準で同梱されているBootstrap単体で取り出して利用することは想定されていませんが、具体的にどこか原因がわかりましたら、改めて追記いただけますと幸いです。

**Comment by Yangsin** [comment]
３系の開発は終了していますので、こちらもクローズします。
