### ISSUE TITLE
管理画面内の日付絞り込み時に、現在時刻を00:00など一意の値に制御したい

### ISSUE THREAD

**Issue by cajiya-nakamura** [EC-CUBE/ec-cube#5920]
## 概要(Overview)

日時絞り込み用のinputフォームですが、`input[type="datetime-local"]` の仕様で、入力UIが常に現在時刻からになります。

時刻よりも、日別のデータで絞り込みをするケースが一般的に多いと思われますが、
日付で絞り込みをするためには、毎回時刻を`00:00`や`23:59`にする必要があります。

![2023-01-26 10 38 28](https://user-images.githubusercontent.com/13391535/214736703-d12d5c07-964b-4a24-a611-4b5f9ca66d21.png)

## 期待する内容(Expect)  or 要望 (Requirement)

スムーズに日時（特に日にち）での絞り込みができるようにしたい。

### 環境 (environment)
+ EC-CUBE: 4.2.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5921 で対応
