### ISSUE TITLE
削除モーダルでダブルクリックで「ページがみつかりません。」画面に遷移する

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/ec-cube#5922]
## 概要(Overview)
店舗設定　＞ 支払方法一覧（配送方法一覧も同様）  で支払方法削除時のモーダルで「削除」ボタンをダブルクリックすると
[ページがみつかりません。]画面が表示される。

1度目のクリックで論理削除は成功しているが、2度目のクリックではNot Foundとなっている模様。

※ 会員一覧の削除（ダブルクリック）では、フラッシュメッセージ「既に削除されています」が表示される

## 期待する内容(Expect)  or 要望 (Requirement)
会員一覧同様、支払い方法一覧に「既に削除されています」が表示される事

## 再現手順(Procedure)
- 支払方法一覧（配送方法一覧）より×をクリック
- 削除モーダルで「削除」ボタンをダブルクリック

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
修正方法としては、削除ボタンにladda-buttonで二重クリック防止でもよいかと思われます。

**Comment by dotani1111** [comment]
PRがマージされた為、クローズ致します。
