### ISSUE TITLE
権限管理 拒否URLに全角文字が入力・登録できる

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/ec-cube#5923]
## 概要(Overview)
システム管理 > 権限管理 の 拒否URLに対して半角文字だけでなく全角文字が入力・登録可能である。

## 期待する内容(Expect)  or 要望 (Requirement)
全角文字はバリデーションで拒否する

## 再現手順(Procedure)
- システム管理 > 権限管理を表示
- 拒否URLに全角文字を含む文字列を入力
- 登録ボタンをクリック

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
URLでの文字種には特に制限はないこと、現状では全角文字を登録できても支障がないことから本Issueはクローズします。
