### ISSUE TITLE
セキュリティ管理　信頼できるホスト名欄に「必須」アイコンがない

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/ec-cube#5924]
## 概要(Overview)
システム管理 > セキュリティ管理 の 信頼できるホスト名は入力必須であるが、
「必須」アイコンが表示されていない。

## 期待する内容(Expect)  or 要望 (Requirement)
必須アイコンが表示されている

## 再現手順(Procedure)
- 特になし

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5925 で対応
