### ISSUE TITLE
4.2.1のapache bench結果(github actions)

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/ec-cube#5926]
## 計測環境
- github actionsで実行(https://github.com/sai-gillingham/ec-cube/actions/runs/4041842506/workflow)
- 計測条件は 4.2.0計測と同様(https://github.com/EC-CUBE/ec-cube/pull/5768)

## 前提条件
- 4.2.0：APP_ENV=prod、APP_DEBUG=0 / 初期インストールプラグインはすべて無効状態
- 4.2.1：APP_ENV=prod、APP_DEBUG=0 / 初期インストールプラグインはすべて無効状態
- 初期状態 -> EC-CUBEをインストール直後の状態
- 商品規格数：9万点 -> 商品数：1万 / 商品規格：3x3 / カテゴリ数：30件

## 計測結果
- apache benchで10回計測を実施したrequest per secondの平均値

#### トップページ
|db|4.2.0|4.2.1|
----|----|----| 
|pgsql|28.75|28.68|
|mysql|31.16|31.68|

#### 商品一覧
|db|4.2.0|4.2.1|
----|----|----| 
|pgsql|20.84|20.86|
|mysql|23.54|23.66|

#### トップページ
|db|4.2.0|4.2.1|
----|----|----| 
|pgsql|27.00|26.55|
|mysql|30.94|30.56|

#### 商品一覧
|db|4.2.0|4.2.1|
----|----|----| 
|pgsql|6.66|6.64|
|mysql|6.31|6.29|

**Comment by chihiro-adachi** [comment]
@KenTanaka 
ありがとうございます。
4.2.0と乖離はなしということでクローズします。
