### ISSUE TITLE
EC-CUBE4 ソフトイレースの使い方

### ISSUE THREAD

**Issue by tienhvmiichisoft** [EC-CUBE/ec-cube#5928]
## 概要(Overview)
- EC-CUBE4.1.2-p1インスタンスを使用していますが、管理画面でのデータ削除がリレーショナルデータに制約されています。
- これをサポートするプラグインはありますか?

## 期待する内容(Expect)  or 要望 (Requirement)
EC-CUBE3.0.14 インスタンスと同様に、データベースでは論理的な削除が使用されます。

### 環境 (environment)
+ EC-CUBE: 4.1.2-p1
+ PHP: 7.4.3
+ DB:
  - MySQL 5.7.40

**Comment by chihiro-adachi** [comment]
@tienhvmiichisoft 
4.0系から論理削除ではなく物理削除を行うようになりました。
https://github.com/EC-CUBE/ec-cube/pull/2512

外部キー制約によって紐付いているデータが有る場合、管理画面から削除できない場合があります。
