### ISSUE TITLE
基本設定のメール設定のラベル名が直感的でない

### ISSUE THREAD

**Issue by cajiya-nakamura** [EC-CUBE/ec-cube#5937]
## 概要(Overview)

EC-CUBEの基本設定内にある「送信元メールアドレス(From)」などの設定、ラベル名が直感的でないので修正したい。

## 期待する内容(Expect)  or 要望 (Requirement)

返信受付メールアドレス(ReplyTo)がfromで使われていたり、一部 bcc が設定されていない様です。
| 管理画面表示 | カラム名 |
| --- | --- |
| 送信元メールアドレス(From) | Email01 |
| 問い合わせ受付メールアドレス(From, ReplyTo) | Email02 |
| 返信受付メールアドレス(ReplyTo) | Email03 |
| 送信エラー受付メールアドレス(ReturnPath) | Email04 |

| メールの種類 | from | To | bcc | replyTo | returnPath |
| --- | --- | --- | --- | --- | --- |
| 仮会員登録メール送信完了 | Email01 | 登録者のEmail | Email01 | Email03 | Email04 |
| 会員登録完了メール送信完了 | Email01 | 登録者のEmail | Email01 | Email03 | Email04 |
| 退会手続き完了メール送信完了 | Email01 | 会員のEmail | Email01 | Email03 | Email04 |
| お問い合わせ受付メール送信完了 | Email02 | 問い合わせ者のEmail | Email02 | Email02 | Email04 |
| 受注メール送信完了 | Email01 | 注文者のEmail | Email01 | Email03 | Email04 |
| 仮会員登録再送メール送信完了 | Email03 | 会員のEmail | Email01 | Email03 | Email04 |
| 受注管理通知メール送信完了 | Email01 | 注文者のEmail | Email01 | Email03 | Email04 |
| パスワード再発行メール送信完了 | Email01 | 会員のEmail | 設定無し | Email03 | Email04 |
| パスワード変更完了メール送信完了 | Email01 | 会員のEmail | Email01 | Email03 | Email04 |
| 出荷通知メール送信処理完了 | Email01 | 注文者のEmail | Email01 | Email03 | Email04 |

２点、誤りかな？と思っているのは、
「仮会員登録再送メール送信完了」のfromに「返信受付メールアドレス(ReplyTo)」のEmail03が使われている点と、
「パスワード再発行メール送信完了」にbccが設定されていない点。どちらも「Email01」が正しいのではと推察したので、プルリクを送ります。

上記の修正で、以下ルールになります。

１． EC-CUBEから送信されるすべてのメールは、fromに設定されたアドレスをbccにも適用
２． 「Email01」は、EC-CUBEから送信される"お問い合わせ"を除く全てのメールの送信元
３． 「Email03」は、EC-CUBEから送信される"お問い合わせ"を除く全てのメールの返信先
４． 「Email04」は、EC-CUBEから送信される全てのメールのエラーメールが届く
５． お問い合わせフォームのみ特例で、送信元・返信先が「Email02」になる（ルール(1)に基づき bccもEmail02）

| メールの種類 | from | To | bcc | replyTo | returnPath |
| --- | --- | --- | --- | --- | --- |
| 仮会員登録メール送信完了 | Email01 | 登録者のEmail | Email01 | Email03 | Email04 |
| 会員登録完了メール送信完了 | Email01 | 登録者のEmail | Email01 | Email03 | Email04 |
| 退会手続き完了メール送信完了 | Email01 | 会員のEmail | Email01 | Email03 | Email04 |
| お問い合わせ受付メール送信完了 | Email02 | 問い合わせ者のEmail | Email02 | Email02 | Email04 |
| 受注メール送信完了 | Email01 | 注文者のEmail | Email01 | Email03 | Email04 |
| 仮会員登録再送メール送信完了 | Email01 | 会員のEmail | Email01 | Email03 | Email04 |
| 受注管理通知メール送信完了 | Email01 | 注文者のEmail | Email01 | Email03 | Email04 |
| パスワード再発行メール送信完了 | Email01 | 会員のEmail | Email01 | Email03 | Email04 |
| パスワード変更完了メール送信完了 | Email01 | 会員のEmail | Email01 | Email03 | Email04 |
| 出荷通知メール送信処理完了 | Email01 | 注文者のEmail | Email01 | Email03 | Email04 |

また、上記に合わせてラベル名と表示順を変更したいのですが、プルリク送っても問題ないでしょうか？
他に良いラベル名があれば、教えてほしいです。

| 管理画面表示 | カラム名 |
| --- | --- |
| 送信元メールアドレス(From) | Email01 |
| 返信先メールアドレス(ReplyTo) | Email03 |
| 送信エラー通知メールアドレス(ReturnPath) | Email04 |
| 問い合わせ専用メールアドレス(From, ReplyTo) | Email02 |

### 環境 (environment)
+ EC-CUBE: 4.0.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 脆弱性報告 (Vulnerability report)
脆弱性のご報告は弊社[問い合わせフォーム](https://www.ec-cube.net/contact/)からお願いします。

**Comment by chihiro-adachi** [comment]
@cajiya-nakamura 
ありがとうございます。
こちら提示いただいた内容で問題ないかと思います。

仕様変更となりますが、仮会員再送メールのfromが変更されてしまう点については、管理者が任意のタイミングで送信するメールであり、頻度としてもそれほど多くはないことから、影響としては軽微と考えています。

**Comment by chihiro-adachi** [comment]
@cajiya-nakamura 
ラベル変更についても問題ないかと思います。
PRいただけますと幸いです。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5938 で対応
