### ISSUE TITLE
fontawesomeの読み込み箇所にIntegrity属性を追加する

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5946]
### 概要(Overview)

fontawesomeの読み込み箇所にIntegrity属性を追加する

### 期待する内容(Expect) or 要望(Requirement)

以下の該当箇所に追加すること
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css">
```

**Comment by watarukashii** [comment]
@chihiro-adachi 
お世話になっております。下記issue と類似する内容かとおもいますが、合わせてご確認いただくことは可能でしょうか。
https://github.com/EC-CUBE/ec-cube/issues/5672

**Comment by chihiro-adachi** [comment]
@watarukashii 
https://github.com/EC-CUBE/ec-cube/issues/5672 は、Integrity属性とはまた別の内容になります。

コメント記載しておきました。
https://github.com/EC-CUBE/ec-cube/issues/5672#issuecomment-1449444875

**Comment by shinya** [comment]
こちらPRにてマージされたのでcloseしておきます。
（遅くなってすみません）
