### ISSUE TITLE
timezoneが設定されていないサーバーの場合インストールに失敗する。

### ISSUE THREAD

**Issue by konotakanobu** [EC-CUBE/ec-cube#595]
ルートディレクトに.htaccessなどを置いて対応したほうがよい？
それともtimezoneが設定されていることが前提、どちらで考えれば宜しいでしょうか？

.htaccess制御で対処する場合

下記を追加
php_value date.timezone Asia/Tokyo

【.htaccess制御範囲内のスクリプト全てに対して適用されます】

プログラム制御で対処する場合

下記を追加
date_default_timezone_set('Asia/Tokyo');

【記述を追加したスクリプトのみに対して適用されます】

**Comment by konotakanobu** [comment]
方針貰えればPRまでしておきます！

**Comment by Yangsin** [comment]
AWSやAzureなどのPaaSで利用することも考えると、アプリケーション側でタイムゾーンは調整可能な様にしておけるのが望ましいと思います。
Application.php あたりでやるのがいいのかな？

**Comment by aminotsukasa** [comment]
.htaccessは使えないサーバもあると思いますので、config.yml内の設定値をApplication.php、InstallApplication.php内でini_setがいいのではないかと思います。

**Comment by ttsuru** [comment]
@aminotsukasa :+1:

**Comment by nanasess** [comment]
> AWSやAzureなどのPaaSで利用することも考えると、アプリケーション側でタイムゾーンは調整可能な様にしておけるのが望ましいと思います。

#276 こちらの対応も必要です

**Comment by nanasess** [comment]
> .htaccessは使えないサーバもあると思いますので、

`.user.ini` を使うという手もあります。

**Comment by konotakanobu** [comment]
とりあえずコミットしちゃいましたが、方針としては

・タイムゾーンは調整可能な方が良い。
・config.yml内の設定値をApplication.php及びInstallApplication.phpでini_set

が良い感じですかね。
インストール時にコケるんですが、どのタイミングで設定させて、ini_setさせるべきですかね？
インストールのstep3で必ず選んでもらうようにしますか？

**Comment by aminotsukasa** [comment]
もしくは、Asia/Tokyo以外にしたい場合はインストール後手動でconfig.ymlを編集で対応してもらっても良いかと思いますので、
とりあえずデフォルトのタイムゾーンが設定されるように
src/Eccube/Resource/config/config.yml.dist
に timezone:Asia/Tokyo を追加するというのも手だと思います。

**Comment by nobuhiko** [comment]
パラメーター設定画面みたいなのはなくなったんですっけ？

**Comment by aminotsukasa** [comment]
今はないですね
確か2->3系の間に設定パラメータを見なおした時に設定変更の頻度が少ないパラメータをconfigファイルに切り出して画面も一旦廃止しています…

**Comment by Yangsin** [comment]
本件自体は、3.0.3修正がはいっており、す。
Timezoneの変更にどう対応するのかは議論が停止してますので一度Issueもクローズします。
