### ISSUE TITLE
会員一覧の最終購入日のPickerに日時がない

### ISSUE THREAD

**Issue by dotani1111** [EC-CUBE/ec-cube#5970]
### 概要(Overview)

会員一覧の最終購入日のPickerに日時項目がありません。
URL例：http://localhost:8080/admin/customer

<img width="643" alt="image" src="https://user-images.githubusercontent.com/121000728/229406075-5507dfc3-2515-406f-97c4-be833f16f13c.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/121000728/229406037-c10f6893-91c8-4707-b4d0-42300bee54b2.png">

それ以外のPickerでは、時間まで表示される
例：登録日
<img width="643" alt="image" src="https://user-images.githubusercontent.com/121000728/229406142-491c6194-c900-4d54-b1e9-ea4c5ff4c6e9.png">

### 再現手順(Procedure)

最終購入日をクリックする

### 環境(Environment)

EC-CUBE: 4系

**Comment by chihiro-adachi** [comment]
内部的な実装では、日付のみの指定で検索できるようになっているようです。
そこから推測すると、時刻指定ではなく、日付での検索を行うことが想定されるのではないかと思われます。
こちらに関しては、仕様ということで扱わせていただければと思います。
