### ISSUE TITLE
会員情報変更後のメッセージの誤り

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5972]
### 概要(Overview)

マイページから会員情報編集後、以下のように `メールアドレスとパスワードでログイン後、ショッピングをお楽しみください。`と表示されている。

<img width="763" alt="image" src="https://user-images.githubusercontent.com/8196725/229692660-3f96c9d7-2455-42a7-981d-eadee1c3612d.png">

https://github.com/EC-CUBE/ec-cube/pull/5869 の https://github.com/EC-CUBE/ec-cube/pull/5869/commits/1182ed8c9baaf9bf2e8c3b8f900265ac456fa681 で、会員登録完了画面でのメッセージを修正したつもりが、会員編集画面のメッセージを誤って修正した模様。

### 再現手順(Procedure)

- マイページへログイン
- 会員編集を実行する
- 完了画面で、`メールアドレスとパスワードでログイン後、ショッピングをお楽しみください。`が表示される

### 環境(Environment)

EC-CUBE: 4.2.1

**Comment by dotani1111** [comment]
Merge済みのためCloseします。
