### ISSUE TITLE
4.2.2リリース計画

### ISSUE THREAD

**Issue by xuelian311** [EC-CUBE/ec-cube#5984]
## 基本方針
マイナーバージョンとして以下の優先順位で開発を行います。

- 既存pull requestの取込
- セキュリティ強化につながる機能追加
- Bug middle以上の不具合修正

方針としては、既存プラグイン/デザインテンプレートとの互換性を最大限考慮します。

## 予定スケジュール

- 2023/6/5 ソースコード凍結
- 2023/6/28 リリース

## 対応内容

EC-CUBE4.2.2にて取り込む予定の改修一覧
https://github.com/EC-CUBE/ec-cube/milestone/50

マージ済みプルリクエスト一覧
https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+milestone%3A4.2.2+is%3Aclosed　

### その他 

- Issue および Pull requests のマイルストーンの設定は現時点での予定であり、変更となる可能性があります。
- Pull Request 未経験の方もぜひ開発にご協力ください。修正が容易と思われるものや、仕様が明確なものには、<a class="d-inline-block IssueLabel v-align-text-top" style="background-color: #5ae833; color: #000000" title="簡単に修正できそうなもの" href="https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue">🏷 good-first-issueラベル</a>をつけています。

## 互換性についての情報

マイナーバージョンの開発では互換性を維持するために、以下の観点でPullRequestをレビューしています。

#### 既存機能の仕様変更
[`affected:外部仕様` ラベル](https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Aaffected%3A%E5%A4%96%E9%83%A8%E4%BB%95%E6%A7%98+is%3Aclosed+milestone%3A4.2.1+is%3Amerged)をご確認ください

#### フックポイントの呼び出しタイミングの変更
変更はありません

#### フックポイントのパラメータの削除・データ型の変更
変更はありません

#### twigファイルに渡しているパラメータの削除・データ型の変更
変更はありません

#### Serviceクラスの公開関数の、引数の削除・データ型の変更
変更はありません

#### 入出力ファイル(CSVなど)のフォーマット変更
変更はありません

### 2023.06.09(金)
今週はセキュリティ面の機能追加として主に以下2点Pull Requestをマージしました。

#### ・会員による重要操作時のメール通知機能  #5989 
　会員情報の編集、お届け先の登録・編集・削除時にメールが送信されます。
　こちらの機能により、本人が編集したことを確認できるため、
　不正アクセスが行われた場合には速やかに対応することができます。

#### ・会員情報編集・お届け先編集時にスロットリングを追加  #5998 
　大量メールアタック防止のため、会員情報編集・お届け先編集機能にスロットリング機能を追加します。

来週はソースコード凍結後の結合テスト、セキュリティテストを中心に進める予定です。
皆さんからのテスト協力も求めています。
ぜひテストパッケージを動かしてみて頂き、フィードバックをお願いいたします！

### 2023.06.16(金)
今週はソースコード凍結後の結合テスト、セキュリティテストまで完遂できました。
バージョンアップに影響するようなバグは見つかっていませんが、
引き続き皆さんのテスト協力よろしくお願いいたします。

何名かのコミュニティの方から質問いただいてましたが、
テストにご協力いただき、バグのissueを上げてくださった方には
コミットポイントも差し上げております！

来週はリリースに向けたドキュメント整備や、アップデートプラグインの開発
などを中心に進めていきます。

### 2023.06.23(金)
今週は4.2.2のリリースに向けて、テスト結果のトリアージをメインに実施しました。
現状は、予定通り6月28日(水)に4.2.2のリリースを実施する予定です。
同日に、4.2.1→4.2.2のアップデートプラグインも提供されます。
重要操作時のメール通知機能に関する運用マニュアルも当日公開させていただきます。

**Comment by ji-eunsoo** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5998 の取り込みをもってコード凍結とさせていただきます。
PRいただいた皆様、誠にありがとうございました。

試験用のパッケージを以下で作成しています。
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.2-20230606
