### ISSUE TITLE
プラグインの code と name が異なる場合、エラーが発生。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#599]
code と name が異なり、orm.path が設定されている場合にエラーが発生する。
name のみだった時の名残がある。

**Comment by Yangsin** [comment]
#600  で対応頂いております。

**Comment by shhirose** [comment]
PR の時に Issue も上げるという記述はどこかにありませんでしたか？
ひとまず Close してしまいます。

**Comment by Yangsin** [comment]
IssueとPRが紐付いていなかったので紐付ける意図だけで、とくにIssueが不要という意図ではございませんでした。言葉が足りず失礼しました。

**Comment by Yangsin** [comment]
ただ、コメントいただいて気づいたんですが、SVNとTracでやってた時代とはちがって、PRに対してコメントできるので、PRがあるなら、Issueは無くてもよいかも。と思ったので、ルールは見直します。

**Comment by Yangsin** [comment]
対応マージ済みですので、こちらもクローズします。
