### ISSUE TITLE
feat:重要操作時のメールのスロットリング

### ISSUE THREAD

**Issue by dotani1111** [EC-CUBE/ec-cube#5996]
### 概要(Overview)

重要操作時のメール設定のIssueに関して、会員情報編集・住所変更時にメールが送信される仕様になる。
https://github.com/EC-CUBE/ec-cube/issues/5373

これに関して、スロットリングを追加が望ましい。

### 期待する内容(Expect) or 要望(Requirement)

以下を参考に、スロットリングの実装を会員情報編集・住所変更時に行う
https://github.com/EC-CUBE/ec-cube/pull/5881
https://doc4.ec-cube.net/customize_throttling

**Comment by dotani1111** [comment]
仕様としては以下になりました。

> 注文確認画面と同じ設定でお願いします。
> IPベース：25回/30分
> 会員ベース：10回/30分

**Comment by dotani1111** [comment]
仕様FIXです。
会員ベース：10回/30分

**Comment by ji-eunsoo** [comment]
こちら、PR取り込みとなったため、closedします。
