### ISSUE TITLE
デジタルコンテンツのダウンロード販売を標準機能として追加してほしい

### ISSUE THREAD

**Issue by nobitextcode** [EC-CUBE/ec-cube#5999]
### 概要(Overview)

標準機能としてダウンロード販売を追加してほしい。

### 期待する内容(Expect) or 要望(Requirement)

ファイルや動画などのデジタルコンテンツを購入後に、入金確認後にマイページからダウンロードできるようになる機能がほしい。
商品発送情報などは必要ないのでオフにする機能もほしい。
領収書もデジタルコンテンツ用にカスタマイズできるようにしてほしい。

**Comment by dotani1111** [comment]
@nobitextcode 
ありがとうございます👍 
同様のIssueがありますので、こちらはクローズさせて頂きます。
https://github.com/EC-CUBE/ec-cube/issues/4874

**Comment by dotani1111** [comment]
[](https://github.com/EC-CUBE/ec-cube/issues/4874)
