### ISSUE TITLE
GitHub Actionsの非推奨のUbuntuバージョンを更新

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#6006]
### 概要(Overview)

GitHubActionsのUbuntuのバージョンを18.04 -> 22.04へ更新する

### 再現手順(Procedure)

対象は以下の通り。

- https://github.com/EC-CUBE/ec-cube/blob/4.2/.github/workflows/penetration-test.yml#L13
- https://github.com/EC-CUBE/ec-cube/blob/4.2/.github/workflows/vaddy-1.yml#L9
- https://github.com/EC-CUBE/ec-cube/blob/4.2/.github/workflows/vaddy-2.yml#L9

### 環境(Environment)

EC-CUBE: 4.2

**Comment by shinya** [comment]
報告ありがとうございます 👍

**Comment by dotani1111** [comment]
PRマージ済みなので、Closeします。
