### ISSUE TITLE
「use.fontawesome.com」のcss読み込みでエラーとなりアイコンが表示されないことがある

### ISSUE THREAD

**Issue by ikeshima** [EC-CUBE/ec-cube#6010]
### 概要(Overview)

「use.fontawesome.com」のcss読み込みでエラーとなりアイコンが表示されないことがあります。
下記部分でエラーとなるようです。

`href="[https://use.fontawesome.com/releases/v5.3.1/css/all.css](view-source:https://use.fontawesome.com/releases/v5.3.1/css/all.css)"`

「ctrl+F5」を実行するとアイコンが読み込めることがあります。
開発者ツールでheader responseを確認すると、下記の状況となっていました。
◆エラー発生時
「Access-Control-Allow-Origin: *」が存在しない
◆エラー未発生時
「Access-Control-Allow-Origin: *」が存在する

エラーは下記の内容です。

`Access to CSS stylesheet at 'https://use.fontawesome.com/releases/v5.3.1/css/all.css' from origin 'https://xxxx.xxxxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

### 再現手順(Procedure)

フロント画面にアクセスすることで発生します。
EC-CUBE4.0.5への初回アクセスで問題を確認しました。
今後、下記についても現象を細かく確認する予定です。

１．「ctrl+F5」押下で問題解消後に再現するタイミング
２．EC-CUBE他バージョンでの発生状況

など

### 環境(Environment)

EC-CUBE：4.0.5
PHP：7.2.24
MySQL： 10.2.10-MariaDB - MariaDB Server

確認したブラウザ：windows chrome バージョン: 114.0.5735.110（Official Build） （64 ビット）

**Comment by shinya** [comment]
こちらのIssueと同一の内容になるので、
このIssueはクローズいたします。
https://github.com/EC-CUBE/ec-cube/issues/5672
