### ISSUE TITLE
商品管理＞商品一覧＞詳細検索で、タグのソート順が反映されない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#6011]
### 概要(Overview)

商品管理＞詳細検索で、タグのソート順が反映されません。

SearchProductTypeでソート順の指定が必要かと思われます。
https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Form/Type/Admin/SearchProductType.php#L110

EntityType Field
https://symfony.com/doc/current/reference/forms/types/entity.html#using-a-custom-query-for-the-entities

### 再現手順(Procedure)

- 商品管理＞タグ管理で、タグの並び順を変更する
- 商品管理＞商品一覧＞詳細検索で、タグの表示順を確認すると、タグ管理の並び順と異なる

<img width="543" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/8196725/1735df36-c2b0-47c4-8edb-a03e0eceaadb">

<img width="976" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/8196725/38a8b8a4-bdac-4dda-b26a-56f47af07215">

### 環境(Environment)

EC-CUBE：ec-cube.co(2023-06-14)

**Comment by dotani1111** [comment]
#6024 
こちらで対応致しましたので、closeさせて頂きます。
