### ISSUE TITLE
配送方法の選択時における配達時間のエラー

### ISSUE THREAD

**Issue by joshoangtien** [EC-CUBE/ec-cube#6019]
### 概要(Overview)

Step 1:「注文管理」画面で「注文の詳細」に入り、「配送情報の追加」を選択してください。
Step 2:「配送情報の追加」画面で、「配送方法」を変更すると、「配達時間」がエラーになります。
![2023-06-27_13h21_49](https://github.com/EC-CUBE/ec-cube/assets/95531279/4629b016-638a-4665-8959-5af77c22b673)

### 再現手順(Procedure)

次のコードに問題があることに気付きました：
![Screenshot from 2023-07-06 10-55-11](https://github.com/EC-CUBE/ec-cube/assets/95531279/36a0038d-8298-429f-8316-d9b5e1c57757)
私たちはこのコードを修正しました：
```
$shippingDeliveryTime.append($('<option></option>').val('').text('{{ 'admin.common.select__unspecified'|trans }}'));
```

### 環境(Environment)

EC-CUBE: 4.2.1
PHP: 8.1.19
DB:
   PostgresSQL 14.8

**Comment by shinya** [comment]
@joshoangtien 
Issueありがとうございます。内容を拝見したところ、「修正しました」とあるのでもしよろしければPull Requestも合わせていただけると嬉しいです。よろしくお願いします。

**Comment by dotani1111** [comment]
@joshoangtien 
issueありがとうございます👍 
こちら代わりにPRを作成させて頂きました！

**Comment by joshoangtien** [comment]
@daichi_otani
PR を作成していただきありがとうございます!

**Comment by dotani1111** [comment]
Marge済みのためCloseします。
