### ISSUE TITLE
データベースの設定でパスワードが正しくても接続エラーとなる

### ISSUE THREAD

**Issue by nzsys** [EC-CUBE/ec-cube#6025]
### 概要(Overview)

データベースパスワードに&が含まれていると、インストーラ画面 > データベースの設定でパスワードが正しくても接続エラーになる。

### 再現手順(Procedure)

データベースのパスワードに&を含める
↓
/index.php/install/step1にアクセス
↓
データベースの設定に&を含んだ正しいパスワードを入力する
↓
データベースに接続できませんでした。...

### 環境(Environment)

EC-CUBE: 4.2.1
PHP: 8.1.17
DB:
  MySQL: 8.0.32

**Comment by dotani1111** [comment]
@nzsys 
Issueありがとうございます。 🐱 
こちら調査したいと思いますが、その際にErrorログなど頂けますと嬉しいです。

**Comment by nanasess** [comment]
.env に出力する際にURLエンコードが必要な気がします

**Comment by nzsys** [comment]
入力値&がDB接続の際に＆に変換されているため、パスワード不一致になります。

**Comment by dotani1111** [comment]
@nzsys @nanasess 
ありがとうございます。
.env↓のDATABASE_URLに＆が入ることで、接続できないみたいですね。

https://github.com/EC-CUBE/ec-cube/blob/1a396722d7e1930484f3ccf09cce6005e09b666c/.env.dist#L19C31-L19C37

**Comment by dotani1111** [comment]
@nzsys @nanasess 
以下の行でurlencodeされてないのが原因みたいですね。
https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Form/Type/Install/Step4Type.php#L113

手元で設定してみたら接続できました。PR作成してみます。

**Comment by dotani1111** [comment]
@nzsys @nanasess 
接続する時の値を見てみました。
入力した半角の「&」が、接続する際は全角の「＆」になってました。

直接、半角&を指定したら接続できました。

**Comment by dotani1111** [comment]
@nzsys 
フロントはデフォルトでサニタイズ処理がかかっている為、パスワードのフォームだけ処理を外すように修正致します。
