### ISSUE TITLE
4.2.3リリース計画

### ISSUE THREAD

**Issue by xuelian311** [EC-CUBE/ec-cube#6034]
## 基本方針
マイナーバージョンとして以下の優先順位で開発を行います。

- セキュリティ強化につながる機能追加
- 既存pull requestの取込

方針としては、既存プラグイン/デザインテンプレートとの互換性を最大限考慮します。

## 予定スケジュール

※現時点での予定であるため、実際は数日前後する可能性があります。

- 2023/9/29(金) ソースコード凍結
- 2023/11/6(月) リリース

## 対応内容

EC-CUBE4.2.2にて取り込む予定の改修一覧
https://github.com/EC-CUBE/ec-cube/milestone/51

マージ済みプルリクエスト一覧
https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+milestone%3A4.2.3+is%3Aclosed

## 互換性についての情報

マイナーバージョンの開発では互換性を維持するために、以下の観点でPullRequestをレビューしています。

#### 既存機能の仕様変更
[`affected:外部仕様` ラベル](https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Aaffected%3A%E5%A4%96%E9%83%A8%E4%BB%95%E6%A7%98+is%3Aclosed+milestone%3A4.2.3+is%3Amerged)をご確認ください

#### フックポイントの呼び出しタイミングの変更
変更はありません

#### フックポイントのパラメータの削除・データ型の変更
変更はありません

#### twigファイルに渡しているパラメータの削除・データ型の変更
変更はありません

#### Serviceクラスの公開関数の、引数の削除・データ型の変更
変更はありません

#### 入出力ファイル(CSVなど)のフォーマット変更
変更はありません

### 期待する内容(Expect) or 要望(Requirement)

- Issue および Pull requests のマイルストーンの設定は現時点での予定であり、変更となる可能性があります。
- Pull Request 未経験の方もぜひ開発にご協力ください。修正が容易と思われるものや、仕様が明確なものには、<a class="d-inline-block IssueLabel v-align-text-top" style="background-color: #5ae833; color: #000000" title="簡単に修正できそうなもの" href="https://github.com/EC-CUBE/ec-cube/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue">🏷 good-first-issueラベル</a>をつけています。
- 4.2.3で対応したいissueを多数取り上げております。社内でもPull Requestの作成に努めておりますが、ぜひ皆さまからのPull Requestもお待ちしております。

**Comment by xuelian311** [comment]
#6029 の取込をもって4.2.3のソースコードを凍結させていただきます。
PRやissueをくださった皆様、ありがとうございました！

テスト用パッケージはこちらです↓
https://github.com/EC-CUBE/ec-cube/releases/

ダウンロードリンク↓
https://github.com/EC-CUBE/ec-cube/releases/download/4.2.3-20231002/eccube-4.2.3-20231002.tar.gz
https://github.com/EC-CUBE/ec-cube/releases/download/4.2.3-20231002/eccube-4.2.3-20231002.zip

**Comment by dotani1111** [comment]
@xuelian311 
4.2.3のリリースは無事完了しているため、こちらのIssueは閉じさせていただきます 🐱
