### ISSUE TITLE
管理画面＞ユーザアイコン＞パスワード変更で入力必須バッジがない 

### ISSUE THREAD

**Issue by ji-eunsoo** [EC-CUBE/ec-cube#6051]
### 概要(Overview)

管理画面＞ユーザアイコン＞パスワード変更に、
入力必須（現在のパスワード、新しいパスワード、新しいパスワード(確認)）バッジがありません。
<img width="1042" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/132241702/d24501ec-f432-44a1-b43a-bea042e46055">

修正箇所
以下のところに、`<span class="badge bg-primary ms-1">{{ 'admin.common.required'|trans }}</span>`を追加
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/change_password.twig#L43

https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/change_password.twig#L55

https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/change_password.twig#L67

### 再現手順(Procedure)

管理画面>ユーザアイコン＞パスワード変更を表示する。

### 環境(Environment)

EC-CUBE:4.2.2

**Comment by dotani1111** [comment]
@ji-eunsoo 
Issueありがとうございます。 👍

**Comment by dotani1111** [comment]
マージ済みのため、クローズします。
