### ISSUE TITLE
管理画面＞商品管理＞商品規格登録で入力必須バッジがない

### ISSUE THREAD

**Issue by ji-eunsoo** [EC-CUBE/ec-cube#6052]
### 概要(Overview)

管理画面＞商品管理＞商品規格登録に、入力必須（在庫、販売価格）バッジがありません。
<br class="Apple-interchange-newline">
<img width="1260" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/132241702/9dbc8d35-c07e-4254-bc6a-717b9d08b9d5">

関連箇所
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/Product/product_class.twig#L253-L267

### 再現手順(Procedure)

管理画面＞商品管理＞商品規格登録を表示する。

### 環境(Environment)

EC-CUBE:4.2.2

**Comment by dotani1111** [comment]
@ji-eunsoo 
issueありがとうございます。 👍 
フォームに必須バッチをつけると、見づらくなってしまうため、ヘッダーに付けるのが良いかと思いました。

**Comment by dotani1111** [comment]
マージ済みのため、クローズします。
