### ISSUE TITLE
受注管理 >受注一覧>出荷済にするボタンでチェックボックスでしかチェック出来ない

### ISSUE THREAD

**Issue by ji-eunsoo** [EC-CUBE/ec-cube#6053]
### 概要(Overview)

受注管理 >受注一覧>出荷済にするボタン＞出荷お知らせメールを同時に送るでチェックボックスでしかチェック出来ない
本来であれば、文字部分をクリックしてもチェックされる。

<img width="1015" alt="スクリーンショット 2023-10-30 9 54 49" src="https://github.com/EC-CUBE/ec-cube/assets/132241702/810713ba-72e3-4c19-b168-200a00ff8063">

修正箇所
以下を`<label class="form-check-label notificationMail" for="notificationMail">`のように修正
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/Order/index.twig#L627-L630

### 再現手順(Procedure)

受注管理 >受注一覧>出荷済にするボタンをクリックする

### 環境(Environment)

EC-CUBE:4.2.2

**Comment by dotani1111** [comment]
マージ済みのため、クローズします。
