### ISSUE TITLE
商品管理>規格管理>登録で入力必須バッジがない

### ISSUE THREAD

**Issue by ji-eunsoo** [EC-CUBE/ec-cube#6055]
### 概要(Overview)

商品管理>規格管理>登録に、入力必須（規格名）バッジがありません。
<img width="938" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/132241702/4062f59d-46ad-4ffc-be89-bd27ba32f491">

修正箇所
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/Product/class_name.twig#L142

### 再現手順(Procedure)

商品管理>規格管理>登録

### 環境(Environment)

EC-CUBE:4.2.2

**Comment by dotani1111** [comment]
マージ済みのため、クローズします。
