### ISSUE TITLE
商品管理>規格管理>規格分類管理に、入力必須バッジがない

### ISSUE THREAD

**Issue by ji-eunsoo** [EC-CUBE/ec-cube#6056]
### 概要(Overview)

商品管理>規格管理>登録に、入力必須（分類名）バッジがありません。
<img width="974" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/132241702/f80651e3-636a-491c-b636-7eb46454aa2e">

修正箇所
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/Product/class_category.twig#L153

### 再現手順(Procedure)

商品管理>規格管理>規格分類管理を表示

### 環境(Environment)

EC-CUBE:4.2.2

**Comment by dotani1111** [comment]
@ji-eunsoo 
issueありがとうございます👍

**Comment by dotani1111** [comment]
マージ済みのため、クローズします。
