### ISSUE TITLE
コンテンツ管理>新着情報管理>新着情報登録に、入力必須バッジがない 

### ISSUE THREAD

**Issue by ji-eunsoo** [EC-CUBE/ec-cube#6057]
### 概要(Overview)

コンテンツ管理>新着情報管理>新着情報登録に、入力必須（公開日時、タイトル）バッジがありません。
<img width="716" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/132241702/34f4c254-0712-48fd-abc5-d32010e6bf4d">

以下のところに、`<span class="badge bg-primary ms-1">{{ 'admin.common.required'|trans }}</span>`を追加
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/Content/news_edit.twig#L40
https://github.com/EC-CUBE/ec-cube/blob/81b68e78b38e4e25d7d818eb65dedce3dc3b87b9/src/Eccube/Resource/template/admin/Content/news_edit.twig#L48

### 再現手順(Procedure)

コンテンツ管理>新着情報管理>新着情報登録を表示

### 環境(Environment)

EC-CUBE:4.2.2

**Comment by dotani1111** [comment]
@ji-eunsoo 
こちらと同じ内容のため、クローズさせて頂きます。
https://github.com/EC-CUBE/ec-cube/issues/6050
