### ISSUE TITLE
開発時のスロットリング機能の無効化

### ISSUE THREAD

**Issue by TCD-HM** [EC-CUBE/ec-cube#6068]
### 概要(Overview)

開発時は、スロットリング機能を無効化する様な設定値の追加をしたい。

### 期待する内容(Expect) or 要望(Requirement)

開発時に、共有開発サーバ等で進めている場合にスロットリング機能を無効化する設定値を追加してスロットリング機能が無効化される仕組みが欲しい。

**Comment by chihiro-adachi** [comment]
@TCD-HM 
`APP_ENV=dev`ならスロットリングは無効になるはずですが、効いてないでしょうか？

**Comment by TCD-HM** [comment]
@TCD-HM 
`APP_ENV=dev`の場合は、無効化されています。
言葉不足でしたが、
`APP_ENV=prod`の設定において開発作業を行っている場合にスロットリング機能の無効化をしたい場合の設定値が欲しいです。

**Comment by chihiro-adachi** [comment]
@TCD-HM 
prodの際は以下で設定が有効になるので、コメントアウトなりファイルの削除なりで無効化できるかと思います。
https://github.com/EC-CUBE/ec-cube/blob/4.2/app/config/eccube/packages/prod/eccube_rate_limiter.yaml

**Comment by dotani1111** [comment]
@TCD-HM 
コメントアウトなどの対応で無効化できるため、クローズさせて頂きます。
