### ISSUE TITLE
商品登録画面 カテゴリ名が長い場合、カテゴリ選択フォームが崩れて表示されてしまう

### ISSUE THREAD

**Issue by tatsuishi** [EC-CUBE/ec-cube#6089]
### 概要(Overview)

商品登録画面 カテゴリ名が長い場合、カテゴリ選択フォームが崩れて表示されてしまう

### 再現手順(Procedure)

管理画面 > 商品管理/商品登録画面「カテゴリ選択フォーム」

カテゴリ名が長い場合、カテゴリ選択フォームが崩れて表示されます
全角15文字以上で崩れることを確認しました

例：「CUBEあああ...」は実際には第３階層ですが、カテゴリ名が長いため崩れて表示されています
![商品登録画面のカテゴリ選択](https://github.com/EC-CUBE/ec-cube/assets/36718825/31decdad-9e97-4877-95c6-e687c0320534)

商品管理だけではなく、同様のスタイルを適用しているであろう箇所は崩れが確認できました

例：フォルダ管理
![フォルダ管理](https://github.com/EC-CUBE/ec-cube/assets/36718825/f0e4e364-85c9-43ad-9f55-9ec954d61263)

### 環境(Environment)

EC-CUBE: 4.2.3
PHP: 8.1.22
DB: MySQL 5.7.43

**Comment by dotani1111** [comment]
@tatsuishi 
 Issueありがとうございます。
 文字列が長い場合は、表示を省略するなどの対応が必要そうですね。

**Comment by tatsuishi** [comment]
@dotani1111 
ご確認ありがとうございます
カテゴリ名によっては先頭に同じ文言を入れる場合もあるので、できれば全て見えているのが理想です
(例「ワイシャツ(長袖)」「ワイシャツ(半袖)」など)
省略する場合でもある程度の文字数は見えていた方がいいかなと感じています

**Comment by tatsuishi** [comment]
マージいただいたのでクローズします。
