### ISSUE TITLE
商品別税率が設定されている場合に、基本税率を編集しようとするとエラーになる

### ISSUE THREAD

**Issue by tatsuishi** [EC-CUBE/ec-cube#6090]
### 概要(Overview)

商品別税率が設定されている場合に、基本税率を編集しようとするとエラーになる

### 再現手順(Procedure)

設定 > 設定/店舗設定/税率設定

商品別税率が設定されている場合に、基本税率を編集しようとすると、
「同時刻の適用日時を設定できません。」というエラーが表示されてしまいます

![税率設定エラー](https://github.com/EC-CUBE/ec-cube/assets/36718825/e1937cbc-3c18-4cd7-8029-1f0ad9079240)

この画面で登録しようとした適用日時と同じapply_dateで商品別税率が設定されている商品が存在する場合に発生します
ここで商品別のデータを考慮していないためです
https://github.com/EC-CUBE/ec-cube/blob/4.3/src/Eccube/Form/Type/Admin/TaxRuleType.php#L77-L80

### 環境(Environment)

EC-CUBE: 4.2.3
PHP: 8.1.22
DB: MySQL 5.7.43

**Comment by dotani1111** [comment]
@tatsuishi 
Issueありがとうございます。
こちら再現確認を進めていきたいと思います。

**Comment by dotani1111** [comment]
マージ済みのためクローズ致します。
