### ISSUE TITLE
カート メッセージが長いとアイコンが改行されてしまう

### ISSUE THREAD

**Issue by tatsuishi** [EC-CUBE/ec-cube#6092]
### 概要(Overview)

カート メッセージが長いとアイコンが改行されてしまう

### 再現手順(Procedure)

画面：フロント画面 カートページ

メッセージが長いとアイコンが改行して表示されてしまいます
(商品名が長い場合に発生しやすくなります)

**改行していない状態**
<img width="1009" alt="カートメッセージ_崩れていない場合" src="https://github.com/EC-CUBE/ec-cube/assets/36718825/9cf66cab-929e-4f53-81d0-e91bf3317ce8">

**商品名が長く改行されている状態**
<img width="986" alt="カートメッセージ_崩れた場合" src="https://github.com/EC-CUBE/ec-cube/assets/36718825/11ee2b65-290b-4c1a-b633-a87eb197bc55">

### 環境(Environment)

EC-CUBE: 4.2.3
PHP: 8.1.22
DB: MySQL 5.7.43

**Comment by dotani1111** [comment]
@tatsuishi 
Issueありがとうございます。
こちらはどのように表示されたらベストになるのか、具体的に教えて頂きたいです。

**Comment by tatsuishi** [comment]
@dotani1111 
ご確認ありがとうございます
デフォルトデザインを再現するのであれば添付画像の形が近いと思っております

![カートメッセージ_修正案](https://github.com/EC-CUBE/ec-cube/assets/36718825/cd18fcec-dfdb-4d5a-9895-6ede8eb07d8a)
```
{# 追加スタイル  #}
    <style>
        .test1 {
            display: inline-block;
        }
        .test2 {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }
        .ec-alert-warning__text {
            flex: 1;
        }
    </style>

{#  参考にカートメッセージ部分を抜粋しています #}
    <div class="ec-off3Grid__cell">
        <div class="ec-alert-warning">
            <div class="test1">
                <div class="test2">
                    <div class="ec-alert-warning__icon"><img src="{{ asset('assets/icon/exclamation-white.svg') }}"></div>
                    <div class="ec-alert-warning__text">{{ 'front.cart.no_items'|trans }}</div>
                </div>
            </div>
        </div>
    </div>

```

**Comment by dotani1111** [comment]
@tatsuishi 
ありがとうございます 👍 
こちらの内容でPRを頂けますか？

**Comment by tatsuishi** [comment]
@dotani1111 
PRお待たせしました、何卒よろしくお願いいたします。

**Comment by dotani1111** [comment]
@tatsuishi 
ありがとうございます。
マージされた為、issueの方もクローズ致します。
