### ISSUE TITLE
Automatically log out when entering a malformed email address and pressing submit a second time in the "My Page" > "Edit Customer Information" screen

### ISSUE THREAD

**Issue by TungNV21** [EC-CUBE/ec-cube#6104]
### 概要(Overview)

On "My Page" screen > "Edit Customer Infomation" tab, When entering the wrong format of the email field before and after, then pressing submit for the 1st time, form validation is activated and a message is displayed, when corrected Correct value of the email field and press submit a second time, the system will automatically log out of the current account.

### 再現手順(Procedure)

Step 1: Log in with any user account.
Step 2: Move to the "My Page" screen.
Step 3: Click on the "Edit Customer Information" tab on the "My Page" screen.
Step 4: Change the value of the first and last "Email" fields to "a".
Step 5: Click "Submit",
-> Now the form validation works and displays the message in the wrong email format.
Step 6: Correct the values ​​of the two email fields in the correct format and click "Submit" a second time.
Expected result: Update customer information successfully
Actual result: Automatically logs out of the current account and no updates are performed

### 環境(Environment)

ECCUBE: 4.2.x
PHP: 7.4.x
MySQL: 5.7.x

**Comment by dotani1111** [comment]
@TungNV21 
issueありがとうございます。
重複しているため、こちらはクローズさせて頂きます。
追加情報などありましたら、以下のリンク先に記入いただけると幸いです。

https://github.com/EC-CUBE/ec-cube/issues/6103
