### ISSUE TITLE
PluginService で config.yml をチェックするコードが残っている

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#6108]
### 概要(Overview)

おそらく3系の名残り。4系に config.yml は存在しない
https://github.com/EC-CUBE/ec-cube/blob/e9edc3bbcc3183c52c07108023382f591d759c5b/src/Eccube/Service/PluginService.php#L418-L444

### 再現手順(Procedure)

コードレビューで発見

### 環境(Environment)

EC-CUBE 4.2

**Comment by dotani1111** [comment]
@nanasess 
Issueありがとうございます。
こちら調査を進めたいと思います。

**Comment by dotani1111** [comment]
@nanasess 
readConfigの関数を見ると、内部的にはcomposer.jsonを見ているようでした。
エラーメッセージのみ修正必要になります。
またいくつかのコメントやエラーメッセージでconfig.ymlの記載があるので、合わせて修正します。
https://github.com/EC-CUBE/ec-cube/blob/e9edc3bbcc3183c52c07108023382f591d759c5b/src/Eccube/Service/PluginService.php#L453-L479
