### ISSUE TITLE
ルーティングのメソッド指定が不適切

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#6171]
### 概要(Overview)

以下のルーティングのメソッド指定がANYになっている。
適切なメソッドを指定すること。
ルーティング | パス | METHOD
-- | -- | --
admin_product_class_category_export | /admin/product/class_category/export/{class_name_id} | ANY
admin_product_class_name_export | /admin/product/class_name/export | ANY
admin_product_class_name_csv_import | /admin/product/class_name_csv_upload | ANY
admin_product_class_category_csv_import | /admin/product/class_category_csv_upload | ANY
block_auto_new_item | /block/auto_new_item | ANY

### 再現手順(Procedure)

```
bin/console debug:router --format=json --env=prod | jq -r '. | to_entries[] | [ .key, .value.path, .value.method ] | @tsv' | grep ANY

```

### 環境(Environment)

EC-CUBE 4.3.0-beta

**Comment by ji-eunsoo** [comment]
マージしました。
https://github.com/EC-CUBE/ec-cube/pull/6174
