### ISSUE TITLE
【docker-compose.ymlの誤記述】ブランチ4.2のdocker-compose.ymlの25行目の記述が誤っています。

### ISSUE THREAD

**Issue by singo-i** [EC-CUBE/ec-cube#6173]
### 概要(Overview)

ブランチ4.2のdocker-compose.ymlの25行目には以下の記述があります:
```
image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ec-cube/ec-cube-php}:${TAG:-8.1-apache}
```
上記の記述では、4.3-betaがインストールされます。

Dockerfileには`ARG TAG=7.4-apache-bullseye`の記述があります。

正しい記述は
```
image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ec-cube/ec-cube-php}:${TAG:-7.4-apache}
```
ではないでしょうか？

上記の修正により、4.2.3がインストールできました。

### 再現手順(Procedure)

ブランチ4.2をcloneした後、`docker-compose -f docker-compose.yml -f docker-compose.mysql.yml up -d`

### 環境(Environment)

Windows11 Home WSL2
Docker Desktop

EC-CUBE:4.2.3
PHP:7.4.33
DB:MySQL 5.7.44

**Comment by nanasess** [comment]
docker-compose.yml の記述が間違っているのではなく、 [ghcr.io/ec-cube/ec-cube-php:8.1-apache](https://github.com/EC-CUBE/ec-cube/pkgs/container/ec-cube-php/207697137?tag=8.1-apache) が4.3ブランチでビルドされてしまっているのが問題ですね。

4.2 ブランチは今後更新されないと思われますので
`export TAG=8.1-apache-4.2` としてから `docker compose` コマンドを実行することで、 
[ghcr.io/ec-cube/ec-cube-php:8.1-apache-4.2](https://github.com/EC-CUBE/ec-cube/pkgs/container/ec-cube-php/167817144?tag=8.1-apache-4.2) を利用できると思います。

`${TAG:-7.4-apache}` とすると 4.2 ブランチが利用できる理由は、4.3 からは PHP7.4 がサポート外となり、4.3 ブランチではビルド対象から外れたためです。

**Comment by dotani1111** [comment]
@singo-i 
現在4.3ブランチのみ開発を行なっているため、上記の方法での解決をお願いします。
