### ISSUE TITLE
APC の推奨表示

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#619]
IIS では [WinCache Extension](http://www.iis.net/downloads/microsoft/wincache-extension) を使用するのが一般的ですので、 `$_SERVER['SERVER_SOFTWARE']` などの情報を参照して、表示有無を制御した方が良いと思います。

**Comment by Yangsin** [comment]
ご意見あリがとうございます。
ぜひプルリクエストをいただけると助かります。

**Comment by ttsuru** [comment]
WinCache って対応してるのかなと思ったら・・・

あるんですね。
https://github.com/symfony/ClassLoader/blob/master/WinCacheClassLoader.php

**Comment by nanasess** [comment]
そもそも、 APC って PHP 5.5 以降でも使えるんでしたっけ？

**Comment by ttsuru** [comment]
@nanasess APCuですね。Macならbrewで入れられますね。

**Comment by nobuhiko** [comment]
symfony/ClassLoader が環境に合わせていい具合に対応してくれればいいのに・・と見てて思いました。

**Comment by nanasess** [comment]
gitter での議論より。

> レンサバではほとんどつかえないし、キャッシュについてはインストーラーのチェックからは外したほうが親切かもしれませんね。
> EC-CUBEのサイト上での表記も見なおさなきゃいけないんですが。
> Symfonyのページへのリンクおいておくくらいで、EC-CUBEとしての推奨はべつにキャッシュかかなくてもいかなと。

**Comment by ttsuru** [comment]
@nanasess 
Warningではなく、Infoレベルにしてはどうでしょうか。
他のCMSでもできれば程度になっていそうですね。

**Comment by nanasess** [comment]
@ttsuru 推奨なので、 info のほうが適切かもしれませんね。

**Comment by nanasess** [comment]
#1138 でマージされましたのでクローズします。
