### ISSUE TITLE
CSVアップロードのフォーマット形式

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#620]
CSVダウンロードした形式そのままで、アップロードできた方が良いと思います。

**Comment by Yangsin** [comment]
いいですね

**Comment by k-yamamura** [comment]
対応は可能なのですが、
例えばダウンロード時に商品コードは必要ないからCSV出力項目で出力しないに設定したとします。

アップロード時には商品コードは必須項目なのですが、
必須となる制御等は2系だとどのような考慮をされているのでしょうか。

**Comment by nanasess** [comment]
2系では、CSV出力項目設定と、アップロード項目が連動していて、必要以上に項目を削ると、アップロード時にエラーになっていました。

ただ、これではユーザビリティに欠けると思いますし、最近主流になりつつある、アップロード時に動的に項目を選択できたら便利かと思います。

### 参考

https://support.freee.co.jp/hc/ja/articles/202847120-%E9%8A%80%E8%A1%8C%E3%82%84%E3%82%AB%E3%83%BC%E3%83%89%E3%81%AE%E6%98%8E%E7%B4%B0%E3%82%92%E6%89%8B%E5%8B%95%E3%81%A7%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E3%81%99%E3%82%8B

**Comment by k-yamamura** [comment]
そういえばsalesforceとかもカスタマイズができますね。

CSV入力項目設定という画面を作りそれと連動させるという機能なら、
今の仕組みなら簡単にできそうなのでこちらは是非対応していきたいですね。

**Comment by t-nagahashi** [comment]
Salesforceだと動的に設定した内容を、マッピングファイルで保存でき、
2回目以降はそれを使用することができたので、そこまでできるとさらに便利ですね。

**Comment by t-nagahashi** [comment]
とはいえ、実装にある程度工数がかかるとおもうので、一旦は、
以下仕様で改修したいと思います。

https://github.com/EC-CUBE/ec-cube/issues/1981#issuecomment-277175087

**Comment by chihiro-adachi** [comment]
4系にて対応済のため、クローズします。
