### ISSUE TITLE
商品を複製し、画像を削除すると、複製元の画像が削除される

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#621]
以下の不具合と、おおむね同じ現象かと思います。
<http://svn.ec-cube.net/open_trac/ticket/846>

**Comment by k-yamamura** [comment]
#625 
で対応しました。

**Comment by Yangsin** [comment]
#625 にて 商品複製時に、画像も複製して作成されることを確認しましたので、クローズとさせていただきます。
