### ISSUE TITLE
PurchaseFlowのPriorityが意図しないソート順になっている場合がある

### ISSUE THREAD

**Issue by h-kida** [EC-CUBE/ec-cube#6257]
### 概要(Overview)

purchaseflow.yamlで指定されているpriorityにてソートする際に、nameで指定されている単位にてソートが行われるため、異なるflow_typeのpriorityにてソートが行われpriorityの指定とは異なる順で処理が実行される部分がある。

これにより、プラグインにてPriorityを指定しイベントを追加する際も意図した順番に追加が行えない状態が発生します。

### 再現手順(Procedure)

purchaseflow.yamlにてAddPointProcessorとPaymentValidatorにてそれぞれ下記の設定が行われているかと思います。

(一部抜粋)
AddPointProcessor
  - { name: eccube.item.holder.post.validator, flow_type: shopping, priority: 900 }
  - { name: eccube.item.holder.post.validator, flow_type: order, priority: 1000 }

PaymentValidator
  - { name: eccube.item.holder.post.validator, flow_type: cart, priority: 1000 }
  - { name: eccube.item.holder.post.validator, flow_type: shopping, priority: 800 }

上記の設定の場合、flow_type = shopping に注目すると、
AddPointProcessorは「priority: 900 」
PaymentValidatorは「priority: 800」
となっているため、AddPointProcessor -> PaymentValidatorの順に実行されるのが正しいが、
PurchaseFlowPass.phpのfindAndSortTaggedServicesで取得を行った際に、
AddPointProcessorの「flow_type: shopping」に指定されている「priority: 900」
PaymentValidatorの「flow_type: cart」に指定されている「priority: 1000」が比較され
これの順番に基づきflow_type毎の処理順番も設定されるため、「flow_type: shopping」において
PaymentValidator -> AddPointProcessorの順で実行される状態となっている。

### 環境(Environment)

EC-CUBE: 4.3RC
PHP: 8.1
DB: PostgreSQL 14

**Comment by shinya** [comment]
起票ありがとうございます。
内容確認します。

**Comment by dotani1111** [comment]
マージ済のためクローズします。
