### ISSUE TITLE
GitHub Actions で Codeception が動作しない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#6275]
### 概要(Overview)

以下のエラーで Codeception が動作しない
https://github.com/EC-CUBE/ec-cube/actions/runs/10573554138/job/29434390280#step:14:29

```
Curl error: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"goog:chromeOptions":{"prefs":{"download.default_directory":"/home/runner/work/ec-cube/ec-cube/codeception/_support/_downloads"}},"browserName":"chrome"}]},"desiredCapabilities":{"goog:chromeOptions":{"prefs":{"download.default_directory":"/home/runner/work/ec-cube/ec-cube/codeception/_support/_downloads"}},"unexpectedAlertBehaviour":"accept","elementScrollBehavior":1,"browserName":"chrome"}}

Failed to connect to 127.0.0.1 port 9515 after 0 ms: Connection refused
```

### 再現手順(Procedure)

GitHub Actions で E2Eテスト(Codeception)を実行する

以下の Job を確認すると、
https://github.com/EC-CUBE/ec-cube/actions/runs/10573554138
- [Runner Image version: 20240818.1.0](https://github.com/EC-CUBE/ec-cube/actions/runs/10573554138/job/29434390809#step:1:9) は正常に動作する
    - ChromeDriver 127.0.6533.119
- [Runner Image version: 20240825.1.0](https://github.com/EC-CUBE/ec-cube/actions/runs/10573554138/job/29434390280#step:1:9) はエラーになる
    - ChromeDriver 128.0.6613.84

という状況の模様

### 環境(Environment)

- EC-CUBE4.3 ブランチ

**Comment by nanasess** [comment]
setup-chromedriver のテストでは **ChromeDriver 128.0.6613.84** でも正常に動作している
https://github.com/nanasess/setup-chromedriver/actions/runs/10568990875/job/29407191676#step:12:26

**Comment by nanasess** [comment]
Chrome 129.0.6668.58 になって互換性の問題が発生している模様
https://github.com/EC-CUBE/ec-cube/actions/runs/11068579032/job/30754326049#step:13:41

**Comment by ji-eunsoo** [comment]
対応完了したのでCLOSEします。
