### ISSUE TITLE
クレカ決済エラーの場合、在庫数が戻りません。

### ISSUE THREAD

**Issue by toptal0212** [EC-CUBE/ec-cube#6290]
### 概要(Overview)

EC-CUBEペイメントPlus決済プラグイン(4.2系)を使用しています。
クレカ決済エラーの場合、在庫数が戻りません。

### 再現手順(Procedure)

クレカ情報
1234567812345678
2024年1月
名義人：test

### 環境(Environment)

EC-Cube 4.2.3
PHP 8.0

**Comment by ji-eunsoo** [comment]
@toptal0212 
決済プラグインの問題かなと思いますので、GMOイプシロン様にお問い合わせお願いいたします。
