### ISSUE TITLE
管理画面の一部のページのタイトルがおかしい

### ISSUE THREAD

**Issue by poego** [EC-CUBE/ec-cube#631]
設定→オーナーズストアの以下のページでタイトルがおかしい。
* プラグイン一覧、プラグインインストール、プラグインハンドラ設定  
　それぞれ、システム設定 になっている
* テンプレート一覧、テンプレートインストール  
　それぞれ、コンテンツ管理になっている

**Comment by k-yamamura** [comment]
別機能を開発しているタイミングで修正しています。
