### ISSUE TITLE
プラグインのインストーラのテストが面倒

### ISSUE THREAD

**Issue by aminotsukasa** [EC-CUBE/ec-cube#632]
プラグインのインストール時にテーブル作成等行うためのインストーラがありますが、
開発時にも毎回管理画面から手動でアーカイブをアップロードする必要があるため面倒です

コマンドラインでインストーラを走らせるツール作ります....コソコソ

**Comment by shinichi-takahashi** [comment]
:clap:

**Comment by ttsuru** [comment]
おおおおお、楽しみです！
ついにCLIからのインストールがshじゃなくなるんですね。

**Comment by ttsuru** [comment]
あ、と思いましたが、プラグインの話なんですね。
https://github.com/ec-cube-plugin/plugin-installer

こんなもの作りました。これとシェルを組み合わせたら、 composer.json に追記するだけでプラグイン入れられますね。

**Comment by Yangsin** [comment]
動作検証不十分ですので、次に送りました。
