### ISSUE TITLE
index_dev.php を使用するとシステムエラーが発生する場合がある。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#638]
以下の条件の場合にページ単位でシステムエラーが発生します。

- キャッシュが存在しない
- 初回アクセス時に /inidex_dev.php をつけてアクセス
- 次回以降は /index_dev.php はつけない

※初回アクセス時に /index_dev.php を付けずにアクセスした場合は、特に問題ありませんでした。

エラーログは以下のとおりです。
<code>
CRITICAL: Twig_Error_Runtime: The "native_profiler" extension is not enabled in "index.twig" at line 22. (uncaught exception) at D:\develop\workspace\php5.6\ec-cube\vendor\twig\twig\lib\Twig\Environment.php line 683 {"exception":"[object] (Twig_Error_Runtime(code: 0): The \"native_profiler\" extension is not enabled in \"index.twig\" at line 22. at D:\\develop\\workspace\\php5.6\\ec-cube\\vendor\\twig\\twig\\lib\\Twig\\Environment.php:683)"} []
</code>

**Comment by aminotsukasa** [comment]
http://stackoverflow.com/questions/30861526/twig-error-after-symfony-2-7-upgrade-the-native-profiler-extension-is-not-en
と類似の内容のように見えます

デバッグモードの場合native_profilerありでTwigテンプレートがキャッシュされるが、非デバッグモード時の場合はtwigがnative_profilerありのキャッシュを解釈できない、という挙動のようです。
そのためnative_profilerありで先にキャッシュだけ作ってからproductionで起動するとこけると思われます。
テンプレートの問題ではなく生成されたキャッシュの問題ですのでtwitのキャッシュ消すのが一旦の回避策にはなると思います。
根本的には、
* native_profilerを呼び出しているWebProfilerServiceProvider を使わないようにする
* index_dev.phpの出力するtwigキャッシュを毎リクエスト後に削除する
* native_profilerありのtwigキャッシュとnative_profilerなしのtwigキャッシュを混ざらないように別ディレクトリに出力する
とかでしょうか

**Comment by shhirose** [comment]
> テンプレートの問題ではなく生成されたキャッシュの問題ですのでtwitのキャッシュ消すのが一旦の回避策にはなると思います。

はい。現在はキャッシュを削除して対応しています。

> - native_profilerありのtwigキャッシュとnative_profilerなしのtwigキャッシュを混ざらないように別ディレクトリに出力する とかでしょうか

これが一番ベストな気がします。


> - index_dev.phpの出力するtwigキャッシュを毎リクエスト後に削除する

この方法や、index_dev.php を使用している間はキャッシュを見ないようにした場合、速度的にいまいちなので、できればキャッシュを分けれたらと思います。

**Comment by ttsuru** [comment]
index_dev.php では file cache をしないというのはいかがでしょうか。
テストの際にはキャッシュがない方が都合が良いのではないでしょうか。

**Comment by aminotsukasa** [comment]
@ttsuru 
手元で実験したところ、キャッシュがあると処理時間が500msぐらい早くなるようですがあまり問題はないような気がします

**Comment by ttsuru** [comment]
@aminotsukasa 
最初にキャッシュする設定でcommitした時も本番の速度の問題でpushした覚えがあります。

**Comment by shhirose** [comment]
スペックの問題だとは思いますが、私の環境だとトップページ表示で 1200ms くらい差が出てしまっています。
開発環境のスペックがどの程度を推奨しているのかわかりませんが、キャッシュできるならしてもらいたいかなと思いました。

> テストの際にはキャッシュがない方が都合が良いのではないでしょうか。

キャッシュを持つことで弊害が想定されるのであればキャッシュ無しでいいかと思います。

**Comment by aminotsukasa** [comment]
@ttsuru 
記述が足りませんでした。500msぐらい遅くなってもあまり問題ないのはデバッグ時だけで、本番で毎リクエストに500msもかかるのは遅いと思います。

ちょっと手元で実験した限りではデバッグ時ならキャッシュありでもtwigを更新しても反映されるので、
弊害がなければ速度差を考えてデバッグ時もキャッシュあり(ディレクトリを分ける)が良さそうに思います。

**Comment by ttsuru** [comment]
@aminotsukasa 
私も本番はキャッシュが必要だと思います。

Twigはファイルのタイムスタンプをみていますので、本来は自動更新ができると思います。
dev用の設定ができるといいですが、実装の手間を考えるとまずは環境ごとにディレクトリを分ける感じですかね。

**Comment by nanasess** [comment]
手元の環境では、安直に以下のようにしてあげれば、

* dev - キャッシュ無し
* prod - キャッシュあり

で開発できてます。

```
                if ($app['env'] !== 'dev') {
                    $twig->setCache($cache);
                }

```

開発環境でも、 APC なり WinCache なりを有効化してあげれば、キャッシュ無しでも 1000ms 以内でレスポンス返ってきているので、そこまで不便に感じないです。
