### ISSUE TITLE
CSVアップロードで空の項目にできない。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#639]
必須項目ではなく、管理画面上からは空にできる項目が、CSV アップロードでは空にすることができません。
　例）商品情報のフリーテキスト

ロジックの IF 文をなくせばいいのではと思います。
<pre>
// if ($row['フリーエリア'] != '') {
    $Product->setFreeArea($row['フリーエリア']);
// }
</pre>

**Comment by k-yamamura** [comment]
ご指摘ありがとうございます。
こちらですがCSVアップロードされたデータを確認したいので、
1行だけで構いませんので記載してもらえないでしょうか。

**Comment by shhirose** [comment]
商品IDが「1」のディナーフォークの検索ワードに何かしらを登録した状態で、以下の内容（検索ワードは空文字列）でインポートするが、検索ワードが空文字列になりません。

<pre>
商品ID,公開ステータス(ID),商品名,ショップ用メモ欄,商品説明(一覧),商品説明(詳細),検索ワード,フリーエリア,商品削除フラグ,商品画像,商品カテゴリ(ID),商品種別(ID),規格分類1(ID),規格分類2(ID),発送日目安(ID),商品コード,在庫数,在庫数無制限フラグ,販売制限数,通常価格,販売価格,送料,商品規格削除フラグ
1,1,ディナーフォーク,,,"セットで揃えたいディナー用のカトラリー。",,,0,"fork-1.jpg,fork-2.jpg,fork-3.jpg","5,6",1,3,6,,fork-01,,1,,115000,110000,,0
</pre>

**Comment by k-yamamura** [comment]
早速のご連絡ありがとうございます。
こちら修正します。

**Comment by shhirose** [comment]
修正の確認ができたためCloseします。
