### ISSUE TITLE
【公式サイト】システム要件のPHPライブラリについて

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#644]
公式サイトのシステム要件ページ（ http://www.ec-cube.net/product/system.php ）の必須 PHP ライブラリとWeb インストーラの表記が異なります。

公式サイト
> pdo pgsql又はmysql

と記載されていますが、Web インストーラでは pdo と pdo_pgsql 又は pdo_mysql です。

実際に必要なのは pdo_pgsql または pdo_mysql ということで正しいのでしょうか。
pgsql または mysql も必要ですか？

※公式サイトではライブラリ間にカンマか改行を入れてもらえると見やすいかと

**Comment by Yangsin** [comment]
ご意見あリがとうございます。以下のような情報もありますので、あわせて確認します。
http://coelacanth.jp.net/heteml_can_not_install_eccube3/

いつもご意見いただきあリがとうございます。よろしければ以下のGitterにもご参加くださいませ。
https://gitter.im/EC-CUBE/ec-cube?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ryo-endo** [comment]
@shhirose 
遅くなりました。公式サイトのほうも下記のような感じで記載しようと思っていますので取り急ぎご連絡です。
http://ec-cube.github.io/requirement.html

**Comment by ryo-endo** [comment]
公式サイトのシステム要件ページ更新しました。

**Comment by ttsuru** [comment]
@ryo-endo 
podになってます！

**Comment by ryo-endo** [comment]
@ttsuru 
github.ioのほうですね。お恥ずかしい...ありがとうございます。直しておきます。
