### ISSUE TITLE
ブロック管理で編集を行うとダブルクォーテーションやシングルクォーテーションがエスケープ処理されてしまう

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#645]
開発コミュニティより。
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&order=ASC&topic_id=16277&forum=11

登録する前は、
```
 <div class="header_logo_area">
    <p class="copy">くらしを楽しむライフスタイルグッズ</p>
    <h1 class="header_logo"><a href="{{ url('homepage') }}">{{ BaseInfo.shop_name }}</a></h1>
</div>
```
と正常に表示されるが、登録ボタンを押すと、
```
<div class=\"header_logo_area\">
    <p class=\"copy\">くらしを楽しむライフスタイルグッズ</p>
    <h1 class=\"header_logo\"><a href=\"{{ url(\'homepage\') }}\">{{ BaseInfo.shop_name }}</a></h1>
</div>
```
とエスケープされてしまい、フロント画面でシステムエラーが発生する。

**Comment by k-yamamura** [comment]
php環境が5.3でmagic_quotes_gpcがonの時のみ発生するため対応不要

**Comment by nobuhiko** [comment]
PHP5.3 ってサポート対象じゃないですっけ？

**Comment by k-yamamura** [comment]
php5.3.9以上が対象です。

**Comment by nobuhiko** [comment]
5.3.28 (Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, mysql, mysqli, session, PDO, pdo_sqlite, standard, posix, Reflection, Phar, SimpleXML, soap, sockets, SQLite, exif, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, apache2handler, imap, yaz, mcrypt, gettext, pgsql, pdo_pgsql, pdo_mysql)

register_globals off で発生しました

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
magic_quotes_gpcではなくてですか？？

**Comment by nobuhiko** [comment]
@shinichi-takahashi 失礼しました、 magic_quotes_gpc On でした。MAMPのデフォルトでONになってるんですね

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
すみません。手元のMAMPが5.5/5.6しかなく確認できないのですが、
magic_quotes_gpcをOffにしても再現されますか？

**Comment by nobuhiko** [comment]
@shinichi-takahashi 
htaccess に php_flag magic_quotes_gpc Off で再現しなくなりました

**Comment by shinichi-takahashi** [comment]
@nobuhiko 
ご検証いただき、ありがとうございます！
.htaccessに書いて於いたほうがよさそうですね。
5.4以降では存在しない設定値なので気持ち悪いかもしれませんが・・・

**Comment by k-yamamura** [comment]
magic_quotes_gpcをOnにしているケースはほぼ想定されないためcloseします。
