### ISSUE TITLE
【質問】URL の指定が path ではなく url としているのは

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#650]
リンク先などの URL の指定が path ではなく、url で生成されているのが大部分ですが、これには理由があるのでしょうか。

Proxy サーバを挟み、URL が変わる場合に url で指定された部分ではリクエストする URL が変わってしまいます。

例えば以下のような形で Proxy を組んだ場合、Webサーバから見たリクエストは **http** となるため、HTML 内の URL が https ではなく http となってしまいます。

クライアント &lt;- (https) -&gt; Proxy サーバ &lt;- (http) -&gt; Webサーバ

url で指定しなければならない理由があれば教えていただけますでしょうか。

**Comment by k-yamamura** [comment]
こちらのコーディング規約にあります、

http://qiita.com/shinichi-takahashi/items/f696ed3f6bea546da722#命名規則

* TwigからRouting定義されたURLを取得する際は、{{ url('route_name') }} をつかう
    * HTTPSを確実にコントロールするため

というのがurlを使う理由でした。

相対パスにすることで上記現象が解消するのであれば、
今更urlをpathに置き換えるのは得策ではありませんので、
TwigのExtensionでurl関数を置き換えたものを作成する方法がベターだと思います。

**Comment by ttsuru** [comment]
これ、URLをtwigで書くのはあまり良くなかったかもしれないですね。
HTTPSにするのはSymfonyのFirewallで自動的にリダイレクトさせられます。

あと、画像系のAssetComponentの利用も含めて検討してもいいのではないでしょうか。
http://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component

現状のディレクトリの環境変数が多いのはaseetで減らせると思います。

**Comment by k-yamamura** [comment]
確かにtwigのExtensionを触るよりはFirwwallでhttpsにする方が遥かに楽でした。
失礼いたしました。

画像系もCDNを使ったりで似たような問題が出てきそうなので、
Assetに置き換えていきたいですね。

**Comment by ttsuru** [comment]
@k-yamamura 
:+1: 

2.7以上用のSilexのAsset providerもありました。
https://github.com/MatTheCat/silex-asset-provider

**Comment by shhirose** [comment]
新しく解決用の Issue を上げましたので、こちらの質問の Issue は Close します。
ref #916
