### ISSUE TITLE
form出力時に{{ form_rest(form) }}を記載する

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#653]
現状、FormBuilderにて構築したFormを `{{ form_widget(form.xxx) }}` として出力していますが、これだけだとFormExtensionで拡張した際に、テンプレートの拡張も必要になり、form_widgetの恩恵のひとつを受けられません。

form出力の末に `{{ form_rest(form) }}` とすることで、拡張が非常に容易になるため、formを描画している全てのページに記載したいです。
具体的なメリットは、以下の `2.` の処理をまったく記載しなくてよくなります。

1. FormExtensionで対象となるFormを拡張
2. RenderEventでテンプレートを拡張
3. Middlewareで拡張したFormの値を加工・登録

**Comment by ttsuru** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by k-yamamura** [comment]
例えばA画面とB画面で共通のFormTypeを使っている画面があり、
A画面では必要な項目がB画面では必要なかった場合、
form_restを記述するとB画面でも表示されてしまいますが、
そもそもFormTypeを共通で使う方法が適切ではないんですかね?

**Comment by shinichi-takahashi** [comment]
#587 こちらと重複していたので閉じます。失礼いたしました。
