### ISSUE TITLE
商品の規格設定

### ISSUE THREAD

**Issue by TakaYasu1984** [EC-CUBE/ec-cube#657]
商品の規格設定が更新できない場合があります。

規格1と規格2の組み合わせで商品規格件数が少ない場合は正常に動作しますが
商品規格件数が多い場合（128件の時 ※閾値は不明）に正常に更新できません。

`ProductClassController.php`まで到達していないようですが調べ切れていません。

**Comment by migarashi47** [comment]
98件が閾値ですね。
おそらく以下の事象と同様だと思います。
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=10208&forum=11

**Comment by ttsuru** [comment]
これ、UI自体を変えるしか方法ないですよね・・・
2系では規格が多い場合は
規格種類選択(カラー/サイズなど)→規格選択(SML/赤白など)→規格一覧表表示
とかってカスタマイズしてましたよね・・・

**Comment by TakaYasu1984** [comment]
@migarashi47 
提示していただいた事象と同様の内容でした。
使用しているサーバーが`php.ini`の設定を変更可能なサーバーでしたので
`max_input_vars`の設定値を大きくしたところ更新ができるようなりました。

@ttsuru 
`php.ini`の設定を変更する方法ではいたちごっこになる可能性があるので
UI自体を変更しないと根本的な解決にならないですかね・・・

**Comment by nanasess** [comment]
PHP 自体の制約に因るものですので bug のラベルをはずしておきます。

**Comment by Yangsin** [comment]
#1939 で集約します。
