### ISSUE TITLE
オリジナルブロックの生成箇所と参照の不一致

### ISSUE THREAD

**Issue by poego** [EC-CUBE/ec-cube#669]
開発フォーラムで投稿がありました。

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16292&forum=8&post_id=72217#forumpost72217

管理画面からテンプレートを作成した場合の生成箇所と参照パスが違っているではないでしょうか？

**Comment by aminotsukasa** [comment]
ブロック編集時のtwigファイルは
app/template/ (削除不可なもの)
html/user_data/block (削除可能なもの)
に出力されますが、

application.php内のtwigのテンプレート検索パスに
html/user_data/
がないのでこけているようです。

**Comment by aminotsukasa** [comment]
本件 #669 にて対応中です
（referenced が付かないので追加）

**Comment by nobuhiko** [comment]
referenced はコミットに ref #688 ってしないからな気がしますが

**Comment by chihiro-adachi** [comment]
#688, #791 にて対応済
