### ISSUE TITLE
商品一覧の表示件数とページングの不具合

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#670]
商品一覧で表示される商品数が検索件数よりも少なく、ページングをした際に、前のページで表示されていた商品も表示される。

デモ環境で再現しています。
検索件数は34件、表示数の上限は15件ですが、表示されているのは9商品のみです。
http://demo3.ec-cube.net/products/list?category_id=&name=&pageno=1

1ページ目にあったフォークが2ページ目にも表示されています。
http://demo3.ec-cube.net/products/list?category_id=&name=&pageno=2

<code>ProductRepository#getQueryBuilderBySearchData</code> の<code>$qb->orderBy</code>が原因と思われます。
SQL 上では DISTINCT していますが、商品規格の項目で orderBy をしているため、SELECT句 に　ORDER BY のカラムが出現し、検索結果が商品情報の件数ではなく、商品規格の件数となってしまい、その状態で　limit、offset しているようです。

**Comment by ttsuru** [comment]
SELECTとCOUNTで別々のクエリにするかgetQueryBuilderBySearchDataを見直す必要がありそうですね

**Comment by aminotsukasa** [comment]
問題のクエリで、
SELECT DISTINCT d0_.product_id AS product_id0, d1_.price02 AS price021 FROM ......
price02の部分がどこで生成されているかxdebugを突っ込んで調べてみたのですが、
結局DQLからSQLに変換する箇所で生成されているようです。

http://qiita.com/imunew/items/a2062e58f9d444978282
とか参考にして生成されたSQLをHint修正とかでしょうか。。。。

**Comment by chihiro-adachi** [comment]
#1034 にて修正.
