### ISSUE TITLE
特定商取引法の表示不具合

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#674]
- 住所情報の表示が他の画面と異なる
- フロント側で予備項目が表示されている。
- 住所のエラー表示位置がおかしい
- 電話番号のエラーメッセージが表示されない

**Comment by muramoto-keisuke** [comment]
電話番号の市外局番桁数チェックが2～4桁になっているのでフリーダイヤルが登録できませんでした

**Comment by chihiro-adachi** [comment]
#851 にて修正いただきましたので、クローズします。
