### ISSUE TITLE
レイアウト設定：ブロックをすべて未使用にすると、ブロックが消える

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#680]
- すべてのブロックを未使用ブロックに移動し、登録
- ブロックが消え、復元できなくなる

※dtb_block_positionに1つでも登録していれば、残りは未使用ブロックとして表示されるため、joinしている箇所で問題がありそう。

**Comment by nanasess** [comment]
#686 にコメントしましたが、すでにマージされていましたので、こちらにもコメントしておきます。

- わざわざ Repository を経由している理由は何でしょうか？
- Block のインスタンスを生成する必要があるのでしょうか？
- `$ids[] = \Eccube\Entity\Block::UNUSED_BLOCK_ID;` で良いのではないでしょうか？

**Comment by aminotsukasa** [comment]
これは確かにに意図不明なコードですね
もう少しわかりやすく書いたほうがいいです

**Comment by tamagoya** [comment]
すいません、Synfonyの使い方を理解しておりませんでした。
Repositoryは、Entityのラッパー的に利用すると思っていたのですが、RepositoryはEntityオブジェクトから永続化層(DB)から取り出すだけなんですね。
ご指摘いただいた通り、Repositoryを経由せず直接呼び出した方が良いと思います。
また、インスタンス化する必要がないのは、その通りだと思います。再修正してプルリクを出します。

**Comment by nanasess** [comment]
@tamagoya 
Symfony の使い方というより、どのようなアーキテクチャにするか、といった問題ですね。

> RepositoryはEntityオブジェクトを永続化層(DB)から取り出すだけなんですね。

Repository が永続化層で、DB は、その中で扱うデータソースなのだと思っていますが、ちゃんと説明したドキュメントも見つからず、意見が別れるところですね。

また、 ID というのは Identifier なので、 Value Object として扱うのが正しいのでしょうけど、どのような実装にしたら良いか。。
少なくとも、 Repository から取り出すものではないと思います。

**Comment by shinichi-takahashi** [comment]
@nanasess 

> ちゃんと説明したドキュメントも見つからず

DDDのリポジトリパターンについては、「ドメイン駆動設計」「リポジトリ」あたりをキーワードに情報を探ると出てきますよ。
（といっても、エリック・エヴァンスがそう言ってるいる、という文献がほとんどですが）
http://phpmentors.jp/post/88996330583/ddd-repository

**Comment by nanasess** [comment]
@shinichi-takahashi 
> DDDのリポジトリパターンについては、「ドメイン駆動設計」「リポジトリ」あたりをキーワードに情報を探ると出てきますよ。

言葉足らずですみません。
Symfony の公式ドキュメントに見つからないという意味です。

**Comment by tamagoya** [comment]
#738 にてmasterにマージされたため、このissueはクローズさせて頂きます。
