### ISSUE TITLE
EC-CUBEパッケージ版(zip)でvendor/bin配下のファイルに対してシンボリックリンクが貼られていない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#684]
tar.gz版の場合、vender/bin配下のファイルに対してシンボリックリンクが貼られています。

**Comment by k-yamamura** [comment]
追記です。
composerでインストールした場合、
doctrine -> ../doctrine/orm/bin/doctrine
等のように適切にシンボリックリンクは貼られますが、
zip版だと実ファイルになっています。

zip圧縮した際にシンボリックリンクが実ファイルとして圧縮されているため、
シンボリックリンクはシンボリックリンクとして圧縮する必要があります。

**Comment by Yangsin** [comment]
勘違いならすみません。
Windowsでの利用を考えると実ファイルとして用意されるべきなのかとおもいますが、いかがでしょうか。

**Comment by k-yamamura** [comment]
実ファイルでも問題ありませんが、
vendor/bin/doctrine.phpに
```
(@include_once __DIR__ . '/../vendor/autoload.php') || @include_once __DIR__ . '/../../../autoload.php';
```
という部分があり、元々は
```
vendor/doctrine/orm/bin
``` 
が実ファイルのためパスを考慮する必要が有ります。

**Comment by aminotsukasa** [comment]
補足しますと
tar.gz版のアーカイブであれば元々のシンボリックリンクを忠実に再現してくれるので問題ないのですが、zip圧縮した時にシンボリックリンクが正しく圧縮されず（もしくはzip展開時にシンボリックリンクの作成に失敗）しているため圧縮前のシンボリックリンクが展開後に再現されていません。

で、このファイルが単なるファイルなら問題なかったのですが、このファイルに記述されているプログラム内部の処理で自分自身がシンボリックリンクか実ファイルかで挙動が異なる部分があります。
そのためファイル自体としては配置されるのですが、プログラムとしては正しい動作をしない挙動になります。

このファイルはDoctrineを普通にcomposer経由でインストールするとvendor以下に生成されるファイルなので、実ファイルでも正しく動作するようにプログラムを書き換えるのはちょっと現実的ではないように思います。
zip圧縮時にシンボリックリンクが正しく圧縮されるよう圧縮ツールの設定変更がとりあえずの方法だと思います。

**Comment by nobuhiko** [comment]
http://qiita.com/mpyw/items/553c4f34cb43783e1449
なんかこういうのを使って（作って）ファイル数減らす・シンボリックリンクの問題を減らすなどの工夫が必要な気がします

**Comment by ttsuru** [comment]
:+1:
ちょうど同じURLを @Yangsin さんに展開してました。
Packagist の ec-cube/ec-cube を vendor 以下でも動くようにすると簡単に ec-cube.phar が作れると思います。

以下のような構成ですかね・・・
```
+ec-cube
  +app
  +html
  +ec-cube.phar
```

**Comment by nobuhiko** [comment]
@ttsuru 
（WPみたいに）自動アップデートされるから、そのものは触るなというのがちゃんとアナウンスされればそれでもいい気はしますが、現状のプラグインや管理画面だとそこまでしちゃうとツライ気がしますねぇ。。
そういう人はgithubから自力で入れればいいのかもですが、うーん・・・

**Comment by ttsuru** [comment]
@nobuhiko 
そうですねぇ・・・
ただ、phar配布版はvendor以下にec-cubeを移動してまとめてしまうのが一番配布としては綺麗かなとか思います。

pharだと ``html/index.php`` の機能も ``ec-cube.phar`` に移動できるんですよね・・・

**Comment by nobuhiko** [comment]
@ttsuru 
よくある、EC-CUBEがバグっている、をフォーラムからのアドバイスで直せないのもツライ気がします
すぐに次のバージョンをリリースしてくれるか、品質が担保されればそれでいいんですが〜

**Comment by ttsuru** [comment]
そこですね・・・
あとは、srcを空ディレクトリで用意して、autoloadに追加しとくとかですかね。
そうすればパッチ当てるファイルだけアップすればどうにかなります。

**Comment by k-yamamura** [comment]
表題の件については対応済みのため一旦Closeとさせて頂きます。
