### ISSUE TITLE
管理画面のシステム管理－特定商取引法画面の不具合

### ISSUE THREAD

**Issue by ActiveFusion** [EC-CUBE/ec-cube#689]
管理画面のシステム管理－特定商取引法画面について、全項目を入力して「登録」ボタンをクリックしても、「登録できませんでした。 」というエラーメッセージで登録が完了しない。

**Comment by Yangsin** [comment]
こちら手元で再現できておりません。
お使いの環境について詳細をいただけますと幸いです。

**Comment by nobuhiko** [comment]
![_-_ec-cube](https://cloud.githubusercontent.com/assets/604492/9840836/f3db8a5a-5ad2-11e5-80b3-1f487a8fa460.png)

TELが必須、かつフリーダイヤルを受け付けない仕様なのにエラーメッセージが出ていないことが原因かと思う

**Comment by ActiveFusion** [comment]
確かに、TELの市外局番の項目を３桁までにしたら登録できました。
また、FAXの市外局番は３桁までしか入力できないように固定になっているようです。

ご確認の程、よろしくお願い致します。

**Comment by chihiro-adachi** [comment]
#764 で修正いただきましたのでクローズします。
