### ISSUE TITLE
会員登録時に日本語メールアドレスを入れるとシステムエラーが発生する。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#692]
#407 と同様のエラーメッセージが発生します。
※エラーの内容は同じですが、Issue の内容としては異なるので別で作成しました。
※会員登録以外でもメールを送信する部分すべてで発生する可能性があります。

手順
1. 会員情報入力画面でメールアドレスに「ああああ@example.com」を入力
2. 確認画面まで行き（validation は通過します。）、登録ボタンを押下するとシステムエラー画面へ遷移

エラーの内容は以下のとおりです。（ホスト名は存在するホスト名を使用しています。）
<pre>
Swift_RfcComplianceException: Address in mailbox given [ああああ@example.com] does not comply with RFC 2822, 3.6.2. (uncaught exception) at C:\workspace\c.next-ec\c.next-ec\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\Headers\MailboxHeader.php line 348 {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [ああああ@example.com] does not comply with RFC 2822, 3.6.2. at C:\\workspace\\c.next-ec\\c.next-ec\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\Headers\\MailboxHeader.php:348)"} []
</pre>

<code>Symfony\Component\Validator\Constraints\Email</code>では RFC 2822 の検証は行っていないためにメール送信時に Swift_Message で上記のエラーが出ているようです。
※<code>\Egulias\EmailValidator\EmailValidator</code> を入れるとやってくれるんですかね・・？

ドットの連続や、「@」前のドットも違反するはずです。
理想としては環境構築する側で RFC 2822 を準拠するか、しないかを選択できるのが一番かな、と今までの経験から（個人的には除外したいですが）思います。

**Comment by nobuhiko** [comment]
\Egulias\EmailValidator\EmailValidator を試してみましたが日本語に関してはダメなようです

**Comment by shhirose** [comment]
メールアドレスに「t..est@example.com」と入れると RuntimeException がスローされてしまいますね。（日本語も同じ）
今のところ RFC 違反のメールをチェックする方法が無いですね。

**Comment by t-nagahashi** [comment]
メールアドレスに「t..est@example.com」を入れてみましたが、
管理、フロント側ともに、サーバ側のエラーチェックで、チェックできているようです。
■管理側
![default](https://cloud.githubusercontent.com/assets/13776434/10362912/3ed10a0e-6dec-11e5-8f79-72b6193b65c6.PNG)
■フロント側
![default](https://cloud.githubusercontent.com/assets/13776434/10362916/42297970-6dec-11e5-88d2-546677e02b75.PNG)

**Comment by shhirose** [comment]
どうも私の環境の問題だったようです。
composer を最新にして、migrate も行ってから実行したらうまくいきました。
お騒がせしました。

よって、この Issue は Close します。

**Comment by nobuhiko** [comment]
#829 で一応、日本語入力出来ないようにと、 strict => true にしたので、RFC違反チェックはされてると思います
ただ、 a@a が通るようになった気はします
