### ISSUE TITLE
決済でエラーになった場合の対応

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#693]
決済会社によっては、決済エラーになった場合、受注番号が欠番となってしまい、新たな番号を発行しなければならない場合があります。
2系の場合は、 nextval() でシーケンス値を取得できましたが、
現状、 Order を一旦キャンセルして、作成し直す or  別途決済用の番号を設けるしかないのでしょうか？

**Comment by chihiro-adachi** [comment]
現状ではシーケンス値の取得を行うケースもあまりないため、クローズします。
