### ISSUE TITLE
ログの設計指針

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#695]
ログ設計指針を作成し、指針に沿ったログ出力を行なう

### 参考

- [ログ設計指針](http://qiita.com/nanasess/items/350e59b29cceb2f122b3)

**Comment by nobuhiko** [comment]
管理画面からの参照もお願いします。。

**Comment by nanasess** [comment]
管理画面のログ参照機能は、プラグインでやろうということで削除されたんでしたっけ？

**Comment by k-yamamura** [comment]
#1171 で対応のためcloseします。
