### ISSUE TITLE
Yaml のキャッシュ

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#696]
Slack #test の議論より。

Entity の Yaml を毎回パースしてそう。
xdebug の結果を貼っておきます。

![yaml](https://cloud.githubusercontent.com/assets/815715/9597676/219ed6f4-50bf-11e5-9aae-abaa818d3705.png)

**Comment by nanasess** [comment]
@nobuhiko wrote:
動くのかは知らないけどcacheまで実装してそうなやつ
- <https://github.com/affinitidev/silex-config>
- <https://github.com/alvk4r/silex-yamlconfigserviceprovider>

**Comment by nanasess** [comment]
これの、
https://github.com/dflydev/dflydev-doctrine-orm-service-provider

- metadata_cache
- query_cache
- result_cache
- hydration_cache 

が使えそうなのですが、うまくキャッシュを読んでくれなくて難儀しています。。

**Comment by nanasess** [comment]
参考
<https://github.com/evanmaastrigt/kwetal-silex/blob/e1200e6335c92e0abdfa86a94dbb9e8ca2c75442/app/config/service/005-doctrineOrmService.php>

**Comment by nanasess** [comment]
キャッシュの種類は、以下が使用できる模様。
デフォルトは array なので、メモリ上にしかキャッシュしないみたいです。

- array
- apc
- xcache
- memcache
- memcached
- filesystem
- redis

apc と filesystem を試してみていますが、キャッシュは作られるものの、目立ったパフォーマンス向上は見られません。。

**Comment by nanasess** [comment]
redis の例

```diff
diff --git a/src/Eccube/Application.php b/src/Eccube/Application.php
index 08dd7c3..ae5bc44 100644
--- a/src/Eccube/Application.php
+++ b/src/Eccube/Application.php
@@ -439,6 +439,26 @@ class Application extends ApplicationTrait
             'orm.proxies_dir' => __DIR__ . '/../../app/cache/doctrine',
             'orm.em.options' => array(
                 'mappings' => $ormMappings,
+                'metadata_cache' => array(
+                    'driver' => 'redis',
+                    'host' => '127.0.0.1',
+                    'port' => '6379'
+                ),
+                'query_cache' => array(
+                    'driver' => 'redis',
+                    'host' => '127.0.0.1',
+                    'port' => '6379'
+                ),
+                'result_cache' => array(
+                    'driver' => 'redis',
+                    'host' => '127.0.0.1',
+                    'port' => '6379'
+                ),
+                'hydration_cache' => array(
+                    'driver' => 'redis',
+                    'host' => '127.0.0.1',
+                    'port' => '6379'
+                ),
             ),
         ));
     }

```

![default](https://cloud.githubusercontent.com/assets/815715/9814142/a85384ec-58c6-11e5-919a-ae508117cc6f.PNG)

商品一覧なのですが、 少し改善しました。
しかし paginator がうまくキャッシュを使ってくれないようです。

**Comment by ryo-endo** [comment]
3.0.11で対応済み。
