### ISSUE TITLE
3.0.3でプラグイン固有設定へのリンクが表示されない

### ISSUE THREAD

**Issue by fors2** [EC-CUBE/ec-cube#702]
下記URLを参考にプラグインの固有設定画面を設定しました。
https://github.com/EC-CUBE/ec-cube/wiki/Plugin%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%A9%E3%83%BC%E4%BB%95%E6%A7%98

3.0.1の時は「プラグイン一覧」に「設定」リンクが表示されていたのですが、3.0.3では表示されていません。

プラグインでは下記設定しています。
```
プラグインファイル構造
|--Controller
|  |--ConfigController.php
|--PluginManager.php
|--ServiceProvider
|  |--HogeServiceProvider.php
|--Hoge.php
|--config.yml
```

```
config.yml
name: Hoge
service: 
    - HogeServiceProvider
```

```
ServiceProvider
class HogeServiceProvider implements ServiceProviderInterface
{

    public function register(BaseApplication $app)
    {
        $admin_dir = '/' . trim($app['config']['admin_route']);
        $app->match($admin_dir.'/plugin/Hoge/config', '\\Plugin\\Hoge\\Controller\\ConfigController::index')->bind('plugin_Hoge_config');
    }
```

3.0.1から3.0.3ではプラグインのアップロード先が
「app/Plugin/」から「html/user_data/Plugin」に変更があるようですが、関係がありますか。
上記の理由から不具合なのかどうかの切り分けができない状態です。

どのようにすれば設定リンクが表示されるようになりますでしょうか。

よろしくお願い致します。

**Comment by shhirose** [comment]
私の方では正常に設定リンクが表示されました。
<code>config.yml</code>に<code>code</code>がないようですが、実際にはありますか？
（ないとインストール自体が失敗するはずですが）

ロジック上は設定リンクを出すだけであれば以下の2点だけで表示されると思います。
- config.yml に code を設定
- plugin_{config.yml のcode}_config の bind を設定

以下のような形になっていれば、3.0.3 では表示されると思います。
config.yml
<pre>
name: Hoge
code: Hoge
version: 1.0.0
service:
    - HogeServiceProvider
</pre>

bind
<pre>
$app->match('/admin/plugin/Hoge/config', '\\Plugin\\Hoge\\Controller\\ConfigController::index')->bind('plugin_Hoge_config');
</pre>

あとは、プラグインを有効にしないと設定リンクは表示されませんが、そこは大丈夫でしょうか？

**Comment by fors2** [comment]
検証頂きましてありがとうございます。

> config.ymlにcodeがないようですが、実際にはありますか？
config.ymlから抜粋して書いてしまいましたが、codeの記載はありました。

> あとは、プラグインを有効にしないと設定リンクは表示されませんが、そこは大丈夫でしょうか？
ご指摘ありがとうございます。有効にしている状態ですが表示されておりませんでした。


もしかしたら3.0.1から3.0.3にバージョンアップした際に
何か手順が間違っていて正常な状態ではない可能性があるのではないかと思います。
（srcを上書きしてDBの不足カラムを追加してバージョンアップ作業をしました。）

**Comment by shhirose** [comment]
> もしかしたら3.0.1から3.0.3にバージョンアップした際に何か手順が間違っていて正常な状態ではない可能性があるのではないかと思います。
> （srcを上書きしてDBの不足カラムを追加してバージョンアップ作業をしました。）

まずは、3.0.3 を別にインストールして、そっちにプラグインをインストールするのが切り分けをする上ではいいかもしれませんね。（面倒かもしれませんが・・

**Comment by fors2** [comment]
別にインストールすると正常にプラグインの設定リンクが表示されました！

**Comment by Yangsin** [comment]
@fors2 問題解決されたようでしたらこちらクローズをお願いします。
