### ISSUE TITLE
http:// と https:// で異なるサブドメインへのインストール

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#703]
#431 にて、 Cookie のドメイン指定が削除されていますが、以下のように、 http:// と https:// で異なるサブドメインへのインストールはサポートされなくなったということでよろしいでしょうか？

- http://www.example.com/
- https://secure.example.com/

**Comment by Yangsin** [comment]
3.0では、常時SSLにもなる様な仕様になっており、SSL証明書自体も数千円の安価なものもふえていますので、FQDNが異なる運用はサポート外としたいと思っています。
レンタルサーバーでも、SSLで異なるサブドメインなどを利用するケースは減っている認識です。
以降などの場合、URLをリダイレクトするなどの対応が必要にはなるかと思いますが、ご懸念などありますでしょうか。

**Comment by nanasess** [comment]
「常時SSLという仕様だよ」というのを、きちんとアピールした方が良いと思われます。

また、多くのレンタルサーバーで、 www の有無にかかわらず、サイトにアクセスできるようになっていて、開発コミュでも何度も質問が繰り広げられていたので、インストール先のドメインは明示できた方が良い気がします。

**Comment by Yangsin** [comment]
常時SSLへの仕様変更等、インストール時の設定項目の仕様をまとめる感じで用意したいですね。昔のwikiみたいなのを用意しようと探してます。

wwwの有無に関わらずアクセスできるというのはたしかに、レンタルサーバーに関わらずありますね。

インストール時にURLを指定せずに、インストール時にアクセスしたURLで登録されるため、意識しづらくなってますね。
インストール時に画面に表示して、インストール後、それ以外のFQDNでのアクセスはリダイレクトされる
くらいが、みんな楽になるような気がしますね。

**Comment by nanasess** [comment]
> 昔のwikiみたいなのを用意しようと探してます。

情報が拡散する + メンテされないメモが量産されるのは良くないので、  github の wiki ではだめなんですかね。

**Comment by Yangsin** [comment]
取り急ぎは、GitHubのWikiだと思ってますが、階層的に情報をまとめられないので、情報がふえるとすごく見づらい印象です。
また、GitHubのWikiが権限付与ができないので、皆さんとコラボできない。。。
Qiitaは、書きやすいのですが、メンテされないメモなので。それも合わないなと。

**Comment by nanasess** [comment]
最近は Github Pages  使ってるところも多いですね。

**Comment by Yangsin** [comment]
そうなんですよ。

http://ec-cube.github.io/

みたいなのとか、試してくれてるんですが、まだまだ勝手がわからず運用していくイメージが作れてないです。

**Comment by nanasess** [comment]
http:// と https:// で異なるサブドメインへのインストールはサポートされなくなったということで、クローズします。
