### ISSUE TITLE
購入完了画面での受注IDの取得

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#706]
購入完了画面に、コンバージョンタグを埋めようとした場合、現状プラグインを(かなり)頑張って作るしかない。

せめて、受注IDくらいは標準で取れるようにしておきたい。

**Comment by shinichi-takahashi** [comment]
@nanasess 

受注IDが簡単に取れるかは追わないとすぐ回答できませんが、
以下でリダイレクト時のみコンバージョンタグを埋め込んでレンダリング
という処理をいれることができます。
受注IDが必要ではない（＝完了ページに正当にアクセスしたかどうかを取得するだけ）の場合は、
こちらの手法が有効かと思います。

```
$response = $event->getResponse();
if ($response instanceof RedirectResponse) {
    // リダイレクト時のみコンバージョンタグを埋め込む
}
```

**Comment by nanasess** [comment]
@shinichi-takahashi 
コンバージョンタグくらいは、 PHP のわからない店舗オペレーターでも簡単に入れられるようにしたいのです。
タグを埋めるたびに開発依頼をするのは辛い :dollar:

**Comment by k-yamamura** [comment]
3.0.5から対応済みですのでcloseします。
