### ISSUE TITLE
金額の桁数チェック

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#713]
1. 購入価格を 999999999円に設定
2. 100 個カートに投入
3. 「レジに進む」ボタンをクリックすると、システムエラーになる。

**Comment by casek** [comment]
再現しませんでした。
レジに進むと、添付画像の様になり、右サイドバーの数値がおかしい気がします。
左のサムネール横の数字は999999999*1.08で合ってますね。
もう一つの添付ファイルは価格4桁の場合のレジ表示ですが、こちらは右サイドバーの数値もあっています。

![screen shot 2015-10-08 at 9 53 58](https://cloud.githubusercontent.com/assets/238605/10355092/892408d0-6da2-11e5-909c-e6c312af4014.png)


![screen shot 2015-10-08 at 9 49 11](https://cloud.githubusercontent.com/assets/238605/10355043/ebfeca22-6da1-11e5-89f8-aea141edd77a.png)

**Comment by nanasess** [comment]
dtb_order.subtotal など、金額を扱うカラムが numeric(10) になっているため、 どこかのタイミングで DB エラーになると思うのですが、そのまま購入できてしまいますか？

**Comment by casek** [comment]
そうですね、購入できてしまいます。
注文確認メールでも、レジ画面と同じ様に合計金額は変ですね。

dtb_order.subtotalで桁あふれだとすると、商品登録時に「価格が高すぎ」とエラー出すって仕様なのでしょうか？

![screen shot 2015-10-08 at 10 15 02](https://cloud.githubusercontent.com/assets/238605/10355317/7b837b36-6da5-11e5-9800-6f6d7dad5ac4.png)

**Comment by nanasess** [comment]
手元の MySQL 5.1.72-community では DB エラーが発生しました。
`SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'subtotal' at row 1`

> 商品登録時に「価格が高すぎ」とエラー出すって仕様なのでしょうか？

商品登録時にエラーを出すのは難しいため、購入時に小計が10桁を越えるようならエラーにするしかないと思われます。

**Comment by casek** [comment]
お、こちらmysql5.5です。
なるほど、確かに購入時にエラーの方がフロー的にも正しい感じがします。
rockonの方とも話して、仕様としてどうするか決めて、作業しますね。

**Comment by nanasess** [comment]
PostgreSQL 9.3.5 でも DB エラーになりますね。

`SQLSTATE[22003]: Numeric value out of range: 7 ERROR:  numeric field overflow DETAIL:  A field with precision 10, scale 0 must round to an absolute value less than 10^10.`

MySQL5.5 は勝手に丸めてしまうのですね。。。

**Comment by casek** [comment]
おおw bug改修としては、もう選択を間違えてたかもですねw
こちらでも確認してみます。

**Comment by casek** [comment]
というわけで、カートに入れるタイミングでチェックいれることになりました。
合計が999,999,999以上になるようだったら、エラーメッセージだしますが、入れられる分だけは入れるというスタンス。。。在庫切れチェックや、販売制限数チェックと同じ形でチェック実施します。

**Comment by chihiro-adachi** [comment]
#926 で修正いただきましたのでクローズします。
