### ISSUE TITLE
非公開商品のエラーメッセージが適切ではない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#714]
1. 管理画面にて、商品を非公開に設定
2. カートに投入
3. 「この商品は同時に購入することはできません。 」というエラーが表示される

**Comment by casek** [comment]
これはすでに直っている気がしますー。
現在のエラーメッセージ「この商品は現在購入することはできません。」

**Comment by chihiro-adachi** [comment]
「この商品は現在購入することはできません。」のメッセージに変更されていることを確認しましたので, クローズします。
