### ISSUE TITLE
[質問]購入者が注文をキャンセルできる機能の実装予定はありますでしょうか

### ISSUE THREAD

**Issue by muramoto-keisuke** [EC-CUBE/ec-cube#716]

**Comment by Yangsin** [comment]
現時点ではありませんが、ソース提供いただければ採用できる可能性は十分にあります。
キャンセル不可という運用のショプもあるので、デフォルトで有効な機能として実装するかは検討の余地があると思います。

**Comment by muramoto-keisuke** [comment]
ご回答ありがとうございました

**Comment by Yangsin** [comment]
@muramoto-keisuke  こちら質問のみとして問題なければ、クローズをお願いします。

**Comment by muramoto-keisuke** [comment]
@Yangsin 失礼しました。クローズしました

**Comment by Yangsin** [comment]
ありがとうございます。m(__)m
