### ISSUE TITLE
商品登録画面へのプラグイン追加について

### ISSUE THREAD

**Issue by ActiveFusions** [EC-CUBE/ec-cube#718]
管理画面の商品登録画面（新規）時へのプラグイン開発をしておりますが、プラグイン側で新規登録商品のproduct_idを取得する方法はないでしょうか？

もし、方法があればご教示の程よろしくお願い致します。

**Comment by shinichi-takahashi** [comment]
@ActiveFusion 

以下が参考になるかと思います。
リダイレクト先のIDを取得することで、新規時もIDを取得できます。
https://github.com/EC-CUBE/related-product-plugin/blob/master/Event.php#L101

**Comment by ActiveFusion** [comment]
@shinichi-takahashi 

ありがとうございます。
無事にproduct_idを取得することができました。
