### ISSUE TITLE
［質問］コンテンツ管理>ページ管理の一覧について

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#720]
コンテンツ管理>ページ管理　でのページ一覧ですが、
デフォルトテンプレートに入っているのに、ここに出ていないファイルが結構あります。
このファイルは意図的にページ管理で触ることができないようにしているのでしょうか

下記、ページ管理一覧に出てこないファイル一覧です
block.twig
default_frame.twig
error.twig
pagination.twig
Contact/confirm.twig
Entry/confirm.twig
Forgot/complete.twig
Forgot/index.twig
Forgot/reset.twig
Form/form_layout.twig
Help/guide.twig
Mail/contact_mail.twig
Mail/customer_withdraw_mail.twig
Mail/entry_complete.twig
Mail/entry_confirm.twig
Mail/forgot_mail.twig
Mail/order.twig
Mail/reset_complete_mail.twig
Mypage/delivery_edit.twig
Mypage/error.twig
Mypage/withdraw_confirm.twig
Mypage/navi.twig
Mypage/mail_view.twig
Shopping/shipping_edit.twig
Shopping/shopping_error.twig

**Comment by kamawi** [comment]
特によく使いそうな「ご利用ガイド（Help/guide.twig）」は、
管理画面でのレイアウト編集もできないのでちょっと不便です。
（そしてヘッダーもフッターもメニューもなにもなく中身しかない状態にしかなりません）

今のところは、これは無かったページと考えて、
しばらくは新規ページを作って耐処する方向で考えるべきでしょうか

**Comment by Yangsin** [comment]
ページ管理≠テンプレート管理 ですので、ページでないMail やform_layoutなどのテンプレートはここで扱うべきではないかと思っています。
ただ、ご指摘いただいているような ご利用ガイドなどのページはページ管理で扱えるようにするべきですね。。。

**Comment by shhirose** [comment]
ユーザーが表示できる画面を dtb_page_layout に登録しようと思ったのですが、確認画面系が軒並みレイアウト変更できないんですね。
※bind の値からブロックが適応されるので、入力画面のレイアウトが適応される。

確認画面もページ編集できるようにしたいのですが、確認画面も追加するのであれば、dtb_page_layout にレイアウト変更できるかどうかのカラムを追加して、レイアウト編集のリンクを不可するとかですかね？
※url カラムは適当な値を設定

**Comment by nobuhiko** [comment]
確認画面もURLを変える、がやっぱりスマートな気がします。
あとページタイトルとかも管理画面から変えられないの意味がわかりません

**Comment by shhirose** [comment]
@nobuhiko 
> 確認画面もURLを変える、がやっぱりスマートな気がします。

URLを変えるとなると結構修正が大変になりますね・・・

> あとページタイトルとかも管理画面から変えられないの意味がわかりません

確かにURLなどは変更できなくてもいいと思いますが、タイトルは変更できていいですね。

**Comment by k-yamamura** [comment]
3.0.5で見直しを行いましたのでcloseさせて頂きます。
タイトルについては別途issueを作ります。
