### ISSUE TITLE
コンテンツ管理>ページ管理に載っているファイル名や場所が違う　等

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#721]
コンテンツ管理>ページ管理　のページ一覧に載っているファイル名や場所が違う気がするものや、
ファイル自体が見つからないものがあります。
ファイルは全てsrc/Eccube/Resource/template/default から探しています。
以下、その一覧です。

# ファイルの場所が違う（気がする）
## ご利用規約
* 管理ページでのファイル場所　Entry/kiyaku.twig
* 管理ページでのURL　http://hoge.xx/html 
* テンプレート内で見つけた該当しそうなファイル？の場所　Help/agreement.twig
* 該当しそうなURL　http://hoge.xx/html/help/agreement

## 商品購入/お届け先の複数指定 
* 管理ページでのファイル場所　Shopping/multiple.twig 
* 管理ページでのURL　http://hoge.xx/html 
* テンプレート内で見つけた該当しそうなファイルの場所　Shopping/shipping_multiple.twig
* 該当しそうなURL　不明

# 該当しそうなファイルが見当たらない
## お商品購入/支払方法・お届け時間等の指定 
* 管理ページでのファイル場所　Shopping/payment.twig
* 管理ページでのURL　http://hoge.xx/html/shopping/payment 

## ご商品購入/入力内容のご確認
* 管理ページでのファイル場所　Shopping/confirm.twig
* 管理ページでのURL　http://hoge.xx/html/shopping/confirm

**Comment by chihiro-adachi** [comment]
#1050 にて修正.
