### ISSUE TITLE
お問い合わせフォーム、お名前(フリガナ)が必須になってます

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#723]
お問い合わせフォーム、のお名前(フリガナ)が必須表示がありませんが、
未入力のまま確認ページに行こうとすると「このフィールドは入力必須です」という表示が出ます。

**Comment by nobuhiko** [comment]
@Yangsin 
これは、カナを必須と表示すべきか、それとも必須である必要が無い
どちらでしょうか？2系は必須っぽいです

**Comment by Yangsin** [comment]
２系では必須ですが、カナが必須である必然性はないと思いますがいかがでしょうか。

**Comment by nobuhiko** [comment]
@Yangsin 了解です、必須をなくすようにしました

**Comment by chihiro-adachi** [comment]
#830 にて修正いただいたため、クローズします。
