### ISSUE TITLE
商品登録時のカテゴリが見づらい

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#724]
商品登録時のカテゴリ表示についてです。
親カテゴリも子カテゴリもまとめて横並びなので、何がどの子カテゴリなのか分かりにくいです。
強いて言えば下層カテゴリになるほどチェックボックスとテキストの間が空いているので「これ子かなぁ」くらいで判別しています。
WordPressみたいに縦並びにならないでしょうか

**Comment by tomothumb** [comment]
同感です。
縦並びにして、ブロック内のスクロール式が良さそうですね。

現状、横並びで、
・1階層目は空白0こ
・2階層目は空白１つ
・n階層目は空白n-1こ
空白がつく状態。

縦並びになったら空白インデントが、階層を表すので見やすいなるとは思いますが、
全角スペースでインデントさせるのではなく、
　A：ラベルのタグにlevel1、level2とかclassを付与してcssで余白を取る
　B：divではなく、入れ子のリスト、ul>li>ul>liでインデント
のどちらか理想ですね。多分前者の方が柔軟性ありそう。

**Comment by tomothumb** [comment]
カテゴリ指定方法の一案です。
このデモページのMultipleの選択肢みたいなのとか。
https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html
実装も大変そうですけど・・

**Comment by ttsuru** [comment]
取り急ぎは、 Form Widgetからorder by の指定と、子階層の場合にはスペース２つ程度入れるなどでいかがでしょうか。
フロントのカテゴリ選択はそのような形で実装した覚えがあります。

**Comment by ttsuru** [comment]
refs https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Form/Type/SearchProductType.php#L44

**Comment by nanasess** [comment]
#1385 で対応済
