### ISSUE TITLE
［質問？］商品CSV登録時、複数の場合の「"」表記について

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#725]
商品CSV登録時、商品画像やカテゴリIDに「複数画像の場合画像ファイル名をカンマ区切りで「"」で囲んで設定」という但し書きがありますが、実際に「"」を入れるとエラーになりました。
また、商品マスターよりダウンロードしたCSVファイルにも「"」は入ってませんでした。
複数カテゴリ、画像共に同じエラーでした。
CSVファイルを編集した環境のせいでしょうか？

OSは Mac OS 10.10.5、　
編集ソフトは　Microsoft Excel for Mac 15.13.1（Office 2016 for Mac 内）です。

下記、入力例です
* エラー　→　“img01.jpg, img02.jpg”
* エラー　→　“img01.jpg”, “img02.jpg”
* OK　→　img01.jpg, img02.jpg

**Comment by Yangsin** [comment]
おそらく不具合と思われますが、環境に起因するものかもしれません。
該当のファイルを共有いただく事はできますでしょうか。

**Comment by kamawi** [comment]
商品マスターでダウンロードしたCSV（複数でも「"」がない）を以下にアップロードしました。
https://www.dropbox.com/s/fzastrkudb1oe9h/product_20150913162621.csv?dl=0

**Comment by k-yamamura** [comment]
@kamawi 
こちら現象が再現しませんでしたので申し訳ございませんがエラーとなったアップロード用CSVファイルを共有してもらえないでしょうか。
あるいは最新のmasterで再度確認してもらえないでしょうか。

こちらで確認したCSVファイルの内容は以下のとおりです。
```
商品ID,公開ステータス(ID),商品名,ショップ用メモ欄,商品説明(一覧),商品説明(詳細),検索ワード,フリーエリア,商品削除フラグ,商品画像,商品カテゴリ(ID),商品種別(ID),規格分類1(ID),規格分類2(ID),発送日目安(ID),商品コード,在庫数,在庫数無制限フラグ,販売制限数,通常価格,販売価格,送料,商品規格削除フラグ
6,2,ほげ,,,,,,,"img01.jpg,img02.jpg",,1,,,,,,1,10,200,400,,
```

**Comment by chihiro-adachi** [comment]
再現性なしということで、クローズさせていただきます。
