### ISSUE TITLE
商品マスターで商品一覧した時の表示件数が違う

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#726]
12点ほど商品を登録したあと、商品管理>商品マスター　で何も入力せず「検索する」で全件表示しました。
1ページ10件表示のはずが、最初のページに5件しか表示されません。
20件表示にした場合は全部表示されますので、こちらは合っていると思います。

また、何か条件を付けた場合（非公開のみ　など）も普通に表示されました。

**Comment by Yangsin** [comment]
#670 と同じ問題な気がしますね・・・

**Comment by chihiro-adachi** [comment]
#1035 にて修正.
