### ISSUE TITLE
バージョンアップ手順の記載について

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#727]
現在バージョンアップの手順が明記されているファイルやWikiページがないと思いますが（あったらゴメンナサイ）、 #702 の方のようにバージョンアップで躓いている方がいるので、整備したほうが良いと思います。

手順としては以下の様な形でしょうか。
1. src フォルダの更新
2. composer.* の更新
3. app/console の更新
4. html/index.php
5. html/template の更新
6. comporser のアップデート（コマンド）
7. マイグレーションのアップデート（コマンド）

2, 3, 4 あたりは毎回ではないと思うので考える必要があるかもしれません。

**Comment by shhirose** [comment]
app/config の内容もリフレッシュする必要がありますね。
3.0.2 から 3.0.3 へバージョンアップした際に  plugin_temp_realdir などが追加されていますが、そのままだと更新されずにエラーが出てしまいますね。

**Comment by Yangsin** [comment]
Gitを利用してソースを取得する場合のアップデートは除いて、パッケージを想定していいますと。

1. src/ html/ vendar/ を上書き
2. html/install.php/migration にアクセスしてマイグレーションを実行
3. html/install.php を削除

でやってますが、どうでしょう？

**Comment by shhirose** [comment]
@Yangsin 
> 2. html/install.php/migration にアクセスしてマイグレーションを実行
これでマイグレーションできるんですね。知りませんでした。
これで app/config の内容は更新されますか？

このIssueの意味合いはとしてはバージョンアップの方法論もそうですが、バージョンアップの手順を何かしらの資料に記載しませんか？ということです。
もしすでに資料があるようでしたらREADMEなりにURL等を記載しませんか？

**Comment by Yangsin** [comment]
Wikiにかいてあったとおもったのですが、開発用のガイドでしかなかったです  
https://github.com/EC-CUBE/ec-cube/wiki/%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%AC%E3%82%A4%E3%83%89  

さっと先ほどの手順はかいてみました。  
https://github.com/EC-CUBE/ec-cube/wiki/%E3%83%9E%E3%82%A4%E3%83%8A%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E6%89%8B%E9%A0%86

ただ、app/configについて確認してみましたところ 
app/config については対応できていませんでした・・・
app/configのアップデートを行うようなことをMigrationに含めるようにしないといけませんね
（本来、app/はアップデートで触るべきではないとおもうので、app/config/ にしか生成されない値ができてしまうこと、一番原因はありそうですが・・・ ）

**Comment by nobuhiko** [comment]
html/install.php って消さなきゃいけないファイルですし
migration は管理画面から出来るといいですよね（将来的には）

**Comment by Yangsin** [comment]
> migration は管理画面から出来るといいですよね（将来的には）

そうですね。現在はまだMigrationも不安定なところがあるのでむずかしいですが
将来的には管理者権限があるユーザーが管理画面からできるくらいにまで、持って行きたいです。

**Comment by Yangsin** [comment]
ドキュメントサイトでアップデート手順記載していっているので、こちらはクローズします。
http://ec-cube.github.io/update.html
