### ISSUE TITLE
［質問］運用面でのメール発送について

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#728]
運用時、商品を発送した（入金確認をした　等も）ということをユーザーに連絡するために
受注マスター>発送済み　などで検索したユーザーにチェックし「メール一括通知」　をしても
送信できるメールの種類が「注文受付」「問合受付」しかありませんでした。
（どちらも注文、問合せ時に自動送信されるものと同じ文面のように思います）
また、問合せをした場合も特に管理画面での通知も、確認画面もありませんでした。

EC-CUBE3ではメールのやりとりは管理画面を使わずそれぞれメーラーでの処理　というフロー想定でいいのでしょうか？

**Comment by TakaYasu1984** [comment]
メールテンプレートの新規追加が管理画面から行えないようになっているようです。
また、データベースに追加し対応するテンプレートを作成しても、
受注マスター「･･･」クリック→メール通知でテンプレートが選べるようになっても送信すると
注文時のメールが送信されます。

下記のファイルなどで「注文メール」のテンプレートが直接指定されている箇所を
動的に動作するように変更すれば登録したテンプレートでの送信が可能になると思います。
`src\Eccube\Controller\Admin\Order\MailController.php`
`src\Eccube\Service\MailService.php`

**Comment by Yangsin** [comment]
需要の高いメールについては今後追加していくことは検討しております。
なお、2系では注文受付メール、注文キャンセル受付メール、取り寄せ確認メールが用意されていました。

お問い合わせについては、2系でもメーラーでのやり取りのみとなっておりました。別途、オーナーズストアで提供されているプラグインのなかに管理画面からお問い合わせの確認、返信ができるようなプラグインがあったかと存じます。

**Comment by Yangsin** [comment]
Question なのでクローズします。 #1924 で新機能を検討します。
