### ISSUE TITLE
管理画面のコンテンツ管理->ファイル管理でドットのみ、ドットで始まるフォルダが受け付けられる。

### ISSUE THREAD

**Issue by akira345** [EC-CUBE/ec-cube#729]
ドットで始まるディレクトリはLinuxだと非表示なので、作成されますが管理画面上表示されません。
これらは入力チェックではじいたほうがよいのではないでしょうか？

EC-CUBE 3.0.3
OS:CentOS6.4

**Comment by chihiro-adachi** [comment]
#944 で修正いただきましたのでクローズします。
