### ISSUE TITLE
管理画面のIP制限でIPアドレスの書式をチェックしていない

### ISSUE THREAD

**Issue by akira345** [EC-CUBE/ec-cube#730]
管理画面のIP制限設定で、IPアドレスの書式をチェックしていないようで、
192.168.0.0/24などと入力すると、システムエラーが発生し、config.ymlから設定内容を削除しないとアクセスできなくなる。

EC-CUBE 3.0.3
CentOS6.4

**Comment by chihiro-adachi** [comment]
#855 にて修正いただきましたのでクローズします。
