### ISSUE TITLE
ファイル管理で日本語ファイル名のファイルを上げると、ダウンロード時ファイル名がおかしくなる

### ISSUE THREAD

**Issue by akira345** [EC-CUBE/ec-cube#731]
管理画面のコンテンツ管理->ファイル管理で日本語ファイル名のファイルを上げると、アップロード自体正常終了するのですが、そのファイルを表示するとfile_viewというファイル名でDLされ、ダウンロードをクリックすると、32というようなファイル名でDLされる。
また、FTPなどで/user_data配下に日本語ディレクトリを作成したばあい、表示はされるが、そのディレクトリ内にアップロードやダウンロード、削除が出来ないし、そのディレクトリ自身も削除出来ない。

EC-CUBE 3.0.3
CentOS 6.6

**Comment by casek** [comment]
再現させようとそれぞれ試したところ。。。

1. 日本語ファイルの表示→OK（再現せず）
2. 日本語ファイルのダウンロード→symfonyのResponseHeaderBagで「ファイル名はASCII文字のみよ」のExceptionがthrowされる
3. 日本語フォルダでのアップロード／ダウンロード／削除→OK（再現せず）

1.と3.については、クライアントの環境によるかもしれないので、ご利用のOSとブラウザおよびそれぞれのバージョン番号を教えていただけますか？（再現させるため）

1〜3について、一部再現しない点もありましたが「そもそも日本語ファイル名を許さない」とするのはどうかと思いますが、みなさんどうでしょうか？？

**Comment by akira345** [comment]
再度環境を作り直して検証しました。
再現環境は以下のとおりです。
CentOS6.6
PHP:5.6.11
Apache:2.2.15
EC-CUBE:3.0.3(Zip版)
PostgreSQL 9.4.4
Chrome:46.0.2490.71 m

ファイル周りについて
まずは日本語ファイルをアップロードします。
![01](https://cloud.githubusercontent.com/assets/655764/10472733/ec68a282-725e-11e5-9a41-1d9d7f477919.jpg)
次に表示をクリックしますと、file_viewとしてDLされます。
![02](https://cloud.githubusercontent.com/assets/655764/10472738/fe223268-725e-11e5-8316-09ee900b418d.jpg)
ダウンロードをクリックしますと
![03](https://cloud.githubusercontent.com/assets/655764/10472743/1003bc40-725f-11e5-8c14-1963254cfcf2.jpg)
システムエラーが発生して、一見不可に見えます。
![04](https://cloud.githubusercontent.com/assets/655764/10472751/1c9c8a7c-725f-11e5-8ec7-da4c5c1e4dc5.jpg)
ですが、半角全角を混ぜると、チェックをスルーして、ダウンロードできますが、、ファイル名がおかしくなります。
![05](https://cloud.githubusercontent.com/assets/655764/10472766/3c800170-725f-11e5-80ab-819c787febd9.jpg)

FTPで日本語ディレクトリ名を作った場合の挙動につきましては、使用したFTPソフトの設定がわるく、作成されたパーミッション設定の問題でした。
Apacheが読み書きできるよう適切な権限設定を行ったところ、問題ありませんでした。

**Comment by casek** [comment]
ありがとうございます！！
chromeもcentos上で、、ってことですね？
こちらの情報を元に追いかけてみます。

**Comment by akira345** [comment]
ChromeはWindowsです。
クライアント環境はWindowｓ７になります。

**Comment by casek** [comment]
お、、了解でっす！

**Comment by chihiro-adachi** [comment]
#952 にて対応.
