### ISSUE TITLE
管理画面 特定商取引法＞郵便番号 がずれる

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#732]
Mac Chrome 45 にて確認。
![image](https://cloud.githubusercontent.com/assets/578548/9711049/5dd75d2e-557b-11e5-87c8-1aee16491eb7.png)

**Comment by ttsuru** [comment]
EC-CUBE 3.0.3

**Comment by chihiro-adachi** [comment]
#822 で修正いただきましたので、クローズします。
