### ISSUE TITLE
コンテンツ管理＞レイアウト管理 「プレビュー登録」完了時メッセージ未翻訳

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#733]
![image](https://cloud.githubusercontent.com/assets/578548/9711275/4acaaf22-557d-11e5-98b8-a13cb3aba386.png)

**Comment by ttsuru** [comment]
EC-CUBE 3.0.3

**Comment by Yangsin** [comment]
#679 と同様
