### ISSUE TITLE
コンテンツ管理＞レイアウト管理 文字化け

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#734]
![image](https://cloud.githubusercontent.com/assets/578548/9711388/3a3b8cac-557e-11e5-83a0-6166921620fd.png)

#ECCUBEDAY

**Comment by ttsuru** [comment]
EC-CUBE 3.0.3

**Comment by Yangsin** [comment]
EC-CUBE DAYで利用した環境の依存かも？
再現できておりません。

**Comment by Yangsin** [comment]
再現されないため一度クローズします。

**Comment by ttsuru** [comment]
ありがとうございます。
また、どこかで確認してみます。
