### ISSUE TITLE
Ver:3.0.3の支払い方法選択について

### ISSUE THREAD

**Issue by ActiveFusion** [EC-CUBE/ec-cube#735]
管理画面の「受注登録画面」とフロント画面の「ご注文内容のご確認」画面の
支払い選択項目で、管理画面にて新規追加した「支払方法」がリストに表示されない場合がある。

※「支払い方法を新規入力」で登録した場合は、管理画面の「受注登録画面」に表示されるが、
公式？で公開されている「EC-CUBEペイメント決済プラグイン(3.0系) 」を導入すると管理画面の「支払方法」リストには表示されるが、管理画面の「受注登録画面」とフロント画面の「ご注文内容のご確認」画面には表示されない。

**Comment by ActiveFusion** [comment]
自己解決いたしました。
「配送方法設定」画面で支払い方法を選択する事により、フロント画面の「ご注文内容のご確認」画面に支払い方法がリスト表示されました。

ありがとうございました。

**Comment by ttsuru** [comment]
こちら、2からの仕様ですね。
IssueもCloseだと思いますので、ご自身でCloseしてみてください。
