### ISSUE TITLE
規格1のみの商品の在庫数が0でも商品ページの規格セレクトボックスの（品切れ中）表示がされない

### ISSUE THREAD

**Issue by TakaYasu1984** [EC-CUBE/ec-cube#736]
規格１のみ設定してある商品の在庫数が０の場合でも（品切れ中）の表示がされず注文ができてしまう。

規格１、規格２の両方が設定してある商品は在庫数が０の場合、（品切れ中）表示される

**Comment by casek** [comment]
こちら、再現しません。
規格1のみの場合も、規格1/2両方の場合も、在庫がどれも0なら「品切れ中」となります。
一部のみを在庫0にすると、すべて選択でき、カートに入れるボタンも押せます。
その後、在庫0のものはカート内でエラー表示されます。
これはあまり親切ではないので、詳細ページの時点で、在庫0のものはプルダウンで選択できない（disable化）するなどしてみます。

**Comment by casek** [comment]
最新masterで、規格selectボックスに品切れ中かどうか表示されるようになっていた。。。
ので、特に問題なしとします。

**Comment by chihiro-adachi** [comment]
再現不可のため、クローズします。
