### ISSUE TITLE
会員マスター管理画面で2ページ目以降の検索結果が0になってしまう

### ISSUE THREAD

**Issue by muramoto-keisuke** [EC-CUBE/ec-cube#737]
2ページ目以降に遷移したら検索結果が0件になってしまいます

**Comment by Yangsin** [comment]
#670 と類似した問題な気がしますね・・・

**Comment by chihiro-adachi** [comment]
#957 で修正いただきましたのでクローズします。

※ #670 とは異なり、検索条件保持およびページング実装が不十分であったことが原因でした。

**Comment by muramoto-keisuke** [comment]
ご対応ありがとうございました
