### ISSUE TITLE
HttpException\NotFoundHttpException のエラーメッセージが表示されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#739]
以下のページで、  `HttpException\NotFoundHttpException` にエラーメッセージを渡しているが、実際に例外がスローされた場合に、画面に反映されない。(ページが見つかりません。というメッセージが表示される)
- パスワードリセット
- 会員本登録

**Comment by trebla-on** [comment]
パスワードリセット画面で2回目アクセスすると「ページが見つかりません。というメッセージが表示される」
レスポンスコードは「404」です
メール内リンクダッブルクリック鹿瀬がありますのでこちらに404エラーページ表示しないほうがと思います
画面で「既に会員登録が完了しているか、無効なURLです。」メッセージを表示したほうが新設と思います
その方法で対応すると例外を外してそのページでメッセージを表示することになります。
※共通のエラーハンドリング追加もありと思います。

**Comment by trebla-on** [comment]
WIP: #2028 で対応始まりました。。。

**Comment by nanasess** [comment]
#2028 で修正済み
