### ISSUE TITLE
パスワード変更の確認メール

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#740]
会員パスワードの変更確認メールが、管理者にも送信されますが、必要でしょうか？

**Comment by nanasess** [comment]
また、パスワードは会員に入力させた方が安全だと思われます。

**Comment by Yangsin** [comment]
パスワードを平文であつかう事自体がのぞましくないので、

1. パスワード忘れた方へからメールアドレス入力
2. 1のセッションに続けて、シークレットコード入力＋パスワード変更の画面を表示
3. 1で入力されたアドレスが存在すればメールにシークレットコードを送る
4. 2に3のシークレットコードと変更したパスワードを入力
5. シークレットコードが一致すればパスワード変更完了。
6. ログイン画面を表示

くらいにできるとベストでしょうか？

ここまでするのはすこし大変ですが、すくなくとも現状の管理者に送信される必要はないですよね・・・・
