### ISSUE TITLE
購入中に品切れになった場合もカートが空にならない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#741]
「購入エラーが発生しました」と表示されるが、カートが空になっていないので、再度購入確認画面まで進めてしまう。

- もう少し親切なメッセージにした方が良い
- 購入できないので、カートは空にすべき

**Comment by casek** [comment]
こちら、レジから購入処理のところですよね。
メッセージは変更しようと思いますが、「エラー後にカートは空になっている」が現最新版での結果でした。

「購入できないので、カートは空にすべき」は、これで十分ですか？
それとも、websocketで在庫数pushしてカートやレジの段でサクッと「売り切れ」を通知するとかですかね？w

**Comment by casek** [comment]
あれ？ #828 との関連で、どうなったのか？ってことですかね。
とりあえず、メッセージ以外は #828 の対応でOKって文脈なんでしょうか？

**Comment by casek** [comment]
「選択された商品の在庫が不足しております。該当商品をカートから削除しました。」
という、カート内で使っているメッセージを表示しようとおもいますー。

**Comment by chihiro-adachi** [comment]
#956 で修正頂きましたのでクローズします
