### ISSUE TITLE
テンプレート一覧からテンプレートをダウンロードした時にappディレクトリが空だと正常なアーカイブが作成されない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#742]
``` app/template/default ```
以下にファイルが存在しなければ、ダウンロードした圧縮ファイルにappディレクトリが含まれない。

**Comment by chihiro-adachi** [comment]
以下の事象が発生します。
1. app/template/defaultが空の状態でダウンロードを実行
2. appディレクトリがないアーカイブが作成される
3. テンプレートのアップロード時に、アーカイブ内のチェック処理で弾かれ、アップロードできない。

**Comment by chihiro-adachi** [comment]
#1052 で修正.
