### ISSUE TITLE
dtb_customer_address は物理削除？

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#743]
dtb_customer_address.del_flg が存在するのにもかかわらず、お届け先を削除した場合、 dtb_customer_address を物理削除している。

物理削除している理由は何でしょうか？

**Comment by nanasess** [comment]
dtb_customer_favorite も同様です

**Comment by chihiro-adachi** [comment]
4系では原則物理削除となりました。
クローズします。
