### ISSUE TITLE
電話番号のバリデーションを厳密にするべき？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#744]
現状は中途半端なバリデーションでフリーダイヤルが登録できないなど問題があります。参考）  #674 
EC-CUBE2系では、各フィールド 6桁まで 全体で 12桁 かつ管理画面から長さの変更可 というざっくりとしたものでしたが3系はそれに合わせますか？

それとも日本の電話番号のパターンに合わせて正規表現でのチェックをしますか？

**Comment by nobuhiko** [comment]
厳密なパターンの場合このパターンを網羅する必要がある
http://www.soumu.go.jp/main_sosiki/joho_tsusin/top/tel_number/number_shitei.html#kotei-denwa

0XXXX X XXXX
0XXX XX XXXX
0XX XXX XXXX
0X XXXX XXXX

携帯、PHS､IP電話等（020,050,060,070,080,090)
0X0 XXXX XXXX

フリーダイヤル、ナビダイヤル、Ｑ２(0120,0800,0570,0990)
0XX0 XXX XXX

**Comment by nanasess** [comment]
そもそも、3分割しているメリットが少ないと思いますので、ざっくりで良い気がします。
外部システムと連携していると、国番号とか入ってくる場合もありますし、厳密にしすぎるとデメリットが大きい気が。

**Comment by Yangsin** [comment]
２系と同等（ただし、管理画面からのパラーメーター変更は現状できない・・・）でよいと思います。
厳密にやるメリットは私も感じないですね。

**Comment by nobuhiko** [comment]
そうなんですよね、そもそも3分割する必要があるのかよくわかりません

数字チェック
各フィールド5文字、全体で15文字まで（ヤマトの最長）
全角は半角に変換
ぐらいにしておきます

**Comment by nobuhiko** [comment]
マージされたので閉じます
