### ISSUE TITLE
EC-CUBE3の性能検証

### ISSUE THREAD

**Issue by tamagoya** [EC-CUBE/ec-cube#745]
性能試験環境を簡単に作れるように、ec-cube2系にあった、createEcCubeData-v25.phpを3系に移植する
https://github.com/EC-CUBE/eccube-2_13/blob/master/test/createEcCubeData-v25.php

**Comment by nanasess** [comment]
せっかくなので、こういう便利なもの使いません？

https://github.com/UseAllFive/doctrine-data-fixtures-command
https://github.com/nelmio/alice
https://github.com/fzaninotto/Faker#formatters

**Comment by tamagoya** [comment]
いいですね。前の方法だと、DBを拡張したときにソースコードを修正が必要なので、fixtureで簡単修正できる方が楽だと思います。

**Comment by tamagoya** [comment]
@nanasess さん
指摘頂いたFixtureを試してみたのですが、以下の2点で使いづらい部分があったので、いったんcreateEcCubeData-v25.phpを3系に移植する形で対応しようかと思います。

* 与えた引数に応じて、生成するデータの量を変更させるのが難しい
* ループを回して、多対多総当たりのリレーションを生成することが難しい

データ量を変動させる必要のない機能テストやシナリオテストでは、Fixtureは有効に使えそうです。

**Comment by tamagoya** [comment]
createEcCubeDataを移植しました。
【課題】速度を出すためEntitiyManagerのflush()頻度を下げています。
これにより、登録するデータ量によっては、メモリ不足で落ちることを確認しています。

**Comment by tamagoya** [comment]
試しに、動かして2系と比較してみた結果は以下です。
明日以降、商品数を増やして調査を進めようと思います。
![image](https://cloud.githubusercontent.com/assets/1086015/9901340/fa38592a-5ca1-11e5-9e7e-62b108102a37.png)

**Comment by tamagoya** [comment]
データ作成数を変えて、今回はapacheベンチでの性能テストを合わせて実施してみました。
apacheベンチの方の結果をみると、処理性能は3系が約1/3になっているように見えます。

![2015-09-17_12-17-06](https://cloud.githubusercontent.com/assets/1086015/9924052/a6ce8be8-5d36-11e5-87a7-feeed6b14f80.png)
![apachebench](https://cloud.githubusercontent.com/assets/1086015/9924063/b0689f04-5d36-11e5-9d6a-3c34ca7b6946.png)

**Comment by nobuhiko** [comment]
:+1: 
app/console から叩けるとさらに :+1: :+1: ですね！
ちなみにmysqlとpostgresの性能差はどうなんでしょう？

**Comment by tamagoya** [comment]
@nobuhiko 
先と同条件で、3系のmysqlとpostgresを比較すると性能差は以下になりました。
DBで大きな差はなさそうです。
![2015-09-17_19-05-48](https://cloud.githubusercontent.com/assets/1086015/9930556/706eb80a-5d6f-11e5-9f99-619f8938dc38.png)

**Comment by tamagoya** [comment]
今回移植したスクリプトでは、EntityManagaerのflushが遅い問題が発生しています。
1商品ごとに規格分類を生成して、flushをするとなぜか1秒近くかかっています...。このため、商品数を1万や10万にすると、かなり時間がかかってしまいます。
カウンターを作って、メモリがあふれない頻度でflushを実行するように改良中が終わったら、プルリクを出す予定です。

**Comment by tamagoya** [comment]
最後に、商品数を1万件に増やした時の比較を共有させて頂きます。
やはり、処理性能は3系が約1/3になっている模様です。ここから性能改善を目指していきたいですね。
![2015-09-18_17-39-28](https://cloud.githubusercontent.com/assets/1086015/9955561/e7695aec-5e2c-11e5-8e54-bf8539e58f75.png)

**Comment by tamagoya** [comment]
なお、1万件商品を登録する際に、createEcCubeData-v30では、EntityManagerにpersistしたオブジェクトが増えると、flushが徐々に遅延し、使用メモリが肥大化します。
上記の量(商品1万、カテゴリ2、規格3×3)のデータ作成だと、最終的に1回flushするのに数分のCPUが100%に張り付く、使用メモリが1.3GBになるというのを確認しています。
何も考えずにclearをかけると、関連付られたオブジェクトがデタッチされ、flushで例外が発生してしますので、うまくclearとDBからの再読み読みを使って、枝切りをするのが望ましいと思います。

**Comment by ttsuru** [comment]
Doctrine の効率的なinsertはテクニックがありますね・・・
http://doctrine-orm.readthedocs.org/en/latest/reference/batch-processing.html

このあたりでしょうか。

**Comment by tamagoya** [comment]
@ttsuru さん
ありがとうございます。
実は、Bulk Insertsと同じことは、saveEntityメソッド内でやってたりします。(頂いたページの様に何も考えずにclearを叩きたい...)

**Comment by tamagoya** [comment]
今回2系と3系の比較には、ニフティさんの公式EC-CUBEイメージを使っているのですが、ミドルウェアのパラメータを含めて、比較したほうが良いと指摘いただいたので、デフォルトの状態の各種パラメータについて、比較表をご用意したいと思います。

**Comment by tamagoya** [comment]
ミドルウェアのパラメータ比較以前に、同じマシン上で性能比較をするべきというご指摘を頂いたので、EC-CUBE3系の公式イメージ上にEC-CUBE2系のソースコードを移植して性能比較しました。
結果は以下です。
![2015-09-25_14-51-02](https://cloud.githubusercontent.com/assets/1086015/10093974/0ecc3088-6395-11e5-9981-447033b3f9a2.png)

**Comment by chihiro-adachi** [comment]
検証結果は、以下に保存しています。
https://github.com/EC-CUBE/eccube3-doc/tree/master/StressTest
