### ISSUE TITLE
EC-CUBE3.0.3でのカート画面について（数量部分の不具合）

### ISSUE THREAD

**Issue by ActiveFusions** [EC-CUBE/ec-cube#746]
自分のところに構築した、
EC-CUBE3.0.3で商品をカートに入れた際、商品詳細画面での数量は「１」と設定しているが、カート画面に遷移すると数量が「２」となってしまう。
※自分の構築環境として
http://downloads.ec-cube.net/src/eccube-3.0.3.tar.gz
をもとに構築しました。

ちなみに、
公式サイト
http://demo3.ec-cube.net/
と
http://site3.ec-cube.net/
のデモサイトだと、この現象は起きない。

**Comment by Yangsin** [comment]
こちら再現できていません。現状も同様に発生していますでしょうか。
以下を参考に動作環境など詳細をいただけますと幸いです。
https://github.com/EC-CUBE/ec-cube/wiki/Issues%E3%81%AE%E5%88%A9%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by ActiveFusion** [comment]
[OS]    CentOS release 6.7
[PHP]   PHP 5.6.12(remiレポジトリのRPM使用)
[データベース]    postgresql 9.4(PostgreSQL公式RPM使用)
[WEBサーバ]  httpd-2.2.15-45
[ブラウザ]  IE11(Windows7)
[EC-CUBEのバージョン] EC-CUBE3.0.3(tar.gzを使用)
[現象]
フロント側の商品詳細画面（パーコレーターを選択）を表示。
右上のカート情報は「０」の状態。商品を「カートに入れる」をクリック。
クリック後のカート画面の商品の数量が「２」となっている。
![default](https://cloud.githubusercontent.com/assets/14008547/9841084/4590e22a-5ad6-11e5-9af1-d4943b805ddf.png)
![default](https://cloud.githubusercontent.com/assets/14008547/9841085/4d1d348a-5ad6-11e5-86d3-97316fe0ca0a.png)

ご確認の程、よろしくお願い致します。

**Comment by k-yamamura** [comment]
#1076 #1077 #1130 で修正のためクローズします。
