### ISSUE TITLE
商品規格の削除後の商品登録ページの項目が元に戻らない

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#747]
商品規格の削除後、同じ商品の商品登録画面の「詳細な設定」の内容を確認すると
商品コードなどが消えたままになっている

再現方法
1.　商品規格を一度登録
2.　「商品規格を初期化」を押下して規格を削除

**Comment by chihiro-adachi** [comment]
#907 で修正いただきましたのでクローズします。
