### ISSUE TITLE
商品規格登録時の商品コードの不具合について

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#749]
規格を登録して商品コードを登録していない場合下記のように表示される
「～」

規格を登録して1つ商品コードを登録した場合下記のように表示される
「～○○○○」

**Comment by Yangsin** [comment]
該当の画面など詳細をもう少し記載いただけますでしょうか。
キャプチャなどを貼り付けていただいても構いません。

**Comment by sf-tuji** [comment]
言葉足らずですみません。

■「～」の件です
管理画面で下記のように商品コードを何も入力せずに設定します。
![2015-09-14_133946](https://cloud.githubusercontent.com/assets/9459909/9842252/b60a7d26-5ae6-11e5-8cbf-4e3e6fade31e.png)

フロント画面では以下のようになります。
![2015-09-14_134004](https://cloud.githubusercontent.com/assets/9459909/9842256/c1333d78-5ae6-11e5-9ae9-013ae8e6d970.png)

■「～○○○○」の件です。
管理画面で下記のように1つだけ商品コードを設定します。
![2015-09-14_134138](https://cloud.githubusercontent.com/assets/9459909/9842275/f666106a-5ae6-11e5-8ac9-8ac478d45a42.png)

フロント画面では以下のようになります。
![2015-09-14_134204](https://cloud.githubusercontent.com/assets/9459909/9842279/076be268-5ae7-11e5-958c-7f048fccfa85.png)

**Comment by chihiro-adachi** [comment]
#749 にて修正いただきましたのでcloseします。
