### ISSUE TITLE
商品送料を設定した商品を購入時に支払方法を変更すると送料が計算されない

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#750]
商品送料を設定した商品をカートに入れ、支払方法画面に進み
支払方法を変更すると商品送料が計算されなくなる

**Comment by casek** [comment]
こちら、本日最新のver.で確認しましたが、再現しませんでした。。。
現在のmasterで再度確認していただければと思います。
よろしくお願いします！

**Comment by sf-tuji** [comment]
masterで確認させていただきましたが、商品に設定してある送料が反映されていませんでした。

手順は下記の通りです。
1. 管理画面にて商品に送料を設定する
2. フロント画面にて送料を設定した商品をカートに入れる
3. ご注文内容のご確認に遷移する
→配送業者ごとの送料は計算されるが、商品に設定してある送料は計算されない
4. 支払方法を変更する
→3.と同様になる

**Comment by k-yamamura** [comment]
購入画面を初回表示時は送料が反映されていますが、
配送業者を変更すると送料が計算されなくなっていましたのでこちら対応します。
ご報告ありがとうございます。

**Comment by casek** [comment]
@k-yamamura さん

こちらの件、引きついで対応してもらえるという認識でOKですか？
docsのリストからも消えてたw

**Comment by chihiro-adachi** [comment]
#983 にて対応.
