### ISSUE TITLE
管理画面の商品検索画面の商品画像について

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#753]
フロントの商品一覧・詳細では管理画面で設定した一番最初に来る画像が表示されるが
管理画面の商品検索画面の商品画像は常に同じ画像が表示される

**Comment by Yangsin** [comment]
管理画面でも一番最初にくる画像が表示されるべきというご意見でよろしいでしょうか。

**Comment by sf-tuji** [comment]
はい、EC-CUBEの2系では一覧-メイン画像が管理画面の商品マスターの一覧とフロントの商品一覧で使われており内容が一致していましたので、2系から3系に移行した方は違和感を覚えるかもしれないと感じ投稿させていただきました。

**Comment by k-yamamura** [comment]
3.0.5で対応されましたのでcloseとさせて頂きます。
