### ISSUE TITLE
【質問】メール本文の編集について

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#755]
2系の頃からだと思いますが、メール本文の編集ができないのはなにか意図があるのでしょうか。

ヘッダー、フッターのみだと動的な表示ができず、結局テンプレートファイルを直す必要が出てきてしまいます。
何か問題があったのであればご教授いただけますでしょうか。

**Comment by Yangsin** [comment]
本来は本文も編集できるようにしたいが、どういった仕様にするか固めきれいないというじょうな状況ですね。
β時点での議論が以下にあります。
https://github.com/EC-CUBE/ec-cube/issues/220

**Comment by Yangsin** [comment]
#1924 に議論を移してこちらはクローズします。
