### ISSUE TITLE
購入遷移の確認画面から遷移する、お届け先の追加・編集画面にFax項目がない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#763]
![default](https://cloud.githubusercontent.com/assets/604492/9845068/5811470a-5b03-11e5-8302-a5f1fade99bf.png)

マイページから登録する、お届け先情報にはFAXがある

お届先情報としてFaxってのは必要なんでしょうか？

**Comment by nobuhiko** [comment]
FormTypeが別々になっているのも原因な気がする

**Comment by Yangsin** [comment]
2系では、Faxありましたね。必須ではないにしろ置いておくで統一でいかがでしょうか。

**Comment by ttsuru** [comment]
お届け情報でFAXは使わないですね。
2の途中でどなたかが追加してますね・・・

**Comment by nobuhiko** [comment]
mergeされたので閉じます
