### ISSUE TITLE
管理画面のテンプレートのフォーマットが統一

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#765]
-  <form>タグに action が指定されていないページが多々ある

（ない場合 requiredが指定されていてもお構いなしにpostされてしまうようなので、バリデーションが正しく効いていない）
- エラーメッセージが統一されてない

```
$app->addError('admin.register.failed', 'admin');
```

↑これがあるページとないページがある

**Comment by ryo-endo** [comment]
まず実装のルールを決めないといけないと思うので、一旦は`question``discussion`とさせていただきます。

**Comment by kiy0taka** [comment]
3.nの新しい管理画面UIでfixするようにします。

**Comment by okazy** [comment]
3系については #2320 で対応済み

3.nでは以下の方針で対応

> タグに action が指定されていないページが多々ある

こちらはページによって必要なページと必要でないページがある

> エラーメッセージが統一されてない

こちらは基本的には出すのが正しいので統一して出るようにします

**Comment by xuelian311** [comment]
4.0で対応しましたのでクローズいたします。
