### ISSUE TITLE
特定商取引法に基づく表記の予備カラムって不要じゃないでしょうか？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#766]
予備のカラムが合っても、そこに登録する処理を作るには結局プラグインが必要になる、となるとなんのためにあるのかよくわかりません。

また会員規約のように、タイトルと内容を登録できる仕様になってるほうが汎用的でよいのかなとも思います

**Comment by Yangsin** [comment]
dtb_helpのlaw_term07~10 の事でしょうか。
確かEC-CUBE3の思想としては、不要なものであり利用する方法がないので、削除で問題ありません。
タイトルと内容が登録できるような大幅な仕様への変更は3.xでの対応とさせてください

**Comment by nanasess** [comment]
> また会員規約のように、タイトルと内容を登録できる仕様になってるほうが汎用的でよいのかなとも思います

こちらは #1355 を新たに登録しました。
予備項目は #766,#851 にて削除されましたのでクローズします。
