### ISSUE TITLE
メンバー管理の権限に差がない

### ISSUE THREAD

**Issue by kamawi** [EC-CUBE/ec-cube#767]
システム設定>メンバー管理 で「店舗オーナー」と「管理者」の2ユーザー分作ってみましたが、
どちらでログインしても管理画面のメニューに差が見られませんでした。
この2つ、何が違うのでしょうか

**Comment by Yangsin** [comment]
「管理者」しかシステム設定に入れない仕様となります。
不具合と思われます・・・

**Comment by chihiro-adachi** [comment]
権限機能がまだ実装されていないため、別途仕様を策定します。

**Comment by nanasess** [comment]
Merged form #1262
