### ISSUE TITLE
マスターの詳細検索画面が閉じたり開いたり挙動が不統一

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#770]
![_-_ec-cube](https://cloud.githubusercontent.com/assets/604492/9867390/1066d424-5ba8-11e5-9e36-b42b866546cf.png)

詳細を開いて検索をしても、閉じてしまう
受注と商品は開きっぱなしになる

**Comment by nobuhiko** [comment]
受注は受注で、詳細を入れてなくても、検索するを押すと全部開く・・・
機能が不統一でどれが標準か不明

**Comment by geany-y** [comment]
以下で解決
https://github.com/EC-CUBE/ec-cube/pull/1030

**Comment by chihiro-adachi** [comment]
#1030 にて対応.
