### ISSUE TITLE
【改善要望】【管理画面/受注登録】受注商品情報の更新時に閉じないでほしい

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#772]
管理画面の受注登録画面の受注商品情報欄に「商品の追加」ボタンや「計算結果の更新」ボタンがありますが、
それぞれのボタンを押下して更新処理が走った際に受注商品情報欄が閉じてしまうので、
開いたまま かつ 受注商品情報欄が画面の先頭に来るようにしていただけると操作がしやすいと思います。

連続で商品を追加したり、計算結果を見て再度修正をかけたい場合など、再度そこまでスクロールして
開いてボタンを押下するのは、手数が多くなるように思いました。

**Comment by k-yamamura** [comment]
3.0.5から画面レイアウトの修正が行われ、受注商品情報欄が閉じなくなりましたのでcloseとさせて頂きます。
スクロールの問題については #1145 で引き継がせてもらいます。
