### ISSUE TITLE
【管理画面/受注登録】購入時のお届け先が反映されていない

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#775]
[PHP]   5.6.10
[データベース]    PostgreSQL 9.4.4
[WEBサーバ] Apache/2.4.12 
[ブラウザ]  Firefox　40.0.3
[現象]
購入時にお届け時間を設定し、購入処理を終えます。
購入後に管理画面の受注登録画面で該当の受注を開くと下記のように
セレクトボックスが「指定なし」の状態になる
![default](https://cloud.githubusercontent.com/assets/9459909/9871448/b2125dfe-5bce-11e5-958d-b59b08a28af3.JPG)

このまま登録を行うとお届け時間は「指定なし」に変わります。

**Comment by chihiro-adachi** [comment]
#951 #939
