### ISSUE TITLE
【フロント/ご注文内容のご確認】再読み込み時に画面の情報を引き継げていない

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#780]
[PHP] 5.6.10
[データベース] PostgreSQL 9.4.4
[WEBサーバ] Apache/2.4.12
[ブラウザ] Firefox　40.0.3
[現象]
フロントのご注文内容のご確認にて、更新時にお届け日、お届け時間の内容が引き継がれていません。

1. お届け日、お届け時間を選択します
![2015-09-16_094549](https://cloud.githubusercontent.com/assets/9459909/9893849/fc6f4cd4-5c57-11e5-87aa-780bd81c63b4.png)

2. お支払方法を変更します
画面の更新が走って、お届け日、お届け時間が消えてしまいます。
![2015-09-16_094630](https://cloud.githubusercontent.com/assets/9459909/9893853/119616ba-5c58-11e5-91bd-bec92b7a1986.png)

購入者がお届け日やお届け時間を一度設定したら、変わったことに気付かない可能性
があるので修正が必要かと思いました。

**Comment by chihiro-adachi** [comment]
現状のmasterで確認した結果です。

1.お届け日、お届け時間を選択
2.支払い方法(配送業者変更でもよいです)を変更し、リロードさせる

の手順で、以下の例外が発生していました。

```
FatalErrorException in DateTimeType.php line 53:
Error: Call to a member function format() on string
```

お届け日のプルダウンは、ShippingItemTypeで生成しているようなのですが、postされるデータ(文字列)からエンティティ(DateTime)への変換がうまくできていない、ように見えます。

**Comment by sai-ken-tanaka** [comment]
▼発生の流れ
Eccube\Form\Type\ShippingItemType::buildForm
        deliveryDates = $app['eccube.service.shopping']->getFormDeliveryDates($data->getOrder());
        $form
                    ->add('shippingDeliveryDate', 'choice', array(
    		       'choices' => $deliveryDates,
                        'required' => false,
                        'empty_value' => '指定なし',
                    ))

・deliveryDates(key/valueともにstring)をFormに放り込んでいます。

Eccube\Controller\ShoppingController::payment
                // 受注関連情報を最新状態に更新
                $app['orm.em']->flush();

・postされる値はコンボで選択されたstringであり、formにバインドされる値もstring.

Doctrine\DBAL\Types\DateTimeType::convertToDatabaseValue
        return ($value !== null)
            ? $value->format($platform->getDateTimeFormatString()) : null;

・flush時に対象のentity :: getDeliveryDate() をコールし、上記書式変換メソッドが実行されて
  いますが、entity::getDeliveryDate() でstringが取れてしまっている為、 formatメソッドを持っていない
  という怒られ方をしています。

※ Eccube\Entity\Shipping:: get/setDeliveryDate()内で強制的に型変換、、とも考えてみたのですが
    ・form/choice が DateTime を食べられない(現状)
    ・setter/getterのparam/returnがmixedになってしまい、当該機能以外でも影響が大きい
     ようです.(管理画面を含めたいくつかの機能で意図せぬ結果が発生しました.)
     (設計/実装としてもそもそもまずい）

▼対処について
現状以下3点程度しか思いつきませんが(発生の流れが間違いないと仮定して)
一旦確認をお願い致します.

・ フロントの配送日指定をドロップダウンではなく、inputに変える
・ choiceにDateTimeを食べれるように拡張する.
・ DateTime::convertToDatabaseValueをオーバーライドして、本要件を満たすようにする.

**Comment by chihiro-adachi** [comment]
#951 #939
