### ISSUE TITLE
【バグ】会員マスター検索で、表示件数の変更ができない。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#781]
■対象画面：会員マスター
■機能名：表示件数機能
■内容：
会員マスター検索で、初期設定の20件以上のデータを用意し、
検索後に表示件数を変更しようとするが、表示件数を変更できません。
■想定動作：
他のマスタ画面では動作しているので、同様の仕様になるよう修正する必要があるとおもいます。

![default](https://cloud.githubusercontent.com/assets/13776434/9955120/76430d3e-5e29-11e5-84f5-a798ff0a9caa.PNG)

**Comment by chihiro-adachi** [comment]
#957 で修正いただきましたのでクローズします。
