### ISSUE TITLE
EC-CUBE3系で利用されていないモデルが残っている(CategoryTotalCount、CategoryCount)

### ISSUE THREAD

**Issue by tamagoya** [EC-CUBE/ec-cube#784]
以下の2つのモデルは、EC-CUBE3系で利用していないと思われる。
- CategoryTotalCount
- CategoryCount

上記のモデルには、インストール時に初期データが投入されるが、Category数を変更しても変更されていない。
また、合計数もCategory数を計算すれば良いので、削除しても問題ないかと思われる。

**Comment by nanasess** [comment]
`Master\Zip` も使用してないと思われます

**Comment by nanasess** [comment]
Lazy Loading で無駄に大量の SQL を発行してそうです。

**Comment by okazy** [comment]
対応済み
