### ISSUE TITLE
Doctrineのバージョンに問題がある

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#785]
参考)
http://www.doctrine-project.org/2015/08/31/security_misconfiguration_vulnerability_in_various_doctrine_projects.html
https://scrutinizer-ci.com/g/EC-CUBE/ec-cube/issues/master/files/composer.lock

**Comment by chihiro-adachi** [comment]
#899, #853 で対応済のため、クローズします。
