### ISSUE TITLE
【改善要望】前回ログイン時カートに入っていた商品を、次回ログイン時引き継いで欲しい。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#793]
■対象画面：
■機能名：ログイン、ログアウト、カート機能
■内容：
以下の流れで操作をした際、再ログイン時1.で入れた商品が保存されていません。（0件になる）
1.ログイン中にカートに商品を追加
2.ログアウト
3.再ログイン
■想定動作：
再ログイン時1.で入れた商品を保存しておく仕様にしてほしいです。

ちなみに、楽天、Amazonなどのモールは、現状保存しておく仕様のようです。

**Comment by Yangsin** [comment]
これは好き嫌い分かれるところだと思いますが、モールなどとは違いカートを保存しておく必要性は薄いのかと思います。
現状は仕様とさせていただきます。

**Comment by hainey** [comment]
ECCUBE2など、一般的なカートシステムは、カート保存機能が有効になっていることが多いので、
こちらは必須機能だと思います。
（少なくとも設定でオン・オフできるようにしていただいたほうが良いと思います。）

**Comment by seasoftjapan** [comment]
EC-CUBE 2 系は無かったような・・・(一部バージョンを除いて、ログアウトしてもセッション中は維持していたと思いますが、会員情報と紐付けた永続化は無かったかなと。)

海外の複数の EC サイトにスクレイピング (というか勝手 API ?) を行うプロジェクトに参画しているのですが、カート保存に対応している EC サイトって多いですね。

モールに限らずです。(B2B 向けが多いので若干偏りがあるかもしれませんが。)

なので、「必要性は薄い」とも言えないと思います。

プラグイン化もできそうですが、「カート変更」と「購入手続き」が、別セッションで同時進行した場合の動作の辺りとかは、本体でキッチリ設計されていないと、プラグインで勝手にすれというのは荷が重いような気もします。
