### ISSUE TITLE
"カートに入れる"ボタン押下時、連続して押下すると注文商品が追加される

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#794]
■対象画面：商品詳細画面、カート画面
■機能名："カートに入れる"ボタン
■内容：
"カートに入れる"ボタン押下時、連続して押下すると注文商品の個数が倍になる場合があります。
■想定動作：
"カートに入れる"ボタンを一度押下したタイミングでボタンを無効化 or 連続しておされても1度の注文として処理される方が良いのでは？と思います。

**Comment by nobuhiko** [comment]
#746  と同じ問題？？

**Comment by t-nagahashi** [comment]
同じかもしれませんね。
私の場合は、再現性はあります。
ボタンを連打すると、確実に個数が増えていきます。

**Comment by chihiro-adachi** [comment]
#1076 #1077 #1130 で修正のためクローズします。
