### ISSUE TITLE
商品規格登録後に、分類、もしくは規格を削除するとシステムエラーが発生する

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#796]
商品規格登録後に、選択した分類、もしくは規格を、管理画面の規格登録から削除すると、削除した分類、規格を選択した商品マスターを表示する画面でシステムエラーが発生します。
管理画面の商品マスタ一覧、フロント画面の商品一覧、商品詳細などでシステムエラー表示になります。

DBの以下の 3テーブルの削除フラグを元に戻す（直接書き換える）と、エラーが解消されました。
dtb_class_name
dtb_class_category
dtb_product_class

※ 商品カテゴリでは、1件でも商品マスタに登録されている場合カテゴリを削除できない制御が入っていました。

**Comment by chihiro-adachi** [comment]
#976 にて対応.
