### ISSUE TITLE
商品登録でカテゴリが未選択で登録できる

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#797]
管理画面の商品登録画面です。

商品登録時に 1つでも商品カテゴリを選択して登録すると、以降商品カテゴリが必須項目になってしまい、カテゴリを未選択にすることができなくなりました。
チェックを外して更新しようとすると、入力エラーが表示されます。

カテゴリは1度登録すると必須項目になるんでしょうか？

**Comment by Yangsin** [comment]
商品カテゴリの選択は必須です。
未選択で登録できる状態が不具合となりますので、タイトル修正させていただきました。

**Comment by nanasess** [comment]
商品一覧には載せたくないけど、限定した顧客に、一時的に商品を公開したい場合があります。
そういった場合に、「商品一覧に表示しない商品」ができたりすると便利です。
商品カテゴリ登録を必須にしなければならない重要な理由がなければ、必須にしなくても良いと思いますが、いかがでしょうか?

**Comment by seasoftjapan** [comment]
私も、カテゴリーを割り当てたくないこと時折ありますね。
反面、選択忘れをアラートされて救われるケースも。。。

**Comment by nobuhiko** [comment]
商品マスターの一覧画面で、赤色でカテゴリー選択されてないことをお知らせするとか

**Comment by Yangsin** [comment]
皆様、ご意見ありがとうございます。
カテゴリーを必須にする運用上の必然性は薄いということですね。
なし → 必須 より 必至 → なし ですので既存の運用への影響はないと言えると思います。
システム上の必然性も確認したうえでになりますが、運用の幅を広げられるので、仕様の変更もありだと思います。

**Comment by geany-y** [comment]
ユーザー画面の仕様はどうでしょうか。
①「カテゴリ」の意図が、商品のカテゴライズなら、他のECサイトを例にみても、カテゴライズされていない商品も
検索出来ると考えます。
②「カテゴリ」はあくまで、検索に対する利便性や店で商品に種別をつけたい意図を叶えるのが目的であるかなと思います。
③個人的には編集が出来るため、カテゴリ未選択時のアラートも必要ではないかなと思います。
④限定公開は別機能とすべきではとの意見をいただきました。

まとめると、こんな感じとなりますが、如何でしょうか。

**Comment by k-yamamura** [comment]
必須 → なしに対応済みのためcloseさせて頂きます。
