### ISSUE TITLE
【バグ】会員マスターで、会員ID検索ができない。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#798]
■対象画面：会員マスター
■機能名：会員マスター検索
■内容：
会員マスター画面の、基本条件（初期表示の一番上の入力箇所）に、
会員IDを入力しても、検索にデータがヒットしない。
■想定動作：
会員IDで検索できること。

**Comment by chihiro-adachi** [comment]
#910 にて修正いただきましたのでクローズします。
