### ISSUE TITLE
autoloaderの実装

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#8]
data/ClassLoader.phpを作成し、全classをautoloadできるようにする

**Comment by nanasess** [comment]
@shinichi-takahashi 
@ttsuru 
リリース用のパッケージ(*.tar.gz, *.zip) には、 PEAR のパッケージも同梱する認識で合っていますか？
Composer の使えない環境も多々あると思いますので。。

**Comment by shinichi-takahashi** [comment]
@nanasess 
その認識であってます。
Composer対応はあくまで開発用で、パッケージでは一般的なレンタルサーバ（SSH接続なし）でインストールできることを想定しています。

**Comment by ttsuru** [comment]
リリース用のスクリプトも修正が必要ですね。

**Comment by shinichi-takahashi** [comment]
Composer導入と@ttsuruさんのPRをマージしたため、本件クローズいたします。
ご対応いただいたみなさま、ありがとうございます。
