### ISSUE TITLE
【バグ】会員マスターで、会員名（姓名の間に半角スペースをいれた状態で）検索ができない。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#800]
■対象画面：会員マスター
■機能名：会員マスター検索
■内容：
会員マスター画面の、基本条件（初期表示の一番上の入力箇所）に、
会員名（姓名の間に半角スペースをいれた状態で）入力しても、検索がヒットしない。
■想定動作：
会員名（姓名の間に半角スペースをいれた状態で）検索にヒットすること。
2系のデモ画面では、同条件で検索が可能です。

**Comment by chihiro-adachi** [comment]
#993 にて対応.
