### ISSUE TITLE
【バグ】会員検索条件の誕生月の選択リストが動かない時がある。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#801]
■対象画面：会員マスター（追加条件の箇所）
■機能名：会員検索
■内容：
会員検索条件の誕生月の選択リストが動かない時がある。
おそらく、画面サイズを変更し、選択リストのサイズが横長になった際に、選択できなくなる模様。
■想定動作：
どんな画面サイズでも、誕生月の選択リストが選択できること。

○選択リスト使用可能時
![default](https://cloud.githubusercontent.com/assets/13776434/9954690/f9149f24-5e25-11e5-8450-bfef7f173c3d.png)
○使用不可時
![2](https://cloud.githubusercontent.com/assets/13776434/9954691/f92d3c78-5e25-11e5-834c-5644736efcae.png)

**Comment by chihiro-adachi** [comment]
#909 にて修正済のため、クローズします。
