### ISSUE TITLE
規格の並び替え後、エラーになる

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#802]
管理画面の規格登録です。
規格一覧でマウスで移動して表示順を変更した場合、画面上は順番が変更されていましたが、その次の作業でエラーになる場合がありました。

1. 一番上に表示されている規格をマウスで下部に移動する
下部に移動した規格の、右端のメニュー内に「上へ」リンクが表示されません。
※ 一番下に規格を移動させていた場合、右端のメニュー内「下へ」リンクをクリックするとエラーメッセージが表示されます。
メッセージ文言「規格を下へ移動できませんでした。」

2. 1の動作の後に、一番上に表示されるようになった規格の右端のメニュー内に「上へ」リンクが表示されたままになります。
※ 「上へ」リンクをクリックするとエラーメッセージが表示されます。
メッセージ文言「規格を上へ移動できませんでした。」

画面を更新したり、上記のエラーメッセージを1度表示させると発生しなくなります。

右端の「上へ」「下へ」リンクをクリックしたときと同じ動きにしてほしいです。
※ 管理画面の分類登録、カテゴリ登録でも同様のことが発生しました。

**Comment by casek** [comment]
規格登録だけでなく、カテゴリ登録でも同じ現象が出ていたので、同時に対応しました。

**Comment by chihiro-adachi** [comment]
3.0.4にて、「上へ」「下へ」の操作は削除し、ドラッグアンドドロップでの操作に統一しました。
