### ISSUE TITLE
【バグ】会員マスター検索結果一覧で、ページング機能が使えない。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#803]
■対象画面：会員マスター
■機能名：ページング機能
■内容：
会員マスター検索結果一覧で、ページング機能が使えない。
リンクを押下すると、検索結果が消え、会員マスター初期表示時の画面に戻ります。
■想定動作：
ページング機能が正常に動作するようこと。

**Comment by nobuhiko** [comment]
#737 と似てる話かな

**Comment by t-nagahashi** [comment]
@nobuhiko さん
ありがとうございます。
737と同様で良いと思いますので、クローズします。
