### ISSUE TITLE
【改善要望】会員削除時、検索結果がクリアされないようにしたい

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#804]
■対象画面：会員マスター
■機能名：会員削除
■内容：
会員マスタ検索結果一覧にて、会員の削除実施すると、
検索結果が消えて、会員マスター初期画面に戻ってします。
■想定動作：
会員マスタ検索結果一覧にて、会員の削除時、
検索結果は消えず、削除対象のデータのみ画面からさくじょされる。

**Comment by nanasess** [comment]
#1620 で対応しています

**Comment by ryo-endo** [comment]
#1620 取り込みました。
