### ISSUE TITLE
【改善要望】同じ会員を別画面にて、ほぼ同時に削除した場合のハンドリングに関して

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#805]
■対象画面：会員マスター
■機能名：会員削除
■内容：
別タブなどで、会員検索結果一覧を表示した画面を2つ用意。
ほぼ同時にデータの削除を行うと、
・片方は正常に処理が終了。
・もう片方が、「ページがみつかりません」画面に遷移してしまう。
　（再ログインする必要がでてきてしまう。）
■想定動作：
同データを、同時に削除した場合、
・片方は正常に処理が終了。
・もう片方の画面では、データが存在しない旨のメッセージを表示する。
（画面は遷移せず、会員マスター検索画面のまま、検索結果も表示された状態、削除されたデータのみ消える。）

○ページが見つかりません画面
![2](https://cloud.githubusercontent.com/assets/13776434/9955602/598694b4-5e2d-11e5-81b3-83d2509e9eb7.PNG)

**Comment by t-nagahashi** [comment]
受注管理はうまくハンドリングできているようです。

**Comment by trebla-on** [comment]
こちらの問題何回も確認しましたが一回でも「ページがみつかりません」メッセージ出なかった。
チケットは九月の物ですのでもう直ってますかもしれません。

**Comment by Yangsin** [comment]
１年以上前のものですので、一度クローズとします。
