### ISSUE TITLE
【改善要望】検索結果一覧画面で、データを削除すると検索結果がクリアされる。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#806]
■対象画面：会員マスター、受注マスター（他の画面も同じかも）
■機能名：削除
■内容：
検索結果一覧から、データを削除した場合、検索結果がクリアされてしまう。
■想定動作：
削除時、検索結果を維持した状態で、削除対象のデータのみ消える。

**Comment by nanasess** [comment]
#1620 で対応しています

**Comment by ryo-endo** [comment]
#1620 取り込みました。
