### ISSUE TITLE
管理画面のプレビューの開き方が不統一

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#808]
管理画面の商品確認（プレビュー）画面です。

商品マスター一覧で「確認」リンクをクリックすると同じウィンドウ内でプレビュー画面に遷移しましたが、商品登録画面では「確認」ボタンをクリックすると別タブ（別ウィンドウ）でプレビュー画面が表示されました。

表示方法が違いますが、同じ動きになっていなくてもよいのでしょうか？
※ 商品登録画面のように別タブ（ウィンドウ）で表示されると、管理画面での作業が止まらなくて良いと思いました。

**Comment by Yangsin** [comment]
ご報告ありがとうございます。不統一の不具合とさせていただきました。

**Comment by casek** [comment]
手始めにこれやりますw
一覧での「確認」をsearch_form経由のページ遷移でなく、aタグ直でtarget="_blank"にして別タブで開くような形で。

**Comment by chihiro-adachi** [comment]
#880 にて対応済のため、クローズします。
