### ISSUE TITLE
商品のプレビューがログインなしでも見れてしまう

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#809]
管理画面の商品確認（プレビュー）画面です。

非公開状態の商品のプレビュー画面が、管理画面にログインしていない状態でもURLを直書きしたら見ることができました。
ログイン制限などは必要ないでしょうか？

※ Chromeで管理画面にログインしプレビュー画面のURLを入手。IEで管理画面ログアウト状態でURLを直書きして確認しました。

**Comment by casek** [comment]
これやります。
「公開／非公開（テーブルdtb_productのstatus）」は、ちゃんと更新されてますが、商品詳細およびプレビュー時に使われてないっぽいですね。
「非公開」なら、商品詳細およびプレビューで表示せずトップページにredirectみたいにしますが、どうでしょう？

**Comment by chihiro-adachi** [comment]
@casek HttpNotFoundExceptionなげてもらうだけで良いかと思います。※「ページが見つかりませんでした」のエラーになります。

**Comment by casek** [comment]
なるほど。了解でっす！

**Comment by casek** [comment]
@NuruMayu414 さん。
こちらで確認したところ、現象が再現できませんでした。
再現可能な情報をいただければと思います。
よろしくお願い致します。

**Comment by NuruMayu414** [comment]
現象を確認した環境が手元にありませんので、詳細な情報は記載できませんが
以下の手順でテストを実施した際に、現象が発生しました。

1. Chromeで管理画面にログインする
2. 商品管理＞商品登録 から、「非公開」の商品を作成する
3. 商品登録が完了後、同画面の「確認」ボタンを押下する
4. 表示したプレビュー画面（URLの最後に ?admin=1 的な変数が付加されている）のURLをコピー
5. IEを立ち上げ、管理画面にログインしない状態で 4 でコピーしたURLを実行する

※ 2 ～ 3 の流れは、「商品管理＞商品マスタから、「非公開」の商品を検索し、右端のメニューから「確認」を押下する」でも可能です。

上記の流れで発生しました。

**Comment by casek** [comment]
@NuruMayu414 さん。情報ありがとうございます。
その手順でいま操作しても同じことがおこりますか？
それとも、今は起こらないけども、起こったことがあるという感じでしょうか？
何度もすみませんが、再現性追求のため、ご協力おねがいいたします！

**Comment by chihiro-adachi** [comment]
こちら現時点のmasterで再現不可のため、クローズします。
