### ISSUE TITLE
【改善要望】検索中の際、検索中とわかるような状態にしてほしい。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#810]
■対象画面：検索系の各画面
■機能名：検索機能（小窓での検索も含む）
■内容：
個人的主観かも知れないが、
検索機能全般で、検索中なのかどうかわかるようにしていただきたいです。
また、小窓検索で検索結果が0件の場合、メッセージも表示されないので、検索中なのか終わったのかわかりづらいです。
■想定動作：
検索中の場合、一部画面が触れなくなるなどのような形や、砂時計みたいなものを表示してもよいのでは？

以下一例。
![2222222](https://cloud.githubusercontent.com/assets/13776434/9956232/2242c464-5e32-11e5-8d4e-d49df7b847dc.PNG)

**Comment by okazy** [comment]
POSTするものは読み込みが走っているので現在のままでも検索状態だとわかるかと思います。
ajaxで検索が走るものについては表示を工夫して検索状態だとわかるようにしたほうがいいかと思います。

**Comment by xuelian311** [comment]
4系メジャーバージョンアップ時に対応がされておらず、長期間にわたって議論が停止していますので、一度クローズいたします。引き続き検討を希望される場合は、新しいIssueを立て、Issue番号を関連付けいただけますと幸いです。
