### ISSUE TITLE
商品CSV登録画面でCSVファイルの作成方法によってエラーが発生する

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#811]
管理画面の商品CSV登録です。

CSVファイルをアップロードする際、以下の方法で作成したCSVファイルをアップロードしようとすると画面が真っ白になりました。
→ Excelを立ち上げシート1枚にし、何も入力せずに csv形式で保存したファイル

カテゴリCSV登録でも同じ動きでした。

※ テキストエディタで、何も入力せずにcsv形式で保存したファイルだと「空のファイルは許可されていません。」と表示されました。Excelの場合も同じようにエラーを表示してほしいです。

**Comment by chihiro-adachi** [comment]
#886 にて修正済。クローズします。
