### ISSUE TITLE
商品マスタの絞り込みで、該当するデータが0件になった場合に絞込のリンクが消えてしまう

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#812]
管理画面の商品マスタ画面です。

商品を検索し 1件以上商品があった場合に、「公開」や「非公開」、「在庫なし」などで絞り込むと 「検索条件に該当するデータがありませんでした。」のみ表示され、再度検索しないといけなくなりました。
できれば、「公開」や「非公開」、「在庫なし」の絞り込みリンクは表示されたままにしてほしいです。

**Comment by tamagoya** [comment]
@Yangsin 
該当件数0件であっても、「検索条件に該当するデータがありませんでした。」と例外処理せず、「検索結果 0 件 が該当しました」とそのまま表示すれば良いのではないかと思うのですがどうでしょうか。
* 現状
![default](https://cloud.githubusercontent.com/assets/1086015/10186699/fd3792fc-678d-11e5-922e-55f91a339555.PNG)

* 変更後
![default](https://cloud.githubusercontent.com/assets/1086015/10186701/01cfcbea-678e-11e5-857b-1e51622cc4d1.PNG)

これならば、絞込みリンクを使って該当数が0件になっても、継続して絞込みリンクを使えます。

**Comment by tamagoya** [comment]
もう一つの案として、絞込みリンクを以下の様に移動させるという案もあります。

* 変更後2
![2](https://cloud.githubusercontent.com/assets/1086015/10188654/fd006af8-679b-11e5-9227-fb61b1225439.PNG)

上記の方法は以下の利点があります。
* 0件の時のページネーションやCSVダウンロードなどの挙動を考慮する必要がない
* 「検索条件に該当するデータがありませんでした。」という例外処理が、顧客マスタ、受注マスタと同じになる

デザイン面での優劣もあると思うので、コメントして頂ければと思います。

**Comment by Yangsin** [comment]
1案がシンプルで良いと思います

**Comment by k-yamamura** [comment]
1案にするなら会員管理画面等の0件の時も同じように統一してください。
「検索結果 0 件 が該当しました」という文言おかしくないでしょうか?
受注管理画面だと帳票プラグインで印刷もできるようになりますが0件の時も問題なく動作するのでしょうか。

**Comment by Yangsin** [comment]
2案の場合は、絞込のリンクの位置をかえるということか、
検索結果の有無によって表示場所が変わるということでしょうか？

@k-yamamura のご意見もごもっともだと思いますが @tamagoya はいかがでしょうか？

**Comment by k-yamamura** [comment]
商品管理の画面だけが検索条件が別にあるというUIになっているため、
2案が本来あるべき姿だと思います。

**Comment by tamagoya** [comment]
@Yangsin @k-yamamura
私は1案がいいのかなと思います

(1)商品、会員、受注検索画面の不統一になる問題と、(2)0件時に表示させるべき機能が不明確な問題は、切り分けて考えるべきかと思います。

(1)の問題については、商品、会員、受注検索画面すべてにおいて、検索結果が0件であろうとも操作が表示されるエリア(絞込み機能やCSVダウンロード機能が表示される横長の枠)は表示されるように変更するべきかと思います。

ただし、(2)の問題があるので、0件での操作が想定されていないもの(帳票プラグインで印刷など)は、非表示にするなどの処理を作ればよいかと思います。

**Comment by tamagoya** [comment]
「検索結果 0 件 が該当しました」という文言はおかしい気がするので、0件のときには文言の変更をした方が良いかと思います。

**Comment by k-yamamura** [comment]
@tamagoya 
表示されるエリア(絞込み機能やCSVダウンロード機能が表示される横長の枠)は表示されるように変更するべきかと思います。
と書いていますが0件の時は何に使うのでしょうか?

**Comment by tamagoya** [comment]
@k-yamamura 
0件の場合で分岐するなら、表示されるものと表示されないもので、以下のように分類されるかと思います。

* 検索結果に影響する操作(表示される機能):
 * 絞込み機能
 * ソート機能 など
* 検索結果を操作する操作(表示されない機能):
 * 1ページの表示件数
 * CSVダウンロード
 * 帳票プラグイン など

検索結果に影響する操作は、0件であっても再検索するのに使うので、表示したままが良いかなと思います。
もし、上記2つで種別の違う操作なので、別エリアに分けて表示させる方がよいのであれば、それでも良いかなと思います。

**Comment by k-yamamura** [comment]
@tamagoya 
検索結果に影響する操作は、0件であっても再検索するのに使うので、表示したままが良いかなと思います。
→最初から検索条件エリアに含ませておけばいいのではないでしょうか?

**Comment by tamagoya** [comment]
@k-yamamura 
利用イメージとして、上部の検索でざっくり絞って、中央部の絞込みなどで微調整する感じなのかなと思ったのですが、中央部で再度微調整をする操作が必要なのか(上部に統合したほうが良いのか)は、正直よくわからないですね。
このあたり絞込みリンクのUIを考えた人の意図と、実際に使っている人の使い勝手を伺いたいかなと思います。

**Comment by ryo-endo** [comment]
#1470 で対応済みでしたので、CLOSEします。
