### ISSUE TITLE
商品マスタ登録時に登録ボタンのダブルクリックで商品が重複して登録される

### ISSUE THREAD

**Issue by NuruMayu414** [EC-CUBE/ec-cube#813]
管理画面の商品登録画面です。

「商品を登録」ボタンを連続でクリックすると、一度に2件以上商品が登録されました。
状態を「公開」にしていた場合、予期しない商品が表示されてしまうので可能であれば登録ボタンは連続したクリックは受付けないように制御してほしいです。

**Comment by chihiro-adachi** [comment]
#1076 #1077 #1130 で修正のためクローズします。
