### ISSUE TITLE
【改善要望】受注管理画面にて検索実行時、追加条件の箇所が広がって表示されてしまう。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#814]
■対象画面：受注マスター
■機能名：受注検索
■内容：
検索を実行すると（追加条件を閉じた状態）
追加条件の部分が開いてしまう。
■想定動作：
検索実行時、以下挙動とする。
追加条件を開いている場合は開いた状態のまま。
追加条件を閉じている場合は閉じた状態のまま。

**Comment by Yangsin** [comment]
#770 重複
