### ISSUE TITLE
【改善要望】受注検索結果一覧から、メール通知入力画面に遷移、戻ってくると検索結果クリアされている。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#815]
■対象画面：受注マスター
■機能名：受注検索、メール通知
■内容：
以下、操作の流れ。
1.受注検索を実施
2.検索結果から、メール通知を選択
3."検索結果へ戻る"ボタンを押下
4.検索画面へ遷移

4.の時に、検索結果がクリアされてしまう。

■想定動作：
"検索結果へ戻る"という文言からも、
検索結果は残っている状態のほうが良いのでは？

**Comment by nanasess** [comment]
重複のため、クローズします #1084
