### ISSUE TITLE
【改善要望】受注登録画面にて、"商品の追加"/"計算結果の更新"実行後、一番上に画面が移動し、受注商品情報セクションもとじてしまう。

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#816]
■対象画面：受注登録、編集
■機能名：商品の追加、計算結果の更新
■内容：
受注登録画面にて、
"商品の追加"/"計算結果の更新"実行後、
一番上に画面が移動し、受注商品情報セクションもとじてしまう。
■想定動作：
受注商品情報セクションは閉じず、
画面の位置も実行時と同じ状態にしておいたほうが
使いやすいのではないか？

**Comment by nobuhiko** [comment]
#772
