### ISSUE TITLE
form_widgetにime-modeが設定されているけどそろそろ不要じゃないでしょうか

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#821]
参考) http://qiita.com/forty4_jp/items/db90141ea02ecafb0967

**Comment by Yangsin** [comment]
type属性値が number, tel, email, url  以外でimeを制御したい場合以外は、必要なさそうですね。

**Comment by Yangsin** [comment]
#1851 のようにデフォルトで消す必要はまだないという判断でクローズします。
