### ISSUE TITLE
パスワード入力欄について

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube#823]
![___ _ _](https://cloud.githubusercontent.com/assets/604492/9980170/4705904a-5fc9-11e5-9ab4-59524fa563f3.png)

2系だと基本的に繰り返し入力を要求されるが3系だと、1回になっている
2回入力させなくて良い感じでしょうか？
また、管理画面でも2系は2回入力させますが、こちらは必要ですか？

ついでに最短が4文字は短すぎると思うので8文字ぐらいにしたほうがいいんじゃないかと思います

あと、会員登録画面のパスワード入力欄はなんだか変な線が下にある

**Comment by Yangsin** [comment]
登録時のパスワードは繰り返し、管理画面は1回 は同感です。
項目の追加ですので既存への影響はなく、3.0.xで対応可な範囲におもえます。

パスワード4文字は確かにそうですね。
CCEでも最低でも8文字ですので、password_min_len は8が妥当ですね。
https://www.ipa.go.jp/security/vuln/CCE.html

4文字を維持したい場合は、app/config/eccube/constant.yml を置いて値上書きで対応可能なので、こちらも、3.0.x で対応可能な仕様変更とします。

> 会員登録画面のパスワード入力欄はなんだか変な線が下にある

必須項目とそれ以外のエリアがわかれているデザイン上の仕様の箇所かと思います。
div が dl_table と dl_table not_required で分けている部分ではないでしょうか？

**Comment by nobuhiko** [comment]
> 必須項目とそれ以外のエリアがわかれているデザイン上の仕様の箇所かと思います。

なるほど、そういうデザインなんですね。
バグってるのかと思いました :sweat:
