### ISSUE TITLE
CartService/OrderServiceの作成

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#83]
購入フローから注文完了までのビジネスロジックを @chihiro-adachi と二人で進めていってます。

SC_XXXX系の登場人物が多いため乗せ換えが難しく、なおかつ、今のロジックのまま開発を進めるより、オブジェクト設計・フロー設計を合わせて見なおしたほうがいいと判断したため、リファクタ込で進めていっております。

具体的には、以下の作成をしています。
* CartService
  + カートセッションの管理クラス
* OrderService
  + 注文まわりの管理クラス

[乗せ換えフェーズの原則](https://github.com/EC-CUBE/ec-cube/wiki#%E4%B9%97%E3%81%9B%E6%8F%9B%E3%81%88%E3%83%95%E3%82%A7%E3%83%BC%E3%82%BA)から外れるイレギュラーな対応となるため、周知の意味で取り急ぎIssueをたてさせていただきます。

**Comment by ttsuru** [comment]
いろんな会社さんが出されてるプラグインで処理しているような送料、手数料、値引きの計算がプラガブルっぽくできると嬉しいです。

Order を DeliveryService や PaymentService に投げると上記送料、手数料、値引きが返ってくる。
同じように CouponService  や SpecalDeliveryService に投げた際に結果として料金が返って。

のような感じですと、例えばDeliveryFeeのようなものを変更する場合や、PaymentServiceを変更する場合によいのではないかと思います。

**Comment by nanasess** [comment]
あまり Service を細分化すると乱立してしまって、結果的に密結合になってしまうので、 Strategy にするのが良いかと。

**Comment by Yangsin** [comment]
βでひとまずクローズします。  
引き続きご意見等ありましたら、別途お寄せいただけると助かります。
