### ISSUE TITLE
Str::isBlank(null) が false になってしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#838]
https://github.com/EC-CUBE/ec-cube/blob/591e49e4122311b3d1ff282f65cbd98bdfd7a2ae/src/Eccube/Util/Str.php#L205

`is_string()` で先に評価してしまっているのが原因。

2系の SC_Utils::isBlank() を移植する。

**Comment by nobuhiko** [comment]
なんだろう、テスト書こうぜって感じなバグ？

**Comment by nanasess** [comment]
Str のテストをせっせと書いてて見つけましたw

**Comment by ttsuru** [comment]
SC_Utils::isBlank() っていりますか？ ``!is_null && is_string()`` 的なのではダメなんですか？

**Comment by nanasess** [comment]
`Str::trimAll('')` が `null` を返してしまう問題も見つけましたので、合わせて修正します。

**Comment by ttsuru** [comment]
非常に細かいんですが、Namespaceの ``Eccube\Util`` 以下の命名がバラバラですね・・・

```
Cache.php
EntityUtil.php
Str.php
```

これって、他の命名と一緒であれば

```
CacheUtil.php
EntityUtil.php
StringUtil.php
```

とかですよね・・・

**Comment by nanasess** [comment]
@ttsuru 命名規則は、別に issues を起こしておきますね。

**Comment by ttsuru** [comment]
@nanasess ありがとうございます！

**Comment by ttsuru** [comment]
すいません、そもそものお話になってしまうのですが、 ``isBlank()`` は必要なのでしょうか。
``empty`` ですまない場合があるのでしょうか？

EC-CUBE2の時から違和感があったのですが、スペースのみ ``がisBlank`` で通過してしまうと、1バイト以上がblankになってしまいませんか？

ある程度、型を想定できるはずですので型に応じた実装を行った方が良いのではないでしょうか。

**Comment by ttsuru** [comment]
https://github.com/EC-CUBE/ec-cube/blob/141084bf57a1501ec96d0ce5e402f793c4575e5a/src/Eccube/Controller/Admin/Product/CsvImportController.php
こちらのみで利用されていますが、ここのチェックは ``empty()`` で事足りると思います。

**Comment by nanasess** [comment]
array が array だって一目でわかればいいのですけど、 文字列なのか array なのか、わからないので、チェックメソッドを統一してしまおうという考えです。

`count(array) > 0` とか、 `empty(array)` とか、 strlen(string) > 0 とか点在させたくないので。

> EC-CUBE2の時から違和感があったのですが、スペースのみ がisBlank で通過してしまうと、1バイト以上がblankになってしまいませんか？

たしかにそうですが、こういう時は trim しませんか？

**Comment by nanasess** [comment]
PHP に慣れたプログラマーは型を推測できるから標準関数のみでも、コーディングルールの統一で問題ないのですが、そうでない方は、フレームワーク側で抽象化した関数が使えた方が便利だと思います。

**Comment by ttsuru** [comment]
@nanasess 
arrayでも文字でもemptyでいいのではないでしょうか。
なんでもUtilにするというEC-CUBE2系の考え方はわかりますが、いまのPHPで必要がある場面があまり想像できません。

**Comment by shinichi-takahashi** [comment]
@nanasess 
私も @ttsuru と同意見です。
`empty()` でまかなえるものはそれをつかい、そうでなく厳密にチェックしたいものは別途で記述することで差別化（≠点在）できます。

また、文字列なのかarrayなのかわからない場面ってそうそうないとおもいます。

**Comment by nanasess** [comment]
@ttsuru `empty()` は 0 を true としてしまう罠があるので、個人的には避けたいです

**Comment by nanasess** [comment]
> また、文字列なのかarrayなのかわからない場面ってそうそうないとおもいます。

僕でもよく迷いますが、みなさん一目でわかるものですかね。。。

**Comment by ttsuru** [comment]
PHPには言語上の問題があるのはご指摘の通りだと思います。

かといって、再帰的にチェックをするような関数をutilとしていれるのも避けたいと思います。

array が想定される変数にarrayもしくはnull以外が入ることはないでしょうし、stringが想定される内容にstring、integer、float、null 以外が入ることが想定されないと思います。

**Comment by ttsuru** [comment]
ちなみにPHPdocを書くことになっているので、arrayとobjectとそれ以外は区別されるはずです。
objectが増えてきたので、objectのemptyも今後増えてくると思いますので、Util的な考え方自体、よろしくないと思います。

**Comment by shinichi-takahashi** [comment]
@nanasess 

> 僕でもよく迷いますが、みなさん一目でわかるものですかね。。。

少しもぐればわかりますよね？

**Comment by nanasess** [comment]
> array が想定される変数にarrayもしくはnull以外が入ることはないでしょうし、stringが想定される内容にstring、integer、float、null 以外が入ることが想定されないと思います。

スキルの高い方は想定できるのだと思います。
少なくとも、僕は直感的には想定できません。

> 少しもぐればわかりますよね？

スキルの高い方は、もぐればわかると思います。
僕のように、 PHP のスキルが低いと、もぐる時間も勿体無く感じます。

**Comment by ttsuru** [comment]
すいません、スキルの話になってしまうと水掛け論になってしまうと思いますので。
Entityの空や、arrayもあり、それぞれごとに処理方法は異なると思います、

それを一つの関数で処理してしまうということはあまりよくないのではないでしょうか。

**Comment by nobuhiko** [comment]
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Repository/OrderRepository.php#L79
emptyでバグってる例

**Comment by nanasess** [comment]
> それを一つの関数で処理してしまうということはあまりよくないのではないでしょうか。

どのようなデメリットがありますでしょうか？
好みのような気がします。
Entity の空は、もはや空ではないと思いますし、 Entity が初期状態であるかどうかチェックするケースは、あまりないのかなと。

EC-CUBE で独自実装しているのに違和感があると思いますが、同様のメソッドが Symfony にあれば、みなさん自然に使うような気がしています。
(おそらく思想の違いで実装されないんだと思いますが)

**Comment by ttsuru** [comment]
@nanasess 
たとえば、DoctrineからとってきたEntityの集合が空の場合にはobjectが返ってきます。
再帰的にarrayを見て空かどうかを判定するなどの処理も疑問です。

PHP 4の時代には有効でしたが、現状はしっかりと型を想定した上で実装する必要があります。

EC-CUBEで独自に実装をすることに対する違和感というわけではなく、型を無視したチェックを行う関数を多用することに疑問があります。

**Comment by ttsuru** [comment]
@nobuhiko 
これってどういう意味でバグなんですか。
前後関係追ってないのでなんとも言えないんですが。

**Comment by nobuhiko** [comment]
@ttsuru 0で検索しようとすると無視するんです。0はempryなので

**Comment by ttsuru** [comment]
@nobuhiko 
DBのIDで0って想定されないんじゃないですか？

本来は ``is_null() && strlen()`` とかの方がいいとは思いますがバグではないと思います。

**Comment by nanasess** [comment]
@ttsuru 
型を想定できる方は良いのですけど、簡単に想定できない方もいらっしゃいますので。。。
型を想定せずに isBlank() を使用して、具体的なデメリットがあれば使用を避けた方が良いと思いますが。

再帰処理は、連想配列時代の遺物ですが、残しておいてもデメリットはないかなと。

**Comment by nobuhiko** [comment]
@ttsuru あー、その下が全部おかしいんです。idだけじゃないです。金額とか

**Comment by nanasess** [comment]
@Yangsin Str::isBlank(null) が false になってしまうのはバグですので、よろしくおねがいします。

**Comment by seasoftjapan** [comment]
`SC_Utils::isBlank()` は、最近もハマったので勘弁して欲しいです。
配列渡したら、例外で落ちてくれるなら良いのですが・・・

**Comment by ttsuru** [comment]
@nanasess 
想定できないと言われていますが、想定しないといけないと思います。
特にarrayとstringとobjectの3種類を全部一括して処理してしまうロジックの実装は危ないと思います。

また、メソッドの長さやphpdocを書くというルールからも想定ができない例が分かりづらいかと思います。

**Comment by ttsuru** [comment]
@seasoftjapan 
ぼくも同じようにはまった例がありました。
ルーズなチェックはメリットもありますが、正しくチェックしないことのデメリットもあります。

**Comment by nanasess** [comment]
たぶん、思想の違いから、どちらが正しいかという答えはでないので、とりあえずは使いたい人が使えばいいと思いますが、いかがでしょうか。

**Comment by ttsuru** [comment]
@nanasess 
本体で使うことはしない方が良いと思います。

**Comment by nanasess** [comment]
@ttsuru それだと、たぶんお互い引かないと思いますので、使いたい人が適材適所に使って、まずは安定化をはかりませんか？
使った箇所で、具体的なデメリットが発生したのなら、コメントを入れた上で、そこは厳密なチェックに変更すれば良いと思います。

**Comment by ttsuru** [comment]
本体でisBlankが必要な部分が想像できないです。
すでに現時点でも具体的なデメリットとして、Objectに対応していないデメリットがあります。

型に合わせてちゃんと実装すべきだと思います。

型を意識せずに問題を起こすのではなく、型を意識しながら型に合わせた実装が必要なのではないでしょうか。

**Comment by ttsuru** [comment]
わからない方も、phpdocなり、var_dumpなりでわかっているはずだと思います。
本当に型がmixedになるシーンがあまり想像できません。

**Comment by ttsuru** [comment]
今までは未定義がnoticeなっていませんでしたが、PHP5.3以降では未定義は未定義で別のエラー処理をすべきになっています。

そのようなかで、すべからく同じisBlankで処理するということ自体が思想として時代にあっていないのではないでしょうか。

**Comment by nanasess** [comment]
@ttsuru 
お互いに、メリットデメリットが想像できないのだと思いますよ。
ここで、どちらが正しいという答えはでないと思います。それでも正しいとおっしゃるかもしれませんが。

**Comment by ttsuru** [comment]
便利だからとUtilをどんどん作っていったらUtilばかりになりませんか？

**Comment by nanasess** [comment]
@ttsuru どちらの思想が正しいかという議論は、答えがでないと思いますので、終わりにしませんか？

**Comment by ttsuru** [comment]
思想が正しいかよりも、実装として両方が乱立してしまう状況は良くないと思います。

**Comment by nanasess** [comment]
@ttsuru このまま議論を続けても、答えがでないと思いますので、終わりにしませんか？

**Comment by ttsuru** [comment]
そうですね。あとはどちらにするかですね。
もし、変更するのであれば既存のものも全てisBlankに書き換えるべきなのではないでしょうか。

**Comment by seasoftjapan** [comment]
カスタマイズで利用する立場では、統一はされていて欲しいです。

素の PHP で空文字を評価する手法は複数あります。その揺らぎを無くす用途で独自の関数を定義するのは賛成です。

その上で、スカラーならばスカラー用の関数、配列ならば配列用の関数でチェックして欲しいです。

Utilをどんどん作っても、素の PHP コードで実装がバラつくよりは良いと思います。

**Comment by nanasess** [comment]
「型を意識した実装にすべき」というご意見が多いので、以下のように改良しようと思います。

- 前提として「型を想定するのが困難な、ビギナー層(特に2系からのユーザー)」でも安心して利用できるメソッドにしたい
- `ArrayCollection::isEmpty()` もサポートする
- 配列型、オブジェクト型に対して使用した場合は `E_USER_DEPRECATED ` を出す
- 引数 `$greedy` は、デフォルト false にする

**Comment by seasoftjapan** [comment]
既存メソッドについては、互換性の問題もあるかもしれませんし、@nanasess さん提案のような感じで良い気がします。
加えて `@deprecated` として、これからの本体実装では、もっと明確に「(文字列として)未入力か」を評価できる別のメソッドを使って欲しいです。

スカラーと NULL 以外が渡ったら、致命的エラーで落ちて欲しいです。その方が、ビギナー層も含め、親切な動作だと思います。(若しくは、false を返しても良いかもしれませんが、個人的にはその需要は無いです。)

ただ、__toString() が定義されているオブジェクトに限っては、(自分は普段扱わないので) どう扱うのが適切か自信が無いです。

・・・と、ここまで打って、スレッド冒頭を振り返ると、EC-CUBE 3 で 「Str::isBlank()」 というのが追加された感じなのでしょうか?

ならば、クラス名的にも、文字列として順当に評価できる範囲で扱うのが筋だと思います。

EC-CUBE 3 に関してビギナー層(2系からのユーザー)である私は、「Str::isBlank()」でオブジェクトや配列を扱うのは混乱しそうです。

**Comment by nanasess** [comment]
@seasoftjapan 
ありがとうございます。
`Str::isBlank()` に関しては、 https://github.com/EC-CUBE/ec-cube/pull/658 で追加されていますね。

今回の `Str::isBlank(null)` が false を返してしまう問題を @k-yamamura さんに相談したところ、本当は配列もチェックできるようにしたいということだったので、 2系の `SC_Utils::isBlank()` を移植しようという話になったのでした。

`Str` クラスでは、文字列のみを対象とするのは本筋だと思いますので、配列やオブジェクトを扱うメソッドは別途検討します。
(現時点では、現状発生している不具合修正・テストに注力したいです)

ただ、デザイナーやプログラミングに不慣れな方にとって、型を意識するのは大変難しいはずなので、厳密に例外をスローするのは酷な気がしています。

**Comment by seasoftjapan** [comment]
アプリケーションの利用者にとって、例外終了することは迷惑だと思います。
しかし、開発者にとっては親切な動作だと思っていました。

とは言え、この辺りは、言語仕様・アプリケーションの規則に準じた動作で良いと思います。
PHP だと、Warning を発して、NULL を返すとかですかね・・・

**Comment by nobuhiko** [comment]
@nanasess さんが想定している人は、プラグインを作るor使う人な気がするので、プラグインから使えるユーティリティークラスにすればいいんじゃないでしょうか？

**Comment by nanasess** [comment]
> プラグインを作るor使う人な気がするので

「カスタマイズはプラグイン作成を推奨」とされてますけど、実態は、プラグイン開発となると、ビギナー層には難易度が高すぎて、2系と同じような要領で、本体を直接カスタマイズするのが精一杯なんじゃないかなと思ってます。
なので、プラグイン用のユーティリティというのは悩ましいところですね。

**Comment by nobuhiko** [comment]
@nanasess 
そういう人を相手にするのであれば、ドキュメントこそ重要だと思いますよ？
http://fuelphp.jp/docs/1.8/classes/str.html
このくらいのレベルは最低限欲しいです

**Comment by nanasess** [comment]
@nobuhiko 
まだ甘いと思いますが、できる限り頑張ってコメントも書いてみました。
https://github.com/nanasess/ec-cube/commit/6acdcbb4c58e796cef37b551d8641a4433057504

例とかも書きたいですが、 PHPDocumentor で表現できるんでしょうか？？ fuelphp は独自にやってるんですかね。

プラグイン開発の難易度を下げるのは必須だと思ってますので、まずは本体の安定を目指しつつ取り組んでいきたいと思っています。

**Comment by ttsuru** [comment]
@nobuhiko
僕も同意します。
Silex + Doctrine ORM + Twig なので、おそらくSymfonyに慣れ親しんだ方以外ムスカしいことが一番の問題かと思います。

**Comment by nobuhiko** [comment]
@nanasess 
例もかけるようです
http://www.phpdoc.org/docs/latest/references/phpdoc/tags/example.html

**Comment by nanasess** [comment]
@nobuhiko ありがとうございます。時間をみて検証してみます。

**Comment by chihiro-adachi** [comment]
みなさまありがとうございます。
現時点では本体の安定化を重視したく、#840 については不具合の修正という観点でマージさせていただきたいと思います。よろしくお願いいたします。

**Comment by chihiro-adachi** [comment]
#840 にて修正いただいたのでクローズします。
