### ISSUE TITLE
Namespaceの Eccube\Util 以下の命名がバラバラ

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#839]
```
Cache.php
EntityUtil.php
Str.php
```

となっているが、以下が正しい

```
CacheUtil.php
EntityUtil.php
StringUtil.php
```

https://github.com/EC-CUBE/ec-cube/issues/838#issuecomment-143184572

**Comment by okazy** [comment]
https://github.com/EC-CUBE/ec-cube/pull/2650 にて対応済みですのでcloseします。
