### ISSUE TITLE
trimAll が 全角スペースを半角スペースに変換してしまい、0が来てもnullが返ってくる

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#841]
https://github.com/EC-CUBE/ec-cube/blob/591e49e4122311b3d1ff282f65cbd98bdfd7a2ae/src/Eccube/Util/Str.php#L236

PHPの ``===`` を使わずに ``==`` を使っているため、 ``null == 0`` となり、0や空文字の場合にはnullがかえります。

また、全角を意図しない場合も含め半角に変換しています。
``preg_replace("/(^\s+)|(\s+$)/u", "", $string);`` の方が意図に近いのではないでしょうか。

**Comment by nanasess** [comment]
ありがとうございます。
一部、以下で修正していますがご指摘の点も後ほど反映しておきますね。
https://github.com/nanasess/ec-cube/commit/c15c207a3b92ff1e62e30f1a044450cd0b7f3b74

**Comment by chihiro-adachi** [comment]
#840 にて修正いただいたため、クローズします。
