### ISSUE TITLE
カートに販売制限数以上の商品を入れてもエラーメッセージがでない

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#844]
■対象画面：商品詳細、カート画面
■機能名：カートに商品を入れる
■内容：
商品詳細画面にて、商品をカートに入れる際、
「販売制限数(もしくは在庫数))<注文」となっている場合、
現状、販売制限数までカートにセットされる。
エラーメッセージが表示されない

■想定動作：
販売制限数までカートにセットされた旨のメッセージを表示していただきたい
と考えております。

**Comment by shhirose** [comment]
#828 
#835 
で対応中です。

**Comment by chihiro-adachi** [comment]
#828 にて対応.
