### ISSUE TITLE
soft_delete filter の使用について

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#846]
#845 にて

 `EntityUtil` クラスのテストを作成するにあたって、 soft_delete filter について、以下のような問題があると感じました。
- 常に適用されるわけではない？適用されるのは LAZY loading の時のみ？とにかく挙動がトリッキーで大変わかりにくい
- soft_delete filter でフィルタリングされたとしても、オブジェクトが返ってくる。
- 空のオブジェクトが返ってくるならわかりやすいが、オブジェクトのプロパティにアクセスしようとすると `EntityNotFoundException` をスローする
- もちろん `EntityNotFoundException` はランタイムなので、不用意にスローされる可能性がある
- 実装者は、 soft_delete 対象のオブジェクトかどうか見分けて `EntityUtil::isEmpty()` を使用しなくてはならない

明示的に `del_flg = 0` とコーディングしなくても、論理削除されたデータをフィルタリングしてくれるのがメリットだと思いますが、デメリットのほうが大きく感じます。

soft_delete filter を使用せず、明示的にコーディングした方が安全かつ、わかりやすいのではないでしょうか。

認識が間違っておりましたら申し訳ございません。
soft_delete filter の使用を肯定される方のご意見もお聞きしたいです。

**Comment by ttsuru** [comment]
soft deleteの実装を変更する必要がありそうですね。
ちなみに、常に適応されるはずです。
なので、Lazy loadingのみということはなく、トリッキーな動作はないはずです。
また、del_flg = 0 をコード内で実装した場合にはリレーションをlazy loadingで取得した場合にもdel_flg=0のもののみを選別する必要がでてくるなど、それはそれで面倒な気がします。
どちらにせよ、soft deleteは他のFWでもFW側で対応すべき内容で、ソフトウェア側で実装すべき内容ではないと思います。

> 空のオブジェクトが返ってくるならわかりやすいが、オブジェクトのプロパティにアクセスしようとすると EntityNotFoundException をスローする

これはDoctrineのEntityの実装や、Twigでの書き方が悪いせいで、soft_deleteが悪いわけではないと思います。

**Comment by nanasess** [comment]
@ttsuru soft_delete filter のメリットを、もう少しお伺いしたいです。
EC-CUBE 本体の開発者だけが意識していれば良い(フレームワーク側で隠蔽されている)のであれば、使用するのは全く構わないと思いますが、現在の実装では、カスタマイズユーザーも意識せねばならず、デメリットの方が大きく感じます。
特に、論理削除されたデータも含めて取得したい場合です。

以下のようなコードは、実装の本質から外れるため、できるだけ使用しないようにしたいです。

```php
        $softDeleteFilter = $this->entityManager->getFilters()->getFilter('soft_delete');
        $softDeleteFilter->setExcludes(array(
            'Eccube\Entity\ProductClass'
        ));
```

> また、del_flg = 0 をコード内で実装した場合にはリレーションをlazy loadingで取得した場合にもdel_flg=0のもののみを選別する必要がでてくるなど、それはそれで面倒な気がします。

例えば、 Order::getOrderDetails() を以下のようにしておけば、 soft_delete filter を使用するより、直感的でわかりやすいのではないでしょうか。(動かしてないのでバグっていたらすみません)
Java ではよくある実装です。

```php
    public function getOrderDetails()
    {
        return $this->OrderDetails->filter(
            function($OrderDetail) {
                return $OrderDetail->getDelFlg() == 0; // 削除判定は isDeleted() というメソッドにしたい
            }
        );
    }
    
    public function getOrderDetailsHasDeleted()
    {
        return $this->OrderDetails;
    }
```

余談ですが、 Lazy loading は、非同期で結果を返しているわけでもないので、パフォーマンスに大きな影響があるため、極力使用すべきでは無いと感じています。
Java ではずいぶん前からアンチパターンとされていますが、 PHP では常套手段なのでしょうか。

> どちらにせよ、soft deleteは他のFWでもFW側で対応すべき内容で、ソフトウェア側で実装すべき内容ではないと思います。

フレームワーク側では、使用するアプリケーションが論理削除を扱っているかどうかわからないので、アプリケーション側の仕事かなと思います。

> これはDoctrineのEntityの実装や、Twigでの書き方が悪いせいで、soft_deleteが悪いわけではないと思います。

カスタマイズ利用者にとって、特別な意識をしなくても実装できるような書き方ができるのであれば良いと思います。

**Comment by ttsuru** [comment]
@nanasess 

> EC-CUBE 本体の開発者だけが意識していれば良い(フレームワーク側で隠蔽されている)のであれば、使用するのは全く構わないと思いますが、現在の実装では、カスタマイズユーザーも意識せねばならず、デメリットの方が大きく感じます。
> 特に、論理削除されたデータも含めて取得したい場合です。

そもそも、論理削除されたものをカスタマイズやプラグインで取得したいという内容がイレギュラーです。
どのようなシステムでも基本的に論理削除したデータは利用しなくて良くなっているはずです。
「特に、論理削除されたデータも含めて取得したい場合」というのがイレギュラーでないケースが私にはあまり想像できません。
イレギュラーな動作であれば、 ``setExcludes`` での指定で良いと思います。

> 例えば、 Order::getOrderDetails() を以下のようにしておけば、 soft_delete filter を使用するより、直感的でわかりやすいのではないでしょうか。(動かしてないのでバグっていたらすみません)
> Java ではよくある実装です。

Javaでなくても一般的にある実装です。
しかし、 ``getOrderDetails()`` をオーバーライドするのは例としては良くないと思います。
``getActiveOrderDetails()`` などとすることで、実際に有効なもののみを取得する例はDoctrineでも一般的です。
こちらについては他にもリレーションを含んだUPDATEやINSERTの挙動などにも影響するため、多くの考慮が必要になります。

指摘されているように、以下の挙動をオーバーライドするか、softdeleteロジックを改良して、nullが返るようにした方が適切かと思います。

> 空のオブジェクトが返ってくるならわかりやすいが、オブジェクトのプロパティにアクセスしようとすると EntityNotFoundException をスローする

また、Lazy loadingがアンチパターンとおっしゃられていますが、これはRailsでよく言われる「N+1問題」という名前が付いています。
ORMを使った場合にすべてをJoinするとそれはそれで問題が出てきますので、適切なタイミングで適切なJoinを行うなりを実装することが推奨されていることは間違いありません。

結論としてお伝えしたいことは、ORMにあったベストプラクティスに従い実装を行うことかと思います。

**Comment by nanasess** [comment]
> 結論としてお伝えしたいことは、ORMにあったベストプラクティスに従い実装を行うことかと思います。

これを見ると、「論理削除使うな」が Doctrine2 ORM のベストプラクティスですかね...
http://ocramius.github.io/doctrine-best-practices/#/73

**Comment by ttsuru** [comment]
@nanasess 
本来はそうだと思います。
削除ではなく、非表示という方が正しいという流れですね。

**Comment by okazy** [comment]
3.nでは対応したのでクローズします。
