### ISSUE TITLE
インストール時に登録されるサンプル商品の作成者(Member)が論理削除されている

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#847]
インストール時に登録される、 `dtb_product` は `creator_id = 1` となっているが、この対象ユーザーは `del_flg = 1` でインストールされる。
結果、 `Product::getCreator()` で、 LAZY loading したオブジェクトのプロパティにアクセスすると、 `EntityNotFoundException` がスローされる。

https://github.com/EC-CUBE/ec-cube/pull/845 で作成したテストケースで使用しているため、変更する場合はこちらも修正が必要。(テストケース内でデータ生成するようにしたい)

**Comment by ttsuru** [comment]
論理削除されたユーザーを ``getUser()`` 的にするのはいろいろ方法ありますね。
Doctrineだと、 ``getUserName()`` 的なメソッドを用意して、
``try {} catch () {}``的にやってあげていない場合はblank出すとかよくやってました。

**Comment by nanasess** [comment]
やはり、参照側のエンティティで頑張るのが一般的なのですね。。。

**Comment by ttsuru** [comment]
直で挙動変えるよりは他にメソッド用意しちゃう方がいいかもですね。Creatorは実際にはgetNameぐらいしかないでしょうから・・・

**Comment by Yangsin** [comment]
初期インストール時に登録される管理者ユーザーのIDに置き換えるくらいでもよさそうですね。

**Comment by trebla-on** [comment]
こちらは商品だけではないですね、
基本的に商品、カテゴリ、ニュースなどのテーブルにcreator_idを設定したらこの管理者レーコドの削除フラグは1するダメみたい、インストールの時creator_idを治すは一部だけなります、管理者はいつでも削除可能です
対応意見
１■管理者削除する時に全てのcreator_idを直す、詳しく調べてないですがテーブル20個ぐらいです
備考：あるテーブルのcreator_idはNULLありその時NULLにする、NOT NULL場合は現在ログインユーザーのIDに変える、
２■getCreator()を呼ぶときに削除フラグ見ないようにする

**Comment by chihiro-adachi** [comment]
@trebla-on 
ありがとうございます。インストール時だけでなく、管理者が削除された際も考慮が必要ということですね。

以下のように、getCreatorを呼ぶ際に、EntityUtil::isEmptyでチェックを行うのが良いかと思いましたがいかがでしょう。
https://github.com/EC-CUBE/ec-cube/blob/master/src/Eccube/Entity/Order.php#L1352

よろしくお願いします。

**Comment by ryo-endo** [comment]
こちら #2139 で、getCreatorを呼ぶ際にEntityUtil::isEmptyでチェックを行う対応を入れましたのでCloseさせていただきます。
対応不十分な場合は、別途コメントいただけたらと。よろしくお願いします。
