### ISSUE TITLE
ユニットテストの基底クラス

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#854]
現在、 tests/Eccube/Tests 以下に点在する基底クラスをまとめる。

以下のような実装に近いイメージ
https://github.com/bolt/bolt/blob/master/tests/phpunit/unit/BoltUnitTest.php

- ~~createApplication() は static で呼び出せるようにしたい。 多くのテストは setUp() で毎回生成する必要ないと思われるので、 `setUpBeforeClass()` で `Application` の生成をしたい~~ sqlite のサポートを考えると setUp() ごとに生成する必要がある
-  ~~DB 関連で、 Application 不要なテストなどは、 データベースのコネクションのみを取り出せるようにしたい~~ sqlite のサポートを考えると、 Application インスタンスを生成する必要がある
- ~~[doctrine/data-fixtures](https://github.com/doctrine/data-fixtures), [nelmio/alice](https://github.com/nelmio/alice) を使用して、 Fixtures の生成ができるようにする~~ nelmio/alice は PHP5.4以降なので使用できず...
- [fzaninotto/Faker](https://github.com/fzaninotto/Faker) を使用してダミーデータを生成する
- PHPUnit_Extensions_Database_TestCase と \Silex\WebTestCase の両立ができないので、独自に Fixture 生成をハンドリングする
- プラグインのテストも楽にできるようにしたい

**Comment by nobuhiko** [comment]
以前試みましたが、staticで呼び出すの難しかったです
FormTypeのテストなどはsetUpで毎回生成しないと動かなかったです

**Comment by nanasess** [comment]
FormType や、 WebTest は毎回生成しないと難しそうですね...
DB接続を取り出すくらいなら、 static でも大丈夫かなと思うので、 static 関数にして、 setUp() でも setUpBeforeClass() でも呼べるようにしておいたら便利かなと。

いろいろ調べてみると、 Application のインスタンス生成自体は、それほどボトルネックではなく、 LAZY loading が大きなボトルネックになっているような雰囲気です。

ZipTypeTest も参考にさせていただきます。適材適所ですね。

**Comment by nobuhiko** [comment]
ボトルネックは、Application.php なのでそっちが改善されればとりあえずテストも早くなるんじゃないかと

**Comment by nanasess** [comment]
#857 において sqlite の in-memory で動かすためには、 setUp() ごとに毎回 Application を生成する必要がある模様

データベースのコネクションをシングルトンにして、 Application に DI するなんてことができれば万事解決しそうですが。。。

**Comment by nanasess** [comment]
#866 マージされましたのでクローズします。
