### ISSUE TITLE
PHP ビルトインウェブサーバー + sqlite3 でも動かしたい

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#857]
とにかく楽にテストできるようにしたい

**Comment by seasoftjapan** [comment]
2系では、どっちもやりました。

SQLite 2 だったかもしれませんが、SQL 文絡みで何箇所か似たパターンでコケる箇所がいくつかあった記憶がありますが、とりあえずザックリ動かすのはさほど手間はなかったと思います。
エープリルフール用にプロトタイプを作成して、ボツになったネタだったかな・・・

**Comment by nobuhiko** [comment]
Doctrineになってるのでsqliteは普通に動きそうな気が
install.shをちゃんとすればいいだけ？

**Comment by nanasess** [comment]
ビルトインウェブサーバーでのインストールは成功しました。
あとは sqlite3 ですね。

**Comment by nanasess** [comment]
sqlite3 でもインストールに成功しましたので、差分置いておきます。

https://github.com/nanasess/ec-cube/commit/26e7757d7a9e83ed0aebf647215a287f3fd4c5e6

`migration/Version20150716110252.php` で `SQLSTATE[HY000]: General error: 5 database is locked` になる以外は動きました。
ちょっと動かすくらいなら、使えそうです。

以下のコマンドでインストールできます。
```sh
./eccube_install.sh sqlite3
```

以下のコマンドで起動します。

```sh
php -S localhost:8080 -t html
```

Windows 環境では、 bash 等で eccube_install.sh を実行すると、ドライブレターが `/c` になってしまうので、  `c:` に置換してあげれば動きます。

**Comment by ttsuru** [comment]
sqliteでも動いちゃうんですね。
最終的に ``eccube_install.sh`` は ``app/console`` でPHPコードのまま実行できるとメンテも楽になりますね。

**Comment by nanasess** [comment]
in-memory database でテストできるようにしてみました。

https://github.com/nanasess/ec-cube/commit/ee6e49cd33c98f3026b85ec00c1260118f2d6fc0

が、  Application インスタンスを別で生成していたりするとコネクションも別になってしまうので動作しないです。
そして、決して速くはないので、あまり有用ではなさそうです。

**Comment by ttsuru** [comment]
#861 でcomoserのインストールが遅い問題を作成させていただきました。

**Comment by nanasess** [comment]
sqlite でも travis のテストが通るようになりました。(#1378 の修正を含んでいます)
https://travis-ci.org/nanasess/ec-cube/builds/102018975

database.yml を以下のようにするだけでユニットテストを実行できるので、とても楽ちんです。
```yml
database:
    driver: pdo_sqlite
    memory: true
```

**Comment by nanasess** [comment]
#1393 で sqlite にも対応しましたのでクローズします。
