### ISSUE TITLE
composer 関係で時間がかかる / テストが遅い

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#861]
composer 系のインストールにも時間がかかるので、 ``prefer-dist`` も含め検討してもよいかもしれません。

**Comment by nobuhiko** [comment]
TravisであればCacheすることも出来るのかなと思いますが、その前にsudoをやめないとダメなんですよね
http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/

**Comment by ttsuru** [comment]
@nobuhiko 
そんな裏技が！
EC-CUBEのインストールをshellスクリプトから composer ＋ php製インストーラにした方が良さそうですね。

**Comment by nobuhiko** [comment]
CircleCI使うとそもそも倍ぐらい早い問題もあります、ただし不安定ですが。。
https://circleci.com/gh/nobuhiko/ec-cube/165

**Comment by chihiro-adachi** [comment]
#942 にてcomoserのキャッシュ処理について対応しましたので、本issueはクローズさせていただきます。
