### ISSUE TITLE
Swift Mailerから送信されたメールが一部のメールクライアントで文字化けする

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#862]
SwiftMailerでメール送信時はUTF-8を使用しているため、
メールクライアントによっては日本語が文字化けする。

参考
http://php-archive.net/php/swift-mailer/

**Comment by ttsuru** [comment]
conf か何かでメールの文字コードを指定できるようにした方がいいですよね。
iso-2022-jp を使うためには若干実装が必要です。

**Comment by k-yamamura** [comment]
@ttsuru 
そうですね。mail.ymlで文字コードを設定できるように修正します。

**Comment by nanasess** [comment]
最近は、「﨑」など iso-2022-jp-3 でないと表示できない文字を利用される方も増えているため、デフォルトは  UTF-8 だと嬉しいです。

**Comment by chihiro-adachi** [comment]
#985 で対応いただきましたのでクローズします。
