### ISSUE TITLE
path.yml のパスを相対パスに

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#864]
サイト移行の時や、 Windows Server の Web Deploy の障壁となるため。

**Comment by ttsuru** [comment]
path.yml ですが、ほとんどのパラメータはいらない子な気がします・・・
Symfony とかでは絶対パスで書かれているところは基本的にありません。

**Comment by okazy** [comment]
3.nではpath.ymlがなくなり、eccube.yamlにpath関連の定数は記述しています。
そちらでkernel.project_dirでpathを指定しているのでどの環境に行っても問題なく使えるようになっています。
