### ISSUE TITLE
【フロント画面マイページ－ご注文履歴】　リスト画面と詳細画面の購入商品の金額表示の違いについて

### ISSUE THREAD

**Issue by ActiveFusion** [EC-CUBE/ec-cube#867]
フロント画面マイページのご注文履歴で
「リスト画面」と「詳細画面」で購入した商品の金額表示が
リスト画面ですと「税別表示」で
詳細画面ですと「税込表示」の様なので
統一した方が良いと思います。

ご確認の程、よろしくお願い致します。

**Comment by ActiveFusion** [comment]
●解決方法
src\Eccube\Resource\template\default\Mypage\index.twig
の77行目を
<dd class="item_price">{{ OrderDetail.price|price }} ×{{ OrderDetail.quantity }}</dd>
から
<dd class="item_price">{{ OrderDetail.total_price|price }} ×{{ OrderDetail.quantity }}</dd>
へ修正。

**Comment by ActiveFusion** [comment]
一応、pull requestを送ってみましたが間違っていたらすいません。

よろしくお願い致します。

**Comment by Yangsin** [comment]
ご対応ありがとうございます。確認させていただきます。

**Comment by chihiro-adachi** [comment]
#868 で修正いただきましたので、closeします。
