### ISSUE TITLE
setApplication と setApp が混在している

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#869]
https://github.com/EC-CUBE/ec-cube/search?utf8=%E2%9C%93&q=setApp&type=Code
https://github.com/EC-CUBE/ec-cube/search?utf8=%E2%9C%93&q=setApplication&type=Code

setApplication() に統一した方が良いのではないか。

**Comment by Yangsin** [comment]
setApplication() に統一したほうがよいですね。

ServiceProviderからしか利用されない関数なので、既存のプラグイン等への影響もなく、マイナーでも可能な修正と見てます。

**Comment by nanasess** [comment]
Merged from #1220
