### ISSUE TITLE
エンティティのインスタンス生成について

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#870]
Repository と Service で、エンティティのインスタンス生成をしている箇所があるが、エンティティのコンストラクタで実装すれば良いと思われる。

https://github.com/EC-CUBE/ec-cube/search?utf8=%E2%9C%93&q=%22public+function+new%22&type=Code

あえて、 Repository や Service でインスタンス生成をする理由があれば、その旨のコメントを追加する.

**Comment by chihiro-adachi** [comment]
@nanasess 

以前いちど試みたのですが、

- Doctrineのentity manager経由のデータ取得
- FormTypeのview dataとmodel dataの変換

の挙動に影響ないかどうか検証しきれず、断念しました、、、
上記問題なければ、Entityで行うのが適切な気がします。

**Comment by nanasess** [comment]
手元の環境では問題なかったはずですので、テスト書いてみますね。

**Comment by xuelian311** [comment]
現状は問題は発生してないので、クローズいたします。
