### ISSUE TITLE
ブロックがレイアウトに設定されたページを削除するとシステムエラーが発生する。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#871]
以下の手順で、システムエラーが発生します。
1. ページを新規に作成し、レイアウト編集でブロックを設定する。
2. ページを削除する。

原因は dtb_block_position にある page_id の FK エラーが発生しているためです。

対処法としては、以下の 2点かなと思います。
* ページ削除時に dtb_block_position の該当ページを削除してから dtb_page_layout を削除する
* FK の ON DELETE オプションの RESTRICT をやめて CASCADE にする

2つ目の対処でよいかなと思いますが、いかがでしょうか。

**Comment by chihiro-adachi** [comment]
#901 にて対応いただきましたのでクローズします。
