### ISSUE TITLE
ブロック管理で登録されるファイルの保存先がdefault配下に保存される

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#874]
ブロック管理で登録する際にファイルの保存先がテンプレート管理で指定された保存先にファイルが保存されず、defaultに保存されてしまう。

別の課題としてテンプレートが変更された場合、
すでに作成されているブロックが使いまわせない。
→再編集すれば良い?

**Comment by Yangsin** [comment]
別の課題についてですが、
https://github.com/EC-CUBE/ec-cube/pull/688
で話されたように、テンプレートが変更される運用はいったん無視でよいかと。
ブロックファイルが見つからない場合もエラーで落ちないようにはなっていますので
必要であれば、テンプレートを変更した後にファイルをコピーしてくるでよいと思います。

**Comment by k-yamamura** [comment]
別の課題についてはその方針で対応で無視します。

指定された保存先にファイルが出来ないと同じく、
削除する時もdefaultを参照しにいくため対応する必要があります。
→defaultが固定になっているため。

**Comment by chihiro-adachi** [comment]
#1017 にて修正
