### ISSUE TITLE
初期インストール時のデータ投入を CSV ファイルに変更

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#876]
## 概要(Overview)

現在は、doctrine\migration にて、 ベタな INSERT 文を実行しているが、 CSV ファイルをロードするように変更することで、メンテナンス性の向上が期待できる。

また、他の RDBMS のサポートを考えると、 CSV ファイルの方が柔軟に対応できる

## 要望 (Requirement)

- [x] 初期インストールデータCSVにエクスポート
+ インストーラーでCSVからデータを登録する
	- [x] 実装方法を検討
		- [x] プロトタイプ実装 
		- [x] 作り込み
			- [x]  Doctrine DBAL or PDO のパフォーマンス検証（極端にDBALがおそくなければDBAL）
			- [x]  クラス整理
	- [x] フォルダにおいてあるCSVを読み込んでテーブルに書き込む
		- [x] Scheme作成後・マイグレーション前に実行される
		- [x] 1テーブル・1CSV、カラム順決め打ちで書き込まれる
		- [ ] Insert後にSequenceの更新
	- [x] 登録されたデータが正しく表示される
	- [x] DB毎にインポートするエンジンを切り替えれるようにする
        - [x] コマンドラインのinstall.phpから利用できなければならない
+ [ ] 一部のレンタルサーバーで利用できるか確認（ORMやDBのCSVローダーを利用すると動かないかも）
    - [x] さくらインターネット
    - [ ] Kagoya
    - [ ] ロリポップ
+ 初期インストール用を想定しているため以下のような条件で書き込みを行っていくのみ  
	- 入力チェックはしない
	- ORM利用しない
	- SQLServer,Oracleなどサポート外のDBは考慮しない
	- 3.0.xで初期データを登録しているテーブルのみ
+ app/console化は別検討

## 関連情報 (Ref)

**Comment by seasoftjapan** [comment]
:+1: 
2 系でも構想していて、バックアップ機能のデータと互換があると良いと考えていました。

**Comment by nanasess** [comment]
## Doctrine DBAL or PDO のパフォーマンス検証

- KEN_ALL.CSV(約12万件) の INSERT 時間を計測
- PHP7.0.14, MySQL5.6.32, Corei5 2.6GHz, SSD
- dbal(mysqli) は参考値

|  | pdo_mysql | dbal(pdo_mysql)   |     dbal(mysqli)        |
|-----------|-----------------|--------------|-------------|
| 1回目         | 8.511879921     | 7.62720108   | 8.336216927 |
| 2回目         | 7.297768116     | 7.342508078  | 8.009325981 |
| 3回目         | 7.346078873     | 8.096148968  | 7.542680025 |
| avg       | 7.718575637     | 7.688619375  | 7.962740978 |

誤差程度なので、 dbal を使用する方針で。

**Comment by nanasess** [comment]
PostgreSQL 用ですが、以下のようなスクリプトでインストーラ用の CSV を出力できます

```bash
#!/bin/sh

SQL=`cat<<EOF
SELECT  c.relname as "name"
FROM pg_catalog.pg_class c
--     LEFT JOIN pg_catalog.pg_user u ON u.usesysid = c.relowner
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','v')
      AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
      AND pg_catalog.pg_table_is_visible(c.oid)
      AND c.relname LIKE '%%'
ORDER BY 1;
EOF
`

EXPORT_PATH=`pwd`/src/Eccube/Resource/doctrine/import_csv
for TABLE in `psql -F, -t -A -c "${SQL}" -h localhost -U cube3_dev_user cube3_dev`
do
    echo "${TABLE}: "
    psql -c "COPY ${TABLE} TO '${EXPORT_PATH}/${TABLE}.csv' WITH CSV DELIMITER E',' FORCE QUOTE * NULL AS '' HEADER" -h localhost -U cube3_dev_user cube3_dev;
done
```

**Comment by nanasess** [comment]
[doctrine/data-fixtures](https://github.com/doctrine/data-fixtures) の拡張クラスを作成しました
https://github.com/nanasess/ec-cube/commit/367d79514991a9369e605f5e0e515db3d6eab9a4

**Comment by okazy** [comment]
実装済みのためクローズします。
