### ISSUE TITLE
カートに複数商品がある状態で、在庫数が下回った時にエラーがどの商品かがわからない

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#879]
カートに複数商品を入れた状態で、ある商品の在庫がカートの数量を下回った際にカート画面でエラーメッセージが表示されるが、どの商品がエラーの原因なのかがわからない。
また、エラーメッセージが1つしか出ないため、在庫を下回っているものや、購入制限数を下回っているものが複数あっても1つしか表示されず、ユーザビリティが悪い。

* CartService の<code>addError</code>ではなく、<code>setError</code>を使用しているためエラーメッセージが1つのみしか表示できない。
* エラーメッセージに商品名、規格名1、規格名2を記載したほうが良いのではないかと思います。

※PR #828 では<code>addError</code>を使用するようにしていたが、PR #850 で<code>setError</code>に書き変えているので、<code>addError</code>だと問題が発生する？

**Comment by chihiro-adachi** [comment]
#929 にて修正.
