### ISSUE TITLE
https で git clone --recursive すると失敗する場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#882]
docs の submodule が ssh になっているため、 https のみで `git clone --recursive` を実行すると失敗する。

ビギナー層が ssh の設定をするのは小々辛いものがあるので、submodule は https にした方が親切。

**Comment by chihiro-adachi** [comment]
#883 にて修正いただきましたので、クローズします。

httpsへの変更方法については、以下をご確認ください。

https://github.com/EC-CUBE/ec-cube/pull/883#issue-109823833
