### ISSUE TITLE
【質問】ブロック内でのjQuery使用について

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#884]
ブロック内で jQuery を使用して操作を行おうとしても、ブロックが表示される段階で jQuery が読み込まれていないため使用できない。

考えられる対応方法は
* ブロック内で、jQuery をロード
* jQuery のロードを&lt;/body&gt;直前ではなく、&lt;/head&gt;直前にする
* ブロック内でも {% block javascript %}～{% endblock %}を使用できるようにする

1つ目は、論外
2つ目は、その他のライブラリも同様になりそう（<code>$(function(){・・・});</code>があるから問題ないか？）
3つ目は、フレームワーク的にできるのか

となってしまい、現時点で有効な対応方法が思い浮かびません。（現時点では2つ目の対応をするしかないかと思っています。）
その他の解決策や、カスタマイズ方法の案があればご教授ください。（私でも対応できそうなら対応します。）

**Comment by k-yamamura** [comment]
こちらはプラグインで拡張する際にも問題となっておりましたので、
次のバージョンで2つ目の対応をします。
対応方法は、
``` src/Eccube/Resource/template/default/default_frame.twig ```
と
``` src/Eccube/Resource/template/admin/default_frame.twig ```
で記載されているjQueryの部分を</head>直前に修正します。

```
・src/Eccube/Resource/template/default/default_frame.twig

・
・
・
<link rel="stylesheet" href="{{ app.config.front_urlpath }}/css/default.css">
<!-- for original theme CSS -->
{% block stylesheet %}{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{ app.config.front_urlpath }}/js/vendor/jquery-1.11.3.min.js"><\/script>')</script>

{# ▼Head COLUMN #}
{% if PageLayout.Head %}
    {# ▼上ナビ #}
    {{ include('block.twig', {'Blocks': PageLayout.Head}) }}
    {# ▲上ナビ #}
{% endif %}
{# ▲Head COLUMN #}

</head>
・
・
・
```


```
・src/Eccube/Resource/template/admin/default_frame.twig

・
・
・
{% block stylesheet %}{% endblock %}
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{ app.config.admin_urlpath }}/assets/js/vendor/jquery-1.11.3.min.js"><\/script>')</script>
</head>
・
・
・
```

**Comment by shhirose** [comment]
@k-yamamura 
ご回答ありがとうございます。
master ブランチにはまだ上がっていないけれども 3.0.4 で対応されるという認識でよろしいでしょうか。

**Comment by k-yamamura** [comment]
@shhirose 
その認識で問題ございません。

**Comment by shhirose** [comment]
@k-yamamura 
ありがとうございました。
