### ISSUE TITLE
CategoryRepository::up(), down() で 1ずつしか rank 変更できない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#885]
以下のようなカテゴリがあった場合、

| ID | 親ID | name | level | rank |
| --- | --- | --- | --- | --- |
| 1 |  | 親1 | 1 | 1 |
| 2 | 1 | 子1 | 2 | 3 |
| 3 | 1 | 子2 | 2 | 4 |
| 4 |  | 親2 | 1 | 2 |
| 5 | 4 | 子3 | 2 | 5 |

CategoryRepository::save() を使用すると、以下のように **親3** が追加される

| ID | 親ID | name | level | rank |
| --- | --- | --- | --- | --- |
| 1 |  | 親1 | 1 | 1 |
| 2 | 1 | 子1 | 2 | 3 |
| 3 | 1 | 子2 | 2 | 4 |
| 4 |  | 親2 | 1 | 2 |
| 5 | 4 | 子3 | 2 | 5 |
| **6** |  | **親3** | **1** | **6** |

親3 を 親2 よりも下位の順序に並べ替えたい場合は、 CategoryRepository::down() を 4回コールしなくてはならない。

1回のコールで、同階層同士の順序変更をできるようにするべき。
### 参考
#881

**Comment by Yangsin** [comment]
すでに利用されていない関数のためクローズします。
