### ISSUE TITLE
MailTemplateRepository の member_id がベタ書き

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#894]
https://github.com/EC-CUBE/ec-cube/blob/74e60910e3c17dc1694e0fa593d56491427fccfd/src/Eccube/Repository/MailTemplateRepository.php#L43
- Member は引数で渡した方が良いと思われる
- 今のところ本体では使用していない模様

**Comment by trebla-on** [comment]
PR: https://github.com/EC-CUBE/ec-cube/pull/2027 で対応しました。
