### ISSUE TITLE
配送業者と支払方法の作成者が固定されてしまっている

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#895]
DeliveryRepository::findOrCreate() の member_id, product_type_id がベタ書き

https://github.com/EC-CUBE/ec-cube/blob/df6b1c4dbd32ef4a50f450ba90ad80beedcac6fc/src/Eccube/Repository/DeliveryRepository.php#L43
- Member、 ProductType は引数で渡した方が良いと思われる
- DeliveryController::edit() で使用しているため、配送業者の作成者が固定になってしまう

**Comment by nanasess** [comment]
PaymentRepository::findOrCreate() も同様。
PaymentController::edit() で使用しているため、支払方法の作成者が固定になってしまう

**Comment by trebla-on** [comment]
PR: https://github.com/EC-CUBE/ec-cube/pull/2026 で対応しました
