### ISSUE TITLE
FormTypeのrequiredオプションを設定ファイルで制御できるようにしたい

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#897]
FormTypeのrequiredオプションがtrueの場合、HTML5のrequired属性がレンダリングされるが、
設定ファイルか何かでrequired属性を付けたり付けなかったりの制御をできるようにしたい。

http://docs.symfony.gr.jp/symfony2/book/forms.html#required

**Comment by nanasess** [comment]
#1577 と重複していますのでクローズします
