### ISSUE TITLE
ご注文履歴画面で決済処理中と購入処理中が件数にカウントされている

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#911]
ご注文履歴画面では決済処理中と購入処理中は画面上に表示しない仕様なので表示されないのは合っているが、
件数に決済処理中と購入処理中の注文もカウントされている。

**Comment by geany-y** [comment]
再現せず
①会員で商品を2件購入
②管理画面/商品マスタから検索し、2件が「新規受付」ステータスになっているのを確認
③マイページを表示し、購入履歴が2件、カウントも2件を確認
④管理画面/商品マスタから2件中1件のステータスを、決済処理中に変更
⑤マイページを表示すると購入履歴が1件、カウントが1件とバグ再現せず
⑥④と同様処理でステータスを「購入処理中」に変更
⑦マイページは⑤と同様でバグ再現されず

**Comment by chihiro-adachi** [comment]
再現不可のため、本issueはクローズいたします。
