### ISSUE TITLE
dtb_class_name, dtb_class_category の name, rank が nullable: true になっている

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#913]
必須項目だと思われるので、 `nullable: false` が正しいと思われる

**Comment by t-nagahashi** [comment]
■現状の動き
こちら、分類/規格ともに編集時に、値なしで更新できてしまいます。
ただし、DBの値（category_name）はクリアされていませんでした。

その後、画面を再表示するとクリア前の値が表示されます。

○初期表示
![default](https://cloud.githubusercontent.com/assets/13776434/10625473/8f89091e-77de-11e5-97f3-8d1d36e68bf5.PNG)

○カテゴリ名をクリア→カテゴリを作成ボタン押下後
![default](https://cloud.githubusercontent.com/assets/13776434/10625479/a654becc-77de-11e5-9938-8de0256e0881.PNG)

○左側のメニューで、カテゴリ登録を押下
![3](https://cloud.githubusercontent.com/assets/13776434/10625490/b8d1a63c-77de-11e5-83c8-b2dd5e3f44a6.PNG)

**Comment by chihiro-adachi** [comment]
#1027 にて修正.
