### ISSUE TITLE
プラグイン一覧の独自プラグインでアップデートすると「入力されていません」というエラーが出る

### ISSUE THREAD

**Issue by Kakinaka** [EC-CUBE/ec-cube#915]
プラグイン一覧の独自プラグインでアップデートをクリックすると必ず「入力されていません」というエラーが出ます。

PluginManagementType.phpのplugin_idの必須チェックを外すと、ソースが更新できますので、この部分が問題かと思います。

**Comment by chihiro-adachi** [comment]
3.0.4にて修正済のため、クローズします。
