### ISSUE TITLE
クライアントリクエスト時と、Webサーバ受信時でURLが異なる場合、正常に動作しない。

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#916]
#650 からの派生

プロキシやロードバランサを挟んだ場合、正常に動作しない場合がある。
client <-(https)-> Proxy(or LB) <-(http)-> server
※https<->http や、ホスト名が異なる場合

HTTPS の強制

> コーディング規約
> - TwigからRouting定義されたURLを取得する際は、{{ url('route_name') }} をつかう
>   - HTTPSを確実にコントロールするため
> 
> @ttsuru 
> HTTPSにするのはSymfonyのFirewallで自動的にリダイレクトさせられます。

画像系

> @ttsuru 
> あと、画像系のAssetComponentの利用も含めて検討してもいいのではないでしょうか。
> http://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component
> 
> 2.7以上用のSilexのAsset providerもありました。
> https://github.com/MatTheCat/silex-asset-provider
> 
> @k-yamamura 
> 画像系もCDNを使ったりで似たような問題が出てきそうなので、
> Assetに置き換えていきたいですね。

以上を検討する。

**Comment by nanasess** [comment]
> HTTPSにするのはSymfonyのFirewallで自動的にリダイレクトさせられます。

http://ec-cube.github.io/ などにサンプルコードがあると良いと思います。

**Comment by nanasess** [comment]
根本的には、 アプリケーション内部では `$app->path()` を使用し、 https:// を強制したい場合は、 Webサーバー側など、上位のレイヤーで処理するのが正しいと思われます。

**Comment by nanasess** [comment]
参考
https://gitter.im/EC-CUBE/ec-cube?at=567a7c310199d70069df6e8f
