### ISSUE TITLE
【不具合　報告】商品詳細画面から「カートに入れる」を押した場合の挙動について

### ISSUE THREAD

**Issue by ActiveFusion** [EC-CUBE/ec-cube#918]
ブラウザを新規に起動して、「商品詳細画面」から「カートに入れる」ボタンを押して、「カート画面」に遷移した時商品がカート画面に登録されない不具合があります。

●細かな手順
１．PC等でブラウザが起動していない状況
２．ブラウザを新規に起動
３．EC-CUBEの商品詳細画面を表示（例：http://demo3.ec-cube.net/products/detail/27）
４．商品詳細画面から「カートに入れる」を押して、「カート画面」に遷移
５．「カート画面」に商品詳細画面でカートに入れた商品が追加されていない

という状況です。

ご確認の程、よろしくお願い致します。

**Comment by ActiveFusion** [comment]
●原因について
問題点として、session cookieの「cookie_path」値の問題でした。
「cookie_path」の値をapp/config/eccube/path.ymlの「root_urlpath」項目を取得していますが、
初期インストール時は「root_urlpath: 」になっておりました。

●応急処置について
これを、「root_urlpath: /」に修正して対応しました。

**Comment by chihiro-adachi** [comment]
@ActiveFusion
ありがとうございます。#671 で修正されているため、次バージョンにて反映されます。
