### ISSUE TITLE
【ショップマスター】郵便番号の必須入力に関するエラーが表示されない

### ISSUE THREAD

**Issue by h-kida** [EC-CUBE/ec-cube#932]
住所の「郵便番号」が未入力の場合、基本情報の保存に失敗するが、入力を促すメッセージが表示されていない。
現状では、「郵便番号」が未入力の場合、どの項目でエラーが発生しているか分かりづらいので、エラーの表記があった方が良いかと思います。

**Comment by h-kida** [comment]
すみません。こちら改善されておりました。

**Comment by chihiro-adachi** [comment]
masterにて修正済のため、、クローズいたします。ありがとうございます。
