### ISSUE TITLE
【会員登録・編集】エラー時の表示がない項目がある

### ISSUE THREAD

**Issue by sf-tuji** [EC-CUBE/ec-cube#933]
[EC-CUBE] 3.0.4 
[PHP]   5.4.43
[データベース]    PostgreSQL 9.3.9
[WEBサーバ]  Apache
[ブラウザ]  FireFox41.0.1
[現象]   
■再現手順
1. 郵便番号、電話番号、FAX番号に「a」を設定する
![2015-10-09_172931](https://cloud.githubusercontent.com/assets/9459909/10389335/9546d89a-6eab-11e5-8359-e8a53f09132a.png)
![2015-10-09_172945](https://cloud.githubusercontent.com/assets/9459909/10389337/97571992-6eab-11e5-894f-2e2b1fd7e74d.png)
2. 「会員情報を登録」ボタンを押下する

■現象
・メールアドレスや生年月日のようにエラーメッセージが表示されませんでした。
・「登録できませんでした」のメッセージが表示されない

**Comment by casek** [comment]
こちら再現しようとしたところ、、、（管理画面ですよね？）

* 電話番号／FAX番号は「数字で入力してください」とエラーメッセージが表示されました
* ただ、電話番号/FAX番号にそれぞれ1桁の数字を入れるとエラーメッセージ表示されません
* 郵便番号については数字以外を入れても、1桁の数字を入れてもエラーメッセージは表示されません（ご指摘のとおりの挙動）
* さらに、invalidなデータのまま「会員情報を登録」をクリックしても登録できなかった旨のエラーメッセージは表示されない（ご指摘の通り）

ということで、それぞれ文字種／桁数などのvalidationがどうなってるかと、登録エラーメッセージの件、チェックして、修正します’。

**Comment by chihiro-adachi** [comment]
#1003 にて修正.
