### ISSUE TITLE
在庫「0」の場合に非表示の設定がymlとDBにある

### ISSUE THREAD

**Issue by shhirose** [EC-CUBE/ec-cube#935]
constant.yml.dist に nostock_hidden の項目があり、データベースにも dtb_base_info に同様のカラムがあります。
ProductController では yml の方を使用しているようですが、ショップマスターでデータベースの設定変更が実装されています。

管理画面から変更できる機能があるので、データベースの方を残す形でよいですか？

**Comment by chihiro-adachi** [comment]
はい、3.0.0でショップマスターで設定できるようになりましたので、データベースの方を残すで問題ありません。

**Comment by chihiro-adachi** [comment]
#949で対応いただきましたのでクローズします。
