### ISSUE TITLE
CustomerRepository の問題点

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#945]
- [X] #869 の課題あり
- [X] CustomerStatus にマジックナンバーが使用されている( #999 で修正済み)
- [x] CustomerRepository::getActiveCustomerByEmail() は loadUserByUsername() と機能が重複している？
- [X] 引数に $app を渡す必要がないはずなのに、渡している( #999 で修正済み)
  - getUniqueSecretKey()
  - getUniqueResetKey()
  - encryptPassword()
- [x] 乱数生成に md5(), rand() を使用しているが、信頼性が低いので hash_hmac(), st_rand() を使用するべき
- [ ] getQueryBuilderBySearchData() の問題
  - kana01, kana02 が nullable: true となっているが、どちらか一方が null だと検索にヒットしない
  - 金額を検索するフィールドで、 0 が無視される

**Comment by nanasess** [comment]
> kana01, kana02 が nullable: true となっているが、どちらか一方が null だと検索にヒットしない

以下のような CASE 文は、 Doctrine で使用できない模様。独自拡張を作成するか、修正を諦めるしかないかも

```php
        // kana
        if (isset($searchData['kana']) && StringUtil::isNotBlank($searchData['kana'])) {
            $qb
                ->andWhere('(CASE WHEN (o.kana01 IS NULL) THEN o.kana02 LIKE :kana
                                 WHEN (o.kana02 IS NULL) THEN o.kana01 LIKE :kana
                                 ELSE CONCAT(o.kana01, o.kana02) LIKE :kana
                            END)')
                ->setParameter('kana', '%'.$searchData['kana'].'%');
        }
```

**Comment by chihiro-adachi** [comment]
残課題のみ、#5351 へ移動。
