### ISSUE TITLE
会員登録時の購入回数、 購入金額

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#946]
会員登録時、購入回数、購入金額の初期値が null になっているが、 0 で初期化しないと管理画面の検索にヒットしない

#945 に関連。 検索条件で頑張るより、 会員登録時に、きちんと初期化するべきだと思われますので別で issues 登録します。

**Comment by chihiro-adachi** [comment]
#1000 にて対応.

**Comment by ttsuru** [comment]
こちら、初期化はEntity側で行ったほうがよい気がします。

**Comment by nanasess** [comment]
関連 #700
