### ISSUE TITLE
商品一覧の価格順ソート

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#958]
2系では、価格昇順となっていましたが、3系では降順となっているようです。
本来は、昇順/降順の切替ができたら良いですが、現状の仕様では、2系と同じ昇順としておいた方が良いと思います。

**Comment by nanasess** [comment]
#954 で対応いただいていると思いますが、新着順の実装も `dtb_product.create_date` 降順が正しいです。

**Comment by chihiro-adachi** [comment]
#1009 #1045 にて対応.
