### ISSUE TITLE
ブランチの切り方について

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube#959]
3.0.4-dev と master がありますが、 3.0.4-dev はどのような意味があるのでしょうか。
例えば、3.0の開発ブランチで3.0-dev、3.1以降も含めた最新ブランチのmasterといった形ならわかりやすいと思いますが、リリース用のマイナーバージョンのブランチがあるのは不自然ではないでしょうか。

**Comment by chihiro-adachi** [comment]
@ttsuru 消し忘れですね、すみません。3.0.4-devは急ぎで3.0.4をリリースする必要があり、一時的に作成したブランチです。現在は役目を終えましたし、混乱の元になるので削除しますね。

**Comment by ttsuru** [comment]
@chihiro-adachi 
回答ありがとうございます。
closeします。
