### ISSUE TITLE
プラグインで利用できるフックポイントと実行順序

### ISSUE THREAD

**Issue by shinichi-takahashi** [EC-CUBE/ec-cube#96]
DocumentとしてFIXしてしまう前に、現在開発しているプラグインのフックポイントと、その実行順序について、覚書程度に記載します。

### フックポイントの命名規則

`eccube.event.*.(before|after|finish)`  

### 現時点で、自動生成もしくは定義されているフックポイント一覧

* `eccube.event.app.before`
* `eccube.event.app.after`
* `eccube.event.controller.ROUTE.before`
* `eccube.event.controller.ROUTE.after`
* `eccube.event.controller.ROUTE.finish`
* `eccube.event.render.before`
    + `$app['view']->render()` のときにEventが走る。
    + 引数のEventObjectを利用することで、ソースコードを自由に触れる用にしてある

`ROUTE` は、 `$request->attributes->get('_route')` で取得できる、ルーティング名  
`->bind('ここ')`

### 実行順序

1. `eccube.event.app.before`
2. `eccube.event.controller.ROUTE.before`
3. `eccube.event.render.before`
4. `eccube.event.controller.ROUTE.after`
5. `eccube.event.app.after`
6. `eccube.event.controller.ROUTE.finish`

同一のフックポイントを利用している場合は、EventSubscriberで定義した優先順位による

### これから実装するところ

* 各Form\Type

**Comment by Yangsin** [comment]
https://github.com/EC-CUBE/ec-cube/wiki/Plugin%E3%81%A7%E5%88%A9%E7%94%A8%E3%81%A7%E3%81%8D%E3%82%8B%E3%83%95%E3%83%83%E3%82%AF%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88
に移してクローズします。
