### ISSUE TITLE
【管理画面】ファイル管理でのファイルダウンロード時のエラー

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#963]
version 3.0.3
PostgreSQL環境

対象ユースケース：EA0601-UC01,EA0602-UC01,EA0603-UC01,EA0604-UC01
番号：EA0602-UC01-T02

ファイル管理でファイル一覧から"ダウンロード"ボタンを押下する
→クリックするとシステムエラーになる。

ファイルがダウンロードされる
→クリックするとシステムエラーになる。

**Comment by chihiro-adachi** [comment]
#952 #1186 にて修正済のためクローズします。
