### ISSUE TITLE
【管理画面】支払方法削除時の確認ポップアップ

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#964]
version 3.0.3
PostgreSQL環境

対象ユースケース：EA0701-UC01,EA0702-UC01,EA0703-UC01,EA0704-UC01,EA0704-UC02,EA0704-UC03,EA0705-UC01,EA0705-UC02,EA0706-UC01,EA0706-UC02,EA0706-UC03,EA0707-UC01,EA0707-UC02,EA0708-UC01,EA0709-UC01,EA0709-UC02,EA0710-UC01
番号：EA0704-UC03-T01

支払方法削除前に確認のポップアップが無い

**Comment by chihiro-adachi** [comment]
3.0.4で確認のアラートができるようになりました。
