### ISSUE TITLE
【管理画面】特定商取引法の設定（予備1〜4の編集方法）

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#966]
version 3.0.3
PostgreSQL環境

対象ユースケース：EA0701-UC01,EA0702-UC01,EA0703-UC01,EA0704-UC01,EA0704-UC02,EA0704-UC03,EA0705-UC01,EA0705-UC02,EA0706-UC01,EA0706-UC02,EA0706-UC03,EA0707-UC01,EA0707-UC02,EA0708-UC01,EA0709-UC01,EA0709-UC02,EA0710-UC01
番号：EA0702-UC01-T01

公開画面の「特定商取引法に基づく表記」ページ下部に、
予備1〜4の項目があるが、管理画面での編集ができない

**Comment by nanasess** [comment]
#766 での話題ですかね。

**Comment by chihiro-adachi** [comment]
#766,#851 にて、予備項目については削除されました。
