### ISSUE TITLE
【管理画面】ファイル管理のフォルダ表示

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#968]
version 3.0.3
MySQL環境

対象ユースケース：EA0601-UC01,EA0601-UC02,EA0601-UC03,EA0601-UC04,EA0602-UC01,EA0603-UC01,EA0604-UC01
番号：EA0602-UC01-T06

ファイル名一覧に「…」が表示される

**Comment by chihiro-adachi** [comment]
表示する条件が逆になっている
トップディレクトリで表示され、下層ディレクトリで表示されていない

**Comment by chihiro-adachi** [comment]
#1006 にて対応.
