### ISSUE TITLE
【管理画面】ページ管理（新規作成、編集）登録完了後の遷移先

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#969]
version 3.0.3
MySQL環境

対象ユースケース：EA0601-UC01,EA0601-UC02,EA0601-UC03,EA0601-UC04,EA0602-UC01,EA0603-UC01,EA0604-UC01
番号：EA0603-UC01-T01,EA0603-UC01-T02

登録完了後、他のページとインターフェースをそろえるのであれば、一覧画面に遷移した方がよい？

**Comment by nanasess** [comment]
#1620 で対応しています

**Comment by ryo-endo** [comment]
#1620 取り込みました。
