### ISSUE TITLE
【管理管理】ブロック管理（新規作成、編集）登録完了後の遷移先

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#970]
version 3.0.3
MySQL環境

対象ユースケース：EA0601-UC01,EA0601-UC02,EA0601-UC03,EA0601-UC04,EA0602-UC01,EA0603-UC01,EA0604-UC01
番号：EA0604-UC01-T01,EA0604-UC01-T02

登録完了後、他のページとインターフェースをそろえるのであれば、一覧画面に遷移した方がよい？

**Comment by okazy** [comment]
3.nでは以下の方針で統一しています。
- 運用系は編集画面に留まる
  - 商品管理、会員管理、コンテンツ管理など
- 設定系は一覧画面に戻る
  - 配送方法設定、支払い方法設定など
