### ISSUE TITLE
【管理管理】ブロック管理で追加したブロックを設置すると公開側がエラー

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#971]
version 3.0.3
MySQL環境

対象ユースケース：EA0601-UC01,EA0601-UC02,EA0601-UC03,EA0601-UC04,EA0602-UC01,EA0603-UC01,EA0604-UC01
番号：EA0604-UC01-T01,EA0604-UC01-T02

ブロック管理で追加したブロックを、ページレイアウトに設置すると、設置した公開側の画面がシステムエラーとなる

**Comment by Yangsin** [comment]
3.0.4で修正済みのためクローズします。
