### ISSUE TITLE
【管理管理】特定商取引法の設定画面の他の画面との挙動違い

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#972]
version 3.0.3
MySQL環境

対象ユースケース：EA0701-UC01,EA0702-UC01,EA0703-UC01,EA0704-UC01,EA0704-UC02,EA0704-UC03,EA0705-UC01,EA0705-UC02,EA0706-UC01,EA0706-UC02,EA0706-UC03,EA0707-UC01,EA0707-UC02,EA0708-UC01,EA0709-UC01,EA0709-UC02,EA0710-UC01
番号：EA0702-UC01-T01

ショッップマスターの方は登録ボタンを押すとすべてのフィールドについてエラーチェックが行われるが、ここはひとつのフィールドずつしか行われていない

また他のページにある郵便番号から住所を自動入力する機能がない

**Comment by okazy** [comment]
3.nでは管理画面がなくなり、静的ページとなったため、問題は発生しなくなりました。
