### ISSUE TITLE
【管理管理】配送方法一覧の順序入れ替え

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#973]
version 3.0.3
MySQL環境

対象ユースケース：EA0701-UC01,EA0702-UC01,EA0703-UC01,EA0704-UC01,EA0704-UC02,EA0704-UC03,EA0705-UC01,EA0705-UC02,EA0706-UC01,EA0706-UC02,EA0706-UC03,EA0707-UC01,EA0707-UC02,EA0708-UC01,EA0709-UC01,EA0709-UC02,EA0710-UC01
番号：EA0706-UC02-T01

ドラッグ＆ドロップでも同様の操作が可能だが、そうできることが分かりにくい

**Comment by okazy** [comment]
3.nでは矢印がついて順序入れ替え操作がわかりやすくなりました。
