### ISSUE TITLE
【管理管理】メールテンプレートの追加

### ISSUE THREAD

**Issue by Yammy** [EC-CUBE/ec-cube#974]
version 3.0.3
MySQL環境

対象ユースケース：EA0701-UC01,EA0702-UC01,EA0703-UC01,EA0704-UC01,EA0704-UC02,EA0704-UC03,EA0705-UC01,EA0705-UC02,EA0706-UC01,EA0706-UC02,EA0706-UC03,EA0707-UC01,EA0707-UC02,EA0708-UC01,EA0709-UC01,EA0709-UC02,EA0710-UC01
番号：EA0709-UC01-T01

プルダウンでメールテンプレートを選択できるが、メールテンプレート自体の追加方法が分からない

**Comment by ActiveFusions** [comment]
メールテンプレート機能拡張プラグイン（https://www.ec-cube.net/products/detail.php?product_id=1011）
にてメールテンプレートの機能拡張を行っていますので、よろしかったらご利用ください！
