### ISSUE TITLE
OrderRepository の問題点

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#980]
- ~このクラスだけ setApplication() ではなく、 setConfig()~
- ~getQueryBuilderBySearchData(), getQueryBuilderBySearchDataForAdmin() は項目の大半が重複している。抽象化可能~
    - getQueryBuilderBySearchData() は使用していないので削除する
- ~getQueryBuilderBySearchData() の order_date_start, order_date_end は dtb_order.create_date を参照している。正しくは dtb_order.order_date~
- #945 のカナと金額について、同様の問題がある
- ~getNew() は、「新規受付一覧の取得」となっているが、キャンセルのみを除外している~

**Comment by chihiro-adachi** [comment]
残課題のみ、#5351 へ移動
