### ISSUE TITLE
【バグ/管理画面>システム設定>メンバー管理】メンバーの並び替えの「下」が「上」に並び替え

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/ec-cube#989]
[PHP]   Vagrant開発環境
[データベース]    Vagrant開発環境
[WEBサーバ]  Vagrant開発環境
[ブラウザ]  Chromer( バージョン 45.0.2454.101 m )
[現象]    
主題件、画面でメンバーを任意の数登録し、メンバーの並び替えのために、
「サブメニュー>下」をクリックすると押下したメンバーが「上」に移動する
※「サブメニュー>上」は正常に動作

**Comment by chihiro-adachi** [comment]
#991 にて対応いただきましたのでクローズします。
