### ISSUE TITLE
【バグ】商品規格で通常価格が空白に設定可能+保存できない項目有⇒エラー発生

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#995]
開発フォーラムで投稿がありました。
動作確認しましたが同様にエラーが発生しました。

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=16473&post_id=72902&order=0&viewmode=flat&pid=72784&forum=12#forumpost72902

**Comment by chihiro-adachi** [comment]
以下で対応しました。ver 3.0.5で反映されます。
#708
#898
