### ISSUE TITLE
【改善要望】DBの設定を事前に設定ファイル記述済の場合、インストール時スキップor自動入力してほしい

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#996]
開発コミュニティにこちらの要望があがっておりましたので、
issueに転記します。

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=flat&order=ASC&topic_id=16465&forum=14

**Comment by nanasess** [comment]
#1334 で対応いただきましたのでクローズします
